CALL "%DYNAMICRESOURCEPATH%\dynamicitemlistuse.bat"
SET /a SELECTED = 1
:START
SET /a BACK = 0
IF %OPTIONTOT% EQU 0 (
	ECHO You don't have any items to use
	CALL :WAITFORTWO
	SET /a BACK = 1
	GOTO :EOF
)
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO Choose the item you wish to use
ECHO.
CALL "%MISCRESOURCEPATH%\menu2.bat"
IF %VARSELECTED% EQU 1 (
	CALL :SELECTED
)
IF %BACK% EQU 1 (
	GOTO :EOF
)
IF %VARSELECTED% EQU 1 (
	GOTO :EOF
) ELSE (
	GOTO :START
)

:SELECTED
CALL :SETSTATICID
SET /a PLAYERCUSTOMITEM = 0
GOTO :EOF

:SETSTATICID
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT% + 1
IF /I "!ITEM%COUNT%NAME!" EQU "!TEXT%SELECTED%NAME1!" (
	SET /a PLAYERITEMCHOICE = %COUNT%
	GOTO :EOF
)
GOTO :LOOPSTART



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
