:CHOOSEMAGICCUST
IF EXIST "%CUSTOMITEMRESOURCEPATH%\Temp\customitemlist.bat" (
	CALL "%CUSTOMITEMRESOURCEPATH%\Temp\customitemlist.bat"
)
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO Choose the Item you wish to use
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
IF DEFINED ITEMSLOT%COUNT%NAME (
	ECHO. %COUNT% - !ITEMSLOT%COUNT%NAME!
)
IF %COUNT% LSS 9 (
	GOTO :LOOPSTART
) 
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P ITEMCUSTCHOICE=
ECHO.
IF "%ITEMCUSTCHOICE%" EQU "" (
	GOTO :CHOICE
)
IF %ITEMCUSTCHOICE% EQU 0 (
	SET /a BACK = 1
	GOTO :EOF
) ELSE IF %ITEMCUSTCHOICE% GTR 9 (
	GOTO :CHOICE
) ELSE IF %ITEMCUSTCHOICE% LSS 0 (
	GOTO :CHOICE
)
IF %ITEMCUSTCHOICE% GTR 0 (
	IF %ITEMCUSTCHOICE% LEQ 9 (
		IF EXIST "%CUSTOMITEMRESOURCEPATH%\Temp\customitem%ITEMCUSTCHOICE%.bat" (
			SET /a PLAYERCUSTOMITEM = 1
		) ELSE (
			GOTO :CHOICE
		)
	)
)
SET /a AUTOBATTLE = 0
GOTO :EOF






:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

