SET /a TEMP = 0
SET /a COUNT=0
:STARTLOOPSTART
SET /a COUNT=%COUNT%+1
IF !PLAYERSKILL%COUNT%ENABLED! EQU 1 (
	SET /a TEMP = %TEMP% + 1
)
IF %COUNT% LSS %SKILLTOT% (
	GOTO :STARTLOOPSTART
)
IF %TEMP% GTR 10 (
	SET TEMP1=APCOST
	SET TEMP2=Descriptions
	CALL "%DYNAMICRESOURCEPATH%\dynamicskillchoose2.bat"
	CALL :START2
	GOTO :EOF
)
CALL "%DYNAMICRESOURCEPATH%\dynamicskillchoose.bat"
SET /a SELECTED = 1
:START
SET /a BACK = 0
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
IF %OPTIONTOT% EQU 0 (
	ECHO You don't have any skills
	CALL :WAITFORTWO
	SET /a BACK = 1
	GOTO :EOF
)
ECHO Choose the skill you wish to use
ECHO.
CALL "%MISCRESOURCEPATH%\menu2.bat"
IF %VARSELECTED% EQU 1 (
	CALL :SELECTED
)
IF %BACK% EQU 1 (
	GOTO :EOF
)
IF %VARSELECTED% EQU 1 (
	GOTO :EOF
) ELSE (
	GOTO :START
)

:SELECTED
CALL :SETSTATICID
GOTO :EOF

:SETSTATICID
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT% + 1
IF /I "!SKILL%COUNT%NAME!" EQU "!TEXT%SELECTED%NAME1!" (
	SET /a SKILLCHOICE = %COUNT%
	GOTO :EOF
)
GOTO :LOOPSTART

:START2
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO Choose the skill you wish to use
ECHO.
SET /a COUNT = 0
:LOOP2
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = 30 - !DYNAMICSKILL%COUNT%NAMELENGTH!
IF %COUNT% GEQ 10 (
	SET /a SPACENUM = %SPACENUM% - 1
)
IF %TEMP1% EQU APCOST (
	ECHO. %COUNT% - !DYNAMICSKILL%COUNT%NAME!!SPACES%SPACENUM%!!DYNAMICSKILL%COUNT%%TEMP1%! AP
) ELSE (
	ECHO. %COUNT% - !DYNAMICSKILL%COUNT%NAME!!SPACES%SPACENUM%!!DYNAMICSKILL%COUNT%%TEMP1%!
)
IF %COUNT% LSS %DYNAMICSKILLTOT% (
	GOTO :LOOP2
) 
ECHO. D - Skill %TEMP2%
ECHO. 0 - Back
ECHO.
SET /P DYNAMICCHOICE=
IF "%DYNAMICCHOICE%" EQU "" (
	GOTO :START2
) ELSE IF "%DYNAMICCHOICE%" EQU "0" (
	SET /a BACK = 1
	GOTO :EOF
) ELSE IF /I "%DYNAMICCHOICE%" EQU "D" (
	CALL :CHANGE
	GOTO :START2
)
IF %DYNAMICCHOICE% GTR %DYNAMICSKILLTOT% (
	GOTO :START2
) ELSE IF %DYNAMICCHOICE% LSS 0 (
	GOTO :START2
)
CALL :SETSTATICID2
GOTO :EOF


:SETSTATICID2
SET /a COUNT = 0
:LOOP2START
SET /a COUNT = %COUNT% + 1
IF /I "!SKILL%COUNT%NAME!" EQU "!DYNAMICSKILL%DYNAMICCHOICE%NAME!" (
	SET /a SKILLCHOICE = %COUNT%
	GOTO :EOF
)
GOTO :LOOP2START

:CHANGE
IF %TEMP1% EQU APCOST (
	SET TEMP1=DESCRIPTION
	SET TEMP2=AP Costs
) ELSE IF %TEMP1% EQU DESCRIPTION (
	SET TEMP1=APCOST
	SET TEMP2=Descriptions
)
GOTO :EOF

:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF