:CHOOSEMAGICCUST
IF EXIST "%CUSTOMSPELLRESOURCEPATH%\Temp\customspelllist.bat" (
	CALL "%CUSTOMSPELLRESOURCEPATH%\Temp\customspelllist.bat"
)
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO Choose the Spell you wish to cast (Current MP %PLAYERMP%)
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
IF DEFINED SPELLSLOT%COUNT%NAME (
	CALL :DISPLAY
)
IF %COUNT% LSS 9 (
	GOTO :LOOPSTART
) 
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P MAGICCUSTCHOICE=
ECHO.
IF "%MAGICCUSTCHOICE%" EQU "" (
	GOTO :CHOICE
)
IF %MAGICCUSTCHOICE% EQU 0 (
	SET /a BACK = 1
	GOTO :EOF
) ELSE IF %MAGICCUSTCHOICE% GTR 9 (
	GOTO :CHOICE
) ELSE IF %MAGICCUSTCHOICE% LSS 0 (
	GOTO :CHOICE
)
IF EXIST "%CUSTOMSPELLRESOURCEPATH%\Temp\customspell%MAGICCUSTCHOICE%.bat" (
	CALL "%CUSTOMSPELLRESOURCEPATH%\Temp\customspell%MAGICCUSTCHOICE%.bat"
	SET /a CUSTOMSPELLSCASTCOUNT = %CUSTOMSPELLSCASTCOUNT% + 1
) ELSE (
	GOTO :CHOICE
)
GOTO :EOF

:DISPLAY
SET /a SPACESMAX = 38
SET /a SPACENUM = %SPACESMAX% - !SPELLSLOT%COUNT%NAMELENGTH!
ECHO. %COUNT% - !SPELLSLOT%COUNT%NAME!!SPACES%SPACENUM%!!SPELLSLOT%COUNT%MPCOST! MP
GOTO :EOF




:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

