CALL "%DYNAMICRESOURCEPATH%\dynamicitemlistuse2.bat"
SET DISPLAYVAR=NUM
SET DISPLAYVARDISPLAY=Descriptions
:START
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO Choose the item you wish to use
ECHO.
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = 34-!DYNAMICITEM%COUNT%NAMELENGTH!
IF %COUNT% GEQ 10 (
	SET /a SPACENUM = %SPACENUM% - 1
)
ECHO. %COUNT% - !DYNAMICITEM%COUNT%NAME!!SPACES%SPACENUM%!!DYNAMICITEM%COUNT%%DISPLAYVAR%!
IF %COUNT% LSS %OPTIONTOT% (
	GOTO :LOOP
)
ECHO. D - %DISPLAYVARDISPLAY%
ECHO. 0 - Back
ECHO.
SET /P DYNAMICCHOICE=
IF "%DYNAMICCHOICE%" EQU "" (
	GOTO :START
) ELSE IF "%DYNAMICCHOICE%" EQU "0" (
	SET /a BACK = 1
	GOTO :EOF
) ELSE IF /I "%DYNAMICCHOICE%" EQU "D" (
	CALL :CHANGE
	GOTO :START
)
IF %DYNAMICCHOICE% GTR %DYNAMICSKILLTOT% (
	GOTO :START
) ELSE IF %DYNAMICCHOICE% LSS 0 (
	GOTO :START
)
IF %BACK% EQU 1 (
	GOTO :EOF
)
CALL :SETSTATICID
GOTO :EOF

:SETSTATICID
SET /a COUNT = 0
SET /a PLAYERCUSTOMITEM = 0
:LOOPSTART
SET /a COUNT = %COUNT% + 1
IF /I "!ITEM%COUNT%NAME!" EQU "!DYNAMICITEM%DYNAMICCHOICE%NAME!" (
	SET /a PLAYERITEMCHOICE = %COUNT%
	GOTO :EOF
)
GOTO :LOOPSTART

:CHANGE
IF %DISPLAYVAR% EQU NUM (
	SET DISPLAYVAR=DESCRIPTION
	SET DISPLAYVARDISPLAY=Number Remaining
) ELSE IF %DISPLAYVAR% EQU DESCRIPTION (
	SET DISPLAYVAR=NUM
	SET DISPLAYVARDISPLAY=Descriptions
)
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
