:CHOOSEMAGICTYPE
SET /a BACK = 0
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
IF %AUTOBATTLE% EQU 1 (
	IF %MEMORYAUTOBATTLE% EQU 1 (
		CALL :CHOICEEND
		GOTO :EOF
	)
)
ECHO Which Type of Magic would you like to use?
ECHO.
ECHO. 1 - Offensive
ECHO. 2 - Status Ailments
ECHO. 3 - Restorative
ECHO. 4 - Support
ECHO. 5 - Custom
ECHO. 0 - Back
ECHO.
:MAGICTYPE
SET /P MAGICTYPE=
ECHO.
:CHOICEEND
IF "%MAGICTYPE%" EQU "1" (
	SET TYPE=OFF
	CALL "%BATTLECHOICERESOURCEPATH%\choosemagic.bat"
) ELSE IF "%MAGICTYPE%" EQU "2" (
	SET TYPE=STAT
	CALL "%BATTLECHOICERESOURCEPATH%\choosemagic.bat"
) ELSE IF "%MAGICTYPE%" EQU "3" (
	SET TYPE=REST
	CALL "%BATTLECHOICERESOURCEPATH%\choosemagic.bat"
) ELSE IF "%MAGICTYPE%" EQU "4" (
	SET TYPE=SUPP
	CALL "%BATTLECHOICERESOURCEPATH%\choosemagic.bat"
) ELSE IF "%MAGICTYPE%" EQU "5" (
	CALL "%BATTLECHOICERESOURCEPATH%\choosemagiccust.bat"
) ELSE IF "%MAGICTYPE%" EQU "0" (
	SET /a BACK = 1
	GOTO :EOF
) ELSE (
	GOTO :MAGICTYPE
)
IF %BACK% EQU 1 (
	GOTO :CHOOSEMAGICTYPE
)
GOTO :EOF







:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
