:ENEMYSPELLCHOOSE
CALL :SETSPELL
CALL :SPELLSTATS
CALL :INTELLIGENCEQUERY
GOTO :EOF

:SETSPELL
SET /a ENEMYSPELLCHOICETEMP=(%RANDOM% %% !ENEMY%ENEMYID%%ENEMYSPELLTYPE%SPELLNUM!)+1
SET /a ENEMYSPELLCHOICE = !ENEMY%ENEMYID%%ENEMYSPELLTYPE%SPELL%ENEMYSPELLCHOICETEMP%!
GOTO :EOF

:SPELLSTATS
SET ENEMYSPELLNAME=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%SPELL!
SET /a ENEMYSPELLACCURACY = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%ACCURACY!
SET /a ENEMYSPELLMPCOST = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%MPCOST!
SET /a ENEMYSPELLREFLECTABLE = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%REFLECTABLE!
SET /a ENEMYSPELLEFFECTSNUM = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECTSNUM!
SET ENEMYSPELLANIMATION=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%ANIMATION!
SET /a EFFECTNUM = 0
:LOOP1START
SET /a EFFECTNUM = %EFFECTNUM% + 1
SET ENEMYSPELLEFFECT%EFFECTNUM%ELEMENT=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%ELEMENT!
SET ENEMYSPELLEFFECT%EFFECTNUM%TYPE=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%TYPE!
SET ENEMYSPELLEFFECT%EFFECTNUM%ATTRIBUTE=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%ATTRIBUTE!
SET ENEMYSPELLEFFECT%EFFECTNUM%TARGET=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%TARGET!
SET /a ENEMYSPELLEFFECT%EFFECTNUM%AMOUNT = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%AMOUNT!
SET /a ENEMYSPELLEFFECT%EFFECTNUM%FIXEDAMOUNT = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%FIXEDAMOUNT!
SET /a ENEMYSPELLEFFECT%EFFECTNUM%MINTURNCOUNT = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%MINTURNCOUNT!
SET /a ENEMYSPELLEFFECT%EFFECTNUM%MAXTURNCOUNT = !%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%MAXTURNCOUNT!
SET ENEMYSPELLEFFECT%EFFECTNUM%TEXT=!%ENEMYSPELLTYPE%%ENEMYSPELLCHOICE%EFFECT%EFFECTNUM%PLAYERTEXT!
IF %EFFECTNUM% LSS %ENEMYSPELLEFFECTSNUM% (
	GOTO :LOOP1START
)
GOTO :EOF

:INTELLIGENCEQUERY
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
IF %ENEMYINT% GTR %RANPERC% (
	CALL "%BATTLECHOICERESOURCEPATH%\badspellchoicequery.bat"
)
GOTO :EOF
