:ENEMYSPELLCHOOSE
CALL :REMOVEUSED
CALL :SETITEM
GOTO :EOF

:REMOVEUSED
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP = !ENEMYITEM%COUNT%! 
IF !ENEMYITEM%TEMP%NUM! LEQ 0 (
	SET /a ENEMYITEM%COUNT%CHANCE = 0
)
IF %COUNT% LSS %ENEMYITEMNUM% (
	GOTO :LOOP
)
GOTO :EOF

:SETITEM
SET /a ENEMYITEMCHANCETOT = 0
SET /a COUNT = 0
:LOOP1
SET /a COUNT = %COUNT% + 1
SET /a ENEMYITEMCHANCETOT = %ENEMYITEMCHANCETOT%+!ENEMYITEM%COUNT%CHANCE!
SET /a ENEMYITEM%COUNT%CHANCECUM = %ENEMYITEMCHANCETOT%
IF %COUNT% LSS %ENEMYITEMNUM% (
	GOTO :LOOP1
)
SET /a TEMP=(%RANDOM% %% %ENEMYITEMCHANCETOT%)+1
SET /a COUNT = 0
:LOOP2
SET /a COUNT = %COUNT% + 1
IF %TEMP% LSS !ENEMYITEM%COUNT%CHANCECUM! (
	SET /a ENEMYITEMCHOICETEMP = %COUNT%
) ELSE IF %COUNT% LSS %ENEMYITEMNUM% (
	GOTO :LOOP2
) ELSE (
	SET /a BADCHOICE = 1
	GOTO :EOF
)
SET /a ENEMYITEMCHOICETEMP2=!ENEMYITEM%ENEMYITEMCHOICETEMP%!
IF !ENEMYITEM%ENEMYITEMCHOICETEMP2%NUM! GTR 0 (
	SET /a ENEMYITEMCHOICE = %ENEMYITEMCHOICETEMP2%
	SET /a ENEMYCUSTOMITEM = 0
) ELSE (
	SET /a BADCHOICE = 1
)
GOTO :EOF