:ENEMYCHOOSEACTION
SET /a BADCHOICE = 0
SET ATTACKER=ENEMY
SET DEFENDER=PLAYER
SET /a ENEMYINTELLIGENTCHOICE = 0
CALL :SPELLCHANCENULLQUERY
CALL :SKILLCHANCENULLQUERY
REM CALL "%BATTLERESOURCEPATH%\ranresources.bat"
REM IF %ENEMYINT% GTR %RANPERC% (
REM 	CALL "%BATTLECHOICERESOURCEPATH%\intelligentchoice.bat"
REM )
REM IF %ENEMYINTELLIGENTCHOICE% EQU 1 (
REM 	GOTO :EOF
REM )
SET /a TEMP = %ENEMYSPELLCHANCE% + %ENEMYITEMCHANCE%
SET /a TEMP2 = %ENEMYSPELLCHANCE% + %ENEMYITEMCHANCE% + %ENEMYSKILLCHANCE%
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
IF %RANPERC% LSS %ENEMYSPELLCHANCE% (
	SET /a ENEMYACTION = 2
) ELSE IF %RANPERC% LSS %TEMP% (
	SET /a ENEMYACTION = 4
) ELSE IF %RANPERC% LSS %TEMP2% (
	SET /a ENEMYACTION = 3
) ELSE (
	SET /a ENEMYACTION = 1
)
IF %ENEMYACTION% EQU 1 (
	GOTO :EOF
) ELSE IF %ENEMYACTION% EQU 2 (
	CALL "%BATTLECHOICERESOURCEPATH%\enemychoosespelltype.bat"
) ELSE IF %ENEMYACTION% EQU 3 (
	CALL "%BATTLECHOICERESOURCEPATH%\enemychooseskill.bat"
) ELSE IF %ENEMYACTION% EQU 4 (
	CALL "%BATTLECHOICERESOURCEPATH%\enemychooseitem.bat"
)
IF %BADCHOICE% EQU 1 (
	GOTO :ENEMYCHOOSEACTION
)
GOTO :EOF



:SPELLCHANCENULLQUERY
IF %ENEMYSILENCE% EQU 1 (
	SET /a ENEMYSPELLCHANCE = 0
) ELSE IF DEFINED ENEMY%ENEMYID%SPELLCHANCE (
	SET /a ENEMYSPELLCHANCE = !ENEMY%ENEMYID%SPELLCHANCE!
)
IF %ENEMYCONFUSION% EQU 1 (
	SET /a ENEMYSPELLCHANCE = 0
) ELSE IF DEFINED ENEMY%ENEMYID%SPELLCHANCE (
	SET /a ENEMYSPELLCHANCE = !ENEMY%ENEMYID%SPELLCHANCE!
)
GOTO :EOF

:SKILLCHANCENULLQUERY
IF %ENEMYCONFUSION% EQU 1 (
	SET /a ENEMYSKILLCHANCE = 0
) ELSE IF %ENEMYSKILLNUM% GTR 0 (
	SET /a ENEMYSKILLCHANCE = !ENEMY%ENEMYID%SKILLCHANCE!
) 
GOTO :EOF