SET /a ENEMYWEAKNESSNUM = 7
SET ENEMYWEAKNESS1=Fire
SET ENEMYWEAKNESS2=Ice
SET ENEMYWEAKNESS3=Electricity
SET ENEMYWEAKNESS4=Water
SET ENEMYWEAKNESS5=Earth
SET ENEMYWEAKNESS6=Demi
SET ENEMYWEAKNESS7=Forbidden

SET /a ENEMYSTRENGTHNUM = 0
SET ENEMYSTRENGTH1=
SET ENEMYSTRENGTH2=
SET ENEMYSTRENGTH3=
SET ENEMYSTRENGTH4=
SET ENEMYSTRENGTH5=
SET ENEMYSTRENGTH6=
SET ENEMYSTRENGTH7=

SET /a ENEMYELEMENTIMMUNENUM = 0
SET ENEMYELEMENTIMMUNE1=
SET ENEMYELEMENTIMMUNE2=
SET ENEMYELEMENTIMMUNE3=
SET ENEMYELEMENTIMMUNE4=
SET ENEMYELEMENTIMMUNE5=
SET ENEMYELEMENTIMMUNE6=
SET ENEMYELEMENTIMMUNE7=

SET /a ENEMYABSORBNUM = 0
SET ENEMYABSORB1=
SET ENEMYABSORB2=
SET ENEMYABSORB3=
SET ENEMYABSORB4=
SET ENEMYABSORB5=
SET ENEMYABSORB6=
SET ENEMYABSORB7=

ECHO After using !LIMITBREAK%LIMITCOUNT%NAME! %ENEMYNAME% is weak to all elements
ECHO.
CALL "%BATTLEDISPLAYRESOURCEPATH%\setupscandisplay.bat"
TIMEOUT /T 1 > nul