SET /a IMMUNEALL = 1
CALL :FIRSTDISPLAY
SET STATUS=Blind
CALL :INDUCESTATUS
SET STATUS=Silence
CALL :INDUCESTATUS
SET STATUS=Poison
CALL :INDUCESTATUS
SET STATUS=Slow
CALL :INDUCESTATUS
SET STATUS=Sleep
CALL :INDUCESTATUS
SET STATUS=Confusion
CALL :INDUCESTATUS
SET STATUS=Stop
CALL :INDUCESTATUS
IF %IMMUNEALL% EQU 1 (
	CALL :LASTDISPLAY
)
TIMEOUT /T 2 > nul
GOTO :EOF

:INDUCESTATUS
SET /a IMMUNE = 0
IF %ENEMYSTATUSIMMUNENUM% EQU 0 (
	CALL :INDUCE
)
SET /a COUNT = 0
:INDUCELOOP
SET /a COUNT = %COUNT% + 1
IF /I !ENEMYSTATUSIMMUNE%COUNT%! EQU %STATUS% (
	SET /a IMMUNE = 1
	GOTO :EOF
)
IF %COUNT% LSS %ENEMYSTATUSIMMUNENUM% (
	GOTO :INDUCELOOP
)
CALL :INDUCE
GOTO :EOF

:INDUCE
SET /a IMMUNEALL = 0
SET /a ENEMY%STATUS% = 1
SET /a ENEMY%STATUS%TURNCOUNT = 3
ECHO. %STATUS%
TIMEOUT /T 1 > nul
GOTO :EOF

:FIRSTDISPLAY
ECHO Using !LIMITBREAK%LIMITCOUNT%NAME! you have afflicted %ENEMYNAME% with the following statuses:
ECHO.
GOTO :EOF

:LASTDISPLAY
ECHO Unfortunately, %ENEMYNAME% is immune to all status ailments^^!
ECHO.
GOTO :EOF