CALL :INITIALISE
CALL :ELEMENTCHECK
CALL :DAMAGECALC
CALL :APPLYDAMAGE
CALL :ENDBATTLEQUERY
GOTO :EOF

:INITIALISE
SET /a WEAKNESSTRUE = 0
SET /a STRENGTHTRUE = 0
SET /a IMMUNETRUE = 0
SET /a ABSORBTRUE = 0
SET /a DAMABSORBDISPLAY = 0
::SET /a PLAYERLIMITBREAK = 0
::SET /a PLAYERLIMITBREAKACTIVE = 0
IF %PLAYERDOUBLELIMDAM% EQU 1 (
	SET /a DAM = %DAM%*2
)
GOTO :EOF

:ELEMENTCHECK
IF /I %ELEMENT% EQU NONE (
	GOTO :EOF
)
:WEAKNESSES
IF %ENEMYWEAKNESSNUM% EQU 0 (
	GOTO :STRENGTHS
)
SET /a COUNT = 0
:WEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
IF /I %ELEMENT% EQU !ENEMYWEAKNESS%COUNT%! (
	SET /a WEAKNESSTRUE = 1
)
IF %COUNT% LSS %ENEMYWEAKNESSNUM% (
	GOTO :WEAKNESSLOOP
)

:STRENGTHS
IF %ENEMYSTRENGTHNUM% EQU 0 (
	GOTO :IMMUNES
)
SET /a COUNT = 0
:STRENGTHLOOP
SET /a COUNT = %COUNT% + 1
IF /I %ELEMENT% EQU !ENEMYSTRENGTH%COUNT%! (
	SET /a STRENGTHTRUE = 1
)
IF %COUNT% LSS %ENEMYSTRENGTHNUM% (
	GOTO :STRENGTHLOOP
)

:IMMUNES
IF %ENEMYELEMENTIMMUNENUM% EQU 0 (
	GOTO :ABSORBS
)
SET /a COUNT = 0
:IMMUNELOOP
SET /a COUNT = %COUNT% + 1
IF /I %ELEMENT% EQU !ENEMYELEMENTIMMUNE%COUNT%! (
	SET /a IMMUNETRUE = 1
)
IF %COUNT% LSS %ENEMYELEMENTIMMUNENUM% (
	GOTO :IMMUNELOOP
)

:ABSORBS
IF %ENEMYABSORBNUM% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:ABSORBLOOP
SET /a COUNT = %COUNT% + 1
IF /I %ELEMENT% EQU !ENEMYABSORB%COUNT%! (
	SET /a ABSORBTRUE = 1
)
IF %COUNT% LSS %ENEMYABSORBNUM% (
	GOTO :ABSORBLOOP
)
GOTO :EOF


:DAMAGECALC
IF %IMMUNETRUE% EQU 1 (
	SET /a DAM = 0
	GOTO :EOF
)
IF %WEAKNESSTRUE% EQU 1 (
	CALL :APPLYWEAKNESS
)
IF %STRENGTHTRUE% EQU 1 (
	CALL :APPLYSTRENGTH
)
IF %DAM% LSS 0 (
	SET /a DAM = %MAXDAM%
)
IF %ABSORBTRUE% EQU 1 (
	CALL :APPLYABSORB
)
IF %PLAYERBREAKDAM% EQU 0 (
	IF %DAM% GTR %MAXDAM% (
		SET /a DAM = %MAXDAM%
	) 
)
GOTO :EOF


:APPLYWEAKNESS
SET /a DAM = %DAM%*2
GOTO :EOF

:APPLYSTRENGTH
SET /a DAM = %DAM%/2
GOTO :EOF

:APPLYABSORB
SET /a DAM = -%DAM%
GOTO :EOF

:APPLYDAMAGE
IF %ABSORBTRUE% EQU 1 (
	SET /a DAMABSORBDISPLAY = -%DAM%
)
SET /a ENEMYHP = %ENEMYHP% - %DAM%
IF %IMMUNETRUE% EQU 1 (
	ECHO %ENEMYNAME% is immune to %ELEMENT% so you did 0 damage with !LIMITBREAK%LIMITCOUNT%NAME!^^!
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %WEAKNESSTRUE% EQU 1 (
	ECHO !LIMITBREAK%LIMITCOUNT%NAME! was super effective and did %DAM% damage^^!
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %STRENGTHTRUE% EQU 1 (
	ECHO !LIMITBREAK%LIMITCOUNT%NAME! wasn't very effective and did %DAM% damage...
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %ABSORBTRUE% EQU 1 (
	ECHO %ENEMYNAME% absorbed the damage and converted it to HP^^!
	ECHO.
	CALL :WAITFORTWO
	ECHO %ENEMYNAME% was healed by %DAMABSORBDISPLAY% HP^^!
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
ECHO !LIMITBREAK%LIMITCOUNT%NAME! did %DAM% damage to %ENEMYNAME%
CALL :WAITFORTWO
GOTO :EOF

:ENDBATTLEQUERY
IF %ENEMYHP% LEQ 0 (
	SET /a ENEMYHP = 0
	SET /a WINBATTLE = 1
) ELSE IF %ENEMYHP% GTR %ENEMYMAXHP% (
	SET /a ENEMYHP = %ENEMYMAXHP%
)
GOTO :EOF




:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
