SET /a DAM=(((((%PLAYERMAG%*%PLAYERSTR%)+%PLAYERLVL%)/((%ENEMYSPR%)+%ENEMYLVL%)*(%PLAYERMAG%+%PLAYERSTR%)*%PLAYERLVL%/%ENEMYLVL%)*100)*%RANFACT%)/10000
SET ELEMENT=NONE
CALL "%BATTLEACTIONRESOURCEPATH%\LimitBreaks\limdam.bat"