SET /a ENEMYSTATUSIMMUNENUM = 0
SET ENEMYSTATUSIMMUNE1=
SET ENEMYSTATUSIMMUNE2=
SET ENEMYSTATUSIMMUNE3=
SET ENEMYSTATUSIMMUNE4=
SET ENEMYSTATUSIMMUNE5=
SET ENEMYSTATUSIMMUNE6=
SET ENEMYSTATUSIMMUNE7=
ECHO After using !LIMITBREAK%LIMITCOUNT%NAME! %ENEMYNAME% is no longer immune to any status ailments
ECHO.
CALL "%BATTLEDISPLAYRESOURCEPATH%\setupscandisplay.bat"
TIMEOUT /T 1 > nul