SET /a ID = !ENEMY%ENEMYID%SET%REWARDSET%MORPHID!
SET TYPE=!ENEMY%ENEMYID%SET%REWARDSET%MORPHTYPE!
SET /a MAX = !ENEMY%ENEMYID%SET%REWARDSET%MORPHMAXNUM!
SET /a ITEMNUM = (%MAX%*%PLAYERLVL%)/100
IF %ITEMNUM% LEQ 0 (
	SET /a ITEMNUM = 1
)
SET /a PLAYER%TYPE%%ID%NUM = !PLAYER%TYPE%%ID%NUM! + %ITEMNUM%
IF %ITEMNUM% EQU 1 (
	ECHO Using !LIMITBREAK%LIMITCOUNT%NAME! you have stolen %ITEMNUM% !%TYPE%%ID%NAME!
) ELSE (
	ECHO Using !LIMITBREAK%LIMITCOUNT%NAME! you have stolen %ITEMNUM% !%TYPE%%ID%NAME!s
)
TIMEOUT /T 2 > nul