SET /a PLAYERHP = %PLAYERMAXHP%
SET /a PLAYERMP = %PLAYERMAXMP%
SET /a PLAYERAP = %PLAYERMAXAP%
SET /a PLAYERBLIND = 0
SET /a PLAYERSILENCE = 0
SET /a PLAYERPOISON = 0
SET /a PLAYERSLOW = 0
SET /a PLAYERSLEEP = 0
SET /a PLAYERCONFUSION = 0
SET /a PLAYERSTOP = 0
SET /a PLAYERBLINDTURNCOUNT = 0
SET /a PLAYERSILENCETURNCOUNT = 0
SET /a PLAYERPOISONTURNCOUNT = 0
SET /a PLAYERSLOWTURNCOUNT = 0
SET /a PLAYERSLEEPTURNCOUNT = 0
SET /a PLAYERCONFUSIONTURNCOUNT = 0
SET /a PLAYERSTOPTURNCOUNT = 0
ECHO Using !LIMITBREAK%LIMITCOUNT%NAME! has filled your HP, MP, AP and removed all negative status ailments.
ECHO.
TIMEOUT /T 2 > nul