::@ECHO OFF
::SETLOCAL ENABLEDELAYEDEXPANSION
::CALL :TEST

:START
SET /a GUITARBATTLETOTAL=%GUITARBATTLETOTAL%+1
SET /a POINTS=0
SET /a EPOINTS=0
SET /a SLASHWIN = 10
SET TEMPPATH=%MUSICPATH%\Battle\GuitarBattle
SET /a STOP = 1
SET /a LOOP = 1
CALL "%MUSICPATH%\startmusic.bat"
SET /a WINPOINTS=((50*%PLAYERLVL%)/%PLAYERSPD%)
CLS
CALL "%MISCRESOURCEPATH%\slashdisplay.bat"
ECHO.
ECHO Slash hates animal cruelty and challenges you to a guitar battle for the captured animals
ECHO.
ECHO You need %WINPOINTS% points to beat slash. Increasing your speed will reduce this
ECHO Slash needs %SLASHWIN% points to win.
ECHO.
pause
:GAMESTART
SET /a RANNUMTEMP=(%RANDOM% %% 35) + 1
SET RANNUM=%RANNUMTEMP%
IF %RANNUMTEMP% GEQ 10 (
	CALL :ADJUST
)
CALL :NEXTROUND
IF %POINTS% GEQ %WINPOINTS% (
	CALL :WIN
	GOTO :EOF
) ELSE IF %EPOINTS% GEQ %SLASHWIN% (
	CALL :LOSE
	GOTO :EOF
)
GOTO :GAMESTART


:ADJUST
IF %RANNUMTEMP% EQU 10 (
	SET RANNUM=Q
) ELSE IF %RANNUMTEMP% EQU 11 (
	SET RANNUM=W
) ELSE IF %RANNUMTEMP% EQU 12 (
	SET RANNUM=E
) ELSE IF %RANNUMTEMP% EQU 13 (
	SET RANNUM=R
) ELSE IF %RANNUMTEMP% EQU 14 (
	SET RANNUM=T
) ELSE IF %RANNUMTEMP% EQU 15 (
	SET RANNUM=Y
) ELSE IF %RANNUMTEMP% EQU 16 (
	SET RANNUM=A
) ELSE IF %RANNUMTEMP% EQU 17 (
	SET RANNUM=S
) ELSE IF %RANNUMTEMP% EQU 18 (
	SET RANNUM=D
) ELSE IF %RANNUMTEMP% EQU 19 (
	SET RANNUM=F
) ELSE IF %RANNUMTEMP% EQU 20 (
	SET RANNUM=G
) ELSE IF %RANNUMTEMP% EQU 21 (
	SET RANNUM=H
) ELSE IF %RANNUMTEMP% EQU 22 (
	SET RANNUM=Z
) ELSE IF %RANNUMTEMP% EQU 23 (
	SET RANNUM=X
) ELSE IF %RANNUMTEMP% EQU 24 (
	SET RANNUM=C
) ELSE IF %RANNUMTEMP% EQU 25 (
	SET RANNUM=V
) ELSE IF %RANNUMTEMP% EQU 26 (
	SET RANNUM=B
) ELSE IF %RANNUMTEMP% EQU 27 (
	SET RANNUM=N
) ELSE IF %RANNUMTEMP% EQU 28 (
	SET RANNUM=U
) ELSE IF %RANNUMTEMP% EQU 29 (
	SET RANNUM=I
) ELSE IF %RANNUMTEMP% EQU 30 (
	SET RANNUM=O
) ELSE IF %RANNUMTEMP% EQU 31 (
	SET RANNUM=P
) ELSE IF %RANNUMTEMP% EQU 32 (
	SET RANNUM=J
) ELSE IF %RANNUMTEMP% EQU 33 (
	SET RANNUM=K
) ELSE IF %RANNUMTEMP% EQU 34 (
	SET RANNUM=L
) ELSE IF %RANNUMTEMP% EQU 35 (
	SET RANNUM=M
)
GOTO :EOF

:NEXTROUND
CLS
ECHO.
ECHO You need %WINPOINTS% points to win 
ECHO      _
ECHO     / 7
ECHO    /_(
ECHO    ^|_^|
ECHO    ^|_^|
ECHO    ^|_^|
ECHO    ^|_^| /^\
ECHO  /^\^|^=^|/ /
ECHO  ^\ ^|_^| /
ECHO   ) _  ^\
ECHO  / ^|_^|  ^\
ECHO /  -^=-o /
ECHO ^\  /~^\_/  
ECHO  ^\/
ECHO.
ECHO Your Score: %POINTS%/%WINPOINTS%
ECHO Slash's Score: %EPOINTS%/%SLASHWIN%
ECHO.
IF /I %DIFFICULTY% EQU HARD (
	ECHO !SPACES%RANNUMTEMP%! Press %RANNUM%
) ELSE (
	ECHO Press %RANNUM%
)
ECHO.
CHOICE /C:123456789QWERTYASDFGHZXCVBNUIOPJKLM0 /N /T:1 /D:0
ECHO.
IF %ERRORLEVEL% EQU %RANNUMTEMP% (
	ECHO Your point^^!
	ECHO.
	SET /a POINTS = %POINTS% + 1
	CALL :WAITFORZERO
) ELSE (
	ECHO Slash's point^^!
	ECHO.
	SET /a EPOINTS = %EPOINTS% + 1
	CALL :WAITFORZERO
)
GOTO :EOF

:LOSE
SET TEMPPATH=%MUSICPATH%\Battle\Lose
SET /a STOP = 1
SET /a LOOP = 1
CALL "%MUSICPATH%\startmusic.bat"
CALL :WAITFORONE
CLS
CALL "%MISCRESOURCEPATH%\slashdisplay.bat"
ECHO Slash has %SLASHWIN% points. You lose^^!
ECHO.
CALL :WAITFORTWO
ECHO Slash: I win^^! Give me that %ENEMYNAME%^^!
ECHO.
CALL :WAITFORTWO
ECHO Slash has taken the captured %ENEMYNAME%. You can no longer abuse it for you own personal pleasure.
ECHO.
pause
SET /a GUITARBATTLELOSETOTAL=%GUITARBATTLELOSETOTAL%+1
SET /a NUMTRAINBATTLES=0
SET /a ENEMY%ENEMYID%CAUGHT=0
GOTO :EOF

:WIN
SET TEMPPATH=%MUSICPATH%\Battle\Win
SET /a STOP = 1
SET /a LOOP = 1
CALL "%MUSICPATH%\startmusic.bat"
CALL :WAITFORONE
CLS
CALL "%MISCRESOURCEPATH%\slashdisplay.bat"
ECHO You have %POINTS% points. You win^^!
ECHO.
CALL :WAITFORTWO
ECHO Slash: Awww man, I lost... Now you can keep the %ENEMYNAME%. Don't let me catch you abusing animals again though^^!
ECHO.
pause
SET /a GUITARBATTLEWINTOTAL=%GUITARBATTLEWINTOTAL%+1
SET /a NUMTRAINBATTLES=0
IF %GUITARBATTLEWINTOTAL% EQU %MAXGUITARBATTLES% (
	CALL :DEFEATSLASH
)
GOTO :EOF

:DEFEATSLASHQUERY
CALL "%MISCRESOURCEPATH%\slashdisplay.bat"
ECHO Slash: Blast^^! You've defeated me again^^!
ECHO.
CALL :WAITFORTWO
ECHO Slash: You're clearly more skilled than I, please take this as a reward.
ECHO.
CALL :WAITFORTWO
ECHO %PLAYERNAME%: Your Guitar^^!?
ECHO.
CALL :WAITFORTWO
ECHO Slash: Don't be foolish, foolish one. No one can have my guitar. Take my hat instead.
ECHO.
CALL :WAITFORTHREE
SET /a PLAYERACCESSORY%TOPHATID%NUM = !PLAYERACCESSORY%TOPHATID%NUM! + 1
ECHO. You have acquired !ACCESSORY%TOPHATID%NAME!^^!
ECHO.
pause
GOTO :EOF

:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF


:TEST
SET /a COUNT = 0
:LOOP
SET /a OLDCOUNT = %COUNT%
SET /a COUNT = %COUNT% + 1
SET SPACES%COUNT%=!SPACES%OLDCOUNT%! 
IF %COUNT% LSS 100 (
	GOTO :LOOP
)
SET DIFFICULTY=HARD
SET MUSICPATH=D:\Users\NDSisson\Desktop\Desktop\Recent\Game\Music
SET /a MUSICENABLED = 0
SET /a GUITARBATTLETOTAL = 0
SET /a PLAYERLVL = 10
SET /a PLAYERSPD = 10

GOTO :EOF