SET /a BATTLELOSETOTAL = %BATTLELOSETOTAL%+1
:TRAINBATTLEQUERY
SET /a SPECIALFIGHT = 0
IF %TRAINBATTLE% EQU 1 (
	GOTO :TRAINLOSE
) ELSE (
	GOTO :LOSE
)
GOTO :EOF

:LOSE
SET TEMPPATH=%MUSICPATH%\Battle\Lose
SET /a STOP = 1
SET /a LOOP = 0
CALL "%MUSICPATH%\startmusic.bat"
CALL "%MISCRESOURCEPATH%\losebattledisplay.bat"
CALL "%BATTLEENDRESOURCEPATH%\itemloss.bat"
CALL "%BATTLEENDRESOURCEPATH%\specialfightloss.bat"
SET /a PLAYERHP = %PLAYERMAXHP%
SET /a PLAYERMP = %PLAYERMAXMP%
SET /a PLAYERLIMITBREAK = 0
SET /a PLAYERLIMITBREAKACTIVE = 0
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplaycalculations.bat"
SET /a TUTORIALFIGHT = 0
GOTO :EOF


:TRAINLOSE
CALL "%MISCRESOURCEPATH%\losebattledisplay.bat"
ECHO The %ENEMYNAME% escaped while you were down...
ECHO.
SET /a ENEMY%ENEMYID%CAUGHT=0
SET /a PLAYERHP = %PLAYERMAXHP%
SET /a PLAYERMP = %PLAYERMAXMP%
pause
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF