IF %ENEMYID% EQU %TRAMPID% (
	IF !PLAYERKEYITEM%TEYEID%ACQUIRED! EQU 1 (
		SET /a STORY9VERSIONNUM = 3
		ECHO.
		ECHO The tramp took his eye back
		ECHO.
		SET /a PLAYERKEYITEM%TEYEID%ACQUIRED = 0
		CALL :WAITFORTWO
	)
) ELSE IF %ENEMYID% EQU %LEEROYID% (
	SET /a STORY17VERSIONNUM = 3
)
:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF