GOTO :START
SET /a MINEKEYID = 1
SET /a PLAYERKEYITEM1ACQUIRED = 0
SET LASTBOSSNAME=Ragata
SET /a MAGSTONE1ID = 1
SET /a MAGSTONE2ID = 2
SET /a MAGSTONE3ID = 3
SET /a MAGSTONE4ID = 4
SET KEYITEM1NAME=Warrior Stone
SET KEYITEM2NAME=Mage Stone
SET KEYITEM3NAME=Thief Stone
SET KEYITEM4NAME=Other Stone
SET /a KEYITEM1NAMELENGTH = 13
SET /a KEYITEM1NAMELENGTH = 10
SET /a KEYITEM1NAMELENGTH = 11
SET /a KEYITEM1NAMELENGTH = 11


:START
SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
SET /a STORY15VERSIONNUM = 2
CALL :BOOKTEXT
IF !PLAYERKEYITEM%MINEKEYID%ACQUIRED! EQU 0 (
	CALL :FINDKEY
)
GOTO :EOF

:FINDKEY
SET /a PLAYERKEYITEM%MINEKEYID%ACQUIRED = 1
ECHO.
ECHO You have found the key to the Mine hidden in a book^^!
ECHO.
pause
GOTO :EOF

:BOOKTEXT
CLS
ECHO.
ECHO This book has a picture of %LASTBOSSNAME% on the front^^!
ECHO.
CALL :WAITFORTHREE
ECHO You open the book...
ECHO.
CALL :WAITFORTHREE
CLS
ECHO.
CALL :CHUCKJOKE
ECHO.
ECHO The name %LASTBOSSNAME% stems from the Latin 'Regata', which means:
ECHO 'Giant Paedophillic Robot Demon Looking Thing'.
ECHO.
ECHO To find %LASTBOSSNAME%, one must open a portal to Hell.
ECHO This requires 4 magical relics:
ECHO.
ECHO. The !KEYITEM%MAGSTONE1ID%NAME!
ECHO. The !KEYITEM%MAGSTONE2ID%NAME!
ECHO. The !KEYITEM%MAGSTONE3ID%NAME!
ECHO. The !KEYITEM%MAGSTONE4ID%NAME!
ECHO.
ECHO The !KEYITEM%MAGSTONE1ID%NAME! will increase Strength and Endurance.
ECHO The !KEYITEM%MAGSTONE2ID%NAME! will increase Magic and Spirit.
ECHO The !KEYITEM%MAGSTONE3ID%NAME! will increase Speed and Evasion.
ECHO The !KEYITEM%MAGSTONE4ID%NAME! does nothing. Deal with it.

ECHO.
pause
GOTO :EOF

:CHUCKJOKE
SET /a TEMP = 1
CALL :CHUCKJOKE%TEMP%
::CALL :LENGTHS
ECHO %LINE1%
ECHO %LINE2%
GOTO :EOF

:CHUCKJOKE1
SET LINE1=Legends say that when %LASTBOSSNAME% does pushups, he doesn't push himself up,
SET LINE2=he pushes the world down.
GOTO :EOF

:BUILDBOOK


:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

:WAITFORFOUR
TIMEOUT /T 4 > nul
GOTO :EOF
