IF %STORY14VERSIONNUM% EQU 0 (
	SET /a STORY14VERSIONNUM = 3
)
IF %STORY15VERSIONNUM% EQU 0 (
	SET /a STORY15VERSIONNUM = 1
)
SET MAP=CASTLE
SET /a PLAYERXCOORD = 1
SET /a PLAYERYCOORD = 5
SET /a EXITMAP = 1