ECHO You have %PLAYERGIL% Gil
ECHO.
ECHO How much Gil would you like to throw?
ECHO.
:CHOICE
SET /P TEMP=
ECHO.
IF "%TEMP%" EQU "" (
	GOTO :CHOICE
)
IF %TEMP% GTR %PLAYERGIL% (
	GOTO :CHOICE
) ELSE IF %TEMP% LEQ 0 (
	GOTO :CHOICE
)
SET /a GILTHROWNCOUNT = %GILTHROWNCOUNT% + %TEMP%
SET /a PLAYERGIL = %PLAYERGIL% - %TEMP%
SET /a SKILLDAM = (%TEMP%*%RANFACT%)/(%ENEMYEND%*50)
SET SKILLELEMENT=NONE
SET /a SKILLCRITICALCHANCE = 0
CALL "%SKILLRESOURCEPATH%\skilldamage.bat"
GOTO :EOF






:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF