::IF %GURUBATTLE% EQU 0 (
::	IF %SPECIALFIGHT% EQU 1 (
::		CALL :CANTTRANSFORM
::		GOTO :EOF
::	)
::)
SET /a TEMP = ((%ENEMYHP%-%PLAYERLCK%)*%RANFACT%)/100
SET /a TEMP2 = (%TEMP%/%ENEMYMAXHP%)*100
IF %TEMP2% LSS %RANPERC% (
	CALL :SUCCESS
) ELSE (
	CALL :FAIL
)
GOTO :EOF

:SUCCESS
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a TRANSGIL = (((100+(%PLAYERLCK%*2))*%RANFACT%)*!ENEMY%ENEMYID%SET%REWARDSET%MORPHGIL!)/10000
SET /a ENEMYHP = 0
SET /a PLAYERGIL = %PLAYERGIL% + %TRANSGIL%
SET /a TRANSGILCOUNT = %TRANSGILCOUNT% + %TRANSGIL%
SET /a ENDBATTLE = 1
SET /a WINBATTLE = 1
ECHO %PLAYERNAME% transformed %ENEMYNAME% into gil^^!
ECHO.
CALL :WAITFORONE
ECHO You have gained %TRANSGIL% gil
ECHO.
pause
GOTO :EOF

:FAIL
ECHO You failed to transform %ENEMYNAME% into gil. Try damaging them some more
ECHO.
CALL :WAITFORTWO
GOTO :EOF

:CANTTRANSFORM
ECHO You cannot transform %ENEMYNAME% in this fight^^!
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

