SET /a PLAYERHASTE = 1
SET /a PLAYERHASTETURNCOUNT = 3
SET /a PLAYERPROTECT = 1
SET /a PLAYERPROTECTTURNCOUNT = 3
SET /a PLAYERSHELL = 1
SET /a PLAYERSHELLTURNCOUNT = 3
ECHO %PLAYERNAME% now has Haste, Protect and Shell active for 3 turns
ECHO.
TIMEOUT /T 3 > nul
