SET /a TEMP = %RANFACT% + %PLAYERLCK%
SET /a TEMP2 = %PLAYERMAXMP%*%TEMP%/500
SET /a PLAYERMP = %PLAYERMP% + %TEMP2%
IF %PLAYERMP% GTR %PLAYERMAXMP% (
	SET /a PLAYERMP = %PLAYERMAXMP%
)
SET /a MPSTOLENCOUNT = %MPSTOLENCOUNT% + %TEMP2%
ECHO %PLAYERNAME% has stolen %TEMP2% MP from %ENEMYNAME%
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF
