IF %PLAYERFIRAGAENABLED% EQU 1 (
	IF %PLAYERBLIZZAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	) ELSE IF %PLAYERTHUNDAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	) ELSE IF %PLAYERWATERAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	)
) ELSE IF %PLAYERBLIZZAGAENABLED% EQU 1 (
	IF %PLAYERTHUNDAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	) ELSE IF %PLAYERWATERAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	)
) ELSE IF %PLAYERTHUNDAGAENABLED% EQU 1 (
	IF %PLAYERWATERAGAENABLED% EQU 1 (
		SET /a ALLELEMENTALSPELLSUNLOCKED = 1
	)
)