CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a MISSVAR = !%ATTACKER%ACC!*80/!%DEFENDER%EVA!
IF %RANPERC% GEQ %MISSVAR% (
	ECHO %PLAYERNAME%'s !SKILL%SKILLCHOICE%NAME! missed^^!
	ECHO.
	TIMEOUT /T 2 > nul
	GOTO :EOF
)
SET /a TEMP = %PLAYERLVL%/10
IF %TEMP% EQU 0 (
	SET /a TEMP = 1
)
SET /a SKILLDAM = (%PLAYERMAXHP% - %PLAYERHP%)*%TEMP%
SET SKILLELEMENT=NONE
SET /a SKILLCRITICALCHANCE = 0
CALL "%SKILLRESOURCEPATH%\skilldamage.bat"