:MISSATTACK
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a MISSVAR = !%ATTACKER%ACC!*50/!%DEFENDER%EVA!
IF %RANPERC% GEQ %MISSVAR% (
	CALL :MISSTRUE
	GOTO :EOF
)
SET /a TEMP = (((((!%ATTACKER%STR!*5)+!%ATTACKER%LVL!)/((!%DEFENDER%END!*3)+!%DEFENDER%LVL!)*(!%ATTACKER%STR!+5)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)*100)*%RANFACT%)/10000
SET /a SKILLDAM = %TEMP%*3
SET SKILLELEMENT=NONE
SET /a SKILLCRITICALCHANCE = %PLAYERLCK%
CALL "%SKILLRESOURCEPATH%\skilldamage.bat"
GOTO :EOF


:MISSTRUE
ECHO %PLAYERNAME%'s !SKILL%SKILLCHOICE%NAME! missed^^!
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF