CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a MISSVAR = !%ATTACKER%ACC!*80/!%DEFENDER%EVA!
IF %RANPERC% GEQ %MISSVAR% (
	ECHO %PLAYERNAME%'s !SKILL%SKILLCHOICE%NAME! missed^^!
	ECHO.
	TIMEOUT /T 2 > nul
	GOTO :EOF
)
SET /a TEMP = (((((!%ATTACKER%STR!*5)+!%ATTACKER%LVL!)/((!%DEFENDER%END!*3)+!%DEFENDER%LVL!)*(!%ATTACKER%STR!+5)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)*100)*%RANFACT%)/10000
SET /a TEMP2 = (%PLAYERLVL%/10) + 1
SET /a TEMP3 = %PLAYERHP% - 1
SET /a TEMP4 = %TEMP2% * %TEMP3% / 2
IF %TEMP3% GEQ %PLAYERHP% (
	SET /a TEMP3 = %PLAYERHP% - 1
)
SET /a SKILLDAM = %TEMP% + %TEMP4%
SET SKILLELEMENT=NONE
SET /a SKILLCRITICALCHANCE = %PLAYERLCK%
CALL "%SKILLRESOURCEPATH%\skilldamage.bat"
SET /a PLAYERHP = %PLAYERHP% - %TEMP3%
ECHO %PLAYERNAME% received %TEMP3% damage
ECHO.
CALL :WAITFORTWO
GOTO :EOF






:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF