CALL :NOTHINGTOSTEALQUERY
IF %NOTHINGTOSTEAL% EQU 1 (
	GOTO :EOF
)
CALL :STEALQUERY
IF %STEALSUCCESS% EQU 1 (
	CALL :SUCCESS
) ELSE (
	CALL :FAIL
)
GOTO :EOF


:NOTHINGTOSTEALQUERY
SET /a NOTHINGTOSTEAL = 0
IF !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! EQU 0 (
	CALL :NOTHINGTOSTEAL
	GOTO :EOF
) 
SET /a TEMPCOUNT = 0
:NOTHINGTOSTEALQUERYLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF !STEALITEM%TEMPCOUNT%SUCCESS! EQU 0 (
	GOTO :EOF
)
IF %TEMPCOUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :NOTHINGTOSTEALQUERYLOOP
)
CALL :NOTHINGTOSTEAL
GOTO :EOF

:NOTHINGTOSTEAL
SET /a NOTHINGTOSTEAL = 1
ECHO The enemy has nothing to steal^^!
ECHO.
CALL :WAITFORTWO
GOTO :EOF

:STEALQUERY
SET /a STEALSUCCESS = 0
SET /a TEMPCOUNT = 0
:STEALLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
CALL :STEALITEMQUERY
IF %STEALSUCCESS% EQU 1 (
	GOTO :EOF
)
IF %TEMPCOUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :STEALLOOP
)
GOTO :EOF


:STEALITEMQUERY
IF !STEALITEM%TEMPCOUNT%SUCCESS! EQU 1 (
	GOTO :EOF
)
SET /a RANSTEAL=%RANDOM% %% %BASESTEALCHANCE%
IF !ITEM%TEMPCOUNT%STEALCHANCE! GTR %RANSTEAL% (
	CALL :STEALSUCCESS
)
GOTO :EOF



:STEALSUCCESS
SET /a STEALSUCCESS = 1
SET /a STEALSUCCESSCOUNT = %STEALSUCCESSCOUNT% + 1
SET /a STEALITEM%TEMPCOUNT%SUCCESS = 1
SET /a TEMP = !ENEMY%ENEMYID%SET%REWARDSET%STEAL%TEMPCOUNT%!
SET TEMPTYPE=!ENEMY%ENEMYID%SET%REWARDSET%STEAL%TEMPCOUNT%TYPE!
SET /a PLAYER%TEMPTYPE%%TEMP%NUM = !PLAYER%TEMPTYPE%%TEMP%NUM! + 1
SET /a MAXSPACENUM = 49
SET STEALREWARD%TEMPCOUNT%=!SPACES%MAXSPACENUM%!
GOTO :EOF

:SUCCESS
ECHO You have successfully stolen one !%TEMPTYPE%%TEMP%NAME!^^!
ECHO.
CALL :WAITFORTHREE
GOTO :EOF

:FAIL
ECHO You failed to steal from the %ENEMYNAME%
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
