SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT% + 1
SET TEMP=!SKILL%COUNT%UNLOCKFIELD!
SET /a SKILL%COUNT%UNLOCKCOUNT = !%TEMP%!
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOPSTART
)
SET /a SKILLID = 0
:LOOP2START
SET /a SKILLID = %SKILLID% + 1
IF !PLAYERSKILL%SKILLID%EARNED! EQU 1 (
	GOTO :LOOP2END
) ELSE IF !SKILL%SKILLID%UNLOCKCOUNT! GEQ !SKILL%SKILLID%UNLOCKTHRESHOLD! (
	CALL "%SKILLRESOURCEPATH%\earnskill.bat"
)
:LOOP2END
IF %SKILLID% LSS %SKILLTOT% (
	GOTO :LOOP2START
)
GOTO :EOF