CALL :SETLOCATION
IF %HOMETOWNQUESTPHASE% EQU 1 (
	IF !%MAP%CHEST1OPEN! EQU 1 (
		SET /a HOMETOWNQUESTPHASE = 2
	)
)
CLS
ECHO.
CALL :PHASE%HOMETOWNQUESTPHASE%
IF %HOMETOWNQUESTPHASE% NEQ 0 (
	IF %HOMETOWNQUESTPHASE% NEQ 2 (
		TIMEOUT /T 3 > nul
	)
)

GOTO :EOF

:SETLOCATION
SET /a PLAYERXCOORD = 2
SET /a PLAYERYCOORD = 5
GOTO :EOF

:PHASE0
CALL "%CUTSCENERESOURCEPATH%\cutscene2.bat"
IF %HOMETOWNQUESTPHASE% EQU 2 (
	CALL :PHASE2
)
GOTO :EOF

:PHASE1
ECHO     %UNCLENAME%: Go and open the chest and then come back here^^!
GOTO :EOF

:PHASE2
IF %PLAYERWEAPONID% EQU 0 (
	CALL "%CUTSCENERESOURCEPATH%\cutscene3.bat"
	REM CALL :EQUIPCHICKENBONE
) ELSE (
	ECHO     %UNCLENAME%: Oh, it seems you already know how to equip things...
	ECHO     I'll leave you to it then, get yourself round %FRIENDNAME%'s house
	SET /a HOMETOWNQUESTPHASE = 3
)
GOTO :EOF

:PHASE3
ECHO There's no answer, %UNCLENAME% must be fast asleep
GOTO :EOF

:PHASE4
ECHO I think I'll let %UNCLENAME% sleep, %FRIENDNAME% and I are going to see %GIRLNAME%
GOTO :EOF

:PHASE5
ECHO     %UNCLENAME%: Can you pop home for a bit? You haven't seen your mother all day
GOTO :EOF

:PHASE6
ECHO I'd best get over to the old mill, %FRIENDNAME% and %GIRLNAME% will be waiting for me
GOTO :EOF

:EQUIPCHICKENBONE
SET /a CHOICE = %CBONEID%
SET PLAYERWEAPON=!WEAPON%CHOICE%NAME!
SET /a PLAYERWEAPONID = %CHOICE%
SET /a PLAYEREQUIPSTR=!WEAPON%CHOICE%STR!
SET /a PLAYEREQUIPMAG=!WEAPON%CHOICE%MAG!
SET /a PLAYEREQUIPACC=!WEAPON%CHOICE%ACC!
SET /a PLAYERSKILL%MEDID%ENABLED = 1
GOTO :EOF