ECHO SET /a PERSISTENTAUTOBATTLE = %PERSISTENTAUTOBATTLE% > "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a MEMORYAUTOBATTLE = %MEMORYAUTOBATTLE% >> "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a MUSICENABLED = %MUSICENABLED% >> "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a SFXENABLED = %SFXENABLED% >> "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a EXPLICIT = %EXPLICIT% >> "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a ANIMATIONENABLED = %ANIMATIONENABLED% >> "%OPTIONSRESOURCEPATH%\options.bat"
ECHO SET /a CUTSCENEPROGRESSION = %CUTSCENEPROGRESSION% >> "%OPTIONSRESOURCEPATH%\options.bat"

