IF !%TARGET%AIM! EQU 1 (
	SET /a %TARGET%ACC = !%TARGET%ACC!*9999
)
IF !%TARGET%HIDE! EQU 1 (
	SET /a %TARGET%EVA = !%TARGET%EVA!*3
)
IF /I %TARGET% EQU PLAYER (
	CALL :LOSEBUFFQUERY
)
GOTO :EOF

:LOSEBUFFQUERY
IF %PLAYERAIM% EQU 0 (
	IF %PLAYERHIDE% EQU 0 (
		GOTO :EOF
	)
)
SET /a RANFACT=%RANDOM% %% 100
IF %PLAYERAIM% EQU 1 (
	IF %RANFACT% LSS 20 (
		SET /a PLAYERAIM = 0
	)
)
SET /a RANFACT=%RANDOM% %% 100
IF %PLAYERHIDE% EQU 1 (
	IF %RANFACT% LSS 20 (
		SET /a PLAYERHIDE = 0
	)
)
GOTO :EOF