:POISONCALCULATION
SET /a POISONAMOUNT = (!%TARGET%MAXHP!*!%TARGETER%MAG!)/(15*!%TARGET%SPR!)
IF %POISONAMOUNT% GTR !%TARGET%MAXHP!/15 (
	SET /a POISONAMOUNT = !%TARGET%MAXHP!/15
)
SET /a %TARGET%HP = !%TARGET%HP!-%POISONAMOUNT%
IF !%TARGET%HP! LEQ 0 (
	SET /a %TARGET%HP = 1
)
ECHO. Poison hurt !%TARGET%NAME! by %POISONAMOUNT% HP
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF