SET /a REGENAMOUNT = !%TARGET%MAG!*!REST%CUREID%EFFECT1AMOUNT!*%RANFACT%/300
SET /a %TARGET%HP = !%TARGET%HP!+%REGENAMOUNT%
IF !%TARGET%HP! GTR !%TARGET%MAXHP! (
	SET /a %TARGET%HP = !%TARGET%MAXHP!
)
ECHO. Regen healed !%TARGET%NAME! by %REGENAMOUNT% HP
ECHO.
CALL :WAITFORTWO
GOTO :EOF



:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF