:STATUSTURNCOUNTS
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
SET STATUS=BLIND
CALL :STATUSQUERY
SET STATUS=SILENCE
CALL :STATUSQUERY
SET STATUS=POISON
CALL :STATUSQUERY
SET STATUS=SLOW
CALL :STATUSQUERY
SET STATUS=SLEEP
CALL :STATUSQUERY
SET STATUS=CONFUSION
CALL :STATUSQUERY
SET STATUS=STOP
CALL :STATUSQUERY
SET STATUS=HASTE
CALL :STATUSQUERY
SET STATUS=PROTECT
CALL :STATUSQUERY
SET STATUS=SHELL
CALL :STATUSQUERY
SET STATUS=REFLECT
CALL :STATUSQUERY
SET STATUS=REGEN
CALL :STATUSQUERY
GOTO :EOF


:STATUSQUERY
SET TARGET=PLAYER
CALL :STATUSCALCULATIONS
SET TARGET=ENEMY
CALL :STATUSCALCULATIONS
GOTO :EOF

:STATUSCALCULATIONS
IF !%TARGET%%STATUS%! EQU 1 (
	CALL :REDUCETURNCOUNT
) ELSE (
	GOTO :EOF
)
CALL :STATUSACTIVEQUERY
GOTO :EOF

:REDUCETURNCOUNT
IF !%TARGET%%STATUS%TURNCOUNT! GTR 0 (	
	SET /a %TARGET%%STATUS%TURNCOUNT = !%TARGET%%STATUS%TURNCOUNT!-1
)
GOTO :EOF

:STATUSACTIVEQUERY
IF !%TARGET%%STATUS%TURNCOUNT! EQU 0 ( 
	SET /a %TARGET%%STATUS% = 0
)
GOTO :EOF







:PLAYERBLINDQUERY
IF %PLAYERBLIND% EQU 0 (
SET /a PLAYERBLINDTURNCOUNT = 9999
)
IF %PLAYERBLIND% GTR 0 (
	IF %PLAYERBLINDTURNCOUNT% GTR 0 (	
		SET /a PLAYERBLINDTURNCOUNT = %PLAYERBLINDTURNCOUNT%-1
	)
	IF %PLAYERBLINDTURNCOUNT% EQU 0 (
	ECHO You're no longer Blinded
	ECHO.
	SET /a PLAYERBLIND = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO You're still Blind, you will be blind for %PLAYERBLINDTURNCOUNT% more turns
	ECHO.
	)
)
IF %ENEMYSILENCE% EQU 0 (
SET /a ENEMYSILENCETURNCOUNT = 9999
)
IF %ENEMYSILENCE% GTR 0 (
	IF %ENEMYSILENCETURNCOUNT% GTR 0 (
		SET /a ENEMYSILENCETURNCOUNT = %ENEMYSILENCETURNCOUNT%-1
	)
	IF %ENEMYSILENCETURNCOUNT% EQU 0 (

	ECHO %ENEMYNAME%'s no longer Silenced
	ECHO.
	SET /a ENEMYSILENCE =0
	CALL :WAITFORONE
	) ELSE (
	ECHO %ENEMYNAME% is still Silenced
	ECHO.
	)
)
IF %PLAYERSILENCE% EQU 0 (
SET /a PLAYERSILENCETURNCOUNT = 9999
)
IF %PLAYERSILENCE% GTR 0 (
	IF %PLAYERSILENCETURNCOUNT% GTR 0 (
		SET /a PLAYERSILENCETURNCOUNT = %PLAYERSILENCETURNCOUNT%-1
	)
	IF %PLAYERSILENCETURNCOUNT% EQU 0 (
	ECHO You're no longer Silenced
	ECHO.
	SET /a PLAYERSILENCE =0
	CALL :WAITFORONE
	) ELSE (
	ECHO You're still Silenced
	ECHO.
	)
)
IF %ENEMYPOISON% EQU 0 (
SET /a ENEMYPOISONTURNCOUNT = 9999
)
IF %ENEMYPOISON% GTR 0 (
	SET /a ENEMYPOISONDAM = %ENEMYMAXHP%*%PLAYERMAG%/(15*%ENEMYSPR%)
	IF %ENEMYPOISONDAM% GTR %ENEMYMAXHP%/15 (
		SET /a ENEMYPOISONDAM = %ENEMYMAXHP%/15
	)
)
IF %ENEMYPOISON% GTR 0 (
	IF %ENEMYPOISONTURNCOUNT% GTR 0 (
		SET /a ENEMYPOISONTURNCOUNT = %ENEMYPOISONTURNCOUNT%-1
	)
	IF %ENEMYPOISONTURNCOUNT% EQU 0 (
	ECHO %ENEMYNAME%'s no longer Poisoned
	ECHO.
	SET /a ENEMYPOISON = 0
	CALL :WAITFORONE
	 ) ELSE (
		ECHO %ENEMYNAME% is still Poisoned
		ECHO.
		CALL :WAITFORONE
		ECHO %ENEMYNAME% was hurt by the poison for %ENEMYPOISONDAM% HP
		ECHO.
		CALL :WAITFORONE
		SET /a ENEMYHP = %ENEMYHP% - %ENEMYPOISONDAM%
		CALL :POISONHPQUERY
	)
)
IF %PLAYERPOISON% EQU 0 (
SET /a PLAYERPOISONTURNCOUNT = 9999
)
IF %PLAYERPOISON% GTR 0 (
	SET /a PLAYERPOISONDAM=(%PLAYERMAXHP%*%ENEMYMAG%)/(15*%PLAYERSPR%)
	IF %PLAYERPOISONDAM% GTR %PLAYERMAXHP%/15 (
		SET /a PLAYERPOISONDAM = %PLAYERMAXHP%/15
	)
)
IF %PLAYERPOISON% GTR 0 (
	IF %PLAYERPOISONTURNCOUNT% GTR 0 (
		SET /a PLAYERPOISONTURNCOUNT = %PLAYERPOISONTURNCOUNT%-1
	)
	IF %PLAYERPOISONTURNCOUNT% EQU 0 (
	ECHO You're no longer Poisoned
	ECHO.
	SET /a PLAYERPOISON = 0
	CALL :WAITFORONE
	 ) ELSE (
	ECHO You're still Poisoned
	ECHO.
	CALL :WAITFORONE
	ECHO You were hurt by the poison for %PLAYERPOISONDAM% HP
	ECHO.
	CALL :WAITFORONE
	SET /a PLAYERHP = %PLAYERHP% - %PLAYERPOISONDAM%
	CALL :POISONHPQUERY
	)
)
IF %ENEMYSLOW% EQU 0 (
SET /a ENEMYSLOWTURNCOUNT = 9999
)
IF %ENEMYSLOW% GTR 0 (
	IF %ENEMYSLOWTURNCOUNT% GTR 0 (
		SET /a ENEMYSLOWTURNCOUNT = %ENEMYSLOWTURNCOUNT%-1
	)
	IF %ENEMYSLOWTURNCOUNT% EQU 0 (
	ECHO %ENEMYNAME%'s no longer Slowed
	ECHO.
	SET /a ENEMYSLOW = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO %ENEMYNAME% is still Slowed
	ECHO.
	)
)
IF %PLAYERSLOW% EQU 0 (
SET /a PLAYERSLOWTURNCOUNT = 9999
)
IF %PLAYERSLOW% GTR 0 (
	IF %PLAYERSLOWTURNCOUNT% GTR 0 (
		SET /a PLAYERSLOWTURNCOUNT = %PLAYERSLOWTURNCOUNT%-1
	)
	IF %PLAYERSLOWTURNCOUNT% EQU 0 (
	ECHO You're no longer Slowed
	ECHO.
	SET /a PLAYERSLOW = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO You're still Slowed
	ECHO.
	)
)
IF %ENEMYSLEEP% EQU 0 (
SET /a ENEMYSLEEPTURNCOUNT = 9999
)
IF %ENEMYSLEEP% GTR 0 (
	IF %ENEMYSLEEPTURNCOUNT% GTR 0 (
		SET /a ENEMYSLEEPTURNCOUNT = %ENEMYSLEEPTURNCOUNT%-1
	)
	IF %ENEMYSLEEPTURNCOUNT% EQU 0 (
	ECHO.
	ECHO %ENEMYNAME% woke up
	ECHO.
	SET /a ENEMYSLEEP = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO %ENEMYNAME% is still Fast Asleep
	ECHO.
	)
)
IF %PLAYERSLEEP% EQU 0 (
SET /a PLAYERSLEEPTURNCOUNT = 9999
)
IF %PLAYERSLEEP% GTR 0 (
	IF %PLAYERSLEEPTURNCOUNT% GTR 0 (
		SET /a PLAYERSLEEPTURNCOUNT = %PLAYERSLEEPTURNCOUNT%-1
	)
	IF %PLAYERSLEEPTURNCOUNT% EQU 0 (
	ECHO You woke up
	ECHO.
	SET /a PLAYERSLEEP = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO You are still Fast Asleep
	ECHO.
	)
)
IF %ENEMYCONFUSION% EQU 0 (
SET /a ENEMYCONFUSIONTURNCOUNT = 9999
)
IF %ENEMYCONFUSION% GTR 0 (
	IF %ENEMYCONFUSIONTURNCOUNT% GTR 0 (
		SET /a ENEMYCONFUSIONTURNCOUNT = %ENEMYCONFUSIONTURNCOUNT%-1
	)
	IF %ENEMYCONFUSIONTURNCOUNT% EQU 0 (
	ECHO %ENEMYNAME%'s no longer Confused
	ECHO.
	SET /a ENEMYCONFUSION = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO %ENEMYNAME% is still Confused
	ECHO.
	)
)
IF %PLAYERCONFUSION% EQU 0 (
SET /a PLAYERCONFUSIONTURNCOUNT = 9999
)
IF %PLAYERCONFUSION% GTR 0 (
	IF %PLAYERCONFUSIONTURNCOUNT% GTR 0 (
		SET /a PLAYERCONFUSIONTURNCOUNT = %PLAYERCONFUSIONTURNCOUNT%-1
	)
	IF %PLAYERCONFUSIONTURNCOUNT% EQU 0 (
	ECHO You're no longer Confused
	ECHO.
	SET /a PLAYERCONFUSION = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO You are still Confused
	ECHO.
	)
)
IF %ENEMYSTOP% EQU 0 (
SET /a ENEMYSTOPTURNCOUNT = 9999
)
IF %ENEMYSTOP% GTR 0 (
	IF %ENEMYSTOPTURNCOUNT% GTR 0 (
		SET /a ENEMYSTOPTURNCOUNT = %ENEMYSTOPTURNCOUNT%-1
	)
	IF %ENEMYSTOPTURNCOUNT% EQU 0 (
	ECHO %ENEMYNAME%'s no longer Stopped
	ECHO.
	SET /a ENEMYSTOP = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO %ENEMYNAME% is still Stopped
	ECHO.
	)
)
IF %PLAYERSTOP% EQU 0 (
SET /a PLAYERSTOPTURNCOUNT = 9999
)
IF %PLAYERSTOP% GTR 0 (
	IF %PLAYERSTOPTURNCOUNT% GTR 0 (
		SET /a PLAYERSTOPTURNCOUNT = %PLAYERSTOPTURNCOUNT%-1
	)
	IF %PLAYERSTOPTURNCOUNT% EQU 0 (
	ECHO You're no longer Stopped
	ECHO.
	SET /a PLAYERSTOP = 0
	CALL :WAITFORONE
	) ELSE (
	ECHO You're still Stopped
	ECHO.
	)
)
IF %ENEMYREGEN% EQU 0 (
SET /a ENEMYREGENTURNCOUNT = 9999
)
IF %ENEMYREGEN% GTR 0 (
	IF %ENEMYREGENTURNCOUNT% GTR 0 (
		SET /a ENEMYREGENTURNCOUNT = %ENEMYREGENTURNCOUNT%-1
	)
	IF %ENEMYREGENTURNCOUNT% EQU 0 (
	ECHO %ENEMYNAME% no longer has Regen active
	ECHO.
	SET /a ENEMYREGEN = 0
	CALL :WAITFORONE
	) ELSE (
		ECHO %ENEMYNAME%'s Regen is still active and healed them by %ENEMYREGENDAM% HP
		ECHO.
		SET /a ENEMYHP= %ENEMYHP% + %ENEMYREGENDAM%
		IF %ENEMYHP% GTR %ENEMYMAXHP% (
			SET /a ENEMYHP = %ENEMYMAXHP%
		)
	)
)
IF %PLAYERREGEN% EQU 0 (
SET /a PLAYERREGENTURNCOUNT = 9999
)
	SET /a PLAYERPOISONDAM=(%PLAYERMAXHP%*%ENEMYMAG%)/(15*%PLAYERSPR%)
	IF %PLAYERPOISONDAM% GTR %PLAYERMAXHP%/15 (
		SET /a PLAYERPOISONDAM = %PLAYERMAXHP%/15
	)
IF %PLAYERREGEN% GTR 0 (
	IF %PLAYERREGENTURNCOUNT% GTR 0 (
		SET /a PLAYERREGENTURNCOUNT = %PLAYERREGENTURNCOUNT%-1
	)
	IF %PLAYERREGENTURNCOUNT% EQU 0 (
	ECHO You no longer have Regen active
	ECHO.
	SET /a PLAYERREGEN = 0
	CALL :WAITFORONE
	) ELSE (
		ECHO Your Regen is still active and healed you by %PLAYERREGENDAM% HP
		ECHO.
		SET /a PLAYERHP= %PLAYERHP% + %PLAYERREGENDAM%
		IF %PLAYERHP% GTR %PLAYERMAXHP% (
			SET /a PLAYERHP = %PLAYERMAXHP%
		)
	)
)

IF %ENEMYHASTE% EQU 0 (
SET /a ENEMYHASTETURNCOUNT = 9999
)
IF %ENEMYHASTE% GTR 0 (
	IF %ENEMYHASTETURNCOUNT% GTR 0 (
		SET /a ENEMYHASTETURNCOUNT = %ENEMYHASTETURNCOUNT%-1
	)
	IF %ENEMYHASTETURNCOUNT% EQU 0 (
		ECHO %ENEMYNAME%'s Haste Spell has worn off
		ECHO.
		SET /a ENEMYHASTE = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO %ENEMYNAME%'s Haste Spell is still active
		ECHO.
	)
)
IF %PLAYERHASTE% EQU 0 (
SET /a PLAYERHASTETURNCOUNT = 9999
)
IF %PLAYERHASTE% GTR 0 (
	IF %PLAYERHASTETURNCOUNT% GTR 0 (
		SET /a PLAYERHASTETURNCOUNT = %PLAYERHASTETURNCOUNT%-1
	)
	IF %PLAYERHASTETURNCOUNT% EQU 0 (
		ECHO Your Haste Spell has worn off
		ECHO.
		SET /a PLAYERHASTE = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO Your Haste Spell is still active
		ECHO.
	)
)




IF %ENEMYPROTECT% EQU 0 (
SET /a ENEMYPROTECTTURNCOUNT = 9999
)
IF %ENEMYPROTECT% GTR 0 (
	IF %ENEMYPROTECTTURNCOUNT% GTR 0 (
		SET /a ENEMYPROTECTTURNCOUNT = %ENEMYPROTECTTURNCOUNT%-1
	)
	IF %ENEMYPROTECTTURNCOUNT% EQU 0 (
		ECHO %ENEMYNAME%'s Protect Spell has worn off
		ECHO.
		SET /a ENEMYPROTECT = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO %ENEMYNAME%'s Protect Spell is still active
		ECHO.
	)
)
IF %PLAYERPROTECT% EQU 0 (
SET /a PLAYERPROTECTTURNCOUNT = 9999
)
IF %PLAYERPROTECT% GTR 0 (
	IF %PLAYERPROTECTTURNCOUNT% GTR 0 (
		SET /a PLAYERPROTECTTURNCOUNT = %PLAYERPROTECTTURNCOUNT%-1
	)
	IF %PLAYERPROTECTTURNCOUNT% EQU 0 (
		ECHO Your Protect Spell has worn off
		ECHO.
		SET /a PLAYERPROTECT = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO Your Protect Spell is still active
		ECHO.
	)
)


IF %ENEMYSHELL% EQU 0 (
SET /a ENEMYSHELLTURNCOUNT = 9999
)
IF %ENEMYSHELL% GTR 0 (
	IF %ENEMYSHELLTURNCOUNT% GTR 0 (
		SET /a ENEMYSHELLTURNCOUNT = %ENEMYSHELLTURNCOUNT%-1
	)
	IF %ENEMYSHELLTURNCOUNT% EQU 0 (
		ECHO %ENEMYNAME%'s Shell Spell has worn off
		ECHO.
		SET /a ENEMYSHELL = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO %ENEMYNAME%'s Shell Spell is still active
		ECHO.
	)
)
IF %PLAYERSHELL% EQU 0 (
SET /a PLAYERSHELLTURNCOUNT = 9999
)
IF %PLAYERSHELL% GTR 0 (
	IF %PLAYERSHELLTURNCOUNT% GTR 0 (
		SET /a PLAYERSHELLTURNCOUNT = %PLAYERSHELLTURNCOUNT%-1
	)
	IF %PLAYERSHELLTURNCOUNT% EQU 0 (
		ECHO Your Shell Spell has worn off
		ECHO.
		SET /a PLAYERSHELL = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO Your Shell Spell is still active
		ECHO.
	)
)


IF %ENEMYREFLECT% EQU 0 (
SET /a ENEMYREFLECTTURNCOUNT = 9999
)
IF %ENEMYREFLECT% GTR 0 (
	IF %ENEMYREFLECTTURNCOUNT% GTR 0 (
		SET /a ENEMYREFLECTTURNCOUNT = %ENEMYREFLECTTURNCOUNT%-1
	)
	IF %ENEMYREFLECTTURNCOUNT% EQU 0 (
		ECHO %ENEMYNAME%'s Reflect Spell has worn off
		ECHO.
		SET /a ENEMYREFLECT = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO %ENEMYNAME%'s Reflect Spell is still active
		ECHO.
	)
)
IF %PLAYERREFLECT% EQU 0 (
SET /a PLAYERREFLECTTURNCOUNT = 9999
)
IF %PLAYERREFLECT% GTR 0 (
	IF %PLAYERREFLECTTURNCOUNT% GTR 0 (
		SET /a PLAYERREFLECTTURNCOUNT = %PLAYERREFLECTTURNCOUNT%-1
	)
	IF %PLAYERREFLECTTURNCOUNT% EQU 0 (
		ECHO Your Reflect Spell has worn off
		ECHO.
		SET /a PLAYERREFLECT = 0
		CALL :WAITFORONE
	) ELSE (
		ECHO Your Reflect Spell is still active
		ECHO.
	)
)
GOTO :EOF

:POISONHPQUERY
IF %PLAYERHP% LEQ 0 (
	SET /a PLAYERHP = 1
)
IF %ENEMYHP% LEQ 0 (
	SET /a ENEMYHP = 1
)
GOTO :EOF


:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF