:START
CLS
ECHO.
IF %DWARFTOT% EQU 0 (
	ECHO You don't have any dwarves in your employ
	ECHO.
	pause
	GOTO :EOF
)
ECHO Dwarf Sultan: Who's salary would you like to adjust?
ECHO.
SET /a COUNT = 0
:DWARFLOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = 12 - !DWARF%COUNT%NAMELENGTH!
ECHO. %COUNT% - !DWARF%COUNT%NAME!!SPACES%SPACENUM%!!DWARF%COUNT%SALARY! Gil
IF %COUNT% LSS %DWARFTOT% (
	GOTO :DWARFLOOP
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P CHOICE=
ECHO.
IF "%CHOICE%" EQU "" (
	GOTO :CHOICE
) ELSE IF "%CHOICE%" EQU "0" (
	GOTO :EOF
)
IF %CHOICE% GTR %DWARFTOT% (
	GOTO :CHOICE
) ELSE IF %CHOICE% LSS 0 (
	GOTO :CHOICE
)
CALL :ADJUSTSALARYQUERY
GOTO :START


:ADJUSTSALARYQUERY
CALL :EXPECTEDCALC
CLS
ECHO.
ECHO !DWARF%CHOICE%NAME!'s current salary is !DWARF%CHOICE%SALARY!
ECHO They are %HAPPINESSVAR% with this salary.
ECHO.
ECHO How much would you like to pay them?
ECHO.
ECHO. 0 - Back
ECHO.
:SALARYCHOICE
SET /P SALARYCHOICE=
ECHO.
IF "%SALARYCHOICE%" EQU "" (
	GOTO :SALARYCHOICE
) ELSE IF "%SALARYCHOICE%" EQU "0" (
	GOTO :EOF
)
IF %SALARYCHOICE% LSS 0 (
	ECHO You evil cunt, choose again
	ECHO.
	GOTO :SALARYCHOICE
) ELSE IF %SALARYCHOICE% GTR 99999 (
	ECHO That's a bit excessive don't you think. Let's be sensible
	ECHO.
	GOTO :SALARYCHOICE
)
CALL :ADJUSTSALARYQUERY
GOTO :EOF


:EXPECTEDCALC
SET /a ARROGANCE = (2*!DWARF%CHOICE%LVL!) - !DWARF%CHOICE%SAT!
SET /a TEMP = (!DWARF%CHOICE%LVL!/2) + 1
IF %ARROGANCE% LSS %TEMP% (
	SET /a ARROGANCE = %TEMP%
)
SET /a EXPECTEDSALARY = !DWARF%CHOICE%LVL!*%ARROGANCE%/2
SET /a HAPPINESS = (!DWARF%CHOICE%SALARY!*100)/%EXPECTEDSALARY%
IF %HAPPINESS% LSS 40 (
	SET HAPPINESSVAR=very unhappy
) ELSE IF %HAPPINESS% LSS 80 (
	SET HAPPINESSVAR=unhappy
) ELSE IF %HAPPINESS% LSS 120 (
	SET HAPPINESSVAR=satisfied
) ELSE IF %HAPPINESS% LSS 160 (
	SET HAPPINESSVAR=happy
) ELSE (
	SET HAPPINESSVAR=very happy
)
GOTO :EOF

:ADJUSTSALARYQUERY
CALL :NEWEXPECTEDCALC
CLS
ECHO.
ECHO If you pay !DWARF%CHOICE%NAME! %SALARYCHOICE% Gil they will be %HAPPINESSVAR%
ECHO.
ECHO Would you like to go ahead with the change?
ECHO.
ECHO. 1 - Yes
ECHO. 0 - Actually I've changed my mind
ECHO.
:CONFIRMATION
SET /P CONFIRMATION=
IF "%CONFIRMATION%" EQU "1" (
	CALL :ADJUSTSALARY
) ELSE IF "%CONFIRMATION%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :CONFIRMATION
)
GOTO :EOF


:NEWEXPECTEDCALC
::My feeble attempt to balance this
SET /a ARROGANCE = (2*!DWARF%DWARFCOUNT%LVL!) - !DWARF%DWARFCOUNT%SAT!
SET /a TEMP = (!DWARF%DWARFCOUNT%LVL!/2) + 1
IF %ARROGANCE% LSS %TEMP% (
	SET /a ARROGANCE = %TEMP%
)
SET /a EXPECTEDSALARY = !DWARF%CHOICE%LVL!*%ARROGANCE%/2
SET /a HAPPINESS = (%SALARYCHOICE%*100)/%EXPECTEDSALARY%
IF %HAPPINESS% LSS 40 (
	SET HAPPINESSVAR=very unhappy
) ELSE IF %HAPPINESS% LSS 80 (
	SET HAPPINESSVAR=unhappy
) ELSE IF %HAPPINESS% LSS 120 (
	SET HAPPINESSVAR=satisfied
) ELSE IF %HAPPINESS% LSS 160 (
	SET HAPPINESSVAR=happy
) ELSE (
	SET HAPPINESSVAR=very happy
)
GOTO :EOF


:ADJUSTSALARY
SET /a DWARF%CHOICE%SALARY = %SALARYCHOICE%
GOTO :EOF
