CALL "%DYNAMICRESOURCEPATH%\dynamicdwarfequipmentstatsshop.bat"
SET /a SELECTED = 1
:START
CLS
ECHO.
ECHO Dwarf Sultan: Which %TYPE% would you like to buy?
ECHO.
ECHO You have %PLAYERGIL% Gil
ECHO.
CALL "%MISCRESOURCEPATH%\menu2.bat"
IF %VARSELECTED% EQU 1 (
	CALL :SELECTED
)
IF %BACK% EQU 1 (
	GOTO :EOF
)
GOTO :START

:SELECTED
IF %PLAYERGIL% GTR !%TYPE%%SELECTED%COST! (
	SET /a SUCCESS = 1
	CALL :BUY
) ELSE (
	CLS
	ECHO.
	ECHO Dwarf Sultan: You don't have enough gil for that
	ECHO.
	SET /a SUCCESS = 0
	CALL :WAITFORTWO
)
GOTO :EOF

:BUY
SET /a PLAYERGIL = %PLAYERGIL% - !%TYPE%%SELECTED%COST!
SET /a PLAYER%TYPE%%SELECTED%NUM = !PLAYER%TYPE%%SELECTED%NUM! + 1
CLS
ECHO.
ECHO Dwarf Sultan: A fine choice sir, here you go
ECHO.
ECHO You now have !PLAYER%TYPE%%SELECTED%NUM! !%TYPE%%SELECTED%NAME!s
ECHO.
CALL :WAITFORTHREE
GOTO :EOF





:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
