:START
CLS
ECHO.
IF %DWARFTOT% EQU 0 (
	ECHO You don't have any dwarves in your employ
	ECHO.
	CALL :WAITFORTHREE
	GOTO :EOF
)
ECHO Here's a list of your dwarves and their stats
ECHO.
SET /a COUNT = 0
ECHO. Name           Level    Strength   Skill    Persistence  Satisfaction  Salary    Happiness
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM1 = 15 - !DWARF%COUNT%NAMELENGTH!
IF !DWARF%COUNT%LVL! LSS 10 (
	SET /a SPACENUM2 = 8
) ELSE IF !DWARF%COUNT%LVL! LSS 100 (
	SET /a SPACENUM2 = 7
) ELSE (
	SET /a SPACENUM2 = 6
)
IF !DWARF%COUNT%BASESTR! LSS 10 (
	SET /a SPACENUM3 = 10
) ELSE IF !DWARF%COUNT%BASESTR! LSS 100 (
	SET /a SPACENUM3 = 9
) ELSE (
	SET /a SPACENUM3 = 8
)
IF !DWARF%COUNT%BASESKL! LSS 10 (
	SET /a SPACENUM4 = 8
) ELSE IF !DWARF%COUNT%BASESKL! LSS 100 (
	SET /a SPACENUM4 = 7
) ELSE (
	SET /a SPACENUM4 = 6
)
IF !DWARF%COUNT%BASEPER! LSS 10 (
	SET /a SPACENUM5 = 12
) ELSE IF !DWARF%COUNT%BASEPER! LSS 100 (
	SET /a SPACENUM5 = 11
) ELSE (
	SET /a SPACENUM5 = 10
)
IF !DWARF%COUNT%SAT! LSS 10 (
	SET /a SPACENUM6 = 13
) ELSE IF !DWARF%COUNT%SAT! LSS 100 (
	SET /a SPACENUM6 = 12
) ELSE (
	SET /a SPACENUM6 = 11
)
IF !DWARF%COUNT%SALARY! LSS 10 (
	SET /a SPACENUM7 = 9
) ELSE IF !DWARF%COUNT%SALARY! LSS 100 (
	SET /a SPACENUM7 = 8
) ELSE IF !DWARF%COUNT%SALARY! LSS 1000 (
	SET /a SPACENUM7 = 7
) ELSE IF !DWARF%COUNT%SALARY! LSS 10000 (
	SET /a SPACENUM7 = 6
) ELSE (
	SET /a SPACENUM7 = 5
)
SET /a ARROGANCE = (2*!DWARF%COUNT%LVL!) - !DWARF%COUNT%SAT!
SET /a TEMP = (!DWARF%COUNT%LVL!/2) + 1
IF %ARROGANCE% LSS %TEMP% (
	SET /a ARROGANCE = %TEMP%
)
SET /a EXPECTEDSALARY = !DWARF%COUNT%LVL!*%ARROGANCE%/2
SET /a HAPPINESS = (!DWARF%COUNT%SALARY!*100)/%EXPECTEDSALARY%
IF %HAPPINESS% LSS 40 (
	SET HAPPINESSVAR=Very Unhappy
) ELSE IF %HAPPINESS% LSS 80 (
	SET HAPPINESSVAR=Unhappy
) ELSE IF %HAPPINESS% LSS 120 (
	SET HAPPINESSVAR=Satisfied
) ELSE IF %HAPPINESS% LSS 160 (
	SET HAPPINESSVAR=Happy
) ELSE (
	SET HAPPINESSVAR=Very Happy
)
ECHO. !DWARF%COUNT%NAME!!SPACES%SPACENUM1%!!DWARF%COUNT%LVL!!SPACES%SPACENUM2%!!DWARF%COUNT%BASESTR!!SPACES%SPACENUM3%!!DWARF%COUNT%BASESKL!!SPACES%SPACENUM4%!!DWARF%COUNT%BASEPER!!SPACES%SPACENUM5%!!DWARF%COUNT%SAT!!SPACES%SPACENUM6%!!DWARF%COUNT%SALARY!!SPACES%SPACENUM7%!%HAPPINESSVAR%
IF %COUNT% LSS %DWARFTOT% (
	GOTO :LOOP
)
ECHO.
pause
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
