SET /a NEWDWARFTOT = 9
SET /a COUNT = 0
SET UPPERCHARS=ABCDEFGHIJKLMNOPQRSTUVWXYZ
SET LOWERCHARS1=abcdefghijklmnopqrstuvwxyz
SET LOWERCHARS2=abc
SET LOWERCHARS3=aeiou
SET LOWERCHARS=%LOWERCHARS1%%LOWERCHARS2%%LOWERCHARS3%
:GENERATELOOP
SET /a COUNT = %COUNT% + 1
CALL :SETNAME
CALL :SETSTATS
IF %COUNT% LSS %NEWDWARFTOT% (
	GOTO :GENERATELOOP
)
GOTO :EOF




:SETNAME
SET /a NEWDWARF%COUNT%NAMELENGTH = (%RANDOM% %% 7) + 3
SET /a TEMP = (%RANDOM% %% 26)
SET NEWDWARF%COUNT%NAME=!UPPERCHARS:~%TEMP%,1!
SET /a LENGTHCOUNT = 1
:NAMELOOP
SET /a LENGTHCOUNT = %LENGTHCOUNT% + 1
SET /a TEMP = (%RANDOM% %% 34)
SET NEWDWARF%COUNT%NAME=!NEWDWARF%COUNT%NAME!!LOWERCHARS:~%TEMP%,1!
IF %LENGTHCOUNT% LSS !NEWDWARF%COUNT%NAMELENGTH! (
	GOTO :NAMELOOP
)
GOTO :EOF



:SETSTATS
SET /a NEWDWARF%COUNT%LVL = (%RANDOM% %% %PLAYERLVL%) + 1
SET /a NEWDWARF%COUNT%EXP = 0
SET /a TEMP = (%DWARFPOINTSPERLEVELUP%*100)/4
SET /a TEMP2 = (%RANDOM% %% 80) + 40
SET /a NEWDWARF%COUNT%BASESTR = (!NEWDWARF%COUNT%LVL!*%TEMP%*%TEMP2%)/10000
SET /a TEMP2 = (%RANDOM% %% 80) + 40
SET /a NEWDWARF%COUNT%BASESKL = (!NEWDWARF%COUNT%LVL!*%TEMP%*%TEMP2%)/10000
SET /a TEMP2 = (%RANDOM% %% 80) + 40
SET /a NEWDWARF%COUNT%BASEPER = (!NEWDWARF%COUNT%LVL!*%TEMP%*%TEMP2%)/10000
SET /a TEMP = !NEWDWARF%COUNT%LVL!*%DWARFPOINTSPERLEVELUP%
SET /a NEWDWARF%COUNT%SAT = %TEMP% - (!NEWDWARF%COUNT%BASESTR! + !NEWDWARF%COUNT%BASESKL! + !NEWDWARF%COUNT%BASEPER!)
:RETRY
SET /a TEMP = (%RANDOM% %% 9) + 1
IF %TEMP% GTR 9 (
	GOTO :RETRY
) ELSE IF %TEMP% LEQ 0 (
	GOTO :RETRY
)
SET NEWDWARF%COUNT%SPECIAL=!MINEITEM%TEMP%SPECIAL!
SET NEWDWARF%COUNT%SPECIALDISPLAY=!MINEITEM%TEMP%SPECIALDISPLAY!
GOTO :EOF