:START
CLS
ECHO.
ECHO Dwarf Sultan: You can expand your mine to allow you to dig for different things
ECHO.
ECHO               What extra mines would you like to gain access to?
ECHO.
ECHO You have %PLAYERGIL% Gil
ECHO.
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = 20 - !MINEITEM%COUNT%SPECIALDISPLAYLENGTH!
IF !MINEITEMTYPE%COUNT%UNLOCKED! EQU 0 (
	ECHO. %COUNT% - !MINEITEM%COUNT%SPECIALDISPLAY!!SPACES%SPACENUM%!!MINEITEM%COUNT%SPECIALUNLOCKCOST! Gil
) ELSE (
	ECHO. %COUNT% - !MINEITEM%COUNT%SPECIALDISPLAY!!SPACES%SPACENUM%!Purchased
)
IF %COUNT% LSS 9 (
	GOTO :LOOP
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P CHOICE=
ECHO.
IF "%CHOICE%" EQU "" (
	GOTO :CHOICE
) ELSE IF "%CHOICE%" EQU "0" (
	GOTO :EOF
)
IF %CHOICE% GTR 9 (
	GOTO :CHOICE
) ELSE IF %CHOICE% LSS 0 (
	GOTO :CHOICE
)
CALL :ALREADYUNLOCKEDQUERY
IF %ALREADYUNLOCKED% EQU 1 (
	GOTO :EOF
)
CALL :GILQUERY
IF %ENOUGHGIL% EQU 0 (
	GOTO :EOF
)
CALL :UNLOCKTYPE
GOTO :START

:ALREADYUNLOCKEDQUERY
IF !MINEITEMTYPE%CHOICE%UNLOCKED! EQU 1 (
	CLS
	ECHO Dwarf Sultan: You have already unlocked this part of the mine
	ECHO
	pause
	SET /a ALREADYUNLOCKED = 1
) ELSE (
	SET /a ALREADYUNLOCKED = 0
)
GOTO :EOF

:GILQUERY
IF %PLAYERGIL% LSS !MINEITEM%CHOICE%SPECIALUNLOCKCOST! (
	CLS
	ECHO.
	ECHO Dwarf Sultan: You don't have enough Gil for that
	ECHO.
	pause
	SET /a ENOUGHGIL = 0
	GOTO :EOF
) ELSE (
	SET /a ENOUGHGIL = 1
)
GOTO :EOF

:UNLOCKTYPE
SET /a MINEITEMTYPE%CHOICE%UNLOCKED = 1
SET /a PLAYERGIL = %PLAYERGIL% - !MINEITEM%CHOICE%SPECIALUNLOCKCOST!
CLS
ECHO.
ECHO Dwarf Sultan: You can now mine for !MINEITEM%CHOICE%SPECIALDISPLAY!^^!
ECHO.
pause
GOTO :EOF