@ECHO OFF
IF %BEATLEEROY% EQU 1 (
	GOTO :EOF
)
CALL :STARTMUSIC
CALL :INITIALISE
:LOOPSTART
CALL :SETLEEROYPOSITION
CALL :RESETROW
CALL :MAPDISPLAY
CALL :RESETOLDCELL
IF %LEEROYXCOORD% LSS 8 (
	GOTO :LOOPSTART
)
SET /a ENEMYID = %LEEROYID%
CALL "%BATTLESTARTRESOURCEPATH%\specialbattlestart.bat"
GOTO :EOF

:STARTMUSIC
SET TEMPPATH=%MUSICPATH%\Battle\Lj
SET /a STOP = 1
SET /a LOOP = 0
CALL "%MUSICPATH%\startmusic.bat"
GOTO :EOF

:INITIALISE
SET LEEROYRIGHT1A=  O ³
SET LEEROYRIGHT1B=  ±ÍÅ
SET LEEROYRIGHT1C=  Ù\ 
SET LEEROYRIGHT2A=  O ³
SET LEEROYRIGHT2B=  ±ÍÅ
SET LEEROYRIGHT2C= /)  
SET LEEROYLEFT1A=³ O  
SET LEEROYLEFT1B=ÅÍ±  
SET LEEROYLEFT1C= /À  
SET LEEROYLEFT2A=³ O  
SET LEEROYLEFT2B=ÅÍ±  
SET LEEROYLEFT2C=  (\ 
SET LEEROYUP1A=  O  
SET LEEROYUP1B=  ±  
SET LEEROYUP1C= ³  
SET LEEROYUP2A=  O  
SET LEEROYUP2B=  ±  
SET LEEROYUP2C=   ³ 
SET LEEROYDOWN1A= ³O  
SET LEEROYDOWN1B= Å±  
SET LEEROYDOWN1C= / \ 
SET LEEROYDOWN2A=  O³ 
SET LEEROYDOWN2B=  ±Å 
SET LEEROYDOWN2C= / \ 
SET /a LEEROYXCOORD = 0
SET /a LEEROYYCOORD = 2
SET /a RESETROW = %LEEROYYCOORD%
SET /a ALTERNATINGVAR = 1
GOTO :EOF

:SETLEEROYPOSITION
SET /a LEEROYXCOORD = %LEEROYXCOORD% + 1
IF %ALTERNATINGVAR% EQU 1 (
	SET /a ALTERNATINGVAR = 2
) ELSE IF %ALTERNATINGVAR% EQU 2 (
	SET /a ALTERNATINGVAR = 1
)
SET TEMP%RESETROW%-%LEEROYXCOORD%-A=!LEEROYRIGHT%ALTERNATINGVAR%A!
SET TEMP%RESETROW%-%LEEROYXCOORD%-B=!LEEROYRIGHT%ALTERNATINGVAR%B!
SET TEMP%RESETROW%-%LEEROYXCOORD%-C=!LEEROYRIGHT%ALTERNATINGVAR%C!
GOTO :EOF

:MAPDISPLAY
CLS
ECHO.
ECHO %MAPDISPLAYTP%
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
ECHO %MAPDISPLAYBM%
ECHO.
ECHO.
ECHO. Move:    W              8
ECHO.       A  S  D   or   4  5  6
ECHO.
ECHO. Press M or 0 to access the menu
ECHO.
ECHO. Press Q to quicksave, L to quickload
ECHO.
CALL :WAITFORZERO
PING 1.1.1.1 -n 1 -w 500 >NUL
GOTO :EOF

:RESETOLDCELL
SET TEMP%LEEROYYCOORD%-%LEEROYXCOORD%-A=!%MAP%%LEEROYYCOORD%-%LEEROYXCOORD%-A!
SET TEMP%LEEROYYCOORD%-%LEEROYXCOORD%-B=!%MAP%%LEEROYYCOORD%-%LEEROYXCOORD%-B!
SET TEMP%LEEROYYCOORD%-%LEEROYXCOORD%-C=!%MAP%%LEEROYYCOORD%-%LEEROYXCOORD%-C!
GOTO :EOF

:RESETROW
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!!TEMP%RESETROW%-10-A!!TEMP%RESETROW%-11-A!!TEMP%RESETROW%-12-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!!TEMP%RESETROW%-10-B!!TEMP%RESETROW%-11-B!!TEMP%RESETROW%-12-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!!TEMP%RESETROW%-10-C!!TEMP%RESETROW%-11-C!!TEMP%RESETROW%-12-C!º
GOTO :EOF





:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF