:CHOOSEDWARF
CLS
IF %DWARFTOT% EQU 0 (
	ECHO.
	ECHO You don't have any dwarves to sack^^!
	ECHO.
	pause
	GOTO :EOF
)
ECHO.
ECHO Dwarf Sultan: Who would you like to sack?
ECHO.
SET /a COUNT = 0
:CHOOSEDWARFLOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = 12 - !DWARF%COUNT%NAMELENGTH!
ECHO. %COUNT% - !DWARF%COUNT%NAME!!SPACES%SPACENUM%!(Level !DWARF%COUNT%LVL!)
IF %COUNT% LSS %DWARFTOT% (
	GOTO :CHOOSEDWARFLOOP
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P CHOICE=
ECHO.
IF "%CHOICE%" EQU "" (
	GOTO :CHOICE
) ELSE IF "%CHOICE%" EQU "0" (
	GOTO :EOF
)
IF %CHOICE% GTR %DWARFTOT% (
	GOTO :CHOICE
) ELSE IF %CHOICE% LSS 0 (
	GOTO :CHOICE
)
CALL :SACKDWARFQUERY
GOTO :CHOOSEDWARF

:SACKDWARFQUERY
CALL :EXPECTEDCALC
CLS
ECHO.
ECHO Dwarf Sultan: Here are !DWARF%CHOICE%NAME!'s stats:
ECHO.
ECHO Strength      !DWARF%CHOICE%BASESTR!
ECHO Skill         !DWARF%CHOICE%BASESKL!
ECHO Persistence   !DWARF%CHOICE%BASEPER!
ECHO Satisfaction  !DWARF%CHOICE%SAT!
ECHO Speciality    !DWARF%CHOICE%SPECIALDISPLAY!
ECHO They are %HAPPINESSVAR% with their salary of !DWARF%CHOICE%SALARY!
ECHO.
ECHO Dwarf Sultan: Are you sure you want to sack them?
ECHO.
ECHO. 1 - Yes
ECHO. 0 - Actually I've changed my mind
ECHO.
:CONFIRMATIONCHOICE
SET /P CONFIRMATION=
ECHO.
IF "%CONFIRMATION%" EQU "1" (
	CALL :SACKDWARF
) ELSE IF "%CONFIRMATION%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :CONFIRMATIONCHOICE
)
GOTO :EOF

:EXPECTEDCALC
SET /a ARROGANCE = (2*!DWARF%DWARFCOUNT%LVL!) - !DWARF%DWARFCOUNT%SAT!
SET /a EXPECTEDSALARY = !DWARF%CHOICE%LVL!*%ARROGANCE%/2
SET /a HAPPINESS = (!DWARF%CHOICE%SALARY!*100)/%EXPECTEDSALARY%
IF %HAPPINESS% LSS 40 (
	SET HAPPINESSVAR=very unhappy
) ELSE IF %HAPPINESS% LSS 80 (
	SET HAPPINESSVAR=unhappy
) ELSE IF %HAPPINESS% LSS 120 (
	SET HAPPINESSVAR=satisfied
) ELSE IF %HAPPINESS% LSS 160 (
	SET HAPPINESSVAR=happy
) ELSE (
	SET HAPPINESSVAR=very happy
)
GOTO :EOF

:SACKDWARF
SET /a OLDTEMP = %CHOICE% - 1
SET /a TEMP = %CHOICE%
SET /a DWARFTOT = %DWARFTOT% - 1
:SACKDWARFLOOP
SET /a OLDTEMP = %OLDTEMP% + 1
SET /a TEMP = %TEMP% + 1
SET DWARF%OLDTEMP%NAME=!DWARF%TEMP%NAME!
SET /a DWARF%OLDTEMP%NAMELENGTH = !DWARF%TEMP%NAMELENGTH!
SET /a DWARF%OLDTEMP%LVL = !DWARF%TEMP%LVL!
SET /a DWARF%OLDTEMP%EXP = !DWARF%TEMP%EXP!
SET /a DWARF%OLDTEMP%BASESTR = !DWARF%TEMP%BASESTR!
SET /a DWARF%OLDTEMP%BASESKL = !DWARF%TEMP%BASESKL!
SET /a DWARF%OLDTEMP%BASEPER = !DWARF%TEMP%BASEPER!
SET /a DWARF%OLDTEMP%SAT = !DWARF%TEMP%SAT!
SET /a DWARF%OLDTEMP%SPECIAL = !DWARF%TEMP%SPECIAL!
SET /a DWARF%OLDTEMP%SALARY = !DWARF%TEMP%SALARY!
SET /a DWARF%OLDTEMP%EQUIPSTR = !DWARF%TEMP%EQUIPSTR!
SET /a DWARF%OLDTEMP%EQUIPSKL = !DWARF%TEMP%EQUIPSTR!
SET /a DWARF%OLDTEMP%EQUIPPER = !DWARF%TEMP%EQUIPSTR!
SET DWARF%OLDTEMP%TYPE=!DWARF%TEMP%TYPE!
SET DWARF%OLDTEMP%TYPEDISPLAY=!DWARF%TEMP%TYPEDISPLAY!
SET /a DWARF%OLDTEMP%MINID = !DWARF%TEMP%MINID!
SET /a DWARF%OLDTEMP%MAXID = !DWARF%TEMP%MAXID!
IF %TEMP% LSS %DWARFTOT% (
	GOTO :SACKDWARFLOOP
)
GOTO :EOF