:START
IF EXIST "%MAPRESOURCEPATH%\%MAP%exceptions.bat" (
	CALL "%MAPRESOURCEPATH%\%MAP%exceptions.bat"
)
SET WORD=!%MAP%DISPLAYNAME!
CALL "%MISCRESOURCEPATH%\calculateword.bat"
SET /a MENUACCESSED = 0
CALL :STARTMUSIC
CALL :INITIALISE
CALL :SETUPTEMPMAPVARS
CALL :CHESTSETUP
CALL :SPECIALFIGHTSETUP
CALL :SETPLAYERLOCATIONVARIABLES
CALL :CALCULATEMAPVARS
CALL :OXYGENCALCULATION
CALL "%MISCRESOURCEPATH%\killloadingbar.bat"
CALL :MAPDISPLAY
:MOVE
CALL :PLAYERMOVE
IF %PLAYERNOENC% EQU 1 (
	SET /a RANBATTLECHANCE = 0
) ELSE (
	SET /a RANBATTLECHANCE = !%MAP%RANBATTLECHANCE!
)
::SET /a PLANTVAR = %PLANTVAR% + 1
::IF %PLANTVAR% GTR 3 (
::	SET /a PLANTVAR = 1
::)
IF %MAINMENUBACK% EQU 1 (
	GOTO :EOF
)
IF %MENUACCESSED% EQU 1 (
	SET /a MENUACCESSED = 0
	GOTO :START
)
IF DEFINED %MAP%LOCATION%PLAYERYCOORD%-%PLAYERXCOORD% (
	CALL :!%MAP%LOCATION%PLAYERYCOORD%-%PLAYERXCOORD%!QUERY
)
IF %EXITMAP% EQU 1 (
	GOTO :EOF
)
CALL :VALIDLOCATIONQUERY
IF %EXITMAP% EQU 1 (
	GOTO :EOF
)
CALL :RESETOLDCELL
CALL :SETPLAYERLOCATIONVARIABLES
CALL :RESETOLDNEWROW
CALL :OXYGENCALCULATION
IF %PLAYERDROWN% EQU 1 (
	GOTO :EOF
)
CALL :BATTLEQUERY
IF %EXITMAP% EQU 1 (
	GOTO :EOF
)
:MENU
CALL :MAPDISPLAY
GOTO :MOVE

:STARTMUSIC
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET TEMPPATH=%MUSICPATH%\Maps\!%MAP%MUSICFOLDER!
SET /a STOP = 1
SET /a LOOP = 1
CALL "%MUSICPATH%\startmusic.bat"
GOTO :EOF

:INITIALISE
SET /a PLAYERMAXHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a RANBATTLEPOSS = 0
IF %PLAYERNOENC% EQU 1 (
	SET /a RANBATTLECHANCE = 0
) ELSE (
	SET /a RANBATTLECHANCE = !%MAP%RANBATTLECHANCE!
)
SET /a MAINMENUBACK = 0
SET /a SPECIALFIGHT = 0
SET /a EXITMAP = 0
SET /a MENUACCESSED = 0
IF %PLAYEREXTRAOXYGEN% EQU 0 (
	SET /a PLAYERMAXOXYGEN = 10
) ELSE IF %PLAYEREXTRAOXYGEN% EQU 1 (
	SET /a PLAYERMAXOXYGEN = 20
)
REM DIFFICULTY HERE
REM Need to make sure oxygen isn't restored by going into the menu. Maybe reset oxygen on the way out of the map rather than in
REM SET /a PLAYEROXYGEN = %PLAYERMAXOXYGEN%
SET /a PLAYERDROWN = 0
::SET /a PLANTVAR = 0
GOTO :EOF

:SETUPTEMPMAPVARS
SET MAPDISPLAYTP=!%MAP%TP!
SET MAPDISPLAYBM=!%MAP%BM!
SET /a YCOUNT = 0
:YLOOP
SET /a YCOUNT = %YCOUNT% + 1
SET /a XCOUNT = 0
:XLOOP
SET /a XCOUNT = %XCOUNT% + 1
SET TEMP%YCOUNT%-%XCOUNT%-A=!%MAP%%YCOUNT%-%XCOUNT%-A!
SET TEMP%YCOUNT%-%XCOUNT%-B=!%MAP%%YCOUNT%-%XCOUNT%-B!
SET TEMP%YCOUNT%-%XCOUNT%-C=!%MAP%%YCOUNT%-%XCOUNT%-C!
IF %XCOUNT% LSS !%MAP%XLIMIT! (
	GOTO :XLOOP
) ELSE IF %YCOUNT% LSS !%MAP%YLIMIT! (
	GOTO :YLOOP
)
GOTO :EOF

:CHESTSETUP
IF !%MAP%CHESTTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:CHESTVARSLOOP
SET /a COUNT = %COUNT% + 1
IF !%MAP%CHEST%COUNT%OPEN! EQU 0 (
	SET TEMP!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTCTOP%
	SET TEMP!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTCMID%
)
IF %COUNT% LSS !%MAP%CHESTTOT! (
	GOTO :CHESTVARSLOOP
)
GOTO :EOF

:SPECIALFIGHTSETUP
IF !%MAP%SPECIALFIGHTTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:SPECIALFIGHTSETUPLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
IF !%TEMP%ALIVE! EQU 1 (
	SET TEMP!%MAP%SPECIALFIGHT%COUNT%YCOORD!-!%MAP%SPECIALFIGHT%COUNT%XCOORD!-A=!%MAP%SPECIALFIGHT%COUNT%TOP!
	SET TEMP!%MAP%SPECIALFIGHT%COUNT%YCOORD!-!%MAP%SPECIALFIGHT%COUNT%XCOORD!-B=!%MAP%SPECIALFIGHT%COUNT%MID!
	SET TEMP!%MAP%SPECIALFIGHT%COUNT%YCOORD!-!%MAP%SPECIALFIGHT%COUNT%XCOORD!-C=!%MAP%SPECIALFIGHT%COUNT%BOT!
)
IF %COUNT% LSS !%MAP%SPECIALFIGHTTOT! (
	GOTO :SPECIALFIGHTSETUPLOOP
)
GOTO :EOF




:SETPLAYERLOCATIONVARIABLES
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-A=!%MAP%PLAYER-A!
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-B=!%MAP%PLAYER-B!
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-C=!%MAP%PLAYER-C!
GOTO :EOF

:CALCULATEMAPVARS
SET /a YCOUNT = 0
:YLOOP3
SET /a YCOUNT = %YCOUNT% + 1
SET MAPDISPLAY%YCOUNT%A=    º
SET MAPDISPLAY%YCOUNT%B=    º
SET MAPDISPLAY%YCOUNT%C=    º
IF %YCOUNT% LSS !%MAP%YLIMIT! (
	GOTO :YLOOP3
)
SET /a YCOUNT = 0
:YLOOP2
SET /a YCOUNT = %YCOUNT% + 1
SET /a XCOUNT = 0
:XLOOP2
SET /a XCOUNT = %XCOUNT% + 1
SET MAPDISPLAY%YCOUNT%A=!MAPDISPLAY%YCOUNT%A!!TEMP%YCOUNT%-%XCOUNT%-A!
SET MAPDISPLAY%YCOUNT%B=!MAPDISPLAY%YCOUNT%B!!TEMP%YCOUNT%-%XCOUNT%-B!
SET MAPDISPLAY%YCOUNT%C=!MAPDISPLAY%YCOUNT%C!!TEMP%YCOUNT%-%XCOUNT%-C!
IF %XCOUNT% LSS !%MAP%XLIMIT! (
	GOTO :XLOOP2
) ELSE IF %YCOUNT% LSS !%MAP%YLIMIT! (
	SET MAPDISPLAY%YCOUNT%A=!MAPDISPLAY%YCOUNT%A!º
	SET MAPDISPLAY%YCOUNT%B=!MAPDISPLAY%YCOUNT%B!º
	SET MAPDISPLAY%YCOUNT%C=!MAPDISPLAY%YCOUNT%C!º
	GOTO :YLOOP2
)
SET MAPDISPLAY%YCOUNT%A=!MAPDISPLAY%YCOUNT%A!º
SET MAPDISPLAY%YCOUNT%B=!MAPDISPLAY%YCOUNT%B!º
SET MAPDISPLAY%YCOUNT%C=!MAPDISPLAY%YCOUNT%C!º
GOTO :EOF

:OXYGENCALCULATION
CALL :SURFACEQUERY
IF %PLAYEREXTRAOXYGEN% EQU 1 (
	SET EXTRAOXYGENVAR=°°°°°°°°°°
) ELSE (
	SET EXTRAOXYGENVAR=          
)
CALL :OXYGENBARVAR%PLAYEROXYGEN%
IF %PLAYEROXYGEN% LEQ 0 (
	CALL :NOOXYGEN
	GOTO :EOF
)
SET /a PLAYEROXYGEN = %PLAYEROXYGEN% - 1
GOTO :EOF

:SURFACEQUERY
IF /I !%MAP%%PLAYERYCOORD%-%PLAYERXCOORD%! EQU WATEREDGE (
	SET /a PLAYEROXYGEN = %PLAYERMAXOXYGEN%
)
GOTO :EOF

:OXYGENBARVAR20
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ
GOTO :EOF

:OXYGENBARVAR19
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°
GOTO :EOF

:OXYGENBARVAR18
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°°
GOTO :EOF

:OXYGENBARVAR17
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°°°
GOTO :EOF

:OXYGENBARVAR16
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°°°°
GOTO :EOF

:OXYGENBARVAR15
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°°°°°
GOTO :EOF

:OXYGENBARVAR14
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛÛ°°°°°°
GOTO :EOF

:OXYGENBARVAR13
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛÛ°°°°°°°
GOTO :EOF

:OXYGENBARVAR12
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛÛ°°°°°°°°
GOTO :EOF

:OXYGENBARVAR11
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛÛ°°°°°°°°°
GOTO :EOF

:OXYGENBARVAR10
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛÛ%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR9
SET OXYGENBAR=ÛÛÛÛÛÛÛÛÛ°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR8
SET OXYGENBAR=ÛÛÛÛÛÛÛÛ°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR7
SET OXYGENBAR=ÛÛÛÛÛÛÛ°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR6
SET OXYGENBAR=ÛÛÛÛÛÛ°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR5
SET OXYGENBAR=ÛÛÛÛÛ°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR4
SET OXYGENBAR=ÛÛÛÛ°°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR3
SET OXYGENBAR=ÛÛÛ°°°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR2
SET OXYGENBAR=ÛÛ°°°°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR1
SET OXYGENBAR=Û°°°°°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:OXYGENBARVAR0
SET OXYGENBAR=°°°°°°°°°°%EXTRAOXYGENVAR%
GOTO :EOF

:NOOXYGEN
IF /I %DIFFICULTY% EQU EASY (
	SET /a DROWNDAMAGEVAR = 10
) ELSE IF /I %DIFFICULTY% EQU HARD (
	SET /a DROWNDAMAGEVAR = 5
)
SET /a PLAYERHP = %PLAYERHP% - (%PLAYERBASEMAXHP%/%DROWNDAMAGEVAR%)
IF %PLAYERHP% LEQ 0 (
	CALL :DROWN
)
GOTO :EOF

:DROWN
IF !%MAP%UNDERWATER! EQU 0 (
	SET /a PLAYERHP = %PLAYERMAXHP%
	SET /a PLAYEROXYGEN = %PLAYERMAXOXYGEN%
	SET /a PLAYERDROWN = 1
	CALL %LAKERESOURCEPATH%/secret.bat
	GOTO :EOF
)
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-A=!%MAP%%PLAYERYCOORD%-%PLAYERXCOORD%-A!
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-B=!%MAP%%PLAYERYCOORD%-%PLAYERXCOORD%-B!
SET TEMP%PLAYERYCOORD%-%PLAYERXCOORD%-C=!%MAP%%PLAYERYCOORD%-%PLAYERXCOORD%-C!
SET /a PLAYERDROWNCOUNT = %PLAYERDROWNCOUNT% + 1
SET /a PLAYERHP = %PLAYERMAXHP%
SET /a PLAYERXCOORD = !%MAP%DROWNRESPAWNXCOORD!
SET /a PLAYERYCOORD = !%MAP%DROWNRESPAWNYCOORD!
SET /a PLAYEROXYGEN = %PLAYERMAXOXYGEN%
SET /a PLAYERDROWN = 1
CLS
ECHO.
ECHO You have drowned^^!
ECHO.
CALL "%BATTLEENDRESOURCEPATH%\itemloss.bat"
GOTO :EOF

:MAPDISPLAY
CLS
ECHO.
ECHO %MAPDISPLAYTP%
CALL :MAPDISPLAY!%MAP%YLIMIT!
ECHO %MAPDISPLAYBM%
ECHO.
ECHO. Oxygen: %OXYGENBAR%
ECHO.
IF %DISPLAYCONTROLS% EQU 1 (
	ECHO. Move:    W              8
	ECHO.       A  S  D   or   4  5  6
	ECHO.
	ECHO. Press M or 0 to access the menu. Press Q to quicksave, L to quickload
	IF %TEMPLE2REMOTEACCESS% EQU 1 (
		ECHO. Press H to fully heal yourself
	) ELSE (
		ECHO.
	)
	ECHO. HP: %PLAYERHP%/%PLAYERMAXHP%  MP: %PLAYERMP%/%PLAYERMAXMP%  Gil: %PLAYERGIL%
) ELSE (
	CALL "%MISCRESOURCEPATH%\displayword.bat"
)
ECHO.
ECHO. Press T to toggle the display
ECHO.
GOTO :EOF

:MAPDISPLAY12
ECHO !MAPDISPLAY12A!
ECHO !MAPDISPLAY12B!
ECHO !MAPDISPLAY12C!
ECHO !MAPDISPLAY11A!
ECHO !MAPDISPLAY11B!
ECHO !MAPDISPLAY11C!
ECHO !MAPDISPLAY10A!
ECHO !MAPDISPLAY10B!
ECHO !MAPDISPLAY10C!
ECHO !MAPDISPLAY9A!
ECHO !MAPDISPLAY9B!
ECHO !MAPDISPLAY9C!
ECHO !MAPDISPLAY8A!
ECHO !MAPDISPLAY8B!
ECHO !MAPDISPLAY8C!
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY11
ECHO !MAPDISPLAY11A!
ECHO !MAPDISPLAY11B!
ECHO !MAPDISPLAY11C!
ECHO !MAPDISPLAY10A!
ECHO !MAPDISPLAY10B!
ECHO !MAPDISPLAY10C!
ECHO !MAPDISPLAY9A!
ECHO !MAPDISPLAY9B!
ECHO !MAPDISPLAY9C!
ECHO !MAPDISPLAY8A!
ECHO !MAPDISPLAY8B!
ECHO !MAPDISPLAY8C!
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY10
ECHO !MAPDISPLAY10A!
ECHO !MAPDISPLAY10B!
ECHO !MAPDISPLAY10C!
ECHO !MAPDISPLAY9A!
ECHO !MAPDISPLAY9B!
ECHO !MAPDISPLAY9C!
ECHO !MAPDISPLAY8A!
ECHO !MAPDISPLAY8B!
ECHO !MAPDISPLAY8C!
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY9
ECHO !MAPDISPLAY9A!
ECHO !MAPDISPLAY9B!
ECHO !MAPDISPLAY9C!
ECHO !MAPDISPLAY8A!
ECHO !MAPDISPLAY8B!
ECHO !MAPDISPLAY8C!
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY8
ECHO !MAPDISPLAY8A!
ECHO !MAPDISPLAY8B!
ECHO !MAPDISPLAY8C!
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY7
ECHO !MAPDISPLAY7A!
ECHO !MAPDISPLAY7B!
ECHO !MAPDISPLAY7C!
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY6
ECHO !MAPDISPLAY6A!
ECHO !MAPDISPLAY6B!
ECHO !MAPDISPLAY6C!
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF

:MAPDISPLAY5
ECHO !MAPDISPLAY5A!
ECHO !MAPDISPLAY5B!
ECHO !MAPDISPLAY5C!
ECHO !MAPDISPLAY4A!
ECHO !MAPDISPLAY4B!
ECHO !MAPDISPLAY4C!
ECHO !MAPDISPLAY3A!
ECHO !MAPDISPLAY3B!
ECHO !MAPDISPLAY3C!
ECHO !MAPDISPLAY2A!
ECHO !MAPDISPLAY2B!
ECHO !MAPDISPLAY2C!
ECHO !MAPDISPLAY1A!
ECHO !MAPDISPLAY1B!
ECHO !MAPDISPLAY1C!
GOTO :EOF







:PLAYERMOVE
SET /a PLAYEROLDXCOORD = %PLAYERXCOORD%
SET /a PLAYEROLDYCOORD = %PLAYERYCOORD%
SET /a NOBATTLE = 0
IF %PLAYERYCOORD% NEQ !%MAP%YLIMIT! (
	CHOICE /C:wsadm85460qlht /N /T:1 /D:8
) ELSE (
	CHOICE /C:wsadm85460qlht /N
)
IF %ERRORLEVEL% EQU 1 (
	SET /a PLAYERYCOORD=%PLAYERYCOORD%+1
) ELSE IF %ERRORLEVEL% EQU 2 (
	SET /a PLAYERYCOORD=%PLAYERYCOORD%-1
) ELSE IF %ERRORLEVEL% EQU 3 (
	SET /a PLAYERXCOORD=%PLAYERXCOORD%-1
	SET %MAP%PLAYER-A=    
	SET %MAP%PLAYER-B= -±  
	SET %MAP%PLAYER-C=   \ 
) ELSE IF %ERRORLEVEL% EQU 4 (
	SET /a PLAYERXCOORD=%PLAYERXCOORD%+1
	SET %MAP%PLAYER-A=    
	SET %MAP%PLAYER-B=  ±- 
	SET %MAP%PLAYER-C= /   
) ELSE IF %ERRORLEVEL% EQU 5 (
	CALL "%MENURESOURCEPATH%\openmenu.bat"
	SET /a MENUACCESSED = 1
	SET /a NOBATTLE = 1
) ELSE IF %ERRORLEVEL% EQU 6 (
	SET /a PLAYERYCOORD=%PLAYERYCOORD%+1
) ELSE IF %ERRORLEVEL% EQU 7 (
	SET /a PLAYERYCOORD=%PLAYERYCOORD%-1
) ELSE IF %ERRORLEVEL% EQU 8 (
	SET /a PLAYERXCOORD=%PLAYERXCOORD%-1
	SET %MAP%PLAYER-A=    
	SET %MAP%PLAYER-B= -±  
	SET %MAP%PLAYER-C=   \ 
) ELSE IF %ERRORLEVEL% EQU 9 (
	SET /a PLAYERXCOORD=%PLAYERXCOORD%+1
	SET %MAP%PLAYER-A=    
	SET %MAP%PLAYER-B=  ±- 
	SET %MAP%PLAYER-C= /   
) ELSE IF %ERRORLEVEL% EQU 10 (
	CALL "%MENURESOURCEPATH%\openmenu.bat"
	SET /a MENUACCESSED = 1
	SET /a NOBATTLE = 1
) ELSE IF %ERRORLEVEL% EQU 11 (
	CLS
	SET /a QUICKSAVE = 1
	CALL "%MENURESOURCEPATH%\savegame.bat"
	SET /a MENUACCESSED = 1
	SET /a NOBATTLE = 1
) ELSE IF %ERRORLEVEL% EQU 12 (
	CALL :QUICKLOAD
	SET /a NOBATTLE = 1
) ELSE IF %ERRORLEVEL% EQU 13 (
	SET /a NOBATTLE = 1
	IF %TEMPLE2REMOTEACCESS% EQU 1 (
		CALL :HEAL
	) ELSE (
		GOTO :EOF
	)
) ELSE IF %ERRORLEVEL% EQU 14 (
	SET /a NOBATTLE = 1
	IF %DISPLAYCONTROLS% EQU 1 (
		SET /a DISPLAYCONTROLS = 0
	) ELSE (
		SET /a DISPLAYCONTROLS = 1
		CALL "%MISCRESOURCEPATH%\calculateword.bat"
	)
)
GOTO :EOF

:HEAL
SET TEMPPATH=%MUSICPATH%\Battle\Spells
SET FILE=Cura.mp3
IF EXIST "%TEMPPATH%\%FILE%" (
	CALL "%MUSICPATH%\soundeffect.bat"
)
SET FILE=Esuna.mp3
IF EXIST "%TEMPPATH%\%FILE%" (
	CALL "%MUSICPATH%\soundeffect.bat"
)
SET /a PLAYERHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a PLAYERMP = %PLAYERBASEMAXMP% + %PLAYEREQUIPMAXMP%
SET /a PLAYERBLIND = 0
SET /a PLAYERSILENCE = 0
SET /a PLAYERPOISON = 0
SET /a PLAYERSLOW = 0
GOTO :EOF

:QUICKLOAD
SET OLDMAP=%MAP%
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Don't you worry there hun, I'll load your game for you
SET PREFIX=PLAYSTART
CALL "%MISCRESOURCEPATH%\calculatedatetime.bat"
IF EXIST "%SAVERESOURCEPATH%\quicksave.bat" (
	CALL "%SAVERESOURCEPATH%\quicksave.bat"
	RMDIR "%CUSTOMSPELLRESOURCEPATH%\Temp" /S /Q
	XCOPY "%CUSTOMSPELLRESOURCEPATH%\QS" "%CUSTOMSPELLRESOURCEPATH%\Temp" /E /I
	RMDIR "%CUSTOMITEMRESOURCEPATH%\Temp" /S /Q
	XCOPY "%CUSTOMITEMRESOURCEPATH%\QS" "%CUSTOMITEMRESOURCEPATH%\Temp" /E /I
	RMDIR "%CUSTOMWEAPONRESOURCEPATH%\Temp" /S /Q
	XCOPY "%CUSTOMWEAPONRESOURCEPATH%\QS" "%CUSTOMWEAPONRESOURCEPATH%\Temp" /E /I
	RMDIR "%CUSTOMARMOURRESOURCEPATH%\Temp" /S /Q
	XCOPY "%CUSTOMARMOURRESOURCEPATH%\QS" "%CUSTOMARMOURRESOURCEPATH%\Temp" /E /I
	RMDIR "%CUSTOMACCESSORYRESOURCEPATH%\Temp" /S /Q
	XCOPY "%CUSTOMACCESSORYRESOURCEPATH%\QS" "%CUSTOMACCESSORYRESOURCEPATH%\Temp" /E /I
) ELSE (
	ECHO.
	ECHO There is no quicksaved data
	CALL :WAITFORTWO
)
IF /I %OLDMAP% NEQ %MAP% (
	SET /a EXITMAP = 1
	SET WORD=!%MAP%DISPLAYNAME!
	CALL "%MISCRESOURCEPATH%\calculateword.bat"
) ELSE (
	SET /a EXITMAP = 0
)
SET /a MENUACCESSED = 1
SET WORD=!%MAP%DISPLAYNAME!
CALL "%MISCRESOURCEPATH%\calculateword.bat"
IF NOT DEFINED %MAP%LOADED (
	CALL :UNDEFINED
)
GOTO :EOF

:UNDEFINED
SET /a %MAP%LOADED = 1
CALL "%MAPSPATH%\%MAP%setup.bat"
SET /a MENUACCESSED = 0
SET LOADINGTEXT=Loading !%MAP%NICKNAME!
SET TEMP=%GAMEPATH%
START "" "%MISCRESOURCEPATH%\loadingbar.lnk"
GOTO :START

:CHESTQUERY
IF !%MAP%CHESTTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:CHESTLOOPSTART
SET /a COUNT = %COUNT%+1
IF !%MAP%CHEST%COUNT%XCOORD! EQU %PLAYERXCOORD% (
	IF !%MAP%CHEST%COUNT%YCOORD! EQU %PLAYERYCOORD% (
		CALL :RESETPLAYERLOCATION
		IF !%MAP%CHEST%COUNT%OPEN! EQU 0 (
			CALL :OPENCHEST
		)
	)
)
IF %COUNT% LSS !%MAP%CHESTTOT! (
	GOTO :CHESTLOOPSTART
)
GOTO :EOF

:OPENCHEST
SET TEMPPATH=%MUSICPATH%\Chest
SET FILE=Chest.mp3
CALL "%MUSICPATH%\soundeffect.bat"
SET /a NOBATTLE = 1
SET /a %MAP%CHEST%COUNT%OPEN = 1
SET TEMP!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET TEMP!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET TYPE=ITEM
CALL :CHESTITEMS
SET TYPE=SPECIALITEM
CALL :CHESTITEMS
SET TYPE=WEAPON
CALL :CHESTITEMS
SET TYPE=ARMOUR
CALL :CHESTITEMS
SET TYPE=ACCESSORY
CALL :CHESTITEMS
SET /a RESETROW = !%MAP%CHEST%COUNT%YCOORD!
CALL :RESETROW!%MAP%XLIMIT!
GOTO :EOF

:CHESTITEMS
IF !%MAP%CHEST%COUNT%%TYPE%TOT! EQU 0 (
	GOTO :EOF
)
SET /a CHESTCOUNT = 0
:CHESTITEMSLOOP
SET /a CHESTCOUNT = %CHESTCOUNT% + 1
SET /a TEMP = !%MAP%CHEST%COUNT%%TYPE%%CHESTCOUNT%!
SET /a PLAYER%TYPE%%TEMP%NUM = !PLAYER%TYPE%%TEMP%NUM!+!%MAP%CHEST%COUNT%%TYPE%%CHESTCOUNT%NUM!
ECHO.
IF !%MAP%CHEST%COUNT%%TYPE%%CHESTCOUNT%NUM! EQU 1 (
	ECHO. !%TYPE%%TEMP%NAME! Acquired^^!
) ELSE (
	ECHO. !%MAP%CHEST%COUNT%%TYPE%%CHESTCOUNT%NUM! !%TYPE%%TEMP%NAME!s Acquired^^!
)
CALL :WAITFORTWO
IF %CHESTCOUNT% LSS !%MAP%CHEST%COUNT%%TYPE%TOT! (
	GOTO :CHESTITEMSLOOP
)
GOTO :EOF	

:BUILDINGQUERY
IF !%MAP%BUILDINGTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:BUILDINGLOOP
SET /a COUNT = %COUNT% + 1
SET /a CELLCOUNT = 0
:BUILDINGLOOP2
SET /a CELLCOUNT = %CELLCOUNT% + 1
IF "%PLAYERYCOORD%-%PLAYERXCOORD%" EQU "!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!" (
	SET TEMP=!%MAP%BUILDING%COUNT%PATH!
	CALL :ENTERBUILDING
	GOTO :EOF
)
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGLOOP2
) ELSE IF %COUNT% LSS !%MAP%BUILDINGTOT! (
	GOTO :BUILDINGLOOP
)
GOTO :EOF

:ENTERBUILDING
SET /a EXITMAP = 0
CALL "!%TEMP%!\!%MAP%BUILDING%COUNT%FILE!.bat"
GOTO :EOF

:SPECIALQUERY
IF !%MAP%SPECIALLOCATIONTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:SPECIALLOCATIONLOOP
SET /a COUNT = %COUNT% + 1
IF %PLAYERXCOORD% EQU !%MAP%SPECIALLOCATION%COUNT%XCOORD! (
	IF %PLAYERYCOORD% EQU !%MAP%SPECIALLOCATION%COUNT%YCOORD! (
		SET TEMP=!%MAP%SPECIALLOCATION%COUNT%PATH!
		CALL :ENTERSPECIALLOCATION
		GOTO :EOF
	)
)
IF %COUNT% LSS !%MAP%SPECIALLOCATIONTOT! (
	GOTO :SPECIALLOCATIONLOOP
)
GOTO :EOF

:ENTERSPECIALLOCATION
SET /a EXITMAP = 1
CALL "!%TEMP%!\!%MAP%SPECIALLOCATION%COUNT%FILE!.bat"
GOTO :EOF

:EXITQUERY
IF !%MAP%EXITNUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:EXITLOOP
SET /a COUNT = %COUNT% + 1
IF %PLAYERXCOORD% EQU !%MAP%EXIT%COUNT%XCOORD! (
	IF %PLAYERYCOORD% EQU !%MAP%EXIT%COUNT%YCOORD! (
		SET /a EXITMAP = 1
		SET /a PLAYERXCOORD = !%MAP%EXIT%COUNT%NEWXCOORD!
		SET /a PLAYERYCOORD = !%MAP%EXIT%COUNT%NEWYCOORD!
		SET MAP=!%MAP%EXIT%COUNT%NEWMAP!
		IF /I %DIFFICULTY% EQU EASY (
			SET /a PLAYEROXYGEN = %PLAYERMAXOXYGEN%
		)
		GOTO :EOF
	)
)
IF %COUNT% LSS !%MAP%EXITNUM! (
	GOTO :EXITLOOP
)
GOTO :EOF

:VALIDLOCATIONQUERY
IF DEFINED %MAP%Y%PLAYERYCOORD%X%PLAYERXCOORD%VALID (
	IF !%MAP%Y%PLAYERYCOORD%X%PLAYERXCOORD%VALID! EQU 0 (
		CALL :RESETPLAYERLOCATION
	)
)
CALL :EDGEQUERY
GOTO :EOF

:RESETPLAYERLOCATION
SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
GOTO :EOF

:EDGEQUERY
IF %PLAYERXCOORD% LSS 1 (
	SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
) ELSE IF %PLAYERXCOORD% GTR !%MAP%XLIMIT! (
	SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
)
IF %PLAYERYCOORD% LSS 1 (
	SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
) ELSE IF %PLAYERYCOORD% GTR !%MAP%YLIMIT! (
	SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
)
GOTO :EOF


:SPECIALBATTLEQUERY
IF !%MAP%SPECIALFIGHTTOT! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:SPECIALBATTLELOOP
SET /a COUNT = %COUNT% + 1
IF %PLAYERXCOORD% EQU !%MAP%SPECIALFIGHT%COUNT%XCOORD! (
	IF %PLAYERYCOORD% EQU !%MAP%SPECIALFIGHT%COUNT%YCOORD! (
		CALL :SPECIALBATTLELIKELY
	)
)
IF %COUNT% LSS !%MAP%SPECIALFIGHTTOT! (
	GOTO :SPECIALBATTLELOOP
)
GOTO :EOF

:SPECIALBATTLELIKELY
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
IF !%TEMP%ALIVE! EQU 1 (
	SET /a ENEMYID = !%TEMP%ID!
	SET /a EXITMAP = 1
	CALL "%BATTLESTARTRESOURCEPATH%\specialbattlestart.bat"
	CALL :RESETLOCATIONQUERY
)
GOTO :EOF

:RESETLOCATIONQUERY
IF %LOSEBATTLE% EQU 1 (
	SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
	SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
) ELSE IF %BATTLERUN% EQU 1 (
	SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
	SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
) 
GOTO :EOF

:RESETOLDCELL
SET TEMP%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-A=!%MAP%%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-A!
SET TEMP%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-B=!%MAP%%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-B!
SET TEMP%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-C=!%MAP%%PLAYEROLDYCOORD%-%PLAYEROLDXCOORD%-C!
GOTO :EOF

:RESETOLDNEWROW
IF %PLAYEROLDYCOORD% EQU %PLAYERYCOORD% (
	SET /a RESETROW = %PLAYERYCOORD%
	CALL :RESETROW!%MAP%XLIMIT!
) ELSE (
	SET /a RESETROW = %PLAYERYCOORD%
	CALL :RESETROW!%MAP%XLIMIT!
	SET /a RESETROW = %PLAYEROLDYCOORD%
	CALL :RESETROW!%MAP%XLIMIT!
)
GOTO :EOF

:RESETROW6
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!º
GOTO :EOF

:RESETROW7
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!º
GOTO :EOF

:RESETROW8
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!º
GOTO :EOF

:RESETROW9
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!º
GOTO :EOF

:RESETROW10
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!!TEMP%RESETROW%-10-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!!TEMP%RESETROW%-10-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!!TEMP%RESETROW%-10-C!º
GOTO :EOF

:RESETROW11
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!!TEMP%RESETROW%-10-A!!TEMP%RESETROW%-11-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!!TEMP%RESETROW%-10-B!!TEMP%RESETROW%-11-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!!TEMP%RESETROW%-10-C!!TEMP%RESETROW%-11-C!º
GOTO :EOF

:RESETROW12
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!!TEMP%RESETROW%-10-A!!TEMP%RESETROW%-11-A!!TEMP%RESETROW%-12-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!!TEMP%RESETROW%-10-B!!TEMP%RESETROW%-11-B!!TEMP%RESETROW%-12-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!!TEMP%RESETROW%-10-C!!TEMP%RESETROW%-11-C!!TEMP%RESETROW%-12-C!º
GOTO :EOF

:RESETROW13
SET MAPDISPLAY%RESETROW%A=    º!TEMP%RESETROW%-1-A!!TEMP%RESETROW%-2-A!!TEMP%RESETROW%-3-A!!TEMP%RESETROW%-4-A!!TEMP%RESETROW%-5-A!!TEMP%RESETROW%-6-A!!TEMP%RESETROW%-7-A!!TEMP%RESETROW%-8-A!!TEMP%RESETROW%-9-A!!TEMP%RESETROW%-10-A!!TEMP%RESETROW%-11-A!!TEMP%RESETROW%-12-A!!TEMP%RESETROW%-13-A!º
SET MAPDISPLAY%RESETROW%B=    º!TEMP%RESETROW%-1-B!!TEMP%RESETROW%-2-B!!TEMP%RESETROW%-3-B!!TEMP%RESETROW%-4-B!!TEMP%RESETROW%-5-B!!TEMP%RESETROW%-6-B!!TEMP%RESETROW%-7-B!!TEMP%RESETROW%-8-B!!TEMP%RESETROW%-9-B!!TEMP%RESETROW%-10-B!!TEMP%RESETROW%-11-B!!TEMP%RESETROW%-12-B!!TEMP%RESETROW%-13-B!º
SET MAPDISPLAY%RESETROW%C=    º!TEMP%RESETROW%-1-C!!TEMP%RESETROW%-2-C!!TEMP%RESETROW%-3-C!!TEMP%RESETROW%-4-C!!TEMP%RESETROW%-5-C!!TEMP%RESETROW%-6-C!!TEMP%RESETROW%-7-C!!TEMP%RESETROW%-8-C!!TEMP%RESETROW%-9-C!!TEMP%RESETROW%-10-C!!TEMP%RESETROW%-11-C!!TEMP%RESETROW%-12-C!!TEMP%RESETROW%-13-C!º
GOTO :EOF




:BATTLEQUERY
IF %NOBATTLE% EQU 1 (
	GOTO :EOF
)
CALL :RANBATTLEQUERY
IF %RANBATTLE% EQU 1 (
	SET /a TRAINBATTLE = 0
	CALL "%BATTLESTARTRESOURCEPATH%\initiateranbattle.bat"
	::TESTING
	SET /a EXITMAP = 0
)
GOTO :EOF

:RANBATTLEQUERY
SET /a RANBATTLEPOSS = !%MAP%%PLAYERYCOORD%%PLAYERXCOORD%RANBATTLEPOSS!
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
IF %RANBATTLEPOSS% EQU 1 (
	IF %RANPERC% LSS %RANBATTLECHANCE% (
		SET /a RANBATTLE = 1
	) ELSE (
		SET /a RANBATTLE = 0
	)
) ELSE IF %RANBATTLEPOSS% EQU 0 (
	SET /a RANBATTLE = 0
)
GOTO :EOF


:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

