IF NOT DEFINED MENUACCESSED (
	SET /a MENUACCESSED = 0
)
IF %MENUACCESSED% EQU 1 (
	GOTO :EOF
)
IF !%MAP%BUILDINGTOT! GTR 0 (
	CALL :TIDY
)
CALL :RANDOMISEEXIT
CALL :RANDOMISEFAKEEXITTILES
SET /a PLAYERXCOORD = %RANDOM% %% !%MAP%XLIMIT! + 1
SET /a PLAYERYCOORD = %RANDOM% %% !%MAP%YLIMIT! + 1
GOTO :EOF

:TIDY
SET /a COUNT = 0
:LOOP1
SET /a COUNT = %COUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-A=%MIST1A%
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-B=%MIST1B%
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-C=%MIST1C%
SET %MAP%LOCATION!%MAP%BUILDING%COUNT%CELL1!=
IF %COUNT% LSS !%MAP%BUILDINGTOT! (
	GOTO :LOOP1
)
GOTO :EOF

:RANDOMISEEXIT
SET /a COUNT = 1
SET /a RANEXITXCOORD = %RANDOM% %% !%MAP%XLIMIT! + 1
SET /a RANEXITYCOORD = %RANDOM% %% !%MAP%YLIMIT! + 1
SET %MAP%BUILDING1FILE=exitforest
SET %MAP%BUILDING1PATH=FORESTRESOURCEPATH
SET /a %MAP%BUILDING1CELLNUM = 1
SET %MAP%BUILDING1CELL1=%RANEXITYCOORD%-%RANEXITXCOORD%
SET %MAP%BUILDING1CELL1DISPLAYA=%MIST2A%
SET %MAP%BUILDING1CELL1DISPLAYB=%MIST2B%
SET %MAP%BUILDING1CELL1DISPLAYC=%MIST2C%
SET %MAP%LOCATION!%MAP%BUILDING1CELL1!=BUILDING
CALL :BUILDINGVARS
SET STORY20VERSION1LINE2=Maybe the exit is on cell !%MAP%BUILDING1CELL1!
GOTO :EOF

:RANDOMISEFAKEEXITTILES
SET /a COUNT = 1
:LOOP2
SET /a COUNT = %COUNT% + 1
SET /a RANEXITXCOORD = %RANDOM% %% !%MAP%XLIMIT! + 1
SET /a RANEXITYCOORD = %RANDOM% %% !%MAP%YLIMIT! + 1
SET %MAP%BUILDING%COUNT%FILE=notexit
SET %MAP%BUILDING%COUNT%PATH=FORESTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 1
SET %MAP%BUILDING%COUNT%CELL1=%RANEXITYCOORD%-%RANEXITXCOORD%
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=%MIST2A%
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=%MIST2B%
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=%MIST2C%
SET %MAP%LOCATION!%MAP%BUILDING%COUNT%CELL1!=BUILDING
CALL :BUILDINGVARS
IF %COUNT% LSS 3 (
	GOTO :LOOP2
)
SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF




:BUILDINGVARS
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-A=!%MAP%BUILDING%COUNT%CELL1DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-B=!%MAP%BUILDING%COUNT%CELL1DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL1!-C=!%MAP%BUILDING%COUNT%CELL1DISPLAYC!
GOTO :EOF