IF %LAKECAVEDISCOVERED% EQU 1 (
	CALL :DISCOVERED
) ELSE (
	CALL :NOT
)
GOTO :EOF

:DISCOVERED
SET /a LAKE1EXITNUM = 2
SET /a LAKE1EXIT2XCOORD = 12
SET /a LAKE1EXIT2YCOORD = 1
SET LAKE1EXIT2NEWMAP=lake2
SET /a LAKE1EXIT2NEWXCOORD = 1
SET /a LAKE1EXIT2NEWYCOORD = 1
SET LAKE1LOCATION%LAKE1EXIT2YCOORD%-%LAKE1EXIT2XCOORD%=EXIT
SET LAKE11-11-A=°°°  
SET LAKE11-11-B=°°°  
SET LAKE11-11-C=°°°  
GOTO :EOF

:NOT
SET LAKE11-11-A=%WATERA%
SET LAKE11-11-B=%WATERB%
SET LAKE11-11-C=%WATERC%
SET /a LAKE1EXITNUM = 1
GOTO :EOF