:MAPCHOICE
CALL "%SKILLRESOURCEPATH%\unlockskillquery.bat"
::SET TEMP=%GAMEPATH%
SET LOADINGTEXT=Loading !%MAP%NICKNAME!
SET TEMP=%GAMEPATH%
START "" "%MISCRESOURCEPATH%\loadingbar.lnk"
IF NOT DEFINED %MAP%LOADED (
	SET /a %MAP%LOADED = 1
	CALL "%MAPSPATH%\%MAP%setup.bat"
)
IF !%MAP%UNDERWATER! EQU 0 (
	CALL "%MAPRESOURCEPATH%\displaymap.bat"
) ELSE (
	CALL "%MAPRESOURCEPATH%\displaywatermap.bat"
)
IF %MAINMENUBACK% EQU 1 (
	GOTO :EOF
)
GOTO :MAPCHOICE