SET /a %MAP%TELEPORTACTIVE = 1
IF %BEATTRAMP% EQU 1 (
	SET TOWN29-3-A=%GRASSA%
	SET TOWN29-3-B=%GRASSB%
	SET TOWN29-3-C=%GRASSC%
	SET TOWN2LOCATION9-3=
) ELSE IF %BEATTRAMP% EQU 0 (
	SET TOWN29-3-A=∞∞∞∞∞
	SET TOWN29-3-B=z    
	SET TOWN29-3-C= ‹Õ 
	SET TOWN2LOCATION9-3=SPECIAL
)
IF %MENUTUTORIALSEEN% EQU 1 (
	SET TOWN2LOCATION4-6=
)
IF %MENUTUTORIALSEEN% EQU 1 (
	SET TOWN2LOCATION2-5=
)