SET /a %MAP%TELEPORTACTIVE = 1
IF %STORY28VERSIONNUM% EQU 0 (
	SET /a STORY28VERSIONNUM = 1
)
IF %PORTALOPENED% EQU 1 (
	SET %MAP%BUILDING6CELL1DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL1DISPLAYB=~°°°°
	SET %MAP%BUILDING6CELL1DISPLAYC=~°°°°
	SET %MAP%BUILDING6CELL2DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL2DISPLAYB=°°°°°
	SET %MAP%BUILDING6CELL2DISPLAYC=°°°°°
	SET %MAP%BUILDING6CELL3DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL3DISPLAYB=°°°°°
	SET %MAP%BUILDING6CELL3DISPLAYC=°°°°°
	SET %MAP%BUILDING6CELL4DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL4DISPLAYB=°°°°~
	SET %MAP%BUILDING6CELL4DISPLAYC=°°°°~
	SET %MAP%BUILDING6CELL5DISPLAYA=~°°°°
	SET %MAP%BUILDING6CELL5DISPLAYB=~°°°°
	SET %MAP%BUILDING6CELL5DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL6DISPLAYA=°°°°°
	SET %MAP%BUILDING6CELL6DISPLAYB=°°°°°
	SET %MAP%BUILDING6CELL6DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL7DISPLAYA=°°°°°
	SET %MAP%BUILDING6CELL7DISPLAYB=°°°°°
	SET %MAP%BUILDING6CELL7DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL8DISPLAYA=°°°°~
	SET %MAP%BUILDING6CELL8DISPLAYB=°°°°~
	SET %MAP%BUILDING6CELL8DISPLAYC=~~~~~
) ELSE IF %PORTALOPENED% EQU 0 (
	SET %MAP%BUILDING6CELL1DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL1DISPLAYB=~    
	SET %MAP%BUILDING6CELL1DISPLAYC=~    
	SET %MAP%BUILDING6CELL2DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL2DISPLAYB=     
	SET %MAP%BUILDING6CELL2DISPLAYC=     
	SET %MAP%BUILDING6CELL3DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL3DISPLAYB=     
	SET %MAP%BUILDING6CELL3DISPLAYC=     
	SET %MAP%BUILDING6CELL4DISPLAYA=~~~~~
	SET %MAP%BUILDING6CELL4DISPLAYB=    ~
	SET %MAP%BUILDING6CELL4DISPLAYC=    ~
	SET %MAP%BUILDING6CELL5DISPLAYA=~    
	SET %MAP%BUILDING6CELL5DISPLAYB=~    
	SET %MAP%BUILDING6CELL5DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL6DISPLAYA=     
	SET %MAP%BUILDING6CELL6DISPLAYB=     
	SET %MAP%BUILDING6CELL6DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL7DISPLAYA=     
	SET %MAP%BUILDING6CELL7DISPLAYB=     
	SET %MAP%BUILDING6CELL7DISPLAYC=~~~~~
	SET %MAP%BUILDING6CELL8DISPLAYA=    ~
	SET %MAP%BUILDING6CELL8DISPLAYB=    ~
	SET %MAP%BUILDING6CELL8DISPLAYC=~~~~~
)