SET /a DWARFTOT = 0
SET /a DWARFSLOTS = 0
SET /a TOTALDWARFHAPPINESS = %INITIALTOTALDWARFHAPPINESS%
SET /a PLAYERHAULTOTAL = 0
SET /a COUNT = 0
:UNLOCKLOOP1
SET /a COUNT = %COUNT% + 1
SET /a MINEITEMTYPE%COUNT%UNLOCKED = 0
IF %COUNT% LSS 9 (
	GOTO :UNLOCKLOOP1
)
SET /a MINEITEMTYPE1UNLOCKED = 0

SET /a STRTRAININGFACILITYUNLOCKED = 0
SET /a SKLTRAININGFACILITYUNLOCKED = 0
SET /a PERTRAININGFACILITYUNLOCKED = 0

SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERPICKAXE%COUNT%NUM = 0
IF %COUNT% LSS %PICKAXETOT% (
	GOTO :LOOPSTART
)

SET /a COUNT = 0
:LOOP2START
SET /a COUNT=%COUNT%+1
SET /a PLAYERSACK%COUNT%NUM = 0
IF %COUNT% LSS %SACKTOT% (
	GOTO :LOOP2START
)