SET /a MENUTUTORIALSEEN = 0
SET /a MINETUTORIALSEEN = 0
SET /a CASTLECUTSCENESEEN = 0
SET /a SHOPWELCOMESEEN = 0
SET /a TEMPLEWELCOMESEEN = 0
SET /a TUTORIALWELCOMESEEN = 0
SET /a CASINOWELCOMESEEN = 0
SET /a BLACKSMITHWELCOMESEEN = 0
SET /a ALCHEMISTWELCOMESEEN = 0
SET /a GURUWELCOMESEEN = 0
SET /a TRAININGWELCOMESEEN = 0


