:WEAPONSTATS
SET PLAYERWEAPON=NONE
SET /a PLAYERWEAPONID = 0
SET /a PLAYEREQUIPSTR = 0
SET /a PLAYEREQUIPMAG = 0
SET /a PLAYEREQUIPACC = 0

:ARMOURSTATS
SET PLAYERARMOUR=NONE
SET /a PLAYERARMOURID = 0
SET /a PLAYEREQUIPEND = 0
SET /a PLAYEREQUIPSPR = 0
SET /a PLAYEREQUIPEVA = 0
SET /a PLAYEREQUIPSPD = 0
SET /a PLAYERWEAKNESSNUM=0
SET /a PLAYERSTRENGTHNUM=0
SET /a PLAYERELEMENTIMMUNENUM=0
SET /a PLAYERABSORBNUM=0
SET /a PLAYERSTATUSIMMUNENUM=0


:ACCESSORYSTATS
SET PLAYERACCESSORY=NONE
SET /a PLAYERACCESSORYID = 0
SET /a PLAYEREQUIPMAXHP = 0
SET /a PLAYEREQUIPMAXMP = 0
SET /a PLAYEREQUIPLCK = 0

