SET /a COUNT = 0
:WEAPONLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERWEAPON%COUNT%NUM = 0
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :WEAPONLOOPSTART
)


SET /a COUNT = 0
:ARMOURLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERARMOUR%COUNT%NUM = 0
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :ARMOURLOOPSTART
)


SET /a COUNT = 0
:ACCESSORYLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERACCESSORY%COUNT%NUM = 0
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :ACCESSORYLOOPSTART
)