:GENERAL
SET /a TIMESSAVED = 0
SET /a TRAINBATTLETOTAL = 0
SET /a GUITARBATTLETOTAL = 0
SET /a GUITARBATTLEWINTOTAL = 0
SET /a GUITARBATTLELOSETOTAL = 0
SET /a ALLELEMENTALSPELLSUNLOCKED = 0
SET /a ALLSUPPORTSPELLSUNLOCKED = 0
SET /a PLAYERDROWNCOUNT = 0
SET /a HOURSPLAYTIME = 0
SET /a MINSPLAYTIME = 0
SET PREFIX=PLAYSTART
CALL "%MISCRESOURCEPATH%\calculatedatetime.bat"

:BATTLE
SET /a BATTLETOTAL = 0
SET /a BATTLEWINTOTAL = 0
SET /a BATTLELOSETOTAL = 0
SET /a PLAYERATTACKCOUNT = 0
SET /a PLAYERMISSCOUNT = 0
SET /a DODGESUCCESSCOUNT = 0
SET /a CRITICALHITSUCCESSCOUNT = 0
SET /a CATCHSUCCESSCOUNT = 0
SET /a RUNSUCCESSCOUNT = 0
SET /a GILSTOLENCOUNT = 0
SET /a GILTHROWNCOUNT = 0
SET /a TRANSGILCOUNT = 0
SET /a MPSTOLENCOUNT = 0
SET /a PLAYERUSEITEMCOUNT = 0
SET /a STEALSUCCESSCOUNT = 0
SET /a FIRESPELLSCASTCOUNT = 0
SET /a ICESPELLSCASTCOUNT = 0
SET /a ELECTRICSPELLSCASTCOUNT = 0
SET /a WATERSPELLSCASTCOUNT = 0
SET /a EARTHSPELLSCASTCOUNT = 0
SET /a FORBIDDENSPELLSCASTCOUNT = 0
SET /a CUSTOMSPELLSCASTCOUNT = 0
SET /a WEAKNESSSPELLCOUNT = 0
SET /a STRENGTHSPELLCOUNT = 0
SET /a ELEMENTIMMUNESPELLCOUNT = 0
SET /a ABSORBSPELLCOUNT = 0
SET /a STATUSIMMUNESPELLCOUNT = 0

SET /a LIMITBREAKUSED = 0
SET /a COUNT = 0
:LIMITBREAKLOOP
SET /a COUNT = %COUNT% + 1
SET /a LIMITBREAK%COUNT%USED = 0
IF %COUNT% LSS %LIMITBREAKTOT% (
	GOTO :LIMITBREAKLOOP
)


:SKILLS
SET /a COUNT = 0
:SKILLLOOP
SET /a COUNT = %COUNT% + 1
SET /a PLAYERUSE!SKILL%COUNT%NICKNAME! = 0
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILLLOOP
)

:TEMPLE
SET /a PLAYERTEMPLEDONATIONTOTAL = 0
SET /a PLAYERTEMPLEDONATIONREDUCTION = 0
SET /a PLAYERCUSTOMSPELLCREATIONCOUNT = 0

:CASINO
SET /a ROULETTEPLAYEDTOTAL = 0
SET /a ROULETTEWINTOTAL = 0
SET /a ROULETTELOSETOTAL = 0
SET /a ROULETTEPROFIT = 0
SET /a BLACKJACKPLAYEDTOTAL = 0
SET /a BLACKJACKWINTOTAL = 0
SET /a BLACKJACKLOSETOTAL = 0
SET /a BLACKJACKPROFIT = 0
SET /a SLOTMACHINEPLAYEDTOTAL = 0
SET /a SLOTMACHINEWINTOTAL = 0
SET /a SLOTMACHINELOSETOTAL = 0
SET /a SLOTMACHINEPROFIT = 0
SET /a TOTALCASINOPROFIT = 0

:SHOPSPEND
SET /a SHOP1SPEND = 0
SET /a SHOP2SPEND = 0
SET /a SHOP3SPEND = 0
SET /a SHOP4SPEND = 0
SET /a SHOP5SPEND = 0

:PORTAL
SET /a PORTALOPENED = 0
