SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERSKILL%COUNT%ENABLED = 0
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOPSTART
)

SET /a COUNT = 0
:LOOP2START
SET /a COUNT=%COUNT%+1
SET /a PLAYERSKILL%COUNT%EARNED = 0
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOP2START
)

SET /a COUNT = 0
:LOOP3START
SET /a COUNT=%COUNT%+1
SET /a SKILL%COUNT%UNLOCKCOUNT = 0
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOP3START
)