SET /a AUTOBATTLE = 0

SET /a PLAYERBLIND = 0
SET /a PLAYERSILENCE = 0
SET /a PLAYERPOISON = 0
SET /a PLAYERSLOW = 0
SET /a PLAYERSLEEP = 0
SET /a PLAYERCONFUSION = 0
SET /a PLAYERSTOP = 0
SET /a PLAYERHASTE = 0
SET /a PLAYERPROTECT = 0
SET /a PLAYERSHELL = 0
SET /a PLAYERREFLECT = 0
SET /a PLAYERREGEN = 0
SET /a PLAYERAUTOLIFE = 0

SET /a PLAYERBLINDTURNCOUNT = 0
SET /a PLAYERSILENCETURNCOUNT = 0
SET /a PLAYERPOISONTURNCOUNT = 0
SET /a PLAYERSLOWTURNCOUNT = 0
SET /a PLAYERSLEEPTURNCOUNT = 0 
SET /a PLAYERCONFUSIONTURNCOUNT = 0
SET /a PLAYERSTOPTURNCOUNT = 0
SET /a PLAYERHASTETURNCOUNT = 0
SET /a PLAYERPROTECTTURNCOUNT = 0
SET /a PLAYERSHELLTURNCOUNT = 0
SET /a PLAYERREFLECTTURNCOUNT = 0
SET /a PLAYERREGENTURNCOUNT = 0

SET /a PLAYERMED = 0
SET /a PLAYERFOC = 0
SET /a PLAYERAIM = 0
SET /a PLAYERHIDE = 0