REM Player's Offensive Magic
SET /a COUNT = 0
:OFFLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYER!OFF%COUNT%SPELL!ENABLED = 0
IF %COUNT% LSS %OFFSPELLTOT% (
	GOTO :OFFLOOPSTART
)
SET /a COUNT = 0
:STATLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYER!STAT%COUNT%SPELL!ENABLED = 0
IF %COUNT% LSS %STATSPELLTOT% (
	GOTO :STATLOOPSTART
)
REM SET /a COUNT = 0
REM :DEBLOOPSTART
REM SET /a COUNT=%COUNT%+1
REM SET /a PLAYERDAMAGE!DEB%COUNT%STAT!ENABLED = 0
REM IF %COUNT% LSS %DEBSPELLTOT% (
REM 	GOTO :DEBLOOPSTART
REM )
SET /a COUNT = 0
:RESTLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYER!REST%COUNT%SPELL!ENABLED = 0
IF %COUNT% LSS %RESTSPELLTOT% (
	GOTO :RESTLOOPSTART
)
SET /a COUNT = 0
:SUPPLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYER!SUPP%COUNT%SPELL!ENABLED = 0
IF %COUNT% LSS %SUPPSPELLTOT% (
	GOTO :SUPPLOOPSTART
)

GOTO :EOF