CLS
ECHO.
ECHO Choose your difficulty
ECHO.
ECHO. 1 - Easy
ECHO. 2 - Hard
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P DIFFICULTYTEMP=
ECHO.
IF "%DIFFICULTYTEMP%" EQU "0" (
	ECHO.
) ELSE IF "%DIFFICULTYTEMP%" EQU "1" (
	SET DIFFICULTY=EASY
) ELSE IF "%DIFFICULTYTEMP%" EQU "2" (
	SET DIFFICULTY=HARD
) ELSE (
	GOTO :CHOICE
)
GOTO :EOF
