SET MAP=castle
SET /a PLAYERXCOORD = 3
SET /a PLAYERYCOORD = 5
SET /a PLAYERKEYITEM%MAGSTONE1ID%ACQUIRED = 1
SET /a PLAYERKEYITEM%MAGSTONE2ID%ACQUIRED = 1
SET /a PLAYERKEYITEM%MAGSTONE3ID%ACQUIRED = 1
SET /a CAVEBOSSALIVE = 0
SET /a CAVEENTER = 1
SET /a MINEBOSS2ALIVE = 0
SET /a BEATMINEBOSS2 = 1
SET /a MINEBOSS1ALIVE = 0
SET /a BEATMINEBOSS1 = 1
SET /a PLAYERGIL = 1000000
SET /a PLAYERLVL = 60
SET /a EXP = ((%PLAYERLVL%-1)*200)+50
SET /a PLAYERBASEMAXHP = 9999
SET /a PLAYERHP = 9999
SET /a PLAYERBASEMAXMP = 5000
SET /a PLAYERMP = 5000
SET /a PLAYERBASESTR = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEEND = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEMAG = 5 + %PLAYERLVL%/2
SET /a PLAYERBASESPR = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEACC = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEEVA = 5 + %PLAYERLVL%/2
SET /a PLAYERBASESPD = 5 + %PLAYERLVL%/2
SET /a PLAYERBASELCK = 5 + %PLAYERLVL%/2


SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERITEM%COUNT%NUM = 10
IF %COUNT% LSS %ITEMTOTAL% (
	GOTO :LOOPSTART
)

SET /a COUNT = 0
:LOOP2START
SET /a COUNT=%COUNT%+1
SET /a PLAYERSPECIALITEM%COUNT%NUM = 10
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :LOOP2START
)

SET /a COUNT = 0
:LOOP3START
SET /a COUNT=%COUNT%+1
SET /a PLAYERWEAPON%COUNT%NUM = 2
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :LOOP3START
)

SET /a COUNT = 0
:LOOP4START
SET /a COUNT=%COUNT%+1
SET /a PLAYERARMOUR%COUNT%NUM = 2
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :LOOP4START
)

SET /a COUNT = 0
:LOOP5START
SET /a COUNT=%COUNT%+1
SET /a PLAYERACCESSORY%COUNT%NUM = 2
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :LOOP5START
)

SET /a ROULETTEPROFIT = 399
SET /a BLACKJACKPROFIT = 300
SET /a SLOTMACHINEPROFIT = 300
SET /a TOTALCASINOPROFIT = 999

REM Reducing all of the skill AP costs and unlock thresholds to 1
SET /a COUNT = 0
:SKILLLOOP
SET /a COUNT = %COUNT% + 1
SET /a SKILL%COUNT%APCOST = 1
SET /a SKILL%COUNT%UNLOCKTHRESHOLD = 1
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILLLOOP
)

REM Making all of the items available to buy in the shop
SET /a COUNT = 0
:ITEMLOOP
SET /a COUNT = %COUNT% + 1
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 1
IF %COUNT% LSS %ITEMTOTAL% (
	GOTO :ITEMLOOP
)

SET /a ENEMY1CAUGHT = 1

SET /a REMOTEACCESSTRUE = 1
SET /a TEMPLEREMOTEACCESS = 1
SET /a TRAININGREMOTEACCESS = 1
SET /a DWARFMINEREMOTEACCESS = 1
SET /a BLACKSMITHREMOTEACCESS = 1
SET /a ALCHEMISTREMOTEACCESS = 1
SET /a GURUREMOTEACCESS = 1
SET /a CASINOREMOTEACCESS = 1
SET /a CASINOBOUGHT = 1
SET /a SHOPREMOTEACCESS = 1
SET /a SHOP1REMOTEACCESS = 1
SET /a SHOP2REMOTEACCESS = 1
SET /a SHOP3REMOTEACCESS = 1
SET /a SHOP4REMOTEACCESS = 1
SET /a SHOP5REMOTEACCESS = 1

SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTACTIVE = 1
IF %COUNT% LSS %TOWNTOT% (
	GOTO :LOOP
)