SET /a ROUND = 0
SET /a FAIL = 0
CLS
ECHO.
ECHO You'll need to press whatever value comes up, are you ready?
ECHO.
pause
:START
SET /a RANNUMTEMP=(%RANDOM% %% 27) + 1
SET RANNUM=%RANNUMTEMP%
IF %RANNUMTEMP% GEQ 10 (
	CALL :ADJUST
)
CALL :NEXTROUND
IF %ROUND% GEQ 50 (
	CALL :WIN
	GOTO :EOF
)
IF %FAIL% EQU 1 (
	GOTO :EOF
)
GOTO :START


:ADJUST
IF %RANNUMTEMP% EQU 10 (
	SET RANNUM=Q
) ELSE IF %RANNUMTEMP% EQU 11 (
	SET RANNUM=W
) ELSE IF %RANNUMTEMP% EQU 12 (
	SET RANNUM=E
) ELSE IF %RANNUMTEMP% EQU 13 (
	SET RANNUM=R
) ELSE IF %RANNUMTEMP% EQU 14 (
	SET RANNUM=T
) ELSE IF %RANNUMTEMP% EQU 15 (
	SET RANNUM=Y
) ELSE IF %RANNUMTEMP% EQU 16 (
	SET RANNUM=A
) ELSE IF %RANNUMTEMP% EQU 17 (
	SET RANNUM=S
) ELSE IF %RANNUMTEMP% EQU 18 (
	SET RANNUM=D
) ELSE IF %RANNUMTEMP% EQU 19 (
	SET RANNUM=F
) ELSE IF %RANNUMTEMP% EQU 20 (
	SET RANNUM=G
) ELSE IF %RANNUMTEMP% EQU 21 (
	SET RANNUM=H
) ELSE IF %RANNUMTEMP% EQU 22 (
	SET RANNUM=Z
) ELSE IF %RANNUMTEMP% EQU 23 (
	SET RANNUM=X
) ELSE IF %RANNUMTEMP% EQU 24 (
	SET RANNUM=C
) ELSE IF %RANNUMTEMP% EQU 25 (
	SET RANNUM=V
) ELSE IF %RANNUMTEMP% EQU 26 (
	SET RANNUM=B
) ELSE IF %RANNUMTEMP% EQU 27 (
	SET RANNUM=N
)
GOTO :EOF


:NEXTROUND
CLS
ECHO Score: %ROUND%
ECHO.
ECHO Press %RANNUM%
ECHO.
IF %DIFFICULTY% EQU 1 (
	CHOICE /C:123456789QWERTYASDFGHZXCVBN0 /N /T:2 /D:0
) ELSE IF %DIFFICULTY% EQU 2 (
	CHOICE /C:123456789QWERTYASDFGHZXCVBN0 /N /T:1 /D:0
) ELSE IF %DIFFICULTY% EQU 3 (
	CHOICE /C:123456789QWERTYASDFGHZXCVBN0 /N /T:1 /D:0
)
ECHO.
IF %ERRORLEVEL% EQU %RANNUMTEMP% (
	ECHO Correct^^!
	ECHO.
	SET /a ROUND = %ROUND% + 1
	CALL :WAITFORZERO
) ELSE (
	ECHO Oops, you lose^^!
	ECHO.
	SET /a FAIL = 1
	pause
)
GOTO :EOF

:WIN
CLS
ECHO.
ECHO Ok I think that's enough, you win^^!
ECHO.
pause
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF