@ECHO OFF
SETLOCAL enabledelayedexpansion
SET /a COUNT = 0

SET /a COUNT = %COUNT% + 1
SET WORD%COUNT%=example
SET /a WORD%COUNT%TIME = 3
SET /a COUNT = %COUNT% + 1
SET WORD%COUNT%=test
SET /a WORD%COUNT%TIME = 2
SET /a COUNT = %COUNT% + 1
SET WORD%COUNT%=nick
SET /a WORD%COUNT%TIME = 2
SET /a COUNT = %COUNT% + 1
SET WORD%COUNT%=matty
SET /a WORD%COUNT%TIME = 2
SET /a COUNT = %COUNT% + 1
SET WORD%COUNT%=paul
SET /a WORD%COUNT%TIME = 2


SET /a WORDTOTAL = %COUNT%

:START
SET /a CORRECT = 0
SET /a WORDNUM = %RANDOM% %% %WORDTOTAL% + 1
SET WORD=!WORD%WORDNUM%!
CLS
ECHO.
ECHO Ready?
ECHO.
pause>nul
CLS
ECHO.
ECHO Type %WORD%
SET SECTEMP=%TIME:~6,2%
SET /a STARTSEC = %SECTEMP%
:TYPE
ECHO.
SET /P TYPEDWORD=
ECHO.
IF /I %TYPEDWORD% EQU %WORD% (
	CALL :TIMEQUERY
) ELSE (
	ECHO That's not the right word^^!
	ECHO.
)
IF %CORRECT% EQU 1 (
	ECHO Correct^^!
	ECHO.
)
pause>nul
GOTO :START

:TIMEQUERY
SET SECTEMP=%TIME:~6,2%
SET /a ENDSEC = %SECTEMP%
SET /a SECDIFF = %ENDSEC% - %STARTSEC%
IF %SECDIFF% LSS 0 (
	SET /a SECDIFF = %SECDIFF% + 60
)
IF %SECDIFF% LSS !WORD%WORDNUM%TIME! (
	SET /a CORRECT = 1
) ELSE (
	ECHO You were too slow^^!
	ECHO.
)
GOTO :EOF

