:ALCHEMISTSHOP
CLS
ECHO.
ECHO %ALCHEMISTNAME%: Ok sir what would you like to buy?
ECHO.
ECHO. 1 - !SPECIALITEM%CRTSTONEID%NAME!s
IF %BEATALCHEMISTMON5% EQU 1 (
	ECHO. 2 - !SPECIALITEM%CMBSTONEID%NAME!s
)
ECHO. 0 - All done
ECHO.
:BUYCHOICE
SET /P BUYCHOICE=
ECHO.
IF "%BUYCHOICE%" EQU "1" (
	CALL :BUYCRTSTONES
) ELSE IF "%BUYCHOICE%" EQU "2" (
	IF %BEATALCHEMISTMON5% EQU 1 (
		CALL :BUYCMBSTONES
	) ELSE (
		GOTO :BUYCHOICE
	)
) ELSE IF "%BUYCHOICE%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :BUYCHOICE
)
GOTO :ALCHEMISTSHOP


:BUYCRTSTONES
CALL "%ALCHEMISTRESOURCEPATH%\alchemistdisplay.bat"
ECHO.
ECHO %ALCHEMISTNAME%: How many !SPECIALITEM%CRTSTONEID%NAME!s would you like to buy?
ECHO.
ECHO. Gil:   %PLAYERGIL%
ECHO. Price: %CREATIONSTONEPRICE%
ECHO. !PLAYERSPECIALITEM%CRTSTONEID%NUM! Currently owned
ECHO.
SET /P BUYNUM=
ECHO.
IF %BUYNUM% LSS 0 (
	ECHO %ALCHEMISTNAME%: Sorry no refunds.
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
) ELSE IF %BUYNUM% EQU 0 (
	GOTO :EOF
)
SET /a TOTALPRICE = %BUYNUM%*%CREATIONSTONEPRICE%
IF %TOTALPRICE% GTR %PLAYERGIL% (
	ECHO %ALCHEMISTNAME%: You don't have enough money for that
	ECHO.
	CALL :WAITFORTWO
	GOTO :BUYCRTSTONES
) ELSE (
	CALL :CRTSUCCESS
)
GOTO :EOF

:CRTSUCCESS
SET /a PLAYERGIL = %PLAYERGIL% - %TOTALPRICE%
SET /a PLAYERSPECIALITEM%CRTSTONEID%NUM = !PLAYERSPECIALITEM%CRTSTONEID%NUM! + %BUYNUM%
ECHO %ALCHEMISTNAME%: Here you are sir
ECHO.
CALL :WAITFORTWO
ECHO You now have !PLAYERSPECIALITEM%CRTSTONEID%NUM! !SPECIALITEM%CRTSTONEID%NAME!s
ECHO.
pause
GOTO :EOF

:BUYCMBSTONES
CALL "%ALCHEMISTRESOURCEPATH%\alchemistdisplay.bat"
ECHO.
ECHO %ALCHEMISTNAME%: How many !SPECIALITEM%CMBSTONEID%NAME!s would you like to buy?
ECHO.
ECHO. Gil:   %PLAYERGIL%
ECHO. Price: %COMBINATIONSTONEPRICE%
ECHO. !PLAYERSPECIALITEM%CMBSTONEID%NUM! Currently owned
ECHO.
SET /P BUYNUM=
ECHO.
IF %BUYNUM% LSS 0 (
	ECHO %ALCHEMISTNAME%: Sorry no refunds.
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
) ELSE IF %BUYNUM% EQU 0 (
	GOTO :EOF
)
SET /a TOTALPRICE = %BUYNUM%*%COMBINATIONSTONEPRICE%
IF %TOTALPRICE% GTR %PLAYERGIL% (
	ECHO %ALCHEMISTNAME%: You don't have enough money for that
	ECHO.
	CALL :WAITFORTWO
	GOTO :BUYCRTSTONES
) ELSE (
	CALL :CMBSUCCESS
)
GOTO :EOF

:CMBSUCCESS
SET /a PLAYERGIL = %PLAYERGIL% - %TOTALPRICE%
SET /a PLAYERSPECIALITEM%CMBSTONEID%NUM = !PLAYERSPECIALITEM%CMBSTONEID%NUM! + %BUYNUM%
ECHO %ALCHEMISTNAME%: Here you are sir
ECHO.
CALL :WAITFORTWO
ECHO You now have !PLAYERSPECIALITEM%CMBSTONEID%NUM! !SPECIALITEM%CMBSTONEID%NAME!s
ECHO.
pause
GOTO :EOF





:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF