:CREATEITEMSTART
CLS
ECHO.
ECHO %ALCHEMISTNAME%: Ok let's take a look at your spells and see what you can create
ECHO.
REM COUNT is set to 1 because the COUNT=%COUNT%+1 is inside the if statement
REM So it won't be evaluated in time for the ECHO
SET /a COUNT = 1
SET /a STATCOUNT = 0
SET /a OFFCOUNT = 0
SET /a SUPPCOUNT = 0
SET /a ITEMCOUNT = %STATITEMSTART%
:STATLOOPSTART
SET /a STATCOUNT = %STATCOUNT%+1
SET /a ITEMCOUNT = %ITEMCOUNT%+1
SET TEMP=!STAT%STATCOUNT%SPELL!
IF !PLAYER%TEMP%ENABLED! EQU 1 (
	ECHO. %COUNT% - !ITEM%ITEMCOUNT%NAME!
	ECHO         !ITEM%ITEMCOUNT%DESCRIPTION!
	ECHO.
	SET TEMP%COUNT%NAME=!ITEM%ITEMCOUNT%NAME!
	SET /a COUNT = %COUNT%+1
)
IF %ITEMCOUNT% LSS %STATITEMEND% (
	GOTO :STATLOOPSTART
)
SET /a ITEMCOUNT = %OFFITEMSTART%
:OFFLOOPSTART
SET /a OFFCOUNT = %OFFCOUNT%+1
SET /a ITEMCOUNT = %ITEMCOUNT%+1
SET TEMP=!OFF%OFFCOUNT%SPELL!
IF !PLAYER%TEMP%ENABLED! EQU 1 (
	ECHO. %COUNT% - !ITEM%ITEMCOUNT%NAME!
	ECHO         !ITEM%ITEMCOUNT%DESCRIPTION!
	ECHO.
	SET TEMP%COUNT%NAME=!ITEM%ITEMCOUNT%NAME!
	SET /a COUNT = %COUNT%+1
)
IF %ITEMCOUNT% LSS %OFFITEMEND% (
	GOTO :OFFLOOPSTART
)
SET /a ITEMCOUNT = %SUPPITEMSTART%
:SUPPLOOPSTART
SET /a SUPPCOUNT = %SUPPCOUNT%+1
SET /a ITEMCOUNT = %ITEMCOUNT%+1
SET TEMP=!SUPP%SUPPCOUNT%SPELL!
IF !PLAYER%TEMP%ENABLED! EQU 1 (
	ECHO. %COUNT% - !ITEM%ITEMCOUNT%NAME!
	ECHO         !ITEM%ITEMCOUNT%DESCRIPTION!
	ECHO.
	SET TEMP%COUNT%NAME=!ITEM%ITEMCOUNT%NAME!
	SET /a COUNT = %COUNT%+1
)
IF %ITEMCOUNT% LSS %SUPPITEMEND% (
	GOTO :SUPPLOOPSTART
)
ECHO. 0 - Back
ECHO.
:CHOICE1
SET /P ITEMCREATECHOICE=
IF "%ITEMCREATECHOICE%" EQU "" (
	GOTO :CHOICE1
)
IF %ITEMCREATECHOICE% GTR %COUNT% (
	GOTO :CHOICE1
) ELSE IF %ITEMCREATECHOICE% LSS 0 (
	GOTO :CHOICE1
) ELSE IF %ITEMCREATECHOICE% EQU 0 (
	GOTO :EOF
) ELSE (
	CALL :CREATEITEM
)
GOTO :EOF


:CREATEITEM
CALL :STATICITEMSET
CALL :ITEMNUM
GOTO :EOF


:STATICITEMSET
SET /a COUNT = 0
:NAMELOOPSTART
SET /a COUNT = %COUNT%+1
IF !TEMP%ITEMCREATECHOICE%NAME! EQU !ITEM%COUNT%NAME! (
	SET /a CREATEITEMCHOICE = %COUNT%
) ELSE (
	GOTO :NAMELOOPSTART
)
GOTO :EOF

:ITEMNUM
CLS
ECHO.
ECHO. !SPECIALITEM%CRTSTONEID%NAME!s - !PLAYERSPECIALITEM%CRTSTONEID%NUM!
ECHO. Gil - %PLAYERGIL%
ECHO.
ECHO %ALCHEMISTNAME%: How many !ITEM%CREATEITEMCHOICE%NAME!s would you like to create?
ECHO            It's !ITEM%CREATEITEMCHOICE%COST! Gil and !ITEM%CREATEITEMCHOICE%CREATESTONES! !SPECIALITEM%CRTSTONEID%NAME!s per item
ECHO.
ECHO. Enter 0 to go back
ECHO.
:CHOICE2
SET /P CREATENUM=
ECHO.
IF "%CREATENUM%" EQU "" (
	GOTO :CHOICE2
)
IF %CREATENUM% EQU 0 (
	GOTO :EOF
)
IF %CREATENUM% LSS 0 (
	ECHO %ALCHEMISTNAME%: Stop being a tit
	ECHO.
	GOTO :ITEMNUM
)
SET /a STONECOST = %CREATENUM%*!ITEM%CREATEITEMCHOICE%CREATESTONES!
SET /a GILCOST = %CREATENUM%*!ITEM%CREATEITEMCHOICE%COST!
IF %STONECOST% GTR !PLAYERSPECIALITEM%CRTSTONEID%NUM! (
	ECHO %ALCHEMISTNAME%: You don't have enough !SPECIALITEM%CRTSTONEID%NAME!s for this
	ECHO.
	GOTO :ITEMNUM
) ELSE IF %GILCOST% GTR %PLAYERGIL% (
	ECHO %ALCHEMISTNAME%: You don't have enough Gil for this
	ECHO.
	GOTO :ITEMNUM
) ELSE (
	SET /a PLAYERITEM%CREATEITEMCHOICE%NUM = !PLAYERITEM%CREATEITEMCHOICE%NUM!+%CREATENUM%
	SET /a PLAYERGIL = %PLAYERGIL% - %GILCOST%
	SET /a PLAYERSPECIALITEM%CRTSTONEID%NUM = !PLAYERSPECIALITEM%CRTSTONEID%NUM! - %STONECOST%
	ECHO %ALCHEMISTNAME%: You have successfully created %CREATENUM% !ITEM%CREATEITEMCHOICE%NAME!s
	ECHO.
	pause
)
GOTO :EOF











:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
