SET MAP=CASTLE
SET %MAP%MUSICFOLDER=CASTLE
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 0
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
::Need knights1-4
::Knight1 is enemyID 45
SET /a TEMPEND = %BOSSIDSTART% + 17
SET /a ENEMYID = %BOSSIDSTART% + 13
:BOSSLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS %TEMPEND% (
	GOTO :BOSSLOOP
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 9
GOTO :EOF

:EXITS
SET /a COUNT = 0
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 0 
SET /a %MAP%EXIT%COUNT%YCOORD = 5
SET %MAP%EXIT%COUNT%NEWMAP=town3
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 10
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 4
:EXIT2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 4
SET /a %MAP%EXIT%COUNT%YCOORD = 5
SET %MAP%EXIT%COUNT%NEWMAP=castle2
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 2
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 4
:EXIT3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 9 
SET /a %MAP%EXIT%COUNT%YCOORD = 5
SET %MAP%EXIT%COUNT%NEWMAP=castle3
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 8
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 1

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF


:BUILDINGS
SET /a COUNT = 0
SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 5
SET /a %MAP%CHEST%COUNT%YCOORD = 1
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %EVASTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 3
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS
:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 6
SET /a %MAP%CHEST%COUNT%YCOORD = 1
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %ACCSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 3
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST3
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 6
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %REMEID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST4
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 5
SET /a %MAP%CHEST%COUNT%YCOORD = 9
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %SPRSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 3
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST5
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 6
SET /a %MAP%CHEST%COUNT%YCOORD = 9
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %ENDSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 3
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST6
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 12
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 3
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 1
SET /a %MAP%CHEST%COUNT%ARMOUR1 = %RUGCLOAKID%
SET /a %MAP%CHEST%COUNT%ARMOUR1NUM = 1
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF



:SPECIALFIGHTS
SET /a COUNT = 0
:SPECIALFIGHT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 5
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 2
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=KNIGHT1
SET %MAP%SPECIALFIGHT%COUNT%TOP=%KNIGHTTOP%
SET %MAP%SPECIALFIGHT%COUNT%MID=%KNIGHTMID%
SET %MAP%SPECIALFIGHT%COUNT%BOT=%KNIGHTBOT%
CALL :SETID

:SPECIALFIGHT2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 6
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 2
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=KNIGHT2
SET %MAP%SPECIALFIGHT%COUNT%TOP=%KNIGHTTOP%
SET %MAP%SPECIALFIGHT%COUNT%MID=%KNIGHTMID%
SET %MAP%SPECIALFIGHT%COUNT%BOT=%KNIGHTBOT%
CALL :SETID

:SPECIALFIGHT3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 5
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 8
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=KNIGHT3
SET %MAP%SPECIALFIGHT%COUNT%TOP=%KNIGHTTOP%
SET %MAP%SPECIALFIGHT%COUNT%MID=%KNIGHTMID%
SET %MAP%SPECIALFIGHT%COUNT%BOT=%KNIGHTBOT%
CALL :SETID

:SPECIALFIGHT4
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 6
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 8
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=KNIGHT4
SET %MAP%SPECIALFIGHT%COUNT%TOP=%KNIGHTTOP%
SET %MAP%SPECIALFIGHT%COUNT%MID=%KNIGHTMID%
SET %MAP%SPECIALFIGHT%COUNT%BOT=%KNIGHTBOT%
CALL :SETID

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=WALL2
SET %MAP%1-2=WALL2
SET %MAP%1-3=WALL2
SET %MAP%1-4=WALL2
SET %MAP%1-5=PATH1
SET %MAP%1-6=PATH1
SET %MAP%1-7=WALL2
SET %MAP%1-8=WALL2
SET %MAP%1-9=WALL2
SET %MAP%1-10=WALL2
SET %MAP%1-11=WALL2
SET %MAP%1-12=WALL2
SET %MAP%2-1=WALL2
SET %MAP%2-2=WALL2
SET %MAP%2-3=WALL2
SET %MAP%2-4=WALL2
SET %MAP%2-5=PATH1
SET %MAP%2-6=PATH1
SET %MAP%2-7=WALL2
SET %MAP%2-8=WALL2
SET %MAP%2-9=WALL2
SET %MAP%2-10=WALL2
SET %MAP%2-11=WALL2
SET %MAP%2-12=WALL2
SET %MAP%3-1=WALL2
SET %MAP%3-2=WALL2
SET %MAP%3-3=WALL2
SET %MAP%3-4=WALL2
SET %MAP%3-5=PATH1
SET %MAP%3-6=PATH1
SET %MAP%3-7=PATH1
SET %MAP%3-8=PATH1
SET %MAP%3-9=WALL2
SET %MAP%3-10=WALL2
SET %MAP%3-11=WALL2
SET %MAP%3-12=WALL2
SET %MAP%4-1=WALL2
SET %MAP%4-2=WALL2
SET %MAP%4-3=PATH1
SET %MAP%4-4=PATH1
SET %MAP%4-5=PATH1
SET %MAP%4-6=PATH1
SET %MAP%4-7=PATH1
SET %MAP%4-8=PATH1
SET %MAP%4-9=PATH1
SET %MAP%4-10=PATH1
SET %MAP%4-11=WALL2
SET %MAP%4-12=WALL2
SET %MAP%5-1=EXITLEFT
SET %MAP%5-2=PATH1
SET %MAP%5-3=PATH1
SET %MAP%5-4=LADDER
SET %MAP%5-5=PATH1
SET %MAP%5-6=PATH1
SET %MAP%5-7=PATH1
SET %MAP%5-8=PATH1
SET %MAP%5-9=LADDER
SET %MAP%5-10=PATH1
SET %MAP%5-11=PATH1
SET %MAP%5-12=PATH1
SET %MAP%6-1=WALL2
SET %MAP%6-2=WALL2
SET %MAP%6-3=PATH1
SET %MAP%6-4=PATH1
SET %MAP%6-5=PATH1
SET %MAP%6-6=PATH1
SET %MAP%6-7=PATH1
SET %MAP%6-8=PATH1
SET %MAP%6-9=PATH1
SET %MAP%6-10=PATH1
SET %MAP%6-11=WALL2
SET %MAP%6-12=WALL2
SET %MAP%7-1=WALL2
SET %MAP%7-2=WALL2
SET %MAP%7-3=WALL2
SET %MAP%7-4=WALL2
SET %MAP%7-5=PATH1
SET %MAP%7-6=PATH1
SET %MAP%7-7=PATH1
SET %MAP%7-8=PATH1
SET %MAP%7-9=WALL2
SET %MAP%7-10=WALL2
SET %MAP%7-11=WALL2
SET %MAP%7-12=WALL2
SET %MAP%8-1=WALL2
SET %MAP%8-2=WALL2
SET %MAP%8-3=WALL2
SET %MAP%8-4=WALL2
SET %MAP%8-5=PATH1
SET %MAP%8-6=PATH1
SET %MAP%8-7=WALL2
SET %MAP%8-8=WALL2
SET %MAP%8-9=WALL2
SET %MAP%8-10=WALL2
SET %MAP%8-11=WALL2
SET %MAP%8-12=WALL2
SET %MAP%9-1=WALL2
SET %MAP%9-2=WALL2
SET %MAP%9-3=WALL2
SET %MAP%9-4=WALL2
SET %MAP%9-5=PATH1
SET %MAP%9-6=PATH1
SET %MAP%9-7=WALL2
SET %MAP%9-8=WALL2
SET %MAP%9-9=WALL2
SET %MAP%9-10=WALL2
SET %MAP%9-11=WALL2
SET %MAP%9-12=WALL2
GOTO :EOF


REM MAPDISPLAYVARTP=    …ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕª
REM MAPDISPLAYVAR9A=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±∫
REM MAPDISPLAYVAR9B=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR9C=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫Tutorial∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8A=    ∫±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8C=    ∫±±±±±∫  Shop  ∫±±±±±±±±±±±±±±±±±±±±±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±∫
REM MAPDISPLAYVAR7A=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7C=    ∫±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6A=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6B=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6C=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR5A=    ∫±±±±±±±±±±                                        …ÕÕÕÕÕÕÕÕª∫
REM MAPDISPLAYVAR5B=    ∫±±±±±±±±±±                                        ∫  Cave  ∫∫
REM MAPDISPLAYVAR5C=    ∫±±±±±±±±±±                                        »ÕÕÕÕÕÕÕÕº∫
REM MAPDISPLAYVAR4A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫ Temple ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2A=    ∫…ÕÕÕÕÕÕÕÕª                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2B=    ∫∫        ∫                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2C=    ∫∫Training∫                         »ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1A=    ∫∫  Area  ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1B=    ∫∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1C=    ∫»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVARBM=    »ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº
