SET MAP=CAVE1LVL2
SET %MAP%MUSICFOLDER=CAVE
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 9
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 12 (
	GOTO :ENEMYLOOP
)
SET /a ENEMYID = %BOSSIDSTART% + 9
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
SET /a ENEMYID = %BOSSIDSTART% + 10
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
SET /a ENEMYID = %BOSSIDSTART% + 11
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 9
SET /a %MAP%YLIMIT = 7
GOTO :EOF

:EXITS
SET /a COUNT = 0
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 5 
SET /a %MAP%EXIT%COUNT%YCOORD = 1
SET %MAP%EXIT%COUNT%NEWMAP=cave1
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 8
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 2

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a %MAP%BUILDINGTOT = 0
GOTO :EOF

:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 3
SET /a %MAP%CHEST%COUNT%YCOORD = 4
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %SUPPOTID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 7
SET /a %MAP%CHEST%COUNT%YCOORD = 4
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 1
SET /a %MAP%CHEST%COUNT%ARMOUR1 = %ALFOILID%
SET /a %MAP%CHEST%COUNT%ARMOUR1NUM = 1
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST3
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 5
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 2
SET /a %MAP%CHEST%COUNT%ITEM1 = %HIETHID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%ITEM2 = %ALIFEID%
SET /a %MAP%CHEST%COUNT%ITEM2NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST4
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 5
SET /a %MAP%CHEST%COUNT%YCOORD = 6
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %GRENID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 2
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %STRSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 2
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 1
SET /a %MAP%CHEST%COUNT%ACCESSORY1 = %SAFBRACID%
SET /a %MAP%CHEST%COUNT%ACCESSORY1NUM = 1
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0
:SPECIALFIGHT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 3
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 5
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=CAVEMON1
SET %MAP%SPECIALFIGHT%COUNT%TOP=± Ï ±
SET %MAP%SPECIALFIGHT%COUNT%MID=±À²Ù±
SET %MAP%SPECIALFIGHT%COUNT%BOT=±ÚÁ¿±

:SPECIALFIGHT2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 7
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 5
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=CAVEMON2
SET %MAP%SPECIALFIGHT%COUNT%TOP=± Ï ±
SET %MAP%SPECIALFIGHT%COUNT%MID=±À²Ù±
SET %MAP%SPECIALFIGHT%COUNT%BOT=±ÚÁ¿±
CALL :SETID

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
:SPECIALLOCATION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 5
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 7
SET %MAP%SPECIALLOCATION%COUNT%FILE=pacmanbattle
SET %MAP%SPECIALLOCATION%COUNT%PATH=CAVERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 0

SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=WALL1
SET %MAP%1-2=WALL1
SET %MAP%1-4=WALL1
SET %MAP%1-3=WALL1
SET %MAP%1-5=LADDER
SET %MAP%1-6=WALL1
SET %MAP%1-7=WALL1
SET %MAP%1-8=WALL1
SET %MAP%1-9=WALL1
SET %MAP%2-1=MINE1
SET %MAP%2-2=MINE1
SET %MAP%2-3=MINE1
SET %MAP%2-4=MINE1
SET %MAP%2-5=MINE1
SET %MAP%2-6=MINE1
SET %MAP%2-7=MINE1
SET %MAP%2-8=MINE1
SET %MAP%2-9=MINE1
SET %MAP%3-1=MINE1
SET %MAP%3-2=WALL1
SET %MAP%3-3=WALL1
SET %MAP%3-4=WALL1
SET %MAP%3-5=MINE1
SET %MAP%3-6=WALL1
SET %MAP%3-7=WALL1
SET %MAP%3-8=WALL1
SET %MAP%3-9=MINE1
SET %MAP%4-1=MINE1
SET %MAP%4-2=WALL1
SET %MAP%4-3=MINE1
SET %MAP%4-4=WALL1
SET %MAP%4-5=MINE1
SET %MAP%4-6=WALL1
SET %MAP%4-7=MINE1
SET %MAP%4-8=WALL1
SET %MAP%4-9=MINE1
SET %MAP%5-1=MINE1
SET %MAP%5-2=WALL1
SET %MAP%5-3=MINE1
SET %MAP%5-4=WALL1
SET %MAP%5-5=MINE1
SET %MAP%5-6=WALL1
SET %MAP%5-7=MINE1
SET %MAP%5-8=WALL1
SET %MAP%5-9=MINE1
SET %MAP%6-1=MINE1
SET %MAP%6-2=WALL1
SET %MAP%6-3=MINE1
SET %MAP%6-4=WALL1
SET %MAP%6-5=MINE1
SET %MAP%6-6=WALL1
SET %MAP%6-7=MINE1
SET %MAP%6-8=WALL1
SET %MAP%6-9=MINE1
SET %MAP%7-1=MINE1
SET %MAP%7-2=MINE1
SET %MAP%7-3=MINE1
SET %MAP%7-4=MINE1
SET %MAP%7-5=MINE1
SET %MAP%7-6=MINE1
SET %MAP%7-7=MINE1
SET %MAP%7-8=MINE1
SET %MAP%7-9=MINE1
GOTO :EOF

REM MAPDISPLAYVARTP=    ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
REM MAPDISPLAYVAR7A=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR7B=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR7C=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR6A=    º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
REM MAPDISPLAYVAR6B=    º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
REM MAPDISPLAYVAR6C=    º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
REM MAPDISPLAYVAR5A=    º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST5TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
REM MAPDISPLAYVAR5B=    º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST5MID%ªªªªª%MON2MID%ªªªªª±±±±±º
REM MAPDISPLAYVAR5C=    º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
REM MAPDISPLAYVAR4A=    º±±±±±ªªªªª%CHEST6TOP%ªªªªª±±±±±ªªªªª%CHEST7TOP%ªªªªª±±±±±º
REM MAPDISPLAYVAR4B=    º±±±±±ªªªªª%CHEST6MID%ªªªªª±±±±±ªªªªª%CHEST7MID%ªªªªª±±±±±º
REM MAPDISPLAYVAR4C=    º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
REM MAPDISPLAYVAR3A=    º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
REM MAPDISPLAYVAR3B=    º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
REM MAPDISPLAYVAR3C=    º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
REM MAPDISPLAYVAR2A=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR2B=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR2C=    º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
REM MAPDISPLAYVAR1A=    ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1B=    ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1C=    ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
REM MAPDISPLAYVARBM=    ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
