SET MAP=FOREST1MIST0
SET %MAP%MUSICFOLDER=FOREST
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 10
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 31
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 35 (
	GOTO :ENEMYLOOP
)
SET /a ENEMYID = %BOSSIDSTART% + 58
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
SET /a ENEMYID = %BOSSIDSTART% + 59
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
GOTO :EOF


:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 8
GOTO :EOF

:EXITS
SET /a COUNT = 0
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 0 
SET /a %MAP%EXIT%COUNT%YCOORD = 1
SET %MAP%EXIT%COUNT%NEWMAP=town4
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 10
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 7
:EXIT2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 13
SET /a %MAP%EXIT%COUNT%YCOORD = 1
SET %MAP%EXIT%COUNT%NEWMAP=town6
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 3
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 2

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:TREE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=tree
SET %MAP%BUILDING%COUNT%PATH=FORESTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 6
::y-x
SET %MAP%BUILDING%COUNT%CELL1=8-6
SET %MAP%BUILDING%COUNT%CELL2=8-7
SET %MAP%BUILDING%COUNT%CELL3=7-6
SET %MAP%BUILDING%COUNT%CELL4=7-7
SET %MAP%BUILDING%COUNT%CELL5=6-6
SET %MAP%BUILDING%COUNT%CELL6=6-7
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=¾ ¾ ¾
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB= ¾  *
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=¾  /.
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=¾ ¾ ¾
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB= ¾ ¾ 
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=\ ¾ ¾
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=¾ /..
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=  /'.
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC= /.''
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA='\  ¾
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB='\ ¾ 
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=.'\ ¾
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA= /.'.
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=/'.''
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=~~~[_
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA='.\ ¾
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=.'.\ 
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=]~~~ 
CALL :BUILDINGVARS
SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF

:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 5
SET /a %MAP%CHEST%COUNT%YCOORD = 8
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %CRITICALSTRIKESTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 12
SET /a %MAP%CHEST%COUNT%YCOORD = 6
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %HALFAPSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST3
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 12
SET /a %MAP%CHEST%COUNT%YCOORD = 7
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 1
SET /a %MAP%CHEST%COUNT%ACCESSORY1 = %APRINGID%
SET /a %MAP%CHEST%COUNT%ACCESSORY1NUM = 1
CALL :CHESTVARS

:CHEST4
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 12
SET /a %MAP%CHEST%COUNT%YCOORD = 8
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %XPOTID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 2
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 1
SET /a %MAP%CHEST%COUNT%ARMOUR1 = %IRONARMOURID%
SET /a %MAP%CHEST%COUNT%ARMOUR1NUM = 1
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

::This one is behind the enemy
:CHEST5
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 9
SET /a %MAP%CHEST%COUNT%YCOORD = 8
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %FULLAPSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST6
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 8
SET /a %MAP%CHEST%COUNT%YCOORD = 1
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %DOUBLELIMSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST7
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 9
SET /a %MAP%CHEST%COUNT%YCOORD = 1
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %STLMOREGILSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0
:SPECIALFIGHT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 10
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 8
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=FORESTBOSS
SET %MAP%SPECIALFIGHT%COUNT%TOP=° Ï °
SET %MAP%SPECIALFIGHT%COUNT%MID=°À²Ù°
SET %MAP%SPECIALFIGHT%COUNT%BOT=°ÚÁ¿°
CALL :SETID

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=EXITLEFT
SET %MAP%1-2=GRASS
SET %MAP%1-3=WALL3
SET %MAP%1-4=WALL3
SET %MAP%1-5=WALL3
SET %MAP%1-6=WALL3
SET %MAP%1-7=WALL3
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%1-10=GRASS
SET %MAP%1-11=GRASS
SET %MAP%1-12=EXITRIGHT
SET %MAP%2-1=GRASS
SET %MAP%2-2=GRASS
SET %MAP%2-3=GRASS
SET %MAP%2-4=GRASS
SET %MAP%2-5=WALL3
SET %MAP%2-6=WALL3
SET %MAP%2-7=WALL3
SET %MAP%2-8=GRASS
SET %MAP%2-9=GRASS
SET %MAP%2-10=GRASS
SET %MAP%2-11=WALL3
SET %MAP%2-12=WALL3
SET %MAP%3-1=WALL3
SET %MAP%3-2=WALL3
SET %MAP%3-3=GRASS
SET %MAP%3-4=GRASS
SET %MAP%3-5=WALL3
SET %MAP%3-6=GRASS
SET %MAP%3-7=GRASS
SET %MAP%3-8=GRASS
SET %MAP%3-9=GRASS
SET %MAP%3-10=WALL3
SET %MAP%3-11=WALL3
SET %MAP%3-12=WALL3
SET %MAP%4-1=WALL3
SET %MAP%4-2=WALL3
SET %MAP%4-3=GRASS
SET %MAP%4-4=GRASS
SET %MAP%4-5=GRASS
SET %MAP%4-6=GRASS
SET %MAP%4-7=GRASS
SET %MAP%4-8=GRASS
SET %MAP%4-9=WALL3
SET %MAP%4-10=WALL3
SET %MAP%4-11=WALL3
SET %MAP%4-12=WALL3
SET %MAP%5-1=WALL3
SET %MAP%5-2=WALL3
SET %MAP%5-3=GRASS
SET %MAP%5-4=GRASS
SET %MAP%5-5=GRASS
SET %MAP%5-6=GRASS
SET %MAP%5-7=GRASS
SET %MAP%5-8=GRASS
SET %MAP%5-9=GRASS
SET %MAP%5-10=WALL3
SET %MAP%5-11=WALL3
SET %MAP%5-12=WALL3
SET %MAP%6-1=WALL3
SET %MAP%6-2=WALL3
SET %MAP%6-3=WALL3
SET %MAP%6-4=WALL3
SET %MAP%6-5=GRASS
SET %MAP%6-6=GRASS
SET %MAP%6-7=GRASS
SET %MAP%6-8=WALL3
SET %MAP%6-9=GRASS
SET %MAP%6-10=GRASS
SET %MAP%6-11=GRASS
SET %MAP%6-12=GRASS
SET %MAP%7-1=WALL3
SET %MAP%7-2=WALL3
SET %MAP%7-3=WALL3
SET %MAP%7-4=WALL3
SET %MAP%7-5=GRASS
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=WALL3
SET %MAP%7-9=WALL3
SET %MAP%7-10=GRASS
SET %MAP%7-11=GRASS
SET %MAP%7-12=GRASS
SET %MAP%8-1=WALL3
SET %MAP%8-2=WALL3
SET %MAP%8-3=WALL3
SET %MAP%8-4=WALL3
SET %MAP%8-5=GRASS
SET %MAP%8-6=GRASS
SET %MAP%8-7=GRASS
SET %MAP%8-8=WALL3
SET %MAP%8-9=GRASS
SET %MAP%8-10=GRASS
SET %MAP%8-11=GRASS
SET %MAP%8-12=GRASS
GOTO :EOF

REM MAPDISPLAYVARTP=    ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
REM MAPDISPLAYVAR7A=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1TOP%ªªªªªªªªªª±±±±±%BOSSTOP%
REM MAPDISPLAYVAR7B=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1MID%ªªªªªªªªªª±±±±±%BOSSMID%
REM MAPDISPLAYVAR7C=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªª±±±±±%BOSSBOT%
REM MAPDISPLAYVAR6A=    ºªªªªªªªªªª%CHEST2TOP%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6B=    ºªªªªªªªªªª%CHEST2MID%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6C=    ºªªªªªªªªªª%CHESTBOTT%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR5A=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5B=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5C=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4A=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4B=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4C=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR1A=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3TOP%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1B=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3MID%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1C=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVARBM=    ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼