SET MAP=LAKE4
SET %MAP%MUSICFOLDER=WATER
SET /a %MAP%UNDERWATER = 1
SET /a %MAP%RANBATTLECHANCE = 0
::CALL :LOADENEMIES
CALL :EDGES
CALL :DROWNRESPAWN
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 8
GOTO :EOF

:DROWNRESPAWN
SET /a %MAP%DROWNRESPAWNXCOORD = 1
SET /a %MAP%DROWNRESPAWNYCOORD = 2
GOTO :EOF

:EXITS
SET /a COUNT = 0
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 0 
SET /a %MAP%EXIT%COUNT%YCOORD = 2
SET %MAP%EXIT%COUNT%NEWMAP=lake3
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 11
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 2

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET %MAP%BUILDING%COUNT%FILE=enterragata
SET %MAP%BUILDING%COUNT%PATH=HELLRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 8
SET %MAP%BUILDING%COUNT%CELL1=9-10
SET %MAP%BUILDING%COUNT%CELL2=9-11
SET %MAP%BUILDING%COUNT%CELL3=8-10
SET %MAP%BUILDING%COUNT%CELL4=8-11
SET %MAP%BUILDING%COUNT%CELL5=7-10
SET %MAP%BUILDING%COUNT%CELL6=7-11
SET %MAP%BUILDING%COUNT%CELL7=6-10
SET %MAP%BUILDING%COUNT%CELL8=6-11
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=   \ß
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=   Ãþ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=ß/   
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=þ´   
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=   ³Ü
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=Ï ÚÁÁ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ÈÍ´ u
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=Ü³   
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=ÁÁ¿ Ï
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=u ÃÍ¼
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=  ³ ~
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=  ³ ~
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=  ÀÂÄ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=~ ³  
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=~ ³  
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=ÄÂÙ  
SET %MAP%BUILDING%COUNT%CELL7DISPLAYA=   º 
SET %MAP%BUILDING%COUNT%CELL7DISPLAYB=   º 
SET %MAP%BUILDING%COUNT%CELL7DISPLAYC=     
SET %MAP%BUILDING%COUNT%CELL8DISPLAYA= º   
SET %MAP%BUILDING%COUNT%CELL8DISPLAYB= º   
SET %MAP%BUILDING%COUNT%CELL8DISPLAYC=     
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF

:CHESTS
SET /a COUNT = 0

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0
SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
GOTO :EOF

:DEFINECELLS
::Y-X
SET %MAP%1-1=WALL1
SET %MAP%1-2=WALL1
SET %MAP%1-3=WALL1
SET %MAP%1-4=WALL1
SET %MAP%1-5=WALL1
SET %MAP%1-6=WALL1
SET %MAP%1-7=WALL1
SET %MAP%1-8=WALL1
SET %MAP%1-9=WALL1
SET %MAP%1-10=WALL1
SET %MAP%1-11=WALL1
SET %MAP%1-12=WALL1
SET %MAP%2-1=EXITLEFT
SET %MAP%2-2=WATER
SET %MAP%2-3=WALL1
SET %MAP%2-4=WATER
SET %MAP%2-5=WATER
SET %MAP%2-6=WATER
SET %MAP%2-7=WALL1
SET %MAP%2-8=WATER
SET %MAP%2-9=WATER
SET %MAP%2-10=WATER
SET %MAP%2-11=WALL1
SET %MAP%2-12=WALL1
SET %MAP%3-1=WALL1
SET %MAP%3-2=WATER
SET %MAP%3-3=WALL1
SET %MAP%3-4=WATER
SET %MAP%3-5=WALL1
SET %MAP%3-6=WATER
SET %MAP%3-7=WALL1
SET %MAP%3-8=WATER
SET %MAP%3-9=WALL1
SET %MAP%3-10=WATER
SET %MAP%3-11=WALL1
SET %MAP%3-12=WALL1
SET %MAP%4-1=WALL1
SET %MAP%4-2=WATER
SET %MAP%4-3=WALL1
SET %MAP%4-4=WATER
SET %MAP%4-5=WALL1
SET %MAP%4-6=WATER
SET %MAP%4-7=WALL1
SET %MAP%4-8=WATER
SET %MAP%4-9=WALL1
SET %MAP%4-10=WATER
SET %MAP%4-11=WALL1
SET %MAP%4-12=WALL1
SET %MAP%5-1=WALL1
SET %MAP%5-2=WATER
SET %MAP%5-3=WALL1
SET %MAP%5-4=WATER
SET %MAP%5-5=WALL1
SET %MAP%5-6=WATER
SET %MAP%5-7=WALL1
SET %MAP%5-8=WATER
SET %MAP%5-9=WALL1
SET %MAP%5-10=WATER
SET %MAP%5-11=WATER
SET %MAP%5-12=WALL1
SET %MAP%6-1=WALL1
SET %MAP%6-2=WATER
SET %MAP%6-3=WALL1
SET %MAP%6-4=WATER
SET %MAP%6-5=WALL1
SET %MAP%6-6=WATER
SET %MAP%6-7=WALL1
SET %MAP%6-8=WATER
SET %MAP%6-9=WALL1
SET %MAP%6-10=WATER
SET %MAP%6-11=WATER
SET %MAP%6-12=WALL1
SET %MAP%7-1=WALL1
SET %MAP%7-2=WATER
SET %MAP%7-3=WATER
SET %MAP%7-4=WATER
SET %MAP%7-5=WALL1
SET %MAP%7-6=WATER
SET %MAP%7-7=WATER
SET %MAP%7-8=WATER
SET %MAP%7-9=WALL1
SET %MAP%7-10=WATER
SET %MAP%7-11=WATER
SET %MAP%7-12=WALL1
SET %MAP%8-1=WALL1
SET %MAP%8-2=WALL1
SET %MAP%8-3=WALL1
SET %MAP%8-4=WALL1
SET %MAP%8-5=WALL1
SET %MAP%8-6=WALL1
SET %MAP%8-7=WALL1
SET %MAP%8-8=WALL1
SET %MAP%8-9=WALL1
SET %MAP%8-10=WALL1
SET %MAP%8-11=WALL1
SET %MAP%8-12=WALL1
GOTO :EOF

REM MAPDISPLAYVARTP=    ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
REM MAPDISPLAYVAR7A=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1TOP%ªªªªªªªªªª±±±±±%BOSSTOP%
REM MAPDISPLAYVAR7B=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1MID%ªªªªªªªªªª±±±±±%BOSSMID%
REM MAPDISPLAYVAR7C=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªª±±±±±%BOSSBOT%
REM MAPDISPLAYVAR6A=    ºªªªªªªªªªª%CHEST2TOP%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6B=    ºªªªªªªªªªª%CHEST2MID%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6C=    ºªªªªªªªªªª%CHESTBOTT%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR5A=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5B=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5C=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4A=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4B=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4C=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR1A=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3TOP%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1B=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3MID%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1C=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVARBM=    ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼