SET MAP=LAKEPALACE
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 0
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a TEMPEND = %BOSSIDSTART% + 51
SET /a ENEMYID = %BOSSIDSTART% + 44
:BOSSLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS %TEMPEND% (
	GOTO :BOSSLOOP
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 8
SET /a %MAP%YLIMIT = 7
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 4 
SET /a %MAP%EXIT%COUNT%YCOORD = 0
SET %MAP%EXIT%COUNT%NEWMAP=town5
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 10
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 4
:EXIT2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 5
SET /a %MAP%EXIT%COUNT%YCOORD = 0
SET %MAP%EXIT%COUNT%NEWMAP=town5
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 10
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 4

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:HOME
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=seamenking
SET %MAP%BUILDING%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=7-4
SET %MAP%BUILDING%COUNT%CELL2=7-5
SET %MAP%BUILDING%COUNT%CELL3=6-4
SET %MAP%BUILDING%COUNT%CELL4=6-5
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=   _Ï
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=  / ¾
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC= // *
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=_   
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB= /º  
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC= /º  
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ç/ ³ 
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=   \_
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=     
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=³ º  
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB= \_  
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=î\_ 
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 1
SET /a %MAP%CHEST%COUNT%YCOORD = 2
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %STLBETTERSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 1
SET /a %MAP%CHEST%COUNT%YCOORD = 4
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %FINDMOREGILSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST3
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 1
SET /a %MAP%CHEST%COUNT%YCOORD = 6
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %ALIFEID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 1
SET /a %MAP%CHEST%COUNT%WEAPON1 = %OSTAFFID%
SET /a %MAP%CHEST%COUNT%WEAPON1NUM = 1
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST4
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 8
SET /a %MAP%CHEST%COUNT%YCOORD = 2
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %MPATTSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST5
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 8
SET /a %MAP%CHEST%COUNT%YCOORD = 4
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %SUPETHID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %STLSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST6
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 8
SET /a %MAP%CHEST%COUNT%YCOORD = 6
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %SUPPOTID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %INDUCEWEAKNESSRANSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
:SPECIALLOCATION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 2
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 2
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

:SPECIALLOCATION2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 2
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 4
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

:SPECIALLOCATION3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 2
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 6
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

:SPECIALLOCATION4
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 7
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 2
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

:SPECIALLOCATION5
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 7
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 4
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

:SPECIALLOCATION6
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 7
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 6
SET %MAP%SPECIALLOCATION%COUNT%FILE=palaceguard
SET %MAP%SPECIALLOCATION%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%KNIGHTTOP%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%KNIGHTMID%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%KNIGHTBOT%
CALL :SPECIALVARS

SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:SPECIALVARS
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-A=!%MAP%SPECIALLOCATION%COUNT%DISPLAYA!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-B=!%MAP%SPECIALLOCATION%COUNT%DISPLAYB!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-C=!%MAP%SPECIALLOCATION%COUNT%DISPLAYC!
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=WALL2
SET %MAP%1-2=WALL2
SET %MAP%1-3=FLOOR
SET %MAP%1-4=CARPETLEFT
SET %MAP%1-5=CARPETRIGHT
SET %MAP%1-6=FLOOR
SET %MAP%1-7=WALL2
SET %MAP%1-8=WALL2
SET %MAP%2-1=FLOOR
SET %MAP%2-2=FLOOR
SET %MAP%2-3=FLOOR
SET %MAP%2-4=CARPETLEFT
SET %MAP%2-5=CARPETRIGHT
SET %MAP%2-6=FLOOR
SET %MAP%2-7=FLOOR
SET %MAP%2-8=FLOOR
SET %MAP%3-1=WALL2
SET %MAP%3-2=WALL2
SET %MAP%3-3=FLOOR
SET %MAP%3-4=CARPETLEFT
SET %MAP%3-5=CARPETRIGHT
SET %MAP%3-6=FLOOR
SET %MAP%3-7=WALL2
SET %MAP%3-8=WALL2
SET %MAP%4-1=FLOOR
SET %MAP%4-2=FLOOR
SET %MAP%4-3=FLOOR
SET %MAP%4-4=CARPETLEFT
SET %MAP%4-5=CARPETRIGHT
SET %MAP%4-6=FLOOR
SET %MAP%4-7=FLOOR
SET %MAP%4-8=FLOOR
SET %MAP%5-1=WALL2
SET %MAP%5-2=WALL2
SET %MAP%5-3=FLOOR
SET %MAP%5-4=CARPETLEFT
SET %MAP%5-5=CARPETRIGHT
SET %MAP%5-6=FLOOR
SET %MAP%5-7=WALL2
SET %MAP%5-8=WALL2
SET %MAP%6-1=FLOOR
SET %MAP%6-2=FLOOR
SET %MAP%6-3=FLOOR
SET %MAP%6-4=CARPETLEFT
SET %MAP%6-5=CARPETRIGHT
SET %MAP%6-6=FLOOR
SET %MAP%6-7=FLOOR
SET %MAP%6-8=FLOOR
SET %MAP%7-1=WALL2
SET %MAP%7-2=WALL2
SET %MAP%7-3=FLOOR
SET %MAP%7-4=CARPETLEFT
SET %MAP%7-5=CARPETRIGHT
SET %MAP%7-6=FLOOR
SET %MAP%7-7=WALL2
SET %MAP%7-8=WALL2
GOTO :EOF
