SET MAP=MINE1
SET %MAP%MUSICFOLDER=CAVE
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 16
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 18 (
	GOTO :ENEMYLOOP
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 7
GOTO :EOF

:EXITS
SET /a COUNT = 0
:EXIT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 0 
SET /a %MAP%EXIT%COUNT%YCOORD = 2
SET %MAP%EXIT%COUNT%NEWMAP=town3
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 5
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 7

SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a %MAP%BUILDINGTOT = 0
GOTO :EOF

:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 11
SET /a %MAP%CHEST%COUNT%YCOORD = 2
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %ITEMTRANSSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 2
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %MINILIXID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST3
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 4
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %WEAKPOWID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 5
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST4
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 3
SET /a %MAP%CHEST%COUNT%YCOORD = 6
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %AREGENSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
:SPECIALLOCATION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 7
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 4
SET %MAP%SPECIALLOCATION%COUNT%FILE=entercart
SET %MAP%SPECIALLOCATION%COUNT%PATH=MINERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=%MINECARTA%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=%MINECARTB%
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC=%MINECARTC%
CALL :SPECIALVARS

:SPECIALLOCATION2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 10
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 2
SET %MAP%SPECIALLOCATION%COUNT%FILE=leeroybattle
SET %MAP%SPECIALLOCATION%COUNT%PATH=MINERESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 0

SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:SPECIALVARS
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-A=!%MAP%SPECIALLOCATION%COUNT%DISPLAYA!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-B=!%MAP%SPECIALLOCATION%COUNT%DISPLAYB!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-C=!%MAP%SPECIALLOCATION%COUNT%DISPLAYC!
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=WALL1
SET %MAP%1-2=WALL1
SET %MAP%1-3=WALL1
SET %MAP%1-4=WALL1
SET %MAP%1-5=WALL1
SET %MAP%1-6=WALL1
SET %MAP%1-7=WALL1
SET %MAP%1-8=WALL1
SET %MAP%1-9=WALL1
SET %MAP%1-10=WALL1
SET %MAP%1-11=WALL1
SET %MAP%1-11=WALL1
SET %MAP%1-12=WALL1
SET %MAP%2-1=EXITLEFT
SET %MAP%2-2=MINE1
SET %MAP%2-3=MINE1
SET %MAP%2-4=MINE1
SET %MAP%2-5=MINE1
SET %MAP%2-6=MINE1
SET %MAP%2-7=MINE1
SET %MAP%2-8=MINE1
SET %MAP%2-9=MINE1
SET %MAP%2-10=MINE1
SET %MAP%2-11=MINE1
SET %MAP%2-12=WALL1
SET %MAP%3-1=WALL1
SET %MAP%3-2=MINE1
SET %MAP%3-3=MINE1
SET %MAP%3-4=MINE1
SET %MAP%3-5=MINE1
SET %MAP%3-6=WALL1
SET %MAP%3-7=WALL1
SET %MAP%3-8=WALL1
SET %MAP%3-9=WALL1
SET %MAP%3-10=WALL1
SET %MAP%3-11=WALL1
SET %MAP%3-12=WALL1
SET %MAP%4-1=WALL1
SET %MAP%4-2=MINE1
SET %MAP%4-3=MINE1
SET %MAP%4-4=MINE1
SET %MAP%4-5=MINE1
SET %MAP%4-6=WALL1
SET %MAP%4-7=TRACKLEFTRIGHT
SET %MAP%4-8=TRACKLEFTRIGHT
SET %MAP%4-9=TRACKLEFTRIGHT
SET %MAP%4-10=TRACKBOTRIGHT
SET %MAP%4-11=WALL1
SET %MAP%4-12=WALL1
SET %MAP%5-1=WALL1
SET %MAP%5-2=MINE1
SET %MAP%5-3=MINE1
SET %MAP%5-4=MINE1
SET %MAP%5-5=MINE1
SET %MAP%5-6=MINE1
SET %MAP%5-7=MINE1
SET %MAP%5-8=WALL1
SET %MAP%5-9=WALL1
SET %MAP%5-10=TRACKUPDOWN
SET %MAP%5-11=WALL1
SET %MAP%5-12=WALL1
SET %MAP%6-1=WALL1
SET %MAP%6-2=WALL1
SET %MAP%6-3=MINE1
SET %MAP%6-4=WALL1
SET %MAP%6-5=WALL1
SET %MAP%6-6=WALL1
SET %MAP%6-7=WALL1
SET %MAP%6-8=WALL1
SET %MAP%6-9=WALL1
SET %MAP%6-10=TRACKTOPLEFT
SET %MAP%6-11=TRACKLEFTRIGHT
SET %MAP%6-12=TRACKLEFTRIGHT
SET %MAP%7-1=WALL1
SET %MAP%7-2=WALL1
SET %MAP%7-3=WALL1
SET %MAP%7-4=WALL1
SET %MAP%7-5=WALL1
SET %MAP%7-6=WALL1
SET %MAP%7-7=WALL1
SET %MAP%7-8=WALL1
SET %MAP%7-9=WALL1
SET %MAP%7-10=WALL1
SET %MAP%7-11=WALL1
SET %MAP%7-12=WALL1
GOTO :EOF

REM MAPDISPLAYVARTP=    ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
REM MAPDISPLAYVAR7A=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1TOP%ªªªªªªªªªª±±±±±%BOSSTOP%
REM MAPDISPLAYVAR7B=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHEST1MID%ªªªªªªªªªª±±±±±%BOSSMID%
REM MAPDISPLAYVAR7C=    ºªªªªªªªªªªªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªª±±±±±%BOSSBOT%
REM MAPDISPLAYVAR6A=    ºªªªªªªªªªª%CHEST2TOP%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6B=    ºªªªªªªªªªª%CHEST2MID%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR6C=    ºªªªªªªªªªª%CHESTBOTT%ªªªªª±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±ªªªªªº
REM MAPDISPLAYVAR5A=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5B=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR5C=    ºªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4A=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4B=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR4C=    ºªªªªªªªªªª±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR3C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±±±±±±±±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2A=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2B=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR2C=    º±±±±±±±±±±±±±±±ªªªªªªªªªª±±±±± ÃÄ´ ±±±±±±±±±±±±±±±ªªªªªº
REM MAPDISPLAYVAR1A=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3TOP%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1B=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHEST3MID%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVAR1C=     ±±±±±±±±±±±±±±±ªªªªªªªªªªªªªªªªªªªª%CHESTBOTT%ªªªªªªªªªªªªªªªº
REM MAPDISPLAYVARBM=    ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼