SET MAP=MINE1
CALL :POSITIONS
CALL :NEWMAP
CALL :UNDERCART
GOTO :EOF

:POSITIONS
SET /a COUNT = 0
:POSITION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 9
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION4
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION5
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION6
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION7
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 11
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION8
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 12
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0

SET /a %MAP%MOVENUM = %COUNT%

GOTO :EOF

:NEWMAP
SET %MAP%NEWMAP0=MINE2
SET /a %MAP%NEWMAPXCOORD0 = 1
SET /a %MAP%NEWMAPYCOORD0 = 7
SET %MAP%NEWMAP1=MINE1
SET /a %MAP%NEWMAPXCOORD1 = 7
SET /a %MAP%NEWMAPYCOORD1 = 5
GOTO :EOF

:UNDERCART
SET /a %MAP%MINECARTXCOORD = 7
SET /a %MAP%MINECARTYCOORD = 4
SET %MAP%UNDERCART=TRACKLEFTRIGHT
GOTO :EOF