SET MAP=MINE2
CALL :POSITIONS
CALL :NEWMAP
CALL :UNDERCART
GOTO :EOF

:POSITIONS
SET /a COUNT = 0
:POSITION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 1
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION4
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION5
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 8
:POSITION6
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION7
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION8
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION9
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 9
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION10
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 9
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION11
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 9
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION12
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION13
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION14
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION15
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 5
:POSITION16
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION17
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION18
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION19
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION20
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 4
:POSITION31
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION32
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION33
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION34
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION35
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION36
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 6
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION37
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 7
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION38
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION39
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION40
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 1
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 8
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION41
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 1
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 9
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION42
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 1
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 6
:POSITION43
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 2
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION44
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 10
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION45
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 3
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 11
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION46
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 4
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 11
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION47
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 11
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0
:POSITION48
SET /a COUNT = %COUNT% + 1
SET /a %MAP%CARTPOSITION%COUNT%YCOORD = 5
SET /a %MAP%CARTPOSITION%COUNT%XCOORD = 12
SET /a %MAP%CARTPOSITION%COUNT%CHEST = 0

SET /a %MAP%MOVENUM = %COUNT%
GOTO :EOF

:NEWMAP
SET %MAP%NEWMAP0=MINE3
SET /a %MAP%NEWMAPXCOORD0 = 1
SET /a %MAP%NEWMAPYCOORD0 = 5
SET %MAP%NEWMAP1=MINE1
SET /a %MAP%NEWMAPXCOORD1 = 12
SET /a %MAP%NEWMAPYCOORD1 = 6
GOTO :EOF

:UNDERCART
SET /a %MAP%MINECARTXCOORD = 0
SET /a %MAP%MINECARTYCOORD = 0
SET %MAP%UNDERCART=TRACKLEFTRIGHT
GOTO :EOF