SET MAP=TOWN1
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 0
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF


:EDGES
SET /a %MAP%XLIMIT = 9
SET /a %MAP%YLIMIT = 7
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:HOME
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterhome
SET %MAP%BUILDING%COUNT%PATH=HOMETOWNRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=2-1
SET %MAP%BUILDING%COUNT%CELL2=2-2
SET %MAP%BUILDING%COUNT%CELL3=1-1
SET %MAP%BUILDING%COUNT%CELL4=1-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ You
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=r   บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ Hou
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=se  บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:UNCLESHOUSE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enteruncleshouse
SET %MAP%BUILDING%COUNT%PATH=HOMETOWNRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=7-1
SET %MAP%BUILDING%COUNT%CELL2=7-2
SET %MAP%BUILDING%COUNT%CELL3=6-1
SET %MAP%BUILDING%COUNT%CELL4=6-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บUncl
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=e's บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ Hou
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=se  บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:FRIENDSHOUSE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterfriendshouse
SET %MAP%BUILDING%COUNT%PATH=HOMETOWNRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 6
SET %MAP%BUILDING%COUNT%CELL1=7-4
SET %MAP%BUILDING%COUNT%CELL2=7-5
SET %MAP%BUILDING%COUNT%CELL3=7-6
SET %MAP%BUILDING%COUNT%CELL4=6-4
SET %MAP%BUILDING%COUNT%CELL5=6-5
SET %MAP%BUILDING%COUNT%CELL6=6-6
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=%FRIENDHOUSEVAR1%
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=อออออ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=%FRIENDHOUSEVAR2%
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=%FRIENDHOUSEVAR3%
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=House
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=อออออ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=ออออผ
CALL :BUILDINGVARS
CALL :BUILDINGVARS

:GIRLSHOUSE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entergirlshouse
SET %MAP%BUILDING%COUNT%PATH=HOMETOWNRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 6
SET %MAP%BUILDING%COUNT%CELL1=2-4
SET %MAP%BUILDING%COUNT%CELL2=2-5
SET %MAP%BUILDING%COUNT%CELL3=2-6
SET %MAP%BUILDING%COUNT%CELL4=1-4
SET %MAP%BUILDING%COUNT%CELL5=1-5
SET %MAP%BUILDING%COUNT%CELL6=1-6
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=%GIRLHOUSEVAR1%
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=อออออ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=%GIRLHOUSEVAR2%
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=%GIRLHOUSEVAR3%
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=House
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=อออออ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=ออออผ
CALL :BUILDINGVARS

:TELEPORTPAD
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=2-8
SET %MAP%BUILDING%COUNT%CELL2=2-9
SET %MAP%BUILDING%COUNT%CELL3=1-8
SET %MAP%BUILDING%COUNT%CELL4=1-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บTele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=portบ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:OLDMILL
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enteroldmill
SET %MAP%BUILDING%COUNT%PATH=HOMETOWNRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=6-8
SET %MAP%BUILDING%COUNT%CELL2=6-9
SET %MAP%BUILDING%COUNT%CELL3=5-8
SET %MAP%BUILDING%COUNT%CELL4=5-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บThe 
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=Old บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ  Mi
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=ll  บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 9
SET /a %MAP%CHEST%COUNT%YCOORD = 7
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %POTID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 2
SET /a %MAP%CHEST%COUNT%WEAPON1 = %CBONEID%
SET /a %MAP%CHEST%COUNT%WEAPON1NUM = 1
SET /a %MAP%CHEST%COUNT%WEAPON2 = %KTAPEID%
SET /a %MAP%CHEST%COUNT%WEAPON2NUM = 1
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0
SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:SPECIALVARS
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-A=!%MAP%SPECIALLOCATION%COUNT%DISPLAYA!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-B=!%MAP%SPECIALLOCATION%COUNT%DISPLAYB!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-C=!%MAP%SPECIALLOCATION%COUNT%DISPLAYC!
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=GRASS
SET %MAP%1-2=GRASS
SET %MAP%1-3=GRASS
SET %MAP%1-4=GRASS
SET %MAP%1-5=GRASS
SET %MAP%1-6=GRASS
SET %MAP%1-7=GRASS
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%2-1=GRASS
SET %MAP%2-2=GRASS
SET %MAP%2-3=GRASS
SET %MAP%2-4=GRASS
SET %MAP%2-5=GRASS
SET %MAP%2-6=GRASS
SET %MAP%2-7=GRASS
SET %MAP%2-8=GRASS
SET %MAP%2-9=GRASS
SET %MAP%3-1=GRASS
SET %MAP%3-2=PATH1
SET %MAP%3-3=GRASS
SET %MAP%3-4=GRASS
SET %MAP%3-5=PATH1
SET %MAP%3-6=PATH1
SET %MAP%3-7=PATH1
SET %MAP%3-8=PATH1
SET %MAP%3-9=GRASS
SET %MAP%4-1=GRASS
SET %MAP%4-2=PATH1
SET %MAP%4-3=PATH1
SET %MAP%4-4=PATH1
SET %MAP%4-5=PATH1
SET %MAP%4-6=GRASS
SET %MAP%4-7=GRASS
SET %MAP%4-8=PATH1
SET %MAP%4-9=GRASS
SET %MAP%5-1=GRASS
SET %MAP%5-2=PATH1
SET %MAP%5-3=GRASS
SET %MAP%5-4=GRASS
SET %MAP%5-5=PATH1
SET %MAP%5-6=PATH1
SET %MAP%5-7=PATH1
SET %MAP%5-8=GRASS
SET %MAP%5-9=GRASS
SET %MAP%6-1=GRASS
SET %MAP%6-2=GRASS
SET %MAP%6-3=GRASS
SET %MAP%6-4=GRASS
SET %MAP%6-5=GRASS
SET %MAP%6-6=GRASS
SET %MAP%6-7=GRASS
SET %MAP%6-8=GRASS
SET %MAP%6-9=GRASS
SET %MAP%7-1=GRASS
SET %MAP%7-2=GRASS
SET %MAP%7-3=GRASS
SET %MAP%7-4=GRASS
SET %MAP%7-5=GRASS
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=GRASS
SET %MAP%7-9=GRASS
GOTO :EOF
