SET MAP=TOWN3
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 12
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 16 (
	GOTO :ENEMYLOOP
)
SET /a ENEMYID = %BOSSIDSTART% + 12
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
GOTO :EOF


:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 9
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:CAVE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entercave2
SET %MAP%BUILDING%COUNT%PATH=CAVERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 2
SET %MAP%BUILDING%COUNT%CELL1=1-1
SET %MAP%BUILDING%COUNT%CELL2=1-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ  Ca
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=ve  บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ออออผ
CALL :BUILDINGVARS

:CASTLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entercastle
SET %MAP%BUILDING%COUNT%PATH=CASTLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 9
SET %MAP%BUILDING%COUNT%CELL1=3-10
SET %MAP%BUILDING%COUNT%CELL2=3-11
SET %MAP%BUILDING%COUNT%CELL3=3-12
SET %MAP%BUILDING%COUNT%CELL4=2-10
SET %MAP%BUILDING%COUNT%CELL5=2-11
SET %MAP%BUILDING%COUNT%CELL6=2-12
SET %MAP%BUILDING%COUNT%CELL7=1-10
SET %MAP%BUILDING%COUNT%CELL8=1-11
SET %MAP%BUILDING%COUNT%CELL9=1-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออป 
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=ศปษผ 
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC= บศออ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ษออป 
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=ศปษผ 
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=อผศออ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ษออป 
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=ศปษผ 
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=อผบ  
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA= บ   
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB= บ   
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC= บ  C
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=astle
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=  บ  
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=  บ  
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=  บ  
SET %MAP%BUILDING%COUNT%CELL7DISPLAYA= บ   
SET %MAP%BUILDING%COUNT%CELL7DISPLAYB= บ   
SET %MAP%BUILDING%COUNT%CELL7DISPLAYC= ศอออ
SET %MAP%BUILDING%COUNT%CELL8DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL8DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL8DISPLAYC=อออออ
SET %MAP%BUILDING%COUNT%CELL9DISPLAYA=  บ  
SET %MAP%BUILDING%COUNT%CELL9DISPLAYB=  บ  
SET %MAP%BUILDING%COUNT%CELL9DISPLAYC=ออผ  
CALL :BUILDINGVARS

:SHOP
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entershop
SET %MAP%BUILDING%COUNT%PATH=SHOPRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=5-2
SET %MAP%BUILDING%COUNT%CELL2=5-3
SET %MAP%BUILDING%COUNT%CELL3=4-2
SET %MAP%BUILDING%COUNT%CELL4=4-3
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ  Sh
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=op  บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:TEMPLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertemple
SET %MAP%BUILDING%COUNT%PATH=TEMPLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=7-2
SET %MAP%BUILDING%COUNT%CELL2=7-3
SET %MAP%BUILDING%COUNT%CELL3=6-2
SET %MAP%BUILDING%COUNT%CELL4=6-3
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ Tem
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ple บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:CASINO
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entercasino
SET %MAP%BUILDING%COUNT%PATH=CASINORESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=9-11
SET %MAP%BUILDING%COUNT%CELL2=9-12
SET %MAP%BUILDING%COUNT%CELL3=8-11
SET %MAP%BUILDING%COUNT%CELL4=8-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ Cas
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ino บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:TELEPORT
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=6-8
SET %MAP%BUILDING%COUNT%CELL2=6-9
SET %MAP%BUILDING%COUNT%CELL3=5-8
SET %MAP%BUILDING%COUNT%CELL4=5-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บTele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=portบ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:MINE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entermine
SET %MAP%BUILDING%COUNT%PATH=MINERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=9-5
SET %MAP%BUILDING%COUNT%CELL2=9-6
SET %MAP%BUILDING%COUNT%CELL3=8-5
SET %MAP%BUILDING%COUNT%CELL4=8-6
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ  Mi
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ne  บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS


SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 4
SET /a %MAP%CHEST%COUNT%YCOORD = 9
SET /a %MAP%CHEST%COUNT%ITEMTOT = 2
SET /a %MAP%CHEST%COUNT%ITEM1 = %CBOMBID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%ITEM2 = %SUPPOTID%
SET /a %MAP%CHEST%COUNT%ITEM2NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS
:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 7
SET /a %MAP%CHEST%COUNT%YCOORD = 9
SET /a %MAP%CHEST%COUNT%ITEMTOT = 0
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEM1 = %MAGSTONEID%
SET /a %MAP%CHEST%COUNT%SPECIALITEM1NUM = 2
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF



:SPECIALFIGHTS
SET /a COUNT = 0
:SPECIALFIGHT1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALFIGHT%COUNT%XCOORD = 11
SET /a %MAP%SPECIALFIGHT%COUNT%YCOORD = 7
SET %MAP%SPECIALFIGHT%COUNT%ENEMYNAME=BOUNCER
SET %MAP%SPECIALFIGHT%COUNT%TOP=%BOUNCERTOP%
SET %MAP%SPECIALFIGHT%COUNT%MID=%BOUNCERMID%
SET %MAP%SPECIALFIGHT%COUNT%BOT=%BOUNCERBOT%
CALL :SETID

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=GRASS
SET %MAP%1-2=GRASS
SET %MAP%1-3=PATH1
SET %MAP%1-4=GRASS
SET %MAP%1-5=GRASS
SET %MAP%1-6=GRASS
SET %MAP%1-7=GRASS
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%1-10=GRASS
SET %MAP%1-11=GRASS
SET %MAP%1-12=GRASS
SET %MAP%2-1=GRASS
SET %MAP%2-2=GRASS
SET %MAP%2-3=PATH1
SET %MAP%2-4=GRASS
SET %MAP%2-5=GRASS
SET %MAP%2-6=GRASS
SET %MAP%2-7=GRASS
SET %MAP%2-8=GRASS
SET %MAP%2-9=GRASS
SET %MAP%2-10=GRASS
SET %MAP%2-11=GRASS
SET %MAP%2-12=GRASS
SET %MAP%3-1=GRASS
SET %MAP%3-2=GRASS
SET %MAP%3-3=PATH1
SET %MAP%3-4=GRASS
SET %MAP%3-5=GRASS
SET %MAP%3-6=GRASS
SET %MAP%3-7=GRASS
SET %MAP%3-8=GRASS
SET %MAP%3-9=GRASS
SET %MAP%3-10=GRASS
SET %MAP%3-11=GRASS
SET %MAP%3-12=GRASS
SET %MAP%4-1=GRASS
SET %MAP%4-2=PATH1
SET %MAP%4-3=PATH1
SET %MAP%4-4=GRASS
SET %MAP%4-5=GRASS
SET %MAP%4-6=GRASS
SET %MAP%4-7=GRASS
SET %MAP%4-8=GRASS
SET %MAP%4-9=GRASS
SET %MAP%4-10=GRASS
SET %MAP%4-11=GRASS
SET %MAP%4-12=GRASS
SET %MAP%5-1=GRASS
SET %MAP%5-2=PATH1
SET %MAP%5-3=PATH1
SET %MAP%5-4=PATH1
SET %MAP%5-5=PATH1
SET %MAP%5-6=PATH1
SET %MAP%5-7=PATH1
SET %MAP%5-8=PATH1
SET %MAP%5-9=PATH1
SET %MAP%5-10=PATH1
SET %MAP%5-11=PATH1
SET %MAP%5-12=GRASS
SET %MAP%6-1=GRASS
SET %MAP%6-2=PATH1
SET %MAP%6-3=PATH1
SET %MAP%6-4=PATH1
SET %MAP%6-5=PATH1
SET %MAP%6-6=PATH1
SET %MAP%6-7=PATH1
SET %MAP%6-8=PATH1
SET %MAP%6-9=PATH1
SET %MAP%6-10=WALL1
SET %MAP%6-11=PATH1
SET %MAP%6-12=WALL1
SET %MAP%7-1=GRASS
SET %MAP%7-2=GRASS
SET %MAP%7-3=GRASS
SET %MAP%7-4=GRASS
SET %MAP%7-5=GRASS
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=GRASS
SET %MAP%7-9=GRASS
SET %MAP%7-10=WALL1
SET %MAP%7-11=PATH1
SET %MAP%7-12=WALL1
SET %MAP%8-1=GRASS
SET %MAP%8-2=GRASS
SET %MAP%8-3=GRASS
SET %MAP%8-4=GRASS
SET %MAP%8-5=GRASS
SET %MAP%8-6=GRASS
SET %MAP%8-7=GRASS
SET %MAP%8-8=GRASS
SET %MAP%8-9=GRASS
SET %MAP%8-10=WALL1
SET %MAP%8-11=GRASS
SET %MAP%8-12=GRASS
SET %MAP%9-1=GRASS
SET %MAP%9-2=GRASS
SET %MAP%9-3=GRASS
SET %MAP%9-4=GRASS
SET %MAP%9-5=GRASS
SET %MAP%9-6=GRASS
SET %MAP%9-7=GRASS
SET %MAP%9-8=GRASS
SET %MAP%9-9=GRASS
SET %MAP%9-10=WALL1
SET %MAP%9-11=GRASS
SET %MAP%9-12=GRASS
GOTO :EOF