SET MAP=TOWN6
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 35
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 40 (
	GOTO :ENEMYLOOP
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 8
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:FOREST
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterforest2
SET %MAP%BUILDING%COUNT%PATH=FORESTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 2
SET %MAP%BUILDING%COUNT%CELL1=1-1
SET %MAP%BUILDING%COUNT%CELL2=1-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ For
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=est บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ออออผ
CALL :BUILDINGVARS

:SHOP
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entershop
SET %MAP%BUILDING%COUNT%PATH=SHOPRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=6-3
SET %MAP%BUILDING%COUNT%CELL2=6-4
SET %MAP%BUILDING%COUNT%CELL3=5-3
SET %MAP%BUILDING%COUNT%CELL4=5-4
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ  Sh
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=op  บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:TEMPLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertemple
SET %MAP%BUILDING%COUNT%PATH=TEMPLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-7
SET %MAP%BUILDING%COUNT%CELL2=3-8
SET %MAP%BUILDING%COUNT%CELL3=2-7
SET %MAP%BUILDING%COUNT%CELL4=2-8
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ Tem
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ple บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:TELEPORT
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=2-10
SET %MAP%BUILDING%COUNT%CELL2=2-11
SET %MAP%BUILDING%COUNT%CELL3=1-10
SET %MAP%BUILDING%COUNT%CELL4=1-11
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บTele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=portบ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:GURU
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterguru
SET %MAP%BUILDING%COUNT%PATH=GURURESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=6-11
SET %MAP%BUILDING%COUNT%CELL2=6-12
SET %MAP%BUILDING%COUNT%CELL3=5-11
SET %MAP%BUILDING%COUNT%CELL4=5-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=ษออออ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=บ  Gu
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ออออป
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ru  บ
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=บ    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=ศออออ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    บ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ออออผ
CALL :BUILDINGVARS

:PORTAL
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterportal
SET %MAP%BUILDING%COUNT%PATH=PORTALRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 8
SET %MAP%BUILDING%COUNT%CELL1=8-6
SET %MAP%BUILDING%COUNT%CELL2=8-7
SET %MAP%BUILDING%COUNT%CELL3=8-8
SET %MAP%BUILDING%COUNT%CELL4=8-9
SET %MAP%BUILDING%COUNT%CELL5=7-6
SET %MAP%BUILDING%COUNT%CELL6=7-7
SET %MAP%BUILDING%COUNT%CELL7=7-8
SET %MAP%BUILDING%COUNT%CELL8=7-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=~~~~~
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=~    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=~    
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=~~~~~
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=     
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=~~~~~
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=     
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=~~~~~
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ~
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=    ~
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=~    
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=~    
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=~~~~~
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=~~~~~
SET %MAP%BUILDING%COUNT%CELL7DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL7DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL7DISPLAYC=~~~~~
SET %MAP%BUILDING%COUNT%CELL8DISPLAYA=    ~
SET %MAP%BUILDING%COUNT%CELL8DISPLAYB=    ~
SET %MAP%BUILDING%COUNT%CELL8DISPLAYC=~~~~~
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF



:SPECIALFIGHTS
SET /a COUNT = 0

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=GRASS
SET %MAP%1-2=GRASS
SET %MAP%1-3=GRASS
SET %MAP%1-4=GRASS
SET %MAP%1-5=GRASS
SET %MAP%1-6=GRASS
SET %MAP%1-7=GRASS
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%1-10=GRASS
SET %MAP%1-11=GRASS
SET %MAP%1-12=GRASS
SET %MAP%2-1=GRASS
SET %MAP%2-2=PATH1
SET %MAP%2-3=PATH1
SET %MAP%2-4=GRASS
SET %MAP%2-5=GRASS
SET %MAP%2-6=GRASS
SET %MAP%2-7=GRASS
SET %MAP%2-8=GRASS
SET %MAP%2-9=PATH1
SET %MAP%2-10=GRASS
SET %MAP%2-11=GRASS
SET %MAP%2-12=GRASS
SET %MAP%3-1=GRASS
SET %MAP%3-2=GRASS
SET %MAP%3-3=PATH1
SET %MAP%3-4=PATH1
SET %MAP%3-5=PATH1
SET %MAP%3-6=PATH1
SET %MAP%3-7=GRASS
SET %MAP%3-8=GRASS
SET %MAP%3-9=GRASS
SET %MAP%3-10=PATH1
SET %MAP%3-11=GRASS
SET %MAP%3-12=GRASS
SET %MAP%4-1=GRASS
SET %MAP%4-2=GRASS
SET %MAP%4-3=PATH1
SET %MAP%4-4=GRASS
SET %MAP%4-5=GRASS
SET %MAP%4-6=PATH1
SET %MAP%4-7=GRASS
SET %MAP%4-8=GRASS
SET %MAP%4-9=GRASS
SET %MAP%4-10=PATH1
SET %MAP%4-11=GRASS
SET %MAP%4-12=GRASS
SET %MAP%5-1=GRASS
SET %MAP%5-2=GRASS
SET %MAP%5-3=GRASS
SET %MAP%5-4=GRASS
SET %MAP%5-5=GRASS
SET %MAP%5-6=PATH1
SET %MAP%5-7=PATH1
SET %MAP%5-8=PATH1
SET %MAP%5-9=PATH1
SET %MAP%5-10=PATH1
SET %MAP%5-11=GRASS
SET %MAP%5-12=GRASS
SET %MAP%6-1=GRASS
SET %MAP%6-2=GRASS
SET %MAP%6-3=GRASS
SET %MAP%6-4=GRASS
SET %MAP%6-5=GRASS
SET %MAP%6-6=GRASS
SET %MAP%6-7=PATH1
SET %MAP%6-8=PATH1
SET %MAP%6-9=GRASS
SET %MAP%6-10=GRASS
SET %MAP%6-11=GRASS
SET %MAP%6-12=GRASS
SET %MAP%7-1=GRASS
SET %MAP%7-2=GRASS
SET %MAP%7-3=GRASS
SET %MAP%7-4=GRASS
SET %MAP%7-5=GRASS
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=GRASS
SET %MAP%7-9=GRASS
SET %MAP%7-10=GRASS
SET %MAP%7-11=GRASS
SET %MAP%7-12=GRASS
SET %MAP%8-1=GRASS
SET %MAP%8-2=GRASS
SET %MAP%8-3=GRASS
SET %MAP%8-4=GRASS
SET %MAP%8-5=GRASS
SET %MAP%8-6=GRASS
SET %MAP%8-7=GRASS
SET %MAP%8-8=GRASS
SET %MAP%8-9=GRASS
SET %MAP%8-10=GRASS
SET %MAP%8-11=GRASS
SET %MAP%8-12=GRASS
GOTO :EOF
