SET MAP=TOWN4
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 20
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 24 (
	GOTO :ENEMYLOOP
)
GOTO :EOF

:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 7
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:MINE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entermine2
SET %MAP%BUILDING%COUNT%PATH=MINERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 2
SET %MAP%BUILDING%COUNT%CELL1=2-1
SET %MAP%BUILDING%COUNT%CELL2=2-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫  Mi
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=ne  ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:LAKE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterlake
SET %MAP%BUILDING%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 6
SET %MAP%BUILDING%COUNT%CELL1=2-10
SET %MAP%BUILDING%COUNT%CELL2=2-11
SET %MAP%BUILDING%COUNT%CELL3=2-12
SET %MAP%BUILDING%COUNT%CELL4=1-10
SET %MAP%BUILDING%COUNT%CELL5=1-11
SET %MAP%BUILDING%COUNT%CELL6=1-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫    
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=Lake 
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=ÕÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:SHOP
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entershop
SET %MAP%BUILDING%COUNT%PATH=SHOPRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=2-6
SET %MAP%BUILDING%COUNT%CELL2=2-7
SET %MAP%BUILDING%COUNT%CELL3=1-6
SET %MAP%BUILDING%COUNT%CELL4=1-7
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫  Sh
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=op  ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TEMPLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertemple
SET %MAP%BUILDING%COUNT%PATH=TEMPLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=6-3
SET %MAP%BUILDING%COUNT%CELL2=6-4
SET %MAP%BUILDING%COUNT%CELL3=5-3
SET %MAP%BUILDING%COUNT%CELL4=5-4
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫ Tem
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ple ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:CASINO
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterblacksmith
SET %MAP%BUILDING%COUNT%PATH=BLACKSMITHRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 6
SET %MAP%BUILDING%COUNT%CELL1=7-6
SET %MAP%BUILDING%COUNT%CELL2=7-7
SET %MAP%BUILDING%COUNT%CELL3=7-8
SET %MAP%BUILDING%COUNT%CELL4=6-6
SET %MAP%BUILDING%COUNT%CELL5=6-7
SET %MAP%BUILDING%COUNT%CELL6=6-8
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫ Bla
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=cksmi
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=th  ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL5DISPLAYA=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYB=     
SET %MAP%BUILDING%COUNT%CELL5DISPLAYC=ÕÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL6DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL6DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL6DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TELEPORT
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=5-11
SET %MAP%BUILDING%COUNT%CELL2=5-12
SET %MAP%BUILDING%COUNT%CELL3=4-11
SET %MAP%BUILDING%COUNT%CELL4=4-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Tele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=port∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:FOREST
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterforest
SET %MAP%BUILDING%COUNT%PATH=FORESTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 2
SET %MAP%BUILDING%COUNT%CELL1=7-11
SET %MAP%BUILDING%COUNT%CELL2=7-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫ For
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=est ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS


SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF



:SPECIALFIGHTS
SET /a COUNT = 0

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=GRASS
SET %MAP%1-2=GRASS
SET %MAP%1-3=GRASS
SET %MAP%1-4=GRASS
SET %MAP%1-5=GRASS
SET %MAP%1-6=GRASS
SET %MAP%1-7=GRASS
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%1-10=GRASS
SET %MAP%1-11=GRASS
SET %MAP%1-12=GRASS
SET %MAP%2-1=GRASS
SET %MAP%2-2=GRASS
SET %MAP%2-3=PATH1
SET %MAP%2-4=GRASS
SET %MAP%2-5=GRASS
SET %MAP%2-6=GRASS
SET %MAP%2-7=GRASS
SET %MAP%2-8=GRASS
SET %MAP%2-9=PATH1
SET %MAP%2-10=GRASS
SET %MAP%2-11=GRASS
SET %MAP%2-12=GRASS
SET %MAP%3-1=GRASS
SET %MAP%3-2=GRASS
SET %MAP%3-3=PATH1
SET %MAP%3-4=PATH1
SET %MAP%3-5=PATH1
SET %MAP%3-6=PATH1
SET %MAP%3-7=GRASS
SET %MAP%3-8=GRASS
SET %MAP%3-9=PATH1
SET %MAP%3-10=GRASS
SET %MAP%3-11=GRASS
SET %MAP%3-12=GRASS
SET %MAP%4-1=GRASS
SET %MAP%4-2=GRASS
SET %MAP%4-3=GRASS
SET %MAP%4-4=PATH1
SET %MAP%4-5=GRASS
SET %MAP%4-6=PATH1
SET %MAP%4-7=PATH1
SET %MAP%4-8=PATH1
SET %MAP%4-9=PATH1
SET %MAP%4-10=PATH1
SET %MAP%4-11=GRASS
SET %MAP%4-12=GRASS
SET %MAP%5-1=GRASS
SET %MAP%5-2=GRASS
SET %MAP%5-3=GRASS
SET %MAP%5-4=GRASS
SET %MAP%5-5=GRASS
SET %MAP%5-6=PATH1
SET %MAP%5-7=GRASS
SET %MAP%5-8=GRASS
SET %MAP%5-9=PATH1
SET %MAP%5-10=GRASS
SET %MAP%5-11=GRASS
SET %MAP%5-12=GRASS
SET %MAP%6-1=GRASS
SET %MAP%6-2=GRASS
SET %MAP%6-3=GRASS
SET %MAP%6-4=GRASS
SET %MAP%6-5=GRASS
SET %MAP%6-6=GRASS
SET %MAP%6-7=GRASS
SET %MAP%6-8=GRASS
SET %MAP%6-9=PATH1
SET %MAP%6-10=GRASS
SET %MAP%6-11=GRASS
SET %MAP%6-12=GRASS
SET %MAP%7-1=GRASS
SET %MAP%7-2=GRASS
SET %MAP%7-3=GRASS
SET %MAP%7-4=GRASS
SET %MAP%7-5=GRASS
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=GRASS
SET %MAP%7-9=PATH1
SET %MAP%7-10=PATH1
SET %MAP%7-11=GRASS
SET %MAP%7-12=GRASS
GOTO :EOF


REM MAPDISPLAYVARTP=    …ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕª
REM MAPDISPLAYVAR9A=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±∫
REM MAPDISPLAYVAR9B=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR9C=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫Tutorial∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8A=    ∫±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8C=    ∫±±±±±∫  Shop  ∫±±±±±±±±±±±±±±±±±±±±±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±∫
REM MAPDISPLAYVAR7A=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7C=    ∫±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6A=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6B=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6C=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR5A=    ∫±±±±±±±±±±                                        …ÕÕÕÕÕÕÕÕª∫
REM MAPDISPLAYVAR5B=    ∫±±±±±±±±±±                                        ∫  Cave  ∫∫
REM MAPDISPLAYVAR5C=    ∫±±±±±±±±±±                                        »ÕÕÕÕÕÕÕÕº∫
REM MAPDISPLAYVAR4A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫ Temple ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2A=    ∫…ÕÕÕÕÕÕÕÕª                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2B=    ∫∫        ∫                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2C=    ∫∫Training∫                         »ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1A=    ∫∫  Area  ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1B=    ∫∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1C=    ∫»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVARBM=    »ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº
