SET MAP=TOWN5
SET %MAP%MUSICFOLDER=WATER
SET /a %MAP%UNDERWATER = 1
SET /a %MAP%RANBATTLECHANCE = 0
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF


:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 8
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a COUNT = %COUNT% + 1
SET /a %MAP%EXIT%COUNT%XCOORD = 0 
SET /a %MAP%EXIT%COUNT%YCOORD = 4
SET %MAP%EXIT%COUNT%NEWMAP=lake3
SET /a %MAP%EXIT%COUNT%NEWXCOORD = 11
SET /a %MAP%EXIT%COUNT%NEWYCOORD = 7
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:TELEPORTPAD
SET /a COUNT = %COUNT% + 1
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-2
SET %MAP%BUILDING%COUNT%CELL2=3-3
SET %MAP%BUILDING%COUNT%CELL3=2-2
SET %MAP%BUILDING%COUNT%CELL4=2-3
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Tele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=port∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TEMPLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertemple
SET %MAP%BUILDING%COUNT%PATH=TEMPLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-4
SET %MAP%BUILDING%COUNT%CELL2=3-5
SET %MAP%BUILDING%COUNT%CELL3=2-4
SET %MAP%BUILDING%COUNT%CELL4=2-5
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫ Tem
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ple ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS


:ALCHEMIST
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enteralchemist
SET %MAP%BUILDING%COUNT%PATH=ALCHEMISTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-6
SET %MAP%BUILDING%COUNT%CELL2=3-7
SET %MAP%BUILDING%COUNT%CELL3=2-6
SET %MAP%BUILDING%COUNT%CELL4=2-7
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Alch
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=emy ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:SHOP
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entershop
SET %MAP%BUILDING%COUNT%PATH=SHOPRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-8
SET %MAP%BUILDING%COUNT%CELL2=3-9
SET %MAP%BUILDING%COUNT%CELL3=2-8
SET %MAP%BUILDING%COUNT%CELL4=2-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫  Sh
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=op  ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:PALACE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterpalace
SET %MAP%BUILDING%COUNT%PATH=LAKERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-10
SET %MAP%BUILDING%COUNT%CELL2=3-11
SET %MAP%BUILDING%COUNT%CELL3=2-10
SET %MAP%BUILDING%COUNT%CELL4=2-11
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫ Pal
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ace ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF



:SPECIALFIGHTS
SET /a COUNT = 0

SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SETID
SET TEMP=!%MAP%SPECIALFIGHT%COUNT%ENEMYNAME!
SET /a %MAP%SPECIALFIGHT%COUNT%ENEMYID = !%TEMP%ID!
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=WALL1
SET %MAP%1-2=WALL1
SET %MAP%1-3=WALL1
SET %MAP%1-4=WALL1
SET %MAP%1-5=WALL1
SET %MAP%1-6=WALL1
SET %MAP%1-7=WALL1
SET %MAP%1-8=WALL1
SET %MAP%1-9=WALL1
SET %MAP%1-10=WALL1
SET %MAP%1-11=WALL1
SET %MAP%1-12=WALL1
SET %MAP%2-1=WALL1
SET %MAP%2-2=WATER
SET %MAP%2-3=WATER
SET %MAP%2-4=WATER
SET %MAP%2-5=WATER
SET %MAP%2-6=WATER
SET %MAP%2-7=WATER
SET %MAP%2-8=WATER
SET %MAP%2-9=WATER
SET %MAP%2-10=WATER
SET %MAP%2-11=WATER
SET %MAP%2-12=WALL1
SET %MAP%3-1=WALL1
SET %MAP%3-2=WATER
SET %MAP%3-3=WATER
SET %MAP%3-4=WATER
SET %MAP%3-5=WATER
SET %MAP%3-6=WATER
SET %MAP%3-7=WATER
SET %MAP%3-8=WATER
SET %MAP%3-9=WATER
SET %MAP%3-10=WATER
SET %MAP%3-11=WATER
SET %MAP%3-12=WALL1
SET %MAP%4-1=EXITLEFT
SET %MAP%4-2=WATER
SET %MAP%4-3=WATER
SET %MAP%4-4=WATER
SET %MAP%4-5=WATER
SET %MAP%4-6=WATER
SET %MAP%4-7=WATER
SET %MAP%4-8=WATER
SET %MAP%4-9=WATER
SET %MAP%4-10=WATER
SET %MAP%4-11=WATER
SET %MAP%4-12=WALL1
SET %MAP%5-1=WALL1
SET %MAP%5-2=WATER
SET %MAP%5-3=WATER
SET %MAP%5-4=WATER
SET %MAP%5-5=WATER
SET %MAP%5-6=WATER
SET %MAP%5-7=WATER
SET %MAP%5-8=WATER
SET %MAP%5-9=WATER
SET %MAP%5-10=WATER
SET %MAP%5-11=WATER
SET %MAP%5-12=WALL1
SET %MAP%6-1=WALL1
SET %MAP%6-2=WATER
SET %MAP%6-3=WATER
SET %MAP%6-4=WATER
SET %MAP%6-5=WATER
SET %MAP%6-6=WATER
SET %MAP%6-7=WATER
SET %MAP%6-8=WATER
SET %MAP%6-9=WATER
SET %MAP%6-10=WATER
SET %MAP%6-11=WATER
SET %MAP%6-12=WALL1
SET %MAP%7-1=WALL1
SET %MAP%7-2=WATEREDGE
SET %MAP%7-3=WATEREDGE
SET %MAP%7-4=WATEREDGE
SET %MAP%7-5=WATEREDGE
SET %MAP%7-6=WATEREDGE
SET %MAP%7-7=WATEREDGE
SET %MAP%7-8=WATEREDGE
SET %MAP%7-9=WATEREDGE
SET %MAP%7-10=WATEREDGE
SET %MAP%7-11=WATEREDGE
SET %MAP%7-12=WALL1
SET %MAP%8-1=WALL1
SET %MAP%8-2=WALL1
SET %MAP%8-3=WALL1
SET %MAP%8-4=WALL1
SET %MAP%8-5=WALL1
SET %MAP%8-6=WALL1
SET %MAP%8-7=WALL1
SET %MAP%8-8=WALL1
SET %MAP%8-9=WALL1
SET %MAP%8-10=WALL1
SET %MAP%8-11=WALL1
SET %MAP%8-12=WALL1
GOTO :EOF


REM MAPDISPLAYVARTP=    …ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕª
REM MAPDISPLAYVAR9A=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±∫
REM MAPDISPLAYVAR9B=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR9C=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫Tutorial∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8A=    ∫±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8C=    ∫±±±±±∫  Shop  ∫±±±±±±±±±±±±±±±±±±±±±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±∫
REM MAPDISPLAYVAR7A=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7C=    ∫±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6A=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6B=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6C=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR5A=    ∫±±±±±±±±±±                                        …ÕÕÕÕÕÕÕÕª∫
REM MAPDISPLAYVAR5B=    ∫±±±±±±±±±±                                        ∫  Cave  ∫∫
REM MAPDISPLAYVAR5C=    ∫±±±±±±±±±±                                        »ÕÕÕÕÕÕÕÕº∫
REM MAPDISPLAYVAR4A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫ Temple ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2A=    ∫…ÕÕÕÕÕÕÕÕª                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2B=    ∫∫        ∫                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2C=    ∫∫Training∫                         »ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1A=    ∫∫  Area  ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1B=    ∫∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1C=    ∫»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVARBM=    »ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº
