SET MAP=TOWN2
SET %MAP%MUSICFOLDER=WORLDMAP
SET /a %MAP%UNDERWATER = 0
SET /a %MAP%RANBATTLECHANCE = 15
CALL :LOADENEMIES
CALL :EDGES
CALL :DEFINECELLS
CALL "%INITIALRESOURCEPATH%\genericmapsetup1.bat"
CALL :EXITS
CALL :BUILDINGS
CALL :CHESTS
CALL :SPECIALFIGHTS
CALL :SPECIALLOCATIONS
CALL "%INITIALRESOURCEPATH%\genericmapsetup2.bat"
GOTO :EOF

:LOADENEMIES
SET /a ENEMYID = 0
:ENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
IF %ENEMYID% LSS 5 (
	GOTO :ENEMYLOOP
)
SET /a ENEMYID = %TRAMPID%
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
GOTO :EOF


:EDGES
SET /a %MAP%XLIMIT = 12
SET /a %MAP%YLIMIT = 9
GOTO :EOF

:EXITS
SET /a COUNT = 0
SET /a %MAP%EXITNUM = %COUNT%
GOTO :EOF

:BUILDINGS
SET /a COUNT = 0
:TUTORIAL
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertutorial
SET %MAP%BUILDING%COUNT%PATH=TUTORIALRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=2-1
SET %MAP%BUILDING%COUNT%CELL2=2-2
SET %MAP%BUILDING%COUNT%CELL3=1-1
SET %MAP%BUILDING%COUNT%CELL4=1-2
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Tuto
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=rial∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:SHOP
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entershop
SET %MAP%BUILDING%COUNT%PATH=SHOPRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=8-2
SET %MAP%BUILDING%COUNT%CELL2=8-3
SET %MAP%BUILDING%COUNT%CELL3=7-2
SET %MAP%BUILDING%COUNT%CELL4=7-3
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫  Sh
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=op  ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TEMPLE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=entertemple
SET %MAP%BUILDING%COUNT%PATH=TEMPLERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=3-8
SET %MAP%BUILDING%COUNT%CELL2=3-9
SET %MAP%BUILDING%COUNT%CELL3=2-8
SET %MAP%BUILDING%COUNT%CELL4=2-9
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫ Tem
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ple ∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TRAINING
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=initiatetraining
SET %MAP%BUILDING%COUNT%PATH=TRAININGRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=9-9
SET %MAP%BUILDING%COUNT%CELL2=9-10
SET %MAP%BUILDING%COUNT%CELL3=8-9
SET %MAP%BUILDING%COUNT%CELL4=8-10
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Trai
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ning∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫  Ar
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=ea  ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:CAVE
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=cavedoor
SET %MAP%BUILDING%COUNT%PATH=CAVERESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 2
SET %MAP%BUILDING%COUNT%CELL1=5-11
SET %MAP%BUILDING%COUNT%CELL2=5-12
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫  Ca
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=ve  ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

:TELEPORT
SET /a COUNT = %COUNT% + 1
SET %MAP%BUILDING%COUNT%FILE=enterteleport
SET %MAP%BUILDING%COUNT%PATH=TELEPORTRESOURCEPATH
SET /a %MAP%BUILDING%COUNT%CELLNUM = 4
SET %MAP%BUILDING%COUNT%CELL1=9-5
SET %MAP%BUILDING%COUNT%CELL2=9-6
SET %MAP%BUILDING%COUNT%CELL3=8-5
SET %MAP%BUILDING%COUNT%CELL4=8-6
SET %MAP%BUILDING%COUNT%CELL1DISPLAYA=…ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL1DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL1DISPLAYC=∫Tele
SET %MAP%BUILDING%COUNT%CELL2DISPLAYA=ÕÕÕÕª
SET %MAP%BUILDING%COUNT%CELL2DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL2DISPLAYC=port∫
SET %MAP%BUILDING%COUNT%CELL3DISPLAYA=∫  Pa
SET %MAP%BUILDING%COUNT%CELL3DISPLAYB=∫    
SET %MAP%BUILDING%COUNT%CELL3DISPLAYC=»ÕÕÕÕ
SET %MAP%BUILDING%COUNT%CELL4DISPLAYA=d   ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYB=    ∫
SET %MAP%BUILDING%COUNT%CELL4DISPLAYC=ÕÕÕÕº
CALL :BUILDINGVARS

SET /a %MAP%BUILDINGTOT = %COUNT%
GOTO :EOF

:BUILDINGVARS
SET /a CELLCOUNT = 0
:BUILDINGVARSLOOP
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-A=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYA!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-B=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYB!
SET %MAP%!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!-C=!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%DISPLAYC!
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :BUILDINGVARSLOOP
)
GOTO :EOF


:CHESTS
SET /a COUNT = 0
:CHEST1
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 1
SET /a %MAP%CHEST%COUNT%YCOORD = 4
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %POTID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 2
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

:CHEST2
SET /a COUNT = %COUNT%+1
SET /a %MAP%CHEST%COUNT%XCOORD = 1
SET /a %MAP%CHEST%COUNT%YCOORD = 5
SET /a %MAP%CHEST%COUNT%ITEMTOT = 1
SET /a %MAP%CHEST%COUNT%ITEM1 = %ETHID%
SET /a %MAP%CHEST%COUNT%ITEM1NUM = 1
SET /a %MAP%CHEST%COUNT%SPECIALITEMTOT = 0
SET /a %MAP%CHEST%COUNT%WEAPONTOT = 0
SET /a %MAP%CHEST%COUNT%ARMOURTOT = 0
SET /a %MAP%CHEST%COUNT%ACCESSORYTOT = 0
CALL :CHESTVARS

SET /a %MAP%CHESTTOT = %COUNT%
GOTO :EOF

:CHESTVARS
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-A=%CHESTOTOP%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-B=%CHESTOMID%
SET %MAP%!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!-C=%CHESTBOTT%
GOTO :EOF


:SPECIALFIGHTS
SET /a COUNT = 0
SET /a %MAP%SPECIALFIGHTTOT = %COUNT%
GOTO :EOF

:SPECIALLOCATIONS
SET /a COUNT = 0
:SPECIALLOCATION1
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 3
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 9
SET %MAP%SPECIALLOCATION%COUNT%FILE=trampencounter
SET %MAP%SPECIALLOCATION%COUNT%PATH=TRAMPRESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 1
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYA=∞∞∞∞∞
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYB=z    
SET %MAP%SPECIALLOCATION%COUNT%DISPLAYC= ‹Õ 
CALL :SPECIALVARS

:SPECIALLOCATION2
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 6
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 4
SET %MAP%SPECIALLOCATION%COUNT%FILE=menuexamplestart
SET %MAP%SPECIALLOCATION%COUNT%PATH=TUTORIALRESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 0

:SPECIALLOCATION3
SET /a COUNT = %COUNT% + 1
SET /a %MAP%SPECIALLOCATION%COUNT%XCOORD = 5
SET /a %MAP%SPECIALLOCATION%COUNT%YCOORD = 2
SET %MAP%SPECIALLOCATION%COUNT%FILE=menuexamplestart
SET %MAP%SPECIALLOCATION%COUNT%PATH=TUTORIALRESOURCEPATH
SET /a %MAP%SPECIALLOCATION%COUNT%DISPLAY = 0


SET /a %MAP%SPECIALLOCATIONTOT = %COUNT%
GOTO :EOF

:SPECIALVARS
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-A=!%MAP%SPECIALLOCATION%COUNT%DISPLAYA!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-B=!%MAP%SPECIALLOCATION%COUNT%DISPLAYB!
SET %MAP%!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!-C=!%MAP%SPECIALLOCATION%COUNT%DISPLAYC!
GOTO :EOF

:DEFINECELLS
SET %MAP%1-1=GRASS
SET %MAP%1-2=GRASS
SET %MAP%1-3=GRASS
SET %MAP%1-4=GRASS
SET %MAP%1-5=GRASS
SET %MAP%1-6=GRASS
SET %MAP%1-7=GRASS
SET %MAP%1-8=GRASS
SET %MAP%1-9=GRASS
SET %MAP%1-10=GRASS
SET %MAP%1-11=GRASS
SET %MAP%1-12=GRASS
SET %MAP%2-1=GRASS
SET %MAP%2-2=GRASS
SET %MAP%2-3=PATH1
SET %MAP%2-4=PATH1
SET %MAP%2-5=PATH1
SET %MAP%2-6=PATH1
SET %MAP%2-7=PATH1
SET %MAP%2-8=GRASS
SET %MAP%2-9=GRASS
SET %MAP%2-10=GRASS
SET %MAP%2-11=GRASS
SET %MAP%2-12=GRASS
SET %MAP%3-1=GRASS
SET %MAP%3-2=GRASS
SET %MAP%3-3=PATH1
SET %MAP%3-4=GRASS
SET %MAP%3-5=GRASS
SET %MAP%3-6=PATH1
SET %MAP%3-7=GRASS
SET %MAP%3-8=GRASS
SET %MAP%3-9=GRASS
SET %MAP%3-10=GRASS
SET %MAP%3-11=GRASS
SET %MAP%3-12=GRASS
SET %MAP%4-1=GRASS
SET %MAP%4-2=GRASS
SET %MAP%4-3=PATH1
SET %MAP%4-4=GRASS
SET %MAP%4-5=GRASS
SET %MAP%4-6=PATH1
SET %MAP%4-7=GRASS
SET %MAP%4-8=GRASS
SET %MAP%4-9=GRASS
SET %MAP%4-10=GRASS
SET %MAP%4-11=GRASS
SET %MAP%4-12=GRASS
SET %MAP%5-1=GRASS
SET %MAP%5-2=GRASS
SET %MAP%5-3=PATH1
SET %MAP%5-4=PATH1
SET %MAP%5-5=PATH1
SET %MAP%5-6=PATH1
SET %MAP%5-7=PATH1
SET %MAP%5-8=PATH1
SET %MAP%5-9=PATH1
SET %MAP%5-10=PATH1
SET %MAP%5-11=GRASS
SET %MAP%5-12=GRASS
SET %MAP%6-1=GRASS
SET %MAP%6-2=GRASS
SET %MAP%6-3=PATH1
SET %MAP%6-4=GRASS
SET %MAP%6-5=PATH1
SET %MAP%6-6=GRASS
SET %MAP%6-7=GRASS
SET %MAP%6-8=GRASS
SET %MAP%6-9=PATH1
SET %MAP%6-10=GRASS
SET %MAP%6-11=GRASS
SET %MAP%6-12=GRASS
SET %MAP%7-1=GRASS
SET %MAP%7-2=GRASS
SET %MAP%7-3=GRASS
SET %MAP%7-4=GRASS
SET %MAP%7-5=PATH1
SET %MAP%7-6=GRASS
SET %MAP%7-7=GRASS
SET %MAP%7-8=GRASS
SET %MAP%7-9=PATH1
SET %MAP%7-10=GRASS
SET %MAP%7-11=GRASS
SET %MAP%7-12=GRASS
SET %MAP%8-1=GRASS
SET %MAP%8-2=GRASS
SET %MAP%8-3=GRASS
SET %MAP%8-4=GRASS
SET %MAP%8-5=GRASS
SET %MAP%8-6=GRASS
SET %MAP%8-7=GRASS
SET %MAP%8-8=GRASS
SET %MAP%8-9=GRASS
SET %MAP%8-10=GRASS
SET %MAP%8-11=GRASS
SET %MAP%8-12=GRASS
SET %MAP%9-1=GRASS
SET %MAP%9-2=GRASS
SET %MAP%9-3=GRASS
SET %MAP%9-4=GRASS
SET %MAP%9-5=GRASS
SET %MAP%9-6=GRASS
SET %MAP%9-7=GRASS
SET %MAP%9-8=GRASS
SET %MAP%9-9=GRASS
SET %MAP%9-10=GRASS
SET %MAP%9-11=GRASS
SET %MAP%9-12=GRASS
GOTO :EOF


REM MAPDISPLAYVARTP=    …ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕª
REM MAPDISPLAYVAR9A=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±∫
REM MAPDISPLAYVAR9B=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR9C=    ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫Tutorial∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8A=    ∫±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±∫        ∫±±±±±±±±±±∫
REM MAPDISPLAYVAR8C=    ∫±±±±±∫  Shop  ∫±±±±±±±±±±±±±±±±±±±±±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±∫
REM MAPDISPLAYVAR7A=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7B=    ∫±±±±±∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR7C=    ∫±±±±±»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6A=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6B=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR6C=    ∫±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±     ±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR5A=    ∫±±±±±±±±±±                                        …ÕÕÕÕÕÕÕÕª∫
REM MAPDISPLAYVAR5B=    ∫±±±±±±±±±±                                        ∫  Cave  ∫∫
REM MAPDISPLAYVAR5C=    ∫±±±±±±±±±±                                        »ÕÕÕÕÕÕÕÕº∫
REM MAPDISPLAYVAR4A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR4C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3A=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±…ÕÕÕÕÕÕÕÕª±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3B=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR3C=    ∫±±±±±±±±±±     ±±±±±±±±±±     ±±±±±∫ Temple ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2A=    ∫…ÕÕÕÕÕÕÕÕª                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2B=    ∫∫        ∫                         ∫        ∫±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR2C=    ∫∫Training∫                         »ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1A=    ∫∫  Area  ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1B=    ∫∫        ∫±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVAR1C=    ∫»ÕÕÕÕÕÕÕÕº±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±∫
REM MAPDISPLAYVARBM=    »ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº
