SET /a MINNAMELENGTH = 6
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0
SET /a ACCESSORYSTART = %COUNT%
:SPRINTSHOES
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Sprint Shoes
SET ACCESSORY%COUNT%NICKNAME=SPRSHOES
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %AHASTEID%
SET /a ACCESSORY%COUNT%COST = 200
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 1
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 1
SET /a ACCESSORY%COUNT%MAXSKL = 15
SET /a ACCESSORY%COUNT%QUANTDIV = 15
SET /a ACCESSORY%COUNT%EXP = 30
::CALL :ACCESSORYNAMELENGTH

:LUCKYCHARM
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Lucky Charm
SET ACCESSORY%COUNT%NICKNAME=LCKCHARM
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 15
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCCRITCHANCEID%
SET /a ACCESSORY%COUNT%COST = 500
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 1
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 1
SET /a ACCESSORY%COUNT%MAXSKL = 25
SET /a ACCESSORY%COUNT%QUANTDIV = 25
SET /a ACCESSORY%COUNT%EXP = 50
::CALL :ACCESSORYNAMELENGTH

:HORSESHOE
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Horse Shoe
SET ACCESSORY%COUNT%NICKNAME=HSHOE
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 15
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCCRITDAMID%
SET /a ACCESSORY%COUNT%COST = 500
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 1
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 1
SET /a ACCESSORY%COUNT%MAXSKL = 25
SET /a ACCESSORY%COUNT%QUANTDIV = 25
SET /a ACCESSORY%COUNT%EXP = 50
::CALL :ACCESSORYNAMELENGTH

:PROTECTIVEAMULET
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Protective Amulet
SET ACCESSORY%COUNT%NICKNAME=PAMULET
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 30
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %APROTECTID%
SET /a ACCESSORY%COUNT%COST = 750
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 1
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 15
SET /a ACCESSORY%COUNT%MAXSKL = 35
SET /a ACCESSORY%COUNT%QUANTDIV = 35
SET /a ACCESSORY%COUNT%EXP = 75
::CALL :ACCESSORYNAMELENGTH

:SHELLSUIT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Shell Suit
SET ACCESSORY%COUNT%NICKNAME=SHLSUIT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 20
SET /a ACCESSORY%COUNT%MAXMP = 5
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%COST = 750
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %ASHELLID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 1
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 15
SET /a ACCESSORY%COUNT%MAXSKL = 35
SET /a ACCESSORY%COUNT%QUANTDIV = 35
SET /a ACCESSORY%COUNT%EXP = 75
::CALL :ACCESSORYNAMELENGTH

:PACMANTALISMAN
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Pacman Talisman
SET ACCESSORY%COUNT%NICKNAME=PMANTAL
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 30
SET /a ACCESSORY%COUNT%MAXMP = 30
SET /a ACCESSORY%COUNT%LCK = 3
SET /a ACCESSORY%COUNT%COST = 1600
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %PACMANSPECIALID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 1
SET /a ACCESSORY%COUNT%MAXSKL = 1
SET /a ACCESSORY%COUNT%QUANTDIV = 1
SET /a ACCESSORY%COUNT%EXP = 1
::CALL :ACCESSORYNAMELENGTH

:SAFETYBRACELET
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Safety Bracelet
SET ACCESSORY%COUNT%NICKNAME=SAFBRAC
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%COST = 1500
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %NOENCID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 25
SET /a ACCESSORY%COUNT%MAXSKL = 45
SET /a ACCESSORY%COUNT%QUANTDIV = 35
SET /a ACCESSORY%COUNT%EXP = 100
::CALL :ACCESSORYNAMELENGTH

:MIRROR
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Mirror
SET ACCESSORY%COUNT%NICKNAME=MIRROR
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 40
SET /a ACCESSORY%COUNT%LCK = 5
SET /a ACCESSORY%COUNT%COST = 1500
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %AREFLECTID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 25
SET /a ACCESSORY%COUNT%MAXSKL = 45
SET /a ACCESSORY%COUNT%QUANTDIV = 40
SET /a ACCESSORY%COUNT%EXP = 120
::CALL :ACCESSORYNAMELENGTH

:RABBITFOOT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Rabbit's Foot
SET ACCESSORY%COUNT%NICKNAME=RABFOOT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 15
SET /a ACCESSORY%COUNT%COST = 1800
SET /a ACCESSORY%COUNT%SPECIALTOT = 2
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCITEMFINDCHANCEID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %FINDBETTERITEMID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 30
SET /a ACCESSORY%COUNT%MAXSKL = 50
SET /a ACCESSORY%COUNT%QUANTDIV = 40
SET /a ACCESSORY%COUNT%EXP = 130
::CALL :ACCESSORYNAMELENGTH

:FOURLEAFCLOVER
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Four Leaf Clover
SET ACCESSORY%COUNT%NICKNAME=CLOVER
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 15
SET /a ACCESSORY%COUNT%COST = 1800
SET /a ACCESSORY%COUNT%SPECIALTOT = 2
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCEQUIPFINDCHANCEID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %FINDBETTEREQUIPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 30
SET /a ACCESSORY%COUNT%MAXSKL = 50
SET /a ACCESSORY%COUNT%QUANTDIV = 40
SET /a ACCESSORY%COUNT%EXP = 130
::CALL :ACCESSORYNAMELENGTH

:CRYSTALBALL
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Crystal Ball
SET ACCESSORY%COUNT%NICKNAME=CBALL
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 50
SET /a ACCESSORY%COUNT%MAXMP = 30
SET /a ACCESSORY%COUNT%LCK = 5
SET /a ACCESSORY%COUNT%COST = 2000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %ASCANID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 35
SET /a ACCESSORY%COUNT%MAXSKL = 55
SET /a ACCESSORY%COUNT%QUANTDIV = 45
SET /a ACCESSORY%COUNT%EXP = 150
::CALL :ACCESSORYNAMELENGTH

:SEERSSTONE
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Seer's Stone
SET ACCESSORY%COUNT%NICKNAME=SEERSTONE
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 50
SET /a ACCESSORY%COUNT%MAXMP = 30
SET /a ACCESSORY%COUNT%LCK = 5
SET /a ACCESSORY%COUNT%COST = 2000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %ADETECTID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 1
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 35
SET /a ACCESSORY%COUNT%MAXSKL = 55
SET /a ACCESSORY%COUNT%QUANTDIV = 45
SET /a ACCESSORY%COUNT%EXP = 150
::CALL :ACCESSORYNAMELENGTH

:OXYGENTANK
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Oxygen Tank
SET ACCESSORY%COUNT%NICKNAME=OXTANK
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 100
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%COST = 4000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %EXTRAOXYGENID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 50
SET /a ACCESSORY%COUNT%MAXSKL = 75
SET /a ACCESSORY%COUNT%QUANTDIV = 60
SET /a ACCESSORY%COUNT%EXP = 200
::CALL :ACCESSORYNAMELENGTH

:HEAVYWEIGHT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Heavy Weight
SET ACCESSORY%COUNT%NICKNAME=WEIGHT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%COST = 3000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %SLOWCARTID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 50
SET /a ACCESSORY%COUNT%MAXSKL = 75
SET /a ACCESSORY%COUNT%QUANTDIV = 60
SET /a ACCESSORY%COUNT%EXP = 200
::CALL :ACCESSORYNAMELENGTH

:LEEROYTAL
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Leeroy Talisman
SET ACCESSORY%COUNT%NICKNAME=LEEROYTAL
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 50
SET /a ACCESSORY%COUNT%MAXMP = 50
SET /a ACCESSORY%COUNT%LCK = 5
SET /a ACCESSORY%COUNT%COST = 4000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %LEEROYSPECIALID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 1
SET /a ACCESSORY%COUNT%MAXSKL = 1
SET /a ACCESSORY%COUNT%QUANTDIV = 1
SET /a ACCESSORY%COUNT%EXP = 1
::CALL :ACCESSORYNAMELENGTH


:NAMEKBLOOD
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Vial of Namek Blood
SET ACCESSORY%COUNT%NICKNAME=NAMEKBLOOD
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 100
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%COST = 2500
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %AREGENID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 55
SET /a ACCESSORY%COUNT%MAXSKL = 85
SET /a ACCESSORY%COUNT%QUANTDIV = 70
SET /a ACCESSORY%COUNT%EXP = 250
::CALL :ACCESSORYNAMELENGTH

:MIDASAMULET
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=King Midas' Amulet
SET ACCESSORY%COUNT%NICKNAME=MIDASAMULET
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 20
SET /a ACCESSORY%COUNT%COST = 4000
SET /a ACCESSORY%COUNT%SPECIALTOT = 2
SET /a ACCESSORY%COUNT%SPECIAL1 = %STLMOREGILID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %FINDMOREGILID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 65
SET /a ACCESSORY%COUNT%MAXSKL = 105
SET /a ACCESSORY%COUNT%QUANTDIV = 70
SET /a ACCESSORY%COUNT%EXP = 300
::CALL :ACCESSORYNAMELENGTH

:ROBINHOOD
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Robin Hood's...Hood
SET ACCESSORY%COUNT%NICKNAME=ROBINHOOD
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 25
SET /a ACCESSORY%COUNT%COST = 5000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCSTLCHANCEID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 70
SET /a ACCESSORY%COUNT%MAXSKL = 110
SET /a ACCESSORY%COUNT%QUANTDIV = 80
SET /a ACCESSORY%COUNT%EXP = 350
::CALL :ACCESSORYNAMELENGTH

:ROBINHOOD
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Limit Breaker
SET ACCESSORY%COUNT%NICKNAME=LIMITBREAKER
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 100
SET /a ACCESSORY%COUNT%MAXMP = 100
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 5000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %MORELIMITBREAKID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 1
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 70
SET /a ACCESSORY%COUNT%MAXSKL = 120
SET /a ACCESSORY%COUNT%QUANTDIV = 80
SET /a ACCESSORY%COUNT%EXP = 375
::CALL :ACCESSORYNAMELENGTH

:APRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=AP Ring
SET ACCESSORY%COUNT%NICKNAME=APRING
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 150
SET /a ACCESSORY%COUNT%MAXMP = 150
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 5000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %DOUBLEAPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 1
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 80
SET /a ACCESSORY%COUNT%MAXSKL = 120
SET /a ACCESSORY%COUNT%QUANTDIV = 90
SET /a ACCESSORY%COUNT%EXP = 400
::CALL :ACCESSORYNAMELENGTH

:ANOTHERAPRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Another AP Ring
SET ACCESSORY%COUNT%NICKNAME=ANOTHERAPRING
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 200
SET /a ACCESSORY%COUNT%MAXMP = 100
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 5000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %FASTAPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 1
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 80
SET /a ACCESSORY%COUNT%MAXSKL = 120
SET /a ACCESSORY%COUNT%QUANTDIV = 90
SET /a ACCESSORY%COUNT%EXP = 400
::CALL :ACCESSORYNAMELENGTH

:AMULETOFEFFICIENCY
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Amulet of Efficiency
SET ACCESSORY%COUNT%NICKNAME=EFFAMULET
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 250
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 10000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %FULLAPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 1
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 100
SET /a ACCESSORY%COUNT%MAXSKL = 140
SET /a ACCESSORY%COUNT%QUANTDIV = 100
SET /a ACCESSORY%COUNT%EXP = 500
::CALL :ACCESSORYNAMELENGTH

:DEGREE
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Forged Degree
SET ACCESSORY%COUNT%NICKNAME=DEGREE
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 100
SET /a ACCESSORY%COUNT%MAXMP = 80
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 8000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %DOUBLEEXPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 1
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 100
SET /a ACCESSORY%COUNT%MAXSKL = 140
SET /a ACCESSORY%COUNT%QUANTDIV = 120
SET /a ACCESSORY%COUNT%EXP = 550
::CALL :ACCESSORYNAMELENGTH

:ARTFULDODGE
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Artful Dodger's Gloves
SET ACCESSORY%COUNT%NICKNAME=ARTFULDODGE
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 35
SET /a ACCESSORY%COUNT%COST = 9000
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %STLBETTERID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 1
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 120
SET /a ACCESSORY%COUNT%MAXSKL = 160
SET /a ACCESSORY%COUNT%QUANTDIV = 130
SET /a ACCESSORY%COUNT%EXP = 650
::CALL :ACCESSORYNAMELENGTH

:DIFFAPRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Different AP Ring
SET ACCESSORY%COUNT%NICKNAME=DIFFAPRING
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 250
SET /a ACCESSORY%COUNT%MAXMP = 150
SET /a ACCESSORY%COUNT%LCK = 12
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %FULLAPID%
SET /a ACCESSORY%COUNT%COST = 12000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 1
SET /a ACCESSORY%COUNT%MINSKL = 120
SET /a ACCESSORY%COUNT%MAXSKL = 160
SET /a ACCESSORY%COUNT%QUANTDIV = 130
SET /a ACCESSORY%COUNT%EXP = 650
::CALL :ACCESSORYNAMELENGTH

:PHOENIXFEATHER
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Phoenix Feather
SET ACCESSORY%COUNT%NICKNAME=PHOENIXFEATHER
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 500
SET /a ACCESSORY%COUNT%MAXMP = 200
SET /a ACCESSORY%COUNT%LCK = 0
SET /a ACCESSORY%COUNT%SPECIALTOT = 3
SET /a ACCESSORY%COUNT%SPECIAL1 = %HEALHPID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %HEALMPID%
SET /a ACCESSORY%COUNT%SPECIAL3 = %AREGENID%
SET /a ACCESSORY%COUNT%COST = 13000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 1
SET /a ACCESSORY%COUNT%MINSKL = 130
SET /a ACCESSORY%COUNT%MAXSKL = 170
SET /a ACCESSORY%COUNT%QUANTDIV = 150
SET /a ACCESSORY%COUNT%EXP = 750
::CALL :ACCESSORYNAMELENGTH

:SKILLHAT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Skill Hat
SET ACCESSORY%COUNT%NICKNAME=SKILLHAT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 300
SET /a ACCESSORY%COUNT%MAXMP = 50
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %ZEROAPID%
SET /a ACCESSORY%COUNT%COST = 15000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 1
SET /a ACCESSORY%COUNT%MINSKL = 150
SET /a ACCESSORY%COUNT%MAXSKL = 200
SET /a ACCESSORY%COUNT%QUANTDIV = 150
SET /a ACCESSORY%COUNT%EXP = 1200
::CALL :ACCESSORYNAMELENGTH

:EFFPENDANT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Pendant of Efficiency
SET ACCESSORY%COUNT%NICKNAME=EFFPENDANT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 300
SET /a ACCESSORY%COUNT%MAXMP = 150
SET /a ACCESSORY%COUNT%LCK = 5
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %HALFMPID%
SET /a ACCESSORY%COUNT%COST = 18000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 1
SET /a ACCESSORY%COUNT%MINSKL = 170
SET /a ACCESSORY%COUNT%MAXSKL = 220
SET /a ACCESSORY%COUNT%QUANTDIV = 160
SET /a ACCESSORY%COUNT%EXP = 1500
::CALL :ACCESSORYNAMELENGTH

:OVERPOWEREDRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Overpowered Ring
SET ACCESSORY%COUNT%NICKNAME=OVERPOWEREDRING
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 400
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 20
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %ZEROMPID%
SET /a ACCESSORY%COUNT%COST = 20000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 200
SET /a ACCESSORY%COUNT%MAXSKL = 250
SET /a ACCESSORY%COUNT%QUANTDIV = 175
SET /a ACCESSORY%COUNT%EXP = 1800
::CALL :ACCESSORYNAMELENGTH

:GOALIEGLOVES
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Goalie Gloves
SET ACCESSORY%COUNT%NICKNAME=GOALIEGLOVES
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 200
SET /a ACCESSORY%COUNT%MAXMP = 200
SET /a ACCESSORY%COUNT%LCK = 20
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCCATCHID%
SET /a ACCESSORY%COUNT%COST = 40000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 200
SET /a ACCESSORY%COUNT%MAXSKL = 250
SET /a ACCESSORY%COUNT%QUANTDIV = 175
SET /a ACCESSORY%COUNT%EXP = 1800
::CALL :ACCESSORYNAMELENGTH

:LEPPOT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Leprechaun's Pot
SET ACCESSORY%COUNT%NICKNAME=LEPPOT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 0
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 45
SET /a ACCESSORY%COUNT%SPECIALTOT = 1
SET /a ACCESSORY%COUNT%SPECIAL1 = %DOUBLECASINOID%
SET /a ACCESSORY%COUNT%COST = 40000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 200
SET /a ACCESSORY%COUNT%MAXSKL = 250
SET /a ACCESSORY%COUNT%QUANTDIV = 175
SET /a ACCESSORY%COUNT%EXP = 1800
::CALL :ACCESSORYNAMELENGTH

:DESTROYER
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Destroyer
SET ACCESSORY%COUNT%NICKNAME=DESTROYER
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 800
SET /a ACCESSORY%COUNT%MAXMP = 800
SET /a ACCESSORY%COUNT%LCK = 20
SET /a ACCESSORY%COUNT%SPECIALTOT = 3
SET /a ACCESSORY%COUNT%SPECIAL1 = %BREAKDAMID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %DOUBLELIMID%
SET /a ACCESSORY%COUNT%SPECIAL3 = %DOUBLELIMDAMID%
SET /a ACCESSORY%COUNT%COST = 40000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 250
SET /a ACCESSORY%COUNT%MAXSKL = 350
SET /a ACCESSORY%COUNT%QUANTDIV = 200
SET /a ACCESSORY%COUNT%EXP = 2500
::CALL :ACCESSORYNAMELENGTH

:GLRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Green Latern's Ring
SET ACCESSORY%COUNT%NICKNAME=LANTERNRING
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 1000
SET /a ACCESSORY%COUNT%MAXMP = 1000
SET /a ACCESSORY%COUNT%LCK = 40
SET /a ACCESSORY%COUNT%SPECIALTOT = 4
SET /a ACCESSORY%COUNT%SPECIAL1 = %ZEROMPID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %ZEROAPID%
SET /a ACCESSORY%COUNT%SPECIAL3 = %BREAKDAMID%
SET /a ACCESSORY%COUNT%SPECIAL4 = %DOUBLEEXPID%
SET /a ACCESSORY%COUNT%COST = 40000
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 300
SET /a ACCESSORY%COUNT%MAXSKL = 1000
SET /a ACCESSORY%COUNT%QUANTDIV = 250
SET /a ACCESSORY%COUNT%EXP = 3000
::CALL :ACCESSORYNAMELENGTH

:COCKRING
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Bandit's Cock Ring
SET ACCESSORY%COUNT%NICKNAME=BCR
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 200
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 10000
SET /a ACCESSORY%COUNT%SPECIALTOT = 2
SET /a ACCESSORY%COUNT%SPECIAL1 = %AHASTEID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %FULLAPID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 100
SET /a ACCESSORY%COUNT%MAXSKL = 140
SET /a ACCESSORY%COUNT%QUANTDIV = 100
SET /a ACCESSORY%COUNT%EXP = 500
::CALL :ACCESSORYNAMELENGTH

:TOPHAT
SET /a COUNT=%COUNT%+1
SET ACCESSORY%COUNT%NAME=Slash's Top Hat
SET ACCESSORY%COUNT%NICKNAME=TOPHAT
SET /a !ACCESSORY%COUNT%NICKNAME!ID = %COUNT%
SET /a ACCESSORY%COUNT%MAXHP = 200
SET /a ACCESSORY%COUNT%MAXMP = 0
SET /a ACCESSORY%COUNT%LCK = 10
SET /a ACCESSORY%COUNT%COST = 10000
SET /a ACCESSORY%COUNT%SPECIALTOT = 4
SET /a ACCESSORY%COUNT%SPECIAL1 = %INCITEMFINDCHANCEID%
SET /a ACCESSORY%COUNT%SPECIAL2 = %INCEQUIPFINDCHANCEID%
SET /a ACCESSORY%COUNT%SPECIAL3 = %FINDMOREGILID%
SET /a ACCESSORY%COUNT%SPECIAL4 = %INCCATCHID%
SET /a ACCESSORY%COUNT%SELL = !ACCESSORY%COUNT%COST!/4
SET /a ACCESSORY%COUNT%SHOP1 = 0
SET /a ACCESSORY%COUNT%SHOP2 = 0
SET /a ACCESSORY%COUNT%SHOP3 = 0
SET /a ACCESSORY%COUNT%SHOP4 = 0
SET /a ACCESSORY%COUNT%SHOP5 = 0
SET /a ACCESSORY%COUNT%MINSKL = 100
SET /a ACCESSORY%COUNT%MAXSKL = 140
SET /a ACCESSORY%COUNT%QUANTDIV = 100
SET /a ACCESSORY%COUNT%EXP = 500
::CALL :ACCESSORYNAMELENGTH

SET /a ACCESSORYTOTAL = %COUNT%
SET /a ACCESSORYEND = %COUNT%

::CALL :RECORDNAMELENGTHS
CALL :SETNAMELENGTHS

GOTO :EOF


:ACCESSORYNAMELENGTH
SET /a ACCESSORY%COUNT%NAMELENGTH = 0
:ACCESSORYNAMELOOPSTART
SET /a ACCESSORY%COUNT%NAMELENGTH += 1
SET TEMP1=!ACCESSORY%COUNT%NAMELENGTH!
SET SUBSTR=!ACCESSORY%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ACCESSORYNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !ACCESSORY%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!ACCESSORY%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ACCESSORYNAMELOOPSTART
	)
)
GOTO :EOF

:RECORDNAMELENGTHS
::To use this, remove all ::s from the "::::CALL :ACCESSORYNAMELENGTH" lines so that the game can calculate the lengths. Then uncomment "CALL :RECORDACCESSORYNAMELENGTHS"
SET /a COUNT = 0
:RECORDLENGTHSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a ACCESSORY%COUNT%NAMELENGTH = !ACCESSORY%COUNT%NAMELENGTH! >> C:\Game\ACCESSORYnamelengths.txt
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :RECORDLENGTHSLOOP
)
GOTO :EOF

:SETNAMELENGTHS
::This should be copied form the output of :RECORDNAMELENGTHS
SET /a ACCESSORY1NAMELENGTH = 12 
SET /a ACCESSORY2NAMELENGTH = 11 
SET /a ACCESSORY3NAMELENGTH = 10 
SET /a ACCESSORY4NAMELENGTH = 17 
SET /a ACCESSORY5NAMELENGTH = 10 
SET /a ACCESSORY6NAMELENGTH = 15 
SET /a ACCESSORY7NAMELENGTH = 15 
SET /a ACCESSORY8NAMELENGTH = 6 
SET /a ACCESSORY9NAMELENGTH = 13 
SET /a ACCESSORY10NAMELENGTH = 16 
SET /a ACCESSORY11NAMELENGTH = 12 
SET /a ACCESSORY12NAMELENGTH = 12 
SET /a ACCESSORY13NAMELENGTH = 11 
SET /a ACCESSORY14NAMELENGTH = 12 
SET /a ACCESSORY15NAMELENGTH = 15 
SET /a ACCESSORY16NAMELENGTH = 19 
SET /a ACCESSORY17NAMELENGTH = 18 
SET /a ACCESSORY18NAMELENGTH = 19 
SET /a ACCESSORY19NAMELENGTH = 13 
SET /a ACCESSORY20NAMELENGTH = 7 
SET /a ACCESSORY21NAMELENGTH = 15 
SET /a ACCESSORY22NAMELENGTH = 20 
SET /a ACCESSORY23NAMELENGTH = 13 
SET /a ACCESSORY24NAMELENGTH = 22 
SET /a ACCESSORY25NAMELENGTH = 17 
SET /a ACCESSORY26NAMELENGTH = 15 
SET /a ACCESSORY27NAMELENGTH = 9 
SET /a ACCESSORY28NAMELENGTH = 21 
SET /a ACCESSORY29NAMELENGTH = 16 
SET /a ACCESSORY30NAMELENGTH = 13 
SET /a ACCESSORY31NAMELENGTH = 16 
SET /a ACCESSORY32NAMELENGTH = 9 
SET /a ACCESSORY33NAMELENGTH = 19 
SET /a ACCESSORY34NAMELENGTH = 18 
SET /a ACCESSORY35NAMELENGTH = 15 
GOTO :EOF