SET /a MINNAMELENGTH = 7
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0
SET /a ARMOURSTART = %COUNT%
:ARMOUR1
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Morph Suit
SET ARMOUR%COUNT%NICKNAME=MORPHSUIT
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 0
SET /a ARMOUR%COUNT%SPR = 0
SET /a ARMOUR%COUNT%EVA = 2
SET /a ARMOUR%COUNT%SPD = 2
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Water
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 80
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 1
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 1
SET /a ARMOUR%COUNT%MAXSKL = 25
SET /a ARMOUR%COUNT%QUANTDIV = 25
SET /a ARMOUR%COUNT%EXP = 50
::CALL :ARMOURNAMELENGTH

:ARMOUR2
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Snuggie
SET ARMOUR%COUNT%NICKNAME=SNUG
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 2
SET /a ARMOUR%COUNT%SPR = 3
SET /a ARMOUR%COUNT%EVA = 1
SET /a ARMOUR%COUNT%SPD = 0
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Fire
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 200
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 1
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 1
SET /a ARMOUR%COUNT%MAXSKL = 25
SET /a ARMOUR%COUNT%QUANTDIV = 30
SET /a ARMOUR%COUNT%EXP = 75
::CALL :ARMOURNAMELENGTH

:ARMOUR3
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Lady Gaga's Meat Suit
SET ARMOUR%COUNT%NICKNAME=MEATSUIT
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 4
SET /a ARMOUR%COUNT%SPR = 0
SET /a ARMOUR%COUNT%EVA = 2
SET /a ARMOUR%COUNT%SPD = 1
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Fire
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 300
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 1
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 20
SET /a ARMOUR%COUNT%MAXSKL = 40
SET /a ARMOUR%COUNT%QUANTDIV = 40
SET /a ARMOUR%COUNT%EXP = 90
::CALL :ARMOURNAMELENGTH

:ARMOUR4
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Aluminium Foil Armour
SET ARMOUR%COUNT%NICKNAME=ALFOIL
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 2
SET /a ARMOUR%COUNT%SPR = 4
SET /a ARMOUR%COUNT%EVA = 3
SET /a ARMOUR%COUNT%SPD = 4
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Electricity
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 600
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 1
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 30
SET /a ARMOUR%COUNT%MAXSKL = 50
SET /a ARMOUR%COUNT%QUANTDIV = 50
SET /a ARMOUR%COUNT%EXP = 110
::CALL :ARMOURNAMELENGTH

:ARMOUR5
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Cloak Made From A Rug
SET ARMOUR%COUNT%NICKNAME=RUGCLOAK
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 2
SET /a ARMOUR%COUNT%SPR = 8
SET /a ARMOUR%COUNT%EVA = 5
SET /a ARMOUR%COUNT%SPD = 5
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Fire
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Electricity
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 1000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 1
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 30
SET /a ARMOUR%COUNT%MAXSKL = 50
SET /a ARMOUR%COUNT%QUANTDIV = 50
SET /a ARMOUR%COUNT%EXP = 150
::CALL :ARMOURNAMELENGTH

:ARMOUR6
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Cardboard Box Robot Suit
SET ARMOUR%COUNT%NICKNAME=CBOXSUIT
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 10
SET /a ARMOUR%COUNT%SPR = 2
SET /a ARMOUR%COUNT%EVA = 4
SET /a ARMOUR%COUNT%SPD = 5
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Water
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Earth
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 1300
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 1
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 30
SET /a ARMOUR%COUNT%MAXSKL = 50
SET /a ARMOUR%COUNT%QUANTDIV = 60
SET /a ARMOUR%COUNT%EXP = 180
::CALL :ARMOURNAMELENGTH

:ARMOUR7
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Wheelie Bin
SET ARMOUR%COUNT%NICKNAME=WHEELBIN
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 8
SET /a ARMOUR%COUNT%SPR = 8
SET /a ARMOUR%COUNT%EVA = 4
SET /a ARMOUR%COUNT%SPD = 4
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 1500
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 1
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 40
SET /a ARMOUR%COUNT%MAXSKL = 60
SET /a ARMOUR%COUNT%QUANTDIV = 50
SET /a ARMOUR%COUNT%EXP = 180
::CALL :ARMOURNAMELENGTH

:ARMOUR8
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Magic Holey Wheelie Bin
SET ARMOUR%COUNT%NICKNAME=MAGWHEELBIN
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 10
SET /a ARMOUR%COUNT%SPR = 10
SET /a ARMOUR%COUNT%EVA = 5
SET /a ARMOUR%COUNT%SPD = 5
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 2000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 1
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 45
SET /a ARMOUR%COUNT%MAXSKL = 65
SET /a ARMOUR%COUNT%QUANTDIV = 55
SET /a ARMOUR%COUNT%EXP = 200
::CALL :ARMOURNAMELENGTH

:PLASTICARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Plastic Armour
SET ARMOUR%COUNT%NICKNAME=PLASTICARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 12
SET /a ARMOUR%COUNT%SPR = 12
SET /a ARMOUR%COUNT%EVA = 8
SET /a ARMOUR%COUNT%SPD = 8
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Fire
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Electricity
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 3000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 1
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 55
SET /a ARMOUR%COUNT%MAXSKL = 75
SET /a ARMOUR%COUNT%QUANTDIV = 65
SET /a ARMOUR%COUNT%EXP = 250
::CALL :ARMOURNAMELENGTH

:LEATHERARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Leather Armour
SET ARMOUR%COUNT%NICKNAME=LEATHERARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 15
SET /a ARMOUR%COUNT%SPR = 10
SET /a ARMOUR%COUNT%EVA = 12
SET /a ARMOUR%COUNT%SPD = 14
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Fire
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Water
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 4500
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 1
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 60
SET /a ARMOUR%COUNT%MAXSKL = 80
SET /a ARMOUR%COUNT%QUANTDIV = 70
SET /a ARMOUR%COUNT%EXP = 300
::CALL :ARMOURNAMELENGTH

:GOBLINARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Goblin Armour
SET ARMOUR%COUNT%NICKNAME=GOBLINARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 20
SET /a ARMOUR%COUNT%SPR = 5
SET /a ARMOUR%COUNT%EVA = 9
SET /a ARMOUR%COUNT%SPD = 11
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 4500
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 1
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 60
SET /a ARMOUR%COUNT%MAXSKL = 80
SET /a ARMOUR%COUNT%QUANTDIV = 80
SET /a ARMOUR%COUNT%EXP = 340
::CALL :ARMOURNAMELENGTH

:GLASSARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Glass Armour
SET ARMOUR%COUNT%NICKNAME=GLASSARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 15
SET /a ARMOUR%COUNT%SPR = 18
SET /a ARMOUR%COUNT%EVA = 12
SET /a ARMOUR%COUNT%SPD = 12
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Electricity
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Earth
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Fire
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 4500
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 1
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 65
SET /a ARMOUR%COUNT%MAXSKL = 85
SET /a ARMOUR%COUNT%QUANTDIV = 85
SET /a ARMOUR%COUNT%EXP = 370
::CALL :ARMOURNAMELENGTH

:IRONARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Iron Armour
SET ARMOUR%COUNT%NICKNAME=IRONARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 25
SET /a ARMOUR%COUNT%SPR = 10
SET /a ARMOUR%COUNT%EVA = 5
SET /a ARMOUR%COUNT%SPD = 5
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Electricity
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Ice
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 5000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 1
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 85
SET /a ARMOUR%COUNT%MAXSKL = 105
SET /a ARMOUR%COUNT%QUANTDIV = 95
SET /a ARMOUR%COUNT%EXP = 450
::CALL :ARMOURNAMELENGTH

:STEELARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Steel Armour
SET ARMOUR%COUNT%NICKNAME=STEELARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 25
SET /a ARMOUR%COUNT%SPR = 18
SET /a ARMOUR%COUNT%EVA = 8
SET /a ARMOUR%COUNT%SPD = 15
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=2
SET ARMOUR%COUNT%STRENGTH1=Fire
SET ARMOUR%COUNT%STRENGTH2=Ice
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 7000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 1
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 100
SET /a ARMOUR%COUNT%MAXSKL = 125
SET /a ARMOUR%COUNT%QUANTDIV = 110
SET /a ARMOUR%COUNT%EXP = 550
::CALL :ARMOURNAMELENGTH

:TITANIUMARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Titanium Armour
SET ARMOUR%COUNT%NICKNAME=TITANIUMARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 30
SET /a ARMOUR%COUNT%SPR = 12
SET /a ARMOUR%COUNT%EVA = 10
SET /a ARMOUR%COUNT%SPD = 10
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Earth
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Electricity
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 9500
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 1
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 120
SET /a ARMOUR%COUNT%MAXSKL = 150
SET /a ARMOUR%COUNT%QUANTDIV = 140
SET /a ARMOUR%COUNT%EXP = 750
::CALL :ARMOURNAMELENGTH

:ELVENARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Elven Armour
SET ARMOUR%COUNT%NICKNAME=ELVENARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 15
SET /a ARMOUR%COUNT%SPR = 20
SET /a ARMOUR%COUNT%EVA = 25
SET /a ARMOUR%COUNT%SPD = 25
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Forbidden
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 10000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 1
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 125
SET /a ARMOUR%COUNT%MAXSKL = 150
SET /a ARMOUR%COUNT%QUANTDIV = 130
SET /a ARMOUR%COUNT%EXP = 800
::CALL :ARMOURNAMELENGTH

:DIAMONDARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Diamond Armour
SET ARMOUR%COUNT%NICKNAME=DIAMONDARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 40
SET /a ARMOUR%COUNT%SPR = 10
SET /a ARMOUR%COUNT%EVA = 10
SET /a ARMOUR%COUNT%SPD = 10
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=4
SET ARMOUR%COUNT%STRENGTH1=Fire
SET ARMOUR%COUNT%STRENGTH2=Ice
SET ARMOUR%COUNT%STRENGTH3=Electricity
SET ARMOUR%COUNT%STRENGTH4=Water
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 16000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 1
SET /a ARMOUR%COUNT%MINSKL = 150
SET /a ARMOUR%COUNT%MAXSKL = 180
SET /a ARMOUR%COUNT%QUANTDIV = 150
SET /a ARMOUR%COUNT%EXP = 1200
::CALL :ARMOURNAMELENGTH

:MYTHRILARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Mythril Armour
SET ARMOUR%COUNT%NICKNAME=MYTHRILARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 30
SET /a ARMOUR%COUNT%SPR = 30
SET /a ARMOUR%COUNT%EVA = 30
SET /a ARMOUR%COUNT%SPD = 30
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Forbidden
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 20000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 1
SET /a ARMOUR%COUNT%MINSKL = 175
SET /a ARMOUR%COUNT%MAXSKL = 230
SET /a ARMOUR%COUNT%QUANTDIV = 150
SET /a ARMOUR%COUNT%EXP = 1500
::CALL :ARMOURNAMELENGTH

:ADAMANTIUMARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Adamantium Armour
SET ARMOUR%COUNT%NICKNAME=ADAMANTIUMARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 70
SET /a ARMOUR%COUNT%SPR = 30
SET /a ARMOUR%COUNT%EVA = 20
SET /a ARMOUR%COUNT%SPD = 20
SET /a ARMOUR%COUNT%WEAKNESSNUM=1
SET ARMOUR%COUNT%WEAKNESS1=Electricity
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=1
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Fire
SET ARMOUR%COUNT%ELEMENTIMMUNE2=Water
SET ARMOUR%COUNT%ELEMENTIMMUNE3=Ice
SET ARMOUR%COUNT%ELEMENTIMMUNE4=Earth
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 40000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 200
SET /a ARMOUR%COUNT%MAXSKL = 300
SET /a ARMOUR%COUNT%QUANTDIV = 150
SET /a ARMOUR%COUNT%EXP = 2000
::CALL :ARMOURNAMELENGTH

:BATSUIT
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Batsuit
SET ARMOUR%COUNT%NICKNAME=BATSUIT
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 30
SET /a ARMOUR%COUNT%SPR = 50
SET /a ARMOUR%COUNT%EVA = 60
SET /a ARMOUR%COUNT%SPD = 40
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=7
SET ARMOUR%COUNT%STRENGTH1=Fire
SET ARMOUR%COUNT%STRENGTH2=Ice
SET ARMOUR%COUNT%STRENGTH3=Electricity
SET ARMOUR%COUNT%STRENGTH4=Water
SET ARMOUR%COUNT%STRENGTH5=Earth
SET ARMOUR%COUNT%STRENGTH6=Demi
SET ARMOUR%COUNT%STRENGTH7=Forbidden
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 40000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 250
SET /a ARMOUR%COUNT%MAXSKL = 400
SET /a ARMOUR%COUNT%QUANTDIV = 150
SET /a ARMOUR%COUNT%EXP = 2500
::CALL :ARMOURNAMELENGTH

:IRONMANARMOUR
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Iron Man's Armour
SET ARMOUR%COUNT%NICKNAME=IRONMANARMOUR
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 50
SET /a ARMOUR%COUNT%SPR = 40
SET /a ARMOUR%COUNT%EVA = 40
SET /a ARMOUR%COUNT%SPD = 60
SET /a ARMOUR%COUNT%WEAKNESSNUM=0
SET /a ARMOUR%COUNT%STRENGTHNUM=1
SET ARMOUR%COUNT%STRENGTH1=Forbidden
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=4
SET ARMOUR%COUNT%ELEMENTIMMUNE1=Ice
SET ARMOUR%COUNT%ELEMENTIMMUNE2=Fire
SET ARMOUR%COUNT%ELEMENTIMMUNE3=Water
SET ARMOUR%COUNT%ELEMENTIMMUNE4=Earth
SET /a ARMOUR%COUNT%ABSORBNUM=1
SET ARMOUR%COUNT%ABSORB1=Electricity
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 40000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 300
SET /a ARMOUR%COUNT%MAXSKL = 1000
SET /a ARMOUR%COUNT%QUANTDIV = 200
SET /a ARMOUR%COUNT%EXP = 3000
::CALL :ARMOURNAMELENGTH

:ULTIMATEPOTENTIAL
SET /a COUNT=%COUNT%+1
SET ARMOUR%COUNT%NAME=Rice Paper Cloak
SET ARMOUR%COUNT%NICKNAME=ULTIMATEPOTENTIAL
SET /a !ARMOUR%COUNT%NICKNAME!ID = %COUNT%
SET /a ARMOUR%COUNT%END = 0
SET /a ARMOUR%COUNT%SPR = 0
SET /a ARMOUR%COUNT%EVA = 0
SET /a ARMOUR%COUNT%SPD = 0
SET /a ARMOUR%COUNT%WEAKNESSNUM=7
SET ARMOUR%COUNT%WEAKNESS1=Fire
SET ARMOUR%COUNT%WEAKNESS2=Ice
SET ARMOUR%COUNT%WEAKNESS3=Electricity
SET ARMOUR%COUNT%WEAKNESS4=Water
SET ARMOUR%COUNT%WEAKNESS5=Earth
SET ARMOUR%COUNT%WEAKNESS6=Demi
SET ARMOUR%COUNT%WEAKNESS7=Forbidden
SET /a ARMOUR%COUNT%STRENGTHNUM=0
SET /a ARMOUR%COUNT%ELEMENTIMMUNENUM=0
SET /a ARMOUR%COUNT%ABSORBNUM=0
SET /a ARMOUR%COUNT%STATUSIMMUNENUM=0
SET /a ARMOUR%COUNT%COST = 40000
SET /a ARMOUR%COUNT%SELL = !ARMOUR%COUNT%COST!/4
SET /a ARMOUR%COUNT%SHOP1 = 0
SET /a ARMOUR%COUNT%SHOP2 = 0
SET /a ARMOUR%COUNT%SHOP3 = 0
SET /a ARMOUR%COUNT%SHOP4 = 0
SET /a ARMOUR%COUNT%SHOP5 = 0
SET /a ARMOUR%COUNT%MINSKL = 0
SET /a ARMOUR%COUNT%MAXSKL = 20
SET /a ARMOUR%COUNT%QUANTDIV = 150
SET /a ARMOUR%COUNT%EXP = 3000
::CALL :ARMOURNAMELENGTH

SET /a ARMOURTOTAL = %COUNT%
SET /a ARMOUREND = %COUNT%

::CALL :RECORDNAMELENGTHS
CALL :SETNAMELENGTHS

GOTO :EOF


:ARMOURNAMELENGTH
SET /a ARMOUR%COUNT%NAMELENGTH = 0
:ARMOURNAMELOOPSTART
SET /a ARMOUR%COUNT%NAMELENGTH += 1
SET TEMP1=!ARMOUR%COUNT%NAMELENGTH!
SET SUBSTR=!ARMOUR%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ARMOURNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !ARMOUR%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!ARMOUR%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ARMOURNAMELOOPSTART
	)
)
GOTO :EOF

:RECORDNAMELENGTHS
::To use this, remove all ::s from the "::::CALL :ARMOURNAMELENGTH" lines so that the game can calculate the lengths. Then uncomment "CALL :RECORDARMOURNAMELENGTHS"
SET /a COUNT = 0
:RECORDLENGTHSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a ARMOUR%COUNT%NAMELENGTH = !ARMOUR%COUNT%NAMELENGTH! >> C:\Game\ARMOURnamelengths.txt
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :RECORDLENGTHSLOOP
)
GOTO :EOF

:SETNAMELENGTHS
::This should be copied form the output of :RECORDNAMELENGTHS
SET /a ARMOUR1NAMELENGTH = 10 
SET /a ARMOUR2NAMELENGTH = 7 
SET /a ARMOUR3NAMELENGTH = 21 
SET /a ARMOUR4NAMELENGTH = 21 
SET /a ARMOUR5NAMELENGTH = 21 
SET /a ARMOUR6NAMELENGTH = 24 
SET /a ARMOUR7NAMELENGTH = 11 
SET /a ARMOUR8NAMELENGTH = 23 
SET /a ARMOUR9NAMELENGTH = 14 
SET /a ARMOUR10NAMELENGTH = 14 
SET /a ARMOUR11NAMELENGTH = 13 
SET /a ARMOUR12NAMELENGTH = 12 
SET /a ARMOUR13NAMELENGTH = 11 
SET /a ARMOUR14NAMELENGTH = 12 
SET /a ARMOUR15NAMELENGTH = 15 
SET /a ARMOUR16NAMELENGTH = 12 
SET /a ARMOUR17NAMELENGTH = 14 
SET /a ARMOUR18NAMELENGTH = 14 
SET /a ARMOUR19NAMELENGTH = 17 
SET /a ARMOUR20NAMELENGTH = 7 
SET /a ARMOUR21NAMELENGTH = 17 
SET /a ARMOUR22NAMELENGTH = 16 
GOTO :EOF