@ECHO OFF
SET CAVEBOSSTOP=± Ï ±
SET CAVEBOSSMID=±À²Ù±
SET CAVEBOSSBOT=±ÚÁ¿±

SET CAVEMON1TOP=± Ï ±
SET CAVEMON1MID=±À²Ù±
SET CAVEMON1BOT=±ÚÁ¿±

SET CAVEMON2TOP=± Ï ±
SET CAVEMON2MID=±À²Ù±
SET CAVEMON2BOT=±ÚÁ¿±

SET BOUNCERTOP=  O  
SET BOUNCERMID= Ú²¿ 
SET BOUNCERBOT= / \ 

SET KNIGHTTOP= ³O  
SET KNIGHTMID= Å²ê 
SET KNIGHTBOT= / \ 

SET WIZTOP=  â* 
SET WIZMID= -²´ 
SET WIZBOT=  º³ 


