SET /a MPGILFACTOR = 10
SET /a MPREDUCTIONPOINTCOST = 50
SET /a DAMAGEPOINTMPCOST = 3
SET /a DAMAGEPOINTGILCOST = %DAMAGEPOINTMPCOST%*%MPGILFACTOR%
SET /a HEALPOINTMPCOST = 3
SET /a HEALPOINTGILCOST = %HEALPOINTMPCOST%*%MPGILFACTOR%

SET /a SUPP1GILCOST = %SUPP1MPCOST%*%MPGILFACTOR%
SET /a SUPP2GILCOST = %SUPP2MPCOST%*%MPGILFACTOR%
SET /a SUPP3GILCOST = %SUPP3MPCOST%*%MPGILFACTOR%
SET /a SUPP4GILCOST = %SUPP4MPCOST%*%MPGILFACTOR%
SET /a SUPP5GILCOST = %SUPP5MPCOST%*%MPGILFACTOR%

SET /a REST5GILCOST = %REST5MPCOST%*%MPGILFACTOR%

REM SET /a DEB1GILCOST = %DEB1MPCOST%*%MPGILFACTOR%
REM SET /a DEB2GILCOST = %DEB2MPCOST%*%MPGILFACTOR%
REM SET /a DEB3GILCOST = %DEB3MPCOST%*%MPGILFACTOR%
REM SET /a DEB4GILCOST = %DEB4MPCOST%*%MPGILFACTOR%
REM SET /a DEB5GILCOST = %DEB5MPCOST%*%MPGILFACTOR%
REM SET /a DEB6GILCOST = %DEB6MPCOST%*%MPGILFACTOR%
REM SET /a DEB7GILCOST = %DEB7MPCOST%*%MPGILFACTOR%
REM SET /a DEB8GILCOST = %DEB8MPCOST%*%MPGILFACTOR%

SET /a STAT1GILCOST = %STAT1MPCOST%*%MPGILFACTOR%
SET /a STAT2GILCOST = %STAT2MPCOST%*%MPGILFACTOR%
SET /a STAT3GILCOST = %STAT3MPCOST%*%MPGILFACTOR%
SET /a STAT4GILCOST = %STAT4MPCOST%*%MPGILFACTOR%
SET /a STAT5GILCOST = %STAT5MPCOST%*%MPGILFACTOR%
SET /a STAT6GILCOST = %STAT6MPCOST%*%MPGILFACTOR%
SET /a STAT7GILCOST = %STAT7MPCOST%*%MPGILFACTOR%


