SET /a COUNT = 0
:KAIOKENSTATS
SET /a COUNT=%COUNT%+1
SET /a DBZ%COUNT%ID = %COUNT%
SET DBZ%COUNT%MOVE=Kaioken Attack
SET /a DBZ%COUNT%BASEDAM = 10
SET /a DBZ%COUNT%ENERGY = 5
SET /a DBZ%COUNT%UNLOCKLVL = 5

:KAMEHAMEHASTATS
SET /a COUNT=%COUNT%+1
SET /a DBZ%COUNT%ID = %COUNT%
SET DBZ%COUNT%MOVE=Kamehameha
SET /a DBZ%COUNT%BASEDAM = 30
SET /a DBZ%COUNT%ENERGY = 20
SET /a DBZ%COUNT%UNLOCKLVL = 10

:ITLKAMEHAMEHASTATS
SET /a COUNT=%COUNT%+1
SET /a DBZ%COUNT%ID = %COUNT%
SET DBZ%COUNT%MOVE=Instant Translocation Kamehameha
SET /a DBZ%COUNT%BASEDAM = 50
SET /a DBZ%COUNT%ENERGY = 40
SET /a DBZ%COUNT%UNLOCKLVL = 15

:SSBOMBSTATS
SET /a COUNT=%COUNT%+1
SET /a DBZ%COUNT%ID = %COUNT%
SET DBZ%COUNT%MOVE=Super Spirit Bomb
SET /a DBZ%COUNT%BASEDAM = 120
SET /a DBZ%COUNT%ENERGY = 100
SET /a DBZ%COUNT%UNLOCKLVL = 20


SET /a DBZMOVETOT = %COUNT%