SET /a RANHINT = (%RANDOM% %% %HINTTOT%) + 1
CLS
CALL "%MISCRESOURCEPATH%\titledisplay.bat"
SET /a COUNT = 0
:HINTLOOP
SET /a COUNT = %COUNT% + 1
ECHO !HINT%RANHINT%LINE%COUNT%!
IF %COUNT% LSS !HINT%RANHINT%LINENUM! (
	GOTO :HINTLOOP
)
GOTO :EOF