SET DISPLAYLETTER 1=     
SET DISPLAYLETTER 2=     
SET DISPLAYLETTER 3=     
SET DISPLAYLETTER 4=     
SET DISPLAYLETTER 5=     
SET DISPLAYLETTER 6=     

SET DISPLAYLETTERA1=_       
SET DISPLAYLETTERA2=/ ³     
SET DISPLAYLETTERA3=/  ³    
SET DISPLAYLETTERA4=/ Ù ³   
SET DISPLAYLETTERA5=/ _  ³  
SET DISPLAYLETTERA6=/_/ ³_³ 

SET DISPLAYLETTERB1=_____    
SET DISPLAYLETTERB2=/     ³  
SET DISPLAYLETTERB3=/   ² /  
SET DISPLAYLETTERB4=/  ÄÄÄ/  
SET DISPLAYLETTERB5=/   ² /  
SET DISPLAYLETTERB6=/_____/  

SET DISPLAYLETTERC1=______   
SET DISPLAYLETTERC2=/  ___/  
SET DISPLAYLETTERC3=/  /     
SET DISPLAYLETTERC4=/  /     
SET DISPLAYLETTERC5=/  /__   
SET DISPLAYLETTERC6=/_____/  

SET DISPLAYLETTERD1=_____    
SET DISPLAYLETTERD2=/     ³  
SET DISPLAYLETTERD3=/     /  
SET DISPLAYLETTERD4=/  ²  /  
SET DISPLAYLETTERD5=/     /  
SET DISPLAYLETTERD6=/_____/  

SET DISPLAYLETTERE1=______   
SET DISPLAYLETTERE2=/ ____/  
SET DISPLAYLETTERE3=/ /_     
SET DISPLAYLETTERE4=/ __/    
SET DISPLAYLETTERE5=/ /___   
SET DISPLAYLETTERE6=/_____/  

SET DISPLAYLETTERF1=______   
SET DISPLAYLETTERF2=/ ____/  
SET DISPLAYLETTERF3=/ /_     
SET DISPLAYLETTERF4=/ __/    
SET DISPLAYLETTERF5=/ /      
SET DISPLAYLETTERF6=/_/      

SET DISPLAYLETTERG1=______   
SET DISPLAYLETTERG2=/ ____/  
SET DISPLAYLETTERG3=/ / ___  
SET DISPLAYLETTERG4=/ / / _/ 
SET DISPLAYLETTERG5=/ /__//  
SET DISPLAYLETTERG6=/_____/  

SET DISPLAYLETTERH1=__  __  
SET DISPLAYLETTERH2=/ / / / 
SET DISPLAYLETTERH3=/ /_/ / 
SET DISPLAYLETTERH4=/ __  / 
SET DISPLAYLETTERH5=/ / / / 
SET DISPLAYLETTERH6=/_/ /_/ 

SET DISPLAYLETTERI1=__   
SET DISPLAYLETTERI2=/ /  
SET DISPLAYLETTERI3=/ /  
SET DISPLAYLETTERI4=/ /  
SET DISPLAYLETTERI5=/ /  
SET DISPLAYLETTERI6=/_/  

SET DISPLAYLETTERJ1=_______  
SET DISPLAYLETTERJ2=/__  __/ 
SET DISPLAYLETTERJ3=   / /   
SET DISPLAYLETTERJ4=   / /   
SET DISPLAYLETTERJ5= __/ /   
SET DISPLAYLETTERJ6=/____/   

SET DISPLAYLETTERK1=__   __   
SET DISPLAYLETTERK2=/ /  / /  
SET DISPLAYLETTERK3=/ /_/ /   
SET DISPLAYLETTERK4=/    /    
SET DISPLAYLETTERK5=/ / \ \   
SET DISPLAYLETTERK6=/_/   \_\ 

SET DISPLAYLETTERL1=__       
SET DISPLAYLETTERL2=/ /      
SET DISPLAYLETTERL3=/ /      
SET DISPLAYLETTERL4=/ /      
SET DISPLAYLETTERL5=/ /___   
SET DISPLAYLETTERL6=/_____/  

SET DISPLAYLETTERM1=_   _      
SET DISPLAYLETTERM2=/ ³ / ³    
SET DISPLAYLETTERM3=/  ³/  ³   
SET DISPLAYLETTERM4=/ /³ /³ ³  
SET DISPLAYLETTERM5=/ / ³/ ³ ³ 
SET DISPLAYLETTERM6=/_/     ³_³

SET DISPLAYLETTERN1=_    _   
SET DISPLAYLETTERN2=/ ³  / / 
SET DISPLAYLETTERN3=/  ³ / / 
SET DISPLAYLETTERN4=/   ³/ / 
SET DISPLAYLETTERN5=/ /³   / 
SET DISPLAYLETTERN6=/_/ ³__/ 

SET DISPLAYLETTERO1=______   
SET DISPLAYLETTERO2=/     /  
SET DISPLAYLETTERO3=/     /  
SET DISPLAYLETTERO4=/  ²  /  
SET DISPLAYLETTERO5=/     /  
SET DISPLAYLETTERO6=/_____/  

SET DISPLAYLETTERP1=______   
SET DISPLAYLETTERP2=/     /  
SET DISPLAYLETTERP3=/  ²  /  
SET DISPLAYLETTERP4=/ ____/  
SET DISPLAYLETTERP5=/ /      
SET DISPLAYLETTERP6=/_/      

SET DISPLAYLETTERQ1=______    
SET DISPLAYLETTERQ2=/     /   
SET DISPLAYLETTERQ3=/     /   
SET DISPLAYLETTERQ4=/  ²  /   
SET DISPLAYLETTERQ5=/     /_  
SET DISPLAYLETTERQ6=/_______/ 

SET DISPLAYLETTERR1=______   
SET DISPLAYLETTERR2=/     /  
SET DISPLAYLETTERR3=/  ²  /  
SET DISPLAYLETTERR4=/   __/  
SET DISPLAYLETTERR5=/ /\ \   
SET DISPLAYLETTERR6=/_/  \_\ 

SET DISPLAYLETTERS1=______   
SET DISPLAYLETTERS2=/ ____/  
SET DISPLAYLETTERS3=/ /___   
SET DISPLAYLETTERS4=/___  /  
SET DISPLAYLETTERS5=____/ /  
SET DISPLAYLETTERS6=/_____/  

SET DISPLAYLETTERT1=_______  
SET DISPLAYLETTERT2=/__  __/ 
SET DISPLAYLETTERT3=   / /   
SET DISPLAYLETTERT4=   / /   
SET DISPLAYLETTERT5=   / /   
SET DISPLAYLETTERT6=   /_/   

SET DISPLAYLETTERU1=__   __   
SET DISPLAYLETTERU2=/ /  / /  
SET DISPLAYLETTERU3=/ /  / /  
SET DISPLAYLETTERU4=/ /  / /  
SET DISPLAYLETTERU5=/ /__/ /  
SET DISPLAYLETTERU6=/______/  


SET DISPLAYLETTERV1=__    __  
SET DISPLAYLETTERV2=³ ³   / / 
SET DISPLAYLETTERV3= ³ ³  / / 
SET DISPLAYLETTERV4=  ³ ³ / / 
SET DISPLAYLETTERV5=   ³ ³/ / 
SET DISPLAYLETTERV6=    ³___/ 

SET DISPLAYLETTERW1=__          __  
SET DISPLAYLETTERW2= ³ ³        / / 
SET DISPLAYLETTERW3=  ³ ³  __   / / 
SET DISPLAYLETTERW4=   ³ ³ /  ³ / / 
SET DISPLAYLETTERW5=    ³ ³/ /³³/ / 
SET DISPLAYLETTERW6=     ³___/ ³__/ 

SET DISPLAYLETTERX1=__    ___    
SET DISPLAYLETTERX2= \ \  /  /   
SET DISPLAYLETTERX3=   \ \/  /   
SET DISPLAYLETTERX4=     /  /    
SET DISPLAYLETTERX5=    /  /\ \  
SET DISPLAYLETTERX6=   /__/   \_\

SET DISPLAYLETTERY1=__  __  
SET DISPLAYLETTERY2=³ ³ / / 
SET DISPLAYLETTERY3= ³ ³/ / 
SET DISPLAYLETTERY4=   \  / 
SET DISPLAYLETTERY5=    / / 
SET DISPLAYLETTERY6=    /_/ 

SET DISPLAYLETTERZ1=______   
SET DISPLAYLETTERZ2=/__   /  
SET DISPLAYLETTERZ3=   / /
SET DISPLAYLETTERZ4=  / /  
SET DISPLAYLETTERZ5= / /__ 
SET DISPLAYLETTERZ6=/_____/  

