SET /a COUNT = 0
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Standard Items
SET MINEITEM%COUNT%SPECIAL=STANDARD
SET MINEITEM%COUNT%TYPE=ITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Scrolls
SET MINEITEM%COUNT%SPECIAL=SCROLL
SET MINEITEM%COUNT%TYPE=ITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Stat Stones
SET MINEITEM%COUNT%SPECIAL=STATSTONE
SET MINEITEM%COUNT%TYPE=SPECIALITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Skill Stones
SET MINEITEM%COUNT%SPECIAL=SKILLSTONE
SET MINEITEM%COUNT%TYPE=SPECIALITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Resistance Powder
SET MINEITEM%COUNT%SPECIAL=RESISTANCEPOWDER
SET MINEITEM%COUNT%TYPE=SPECIALITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Special Stones
SET MINEITEM%COUNT%SPECIAL=SPECIALSTONE
SET MINEITEM%COUNT%TYPE=SPECIALITEM
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Weapons
SET MINEITEM%COUNT%SPECIAL=WEAPON
SET MINEITEM%COUNT%TYPE=WEAPON
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Armour
SET MINEITEM%COUNT%SPECIAL=ARMOUR
SET MINEITEM%COUNT%TYPE=ARMOUR
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 10000
SET /a COUNT = %COUNT% + 1
SET MINEITEM%COUNT%SPECIALDISPLAY=Accessories
SET MINEITEM%COUNT%SPECIAL=ACCESSORY
SET MINEITEM%COUNT%TYPE=ACCESSORY
SET /a MINEITEM%COUNT%SPECIALUNLOCKCOST = 5000


SET /a COUNT = 0
:SPECIALDISPLAYLENGTH
SET /a COUNT = %COUNT% + 1
SET /a MINEITEM%COUNT%SPECIALDISPLAYLENGTH = 0
:SPECIALDISPLAYLENGTHLOOPSTART
SET /a MINEITEM%COUNT%SPECIALDISPLAYLENGTH += 1
SET TEMP1=!MINEITEM%COUNT%SPECIALDISPLAYLENGTH!
SET SUBSTR=!MINEITEM%COUNT%SPECIALDISPLAY:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPECIALDISPLAYLENGTHLOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !MINEITEM%COUNT%SPECIALDISPLAYLENGTH! + 1
	SET SUBSTR=!MINEITEM%COUNT%SPECIALDISPLAY:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPECIALDISPLAYLENGTHLOOPSTART
	)
)
IF %COUNT% LSS 9 (
	GOTO :SPECIALDISPLAYLENGTH
)
