SET /a COUNT = 0
:ENEMYLOOPSTART
SET /a COUNT = %COUNT% + 1
CALL :SETNAMELENGTH
CALL :SETDESCRIPTIONLENGTH
REM SET /a TEMPREWARDSET = 1
REM CALL :SETITEMREWARDSLENGTH
REM CALL :SETEEQUIPMENTREWARDLENGTH
REM SET /a TEMPREWARDSET = 2
REM CALL :SETITEMREWARDSLENGTH
REM CALL :SETEEQUIPMENTREWARDLENGTH
IF %COUNT% LSS %BOSSIDEND% (
	GOTO :ENEMYLOOPSTART
)
GOTO :EOF





:SETNAMELENGTH
SET /a LENGTH = 0
:ENEMYNAMELOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!ENEMY%COUNT%NAME:~%LENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ENEMYNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %LENGTH% + 1
	SET SUBSTR=!ENEMY%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ENEMYNAMELOOPSTART
	)
)
SET /a ENEMY%COUNT%NAMELENGTH = %LENGTH%
GOTO :EOF


:SETDESCRIPTIONLENGTH
SET /a DESCCOUNT = 0
:DESCLOOPSTART
SET /a DESCCOUNT = %DESCCOUNT% + 1
IF DEFINED ENEMY%COUNT%DESCRIPTION%DESCCOUNT% (
	CALL :SETDESCLENGTH
)
IF %DESCCOUNT% LSS 4 (
	GOTO :DESCLOOPSTART
)
GOTO :EOF



:SETDESCLENGTH
SET /a LENGTH = 0
:ENEMYDESCRIPTIONLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!ENEMY%COUNT%DESCRIPTION%DESCCOUNT%:~%LENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ENEMYDESCRIPTIONLOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %LENGTH% + 1
	SET SUBSTR=!ENEMY%COUNT%DESCRIPTION%DESCCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ENEMYDESCRIPTIONLOOPSTART
	)
)
SET /a ENEMY%COUNT%DESCRIPTION%DESCCOUNT%LENGTH = %LENGTH%
GOTO :EOF








