:INITIALISE
SET /a COUNT = 0
:INITIALISELOOP1
SET /a COUNT = %COUNT% + 1
SET /a TEMPCOUNT = 0
:INITIALISELOOP2
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
SET /a ENEMY%COUNT%!ENEMYSKILL%TEMPCOUNT%NICKNAME!ENABLED = 0
IF %TEMPCOUNT% LSS %ENEMYSKILLTOT% (
	GOTO :INITIALISELOOP2
) ELSE IF %COUNT% LSS %BOSSIDEND% (
	GOTO :INITIALISELOOP1
)
SET /a COUNT = 0
:LOOP1
SET /a COUNT = %COUNT% + 1
SET /a TEMPCOUNT = 0
IF !ENEMY%COUNT%SKILLNUM! EQU 0 (
	GOTO :LOOPEND
)
:LOOP2
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
SET /a TEMP = !ENEMY%COUNT%SKILL%TEMPCOUNT%!
SET /a ENEMY%COUNT%!ENEMYSKILL%TEMP%NICKNAME!ENABLED = 1
IF %TEMPCOUNT% LSS !ENEMY%COUNT%SKILLNUM! (
	GOTO :LOOP2
)
:LOOPEND
IF %COUNT% LSS %BOSSIDEND% (
	GOTO :LOOP1
)
GOTO :EOF