SET TYPE=OFF
CALL :LOOP
SET TYPE=STAT
CALL :LOOP
SET TYPE=REST
CALL :LOOP
SET TYPE=SUPP
CALL :LOOP
GOTO :EOF



:LOOP
SET /a COUNT = 0
:LOOP1
SET /a COUNT = %COUNT% + 1
SET /a TEMPCOUNT = 0
SET /a ENEMY%COUNT%%TYPE%SPELLNUM = 0
:LOOP2
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
SET TEMP=!%TYPE%%TEMPCOUNT%SPELL!
IF !ENEMY%COUNT%%TEMP%ENABLED! EQU 1 (
	CALL :ENABLED
)
IF %TEMPCOUNT% LSS !%TYPE%SPELLTOT! (
	GOTO :LOOP2
) ELSE IF %COUNT% LSS %BOSSIDEND% (
	GOTO :LOOP1
)
GOTO :EOF

:ENABLED
SET /a ENEMY%COUNT%%TYPE%SPELLNUM = !ENEMY%COUNT%%TYPE%SPELLNUM! + 1
SET /a ENEMY%COUNT%%TYPE%SPELL!ENEMY%COUNT%%TYPE%SPELLNUM! = %TEMPCOUNT%
GOTO :EOF
