::If changes are made to enemy spells/skills/items then :LOADENEMIES and :RECORDANIMATIONS needs to run
::Otherwise just run :SETANIMATIONS
::For testing:
::SET /a BOSSIDEND = 10

::For recording the data
::CALL :LOADENEMIES
::CALL :RECORDANIMATIONS
::CALL :GIMPLY

::For setting the data one it's been recorded
CALL :SETANIMATIONS
GOTO :EOF






:LOADENEMIES
::This will load every enemy in the game and then record the animations that each of them require
SET /a ENEMYID = 0
:LOADENEMYLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
	ECHO LOADED !ENEMY%ENEMYID%NAME!
)
IF %ENEMYID% LSS %BOSSIDEND% (
	GOTO :LOADENEMYLOOP
)
::Now that all enemies are loaded, record what animations are required
GOTO :EOF

:RECORDANIMATIONS
SET /a COUNT = 0
:RECORDANIMATIONSLOOP
SET /a COUNT = %COUNT% + 1
ECHO !ENEMY%COUNT%NAME!
CALL :INITIALISE
CALL :FIRESPELL
CALL :ELECTRICITYSPELL
CALL :WATERSPELL
CALL :ICESPELL
CALL :EARTHSPELL
CALL :DRAINSPELL
CALL :DEMISPELL
CALL :FORBIDDEN1SPELL
CALL :FORBIDDEN2SPELL
CALL :STATUSSPELL
CALL :SELFSPELL
:SPELLSDONE
CALL :ITEMS
CALL :SKILLS
CALL :RECORD
IF %COUNT% LSS %BOSSIDEND% (
	GOTO :RECORDANIMATIONSLOOP
)
GOTO :EOF

:INITIALISE
SET /a ENEMY%COUNT%FIRESPELLANIMATION = 0
SET /a ENEMY%COUNT%ICESPELLANIMATION = 0
SET /a ENEMY%COUNT%WATERSPELLANIMATION = 0
SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 0
SET /a ENEMY%COUNT%EARTHSPELLANIMATION = 0
SET /a ENEMY%COUNT%DRAINSPELLANIMATION = 0
SET /a ENEMY%COUNT%DEMISPELLANIMATION = 0
SET /a ENEMY%COUNT%FORBIDDEN1SPELLANIMATION = 0
SET /a ENEMY%COUNT%FORBIDDEN2SPELLANIMATION = 0
SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 0
SET /a ENEMY%COUNT%SELFSPELLANIMATION = 0
SET /a ENEMY%COUNT%OFFITEMANIMATION = 0
SET /a ENEMY%COUNT%SELFITEMANIMATION = 0
GOTO :EOF


:FIRESPELL
IF DEFINED ENEMY%COUNT%FIREENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%FIRAENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%FIRAGAENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%FLAREENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%INFERNOENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%FIRESTORMENABLED (
	SET /a ENEMY%COUNT%FIRESPELLANIMATION = 1
)
GOTO :EOF

:ELECTRICITYSPELL
IF DEFINED ENEMY%COUNT%THUNDERENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%THUNDARAENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%THUNDAGAENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%ZAPENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%LIGHTNINGENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%STORMFIREENABLED (
	SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = 1
)
GOTO :EOF

:ICESPELL
IF DEFINED ENEMY%COUNT%BLIZZARDENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%BLIZZARAENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%BLIZZAGAENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%FREEZEENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%ARCTICBLASTENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%ICESTORMENABLED (
	SET /a ENEMY%COUNT%ICESPELLANIMATION = 1
)
GOTO :EOF

:WATERSPELL
IF DEFINED ENEMY%COUNT%WATERENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%WATERAENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%WATERAGAENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%WAVEENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%HYDROPUMPENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%HYDROCANNONENABLED (
	SET /a ENEMY%COUNT%WATERSPELLANIMATION = 1
)
GOTO :EOF

:DRAINSPELL
IF DEFINED ENEMY%COUNT%DRAINENABLED (
	SET /a ENEMY%COUNT%DRAINSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%DRAINARAENABLED (
	SET /a ENEMY%COUNT%DRAINSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%DRAINAGAENABLED (
	SET /a ENEMY%COUNT%DRAINSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%DISPELENABLED (
	SET /a ENEMY%COUNT%DRAINSPELLANIMATION = 1
) 
GOTO :EOF

:DEMISPELL
IF DEFINED ENEMY%COUNT%DEMIENABLED (
	SET /a ENEMY%COUNT%DEMISPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%DEMIRAENABLED (
	SET /a ENEMY%COUNT%DEMISPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%DEMIGAENABLED (
	SET /a ENEMY%COUNT%DEMISPELLANIMATION = 1
) 
GOTO :EOF

:EARTHSPELL
IF DEFINED ENEMY%COUNT%QUAKEENABLED (
	SET /a ENEMY%COUNT%EARTHSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%QUAKARAENABLED (
	SET /a ENEMY%COUNT%EARTHSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%QUAKAGAENABLED (
	SET /a ENEMY%COUNT%EARTHSPELLANIMATION = 1
) 
GOTO :EOF

:FORBIDDEN1SPELL
IF DEFINED ENEMY%COUNT%COMETENABLED (
	SET /a ENEMY%COUNT%FORBIDDEN1SPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%METEORENABLED (
	SET /a ENEMY%COUNT%FORBIDDEN1SPELLANIMATION = 1
)
GOTO :EOF

:FORBIDDEN2SPELL
IF DEFINED ENEMY%COUNT%SHADOWFLAREENABLED (
	SET /a ENEMY%COUNT%FORBIDDEN2SPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%ULTIMAENABLED (
	SET /a ENEMY%COUNT%FORBIDDEN2SPELLANIMATION = 1
)
GOTO :EOF

:STATUSSPELL
IF DEFINED ENEMY%COUNT%BLINDENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%SILENCEENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%POISONENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%SLOWENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%SLEEPENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%CONFUSIONENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%STOPENABLED (
	SET /a ENEMY%COUNT%STATUSSPELLANIMATION = 1
) 
GOTO :EOF

:SELFSPELL
IF DEFINED ENEMY%COUNT%CUREENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%CURAENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%CURAGAENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%ESUNAENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%REGENENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%HASTEENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%PROTECTENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%SHELLENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) ELSE IF DEFINED ENEMY%COUNT%REFLECTENABLED (
	SET /a ENEMY%COUNT%SELFSPELLANIMATION = 1
) 
GOTO :EOF

:ITEMS
IF !ENEMY%COUNT%ITEMNUM! GTR 0 (
	SET /a ENEMY%COUNT%OFFITEMANIMATION = 1
	SET /a ENEMY%COUNT%SELFITEMANIMATION = 1
) ELSE IF !ENEMY%COUNT%ENEMYMUGENABLED! EQU 1 (
	SET /a ENEMY%COUNT%OFFITEMANIMATION = 1
	SET /a ENEMY%COUNT%SELFITEMANIMATION = 1
)	
GOTO :EOF

:SKILLS
SET /a ENEMYSKILLTOT = !ENEMY%COUNT%SKILLNUM!
SET /a SKILLCOUNT = 0
IF %ENEMYSKILLTOT% EQU 0 (
	GOTO :EOF
)
:SKILLSLOOP
SET /a SKILLCOUNT = %SKILLCOUNT% + 1
SET /a SKILLID = !ENEMY%COUNT%SKILL%SKILLCOUNT%!
SET ANIMATION=!ENEMYSKILL%SKILLID%ANIMATION!
SET /a ENEMY%COUNT%%ANIMATION%ANIMATION = 1
IF %SKILLCOUNT% LSS %ENEMYSKILLTOT% (
	GOTO :SKILLSLOOP
)
GOTO :EOF


:RECORD
ECHO SET /a ENEMY%COUNT%FIRESPELLANIMATION = !ENEMY%COUNT%FIRESPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%ICESPELLANIMATION = !ENEMY%COUNT%ICESPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%WATERSPELLANIMATION = !ENEMY%COUNT%WATERSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%ELECTRICITYSPELLANIMATION = !ENEMY%COUNT%ELECTRICITYSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%EARTHSPELLANIMATION = !ENEMY%COUNT%EARTHSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%DRAINSPELLANIMATION = !ENEMY%COUNT%DRAINSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%DEMISPELLANIMATION = !ENEMY%COUNT%DEMISPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%FORBIDDEN1SPELLANIMATION = !ENEMY%COUNT%FORBIDDEN1SPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%FORBIDDEN2SPELLANIMATION = !ENEMY%COUNT%FORBIDDEN2SPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%STATUSSPELLANIMATION = !ENEMY%COUNT%STATUSSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%SELFSPELLANIMATION = !ENEMY%COUNT%SELFSPELLANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%OFFITEMANIMATION = !ENEMY%COUNT%OFFITEMANIMATION! >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%COUNT%SELFITEMANIMATION = !ENEMY%COUNT%SELFITEMANIMATION! >> C:\Game\enemyanimations.txt
GOTO :EOF

:GIMPLY
ECHO SET /a ENEMY%GIMPLYID%FIRESPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%ICESPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%WATERSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%ELECTRICITYSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%EARTHSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%DRAINSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%DEMISPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%FORBIDDEN1SPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%FORBIDDEN2SPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%STATUSSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%SELFSPELLANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%OFFITEMANIMATION = 1 >> C:\Game\enemyanimations.txt
ECHO SET /a ENEMY%GIMPLYID%SELFITEMANIMATION = 1 >> C:\Game\enemyanimations.txt
GOTO :EOF


:SETANIMATIONS
::copied from enemyanimations.txt
SET /a ENEMY1FIRESPELLANIMATION = 0 
SET /a ENEMY1ICESPELLANIMATION = 0 
SET /a ENEMY1WATERSPELLANIMATION = 0 
SET /a ENEMY1ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY1EARTHSPELLANIMATION = 0 
SET /a ENEMY1DRAINSPELLANIMATION = 0 
SET /a ENEMY1DEMISPELLANIMATION = 0 
SET /a ENEMY1FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY1FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY1STATUSSPELLANIMATION = 0 
SET /a ENEMY1SELFSPELLANIMATION = 0 
SET /a ENEMY1OFFITEMANIMATION = 0 
SET /a ENEMY1SELFITEMANIMATION = 0 
SET /a ENEMY2FIRESPELLANIMATION = 0 
SET /a ENEMY2ICESPELLANIMATION = 0 
SET /a ENEMY2WATERSPELLANIMATION = 0 
SET /a ENEMY2ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY2EARTHSPELLANIMATION = 0 
SET /a ENEMY2DRAINSPELLANIMATION = 0 
SET /a ENEMY2DEMISPELLANIMATION = 0 
SET /a ENEMY2FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY2FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY2STATUSSPELLANIMATION = 0 
SET /a ENEMY2SELFSPELLANIMATION = 0 
SET /a ENEMY2OFFITEMANIMATION = 0 
SET /a ENEMY2SELFITEMANIMATION = 0 
SET /a ENEMY3FIRESPELLANIMATION = 1 
SET /a ENEMY3ICESPELLANIMATION = 1 
SET /a ENEMY3WATERSPELLANIMATION = 1 
SET /a ENEMY3ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY3EARTHSPELLANIMATION = 0 
SET /a ENEMY3DRAINSPELLANIMATION = 0 
SET /a ENEMY3DEMISPELLANIMATION = 0 
SET /a ENEMY3FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY3FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY3STATUSSPELLANIMATION = 1 
SET /a ENEMY3SELFSPELLANIMATION = 1 
SET /a ENEMY3OFFITEMANIMATION = 1 
SET /a ENEMY3SELFITEMANIMATION = 1 
SET /a ENEMY4FIRESPELLANIMATION = 0 
SET /a ENEMY4ICESPELLANIMATION = 0 
SET /a ENEMY4WATERSPELLANIMATION = 0 
SET /a ENEMY4ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY4EARTHSPELLANIMATION = 0 
SET /a ENEMY4DRAINSPELLANIMATION = 0 
SET /a ENEMY4DEMISPELLANIMATION = 0 
SET /a ENEMY4FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY4FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY4STATUSSPELLANIMATION = 0 
SET /a ENEMY4SELFSPELLANIMATION = 0 
SET /a ENEMY4OFFITEMANIMATION = 0 
SET /a ENEMY4SELFITEMANIMATION = 0 
SET /a ENEMY5FIRESPELLANIMATION = 0 
SET /a ENEMY5ICESPELLANIMATION = 0 
SET /a ENEMY5WATERSPELLANIMATION = 0 
SET /a ENEMY5ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY5EARTHSPELLANIMATION = 0 
SET /a ENEMY5DRAINSPELLANIMATION = 0 
SET /a ENEMY5DEMISPELLANIMATION = 0 
SET /a ENEMY5FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY5FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY5STATUSSPELLANIMATION = 0 
SET /a ENEMY5SELFSPELLANIMATION = 1 
SET /a ENEMY5OFFITEMANIMATION = 0 
SET /a ENEMY5SELFITEMANIMATION = 0 
SET /a ENEMY6FIRESPELLANIMATION = 0 
SET /a ENEMY6ICESPELLANIMATION = 0 
SET /a ENEMY6WATERSPELLANIMATION = 0 
SET /a ENEMY6ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY6EARTHSPELLANIMATION = 0 
SET /a ENEMY6DRAINSPELLANIMATION = 1 
SET /a ENEMY6DEMISPELLANIMATION = 0 
SET /a ENEMY6FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY6FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY6STATUSSPELLANIMATION = 0 
SET /a ENEMY6SELFSPELLANIMATION = 0 
SET /a ENEMY6OFFITEMANIMATION = 0 
SET /a ENEMY6SELFITEMANIMATION = 0 
SET /a ENEMY7FIRESPELLANIMATION = 0 
SET /a ENEMY7ICESPELLANIMATION = 0 
SET /a ENEMY7WATERSPELLANIMATION = 0 
SET /a ENEMY7ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY7EARTHSPELLANIMATION = 0 
SET /a ENEMY7DRAINSPELLANIMATION = 0 
SET /a ENEMY7DEMISPELLANIMATION = 0 
SET /a ENEMY7FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY7FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY7STATUSSPELLANIMATION = 0 
SET /a ENEMY7SELFSPELLANIMATION = 0 
SET /a ENEMY7OFFITEMANIMATION = 1 
SET /a ENEMY7SELFITEMANIMATION = 1 
SET /a ENEMY8FIRESPELLANIMATION = 0 
SET /a ENEMY8ICESPELLANIMATION = 0 
SET /a ENEMY8WATERSPELLANIMATION = 0 
SET /a ENEMY8ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY8EARTHSPELLANIMATION = 0 
SET /a ENEMY8DRAINSPELLANIMATION = 1 
SET /a ENEMY8DEMISPELLANIMATION = 0 
SET /a ENEMY8FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY8FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY8STATUSSPELLANIMATION = 1 
SET /a ENEMY8SELFSPELLANIMATION = 0 
SET /a ENEMY8OFFITEMANIMATION = 0 
SET /a ENEMY8SELFITEMANIMATION = 0 
SET /a ENEMY9FIRESPELLANIMATION = 0 
SET /a ENEMY9ICESPELLANIMATION = 0 
SET /a ENEMY9WATERSPELLANIMATION = 0 
SET /a ENEMY9ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY9EARTHSPELLANIMATION = 0 
SET /a ENEMY9DRAINSPELLANIMATION = 0 
SET /a ENEMY9DEMISPELLANIMATION = 0 
SET /a ENEMY9FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY9FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY9STATUSSPELLANIMATION = 0 
SET /a ENEMY9SELFSPELLANIMATION = 0 
SET /a ENEMY9OFFITEMANIMATION = 0 
SET /a ENEMY9SELFITEMANIMATION = 0 
SET /a ENEMY10FIRESPELLANIMATION = 0 
SET /a ENEMY10ICESPELLANIMATION = 1 
SET /a ENEMY10WATERSPELLANIMATION = 0 
SET /a ENEMY10ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY10EARTHSPELLANIMATION = 0 
SET /a ENEMY10DRAINSPELLANIMATION = 0 
SET /a ENEMY10DEMISPELLANIMATION = 0 
SET /a ENEMY10FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY10FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY10STATUSSPELLANIMATION = 0 
SET /a ENEMY10SELFSPELLANIMATION = 1 
SET /a ENEMY10OFFITEMANIMATION = 0 
SET /a ENEMY10SELFITEMANIMATION = 0 
SET /a ENEMY11FIRESPELLANIMATION = 0 
SET /a ENEMY11ICESPELLANIMATION = 0 
SET /a ENEMY11WATERSPELLANIMATION = 0 
SET /a ENEMY11ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY11EARTHSPELLANIMATION = 0 
SET /a ENEMY11DRAINSPELLANIMATION = 0 
SET /a ENEMY11DEMISPELLANIMATION = 0 
SET /a ENEMY11FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY11FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY11STATUSSPELLANIMATION = 0 
SET /a ENEMY11SELFSPELLANIMATION = 0 
SET /a ENEMY11OFFITEMANIMATION = 0 
SET /a ENEMY11SELFITEMANIMATION = 0 
SET /a ENEMY12FIRESPELLANIMATION = 0 
SET /a ENEMY12ICESPELLANIMATION = 0 
SET /a ENEMY12WATERSPELLANIMATION = 0 
SET /a ENEMY12ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY12EARTHSPELLANIMATION = 0 
SET /a ENEMY12DRAINSPELLANIMATION = 0 
SET /a ENEMY12DEMISPELLANIMATION = 0 
SET /a ENEMY12FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY12FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY12STATUSSPELLANIMATION = 0 
SET /a ENEMY12SELFSPELLANIMATION = 0 
SET /a ENEMY12OFFITEMANIMATION = 0 
SET /a ENEMY12SELFITEMANIMATION = 0 
SET /a ENEMY13FIRESPELLANIMATION = 1 
SET /a ENEMY13ICESPELLANIMATION = 1 
SET /a ENEMY13WATERSPELLANIMATION = 1 
SET /a ENEMY13ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY13EARTHSPELLANIMATION = 0 
SET /a ENEMY13DRAINSPELLANIMATION = 0 
SET /a ENEMY13DEMISPELLANIMATION = 0 
SET /a ENEMY13FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY13FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY13STATUSSPELLANIMATION = 0 
SET /a ENEMY13SELFSPELLANIMATION = 1 
SET /a ENEMY13OFFITEMANIMATION = 1 
SET /a ENEMY13SELFITEMANIMATION = 1 
SET /a ENEMY14FIRESPELLANIMATION = 0 
SET /a ENEMY14ICESPELLANIMATION = 0 
SET /a ENEMY14WATERSPELLANIMATION = 0 
SET /a ENEMY14ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY14EARTHSPELLANIMATION = 0 
SET /a ENEMY14DRAINSPELLANIMATION = 0 
SET /a ENEMY14DEMISPELLANIMATION = 0 
SET /a ENEMY14FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY14FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY14STATUSSPELLANIMATION = 0 
SET /a ENEMY14SELFSPELLANIMATION = 0 
SET /a ENEMY14OFFITEMANIMATION = 0 
SET /a ENEMY14SELFITEMANIMATION = 0 
SET /a ENEMY15FIRESPELLANIMATION = 0 
SET /a ENEMY15ICESPELLANIMATION = 0 
SET /a ENEMY15WATERSPELLANIMATION = 0 
SET /a ENEMY15ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY15EARTHSPELLANIMATION = 0 
SET /a ENEMY15DRAINSPELLANIMATION = 0 
SET /a ENEMY15DEMISPELLANIMATION = 0 
SET /a ENEMY15FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY15FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY15STATUSSPELLANIMATION = 0 
SET /a ENEMY15SELFSPELLANIMATION = 0 
SET /a ENEMY15OFFITEMANIMATION = 0 
SET /a ENEMY15SELFITEMANIMATION = 0 
SET /a ENEMY16FIRESPELLANIMATION = 0 
SET /a ENEMY16ICESPELLANIMATION = 0 
SET /a ENEMY16WATERSPELLANIMATION = 0 
SET /a ENEMY16ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY16EARTHSPELLANIMATION = 0 
SET /a ENEMY16DRAINSPELLANIMATION = 0 
SET /a ENEMY16DEMISPELLANIMATION = 0 
SET /a ENEMY16FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY16FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY16STATUSSPELLANIMATION = 0 
SET /a ENEMY16SELFSPELLANIMATION = 0 
SET /a ENEMY16OFFITEMANIMATION = 1 
SET /a ENEMY16SELFITEMANIMATION = 1 
SET /a ENEMY17FIRESPELLANIMATION = 0 
SET /a ENEMY17ICESPELLANIMATION = 0 
SET /a ENEMY17WATERSPELLANIMATION = 0 
SET /a ENEMY17ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY17EARTHSPELLANIMATION = 0 
SET /a ENEMY17DRAINSPELLANIMATION = 1 
SET /a ENEMY17DEMISPELLANIMATION = 0 
SET /a ENEMY17FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY17FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY17STATUSSPELLANIMATION = 0 
SET /a ENEMY17SELFSPELLANIMATION = 0 
SET /a ENEMY17OFFITEMANIMATION = 0 
SET /a ENEMY17SELFITEMANIMATION = 0 
SET /a ENEMY18FIRESPELLANIMATION = 0 
SET /a ENEMY18ICESPELLANIMATION = 0 
SET /a ENEMY18WATERSPELLANIMATION = 0 
SET /a ENEMY18ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY18EARTHSPELLANIMATION = 0 
SET /a ENEMY18DRAINSPELLANIMATION = 0 
SET /a ENEMY18DEMISPELLANIMATION = 0 
SET /a ENEMY18FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY18FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY18STATUSSPELLANIMATION = 0 
SET /a ENEMY18SELFSPELLANIMATION = 0 
SET /a ENEMY18OFFITEMANIMATION = 1 
SET /a ENEMY18SELFITEMANIMATION = 1 
SET /a ENEMY19FIRESPELLANIMATION = 0 
SET /a ENEMY19ICESPELLANIMATION = 0 
SET /a ENEMY19WATERSPELLANIMATION = 0 
SET /a ENEMY19ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY19EARTHSPELLANIMATION = 0 
SET /a ENEMY19DRAINSPELLANIMATION = 0 
SET /a ENEMY19DEMISPELLANIMATION = 0 
SET /a ENEMY19FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY19FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY19STATUSSPELLANIMATION = 0 
SET /a ENEMY19SELFSPELLANIMATION = 0 
SET /a ENEMY19OFFITEMANIMATION = 1 
SET /a ENEMY19SELFITEMANIMATION = 1 
SET /a ENEMY20FIRESPELLANIMATION = 0 
SET /a ENEMY20ICESPELLANIMATION = 1 
SET /a ENEMY20WATERSPELLANIMATION = 0 
SET /a ENEMY20ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY20EARTHSPELLANIMATION = 0 
SET /a ENEMY20DRAINSPELLANIMATION = 1 
SET /a ENEMY20DEMISPELLANIMATION = 0 
SET /a ENEMY20FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY20FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY20STATUSSPELLANIMATION = 1 
SET /a ENEMY20SELFSPELLANIMATION = 0 
SET /a ENEMY20OFFITEMANIMATION = 0 
SET /a ENEMY20SELFITEMANIMATION = 0 
SET /a ENEMY21FIRESPELLANIMATION = 0 
SET /a ENEMY21ICESPELLANIMATION = 0 
SET /a ENEMY21WATERSPELLANIMATION = 0 
SET /a ENEMY21ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY21EARTHSPELLANIMATION = 0 
SET /a ENEMY21DRAINSPELLANIMATION = 0 
SET /a ENEMY21DEMISPELLANIMATION = 0 
SET /a ENEMY21FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY21FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY21STATUSSPELLANIMATION = 0 
SET /a ENEMY21SELFSPELLANIMATION = 0 
SET /a ENEMY21OFFITEMANIMATION = 0 
SET /a ENEMY21SELFITEMANIMATION = 0 
SET /a ENEMY22FIRESPELLANIMATION = 1 
SET /a ENEMY22ICESPELLANIMATION = 1 
SET /a ENEMY22WATERSPELLANIMATION = 1 
SET /a ENEMY22ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY22EARTHSPELLANIMATION = 0 
SET /a ENEMY22DRAINSPELLANIMATION = 0 
SET /a ENEMY22DEMISPELLANIMATION = 0 
SET /a ENEMY22FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY22FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY22STATUSSPELLANIMATION = 1 
SET /a ENEMY22SELFSPELLANIMATION = 1 
SET /a ENEMY22OFFITEMANIMATION = 1 
SET /a ENEMY22SELFITEMANIMATION = 1 
SET /a ENEMY23FIRESPELLANIMATION = 0 
SET /a ENEMY23ICESPELLANIMATION = 0 
SET /a ENEMY23WATERSPELLANIMATION = 0 
SET /a ENEMY23ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY23EARTHSPELLANIMATION = 0 
SET /a ENEMY23DRAINSPELLANIMATION = 1 
SET /a ENEMY23DEMISPELLANIMATION = 1 
SET /a ENEMY23FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY23FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY23STATUSSPELLANIMATION = 1 
SET /a ENEMY23SELFSPELLANIMATION = 1 
SET /a ENEMY23OFFITEMANIMATION = 0 
SET /a ENEMY23SELFITEMANIMATION = 0 
SET /a ENEMY24FIRESPELLANIMATION = 0 
SET /a ENEMY24ICESPELLANIMATION = 0 
SET /a ENEMY24WATERSPELLANIMATION = 0 
SET /a ENEMY24ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY24EARTHSPELLANIMATION = 0 
SET /a ENEMY24DRAINSPELLANIMATION = 0 
SET /a ENEMY24DEMISPELLANIMATION = 0 
SET /a ENEMY24FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY24FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY24STATUSSPELLANIMATION = 0 
SET /a ENEMY24SELFSPELLANIMATION = 0 
SET /a ENEMY24OFFITEMANIMATION = 1 
SET /a ENEMY24SELFITEMANIMATION = 1 
SET /a ENEMY25FIRESPELLANIMATION = 0 
SET /a ENEMY25ICESPELLANIMATION = 0 
SET /a ENEMY25WATERSPELLANIMATION = 0 
SET /a ENEMY25ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY25EARTHSPELLANIMATION = 0 
SET /a ENEMY25DRAINSPELLANIMATION = 0 
SET /a ENEMY25DEMISPELLANIMATION = 0 
SET /a ENEMY25FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY25FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY25STATUSSPELLANIMATION = 0 
SET /a ENEMY25SELFSPELLANIMATION = 0 
SET /a ENEMY25OFFITEMANIMATION = 0 
SET /a ENEMY25SELFITEMANIMATION = 0 
SET /a ENEMY26FIRESPELLANIMATION = 0 
SET /a ENEMY26ICESPELLANIMATION = 0 
SET /a ENEMY26WATERSPELLANIMATION = 0 
SET /a ENEMY26ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY26EARTHSPELLANIMATION = 0 
SET /a ENEMY26DRAINSPELLANIMATION = 1 
SET /a ENEMY26DEMISPELLANIMATION = 0 
SET /a ENEMY26FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY26FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY26STATUSSPELLANIMATION = 0 
SET /a ENEMY26SELFSPELLANIMATION = 0 
SET /a ENEMY26OFFITEMANIMATION = 0 
SET /a ENEMY26SELFITEMANIMATION = 0 
SET /a ENEMY27FIRESPELLANIMATION = 0 
SET /a ENEMY27ICESPELLANIMATION = 0 
SET /a ENEMY27WATERSPELLANIMATION = 0 
SET /a ENEMY27ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY27EARTHSPELLANIMATION = 0 
SET /a ENEMY27DRAINSPELLANIMATION = 1 
SET /a ENEMY27DEMISPELLANIMATION = 0 
SET /a ENEMY27FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY27FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY27STATUSSPELLANIMATION = 0 
SET /a ENEMY27SELFSPELLANIMATION = 0 
SET /a ENEMY27OFFITEMANIMATION = 0 
SET /a ENEMY27SELFITEMANIMATION = 0 
SET /a ENEMY28FIRESPELLANIMATION = 0 
SET /a ENEMY28ICESPELLANIMATION = 0 
SET /a ENEMY28WATERSPELLANIMATION = 0 
SET /a ENEMY28ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY28EARTHSPELLANIMATION = 0 
SET /a ENEMY28DRAINSPELLANIMATION = 1 
SET /a ENEMY28DEMISPELLANIMATION = 0 
SET /a ENEMY28FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY28FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY28STATUSSPELLANIMATION = 0 
SET /a ENEMY28SELFSPELLANIMATION = 0 
SET /a ENEMY28OFFITEMANIMATION = 0 
SET /a ENEMY28SELFITEMANIMATION = 0 
SET /a ENEMY29FIRESPELLANIMATION = 0 
SET /a ENEMY29ICESPELLANIMATION = 0 
SET /a ENEMY29WATERSPELLANIMATION = 0 
SET /a ENEMY29ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY29EARTHSPELLANIMATION = 0 
SET /a ENEMY29DRAINSPELLANIMATION = 1 
SET /a ENEMY29DEMISPELLANIMATION = 0 
SET /a ENEMY29FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY29FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY29STATUSSPELLANIMATION = 0 
SET /a ENEMY29SELFSPELLANIMATION = 0 
SET /a ENEMY29OFFITEMANIMATION = 0 
SET /a ENEMY29SELFITEMANIMATION = 0 
SET /a ENEMY30FIRESPELLANIMATION = 0 
SET /a ENEMY30ICESPELLANIMATION = 0 
SET /a ENEMY30WATERSPELLANIMATION = 0 
SET /a ENEMY30ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY30EARTHSPELLANIMATION = 0 
SET /a ENEMY30DRAINSPELLANIMATION = 1 
SET /a ENEMY30DEMISPELLANIMATION = 0 
SET /a ENEMY30FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY30FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY30STATUSSPELLANIMATION = 0 
SET /a ENEMY30SELFSPELLANIMATION = 0 
SET /a ENEMY30OFFITEMANIMATION = 0 
SET /a ENEMY30SELFITEMANIMATION = 0 
SET /a ENEMY31FIRESPELLANIMATION = 0 
SET /a ENEMY31ICESPELLANIMATION = 0 
SET /a ENEMY31WATERSPELLANIMATION = 0 
SET /a ENEMY31ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY31EARTHSPELLANIMATION = 0 
SET /a ENEMY31DRAINSPELLANIMATION = 1 
SET /a ENEMY31DEMISPELLANIMATION = 0 
SET /a ENEMY31FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY31FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY31STATUSSPELLANIMATION = 0 
SET /a ENEMY31SELFSPELLANIMATION = 0 
SET /a ENEMY31OFFITEMANIMATION = 0 
SET /a ENEMY31SELFITEMANIMATION = 0 
SET /a ENEMY32FIRESPELLANIMATION = 1 
SET /a ENEMY32ICESPELLANIMATION = 0 
SET /a ENEMY32WATERSPELLANIMATION = 0 
SET /a ENEMY32ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY32EARTHSPELLANIMATION = 1 
SET /a ENEMY32DRAINSPELLANIMATION = 0 
SET /a ENEMY32DEMISPELLANIMATION = 0 
SET /a ENEMY32FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY32FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY32STATUSSPELLANIMATION = 1 
SET /a ENEMY32SELFSPELLANIMATION = 1 
SET /a ENEMY32OFFITEMANIMATION = 1 
SET /a ENEMY32SELFITEMANIMATION = 1 
SET /a ENEMY33FIRESPELLANIMATION = 0 
SET /a ENEMY33ICESPELLANIMATION = 0 
SET /a ENEMY33WATERSPELLANIMATION = 0 
SET /a ENEMY33ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY33EARTHSPELLANIMATION = 0 
SET /a ENEMY33DRAINSPELLANIMATION = 0 
SET /a ENEMY33DEMISPELLANIMATION = 0 
SET /a ENEMY33FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY33FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY33STATUSSPELLANIMATION = 0 
SET /a ENEMY33SELFSPELLANIMATION = 0 
SET /a ENEMY33OFFITEMANIMATION = 0 
SET /a ENEMY33SELFITEMANIMATION = 0 
SET /a ENEMY34FIRESPELLANIMATION = 0 
SET /a ENEMY34ICESPELLANIMATION = 1 
SET /a ENEMY34WATERSPELLANIMATION = 1 
SET /a ENEMY34ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY34EARTHSPELLANIMATION = 0 
SET /a ENEMY34DRAINSPELLANIMATION = 0 
SET /a ENEMY34DEMISPELLANIMATION = 0 
SET /a ENEMY34FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY34FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY34STATUSSPELLANIMATION = 1 
SET /a ENEMY34SELFSPELLANIMATION = 1 
SET /a ENEMY34OFFITEMANIMATION = 1 
SET /a ENEMY34SELFITEMANIMATION = 1 
SET /a ENEMY35FIRESPELLANIMATION = 0 
SET /a ENEMY35ICESPELLANIMATION = 0 
SET /a ENEMY35WATERSPELLANIMATION = 0 
SET /a ENEMY35ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY35EARTHSPELLANIMATION = 0 
SET /a ENEMY35DRAINSPELLANIMATION = 0 
SET /a ENEMY35DEMISPELLANIMATION = 0 
SET /a ENEMY35FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY35FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY35STATUSSPELLANIMATION = 0 
SET /a ENEMY35SELFSPELLANIMATION = 0 
SET /a ENEMY35OFFITEMANIMATION = 1 
SET /a ENEMY35SELFITEMANIMATION = 1 
SET /a ENEMY36FIRESPELLANIMATION = 0 
SET /a ENEMY36ICESPELLANIMATION = 0 
SET /a ENEMY36WATERSPELLANIMATION = 0 
SET /a ENEMY36ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY36EARTHSPELLANIMATION = 0 
SET /a ENEMY36DRAINSPELLANIMATION = 0 
SET /a ENEMY36DEMISPELLANIMATION = 0 
SET /a ENEMY36FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY36FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY36STATUSSPELLANIMATION = 0 
SET /a ENEMY36SELFSPELLANIMATION = 0 
SET /a ENEMY36OFFITEMANIMATION = 0 
SET /a ENEMY36SELFITEMANIMATION = 0 
SET /a ENEMY37FIRESPELLANIMATION = 0 
SET /a ENEMY37ICESPELLANIMATION = 0 
SET /a ENEMY37WATERSPELLANIMATION = 0 
SET /a ENEMY37ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY37EARTHSPELLANIMATION = 0 
SET /a ENEMY37DRAINSPELLANIMATION = 0 
SET /a ENEMY37DEMISPELLANIMATION = 0 
SET /a ENEMY37FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY37FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY37STATUSSPELLANIMATION = 0 
SET /a ENEMY37SELFSPELLANIMATION = 0 
SET /a ENEMY37OFFITEMANIMATION = 1 
SET /a ENEMY37SELFITEMANIMATION = 0 
SET /a ENEMY38FIRESPELLANIMATION = 0 
SET /a ENEMY38ICESPELLANIMATION = 0 
SET /a ENEMY38WATERSPELLANIMATION = 0 
SET /a ENEMY38ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY38EARTHSPELLANIMATION = 0 
SET /a ENEMY38DRAINSPELLANIMATION = 1 
SET /a ENEMY38DEMISPELLANIMATION = 1 
SET /a ENEMY38FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY38FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY38STATUSSPELLANIMATION = 1 
SET /a ENEMY38SELFSPELLANIMATION = 1 
SET /a ENEMY38OFFITEMANIMATION = 0 
SET /a ENEMY38SELFITEMANIMATION = 1 
SET /a ENEMY39FIRESPELLANIMATION = 0 
SET /a ENEMY39ICESPELLANIMATION = 0 
SET /a ENEMY39WATERSPELLANIMATION = 0 
SET /a ENEMY39ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY39EARTHSPELLANIMATION = 0 
SET /a ENEMY39DRAINSPELLANIMATION = 0 
SET /a ENEMY39DEMISPELLANIMATION = 0 
SET /a ENEMY39FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY39FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY39STATUSSPELLANIMATION = 0 
SET /a ENEMY39SELFSPELLANIMATION = 0 
SET /a ENEMY39OFFITEMANIMATION = 1 
SET /a ENEMY39SELFITEMANIMATION = 0 
SET /a ENEMY40FIRESPELLANIMATION = 0 
SET /a ENEMY40ICESPELLANIMATION = 0 
SET /a ENEMY40WATERSPELLANIMATION = 0 
SET /a ENEMY40ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY40EARTHSPELLANIMATION = 0 
SET /a ENEMY40DRAINSPELLANIMATION = 0 
SET /a ENEMY40DEMISPELLANIMATION = 0 
SET /a ENEMY40FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY40FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY40STATUSSPELLANIMATION = 0 
SET /a ENEMY40SELFSPELLANIMATION = 1 
SET /a ENEMY40OFFITEMANIMATION = 0 
SET /a ENEMY40SELFITEMANIMATION = 0 
SET /a ENEMY41FIRESPELLANIMATION = 0 
SET /a ENEMY41ICESPELLANIMATION = 1 
SET /a ENEMY41WATERSPELLANIMATION = 0 
SET /a ENEMY41ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY41EARTHSPELLANIMATION = 0 
SET /a ENEMY41DRAINSPELLANIMATION = 0 
SET /a ENEMY41DEMISPELLANIMATION = 0 
SET /a ENEMY41FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY41FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY41STATUSSPELLANIMATION = 0 
SET /a ENEMY41SELFSPELLANIMATION = 0 
SET /a ENEMY41OFFITEMANIMATION = 1 
SET /a ENEMY41SELFITEMANIMATION = 1 
SET /a ENEMY42FIRESPELLANIMATION = 0 
SET /a ENEMY42ICESPELLANIMATION = 0 
SET /a ENEMY42WATERSPELLANIMATION = 0 
SET /a ENEMY42ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY42EARTHSPELLANIMATION = 0 
SET /a ENEMY42DRAINSPELLANIMATION = 0 
SET /a ENEMY42DEMISPELLANIMATION = 0 
SET /a ENEMY42FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY42FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY42STATUSSPELLANIMATION = 0 
SET /a ENEMY42SELFSPELLANIMATION = 0 
SET /a ENEMY42OFFITEMANIMATION = 1 
SET /a ENEMY42SELFITEMANIMATION = 1 
SET /a ENEMY43FIRESPELLANIMATION = 0 
SET /a ENEMY43ICESPELLANIMATION = 0 
SET /a ENEMY43WATERSPELLANIMATION = 0 
SET /a ENEMY43ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY43EARTHSPELLANIMATION = 0 
SET /a ENEMY43DRAINSPELLANIMATION = 0 
SET /a ENEMY43DEMISPELLANIMATION = 0 
SET /a ENEMY43FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY43FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY43STATUSSPELLANIMATION = 1 
SET /a ENEMY43SELFSPELLANIMATION = 0 
SET /a ENEMY43OFFITEMANIMATION = 1 
SET /a ENEMY43SELFITEMANIMATION = 1 
SET /a ENEMY44FIRESPELLANIMATION = 0 
SET /a ENEMY44ICESPELLANIMATION = 0 
SET /a ENEMY44WATERSPELLANIMATION = 0 
SET /a ENEMY44ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY44EARTHSPELLANIMATION = 0 
SET /a ENEMY44DRAINSPELLANIMATION = 0 
SET /a ENEMY44DEMISPELLANIMATION = 0 
SET /a ENEMY44FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY44FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY44STATUSSPELLANIMATION = 0 
SET /a ENEMY44SELFSPELLANIMATION = 0 
SET /a ENEMY44OFFITEMANIMATION = 1 
SET /a ENEMY44SELFITEMANIMATION = 1 
SET /a ENEMY45FIRESPELLANIMATION = 0 
SET /a ENEMY45ICESPELLANIMATION = 0 
SET /a ENEMY45WATERSPELLANIMATION = 1 
SET /a ENEMY45ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY45EARTHSPELLANIMATION = 0 
SET /a ENEMY45DRAINSPELLANIMATION = 0 
SET /a ENEMY45DEMISPELLANIMATION = 0 
SET /a ENEMY45FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY45FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY45STATUSSPELLANIMATION = 0 
SET /a ENEMY45SELFSPELLANIMATION = 0 
SET /a ENEMY45OFFITEMANIMATION = 1 
SET /a ENEMY45SELFITEMANIMATION = 1 
SET /a ENEMY46FIRESPELLANIMATION = 1 
SET /a ENEMY46ICESPELLANIMATION = 0 
SET /a ENEMY46WATERSPELLANIMATION = 0 
SET /a ENEMY46ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY46EARTHSPELLANIMATION = 0 
SET /a ENEMY46DRAINSPELLANIMATION = 0 
SET /a ENEMY46DEMISPELLANIMATION = 0 
SET /a ENEMY46FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY46FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY46STATUSSPELLANIMATION = 0 
SET /a ENEMY46SELFSPELLANIMATION = 1 
SET /a ENEMY46OFFITEMANIMATION = 0 
SET /a ENEMY46SELFITEMANIMATION = 0 
SET /a ENEMY47FIRESPELLANIMATION = 0 
SET /a ENEMY47ICESPELLANIMATION = 0 
SET /a ENEMY47WATERSPELLANIMATION = 0 
SET /a ENEMY47ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY47EARTHSPELLANIMATION = 0 
SET /a ENEMY47DRAINSPELLANIMATION = 0 
SET /a ENEMY47DEMISPELLANIMATION = 0 
SET /a ENEMY47FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY47FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY47STATUSSPELLANIMATION = 0 
SET /a ENEMY47SELFSPELLANIMATION = 0 
SET /a ENEMY47OFFITEMANIMATION = 1 
SET /a ENEMY47SELFITEMANIMATION = 1 
SET /a ENEMY48FIRESPELLANIMATION = 1 
SET /a ENEMY48ICESPELLANIMATION = 0 
SET /a ENEMY48WATERSPELLANIMATION = 0 
SET /a ENEMY48ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY48EARTHSPELLANIMATION = 0 
SET /a ENEMY48DRAINSPELLANIMATION = 0 
SET /a ENEMY48DEMISPELLANIMATION = 0 
SET /a ENEMY48FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY48FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY48STATUSSPELLANIMATION = 0 
SET /a ENEMY48SELFSPELLANIMATION = 1 
SET /a ENEMY48OFFITEMANIMATION = 1 
SET /a ENEMY48SELFITEMANIMATION = 1 
SET /a ENEMY49FIRESPELLANIMATION = 0 
SET /a ENEMY49ICESPELLANIMATION = 0 
SET /a ENEMY49WATERSPELLANIMATION = 0 
SET /a ENEMY49ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY49EARTHSPELLANIMATION = 0 
SET /a ENEMY49DRAINSPELLANIMATION = 0 
SET /a ENEMY49DEMISPELLANIMATION = 0 
SET /a ENEMY49FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY49FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY49STATUSSPELLANIMATION = 0 
SET /a ENEMY49SELFSPELLANIMATION = 0 
SET /a ENEMY49OFFITEMANIMATION = 1 
SET /a ENEMY49SELFITEMANIMATION = 1 
SET /a ENEMY50FIRESPELLANIMATION = 0 
SET /a ENEMY50ICESPELLANIMATION = 0 
SET /a ENEMY50WATERSPELLANIMATION = 0 
SET /a ENEMY50ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY50EARTHSPELLANIMATION = 0 
SET /a ENEMY50DRAINSPELLANIMATION = 0 
SET /a ENEMY50DEMISPELLANIMATION = 0 
SET /a ENEMY50FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY50FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY50STATUSSPELLANIMATION = 0 
SET /a ENEMY50SELFSPELLANIMATION = 0 
SET /a ENEMY50OFFITEMANIMATION = 1 
SET /a ENEMY50SELFITEMANIMATION = 1 
SET /a ENEMY51FIRESPELLANIMATION = 0 
SET /a ENEMY51ICESPELLANIMATION = 0 
SET /a ENEMY51WATERSPELLANIMATION = 0 
SET /a ENEMY51ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY51EARTHSPELLANIMATION = 0 
SET /a ENEMY51DRAINSPELLANIMATION = 0 
SET /a ENEMY51DEMISPELLANIMATION = 0 
SET /a ENEMY51FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY51FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY51STATUSSPELLANIMATION = 0 
SET /a ENEMY51SELFSPELLANIMATION = 0 
SET /a ENEMY51OFFITEMANIMATION = 1 
SET /a ENEMY51SELFITEMANIMATION = 1 
SET /a ENEMY52FIRESPELLANIMATION = 0 
SET /a ENEMY52ICESPELLANIMATION = 0 
SET /a ENEMY52WATERSPELLANIMATION = 0 
SET /a ENEMY52ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY52EARTHSPELLANIMATION = 0 
SET /a ENEMY52DRAINSPELLANIMATION = 0 
SET /a ENEMY52DEMISPELLANIMATION = 0 
SET /a ENEMY52FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY52FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY52STATUSSPELLANIMATION = 0 
SET /a ENEMY52SELFSPELLANIMATION = 0 
SET /a ENEMY52OFFITEMANIMATION = 0 
SET /a ENEMY52SELFITEMANIMATION = 0 
SET /a ENEMY53FIRESPELLANIMATION = 0 
SET /a ENEMY53ICESPELLANIMATION = 1 
SET /a ENEMY53WATERSPELLANIMATION = 0 
SET /a ENEMY53ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY53EARTHSPELLANIMATION = 0 
SET /a ENEMY53DRAINSPELLANIMATION = 0 
SET /a ENEMY53DEMISPELLANIMATION = 0 
SET /a ENEMY53FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY53FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY53STATUSSPELLANIMATION = 0 
SET /a ENEMY53SELFSPELLANIMATION = 1 
SET /a ENEMY53OFFITEMANIMATION = 0 
SET /a ENEMY53SELFITEMANIMATION = 0 
SET /a ENEMY54FIRESPELLANIMATION = 0 
SET /a ENEMY54ICESPELLANIMATION = 0 
SET /a ENEMY54WATERSPELLANIMATION = 1 
SET /a ENEMY54ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY54EARTHSPELLANIMATION = 0 
SET /a ENEMY54DRAINSPELLANIMATION = 0 
SET /a ENEMY54DEMISPELLANIMATION = 0 
SET /a ENEMY54FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY54FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY54STATUSSPELLANIMATION = 0 
SET /a ENEMY54SELFSPELLANIMATION = 1 
SET /a ENEMY54OFFITEMANIMATION = 0 
SET /a ENEMY54SELFITEMANIMATION = 0 
SET /a ENEMY55FIRESPELLANIMATION = 1 
SET /a ENEMY55ICESPELLANIMATION = 0 
SET /a ENEMY55WATERSPELLANIMATION = 0 
SET /a ENEMY55ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY55EARTHSPELLANIMATION = 0 
SET /a ENEMY55DRAINSPELLANIMATION = 0 
SET /a ENEMY55DEMISPELLANIMATION = 0 
SET /a ENEMY55FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY55FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY55STATUSSPELLANIMATION = 0 
SET /a ENEMY55SELFSPELLANIMATION = 1 
SET /a ENEMY55OFFITEMANIMATION = 0 
SET /a ENEMY55SELFITEMANIMATION = 0 
SET /a ENEMY56FIRESPELLANIMATION = 1 
SET /a ENEMY56ICESPELLANIMATION = 1 
SET /a ENEMY56WATERSPELLANIMATION = 1 
SET /a ENEMY56ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY56EARTHSPELLANIMATION = 0 
SET /a ENEMY56DRAINSPELLANIMATION = 0 
SET /a ENEMY56DEMISPELLANIMATION = 0 
SET /a ENEMY56FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY56FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY56STATUSSPELLANIMATION = 0 
SET /a ENEMY56SELFSPELLANIMATION = 1 
SET /a ENEMY56OFFITEMANIMATION = 0 
SET /a ENEMY56SELFITEMANIMATION = 0 
SET /a ENEMY57FIRESPELLANIMATION = 0 
SET /a ENEMY57ICESPELLANIMATION = 0 
SET /a ENEMY57WATERSPELLANIMATION = 0 
SET /a ENEMY57ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY57EARTHSPELLANIMATION = 0 
SET /a ENEMY57DRAINSPELLANIMATION = 0 
SET /a ENEMY57DEMISPELLANIMATION = 0 
SET /a ENEMY57FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY57FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY57STATUSSPELLANIMATION = 0 
SET /a ENEMY57SELFSPELLANIMATION = 1 
SET /a ENEMY57OFFITEMANIMATION = 1 
SET /a ENEMY57SELFITEMANIMATION = 1 
SET /a ENEMY58FIRESPELLANIMATION = 0 
SET /a ENEMY58ICESPELLANIMATION = 1 
SET /a ENEMY58WATERSPELLANIMATION = 0 
SET /a ENEMY58ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY58EARTHSPELLANIMATION = 0 
SET /a ENEMY58DRAINSPELLANIMATION = 0 
SET /a ENEMY58DEMISPELLANIMATION = 0 
SET /a ENEMY58FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY58FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY58STATUSSPELLANIMATION = 0 
SET /a ENEMY58SELFSPELLANIMATION = 1 
SET /a ENEMY58OFFITEMANIMATION = 1 
SET /a ENEMY58SELFITEMANIMATION = 1 
SET /a ENEMY59FIRESPELLANIMATION = 0 
SET /a ENEMY59ICESPELLANIMATION = 0 
SET /a ENEMY59WATERSPELLANIMATION = 0 
SET /a ENEMY59ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY59EARTHSPELLANIMATION = 0 
SET /a ENEMY59DRAINSPELLANIMATION = 0 
SET /a ENEMY59DEMISPELLANIMATION = 0 
SET /a ENEMY59FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY59FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY59STATUSSPELLANIMATION = 0 
SET /a ENEMY59SELFSPELLANIMATION = 0 
SET /a ENEMY59OFFITEMANIMATION = 0 
SET /a ENEMY59SELFITEMANIMATION = 0 
SET /a ENEMY60FIRESPELLANIMATION = 0 
SET /a ENEMY60ICESPELLANIMATION = 0 
SET /a ENEMY60WATERSPELLANIMATION = 0 
SET /a ENEMY60ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY60EARTHSPELLANIMATION = 0 
SET /a ENEMY60DRAINSPELLANIMATION = 0 
SET /a ENEMY60DEMISPELLANIMATION = 0 
SET /a ENEMY60FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY60FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY60STATUSSPELLANIMATION = 0 
SET /a ENEMY60SELFSPELLANIMATION = 0 
SET /a ENEMY60OFFITEMANIMATION = 0 
SET /a ENEMY60SELFITEMANIMATION = 0 
SET /a ENEMY61FIRESPELLANIMATION = 0 
SET /a ENEMY61ICESPELLANIMATION = 0 
SET /a ENEMY61WATERSPELLANIMATION = 0 
SET /a ENEMY61ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY61EARTHSPELLANIMATION = 0 
SET /a ENEMY61DRAINSPELLANIMATION = 0 
SET /a ENEMY61DEMISPELLANIMATION = 0 
SET /a ENEMY61FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY61FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY61STATUSSPELLANIMATION = 0 
SET /a ENEMY61SELFSPELLANIMATION = 0 
SET /a ENEMY61OFFITEMANIMATION = 0 
SET /a ENEMY61SELFITEMANIMATION = 0 
SET /a ENEMY62FIRESPELLANIMATION = 0 
SET /a ENEMY62ICESPELLANIMATION = 0 
SET /a ENEMY62WATERSPELLANIMATION = 0 
SET /a ENEMY62ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY62EARTHSPELLANIMATION = 0 
SET /a ENEMY62DRAINSPELLANIMATION = 0 
SET /a ENEMY62DEMISPELLANIMATION = 0 
SET /a ENEMY62FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY62FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY62STATUSSPELLANIMATION = 0 
SET /a ENEMY62SELFSPELLANIMATION = 0 
SET /a ENEMY62OFFITEMANIMATION = 0 
SET /a ENEMY62SELFITEMANIMATION = 0 
SET /a ENEMY63FIRESPELLANIMATION = 1 
SET /a ENEMY63ICESPELLANIMATION = 1 
SET /a ENEMY63WATERSPELLANIMATION = 1 
SET /a ENEMY63ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY63EARTHSPELLANIMATION = 0 
SET /a ENEMY63DRAINSPELLANIMATION = 0 
SET /a ENEMY63DEMISPELLANIMATION = 0 
SET /a ENEMY63FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY63FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY63STATUSSPELLANIMATION = 1 
SET /a ENEMY63SELFSPELLANIMATION = 1 
SET /a ENEMY63OFFITEMANIMATION = 1 
SET /a ENEMY63SELFITEMANIMATION = 1 
SET /a ENEMY64FIRESPELLANIMATION = 0 
SET /a ENEMY64ICESPELLANIMATION = 0 
SET /a ENEMY64WATERSPELLANIMATION = 0 
SET /a ENEMY64ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY64EARTHSPELLANIMATION = 0 
SET /a ENEMY64DRAINSPELLANIMATION = 1 
SET /a ENEMY64DEMISPELLANIMATION = 1 
SET /a ENEMY64FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY64FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY64STATUSSPELLANIMATION = 1 
SET /a ENEMY64SELFSPELLANIMATION = 1 
SET /a ENEMY64OFFITEMANIMATION = 1 
SET /a ENEMY64SELFITEMANIMATION = 1 
SET /a ENEMY65FIRESPELLANIMATION = 0 
SET /a ENEMY65ICESPELLANIMATION = 0 
SET /a ENEMY65WATERSPELLANIMATION = 1 
SET /a ENEMY65ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY65EARTHSPELLANIMATION = 1 
SET /a ENEMY65DRAINSPELLANIMATION = 0 
SET /a ENEMY65DEMISPELLANIMATION = 0 
SET /a ENEMY65FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY65FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY65STATUSSPELLANIMATION = 1 
SET /a ENEMY65SELFSPELLANIMATION = 1 
SET /a ENEMY65OFFITEMANIMATION = 1 
SET /a ENEMY65SELFITEMANIMATION = 1 
SET /a ENEMY66FIRESPELLANIMATION = 1 
SET /a ENEMY66ICESPELLANIMATION = 1 
SET /a ENEMY66WATERSPELLANIMATION = 0 
SET /a ENEMY66ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY66EARTHSPELLANIMATION = 0 
SET /a ENEMY66DRAINSPELLANIMATION = 0 
SET /a ENEMY66DEMISPELLANIMATION = 0 
SET /a ENEMY66FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY66FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY66STATUSSPELLANIMATION = 1 
SET /a ENEMY66SELFSPELLANIMATION = 1 
SET /a ENEMY66OFFITEMANIMATION = 1 
SET /a ENEMY66SELFITEMANIMATION = 1 
SET /a ENEMY67FIRESPELLANIMATION = 1 
SET /a ENEMY67ICESPELLANIMATION = 1 
SET /a ENEMY67WATERSPELLANIMATION = 0 
SET /a ENEMY67ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY67EARTHSPELLANIMATION = 0 
SET /a ENEMY67DRAINSPELLANIMATION = 1 
SET /a ENEMY67DEMISPELLANIMATION = 0 
SET /a ENEMY67FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY67FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY67STATUSSPELLANIMATION = 1 
SET /a ENEMY67SELFSPELLANIMATION = 1 
SET /a ENEMY67OFFITEMANIMATION = 1 
SET /a ENEMY67SELFITEMANIMATION = 1 
SET /a ENEMY68FIRESPELLANIMATION = 0 
SET /a ENEMY68ICESPELLANIMATION = 0 
SET /a ENEMY68WATERSPELLANIMATION = 1 
SET /a ENEMY68ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY68EARTHSPELLANIMATION = 1 
SET /a ENEMY68DRAINSPELLANIMATION = 0 
SET /a ENEMY68DEMISPELLANIMATION = 0 
SET /a ENEMY68FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY68FORBIDDEN2SPELLANIMATION = 1 
SET /a ENEMY68STATUSSPELLANIMATION = 1 
SET /a ENEMY68SELFSPELLANIMATION = 1 
SET /a ENEMY68OFFITEMANIMATION = 1 
SET /a ENEMY68SELFITEMANIMATION = 1 
SET /a ENEMY69FIRESPELLANIMATION = 1 
SET /a ENEMY69ICESPELLANIMATION = 1 
SET /a ENEMY69WATERSPELLANIMATION = 0 
SET /a ENEMY69ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY69EARTHSPELLANIMATION = 0 
SET /a ENEMY69DRAINSPELLANIMATION = 0 
SET /a ENEMY69DEMISPELLANIMATION = 1 
SET /a ENEMY69FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY69FORBIDDEN2SPELLANIMATION = 1 
SET /a ENEMY69STATUSSPELLANIMATION = 1 
SET /a ENEMY69SELFSPELLANIMATION = 1 
SET /a ENEMY69OFFITEMANIMATION = 1 
SET /a ENEMY69SELFITEMANIMATION = 1 
SET /a ENEMY70FIRESPELLANIMATION = 1 
SET /a ENEMY70ICESPELLANIMATION = 1 
SET /a ENEMY70WATERSPELLANIMATION = 1 
SET /a ENEMY70ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY70EARTHSPELLANIMATION = 0 
SET /a ENEMY70DRAINSPELLANIMATION = 0 
SET /a ENEMY70DEMISPELLANIMATION = 0 
SET /a ENEMY70FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY70FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY70STATUSSPELLANIMATION = 0 
SET /a ENEMY70SELFSPELLANIMATION = 1 
SET /a ENEMY70OFFITEMANIMATION = 0 
SET /a ENEMY70SELFITEMANIMATION = 0 
SET /a ENEMY71FIRESPELLANIMATION = 0 
SET /a ENEMY71ICESPELLANIMATION = 0 
SET /a ENEMY71WATERSPELLANIMATION = 0 
SET /a ENEMY71ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY71EARTHSPELLANIMATION = 0 
SET /a ENEMY71DRAINSPELLANIMATION = 0 
SET /a ENEMY71DEMISPELLANIMATION = 0 
SET /a ENEMY71FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY71FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY71STATUSSPELLANIMATION = 0 
SET /a ENEMY71SELFSPELLANIMATION = 1 
SET /a ENEMY71OFFITEMANIMATION = 0 
SET /a ENEMY71SELFITEMANIMATION = 0 
SET /a ENEMY72FIRESPELLANIMATION = 0 
SET /a ENEMY72ICESPELLANIMATION = 0 
SET /a ENEMY72WATERSPELLANIMATION = 0 
SET /a ENEMY72ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY72EARTHSPELLANIMATION = 0 
SET /a ENEMY72DRAINSPELLANIMATION = 0 
SET /a ENEMY72DEMISPELLANIMATION = 0 
SET /a ENEMY72FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY72FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY72STATUSSPELLANIMATION = 0 
SET /a ENEMY72SELFSPELLANIMATION = 0 
SET /a ENEMY72OFFITEMANIMATION = 1 
SET /a ENEMY72SELFITEMANIMATION = 1 
SET /a ENEMY73FIRESPELLANIMATION = 0 
SET /a ENEMY73ICESPELLANIMATION = 0 
SET /a ENEMY73WATERSPELLANIMATION = 0 
SET /a ENEMY73ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY73EARTHSPELLANIMATION = 0 
SET /a ENEMY73DRAINSPELLANIMATION = 0 
SET /a ENEMY73DEMISPELLANIMATION = 0 
SET /a ENEMY73FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY73FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY73STATUSSPELLANIMATION = 0 
SET /a ENEMY73SELFSPELLANIMATION = 0 
SET /a ENEMY73OFFITEMANIMATION = 1 
SET /a ENEMY73SELFITEMANIMATION = 1 
SET /a ENEMY74FIRESPELLANIMATION = 0 
SET /a ENEMY74ICESPELLANIMATION = 0 
SET /a ENEMY74WATERSPELLANIMATION = 0 
SET /a ENEMY74ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY74EARTHSPELLANIMATION = 0 
SET /a ENEMY74DRAINSPELLANIMATION = 0 
SET /a ENEMY74DEMISPELLANIMATION = 0 
SET /a ENEMY74FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY74FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY74STATUSSPELLANIMATION = 0 
SET /a ENEMY74SELFSPELLANIMATION = 0 
SET /a ENEMY74OFFITEMANIMATION = 1 
SET /a ENEMY74SELFITEMANIMATION = 1 
SET /a ENEMY75FIRESPELLANIMATION = 0 
SET /a ENEMY75ICESPELLANIMATION = 0 
SET /a ENEMY75WATERSPELLANIMATION = 0 
SET /a ENEMY75ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY75EARTHSPELLANIMATION = 0 
SET /a ENEMY75DRAINSPELLANIMATION = 0 
SET /a ENEMY75DEMISPELLANIMATION = 0 
SET /a ENEMY75FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY75FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY75STATUSSPELLANIMATION = 0 
SET /a ENEMY75SELFSPELLANIMATION = 0 
SET /a ENEMY75OFFITEMANIMATION = 1 
SET /a ENEMY75SELFITEMANIMATION = 1 
SET /a ENEMY76FIRESPELLANIMATION = 0 
SET /a ENEMY76ICESPELLANIMATION = 0 
SET /a ENEMY76WATERSPELLANIMATION = 0 
SET /a ENEMY76ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY76EARTHSPELLANIMATION = 0 
SET /a ENEMY76DRAINSPELLANIMATION = 0 
SET /a ENEMY76DEMISPELLANIMATION = 0 
SET /a ENEMY76FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY76FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY76STATUSSPELLANIMATION = 0 
SET /a ENEMY76SELFSPELLANIMATION = 0 
SET /a ENEMY76OFFITEMANIMATION = 1 
SET /a ENEMY76SELFITEMANIMATION = 1 
SET /a ENEMY77FIRESPELLANIMATION = 0 
SET /a ENEMY77ICESPELLANIMATION = 0 
SET /a ENEMY77WATERSPELLANIMATION = 0 
SET /a ENEMY77ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY77EARTHSPELLANIMATION = 0 
SET /a ENEMY77DRAINSPELLANIMATION = 0 
SET /a ENEMY77DEMISPELLANIMATION = 0 
SET /a ENEMY77FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY77FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY77STATUSSPELLANIMATION = 0 
SET /a ENEMY77SELFSPELLANIMATION = 0 
SET /a ENEMY77OFFITEMANIMATION = 1 
SET /a ENEMY77SELFITEMANIMATION = 1 
SET /a ENEMY78FIRESPELLANIMATION = 0 
SET /a ENEMY78ICESPELLANIMATION = 0 
SET /a ENEMY78WATERSPELLANIMATION = 0 
SET /a ENEMY78ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY78EARTHSPELLANIMATION = 0 
SET /a ENEMY78DRAINSPELLANIMATION = 0 
SET /a ENEMY78DEMISPELLANIMATION = 0 
SET /a ENEMY78FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY78FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY78STATUSSPELLANIMATION = 0 
SET /a ENEMY78SELFSPELLANIMATION = 0 
SET /a ENEMY78OFFITEMANIMATION = 1 
SET /a ENEMY78SELFITEMANIMATION = 1 
SET /a ENEMY79FIRESPELLANIMATION = 0 
SET /a ENEMY79ICESPELLANIMATION = 0 
SET /a ENEMY79WATERSPELLANIMATION = 0 
SET /a ENEMY79ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY79EARTHSPELLANIMATION = 0 
SET /a ENEMY79DRAINSPELLANIMATION = 0 
SET /a ENEMY79DEMISPELLANIMATION = 0 
SET /a ENEMY79FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY79FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY79STATUSSPELLANIMATION = 0 
SET /a ENEMY79SELFSPELLANIMATION = 0 
SET /a ENEMY79OFFITEMANIMATION = 1 
SET /a ENEMY79SELFITEMANIMATION = 1 
SET /a ENEMY80FIRESPELLANIMATION = 0 
SET /a ENEMY80ICESPELLANIMATION = 0 
SET /a ENEMY80WATERSPELLANIMATION = 0 
SET /a ENEMY80ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY80EARTHSPELLANIMATION = 0 
SET /a ENEMY80DRAINSPELLANIMATION = 0 
SET /a ENEMY80DEMISPELLANIMATION = 0 
SET /a ENEMY80FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY80FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY80STATUSSPELLANIMATION = 0 
SET /a ENEMY80SELFSPELLANIMATION = 0 
SET /a ENEMY80OFFITEMANIMATION = 1 
SET /a ENEMY80SELFITEMANIMATION = 1 
SET /a ENEMY81FIRESPELLANIMATION = 0 
SET /a ENEMY81ICESPELLANIMATION = 0 
SET /a ENEMY81WATERSPELLANIMATION = 0 
SET /a ENEMY81ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY81EARTHSPELLANIMATION = 0 
SET /a ENEMY81DRAINSPELLANIMATION = 0 
SET /a ENEMY81DEMISPELLANIMATION = 0 
SET /a ENEMY81FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY81FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY81STATUSSPELLANIMATION = 0 
SET /a ENEMY81SELFSPELLANIMATION = 0 
SET /a ENEMY81OFFITEMANIMATION = 1 
SET /a ENEMY81SELFITEMANIMATION = 1 
SET /a ENEMY82FIRESPELLANIMATION = 0 
SET /a ENEMY82ICESPELLANIMATION = 0 
SET /a ENEMY82WATERSPELLANIMATION = 0 
SET /a ENEMY82ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY82EARTHSPELLANIMATION = 0 
SET /a ENEMY82DRAINSPELLANIMATION = 0 
SET /a ENEMY82DEMISPELLANIMATION = 0 
SET /a ENEMY82FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY82FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY82STATUSSPELLANIMATION = 0 
SET /a ENEMY82SELFSPELLANIMATION = 0 
SET /a ENEMY82OFFITEMANIMATION = 1 
SET /a ENEMY82SELFITEMANIMATION = 1 
SET /a ENEMY83FIRESPELLANIMATION = 0 
SET /a ENEMY83ICESPELLANIMATION = 0 
SET /a ENEMY83WATERSPELLANIMATION = 0 
SET /a ENEMY83ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY83EARTHSPELLANIMATION = 0 
SET /a ENEMY83DRAINSPELLANIMATION = 0 
SET /a ENEMY83DEMISPELLANIMATION = 0 
SET /a ENEMY83FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY83FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY83STATUSSPELLANIMATION = 0 
SET /a ENEMY83SELFSPELLANIMATION = 0 
SET /a ENEMY83OFFITEMANIMATION = 1 
SET /a ENEMY83SELFITEMANIMATION = 1 
SET /a ENEMY84FIRESPELLANIMATION = 0 
SET /a ENEMY84ICESPELLANIMATION = 0 
SET /a ENEMY84WATERSPELLANIMATION = 0 
SET /a ENEMY84ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY84EARTHSPELLANIMATION = 0 
SET /a ENEMY84DRAINSPELLANIMATION = 0 
SET /a ENEMY84DEMISPELLANIMATION = 0 
SET /a ENEMY84FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY84FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY84STATUSSPELLANIMATION = 0 
SET /a ENEMY84SELFSPELLANIMATION = 0 
SET /a ENEMY84OFFITEMANIMATION = 1 
SET /a ENEMY84SELFITEMANIMATION = 1 
SET /a ENEMY85FIRESPELLANIMATION = 1 
SET /a ENEMY85ICESPELLANIMATION = 1 
SET /a ENEMY85WATERSPELLANIMATION = 1 
SET /a ENEMY85ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY85EARTHSPELLANIMATION = 0 
SET /a ENEMY85DRAINSPELLANIMATION = 0 
SET /a ENEMY85DEMISPELLANIMATION = 0 
SET /a ENEMY85FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY85FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY85STATUSSPELLANIMATION = 1 
SET /a ENEMY85SELFSPELLANIMATION = 1 
SET /a ENEMY85OFFITEMANIMATION = 1 
SET /a ENEMY85SELFITEMANIMATION = 1 
SET /a ENEMY86FIRESPELLANIMATION = 0 
SET /a ENEMY86ICESPELLANIMATION = 0 
SET /a ENEMY86WATERSPELLANIMATION = 0 
SET /a ENEMY86ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY86EARTHSPELLANIMATION = 0 
SET /a ENEMY86DRAINSPELLANIMATION = 0 
SET /a ENEMY86DEMISPELLANIMATION = 0 
SET /a ENEMY86FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY86FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY86STATUSSPELLANIMATION = 0 
SET /a ENEMY86SELFSPELLANIMATION = 0 
SET /a ENEMY86OFFITEMANIMATION = 0 
SET /a ENEMY86SELFITEMANIMATION = 0 
SET /a ENEMY87FIRESPELLANIMATION = 1 
SET /a ENEMY87ICESPELLANIMATION = 1 
SET /a ENEMY87WATERSPELLANIMATION = 1 
SET /a ENEMY87ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY87EARTHSPELLANIMATION = 0 
SET /a ENEMY87DRAINSPELLANIMATION = 0 
SET /a ENEMY87DEMISPELLANIMATION = 0 
SET /a ENEMY87FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY87FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY87STATUSSPELLANIMATION = 0 
SET /a ENEMY87SELFSPELLANIMATION = 0 
SET /a ENEMY87OFFITEMANIMATION = 0 
SET /a ENEMY87SELFITEMANIMATION = 0 
SET /a ENEMY88FIRESPELLANIMATION = 0 
SET /a ENEMY88ICESPELLANIMATION = 0 
SET /a ENEMY88WATERSPELLANIMATION = 0 
SET /a ENEMY88ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY88EARTHSPELLANIMATION = 0 
SET /a ENEMY88DRAINSPELLANIMATION = 0 
SET /a ENEMY88DEMISPELLANIMATION = 0 
SET /a ENEMY88FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY88FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY88STATUSSPELLANIMATION = 0 
SET /a ENEMY88SELFSPELLANIMATION = 0 
SET /a ENEMY88OFFITEMANIMATION = 0 
SET /a ENEMY88SELFITEMANIMATION = 0 
SET /a ENEMY89FIRESPELLANIMATION = 0 
SET /a ENEMY89ICESPELLANIMATION = 0 
SET /a ENEMY89WATERSPELLANIMATION = 0 
SET /a ENEMY89ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY89EARTHSPELLANIMATION = 0 
SET /a ENEMY89DRAINSPELLANIMATION = 0 
SET /a ENEMY89DEMISPELLANIMATION = 0 
SET /a ENEMY89FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY89FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY89STATUSSPELLANIMATION = 0 
SET /a ENEMY89SELFSPELLANIMATION = 0 
SET /a ENEMY89OFFITEMANIMATION = 0 
SET /a ENEMY89SELFITEMANIMATION = 0 
SET /a ENEMY90FIRESPELLANIMATION = 0 
SET /a ENEMY90ICESPELLANIMATION = 0 
SET /a ENEMY90WATERSPELLANIMATION = 0 
SET /a ENEMY90ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY90EARTHSPELLANIMATION = 0 
SET /a ENEMY90DRAINSPELLANIMATION = 0 
SET /a ENEMY90DEMISPELLANIMATION = 0 
SET /a ENEMY90FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY90FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY90STATUSSPELLANIMATION = 0 
SET /a ENEMY90SELFSPELLANIMATION = 0 
SET /a ENEMY90OFFITEMANIMATION = 0 
SET /a ENEMY90SELFITEMANIMATION = 0 
SET /a ENEMY91FIRESPELLANIMATION = 0 
SET /a ENEMY91ICESPELLANIMATION = 0 
SET /a ENEMY91WATERSPELLANIMATION = 0 
SET /a ENEMY91ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY91EARTHSPELLANIMATION = 0 
SET /a ENEMY91DRAINSPELLANIMATION = 0 
SET /a ENEMY91DEMISPELLANIMATION = 0 
SET /a ENEMY91FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY91FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY91STATUSSPELLANIMATION = 0 
SET /a ENEMY91SELFSPELLANIMATION = 0 
SET /a ENEMY91OFFITEMANIMATION = 0 
SET /a ENEMY91SELFITEMANIMATION = 0 
SET /a ENEMY92FIRESPELLANIMATION = 0 
SET /a ENEMY92ICESPELLANIMATION = 0 
SET /a ENEMY92WATERSPELLANIMATION = 0 
SET /a ENEMY92ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY92EARTHSPELLANIMATION = 0 
SET /a ENEMY92DRAINSPELLANIMATION = 0 
SET /a ENEMY92DEMISPELLANIMATION = 0 
SET /a ENEMY92FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY92FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY92STATUSSPELLANIMATION = 0 
SET /a ENEMY92SELFSPELLANIMATION = 0 
SET /a ENEMY92OFFITEMANIMATION = 0 
SET /a ENEMY92SELFITEMANIMATION = 0 
SET /a ENEMY93FIRESPELLANIMATION = 0 
SET /a ENEMY93ICESPELLANIMATION = 0 
SET /a ENEMY93WATERSPELLANIMATION = 0 
SET /a ENEMY93ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY93EARTHSPELLANIMATION = 0 
SET /a ENEMY93DRAINSPELLANIMATION = 0 
SET /a ENEMY93DEMISPELLANIMATION = 0 
SET /a ENEMY93FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY93FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY93STATUSSPELLANIMATION = 0 
SET /a ENEMY93SELFSPELLANIMATION = 0 
SET /a ENEMY93OFFITEMANIMATION = 0 
SET /a ENEMY93SELFITEMANIMATION = 0 
SET /a ENEMY94FIRESPELLANIMATION = 0 
SET /a ENEMY94ICESPELLANIMATION = 0 
SET /a ENEMY94WATERSPELLANIMATION = 0 
SET /a ENEMY94ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY94EARTHSPELLANIMATION = 0 
SET /a ENEMY94DRAINSPELLANIMATION = 0 
SET /a ENEMY94DEMISPELLANIMATION = 0 
SET /a ENEMY94FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY94FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY94STATUSSPELLANIMATION = 0 
SET /a ENEMY94SELFSPELLANIMATION = 0 
SET /a ENEMY94OFFITEMANIMATION = 0 
SET /a ENEMY94SELFITEMANIMATION = 0 
SET /a ENEMY95FIRESPELLANIMATION = 0 
SET /a ENEMY95ICESPELLANIMATION = 0 
SET /a ENEMY95WATERSPELLANIMATION = 0 
SET /a ENEMY95ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY95EARTHSPELLANIMATION = 0 
SET /a ENEMY95DRAINSPELLANIMATION = 0 
SET /a ENEMY95DEMISPELLANIMATION = 0 
SET /a ENEMY95FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY95FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY95STATUSSPELLANIMATION = 0 
SET /a ENEMY95SELFSPELLANIMATION = 0 
SET /a ENEMY95OFFITEMANIMATION = 0 
SET /a ENEMY95SELFITEMANIMATION = 0 
SET /a ENEMY96FIRESPELLANIMATION = 0 
SET /a ENEMY96ICESPELLANIMATION = 0 
SET /a ENEMY96WATERSPELLANIMATION = 0 
SET /a ENEMY96ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY96EARTHSPELLANIMATION = 0 
SET /a ENEMY96DRAINSPELLANIMATION = 0 
SET /a ENEMY96DEMISPELLANIMATION = 0 
SET /a ENEMY96FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY96FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY96STATUSSPELLANIMATION = 0 
SET /a ENEMY96SELFSPELLANIMATION = 0 
SET /a ENEMY96OFFITEMANIMATION = 0 
SET /a ENEMY96SELFITEMANIMATION = 0 
SET /a ENEMY97FIRESPELLANIMATION = 1 
SET /a ENEMY97ICESPELLANIMATION = 0 
SET /a ENEMY97WATERSPELLANIMATION = 0 
SET /a ENEMY97ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY97EARTHSPELLANIMATION = 0 
SET /a ENEMY97DRAINSPELLANIMATION = 0 
SET /a ENEMY97DEMISPELLANIMATION = 0 
SET /a ENEMY97FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY97FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY97STATUSSPELLANIMATION = 0 
SET /a ENEMY97SELFSPELLANIMATION = 0 
SET /a ENEMY97OFFITEMANIMATION = 1 
SET /a ENEMY97SELFITEMANIMATION = 1 
SET /a ENEMY98FIRESPELLANIMATION = 0 
SET /a ENEMY98ICESPELLANIMATION = 1 
SET /a ENEMY98WATERSPELLANIMATION = 0 
SET /a ENEMY98ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY98EARTHSPELLANIMATION = 0 
SET /a ENEMY98DRAINSPELLANIMATION = 0 
SET /a ENEMY98DEMISPELLANIMATION = 0 
SET /a ENEMY98FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY98FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY98STATUSSPELLANIMATION = 0 
SET /a ENEMY98SELFSPELLANIMATION = 0 
SET /a ENEMY98OFFITEMANIMATION = 1 
SET /a ENEMY98SELFITEMANIMATION = 1 
SET /a ENEMY99FIRESPELLANIMATION = 0 
SET /a ENEMY99ICESPELLANIMATION = 0 
SET /a ENEMY99WATERSPELLANIMATION = 0 
SET /a ENEMY99ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY99EARTHSPELLANIMATION = 0 
SET /a ENEMY99DRAINSPELLANIMATION = 0 
SET /a ENEMY99DEMISPELLANIMATION = 0 
SET /a ENEMY99FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY99FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY99STATUSSPELLANIMATION = 0 
SET /a ENEMY99SELFSPELLANIMATION = 0 
SET /a ENEMY99OFFITEMANIMATION = 1 
SET /a ENEMY99SELFITEMANIMATION = 1 
SET /a ENEMY100FIRESPELLANIMATION = 0 
SET /a ENEMY100ICESPELLANIMATION = 0 
SET /a ENEMY100WATERSPELLANIMATION = 1 
SET /a ENEMY100ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY100EARTHSPELLANIMATION = 0 
SET /a ENEMY100DRAINSPELLANIMATION = 0 
SET /a ENEMY100DEMISPELLANIMATION = 0 
SET /a ENEMY100FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY100FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY100STATUSSPELLANIMATION = 0 
SET /a ENEMY100SELFSPELLANIMATION = 0 
SET /a ENEMY100OFFITEMANIMATION = 1 
SET /a ENEMY100SELFITEMANIMATION = 1 
SET /a ENEMY101FIRESPELLANIMATION = 0 
SET /a ENEMY101ICESPELLANIMATION = 0 
SET /a ENEMY101WATERSPELLANIMATION = 0 
SET /a ENEMY101ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY101EARTHSPELLANIMATION = 1 
SET /a ENEMY101DRAINSPELLANIMATION = 0 
SET /a ENEMY101DEMISPELLANIMATION = 0 
SET /a ENEMY101FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY101FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY101STATUSSPELLANIMATION = 0 
SET /a ENEMY101SELFSPELLANIMATION = 0 
SET /a ENEMY101OFFITEMANIMATION = 1 
SET /a ENEMY101SELFITEMANIMATION = 1 
SET /a ENEMY102FIRESPELLANIMATION = 0 
SET /a ENEMY102ICESPELLANIMATION = 0 
SET /a ENEMY102WATERSPELLANIMATION = 0 
SET /a ENEMY102ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY102EARTHSPELLANIMATION = 0 
SET /a ENEMY102DRAINSPELLANIMATION = 1 
SET /a ENEMY102DEMISPELLANIMATION = 0 
SET /a ENEMY102FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY102FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY102STATUSSPELLANIMATION = 0 
SET /a ENEMY102SELFSPELLANIMATION = 0 
SET /a ENEMY102OFFITEMANIMATION = 1 
SET /a ENEMY102SELFITEMANIMATION = 1 
SET /a ENEMY103FIRESPELLANIMATION = 0 
SET /a ENEMY103ICESPELLANIMATION = 0 
SET /a ENEMY103WATERSPELLANIMATION = 0 
SET /a ENEMY103ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY103EARTHSPELLANIMATION = 0 
SET /a ENEMY103DRAINSPELLANIMATION = 0 
SET /a ENEMY103DEMISPELLANIMATION = 0 
SET /a ENEMY103FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY103FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY103STATUSSPELLANIMATION = 0 
SET /a ENEMY103SELFSPELLANIMATION = 0 
SET /a ENEMY103OFFITEMANIMATION = 1 
SET /a ENEMY103SELFITEMANIMATION = 1 
SET /a ENEMY104FIRESPELLANIMATION = 1 
SET /a ENEMY104ICESPELLANIMATION = 1 
SET /a ENEMY104WATERSPELLANIMATION = 1 
SET /a ENEMY104ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY104EARTHSPELLANIMATION = 0 
SET /a ENEMY104DRAINSPELLANIMATION = 0 
SET /a ENEMY104DEMISPELLANIMATION = 0 
SET /a ENEMY104FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY104FORBIDDEN2SPELLANIMATION = 0 
SET /a ENEMY104STATUSSPELLANIMATION = 0 
SET /a ENEMY104SELFSPELLANIMATION = 0 
SET /a ENEMY104OFFITEMANIMATION = 0 
SET /a ENEMY104SELFITEMANIMATION = 0 
SET /a ENEMY105FIRESPELLANIMATION = 1 
SET /a ENEMY105ICESPELLANIMATION = 0 
SET /a ENEMY105WATERSPELLANIMATION = 0 
SET /a ENEMY105ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY105EARTHSPELLANIMATION = 0 
SET /a ENEMY105DRAINSPELLANIMATION = 0 
SET /a ENEMY105DEMISPELLANIMATION = 0 
SET /a ENEMY105FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY105FORBIDDEN2SPELLANIMATION = 1 
SET /a ENEMY105STATUSSPELLANIMATION = 1 
SET /a ENEMY105SELFSPELLANIMATION = 1 
SET /a ENEMY105OFFITEMANIMATION = 1 
SET /a ENEMY105SELFITEMANIMATION = 1 
SET /a ENEMY106FIRESPELLANIMATION = 0 
SET /a ENEMY106ICESPELLANIMATION = 0 
SET /a ENEMY106WATERSPELLANIMATION = 0 
SET /a ENEMY106ELECTRICITYSPELLANIMATION = 0 
SET /a ENEMY106EARTHSPELLANIMATION = 0 
SET /a ENEMY106DRAINSPELLANIMATION = 0 
SET /a ENEMY106DEMISPELLANIMATION = 0 
SET /a ENEMY106FORBIDDEN1SPELLANIMATION = 0 
SET /a ENEMY106FORBIDDEN2SPELLANIMATION = 1 
SET /a ENEMY106STATUSSPELLANIMATION = 1 
SET /a ENEMY106SELFSPELLANIMATION = 1 
SET /a ENEMY106OFFITEMANIMATION = 0 
SET /a ENEMY106SELFITEMANIMATION = 0 
SET /a ENEMY89FIRESPELLANIMATION = 1 
SET /a ENEMY89ICESPELLANIMATION = 1 
SET /a ENEMY89WATERSPELLANIMATION = 1 
SET /a ENEMY89ELECTRICITYSPELLANIMATION = 1 
SET /a ENEMY89EARTHSPELLANIMATION = 1 
SET /a ENEMY89DRAINSPELLANIMATION = 1 
SET /a ENEMY89DEMISPELLANIMATION = 1 
SET /a ENEMY89FORBIDDEN1SPELLANIMATION = 1 
SET /a ENEMY89FORBIDDEN2SPELLANIMATION = 1 
SET /a ENEMY89STATUSSPELLANIMATION = 1 
SET /a ENEMY89SELFSPELLANIMATION = 1 
SET /a ENEMY89OFFITEMANIMATION = 1 
SET /a ENEMY89SELFITEMANIMATION = 1 
GOTO :EOF
