SET /a COUNT = 0

:SKILL1
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Rabies Bite
SET ENEMYSKILL%COUNT%NICKNAME=RAB
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL2
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Focus
SET ENEMYSKILL%COUNT%NICKNAME=ENEMYFOC
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=SELFSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL3
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Mule Kick
SET ENEMYSKILL%COUNT%NICKNAME=MULEKICK
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL4
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Neck Whip
SET ENEMYSKILL%COUNT%NICKNAME=NECKWHIP
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL5
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Steal Life
SET ENEMYSKILL%COUNT%NICKNAME=STEALLIFE
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=DRAINSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL6
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Chew
SET ENEMYSKILL%COUNT%NICKNAME=CHEW
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL7
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Troll Smash
SET ENEMYSKILL%COUNT%NICKNAME=TROLLSMASH
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL8
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Quack Attack
SET ENEMYSKILL%COUNT%NICKNAME=QUACKATTACK
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL9
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Piledriver
SET ENEMYSKILL%COUNT%NICKNAME=PILEDRIVER
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL10
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Vampire Bite
SET ENEMYSKILL%COUNT%NICKNAME=VAMBITE
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=DRAINSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL11
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Charge
SET ENEMYSKILL%COUNT%NICKNAME=CHARGE
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL12
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Chomp
SET ENEMYSKILL%COUNT%NICKNAME=CHOMP
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL13
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Steal Oxygen
SET ENEMYSKILL%COUNT%NICKNAME=STEALOX
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=DRAINSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL14
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Quick Attack
SET ENEMYSKILL%COUNT%NICKNAME=ENEMYQATTACK
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL15
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Smash
SET ENEMYSKILL%COUNT%NICKNAME=SMASH
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL16
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Fly
SET ENEMYSKILL%COUNT%NICKNAME=FLY
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=SELFSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL17
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=WMD Attack
SET ENEMYSKILL%COUNT%NICKNAME=WMD
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ICESPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL18
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Suicide Bomb
SET ENEMYSKILL%COUNT%NICKNAME=SUBOMB
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=FORBIDDEN1SPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL19
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Gas Chamber
SET ENEMYSKILL%COUNT%NICKNAME=GASCHAM
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=STATUSSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL20
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Steal Princess
SET ENEMYSKILL%COUNT%NICKNAME=STLPRIN
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL21
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Death Ray
SET ENEMYSKILL%COUNT%NICKNAME=DEATHRAY
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=WATERSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL22
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Throw Gil
SET ENEMYSKILL%COUNT%NICKNAME=ENEMYTHROWGIL
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ICESPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL23
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Mug
SET ENEMYSKILL%COUNT%NICKNAME=ENEMYMUG
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 1
SET ENEMYSKILL%COUNT%DESCRIPTION=
SET ENEMYSKILL%COUNT%ANIMATION=ATTACK
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL24
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Enormous Bullet
SET ENEMYSKILL%COUNT%NICKNAME=BULLET
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=The bullet is enormous. There is no escape
SET ENEMYSKILL%COUNT%ANIMATION=FIRESPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

:SKILL25
SET /a COUNT = %COUNT% + 1
SET ENEMYSKILL%COUNT%NAME=Mighty Guard
SET ENEMYSKILL%COUNT%NICKNAME=EMGUARD
SET /a ENEMYSKILL%COUNT%PROTECTABLE = 0
SET ENEMYSKILL%COUNT%DESCRIPTION=Casts Haste, Protect and Shell on the user
SET ENEMYSKILL%COUNT%ANIMATION=SELFSPELL
SET /a !ENEMYSKILL%COUNT%NICKNAME!ID = %COUNT%

SET /a ENEMYSKILLTOT = %COUNT%