CALL :RANDOMBATTLES
CALL :VALIDLOCATIONS
CALL :SETLOCATIONS
GOTO :EOF


:RANDOMBATTLES
SET /a YCOUNT = 0
:YLOOPRANBATTLE
SET /a YCOUNT = %YCOUNT% + 1
SET /a XCOUNT = 0
:XLOOPRANBATTLE
SET /a XCOUNT = %XCOUNT% + 1
SET TEMP=!%MAP%%YCOUNT%-%XCOUNT%!
SET /a %MAP%%YCOUNT%%XCOUNT%RANBATTLEPOSS = !%TEMP%RANBAT!
IF %XCOUNT% LSS !%MAP%XLIMIT! (
	GOTO :XLOOPRANBATTLE
) ELSE IF %YCOUNT% LSS !%MAP%YLIMIT! (
	GOTO :YLOOPRANBATTLE
)
GOTO :EOF

:VALIDLOCATIONS
SET /a YCOUNT = 0
:VALIDYLOOP
SET /a YCOUNT = %YCOUNT% + 1
SET /a XCOUNT = 0
:VALIDXLOOP
SET /a XCOUNT = %XCOUNT% + 1
SET TEMP=!%MAP%%YCOUNT%-%XCOUNT%!
SET /a %MAP%Y%YCOUNT%X%XCOUNT%VALID = !%TEMP%VALID!
IF %XCOUNT% LSS !%MAP%XLIMIT! (
	GOTO :VALIDXLOOP
) ELSE IF %YCOUNT% LSS !%MAP%YLIMIT! (
	GOTO :VALIDYLOOP
)
GOTO :EOF

:SETLOCATIONS
:SETEXITLOCATIONS
IF !%MAP%EXITNUM! EQU 0 (
	GOTO :SETBUILDINGLOCATIONS
)
SET /a COUNT = 0
:SETEXITLOCATIONSLOOP
SET /a COUNT = %COUNT% + 1
SET %MAP%LOCATION!%MAP%EXIT%COUNT%YCOORD!-!%MAP%EXIT%COUNT%XCOORD!=EXIT
IF %COUNT% LSS !%MAP%EXITNUM! (
	GOTO :SETEXITLOCATIONSLOOP
)
:SETBUILDINGLOCATIONS
IF !%MAP%BUILDINGTOT! EQU 0 (
	GOTO :SETCHESTLOCATIONS
)
SET /a COUNT = 0
:SETBUILDINGLOCATIONSLOOP
SET /a COUNT = %COUNT% + 1
SET /a CELLCOUNT = 0
:SETBUILDINGLOCATIONSLOOP2
SET /a CELLCOUNT = %CELLCOUNT% + 1
SET %MAP%LOCATION!%MAP%BUILDING%COUNT%CELL%CELLCOUNT%!=BUILDING
IF %CELLCOUNT% LSS !%MAP%BUILDING%COUNT%CELLNUM! (
	GOTO :SETBUILDINGLOCATIONSLOOP2
) ELSE IF %COUNT% LSS !%MAP%BUILDINGTOT! (
	GOTO :SETBUILDINGLOCATIONSLOOP
)
:SETCHESTLOCATIONS
IF !%MAP%CHESTTOT! EQU 0 (
	GOTO :SETSPECIALLOCATIONS
)
SET /a COUNT = 0
:SETCHESTLOCATIONSLOOP
SET /a COUNT = %COUNT% + 1
SET %MAP%LOCATION!%MAP%CHEST%COUNT%YCOORD!-!%MAP%CHEST%COUNT%XCOORD!=CHEST
IF %COUNT% LSS !%MAP%CHESTTOT! (
	GOTO :SETCHESTLOCATIONSLOOP
)
:SETSPECIALLOCATIONS
IF !%MAP%SPECIALLOCATIONTOT! EQU 0 (
	GOTO :SETSPECIALBATTLELOCATIONS
)
SET /a COUNT = 0
:SETSPECIALLOCATIONSLOOP
SET /a COUNT = %COUNT% + 1
SET %MAP%LOCATION!%MAP%SPECIALLOCATION%COUNT%YCOORD!-!%MAP%SPECIALLOCATION%COUNT%XCOORD!=SPECIAL
IF %COUNT% LSS !%MAP%SPECIALLOCATIONTOT! (
	GOTO :SETSPECIALLOCATIONSLOOP
)
:SETSPECIALBATTLELOCATIONS
IF !%MAP%SPECIALFIGHTTOT! EQU 0 (
	GOTO :LOCATIONSEND
)
SET /a COUNT = 0
:SETSPECIALBATTLELOCATIONSLOOP
SET /a COUNT = %COUNT% + 1
SET %MAP%LOCATION!%MAP%SPECIALFIGHT%COUNT%YCOORD!-!%MAP%SPECIALFIGHT%COUNT%XCOORD!=SPECIALBATTLE
IF %COUNT% LSS !%MAP%SPECIALFIGHTTOT! (
	GOTO :SETSPECIALBATTLELOCATIONSLOOP
)
:LOCATIONSEND
GOTO :EOF