SET /a COUNT = 0

:TOWN2
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 5
SET /a GURUGROUP%COUNT%ENEMY1 = 1
SET /a GURUGROUP%COUNT%ENEMY2 = 2
SET /a GURUGROUP%COUNT%ENEMY3 = 3
SET /a GURUGROUP%COUNT%ENEMY4 = 4
SET /a GURUGROUP%COUNT%ENEMY5 = 5
SET /a GURUGROUP%COUNT%EXTRAS = 1
SET /a GURUGROUP%COUNT%EXTRA1 = %TRAMPID%

:CAVE
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 7
SET /a GURUGROUP%COUNT%ENEMY1 = 6
SET /a GURUGROUP%COUNT%ENEMY2 = 7
SET /a GURUGROUP%COUNT%ENEMY3 = 8
SET /a GURUGROUP%COUNT%ENEMY4 = 9
SET /a GURUGROUP%COUNT%ENEMY5 = 10
SET /a GURUGROUP%COUNT%ENEMY6 = 11
SET /a GURUGROUP%COUNT%ENEMY7 = 12
SET /a GURUGROUP%COUNT%EXTRAS = 3
SET /a GURUGROUP%COUNT%EXTRA1 = %BOSSIDSTART% + 9
SET /a GURUGROUP%COUNT%EXTRA2 = %BOSSIDSTART% + 11
SET /a GURUGROUP%COUNT%EXTRA3 = %BOSSIDSTART% + 8

:TOWN3
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 4
SET /a GURUGROUP%COUNT%ENEMY1 = 13
SET /a GURUGROUP%COUNT%ENEMY2 = 14
SET /a GURUGROUP%COUNT%ENEMY3 = 15
SET /a GURUGROUP%COUNT%ENEMY4 = 16
SET /a GURUGROUP%COUNT%EXTRAS = 2
SET /a GURUGROUP%COUNT%EXTRA1 = %BOUNCERID%
SET /a GURUGROUP%COUNT%EXTRA2 = %CASINOBOSSID%
::SET /a GURUGROUP%COUNT%EXTRA3 = %BOSSIDSTART% + 14

:MINE1
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 4
SET /a GURUGROUP%COUNT%ENEMY1 = 17
SET /a GURUGROUP%COUNT%ENEMY2 = 18
SET /a GURUGROUP%COUNT%ENEMY3 = 19
SET /a GURUGROUP%COUNT%ENEMY4 = 20
SET /a GURUGROUP%COUNT%EXTRAS = 3
SET /a GURUGROUP%COUNT%EXTRA1 = %BOSSIDSTART% + 41
SET /a GURUGROUP%COUNT%EXTRA2 = %BOSSIDSTART% + 42
SET /a GURUGROUP%COUNT%EXTRA3 = %BOSSIDSTART% + 43

:TOWN4
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 4
SET /a GURUGROUP%COUNT%ENEMY1 = 21
SET /a GURUGROUP%COUNT%ENEMY2 = 22
SET /a GURUGROUP%COUNT%ENEMY3 = 23
SET /a GURUGROUP%COUNT%ENEMY4 = 24
SET /a GURUGROUP%COUNT%EXTRAS = 0

:LAKE1
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 7
SET /a GURUGROUP%COUNT%ENEMY1 = 25
SET /a GURUGROUP%COUNT%ENEMY2 = 26
SET /a GURUGROUP%COUNT%ENEMY3 = 27
SET /a GURUGROUP%COUNT%ENEMY4 = 28
SET /a GURUGROUP%COUNT%ENEMY5 = 29
SET /a GURUGROUP%COUNT%ENEMY6 = 30
SET /a GURUGROUP%COUNT%ENEMY7 = 31
SET /a GURUGROUP%COUNT%EXTRAS = 2
SET /a GURUGROUP%COUNT%EXTRA1 = %BOSSIDSTART% + 45
SET /a GURUGROUP%COUNT%EXTRA2 = %BOSSIDSTART% + 52

:FOREST
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 4
SET /a GURUGROUP%COUNT%ENEMY1 = 32
SET /a GURUGROUP%COUNT%ENEMY2 = 33
SET /a GURUGROUP%COUNT%ENEMY3 = 34
SET /a GURUGROUP%COUNT%ENEMY4 = 35
SET /a GURUGROUP%COUNT%EXTRAS = 2
SET /a GURUGROUP%COUNT%EXTRA1 = %BOSSIDSTART% + 58
SET /a GURUGROUP%COUNT%EXTRA2 = %BOSSIDSTART% + 59

:TOWN6
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 5
SET /a GURUGROUP%COUNT%ENEMY1 = 36
SET /a GURUGROUP%COUNT%ENEMY2 = 37
SET /a GURUGROUP%COUNT%ENEMY3 = 38
SET /a GURUGROUP%COUNT%ENEMY4 = 39
SET /a GURUGROUP%COUNT%ENEMY5 = 40
SET /a GURUGROUP%COUNT%EXTRAS = 0

:HELL
SET /a COUNT = %COUNT% + 1
SET /a GURUGROUP%COUNT%ENEMIES = 5
SET /a GURUGROUP%COUNT%ENEMY1 = 41
SET /a GURUGROUP%COUNT%ENEMY2 = 42
SET /a GURUGROUP%COUNT%ENEMY3 = 43
SET /a GURUGROUP%COUNT%ENEMY4 = 44
SET /a GURUGROUP%COUNT%ENEMY5 = 45
SET /a GURUGROUP%COUNT%EXTRAS = 1
SET /a GURUGROUP%COUNT%EXTRA1 = %BOSSIDSTART% + 60