SET /a MINNAMELENGTH = 5
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0 
SET /a STANDARDSTART = %COUNT%
:ITEM1
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Potion
SET ITEM%COUNT%NICKNAME=POT
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 50 HP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 50
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 50
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 0
SET /a ITEM%COUNT%MAXSKL = 15
SET /a ITEM%COUNT%QUANTDIV = 3
SET /a ITEM%COUNT%EXP = 5
::CALL :ITEMNAMELENGTH

:ITEM2
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Hi-Potion
SET ITEM%COUNT%NICKNAME=HIPOT
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 150 HP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 150
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 250
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 1
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 10
SET /a ITEM%COUNT%MAXSKL = 40
SET /a ITEM%COUNT%QUANTDIV = 8
SET /a ITEM%COUNT%EXP = 30
::CALL :ITEMNAMELENGTH

:ITEM2
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Super Potion
SET ITEM%COUNT%NICKNAME=SUPPOT
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 500 HP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 500
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 750
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 1
SET /a ITEM%COUNT%SHOP4 = 1
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 25
SET /a ITEM%COUNT%MAXSKL = 65
SET /a ITEM%COUNT%QUANTDIV = 11
SET /a ITEM%COUNT%EXP = 40
::CALL :ITEMNAMELENGTH

:ITEM3
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=X-Potion
SET ITEM%COUNT%NICKNAME=XPOT
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 1000 HP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 1000
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 1000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 1
SET /a ITEM%COUNT%MINSKL = 35
SET /a ITEM%COUNT%MAXSKL = 85
SET /a ITEM%COUNT%QUANTDIV = 15
SET /a ITEM%COUNT%EXP = 50
::CALL :ITEMNAMELENGTH

:ITEM4
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Ether
SET ITEM%COUNT%NICKNAME=ETH
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 50 MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 50
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 150
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 20
SET /a ITEM%COUNT%MAXSKL = 50
SET /a ITEM%COUNT%QUANTDIV = 15
SET /a ITEM%COUNT%EXP = 45
::CALL :ITEMNAMELENGTH

:ITEM5
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Hi-Ether
SET ITEM%COUNT%NICKNAME=HIETH
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 150 MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 150
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 500
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 1
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 40
SET /a ITEM%COUNT%MAXSKL = 80
SET /a ITEM%COUNT%QUANTDIV = 25
SET /a ITEM%COUNT%EXP = 80
::CALL :ITEMNAMELENGTH

:ITEM2
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Super Ether
SET ITEM%COUNT%NICKNAME=SUPETH
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Restores 500 MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 500
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 1000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 1
SET /a ITEM%COUNT%SHOP4 = 1
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 55
SET /a ITEM%COUNT%MAXSKL = 100
SET /a ITEM%COUNT%QUANTDIV = 40
SET /a ITEM%COUNT%EXP = 100
::CALL :ITEMNAMELENGTH

:ITEM6
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=X-Ether
SET ITEM%COUNT%DESCRIPTION=Restores 1000 MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET ITEM%COUNT%NICKNAME=XETH
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 1000
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET /a ITEM%COUNT%COST = 1500
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 1
SET /a ITEM%COUNT%MINSKL = 75
SET /a ITEM%COUNT%MAXSKL = 130
SET /a ITEM%COUNT%QUANTDIV = 60
SET /a ITEM%COUNT%EXP = 150
::CALL :ITEMNAMELENGTH

:ITEM7
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Minilixir
SET ITEM%COUNT%DESCRIPTION=Restores a 150 HP and MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET ITEM%COUNT%NICKNAME=MINILIX
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a ITEM%COUNT%EFFECTSNUM = 2
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 150
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET ITEM%COUNT%EFFECT2TYPE=STAT
SET ITEM%COUNT%EFFECT2TARGET=ATTACKER
SET ITEM%COUNT%EFFECT2ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT2ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT2TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT2AMOUNT = 150
SET /a ITEM%COUNT%EFFECT2FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT2TEXT=!ITEM%COUNT%EFFECT2ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT2AMOUNT!^^!
SET /a ITEM%COUNT%COST = 1300
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 1
SET /a ITEM%COUNT%SHOP5 = 1
SET /a ITEM%COUNT%MINSKL = 45
SET /a ITEM%COUNT%MAXSKL = 90
SET /a ITEM%COUNT%QUANTDIV = 50
SET /a ITEM%COUNT%EXP = 100
::CALL :ITEMNAMELENGTH

:ITEM7
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Supelixir
SET ITEM%COUNT%DESCRIPTION=Restores a 500 HP and MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET ITEM%COUNT%NICKNAME=SUPELIX
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a ITEM%COUNT%EFFECTSNUM = 2
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 500
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT1AMOUNT!^^!
SET ITEM%COUNT%EFFECT2TYPE=STAT
SET ITEM%COUNT%EFFECT2TARGET=ATTACKER
SET ITEM%COUNT%EFFECT2ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT2ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT2TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT2AMOUNT = 500
SET /a ITEM%COUNT%EFFECT2FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT2TEXT=!ITEM%COUNT%EFFECT2ATTRIBUTE! has been restored by !ITEM%COUNT%EFFECT2AMOUNT!^^!
SET /a ITEM%COUNT%COST = 2000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 1
SET /a ITEM%COUNT%SHOP5 = 1
SET /a ITEM%COUNT%MINSKL = 60
SET /a ITEM%COUNT%MAXSKL = 130
SET /a ITEM%COUNT%QUANTDIV = 60
SET /a ITEM%COUNT%EXP = 150
::CALL :ITEMNAMELENGTH

:ITEM8
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Elixir
SET ITEM%COUNT%NICKNAME=ELIX
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Fully restores your HP and MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 2
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 99999
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! has been fully restored^^!
SET ITEM%COUNT%EFFECT2TYPE=STAT
SET ITEM%COUNT%EFFECT2TARGET=ATTACKER
SET ITEM%COUNT%EFFECT2ATTRIBUTE=MP
SET ITEM%COUNT%EFFECT2ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT2TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT2AMOUNT = 99999
SET /a ITEM%COUNT%EFFECT2FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT2TEXT=!ITEM%COUNT%EFFECT2ATTRIBUTE! has been fully restored^^!
SET /a ITEM%COUNT%COST = 5000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 90
SET /a ITEM%COUNT%MAXSKL = 190
SET /a ITEM%COUNT%QUANTDIV = 70
SET /a ITEM%COUNT%EXP = 200
::CALL :ITEMNAMELENGTH

:ITEM9
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Eye Drops
SET ITEM%COUNT%NICKNAME=EDROP
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Cures Blind
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=Blind
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 0
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! status has been removed^^!
SET /a ITEM%COUNT%COST = 50
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 1
SET /a ITEM%COUNT%MAXSKL = 15
SET /a ITEM%COUNT%QUANTDIV = 3
SET /a ITEM%COUNT%EXP = 5
::CALL :ITEMNAMELENGTH

:ITEM10
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Echo Screen
SET ITEM%COUNT%NICKNAME=ESCREEN
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Cures Silence
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=Silence
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 0
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! status has been removed^^!
SET /a ITEM%COUNT%COST = 50
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 1
SET /a ITEM%COUNT%MAXSKL = 15
SET /a ITEM%COUNT%QUANTDIV = 3
SET /a ITEM%COUNT%EXP = 5
::CALL :ITEMNAMELENGTH

:ITEM11
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Antidote
SET ITEM%COUNT%NICKNAME=ANT
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Cures Poison
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=Poison
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 0
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! status has been removed^^!
SET /a ITEM%COUNT%COST = 50
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 1
SET /a ITEM%COUNT%MAXSKL = 15
SET /a ITEM%COUNT%QUANTDIV = 3
SET /a ITEM%COUNT%EXP = 5
::CALL :ITEMNAMELENGTH

:ITEM12
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Remedy
SET ITEM%COUNT%NICKNAME=REME
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Cures all negative status ailments
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 4
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=Blind
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 0
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! status has been removed^^!
SET ITEM%COUNT%EFFECT2TYPE=STATUS
SET ITEM%COUNT%EFFECT2TARGET=ATTACKER
SET ITEM%COUNT%EFFECT2ATTRIBUTE=Silence
SET ITEM%COUNT%EFFECT2ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT2TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT2AMOUNT = 0
SET /a ITEM%COUNT%EFFECT2FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT2TEXT=!ITEM%COUNT%EFFECT2ATTRIBUTE! status has been removed^^!
SET ITEM%COUNT%EFFECT3TYPE=STATUS
SET ITEM%COUNT%EFFECT3TARGET=ATTACKER
SET ITEM%COUNT%EFFECT3ATTRIBUTE=Poison
SET ITEM%COUNT%EFFECT3ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT3TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT3AMOUNT = 0
SET /a ITEM%COUNT%EFFECT3FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT3TEXT=!ITEM%COUNT%EFFECT3ATTRIBUTE! status has been removed^^!
SET ITEM%COUNT%EFFECT4TYPE=STATUS
SET ITEM%COUNT%EFFECT4TARGET=ATTACKER
SET ITEM%COUNT%EFFECT4ATTRIBUTE=Slow
SET ITEM%COUNT%EFFECT4ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT4TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT4AMOUNT = 0
SET /a ITEM%COUNT%EFFECT4FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT4TEXT=!ITEM%COUNT%EFFECT4ATTRIBUTE! status has been removed^^!
SET /a ITEM%COUNT%COST = 250
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 50
SET /a ITEM%COUNT%MAXSKL = 90
SET /a ITEM%COUNT%QUANTDIV = 30
SET /a ITEM%COUNT%EXP = 80
::CALL :ITEMNAMELENGTH

:ITEM13
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Auto Life
SET ITEM%COUNT%NICKNAME=ALIFE
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Instant revive after death, full HP and MP
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=Autolife
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 1
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%EFFECT1ATTRIBUTE! status is now active^^!
SET /a ITEM%COUNT%COST = 5000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 125
SET /a ITEM%COUNT%MAXSKL = 1000
SET /a ITEM%COUNT%QUANTDIV = 100
SET /a ITEM%COUNT%EXP = 300
::CALL :ITEMNAMELENGTH

:ITEM14
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Grenade
SET ITEM%COUNT%NICKNAME=GREN
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Deals 50 damage to the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=DEFENDER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = -50
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! did 50 damage^^!
SET /a ITEM%COUNT%COST = 50
SET /a ITEM%COUNT%SHOP1 = 1
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 10
SET /a ITEM%COUNT%MAXSKL = 40
SET /a ITEM%COUNT%QUANTDIV = 10
SET /a ITEM%COUNT%EXP = 30
::CALL :ITEMNAMELENGTH

:ITEM15
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Cluster Bomb
SET ITEM%COUNT%NICKNAME=CBOMB
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Deals 150 damage to the enemy by dropping the C-Bomb
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=DEFENDER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = -150
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! did 150 damage^^!
SET /a ITEM%COUNT%COST = 250
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 30
SET /a ITEM%COUNT%MAXSKL = 60
SET /a ITEM%COUNT%QUANTDIV = 30
SET /a ITEM%COUNT%EXP = 80
::CALL :ITEMNAMELENGTH


:ITEM16
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Holy Hand Grenade
SET ITEM%COUNT%NICKNAME=HHGREN
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Deals 500 damage to the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=DEFENDER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = -500
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! did 500 damage^^!
SET /a ITEM%COUNT%COST = 1000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 1
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = 60
SET /a ITEM%COUNT%MAXSKL = 100
SET /a ITEM%COUNT%QUANTDIV = 50
SET /a ITEM%COUNT%EXP = 100
::CALL :ITEMNAMELENGTH

SET /a STANDARDEND = %COUNT%
SET /a SCROLLSTART = %COUNT%
SET /a STATITEMSTART = %COUNT%

:ITEM16
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=Concrete Donkey
SET ITEM%COUNT%NICKNAME=CONDON
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Deals 2000 damage to the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STAT
SET ITEM%COUNT%EFFECT1TARGET=DEFENDER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=HP
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = -2000
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! did 2000 damage^^!
SET /a ITEM%COUNT%COST = 4000
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 1
SET /a ITEM%COUNT%SHOP5 = 1
SET /a ITEM%COUNT%MINSKL = 60
SET /a ITEM%COUNT%MAXSKL = 100
SET /a ITEM%COUNT%QUANTDIV = 50
SET /a ITEM%COUNT%EXP = 100
::CALL :ITEMNAMELENGTH

SET /a STANDARDEND = %COUNT%
SET /a SCROLLSTART = %COUNT%
SET /a STATITEMSTART = %COUNT%

:ITEMS17-23
SET /a STATSPELLCOUNT = 0
:STATSPELLLOOP
SET /a STATSPELLCOUNT = %STATSPELLCOUNT% + 1
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=!STAT%STATSPELLCOUNT%SPELL! Scroll
SET ITEM%COUNT%NICKNAME=!STAT%STATSPELLCOUNT%SPELL!ITEM
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Casts !STAT%STATSPELLCOUNT%SPELL! on the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = !STAT%STATSPELLCOUNT%EFFECTSNUM!
SET /a EFFECTNUM = !ITEM%COUNT%EFFECTSNUM!
:STATSPELLLOOP1
SET ITEM%COUNT%EFFECT%EFFECTNUM%TYPE=!STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%TYPE!
SET ITEM%COUNT%EFFECT%EFFECTNUM%TARGET=!STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%TARGET!
SET ITEM%COUNT%EFFECT%EFFECTNUM%ATTRIBUTE=!STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%ATTRIBUTE!
SET ITEM%COUNT%EFFECT%EFFECTNUM%ELEMENT=!STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%ELEMENT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%TURNCOUNT = !STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%MINTURNCOUNT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%AMOUNT = !STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%AMOUNT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%FIXEDAMOUNT = !STAT%STATSPELLCOUNT%EFFECT%EFFECTNUM%FIXEDAMOUNT!
SET ITEM%COUNT%EFFECT%EFFECTNUM%TEXT=!ITEM%COUNT%NAME! cast !STAT%STATSPELLCOUNT%SPELL!^^!
SET /a EFFECTNUM = %EFFECTNUM% - 1
IF %EFFECTNUM% GTR 0 (
	GOTO :STATSPELLLOOP1
)
SET /a ITEM%COUNT%COST = !STAT%STATSPELLCOUNT%MPCOST!*10
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = (!STAT%STATSPELLCOUNT%MPCOST!-10)*3
SET /a ITEM%COUNT%MAXSKL = (!STAT%STATSPELLCOUNT%MPCOST!*6)
SET /a ITEM%COUNT%QUANTDIV = !STAT%STATSPELLCOUNT%MPCOST!
SET /a ITEM%COUNT%EXP = !STAT%STATSPELLCOUNT%MPCOST!*3
SET /a ITEM%COUNT%NAMELENGTH = !STAT%STATSPELLCOUNT%NAMELENGTH! + 7
::::CALL :ITEMNAMELENGTH
IF %STATSPELLCOUNT% LSS %STATSPELLTOT% (
	GOTO :STATSPELLLOOP
)
SET /a STATITEMEND = %COUNT%

SET /a OFFITEMSTART = %COUNT%

:ITEMS24-44
SET /a OFFSPELLCOUNT = 0
:OFFSPELLLOOP
SET /a OFFSPELLCOUNT = %OFFSPELLCOUNT% + 1
SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=!OFF%OFFSPELLCOUNT%SPELL! Scroll
SET ITEM%COUNT%NICKNAME=!OFF%OFFSPELLCOUNT%SPELL!ITEM
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Casts !OFF%OFFSPELLCOUNT%SPELL! on the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = !OFF%OFFSPELLCOUNT%EFFECTSNUM!
SET /a EFFECTNUM = !ITEM%COUNT%EFFECTSNUM!
:OFFSPELLLOOP1
SET ITEM%COUNT%EFFECT%EFFECTNUM%TYPE=!OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%TYPE!
SET ITEM%COUNT%EFFECT%EFFECTNUM%TARGET=!OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%TARGET!
SET ITEM%COUNT%EFFECT%EFFECTNUM%ATTRIBUTE=!OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%ATTRIBUTE!
SET ITEM%COUNT%EFFECT%EFFECTNUM%ELEMENT=!OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%ELEMENT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%TURNCOUNT = !OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%MINTURNCOUNT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%AMOUNT = !OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%AMOUNT!
SET /a ITEM%COUNT%EFFECT%EFFECTNUM%FIXEDAMOUNT = !OFF%OFFSPELLCOUNT%EFFECT%EFFECTNUM%FIXEDAMOUNT!
SET ITEM%COUNT%EFFECT%EFFECTNUM%TEXT=!ITEM%COUNT%NAME! cast !OFF%OFFSPELLCOUNT%SPELL!^^!
SET /a EFFECTNUM = %EFFECTNUM% - 1
IF %EFFECTNUM% GTR 0 (
	GOTO :OFFSPELLLOOP1
)
SET /a ITEM%COUNT%COST = !OFF%OFFSPELLCOUNT%MPCOST!*10
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = !OFF%OFFSPELLCOUNT%MPCOST!/5
SET /a ITEM%COUNT%MAXSKL = !OFF%OFFSPELLCOUNT%MPCOST!
SET /a ITEM%COUNT%QUANTDIV = !OFF%OFFSPELLCOUNT%MPCOST!/2
SET /a ITEM%COUNT%EXP = !OFF%OFFSPELLCOUNT%MPCOST!
SET /a ITEM%COUNT%NAMELENGTH = !OFF%OFFSPELLCOUNT%NAMELENGTH! + 7
::::CALL :ITEMNAMELENGTH
IF %OFFSPELLCOUNT% LSS %OFFSPELLTOT% (
	GOTO :OFFSPELLLOOP
)

REM A fix for drain
SET ITEM%DRAINITEMID%EFFECT2TEXT=!ITEM%DRAINITEMID%NAME! healed them by draining HP

SET /a OFFITEMEND = %COUNT%
SET /a SUPPITEMSTART = %COUNT%

:ITEMS45-48
SET /a SUPPSPELLCOUNT = 0
:SUPPSPELLLOOP
SET /a SUPPSPELLCOUNT = %SUPPSPELLCOUNT% + 1

SET /a COUNT=%COUNT%+1
SET ITEM%COUNT%NAME=!SUPP%SUPPSPELLCOUNT%SPELL! Scroll
SET ITEM%COUNT%NICKNAME=!SUPP%SUPPSPELLCOUNT%SPELL!ITEM
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Casts !SUPP%SUPPSPELLCOUNT%SPELL! on you
SET ITEM%COUNT%ANIMATION=SELFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 1
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=ATTACKER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=!SUPP%SUPPSPELLCOUNT%SPELL!
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 3
SET /a ITEM%COUNT%EFFECT1AMOUNT = 1
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! cast !SUPP%SUPPSPELLCOUNT%SPELL!^^!
SET /a ITEM%COUNT%COST = !SUPP%SUPPSPELLCOUNT%MPCOST!*10
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = (!SUPP%SUPPSPELLCOUNT%MPCOST!-10)*3
SET /a ITEM%COUNT%MAXSKL = (!SUPP%SUPPSPELLCOUNT%MPCOST!*4)
SET /a ITEM%COUNT%QUANTDIV = !SUPP%SUPPSPELLCOUNT%MPCOST!
SET /a ITEM%COUNT%EXP = !SUPP%SUPPSPELLCOUNT%MPCOST!*3
SET /a ITEM%COUNT%NAMELENGTH = !SUPP%SUPPSPELLCOUNT%NAMELENGTH! + 7
::::CALL :ITEMNAMELENGTH
IF %SUPPSPELLCOUNT% LSS 4 (
	GOTO :SUPPSPELLLOOP
)

:ITEM49
SET /a SUPPSPELLCOUNT = %SUPPSPELLCOUNT% + 1
SET /a COUNT=%COUNT%+1

SET ITEM%COUNT%NAME=!SUPP%SUPPSPELLCOUNT%SPELL! Scroll
SET ITEM%COUNT%NICKNAME=!SUPP%SUPPSPELLCOUNT%SPELL!ITEM
SET /a !ITEM%COUNT%NICKNAME!ID = %COUNT%
SET ITEM%COUNT%DESCRIPTION=Casts !SUPP%SUPPSPELLCOUNT%SPELL! on the enemy
SET ITEM%COUNT%ANIMATION=OFFITEM
SET /a ITEM%COUNT%EFFECTSNUM = 4
SET ITEM%COUNT%EFFECT1TYPE=STATUS
SET ITEM%COUNT%EFFECT1TARGET=DEFENDER
SET ITEM%COUNT%EFFECT1ATTRIBUTE=%SUPP1SPELL%
SET ITEM%COUNT%EFFECT1ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT1TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT1AMOUNT = 0
SET /a ITEM%COUNT%EFFECT1FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT1TEXT=!ITEM%COUNT%NAME! removed the %SUPP1SPELL% status^^!
SET ITEM%COUNT%EFFECT2TYPE=STATUS
SET ITEM%COUNT%EFFECT2TARGET=DEFENDER
SET ITEM%COUNT%EFFECT2ATTRIBUTE=%SUPP2SPELL%
SET ITEM%COUNT%EFFECT2ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT2TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT2AMOUNT = 0
SET /a ITEM%COUNT%EFFECT2FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT2TEXT=!ITEM%COUNT%NAME! removed the %SUPP2SPELL% status^^!
SET ITEM%COUNT%EFFECT3TYPE=STATUS
SET ITEM%COUNT%EFFECT3TARGET=DEFENDER
SET ITEM%COUNT%EFFECT3ATTRIBUTE=%SUPP3SPELL%
SET ITEM%COUNT%EFFECT3ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT3TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT3AMOUNT = 0
SET /a ITEM%COUNT%EFFECT3FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT3TEXT=!ITEM%COUNT%NAME! removed the %SUPP3SPELL% status^^!
SET ITEM%COUNT%EFFECT4TYPE=STATUS
SET ITEM%COUNT%EFFECT4TARGET=DEFENDER
SET ITEM%COUNT%EFFECT4ATTRIBUTE=%SUPP4SPELL%
SET ITEM%COUNT%EFFECT4ELEMENT=NONE
SET /a ITEM%COUNT%EFFECT4TURNCOUNT = 0
SET /a ITEM%COUNT%EFFECT4AMOUNT = 0
SET /a ITEM%COUNT%EFFECT4FIXEDAMOUNT = 1
SET ITEM%COUNT%EFFECT4TEXT=!ITEM%COUNT%NAME! removed the %SUPP4SPELL% status^^!
SET /a ITEM%COUNT%COST = !SUPP%SUPPSPELLCOUNT%MPCOST!*10
SET /a ITEM%COUNT%SHOP1 = 0
SET /a ITEM%COUNT%SHOP2 = 0
SET /a ITEM%COUNT%SHOP3 = 0
SET /a ITEM%COUNT%SHOP4 = 0
SET /a ITEM%COUNT%SHOP5 = 0
SET /a ITEM%COUNT%MINSKL = (!SUPP%SUPPSPELLCOUNT%MPCOST!-10)*3
SET /a ITEM%COUNT%MAXSKL = (!SUPP%SUPPSPELLCOUNT%MPCOST!*4)
SET /a ITEM%COUNT%QUANTDIV = !SUPP%SUPPSPELLCOUNT%MPCOST!
SET /a ITEM%COUNT%EXP = !SUPP%SUPPSPELLCOUNT%MPCOST!*3
SET /a ITEM%COUNT%NAMELENGTH = !SUPP%SUPPSPELLCOUNT%NAMELENGTH! + 7
::::CALL :ITEMNAMELENGTH

SET /a SUPPITEMEND = %COUNT%
SET /a SCROLLEND = %COUNT%

SET /a ITEMTOTAL = %COUNT%

::CALL :RECORDNAMELENGTHS
CALL :SETNAMELENGTHS

GOTO :EOF

:ITEMNAMELENGTH
SET /a ITEM%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:ITEMNAMELOOPSTART
SET /a ITEM%COUNT%NAMELENGTH += 1
SET TEMP1=!ITEM%COUNT%NAMELENGTH!
SET SUBSTR=!ITEM%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ITEMNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !ITEM%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!ITEM%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ITEMNAMELOOPSTART
	)
)
::ECHO !ITEM%COUNT%NAME! is !ITEM%COUNT%NAMELENGTH! letters long
GOTO :EOF

:RECORDNAMELENGTHS
::To use this, remove all ::s from the "::::CALL :ITEMNAMELENGTH" lines so that the game can calculate the lengths. Then uncomment "CALL :RECORDITEMNAMELENGTHS"
SET /a COUNT = 0
:RECORDLENGTHSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a ITEM%COUNT%NAMELENGTH = !ITEM%COUNT%NAMELENGTH! >> C:\Game\ITEMnamelengths.txt
IF %COUNT% LSS %ITEMTOTAL% (
	GOTO :RECORDLENGTHSLOOP
)
GOTO :EOF

:SETNAMELENGTHS
::This should be copied form the output of :RECORDNAMELENGTHS
SET /a ITEM1NAMELENGTH = 6 
SET /a ITEM2NAMELENGTH = 9 
SET /a ITEM3NAMELENGTH = 12 
SET /a ITEM4NAMELENGTH = 8 
SET /a ITEM5NAMELENGTH = 5 
SET /a ITEM6NAMELENGTH = 8 
SET /a ITEM7NAMELENGTH = 11 
SET /a ITEM8NAMELENGTH = 7 
SET /a ITEM9NAMELENGTH = 9 
SET /a ITEM10NAMELENGTH = 9 
SET /a ITEM11NAMELENGTH = 6 
SET /a ITEM12NAMELENGTH = 9 
SET /a ITEM13NAMELENGTH = 11 
SET /a ITEM14NAMELENGTH = 8 
SET /a ITEM15NAMELENGTH = 6 
SET /a ITEM16NAMELENGTH = 9 
SET /a ITEM17NAMELENGTH = 7 
SET /a ITEM18NAMELENGTH = 12 
SET /a ITEM19NAMELENGTH = 17 
SET /a ITEM20NAMELENGTH = 15 
SET /a ITEM21NAMELENGTH = 12 
SET /a ITEM22NAMELENGTH = 14 
SET /a ITEM23NAMELENGTH = 13 
SET /a ITEM24NAMELENGTH = 11 
SET /a ITEM25NAMELENGTH = 12 
SET /a ITEM26NAMELENGTH = 16 
SET /a ITEM27NAMELENGTH = 11 
SET /a ITEM28NAMELENGTH = 11 
SET /a ITEM29NAMELENGTH = 15 
SET /a ITEM30NAMELENGTH = 14 
SET /a ITEM31NAMELENGTH = 12 
SET /a ITEM32NAMELENGTH = 11 
SET /a ITEM33NAMELENGTH = 15 
SET /a ITEM34NAMELENGTH = 15 
SET /a ITEM35NAMELENGTH = 13 
SET /a ITEM36NAMELENGTH = 13 
SET /a ITEM37NAMELENGTH = 15 
SET /a ITEM38NAMELENGTH = 15 
SET /a ITEM39NAMELENGTH = 15 
SET /a ITEM40NAMELENGTH = 12 
SET /a ITEM41NAMELENGTH = 12 
SET /a ITEM42NAMELENGTH = 11 
SET /a ITEM43NAMELENGTH = 12 
SET /a ITEM44NAMELENGTH = 12 
SET /a ITEM45NAMELENGTH = 13 
SET /a ITEM46NAMELENGTH = 11 
SET /a ITEM47NAMELENGTH = 10 
SET /a ITEM48NAMELENGTH = 15 
SET /a ITEM49NAMELENGTH = 14 
SET /a ITEM50NAMELENGTH = 13 
SET /a ITEM51NAMELENGTH = 13 
SET /a ITEM52NAMELENGTH = 14 
SET /a ITEM53NAMELENGTH = 18 
SET /a ITEM54NAMELENGTH = 16 
SET /a ITEM55NAMELENGTH = 14 
SET /a ITEM56NAMELENGTH = 15 
SET /a ITEM57NAMELENGTH = 14 
SET /a ITEM58NAMELENGTH = 13 
SET /a ITEM59NAMELENGTH = 18 
SET /a ITEM60NAMELENGTH = 15 
SET /a ITEM61NAMELENGTH = 21 
SET /a ITEM62NAMELENGTH = 12 
SET /a ITEM63NAMELENGTH = 16 
SET /a ITEM64NAMELENGTH = 13 
SET /a ITEM65NAMELENGTH = 12 
SET /a ITEM66NAMELENGTH = 14 
SET /a ITEM67NAMELENGTH = 12 
SET /a ITEM68NAMELENGTH = 14 
SET /a ITEM69NAMELENGTH = 13 
GOTO :EOF