SET /a ITEM%BLINDITEMID%CREATECOST = 1
SET /a ITEM%BLINDITEMID%CREATESTONES = 1

SET /a ITEM%SILENCEITEMID%CREATECOST = 1
SET /a ITEM%SILENCEITEMID%CREATESTONES = 1

SET /a ITEM%POISONITEMID%CREATECOST = 1
SET /a ITEM%POISONITEMID%CREATESTONES = 1

SET /a ITEM%SLOWITEMID%CREATECOST = 1
SET /a ITEM%SLOWITEMID%CREATESTONES = 1

SET /a ITEM%SLEEPITEMID%CREATECOST = 1
SET /a ITEM%SLEEPITEMID%CREATESTONES = 2

SET /a ITEM%CONFUSIONITEMID%CREATECOST = 1
SET /a ITEM%CONFUSIONITEMID%CREATESTONES = 2

SET /a ITEM%STOPITEMID%CREATECOST = 1
SET /a ITEM%STOPITEMID%CREATESTONES = 3

SET /a ITEM%FIREITEMID%CREATECOST = 1
SET /a ITEM%FIREITEMID%CREATESTONES = 1

SET /a ITEM%BLIZZARDITEMID%CREATECOST = 1
SET /a ITEM%BLIZZARDITEMID%CREATESTONES = 1

SET /a ITEM%THUNDERITEMID%CREATECOST = 1
SET /a ITEM%THUNDERITEMID%CREATESTONES = 1

SET /a ITEM%WATERITEMID%CREATECOST = 1
SET /a ITEM%WATERITEMID%CREATESTONES = 1

SET /a ITEM%FIRAITEMID%CREATECOST = 1
SET /a ITEM%FIRAITEMID%CREATESTONES = 1

SET /a ITEM%BLIZZARAITEMID%CREATECOST = 1
SET /a ITEM%BLIZZARAITEMID%CREATESTONES = 1

SET /a ITEM%THUNDARAITEMID%CREATECOST = 1
SET /a ITEM%THUNDARAITEMID%CREATESTONES = 1

SET /a ITEM%WATERAITEMID%CREATECOST = 1
SET /a ITEM%WATERAITEMID%CREATESTONES = 1

SET /a ITEM%FIRAGAITEMID%CREATECOST = 1
SET /a ITEM%FIRAGAITEMID%CREATESTONES = 2

SET /a ITEM%BLIZZAGAITEMID%CREATECOST = 1
SET /a ITEM%BLIZZAGAITEMID%CREATESTONES = 2

SET /a ITEM%THUNDAGAITEMID%CREATECOST = 1
SET /a ITEM%THUNDAGAITEMID%CREATESTONES = 2

SET /a ITEM%WATERAGAITEMID%CREATECOST = 1
SET /a ITEM%WATERAGAITEMID%CREATESTONES = 2

SET /a ITEM%DRAINITEMID%CREATECOST = 1
SET /a ITEM%DRAINITEMID%CREATESTONES = 2

SET /a ITEM%QUAKEITEMID%CREATECOST = 1
SET /a ITEM%QUAKEITEMID%CREATESTONES = 2

SET /a ITEM%DEMIITEMID%CREATECOST = 1
SET /a ITEM%DEMIITEMID%CREATESTONES = 2

SET /a ITEM%COMETITEMID%CREATECOST = 1
SET /a ITEM%COMETITEMID%CREATESTONES = 3

SET /a ITEM%FLAREITEMID%CREATECOST = 1
SET /a ITEM%FLAREITEMID%CREATESTONES = 2

SET /a ITEM%FREEZEITEMID%CREATECOST = 1
SET /a ITEM%FREEZEITEMID%CREATESTONES = 2

SET /a ITEM%ZAPITEMID%CREATECOST = 1
SET /a ITEM%ZAPITEMID%CREATESTONES = 2

SET /a ITEM%WAVEITEMID%CREATECOST = 1
SET /a ITEM%WAVEITEMID%CREATESTONES = 2

SET /a ITEM%DRAINARAITEMID%CREATECOST = 1
SET /a ITEM%DRAINARAITEMID%CREATESTONES = 2

SET /a ITEM%QUAKARAITEMID%CREATECOST = 1
SET /a ITEM%QUAKARAITEMID%CREATESTONES = 2

SET /a ITEM%DEMIRAITEMID%CREATECOST = 1
SET /a ITEM%DEMIRAITEMID%CREATESTONES = 2

SET /a ITEM%METEORITEMID%CREATECOST = 1
SET /a ITEM%METEORITEMID%CREATESTONES = 3

SET /a ITEM%INFERNOITEMID%CREATECOST = 1
SET /a ITEM%INFERNOITEMID%CREATESTONES = 2

SET /a ITEM%ARCTICBLASTITEMID%CREATECOST = 1
SET /a ITEM%ARCTICBLASTITEMID%CREATESTONES = 2

SET /a ITEM%LIGHTNINGITEMID%CREATECOST = 1
SET /a ITEM%LIGHTNINGITEMID%CREATESTONES = 2

SET /a ITEM%HYDROPUMPITEMID%CREATECOST = 1
SET /a ITEM%HYDROPUMPITEMID%CREATESTONES = 2

SET /a ITEM%DRAINAGAITEMID%CREATECOST = 1
SET /a ITEM%DRAINAGAITEMID%CREATESTONES = 2

SET /a ITEM%QUAKAGAITEMID%CREATECOST = 1
SET /a ITEM%QUAKAGAITEMID%CREATESTONES = 2

SET /a ITEM%DEMIGAITEMID%CREATECOST = 1
SET /a ITEM%DEMIGAITEMID%CREATESTONES = 2

SET /a ITEM%SHADOWFLAREITEMID%CREATECOST = 1
SET /a ITEM%SHADOWFLAREITEMID%CREATESTONES = 4

SET /a ITEM%FIRESTORMITEMID%CREATECOST = 1
SET /a ITEM%FIRESTORMITEMID%CREATESTONES = 2

SET /a ITEM%ICESTORMITEMID%CREATECOST = 1
SET /a ITEM%ICESTORMITEMID%CREATESTONES = 2

SET /a ITEM%STORMITEMID%CREATECOST = 1
SET /a ITEM%STORMITEMID%CREATESTONES = 2

SET /a ITEM%HYDROCANNONITEMID%CREATECOST = 1
SET /a ITEM%HYDROCANNONITEMID%CREATESTONES = 2

SET /a ITEM%ULTIMAITEMID%CREATECOST = 1
SET /a ITEM%ULTIMAITEMID%CREATESTONES = 4

SET /a ITEM%HASTEITEMID%CREATECOST = 1
SET /a ITEM%HASTEITEMID%CREATESTONES = 1

SET /a ITEM%PROTECTITEMID%CREATECOST = 1
SET /a ITEM%PROTECTITEMID%CREATESTONES = 1

SET /a ITEM%SHELLITEMID%CREATECOST = 1
SET /a ITEM%SHELLITEMID%CREATESTONES = 1

SET /a ITEM%REFLECTITEMID%CREATECOST = 1
SET /a ITEM%REFLECTITEMID%CREATESTONES = 2

SET /a ITEM%DISPELITEMID%CREATECOST = 1
SET /a ITEM%DISPELITEMID%CREATESTONES = 2
