SET /a COUNT = 0

:NONELEDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Non-elemental Kick in the Nuts
SET LIMITBREAK%COUNT%NICKNAME=NONELEDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STEAL
SET LIMITBREAK%COUNT%DESCRIPTION=Deals non-elemental damage to the enemy's plums

:FIREDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Hellfire
SET LIMITBREAK%COUNT%NICKNAME=FIREDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=FIRESPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons a powerful demonic beast that does some sort of firey...thing

:ICEDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Diamond Dust
SET LIMITBREAK%COUNT%NICKNAME=ICEDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=ICESPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons a beautiful ice lass to angrily click her fingers at the enemy

:ELECDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Judgement Bolt
SET LIMITBREAK%COUNT%NICKNAME=ELECDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=ELECTRICITYSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons an old gadgey to use his magnificent rod on the enemy

:WATERDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Tsunami
SET LIMITBREAK%COUNT%NICKNAME=WATERDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=WATERSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons a gigantic Leviathan to bring forth a seismic sea wave

:EARTHDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Anger of the Land
SET LIMITBREAK%COUNT%NICKNAME=EARTHDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=EARTHSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons a gargantuan Titan from the depths of the earth to inefficiently flip the enemy over

:FORBDAM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Mega Flare
SET LIMITBREAK%COUNT%NICKNAME=FORBDAM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=FORBIDDEN2SPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Summons the King of the Dragons to blast the enemy with a beam of pure death

:SUPERSTEALITEM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Super Steal
SET LIMITBREAK%COUNT%NICKNAME=SUPERSTEALITEM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STEAL
SET LIMITBREAK%COUNT%DESCRIPTION=Steals the item that an enemy would be morphed into. Very Useful^^!

:AUTOCATCH
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Super Catch
SET LIMITBREAK%COUNT%NICKNAME=AUTOCATCH
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STEAL
SET LIMITBREAK%COUNT%DESCRIPTION=Never fails to catch an enemy

:REMSTATIMM
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Holy Cleanse
SET LIMITBREAK%COUNT%NICKNAME=REMSTATIMMLIM
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STATUSSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Removes an enemy's status immunities

:INDUCEALLWEAK
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Induce weakness to all elements
SET LIMITBREAK%COUNT%NICKNAME=INDUCEALLWEAK
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STATUSSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Causes an enemy to be weak to all elements

:SUPERSTEALGIL
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Super Gil Steal
SET LIMITBREAK%COUNT%NICKNAME=SUPERSTEALGIL
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STEAL
SET LIMITBREAK%COUNT%DESCRIPTION=Steals a metric f*ck tonne of money

:ALLPOSSTAT
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Super Mighty Guard
SET LIMITBREAK%COUNT%NICKNAME=ALLPOSSTAT
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=SELFSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Gives you loads of positive statuses and effects

:SUPERHEAL
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Supelixir
SET LIMITBREAK%COUNT%NICKNAME=SUPERHEAL
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=SELFITEM
SET LIMITBREAK%COUNT%DESCRIPTION=Fully heals HP, MP, AP and Status Ailments

:INDUCEALLSTATUS
SET /a COUNT = %COUNT% + 1
SET LIMITBREAK%COUNT%NAME=Mind F*ck
SET LIMITBREAK%COUNT%NICKNAME=INDUCEALLSTATUS
SET /a !LIMITBREAK%COUNT%NICKNAME!ID = %COUNT%
SET LIMITBREAK%COUNT%ANIMATION=STATUSSPELL
SET LIMITBREAK%COUNT%DESCRIPTION=Induces all negative status ailments on an enemy

SET /a LIMITBREAKTOT = %COUNT%
