SET /a COUNT = 0
:START

:TOWN1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN1
SET !MAP%COUNT%!NICKNAME=Calm
SET !MAP%COUNT%!DISPLAYNAME=Calm

:TOWN2
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN2
SET !MAP%COUNT%!NICKNAME=Hibelneim
SET !MAP%COUNT%!DISPLAYNAME=Hibelneim

:TOWN3
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN3
SET !MAP%COUNT%!NICKNAME=Dongaga
SET !MAP%COUNT%!DISPLAYNAME=Dongaga

:TOWN4
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN4
SET !MAP%COUNT%!NICKNAME=Woo Thai
SET !MAP%COUNT%!DISPLAYNAME=Woo Thai

:TOWN5
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN5
SET !MAP%COUNT%!NICKNAME=Lost City
SET !MAP%COUNT%!DISPLAYNAME=Lost City

:TOWN6
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=TOWN6
SET !MAP%COUNT%!NICKNAME=Pocket Town
SET !MAP%COUNT%!DISPLAYNAME=Pocket Town

:CAVE1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=CAVE1
SET !MAP%COUNT%!NICKNAME=Cave
SET !MAP%COUNT%!DISPLAYNAME=Cave

:CAVE1LVL2
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=CAVE1LVL2
SET !MAP%COUNT%!NICKNAME=Cave Level 2
SET !MAP%COUNT%!DISPLAYNAME=Cave

:CASTLE
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=CASTLE
SET !MAP%COUNT%!NICKNAME=Castle
SET !MAP%COUNT%!DISPLAYNAME=Castle

:CASTLE2
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=CASTLE2
SET !MAP%COUNT%!NICKNAME=Castle Basement
SET !MAP%COUNT%!DISPLAYNAME=Castle

:CASTLE3
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=CASTLE3
SET !MAP%COUNT%!NICKNAME=Castle Library
SET !MAP%COUNT%!DISPLAYNAME=Castle

:MINE1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=MINE1
SET !MAP%COUNT%!NICKNAME=Mine
SET !MAP%COUNT%!DISPLAYNAME=Mine

:MINE2
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=MINE2
SET !MAP%COUNT%!NICKNAME=Mine Cart Roller Coaster
SET !MAP%COUNT%!DISPLAYNAME=Mine

:MINE3
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=MINE3
SET !MAP%COUNT%!NICKNAME=Mine - Dwarven Territory
SET !MAP%COUNT%!DISPLAYNAME=Mine

:LAKE1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=LAKE1
SET !MAP%COUNT%!NICKNAME=Lake
SET !MAP%COUNT%!DISPLAYNAME=Lake

:LAKE2
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=LAKE2
SET !MAP%COUNT%!NICKNAME=Secret Lake Passage
SET !MAP%COUNT%!DISPLAYNAME=Lake

:LAKE3
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=LAKE3
SET !MAP%COUNT%!NICKNAME=Secret Lake Passage 2
SET !MAP%COUNT%!DISPLAYNAME=Lake

:LAKE4
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=LAKE4
SET !MAP%COUNT%!NICKNAME=Land of Nightmares
SET !MAP%COUNT%!DISPLAYNAME=Nightmares

:LAKEPALACE
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=LAKEPALACE
SET !MAP%COUNT%!NICKNAME=Sea King's Palace
SET !MAP%COUNT%!DISPLAYNAME=Palace

:FOREST1MIST1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=FOREST1MIST1
SET !MAP%COUNT%!NICKNAME=Snoozing Forest
SET !MAP%COUNT%!DISPLAYNAME=Forest

:FOREST1MIST0
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=FOREST1MIST0
SET !MAP%COUNT%!NICKNAME=Evil Forest
SET !MAP%COUNT%!DISPLAYNAME=Forest

:HELL1
SET /a COUNT = %COUNT% + 1
SET MAP%COUNT%=HELL1
SET !MAP%COUNT%!NICKNAME=Hell
SET !MAP%COUNT%!DISPLAYNAME=Hell

GOTO :EOF
