CALL :SETUPTERRAIN
CALL :SETUPOBJECTS
CALL :SETUPMAPS
GOTO :EOF

:SETUPTERRAIN
SET GRASSA=°°°°°
SET GRASSB=°°°°°
SET GRASSC=°°°°°
SET /a GRASSRANBAT = 1
SET /a GRASSVALID = 1
SET MINE1A=±±±±±
SET MINE1B=±±±±±
SET MINE1C=±±±±±
SET /a MINE1RANBAT = 1
SET /a MINE1VALID = 1
SET PATH1A=     
SET PATH1B=     
SET PATH1C=     
SET /a PATH1RANBAT = 0
SET /a PATH1VALID = 1
SET WALL1A=ªªªªª
SET WALL1B=ªªªªª
SET WALL1C=ªªªªª
SET /a WALL1RANBAT = 0
SET /a WALL1VALID = 0
SET WALL2A=ÂÄÄÄÁ
SET WALL2B=ÁÄÂÄÄ
SET WALL2C=ÄÄÁÄÂ
SET /a WALL2RANBAT = 0
SET /a WALL2VALID = 0
SET WALL3A=¾ ¾ ¾
SET WALL3B= ¾ ¾ 
SET WALL3C=¾ ¾ ¾
SET /a WALL3RANBAT = 0
SET /a WALL3VALID = 0
SET EXITRIGHTA=^> ^> ^>
SET EXITRIGHTB=^> ^> ^>
SET EXITRIGHTC=^> ^> ^>
SET /a EXITRIGHTRANBAT = 1
SET /a EXITRIGHTVALID = 1
SET EXITLEFTA=^< ^< ^<
SET EXITLEFTB=^< ^< ^<
SET EXITLEFTC=^< ^< ^<
SET /a EXITLEFTRANBAT = 1
SET /a EXITLEFTVALID = 1
SET LADDERA= ÃÄ´ 
SET LADDERB= ÃÄ´ 
SET LADDERC= ÃÄ´ 
SET /a LADDERRANBAT = 0
SET /a LADDERVALID = 1
SET MIST1A=²²²²²
SET MIST1B=²²²²²
SET MIST1C=²²²²²
SET /a MIST1RANBAT = 0
SET /a MIST1VALID = 1
SET MIST2A=°°°°°
SET MIST2B=°°°°°
SET MIST2C=°°°°°
SET /a MIST2RANBAT = 0
SET /a MIST2VALID = 1
SET WATERA=°°°°°
SET WATERB=°°°°°
SET WATERC=°°°°°
SET /a WATERRANBAT = 1
SET /a WATERVALID = 1
SET WATEREDGEA=     
SET WATEREDGEB=~~~~~
SET WATEREDGEC=°°°°°
SET /a WATEREDGERANBAT = 0
SET /a WATEREDGEVALID = 1
::SET PLANT1A= *   
::SET PLANT1B= À´  
::SET PLANT1C= ÚÁ¿ 
::SET /a PLANT1RANBAT = 0
::SET /a PLANT1VALID = 0
::SET PLANT1A=   * 
::SET PLANT1B=  ÃÙ 
::SET PLANT1C= ÚÁ¿ 
::SET /a PLANT1RANBAT = 0
::SET /a PLANT1VALID = 0
SET PLANT1A=  *  
SET PLANT1B=  ³  
SET PLANT1C= ÚÁ¿ 
SET /a PLANT1RANBAT = 0
SET /a PLANT1VALID = 0
SET CARPETLEFTA=º±±±±
SET CARPETLEFTB=º±±Ï±
SET CARPETLEFTC=º±±±±
SET /a CARPETLEFTRANBAT = 0
SET /a CARPETLEFTVALID = 1
SET CARPETRIGHTA=±±±±º
SET CARPETRIGHTB=±Ï±±º
SET CARPETRIGHTC=±±±±º
SET /a CARPETRIGHTRANBAT = 0
SET /a CARPETRIGHTVALID = 1
SET FLOORA=°°°°°
SET FLOORB=°°°°°
SET FLOORC=°°°°°
SET /a FLOORRANBAT = 0
SET /a FLOORVALID = 1
SET LAVA1A=~ ~ ~
SET LAVA1B= ~ ~ 
SET LAVA1C=~ ~ ~
SET /a LAVA1RANBAT = 0
SET /a LAVA1VALID = 0
SET HELL1A=°°°°°
SET HELL1B=°°°°°
SET HELL1C=°°°°°
SET /a HELL1RANBAT = 1
SET /a HELL1VALID = 1
SET EDGE=ÍÍÍÍÍ
GOTO :EOF

:SETUPOBJECTS
SET TRACKUPDOWNA= ÃÄ´ 
SET TRACKUPDOWNB= ÃÄ´ 
SET TRACKUPDOWNC= ÃÄ´ 
SET /a TRACKUPDOWNRANBAT = 0
SET /a TRACKUPDOWNVALID = 1

SET TRACKLEFTRIGHTA=ÂÂÂÂÂ
SET TRACKLEFTRIGHTB=³³³³³
SET TRACKLEFTRIGHTC=ÁÁÁÁÁ
SET /a TRACKLEFTRIGHTRANBAT = 0
SET /a TRACKLEFTRIGHTVALID = 1

SET TRACKTOPLEFTA= ÚÄÂÂ
SET TRACKTOPLEFTB= ÃÄ´³
SET TRACKTOPLEFTC= ÃÄÅÁ
SET /a TRACKTOPLEFTRANBAT = 0
SET /a TRACKTOPLEFTVALID = 1

SET TRACKTOPRIGHTA=ÂÂÄ¿ 
SET TRACKTOPRIGHTB=³ÃÄ´ 
SET TRACKTOPRIGHTC=ÁÅÄ´ 
SET /a TRACKTOPRIGHTRANBAT = 0
SET /a TRACKTOPRIGHTVALID = 1

SET TRACKBOTLEFTA= ÃÄÅÂ
SET TRACKBOTLEFTB= ÃÄ´³
SET TRACKBOTLEFTC= ÀÄÁÁ
SET /a TRACKBOTLEFTRANBAT = 0
SET /a TRACKBOTLEFTVALID = 1

SET TRACKBOTRIGHTA=ÂÅÄ´ 
SET TRACKBOTRIGHTB=³ÃÄ´ 
SET TRACKBOTRIGHTC=ÁÁÄÙ 
SET /a TRACKBOTRIGHTRANBAT = 0
SET /a TRACKBOTRIGHTVALID = 1

SET BOOKCASETOPLEFTA=ÚÄÄÄÄ
SET BOOKCASETOPLEFTB=³³±\ 
SET BOOKCASETOPLEFTC=ÃÄÄÄÄ

SET BOOKCASEBOTLEFTA=³   ±
SET BOOKCASEBOTLEFTB=³° Ý±
SET BOOKCASEBOTLEFTC=ÀÄÄÄÄ

SET BOOKCASETOPRIGHTA=ÄÄÄÄ¿
SET BOOKCASETOPRIGHTB=² /°³
SET BOOKCASETOPRIGHTC=ÄÄÄÄ´

SET BOOKCASEBOTRIGHTA=    ³
SET BOOKCASEBOTRIGHTB= /²²³
SET BOOKCASEBOTRIGHTC=ÄÄÄÄÙ

SET MINECARTA=ÃÄÄÄ´
SET MINECARTB=³   ³
SET MINECARTC=ÀOÄOÙ

GOTO :EOF

:SETUPMAPS
SET MAPSPATH=%INITIALRESOURCEPATH%\Maps
CALL "%MAPSPATH%\mine1cartsetup.bat"
CALL "%MAPSPATH%\mine2cartsetup.bat"
CALL "%MAPSPATH%\mine2setup.bat"
CALL "%MAPSPATH%\mine3cartsetup.bat"
GOTO :EOF
