SET OPTION1NAME=Persistent Auto Battle
SET OPTION1VAR=PERSISTENTAUTOBATTLE
SET OPTION1DESCRIPTION1=Turning this on will mean that if auto battle was on at the end
SET OPTION1DESCRIPTION2=of the last battle then it'll be on at the start of the next
SET OPTION2NAME=Memory Auto Battle
SET OPTION2VAR=MEMORYAUTOBATTLE
SET OPTION2DESCRIPTION1=Auto battle will repeat your last move if this is turned on.
SET OPTION2DESCRIPTION2=If it's turned off then auto battle will just attack
SET OPTION3NAME=Music
SET OPTION3VAR=MUSICENABLED
SET OPTION3DESCRIPTION1=Turns the music or and off
SET OPTION3DESCRIPTION2=Obviously...
SET OPTION4NAME=Sound Effects
SET OPTION4VAR=SFXENABLED
SET OPTION4DESCRIPTION1=Spells, Skills, Chests etc.
SET OPTION4DESCRIPTION2=Toggling this on will play a random sound effect
SET OPTION5NAME=Explicit mode
SET OPTION5VAR=EXPLICIT
SET OPTION5DESCRIPTION1=With explicit mode turned on, the game is a bit more...sweary
SET OPTION5DESCRIPTION2=THIS WILL SWEAR WHEN TURNED ON^^!
SET OPTION6NAME=Animations
SET OPTION6VAR=ANIMATIONENABLED
SET OPTION6DESCRIPTION1=Battle animations are cool but they increase loading times slightly.
SET OPTION6DESCRIPTION2=If battles are too slow for you, try turning these off.
SET OPTION7NAME=Automatic Cutscene Progression
SET OPTION7VAR=CUTSCENEPROGRESSION
SET OPTION7DESCRIPTION1=With this turned off you'll need to press 1 to advance text in cutscenes.
SET OPTION7DESCRIPTION2=When it's turned on they progress automatically unless you intervene
SET /a OPTIONSMENUTOT = 7

SET SWEAR1=Dog Shit Taco
SET SWEAR2=Blood Dripped Frozen Tampon Popsickle
SET SWEAR3=Fuck Shit Cock Ass Titty Boner Bitch Mom's Pussy God's Butthole Barbara Streisand
SET SWEAR4=Butthole, Titties, Balls. Cocksucker
SET SWEAR5=Ginger retard. Ass licker dick face
SET SWEAR6=Asshole, Pussy Asshole
SET SWEAR7=Spoodge, Balls, Bloody Vaginal Belch
SET SWEAR8=Tampon, Tampon Dick Shit
SET SWEAR9=Crap filled vagina
SET SWEAR10=Piss out your ass right onto Kyle's mom's fat fucking jew face
SET SWEAR11=Jizz farmer, Dick sneeze, Titty sprinkles
SET /a SWEARTOT = 11