SET /a MINNAMELENGTH = 12
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0

:PICKAXE1
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Wooden Pickaxe
SET /a PICKAXE%COUNT%COST = 100
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %CHEWID%
CALL :PICKAXENAMELENGTH

:PICKAXE2
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Stone Pickaxe
SET /a PICKAXE%COUNT%COST = 250
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %CHARGEID%
CALL :PICKAXENAMELENGTH

:PICKAXE3
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Iron Pickaxe
SET /a PICKAXE%COUNT%COST = 750
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %CHOMPID%
CALL :PICKAXENAMELENGTH

:PICKAXE4
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Steel Pickaxe
SET /a PICKAXE%COUNT%COST = 2500
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %ENEMYQATTACKID%
CALL :PICKAXENAMELENGTH

:PICKAXE5
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Diamond Pickaxe
SET /a PICKAXE%COUNT%COST = 5000
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %SMASHID%
CALL :PICKAXENAMELENGTH

:PICKAXE6
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Mythril Pickaxe
SET /a PICKAXE%COUNT%COST = 10000
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %WMDID%
CALL :PICKAXENAMELENGTH

:PICKAXE6
SET /a COUNT = %COUNT% + 1
SET PICKAXE%COUNT%NAME=Adamantium Pickaxe
SET /a PICKAXE%COUNT%COST = 20000
SET /a PICKAXE%COUNT%SELL = !PICKAXE%COUNT%COST!
SET /a PICKAXE%COUNT%STR = %COUNT%*10
SET /a PICKAXE%COUNT%SKL = %COUNT%*10
SET /a PICKAXE%COUNT%PER = %COUNT%*10
SET /a PICKAXE%COUNT%ENEMYSKILL = %DEATHRAYID%
CALL :PICKAXENAMELENGTH

SET /a PICKAXETOT = %COUNT%
GOTO :EOF


:PICKAXENAMELENGTH
SET /a PICKAXE%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:PICKAXENAMELOOPSTART
SET /a PICKAXE%COUNT%NAMELENGTH += 1
SET TEMP1=!PICKAXE%COUNT%NAMELENGTH!
SET SUBSTR=!PICKAXE%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :PICKAXENAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !PICKAXE%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!PICKAXE%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :PICKAXENAMELOOPSTART
	)
)
GOTO :EOF
