SET /a MINNAMELENGTH = 4
::SET /a MINNAMELENGTH = 1
SET /a COUNT=0
:CURESPELLSTATS
SET /a COUNT=%COUNT%+1
SET REST%COUNT%SPELL=Cure
SET REST%COUNT%DESCRIPTION=Restores your HP by a small amount
SET REST%COUNT%ANIMATION=SELFSPELL
SET /a !REST%COUNT%SPELL!ID = %COUNT%
SET /a REST%COUNT%ACCURACY = 9999
SET /a REST%COUNT%MPCOST = 10
SET /a REST%COUNT%UNLOCKLVL = 1
SET REST%COUNT%PREREQUISITE=NONE
SET /a REST%COUNT%REFLECTABLE = 0
SET /a REST%COUNT%EFFECTSNUM = 1
SET REST%COUNT%EFFECT1ELEMENT=NONE
SET REST%COUNT%EFFECT1TYPE=STAT
SET REST%COUNT%EFFECT1ATTRIBUTE=HP
SET REST%COUNT%EFFECT1TARGET=ATTACKER
SET /a REST%COUNT%EFFECT1AMOUNT = 5
SET /a REST%COUNT%EFFECT1FIXEDAMOUNT = 0
SET /a REST%COUNT%EFFECT1MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT1MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT1PLAYERTEXT=Your spell did
CALL :SPELLNAMELENGTH


:CURASPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a REST2ID = 2
SET REST%COUNT%SPELL=Cura
SET REST%COUNT%DESCRIPTION=Restores your HP by a moderate amount
SET REST%COUNT%ANIMATION=SELFSPELL
SET /a !REST%COUNT%SPELL!ID = %COUNT%
SET /a REST%COUNT%ACCURACY = 9999
SET /a REST%COUNT%MPCOST = 25
SET /a REST%COUNT%UNLOCKLVL = 5
SET REST%COUNT%PREREQUISITE=Cure
SET /a REST%COUNT%REFLECTABLE = 0
SET /a REST%COUNT%EFFECTSNUM = 1
SET REST%COUNT%EFFECT1ELEMENT=NONE
SET REST%COUNT%EFFECT1TYPE=STAT
SET REST%COUNT%EFFECT1ATTRIBUTE=HP
SET REST%COUNT%EFFECT1TARGET=ATTACKER
SET /a REST%COUNT%EFFECT1AMOUNT = 10
SET /a REST%COUNT%EFFECT1FIXEDAMOUNT = 0
SET /a REST%COUNT%EFFECT1MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT1MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT1PLAYERTEXT=Your spell did
CALL :SPELLNAMELENGTH


:CURAGASPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a REST3ID = 3
SET REST%COUNT%SPELL=Curaga
SET REST%COUNT%DESCRIPTION=Restores your HP by a large amount
SET REST%COUNT%ANIMATION=SELFSPELL
SET /a !REST%COUNT%SPELL!ID = %COUNT%
SET /a REST%COUNT%ACCURACY = 9999
SET /a REST%COUNT%MPCOST = 60
SET /a REST%COUNT%UNLOCKLVL = 15
SET REST%COUNT%PREREQUISITE=Cura
SET /a REST%COUNT%REFLECTABLE = 0
SET /a REST%COUNT%EFFECTSNUM = 1
SET REST%COUNT%EFFECT1ELEMENT=NONE
SET REST%COUNT%EFFECT1TYPE=STAT
SET REST%COUNT%EFFECT1ATTRIBUTE=HP
SET REST%COUNT%EFFECT1TARGET=ATTACKER
SET /a REST%COUNT%EFFECT1AMOUNT = 20
SET /a REST%COUNT%EFFECT1FIXEDAMOUNT = 0
SET /a REST%COUNT%EFFECT1MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT1MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT1PLAYERTEXT=Your spell did
CALL :SPELLNAMELENGTH


:REGENSPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a REST4ID = 4
SET REST%COUNT%SPELL=Regen
SET REST%COUNT%DESCRIPTION=Restores your HP by a small amount at the start of the round
SET REST%COUNT%ANIMATION=SELFSPELL
SET /a !REST%COUNT%SPELL!ID = %COUNT%
SET /a REST%COUNT%ACCURACY = 9999
SET /a REST%COUNT%MPCOST = 60
SET /a REST%COUNT%UNLOCKLVL = 15
SET REST%COUNT%PREREQUISITE=Cura
SET /a REST%COUNT%REFLECTABLE = 0
SET /a REST%COUNT%EFFECTSNUM = 1
SET REST%COUNT%EFFECT1ELEMENT=NONE
SET REST%COUNT%EFFECT1TYPE=STATUS
SET REST%COUNT%EFFECT1ATTRIBUTE=Regen
SET REST%COUNT%EFFECT1TARGET=ATTACKER
SET /a REST%COUNT%EFFECT1AMOUNT = 1
SET /a REST%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a REST%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a REST%COUNT%EFFECT1MAXTURNCOUNT = 6
SET REST%COUNT%EFFECT1PLAYERTEXT=now has the !REST%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH

:ESUNASPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a REST5ID = 5
SET REST%COUNT%SPELL=Esuna
SET REST%COUNT%DESCRIPTION=Cures negative status ailments
SET REST%COUNT%ANIMATION=SELFSPELL
SET /a !REST%COUNT%SPELL!ID = %COUNT%
SET /a REST%COUNT%ACCURACY = 9999
SET /a REST%COUNT%MPCOST = 25
SET /a REST%COUNT%UNLOCKLVL = 10
SET REST%COUNT%PREREQUISITE=NONE
SET /a REST%COUNT%REFLECTABLE = 0
SET /a REST%COUNT%EFFECTSNUM = 4
SET REST%COUNT%EFFECT1ELEMENT=NONE
SET REST%COUNT%EFFECT1TYPE=STATUS
SET REST%COUNT%EFFECT1ATTRIBUTE=Blind
SET REST%COUNT%EFFECT1TARGET=ATTACKER
SET /a REST%COUNT%EFFECT1AMOUNT = 0
SET /a REST%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a REST%COUNT%EFFECT1MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT1MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT1PLAYERTEXT=is no longer afflicted with !REST%COUNT%EFFECT1ATTRIBUTE!^^!
SET REST%COUNT%EFFECT2ELEMENT=NONE
SET REST%COUNT%EFFECT2TYPE=STATUS
SET REST%COUNT%EFFECT2ATTRIBUTE=Silence
SET REST%COUNT%EFFECT2TARGET=ATTACKER
SET /a REST%COUNT%EFFECT2AMOUNT = 0
SET /a REST%COUNT%EFFECT2FIXEDAMOUNT = 1
SET /a REST%COUNT%EFFECT2MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT2MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT2PLAYERTEXT=is no longer afflicted with !REST%COUNT%EFFECT2ATTRIBUTE!^^!
SET REST%COUNT%EFFECT3ELEMENT=NONE
SET REST%COUNT%EFFECT3TYPE=STATUS
SET REST%COUNT%EFFECT3ATTRIBUTE=Poison
SET REST%COUNT%EFFECT3TARGET=ATTACKER
SET /a REST%COUNT%EFFECT3AMOUNT = 0
SET /a REST%COUNT%EFFECT3FIXEDAMOUNT = 1
SET /a REST%COUNT%EFFECT3MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT3MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT3PLAYERTEXT=is no longer afflicted with !REST%COUNT%EFFECT3ATTRIBUTE!^^!
SET REST%COUNT%EFFECT4ELEMENT=NONE
SET REST%COUNT%EFFECT4TYPE=STATUS
SET REST%COUNT%EFFECT4ATTRIBUTE=Confusion
SET REST%COUNT%EFFECT4TARGET=ATTACKER
SET /a REST%COUNT%EFFECT4AMOUNT = 0
SET /a REST%COUNT%EFFECT4FIXEDAMOUNT = 1
SET /a REST%COUNT%EFFECT4MINTURNCOUNT = 0
SET /a REST%COUNT%EFFECT4MAXTURNCOUNT = 0
SET REST%COUNT%EFFECT4PLAYERTEXT=is no longer afflicted with !REST%COUNT%EFFECT4ATTRIBUTE!^^!
CALL :SPELLNAMELENGTH



SET /a RESTSPELLTOT = %COUNT%

GOTO :EOF

:SPELLNAMELENGTH
SET /a REST%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SPELLNAMELOOPSTART
SET /a REST%COUNT%NAMELENGTH += 1
SET TEMP1=!REST%COUNT%NAMELENGTH!
SET SUBSTR=!REST%COUNT%SPELL:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPELLNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !REST%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!REST%COUNT%SPELL:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPELLNAMELOOPSTART
	)
)
GOTO :EOF