SET /a MINNAMELENGTH = 9
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0

:SACK1
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Paper Bag
SET /a SACK%COUNT%COST = 100
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %RABID%
CALL :SACKNAMELENGTH

:SACK2
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Tesco Bag
SET /a SACK%COUNT%COST = 250
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %TROLLSMASHID%
CALL :SACKNAMELENGTH

:SACK3
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Bag for Life
SET /a SACK%COUNT%COST = 750
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %PILEDRIVERID%
CALL :SACKNAMELENGTH

:SACK4
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Small Leather Sack
SET /a SACK%COUNT%COST = 2500
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %VAMBITEID%
CALL :SACKNAMELENGTH

:SACK5
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Large Leather Sack
SET /a SACK%COUNT%COST = 7500
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %FLYID%
CALL :SACKNAMELENGTH

:SACK6
SET /a COUNT = %COUNT% + 1
SET SACK%COUNT%NAME=Santa's Sack
SET /a SACK%COUNT%COST = 15000
SET /a SACK%COUNT%SELL = !SACK%COUNT%COST!
SET /a SACK%COUNT%STR = %COUNT%*10
SET /a SACK%COUNT%SKL = %COUNT%*10
SET /a SACK%COUNT%PER = %COUNT%*10
SET /a SACK%COUNT%ENEMYSKILL = %GASCHAMID%
CALL :SACKNAMELENGTH


SET /a SACKTOT = %COUNT%
GOTO :EOF

:SACKNAMELENGTH
SET /a SACK%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SACKNAMELOOPSTART
SET /a SACK%COUNT%NAMELENGTH += 1
SET TEMP1=!SACK%COUNT%NAMELENGTH!
SET SUBSTR=!SACK%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SACKNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !SACK%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!SACK%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SACKNAMELOOPSTART
	)
)
GOTO :EOF
