SET /a MINNAMELENGTH = 9
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0

:SPECIAL1
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Haste
SET SPECIAL%COUNT%NICKNAME=AHASTE
SET SPECIAL%COUNT%DESCRIPTION=Automatically gives you the Haste status for 5 turns
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
REM This gilcost is the amount you need to pay the blacksmith to add this special to an accessory
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL2
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Protect
SET SPECIAL%COUNT%NICKNAME=APROTECT
SET SPECIAL%COUNT%DESCRIPTION=Automatically gives you the Protect status for 5 turns
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL3
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Shell
SET SPECIAL%COUNT%NICKNAME=ASHELL
SET SPECIAL%COUNT%DESCRIPTION=Automatically gives you the Shell status for 5 turns
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL4
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Reflect
SET SPECIAL%COUNT%NICKNAME=AREFLECT
SET SPECIAL%COUNT%DESCRIPTION=Automatically gives you the Reflect status for 5 turns
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 4000
CALL :SPECIALNAMELENGTH

:SPECIAL5
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Regen
SET SPECIAL%COUNT%NICKNAME=AREGEN
SET SPECIAL%COUNT%DESCRIPTION=Automatically gives you the Regen status for 5 turns
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL5
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Scan
SET SPECIAL%COUNT%NICKNAME=ASCAN
SET SPECIAL%COUNT%DESCRIPTION=Automatically sets up scan at the start of a battle
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL5
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Detect
SET SPECIAL%COUNT%NICKNAME=ADETECT
SET SPECIAL%COUNT%DESCRIPTION=Automatically sets up detect at the start of a battle
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL7
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increased Critical Chance
SET SPECIAL%COUNT%NICKNAME=INCCRITCHANCE
SET SPECIAL%COUNT%DESCRIPTION=Increases your chance of performing a Critical Hit
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL7
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increased Critical Damage
SET SPECIAL%COUNT%NICKNAME=INCCRITDAM
SET SPECIAL%COUNT%DESCRIPTION=Increases the damage done by your Critical Hits
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 2500
CALL :SPECIALNAMELENGTH

:SPECIAL8
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increased Item Find Chance
SET SPECIAL%COUNT%NICKNAME=INCITEMFINDCHANCE
SET SPECIAL%COUNT%DESCRIPTION=Increases the chance that you'll find an item
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL9
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Find Better Items
SET SPECIAL%COUNT%NICKNAME=FINDBETTERITEM
SET SPECIAL%COUNT%DESCRIPTION=Increases your chance of finding a more rare item
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL8
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increased Equipment Find Chance
SET SPECIAL%COUNT%NICKNAME=INCEQUIPFINDCHANCE
SET SPECIAL%COUNT%DESCRIPTION=Increases the chance that you'll find some equipment
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL9
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Find Better Equipment
SET SPECIAL%COUNT%NICKNAME=FINDBETTEREQUIP
SET SPECIAL%COUNT%DESCRIPTION=Increases your chance of finding rare equipment
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL10
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increased Steal Item Chance
SET SPECIAL%COUNT%NICKNAME=INCSTLCHANCE
SET SPECIAL%COUNT%DESCRIPTION=Increses the chance that you'll successfully steal
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL11
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Steal Better Items
SET SPECIAL%COUNT%NICKNAME=STLBETTER
SET SPECIAL%COUNT%DESCRIPTION=Increases your chance of stealing a more rare item
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL12
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Find More Gil
SET SPECIAL%COUNT%NICKNAME=FINDMOREGIL
SET SPECIAL%COUNT%DESCRIPTION=You will receive more Gil at the end of a battle
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

REM TODO
:SPECIAL13
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Steal More Gil
SET SPECIAL%COUNT%NICKNAME=STLMOREGIL
SET SPECIAL%COUNT%DESCRIPTION=Increases the amount of Gil that you'll steal
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 3000
CALL :SPECIALNAMELENGTH

:SPECIAL14
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Double EXP
SET SPECIAL%COUNT%NICKNAME=DOUBLEEXP
SET SPECIAL%COUNT%DESCRIPTION=Doubles the EXP you gain from battles
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 7000
CALL :SPECIALNAMELENGTH

:SPECIAL14
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increase Catch Chance
SET SPECIAL%COUNT%NICKNAME=INCCATCH
SET SPECIAL%COUNT%DESCRIPTION=Greatly increases the chance of catching enemies
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL15
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Half MP Cost
SET SPECIAL%COUNT%NICKNAME=HALFMP
SET SPECIAL%COUNT%DESCRIPTION=All spells will cost half the usual amount of MP
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 10000
CALL :SPECIALNAMELENGTH

:SPECIAL16
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Zero MP Cost
SET SPECIAL%COUNT%NICKNAME=ZEROMP
SET SPECIAL%COUNT%DESCRIPTION=All spells will cost no MP. At ALL^^! Imagine that^^!
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 20000
CALL :SPECIALNAMELENGTH

:SPECIAL17
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Half AP Cost
SET SPECIAL%COUNT%NICKNAME=HALFAP
SET SPECIAL%COUNT%DESCRIPTION=All skills will cost half the usual AP
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL18
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Zero AP Cost
SET SPECIAL%COUNT%NICKNAME=ZEROAP
SET SPECIAL%COUNT%DESCRIPTION=All skills will cost no AP.
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 10000
CALL :SPECIALNAMELENGTH

:SPECIAL19
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Heal HP
SET SPECIAL%COUNT%NICKNAME=HEALHP
SET SPECIAL%COUNT%DESCRIPTION=Automatically restores all of your HP after a battle
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 4000
CALL :SPECIALNAMELENGTH

:SPECIAL20
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Auto Heal MP
SET SPECIAL%COUNT%NICKNAME=HEALMP
SET SPECIAL%COUNT%DESCRIPTION=Automatically restores all of your MP after a battle
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 4000
CALL :SPECIALNAMELENGTH

:SPECIAL21
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Full AP Start
SET SPECIAL%COUNT%NICKNAME=FULLAP
SET SPECIAL%COUNT%DESCRIPTION=Automatically start a battle with full AP
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 8000
CALL :SPECIALNAMELENGTH

:SPECIAL22
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Double AP Gain Rate
SET SPECIAL%COUNT%NICKNAME=FASTAP
SET SPECIAL%COUNT%DESCRIPTION=Gain AP twice as fast
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL23
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Double Max AP
SET SPECIAL%COUNT%NICKNAME=DOUBLEAP
SET SPECIAL%COUNT%DESCRIPTION=Doubles your maximum AP
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 2500
CALL :SPECIALNAMELENGTH

:SPECIAL23
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Double Limit Break Charge Rate
SET SPECIAL%COUNT%NICKNAME=DOUBLELIM
SET SPECIAL%COUNT%DESCRIPTION=Doubles the rate at which your limit break charges
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 10000
CALL :SPECIALNAMELENGTH

:SPECIAL23
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Double Limit Break Damage
SET SPECIAL%COUNT%NICKNAME=DOUBLELIMDAM
SET SPECIAL%COUNT%DESCRIPTION=Doubles the damage that your limit break does
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 10000
CALL :SPECIALNAMELENGTH

:SPECIAL24
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Break Damage limit
SET SPECIAL%COUNT%NICKNAME=BREAKDAM
SET SPECIAL%COUNT%DESCRIPTION=You can break the damage limit of %MAXDAM%
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 20000
CALL :SPECIALNAMELENGTH

:SPECIAL25
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Pacman Special
SET SPECIAL%COUNT%NICKNAME=PACMANSPECIAL
SET SPECIAL%COUNT%DESCRIPTION=Pacman may appear and munch the enemies up for you
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL26
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Leeroy Special
SET SPECIAL%COUNT%NICKNAME=LEEROYSPECIAL
SET SPECIAL%COUNT%DESCRIPTION=Leeroy charges into the battle before you
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 5000
CALL :SPECIALNAMELENGTH

:SPECIAL27
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=No Encounters
SET SPECIAL%COUNT%NICKNAME=NOENC
SET SPECIAL%COUNT%DESCRIPTION=You won't randomly bump into enemies
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL28
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=More Oxygen
SET SPECIAL%COUNT%NICKNAME=EXTRAOXYGEN
SET SPECIAL%COUNT%DESCRIPTION=Breathe for longer under water
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL29
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Slow Mine Cart
SET SPECIAL%COUNT%NICKNAME=SLOWCART
SET SPECIAL%COUNT%DESCRIPTION=Slows the mine cart down
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 1000
CALL :SPECIALNAMELENGTH

:SPECIAL30
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=Increase Casino Money
SET SPECIAL%COUNT%NICKNAME=DOUBLECASINO
SET SPECIAL%COUNT%DESCRIPTION=Receive more income from the casino
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 20000
CALL :SPECIALNAMELENGTH

:SPECIAL31
SET /a COUNT = %COUNT% + 1
SET SPECIAL%COUNT%NAME=More Limit Breaks
SET SPECIAL%COUNT%NICKNAME=MORELIMITBREAK
SET SPECIAL%COUNT%DESCRIPTION=Allows your limit breaks to be made up of 3 components
SET /a !SPECIAL%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIAL%COUNT%GILCOST = 20000
CALL :SPECIALNAMELENGTH

SET /a SPECIALTOT = %COUNT%

::ECHO The minimum is %MINNAMELENGTH% for !SPECIAL%MIN%NAME!
::pause

GOTO :EOF




:SPECIALNAMELENGTH
SET /a SPECIAL%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SPECIALNAMELOOPSTART
SET /a SPECIAL%COUNT%NAMELENGTH += 1
SET TEMP1=!SPECIAL%COUNT%NAMELENGTH!
SET SUBSTR=!SPECIAL%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPECIALNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !SPECIAL%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!SPECIAL%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPECIALNAMELOOPSTART
	)
)
::ECHO !SPECIAL%COUNT%NAME! is !SPECIAL%COUNT%NAMELENGTH! letters long
::IF !SPECIAL%COUNT%NAMELENGTH! LSS %MINNAMELENGTH% (
::	SET /a MINNAMELENGTH = !SPECIAL%COUNT%NAMELENGTH!
::	SET /a MIN = %COUNT%
::)
GOTO :EOF
