SET /a MINNAMELENGTH = 8
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0
SET /a STATSTONESTART = %COUNT%

:SPECIALITEM1
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Strength Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Strength bonus of a Weapon
SET SPECIALITEM%COUNT%NICKNAME=STRSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM2
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Magic Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Magic bonus of a Weapon
SET SPECIALITEM%COUNT%NICKNAME=MAGSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM3
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Accuracy Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Accuracy bonus of a Weapon
SET SPECIALITEM%COUNT%NICKNAME=ACCSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM4
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Endurance Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Endurance bonus of Armour
SET SPECIALITEM%COUNT%NICKNAME=ENDSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM5
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Spirit Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Spirit bonus of a Armour
SET SPECIALITEM%COUNT%NICKNAME=SPRSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM6
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Evasion Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Evasion bonus of a Armour
SET SPECIALITEM%COUNT%NICKNAME=EVASTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM7
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Speed Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Speed bonus of a Armour
SET SPECIALITEM%COUNT%NICKNAME=SPDSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM8
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=HP Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the HP bonus of an Accessory
SET SPECIALITEM%COUNT%NICKNAME=MAXHPSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM9
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=MP Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the MP bonus of an Accessory
SET SPECIALITEM%COUNT%NICKNAME=MAXMPSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM10
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Luck Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Increases the Luck bonus of an Accessory
SET SPECIALITEM%COUNT%NICKNAME=LCKSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 300
SET /a SPECIALITEM%COUNT%QUANTDIV = 60
SET /a SPECIALITEM%COUNT%EXP = 100

SET /a STATSTONEEND = %COUNT%
SET /a ALCHEMYSTONESTART = %COUNT%

:SPECIALITEM11
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Creation Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Used for item creation
SET SPECIALITEM%COUNT%NICKNAME=CRTSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100

:SPECIALITEM12
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Combining Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Used to combine items
SET SPECIALITEM%COUNT%NICKNAME=CMBSTONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100

SET /a ALCHEMYSTONEEND = %COUNT%

SET /a RESISTANCEPOWDERSTART = %COUNT%

:SPECIALITEM13
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Weakness Powder
SET SPECIALITEM%COUNT%DESCRIPTION=Removes elemental weaknesses from armour
SET SPECIALITEM%COUNT%NICKNAME=WEAKPOW
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 50
SET /a SPECIALITEM%COUNT%QUANTDIV = 20
SET /a SPECIALITEM%COUNT%EXP = 50


:SPECIALITEM14
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Resistance Powder
SET SPECIALITEM%COUNT%DESCRIPTION=Adds elemental resistances to armour
SET SPECIALITEM%COUNT%NICKNAME=RESPOW
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 0
SET /a SPECIALITEM%COUNT%MAXSKL = 30
SET /a SPECIALITEM%COUNT%QUANTDIV = 20
SET /a SPECIALITEM%COUNT%EXP = 50

:SPECIALITEM15
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Elemental Immunity Powder
SET SPECIALITEM%COUNT%DESCRIPTION=Adds elemental immunities to armour
SET SPECIALITEM%COUNT%NICKNAME=ELEIMMPOW
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 20
SET /a SPECIALITEM%COUNT%MAXSKL = 60
SET /a SPECIALITEM%COUNT%QUANTDIV = 30
SET /a SPECIALITEM%COUNT%EXP = 100

:SPECIALITEM16
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Absorpion Powder
SET SPECIALITEM%COUNT%DESCRIPTION=Adds elemental absorption to armour
SET SPECIALITEM%COUNT%NICKNAME=ABSPOW
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 50
SET /a SPECIALITEM%COUNT%MAXSKL = 200
SET /a SPECIALITEM%COUNT%QUANTDIV = 50
SET /a SPECIALITEM%COUNT%EXP = 250

:SPECIALITEM17
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=Status Immunity Powder
SET SPECIALITEM%COUNT%DESCRIPTION=Adds status immunities to armour
SET SPECIALITEM%COUNT%NICKNAME=STATIMMPOW
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
SET /a SPECIALITEM%COUNT%MINSKL = 30
SET /a SPECIALITEM%COUNT%MAXSKL = 100
SET /a SPECIALITEM%COUNT%QUANTDIV = 30
SET /a SPECIALITEM%COUNT%EXP = 100

SET /a RESISTANCEPOWDEREND = %COUNT%
SET /a SKILLSTONESTART = %COUNT%

SET /a SKILLCOUNT = 0

:SPECIALITEMSKILLLOOP
SET /a SKILLCOUNT = %SKILLCOUNT%+1
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=!SKILL%SKILLCOUNT%NAME! Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Adds the !SKILL%SKILLCOUNT%NAME! Skill to weapons
SET SPECIALITEM%COUNT%NICKNAME=!SKILL%SKILLCOUNT%NICKNAME!STONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
REM Will need to make these related to the !SKILL%COUNT%APCOST! in some way
SET /a SPECIALITEM%COUNT%MINSKL = !SKILL%SKILLCOUNT%APCOST!
SET /a SPECIALITEM%COUNT%MAXSKL = !SKILL%SKILLCOUNT%APCOST!*5
SET /a SPECIALITEM%COUNT%QUANTDIV = !SKILL%SKILLCOUNT%APCOST!*2
SET /a SPECIALITEM%COUNT%EXP = !SKILL%SKILLCOUNT%APCOST!*10
::For efficiency, this is calculated here instead of below. The +6 is for " Stone"
SET /a SPECIALITEM%COUNT%NAMELENGTH = !SKILL%SKILLCOUNT%NAMELENGTH! + 6
IF %SKILLCOUNT% LSS %SKILLTOT% (
	GOTO :SPECIALITEMSKILLLOOP
)
SET /a SKILLSTONEEND = %COUNT%

SET /a SPECIALSTONESTART = %COUNT%

SET /a SPECIALCOUNT = 0

:SPECIALITEMSPECIALLOOP
SET /a SPECIALCOUNT = %SPECIALCOUNT%+1
SET /a COUNT = %COUNT%+1
SET SPECIALITEM%COUNT%NAME=!SPECIAL%SPECIALCOUNT%NAME! Stone
SET SPECIALITEM%COUNT%DESCRIPTION=Adds the !SPECIAL%SPECIALCOUNT%NAME! Special Ability to accessories
SET SPECIALITEM%COUNT%NICKNAME=!SPECIAL%SPECIALCOUNT%NICKNAME!STONE
SET /a !SPECIALITEM%COUNT%NICKNAME!ID = %COUNT%
SET /a SPECIALITEM%COUNT%COST = 100
REM Will need to make these related to the !SPECIAL%COUNT%GILCOST! in some way
SET /a SPECIALITEM%COUNT%MINSKL = !SPECIAL%SPECIALCOUNT%GILCOST!/100
SET /a SPECIALITEM%COUNT%MAXSKL = !SPECIAL%SPECIALCOUNT%GILCOST!/50
SET /a SPECIALITEM%COUNT%QUANTDIV = !SPECIAL%SPECIALCOUNT%GILCOST!/100
SET /a SPECIALITEM%COUNT%EXP = !SPECIAL%SPECIALCOUNT%GILCOST!/20
::For efficiency, this is calculated here instead of below. The +6 is for " Stone"
SET /a SPECIALITEM%COUNT%NAMELENGTH = !SPECIAL%SPECIALCOUNT%NAMELENGTH! + 6
IF %SPECIALCOUNT% LSS %SPECIALTOT% (
	GOTO :SPECIALITEMSPECIALLOOP
)
SET /a SPECIALSTONEEND = %COUNT%

SET /a SPECIALITEMTOTAL = %COUNT%

::CALL :LENGTHCALCULATIONS
::CALL :RECORDNAMELENGTHS
CALL :SETNAMELENGTHS
GOTO :EOF


:LENGTHCALCULATIONS
SET /a COUNT = 0
:SPECIALITEMNAMELENGTH
SET /a COUNT = %COUNT% + 1
SET /a SPECIALITEM%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SPECIALITEMNAMELOOPSTART
SET /a SPECIALITEM%COUNT%NAMELENGTH += 1
SET TEMP1=!SPECIALITEM%COUNT%NAMELENGTH!
SET SUBSTR=!SPECIALITEM%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPECIALITEMNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !SPECIALITEM%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!SPECIALITEM%COUNT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPECIALITEMNAMELOOPSTART
	)
)
::ECHO !SPECIALITEM%COUNT%NAME! is !SPECIALITEM%COUNT%NAMELENGTH! letters long
::IF !SPECIALITEM%COUNT%NAMELENGTH! LSS %MINNAMELENGTH% (
::	SET /a MINNAMELENGTH = !SPECIALITEM%COUNT%NAMELENGTH!
::	SET /a MIN = %COUNT%
::)

::Changed from %SPECIALITEMTOTAL% and set these "manually" above to improve efficiency
IF %COUNT% LSS %RESISTANCEPOWDEREND% (
	GOTO :SPECIALITEMNAMELENGTH
)
::ECHO The minimum is %MINNAMELENGTH% for !SPECIALITEM%MIN%NAME!
::pause
GOTO :EOF

:RECORDNAMELENGTHS
::To use this, remove all ::s from the "::CALL :SPECIALITEMNAMELENGTH" lines so that the game can calculate the lengths. Then uncomment "CALL :RECORDSPECIALITEMNAMELENGTHS"
SET /a COUNT = 0
:RECORDLENGTHSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a SPECIALITEM%COUNT%NAMELENGTH = !SPECIALITEM%COUNT%NAMELENGTH! >> C:\Game\SPECIALITEMnamelengths.txt
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :RECORDLENGTHSLOOP
)
GOTO :EOF

:SETNAMELENGTHS
::This should be copied form the output of :RECORDNAMELENGTHS
SET /a SPECIALITEM1NAMELENGTH = 14 
SET /a SPECIALITEM2NAMELENGTH = 11 
SET /a SPECIALITEM3NAMELENGTH = 14 
SET /a SPECIALITEM4NAMELENGTH = 15 
SET /a SPECIALITEM5NAMELENGTH = 12 
SET /a SPECIALITEM6NAMELENGTH = 13 
SET /a SPECIALITEM7NAMELENGTH = 11 
SET /a SPECIALITEM8NAMELENGTH = 8 
SET /a SPECIALITEM9NAMELENGTH = 8 
SET /a SPECIALITEM10NAMELENGTH = 10 
SET /a SPECIALITEM11NAMELENGTH = 14 
SET /a SPECIALITEM12NAMELENGTH = 15 
SET /a SPECIALITEM13NAMELENGTH = 15 
SET /a SPECIALITEM14NAMELENGTH = 17 
SET /a SPECIALITEM15NAMELENGTH = 25 
SET /a SPECIALITEM16NAMELENGTH = 16 
SET /a SPECIALITEM17NAMELENGTH = 22 
SET /a SPECIALITEM18NAMELENGTH = 13 
SET /a SPECIALITEM19NAMELENGTH = 18 
SET /a SPECIALITEM20NAMELENGTH = 13 
SET /a SPECIALITEM21NAMELENGTH = 18 
SET /a SPECIALITEM22NAMELENGTH = 10 
SET /a SPECIALITEM23NAMELENGTH = 14 
SET /a SPECIALITEM24NAMELENGTH = 11 
SET /a SPECIALITEM25NAMELENGTH = 9 
SET /a SPECIALITEM26NAMELENGTH = 10 
SET /a SPECIALITEM27NAMELENGTH = 16 
SET /a SPECIALITEM28NAMELENGTH = 18 
SET /a SPECIALITEM29NAMELENGTH = 23 
SET /a SPECIALITEM30NAMELENGTH = 24 
SET /a SPECIALITEM31NAMELENGTH = 25 
SET /a SPECIALITEM32NAMELENGTH = 11 
SET /a SPECIALITEM33NAMELENGTH = 20 
SET /a SPECIALITEM34NAMELENGTH = 10 
SET /a SPECIALITEM35NAMELENGTH = 12 
SET /a SPECIALITEM36NAMELENGTH = 10 
SET /a SPECIALITEM37NAMELENGTH = 14 
SET /a SPECIALITEM38NAMELENGTH = 15 
SET /a SPECIALITEM39NAMELENGTH = 22 
SET /a SPECIALITEM40NAMELENGTH = 18 
SET /a SPECIALITEM41NAMELENGTH = 23 
SET /a SPECIALITEM42NAMELENGTH = 21 
SET /a SPECIALITEM43NAMELENGTH = 26 
SET /a SPECIALITEM44NAMELENGTH = 28 
SET /a SPECIALITEM45NAMELENGTH = 30 
SET /a SPECIALITEM46NAMELENGTH = 35 
SET /a SPECIALITEM47NAMELENGTH = 28 
SET /a SPECIALITEM48NAMELENGTH = 17 
SET /a SPECIALITEM49NAMELENGTH = 22 
SET /a SPECIALITEM50NAMELENGTH = 16 
SET /a SPECIALITEM51NAMELENGTH = 21 
SET /a SPECIALITEM52NAMELENGTH = 21 
SET /a SPECIALITEM53NAMELENGTH = 26 
SET /a SPECIALITEM54NAMELENGTH = 18 
SET /a SPECIALITEM55NAMELENGTH = 23 
SET /a SPECIALITEM56NAMELENGTH = 18 
SET /a SPECIALITEM57NAMELENGTH = 23 
SET /a SPECIALITEM58NAMELENGTH = 22 
SET /a SPECIALITEM59NAMELENGTH = 27 
SET /a SPECIALITEM60NAMELENGTH = 18 
SET /a SPECIALITEM61NAMELENGTH = 21 
SET /a SPECIALITEM62NAMELENGTH = 26 
SET /a SPECIALITEM63NAMELENGTH = 14 
SET /a SPECIALITEM64NAMELENGTH = 16 
SET /a SPECIALITEM65NAMELENGTH = 19 
SET /a SPECIALITEM66NAMELENGTH = 9 
SET /a SPECIALITEM67NAMELENGTH = 18 
SET /a SPECIALITEM68NAMELENGTH = 16 
SET /a SPECIALITEM69NAMELENGTH = 18 
SET /a SPECIALITEM70NAMELENGTH = 16 
SET /a SPECIALITEM71NAMELENGTH = 18 
SET /a SPECIALITEM72NAMELENGTH = 16 
SET /a SPECIALITEM73NAMELENGTH = 15 
SET /a SPECIALITEM74NAMELENGTH = 17 
SET /a SPECIALITEM75NAMELENGTH = 31 
SET /a SPECIALITEM76NAMELENGTH = 31 
SET /a SPECIALITEM77NAMELENGTH = 32 
SET /a SPECIALITEM78NAMELENGTH = 23 
SET /a SPECIALITEM79NAMELENGTH = 37 
SET /a SPECIALITEM80NAMELENGTH = 27 
SET /a SPECIALITEM81NAMELENGTH = 33 
SET /a SPECIALITEM82NAMELENGTH = 24 
SET /a SPECIALITEM83NAMELENGTH = 19 
SET /a SPECIALITEM84NAMELENGTH = 20 
SET /a SPECIALITEM85NAMELENGTH = 16 
SET /a SPECIALITEM86NAMELENGTH = 27 
SET /a SPECIALITEM87NAMELENGTH = 18 
SET /a SPECIALITEM88NAMELENGTH = 18 
SET /a SPECIALITEM89NAMELENGTH = 18 
SET /a SPECIALITEM90NAMELENGTH = 18 
SET /a SPECIALITEM91NAMELENGTH = 18 
SET /a SPECIALITEM92NAMELENGTH = 18 
SET /a SPECIALITEM93NAMELENGTH = 19 
SET /a SPECIALITEM94NAMELENGTH = 25 
SET /a SPECIALITEM95NAMELENGTH = 19 
SET /a SPECIALITEM96NAMELENGTH = 36 
SET /a SPECIALITEM97NAMELENGTH = 31 
SET /a SPECIALITEM98NAMELENGTH = 24 
SET /a SPECIALITEM99NAMELENGTH = 20 
SET /a SPECIALITEM100NAMELENGTH = 20 
SET /a SPECIALITEM101NAMELENGTH = 19 
SET /a SPECIALITEM102NAMELENGTH = 17 
SET /a SPECIALITEM103NAMELENGTH = 20 
SET /a SPECIALITEM104NAMELENGTH = 27 
SET /a SPECIALITEM105NAMELENGTH = 23 
GOTO :EOF