SET /a MINNAMELENGTH = 4
::SET /a MINNAMELENGTH = 1
SET /a COUNT=0
:STAT1SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 1
SET STAT%COUNT%SPELL=Blind
SET STAT%COUNT%DESCRIPTION=Reduces the enemy's accuracy
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 100
SET /a STAT%COUNT%MPCOST = 10
SET /a STAT%COUNT%UNLOCKLVL = 5
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Blind
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT2SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 2
SET STAT%COUNT%SPELL=Silence
SET STAT%COUNT%DESCRIPTION=Stops the enemy from casting spells
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 100
SET /a STAT%COUNT%MPCOST = 10
SET /a STAT%COUNT%UNLOCKLVL = 10
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Silence
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT3SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 3
SET STAT%COUNT%SPELL=Poison
SET STAT%COUNT%DESCRIPTION=Damages the enemy for a small amount each turn
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 100
SET /a STAT%COUNT%MPCOST = 15
SET /a STAT%COUNT%UNLOCKLVL = 15
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Poison
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT4SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 4
SET STAT%COUNT%SPELL=Slow
SET STAT%COUNT%DESCRIPTION=Reduces the enemy's speed
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 100
SET /a STAT%COUNT%MPCOST = 5
SET /a STAT%COUNT%UNLOCKLVL = 5
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Slow
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT5SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 5
SET STAT%COUNT%SPELL=Sleep
SET STAT%COUNT%DESCRIPTION=Puts the enemy to sleep, sleeping enemies cannot act
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 60
SET /a STAT%COUNT%MPCOST = 40
SET /a STAT%COUNT%UNLOCKLVL = 25
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Sleep
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT6SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 6
SET STAT%COUNT%SPELL=Confusion
SET STAT%COUNT%DESCRIPTION=Confuses the enemy so that it may attack itself
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 60
SET /a STAT%COUNT%MPCOST = 40
SET /a STAT%COUNT%UNLOCKLVL = 30
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Confusion
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:STAT7SPELLSTATS
SET /a COUNT=%COUNT%+1
SET /a STAT%COUNT%ID = 7
SET STAT%COUNT%SPELL=Stop
SET STAT%COUNT%DESCRIPTION=Stops the enemy in it's tracks, stopped enemies cannot act
SET STAT%COUNT%ANIMATION=STATUSSPELL
SET /a !STAT%COUNT%SPELL!ID = %COUNT%
SET /a STAT%COUNT%ACCURACY = 60
SET /a STAT%COUNT%MPCOST = 50
SET /a STAT%COUNT%UNLOCKLVL = 40
SET STAT%COUNT%PREREQUISITE=NONE
SET /a STAT%COUNT%REFLECTABLE = 1
SET /a STAT%COUNT%EFFECTSNUM = 1
SET STAT%COUNT%EFFECT1ELEMENT=NONE
SET STAT%COUNT%EFFECT1TYPE=STATUS
SET STAT%COUNT%EFFECT1ATTRIBUTE=Stop
SET STAT%COUNT%EFFECT1TARGET=DEFENDER
SET /a STAT%COUNT%EFFECT1AMOUNT = 1
SET /a STAT%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a STAT%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a STAT%COUNT%EFFECT1MAXTURNCOUNT = 6
SET STAT%COUNT%EFFECT1PLAYERTEXT=now has the !STAT%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


SET /a STATSPELLTOT = %COUNT%


GOTO :EOF

:SPELLNAMELENGTH
SET /a STAT%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SPELLNAMELOOPSTART
SET /a STAT%COUNT%NAMELENGTH += 1
SET TEMP1=!STAT%COUNT%NAMELENGTH!
SET SUBSTR=!STAT%COUNT%SPELL:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPELLNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !STAT%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!STAT%COUNT%SPELL:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPELLNAMELOOPSTART
	)
)
GOTO :EOF