SET /a PAGE1START = 1 
SET STORY1VERSION1LINE1=Your mother asked you to pop over to Uncle Jim's house.  
SET /a STORY1VERSION1LINETOT=1 
SET STORY1VERSION2LINE1=Your mother asked you to pop over to Uncle Jim's house,  
SET STORY1VERSION2LINE2=who showed you how to use equipment and navigate different types of menus.  
SET /a STORY1VERSION2LINETOT=2 
SET STORY2VERSION1LINE1=Your friend %FRIENDNAME% showed you how to fight enemies and   
SET STORY2VERSION1LINE2=%GIRLNAME% showed you how to catch them.  
SET /a STORY2VERSION1LINETOT=2 
SET STORY3VERSION1LINE1=During a camp-out at The Old Mill, the town was attacked by %LASTBOSSNAME%.   
SET STORY3VERSION1LINE2=The townsfolk were missing and your house collapsed before you could check if your mother was inside.   
SET STORY3VERSION1LINE3=%FRIENDNAME% ran away, vowing to track down %LASTBOSSNAME% and kill him.  
SET STORY3VERSION1LINE4=%LASTBOSSNAME% returned, killed Uncle Jim and kidnapped %GIRLNAME%.   
SET /a STORY3VERSION1LINETOT=4 
SET STORY4VERSION1LINE1=You tried to stop him but were defeated.  
SET /a STORY4VERSION1LINETOT=1 
SET STORY4VERSION2LINE1=You kicked his ass. Game over, well done.
SET /a STORY4VERSION2LINETOT=1 
SET STORY5VERSION1LINE1=You woke in a temple after being healed by %PRIESTNAME%.  
SET STORY5VERSION1LINE2=He spoke of a book in a castle in %TOWN3NICKNAME% that contains vital   
SET STORY5VERSION1LINE3=information about %LASTBOSSNAME%. To get there you'll need to pass  
SET STORY5VERSION1LINE4=through the cave, but first you'll have to open the door...  
SET /a STORY5VERSION1LINETOT=4 
SET /a PAGE1END = 5 
SET /a PAGE2START = 6 
SET STORY6VERSION1LINE1=You found that the entrance to the cave was locked and seemingly,   
SET STORY6VERSION1LINE2=the only way in is to scan the correct eye on the retina scanner  
SET /a STORY6VERSION1LINETOT=2 
SET STORY7VERSION1LINE1=The Tramp round the back of the shop seems to have a very unusual eye.  
SET STORY7VERSION1LINE2=Maybe this is related to the cave somehow (Hint Hint^!)  
SET /a STORY7VERSION1LINETOT=2 
SET STORY8VERSION1LINE1=You woke the Tramp up by kicking him in the balls.  
SET /a STORY8VERSION1LINETOT=1 
SET STORY8VERSION2LINE1=You woke the Tramp up by kissing him...weirdo.  
SET /a STORY8VERSION2LINETOT=1 
SET STORY8VERSION3LINE1=You woke the Tramp up by ripping his eye out while he slept.  
SET /a STORY8VERSION3LINETOT=1 
SET STORY9VERSION1LINE1=You beat the Tramp and, in a meth-induced euphoria, he ripped his eye out and  
SET STORY9VERSION1LINE2=presented it to you as a gift  
SET /a STORY9VERSION1LINETOT=2 
SET STORY9VERSION2LINE1=You beat the Tramp and kept his eye from when you ripped it out earlier  
SET /a STORY9VERSION2LINETOT=1 
SET STORY9VERSION3LINE1=The Tramp beat you. Loser. Go and kick his ass^!  
SET /a STORY9VERSION3LINETOT=1 
SET STORY9VERSION4LINE1=You ran away from the Tramp and he took his eye back. Go and kick his ass^!  
SET /a STORY9VERSION4LINETOT=1 
SET STORY10VERSION1LINE1=You let the Tramp die, forever missing out on the chance to make a new best friend.  
SET /a STORY10VERSION1LINETOT=1 
SET STORY10VERSION2LINE1=You took the Tramp to the temple to get fixed up.  
SET /a STORY10VERSION2LINETOT=1 
SET STORY11VERSION1LINE1=You paid for the Tramp's treatment and he taught you the !SKILL%TRAGEID%NAME! skill in return  
SET /a STORY11VERSION1LINETOT=1 
SET STORY11VERSION2LINE1=You elected not to pay for the Tramp's treatment and he died at the temple  
SET /a STORY11VERSION2LINETOT=1 
SET STORY11VERSION3LINE1=%PRIESTNAME% said that he would perform the healing ritual for free, on one condition...  
SET STORY11VERSION3LINE2=You have to kill the Shopkeeper within 24 hours^!  
SET /a STORY11VERSION3LINETOT=2 
SET STORY11VERSION4LINE1=%PRIESTNAME% said that he would perform the healing ritual if you killed the Shopkeeper within 24 hours  
SET STORY11VERSION4LINE2=You didn't do this and the Tramp sadly passed away  
SET /a STORY11VERSION4LINETOT=2 
SET STORY11VERSION5LINE1=%PRIESTNAME% said that he would perform the healing ritual if you killed the Shopkeeper within 24 hours  
SET STORY11VERSION5LINE2=You happily complied and the Tramp was saved^!  
SET STORY11VERSION5LINE3=He taught you the !SKILL%TRAGEID%NAME! skill for saving his life.  
SET /a STORY11VERSION5LINETOT=3 
SET STORY12VERSION1LINE1=You used the Tramp's eye to enter the cave  
SET /a STORY12VERSION1LINETOT=1 
SET STORY12VERSION2LINE1=You used the Shopkeeper's eye on the retina scanner and found lots of goodies^!  
SET /a STORY12VERSION2LINETOT=1 
SET STORY12VERSION3LINE1=You used the Shopkeeper's eye on the retina scanner and found lots of goodies^!  
SET STORY12VERSION3LINE2=You used the Tramp's eye to enter the cave  
SET /a STORY12VERSION3LINETOT=2 
SET /a PAGE2END = 12 
SET /a PAGE3START = 13 
SET STORY13VERSION1LINE1=You travelled through the cave without even bothering to explore the second level.  
SET STORY13VERSION1LINE2=Maybe you should go back and explore a bit more...  
SET /a STORY13VERSION1LINETOT=2 
SET STORY13VERSION2LINE1=You went down to the second level of the cave but haven't yet defeated the familiar fellow.  
SET STORY13VERSION2LINE2=No matter, you can go back when you're stronger  
SET /a STORY13VERSION2LINETOT=2 
SET STORY13VERSION3LINE1=You went down to the second level of the cave and beat Pacman^!  
SET STORY13VERSION3LINE2=You acquired a talisman (accessory) that can call on Pacman to defeat enemies for you.  
SET /a STORY13VERSION3LINETOT=2 
SET STORY14VERSION1LINE1=You entered %TOWN3NICKNAME% and went straight to the Mine.  
SET STORY14VERSION1LINE2=Unfortunately it was locked. Maybe the key is in the castle. (Hint hint^!)  
SET /a STORY14VERSION1LINETOT=2 
SET STORY14VERSION2LINE1=You entered %TOWN3NICKNAME% and went straight to the Casino.  
SET STORY14VERSION2LINE2=Hopefully you'll make plenty of money here without annoying the owner...  
SET /a STORY14VERSION2LINETOT=2 
SET STORY14VERSION3LINE1=You entered %TOWN3NICKNAME% and went straight into the Castle.  
SET STORY14VERSION3LINE2=You should look for the book on %LASTBOSSNAME% that %PRIESTNAME% mentioned.  
SET /a STORY14VERSION3LINETOT=2 
SET STORY15VERSION1LINE1=You're yet to find the Mine key and book on %LASTBOSSNAME% that %PRIESTNAME% mentioned  
SET STORY15VERSION1LINE2=They must be somewhere in this castle.  
SET /a STORY15VERSION1LINETOT=2 
SET STORY15VERSION2LINE1=You found the Mine key and book about %LASTBOSSNAME%.  
SET STORY15VERSION2LINE2=The book says that you need to find 4 crystals to open the portal to Hell and confront %LASTBOSSNAME%  
SET STORY15VERSION2LINE3=The !KEYITEM%MAGSTONE1ID%NAME!  
SET STORY15VERSION2LINE4=The !KEYITEM%MAGSTONE2ID%NAME!  
SET STORY15VERSION2LINE5=The !KEYITEM%MAGSTONE3ID%NAME!  
SET STORY15VERSION2LINE6=The !KEYITEM%MAGSTONE4ID%NAME!  
SET /a STORY15VERSION2LINETOT=6 
SET STORY16VERSION1LINE1=You should play more in the Casino. Something fun might happen^!  
SET /a STORY16VERSION1LINETOT=1 
SET STORY16VERSION2LINE1=You won enough money in the Casino to catch the owner's eye and he had you thrown out.  
SET STORY16VERSION2LINE2=Are you going to stand for that^!?  
SET /a STORY16VERSION2LINETOT=2 
SET STORY16VERSION3LINE1=You got thrown out of the Casino but went back in there and kicked arse Terminator-style.  
SET STORY16VERSION3LINE2=You beat the Casino Owner and you now own the Casino.  
SET STORY16VERSION3LINE3=It generates money over time and you can invest gil in it to increase the income  
SET /a STORY16VERSION3LINETOT=3 
SET /a PAGE3END = 16 
SET /a PAGE4START = 17 
SET STORY17VERSION1LINE1=You went into the Mine, but didn't bother to explore before jumping on the cart.  
SET STORY17VERSION1LINE2=Probably worth going back and looking around...  
SET /a STORY17VERSION1LINETOT=2 
SET STORY17VERSION2LINE1=You went into the Mine and found Leeroy Jenkins^! (Google if unfamiliar)  
SET STORY17VERSION2LINE2=You beat him and acquired his talisman (accessory) that lets him help you defeat enemies  
SET /a STORY17VERSION2LINETOT=2 
SET STORY17VERSION3LINE1=You went into the Mine and found Leeroy Jenkins^! (Google if unfamiliar)  
SET STORY17VERSION3LINE2=You didn't manage to beat him. You should try again when you're stronger  
SET /a STORY17VERSION3LINETOT=2 
SET STORY18VERSION1LINE1=You didn't check out the Gold Mine as you were obviously scared.  
SET STORY18VERSION1LINE2=Get back in there and check it out you little bitch.  
SET /a STORY18VERSION1LINETOT=2 
SET STORY18VERSION2LINE1=You beat Balthazar and found the !KEYITEM%MAGSTONE1ID%NAME!^!  
SET STORY18VERSION2LINE2=You entered the Gold Mine and met with the Dwarf Sultan, who offered his people's services  
SET STORY18VERSION2LINE3=This could be a fantastic way to get really rare items and equipment (Hint hint^!)  
SET /a STORY18VERSION2LINETOT=3 
SET STORY19VERSION1LINE1=You should check out the Blacksmith  
SET /a STORY19VERSION1LINETOT=1 
SET STORY19VERSION2LINE1=You met the Blacksmith, who offered to customise your equipment for you.  
SET STORY19VERSION2LINE2=This sounds like it's definitely worth doing... (INCREDIBLY BIG HINT HINT^!)  
SET /a STORY19VERSION2LINETOT=2 
SET STORY20VERSION1LINE1=You entered the Forest but couldn't see a thing for the mist.  
SET STORY20VERSION1LINE2=Maybe
SET /a STORY20VERSION1LINETOT=2 
SET STORY20VERSION2LINE1=You entered the Forest but couldn't see a thing for the mist.  
SET STORY20VERSION2LINE2=When you escaped you were confronted by an Old Man who told you that you'll need to speak  
SET STORY20VERSION2LINE3=to %SEAKINGNAME% to remove the mist.  
SET STORY20VERSION2LINE4=You should look for the entrance to his kingdom at the bottom right of the Lake.  
SET /a STORY20VERSION2LINETOT=4 
SET /a PAGE4END = 20 
SET /a PAGE5START = 21 
SET STORY21VERSION1LINE1=You found the entrance to an underwater passage that leads to %SEAKINGNAME%'s kingdom.  
SET /a STORY21VERSION1LINETOT=1 
SET STORY22VERSION1LINE1=You should check out the Alchemist's.  
SET /a STORY22VERSION1LINETOT=1 
SET STORY22VERSION2LINE1=You met the Alchemist, who offered to create and combine items for you.  
SET STORY22VERSION2LINE2=You could potentially create some incredibly powerful items here (Hint hint)  
SET /a STORY22VERSION2LINETOT=2 
SET STORY23VERSION1LINE1=You spoke to %SEAKINGNAME% and he refused to remove the mist.  
SET STORY23VERSION1LINE2=You walked away, vowing to find a way to remove it  
SET /a STORY23VERSION1LINETOT=2 
SET STORY23VERSION2LINE1=You spoke to %SEAKINGNAME% and he refused to remove the mist.  
SET STORY23VERSION2LINE2=You tried to force him to do it but weren't strong enough  
SET /a STORY23VERSION2LINETOT=2 
SET STORY23VERSION3LINE1=You spoke to %SEAKINGNAME% and he refused to remove the mist.  
SET STORY23VERSION3LINE2=You defeated his guards and him, finding the !KEYITEM%MAGSTONE2ID%NAME! and removing the mist^!  
SET /a STORY23VERSION3LINETOT=2 
SET STORY24VERSION1LINE1=You entered the forest to find that the mist was gone^!  
SET /a STORY24VERSION1LINETOT=1 
SET STORY25VERSION1LINE1=In the forest you found a lovely looking Christmas Tree, but when you approached it you were  
SET STORY25VERSION1LINE2=ambused by a Bandit who was trying to mug you.  
SET STORY25VERSION1LINE3=You gave him some gil and he let you leave. Don't worry, you'll get revenge on him soon^!  
SET /a STORY25VERSION1LINETOT=3 
SET STORY25VERSION2LINE1=In the forest you found a lovely looking Christmas Tree, but when you approached it you were  
SET STORY25VERSION2LINE2=ambused by a Bandit who was trying to mug you. You fought him but couldn't beat him.  
SET STORY25VERSION2LINE3=Don't worry, you'll beat him when you're stronger^!  
SET /a STORY25VERSION2LINETOT=3 
SET STORY25VERSION3LINE1=In the forest you found a lovely looking Christmas Tree, but when you approached it you were  
SET STORY25VERSION3LINE2=ambused by a Bandit who was trying to mug you. You fought and beat him^!  
SET /a STORY25VERSION3LINETOT=2 
SET STORY26VERSION1LINE1=The Bandit revealed his name as %BANDITNAME% and told you that he saw %FRIENDNAME% not too long ago  
SET STORY26VERSION1LINE2=%FRIENDNAME% is likely in %TOWN6NICKNAME%, you should go and look for him.  
SET STORY26VERSION1LINE3=%BANDITNAME% also gave you the !KEYITEM%MAGSTONE3ID%NAME! because he wanted to give up his life  
SET STORY26VERSION1LINE4=of crime and become a teacher. Speaking of which, catch a Dragon for him and he'll teach you Mug^!  
SET /a STORY26VERSION1LINETOT=4 
SET STORY27VERSION1LINE1=You brought %BANDITNAME% a Dragon and he taught you the Mug skill.  
SET STORY27VERSION1LINE2=It was a little underwhelming...  
SET /a STORY27VERSION1LINETOT=2 
SET /a PAGE5END = 27 
SET /a PAGE6START = 28 
SET STORY28VERSION1LINE1=You made it into %TOWN6NICKNAME%. You should speak to the Guru  
SET /a STORY28VERSION1LINETOT=1 
SET STORY28VERSION2LINE1=You made it into %TOWN6NICKNAME% and spoke to the Guru. He's just great isn't he.  
SET /a STORY28VERSION2LINETOT=1 
SET STORY29VERSION1LINE1=You approached the Hell Gate and met up with %FRIENDNAME%. You then both descended into Hell to  
SET STORY29VERSION1LINE2=face %LASTBOSSNAME% together...  
SET /a STORY29VERSION1LINETOT=2 
SET STORY30VERSION1LINE1=You and %FRIENDNAME% confronted %LASTBOSSNAME%. After a short exchange, he KO'd %FRIENDNAME%  
SET STORY30VERSION1LINE2=almost immediately and proceded to defeat you too. Man up and kill him^!  
SET /a STORY30VERSION1LINETOT=2 
SET STORY30VERSION2LINE1=You and %FRIENDNAME% confronted %LASTBOSSNAME%. After a short exchange, he KO'd %FRIENDNAME%  
SET STORY30VERSION2LINE2=almost immediately but you were able to defeat him. Good job Bozo  
SET /a PAGE6END = 30 
SET /a PAGETOT = 6 
SET /a STORYTOT = 30 
