SET /a MINNAMELENGTH = 5
::SET /a MINNAMELENGTH = 1
SET /a COUNT=0
:HASTESPELLSUPPS
SET /a COUNT=%COUNT%+1
SET SUPP%COUNT%SPELL=Haste
SET /a !SUPP%COUNT%SPELL!ID = %COUNT%
SET SUPP%COUNT%DESCRIPTION=Temporarily increases your Speed
SET SUPP%COUNT%ANIMATION=SELFSPELL
SET /a SUPP%COUNT%ACCURACY = 9999
SET /a SUPP%COUNT%MPCOST = 5
SET /a SUPP%COUNT%UNLOCKLVL = 5
SET SUPP%COUNT%PREREQUISITE=NONE
SET /a SUPP%COUNT%REFLECTABLE = 0
SET /a SUPP%COUNT%EFFECTSNUM = 1
SET SUPP%COUNT%EFFECT1ELEMENT=NONE
SET SUPP%COUNT%EFFECT1TYPE=STATUS
SET SUPP%COUNT%EFFECT1ATTRIBUTE=Haste
SET SUPP%COUNT%EFFECT1TARGET=ATTACKER
SET /a SUPP%COUNT%EFFECT1AMOUNT = 1
SET /a SUPP%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a SUPP%COUNT%EFFECT1MAXTURNCOUNT = 6
SET SUPP%COUNT%EFFECT1PLAYERTEXT=now has the !SUPP%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH

:PROTECTSPELLSUPPS
SET /a COUNT=%COUNT%+1
SET SUPP%COUNT%SPELL=Protect
SET /a !SUPP%COUNT%SPELL!ID = %COUNT%
SET SUPP%COUNT%DESCRIPTION=Halves damage from physical attacks
SET SUPP%COUNT%ANIMATION=SELFSPELL
SET /a SUPP%COUNT%ACCURACY = 9999
SET /a SUPP%COUNT%MPCOST = 15
SET /a SUPP%COUNT%UNLOCKLVL = 10
SET SUPP%COUNT%PREREQUISITE=NONE
SET /a SUPP%COUNT%REFLECTABLE = 0
SET /a SUPP%COUNT%EFFECTSNUM = 1
SET SUPP%COUNT%EFFECT1ELEMENT=NONE
SET SUPP%COUNT%EFFECT1TYPE=STATUS
SET SUPP%COUNT%EFFECT1ATTRIBUTE=Protect
SET SUPP%COUNT%EFFECT1TARGET=ATTACKER
SET /a SUPP%COUNT%EFFECT1AMOUNT = 1
SET /a SUPP%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a SUPP%COUNT%EFFECT1MAXTURNCOUNT = 6
SET SUPP%COUNT%EFFECT1PLAYERTEXT=now has the !SUPP%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:SHELLSPELLSUPPS
SET /a COUNT=%COUNT%+1
SET SUPP%COUNT%SPELL=Shell
SET /a !SUPP%COUNT%SPELL!ID = %COUNT%
SET SUPP%COUNT%DESCRIPTION=Halves damage from magical attacks
SET SUPP%COUNT%ANIMATION=SELFSPELL
SET /a SUPP%COUNT%ACCURACY = 9999
SET /a SUPP%COUNT%MPCOST = 15
SET /a SUPP%COUNT%UNLOCKLVL = 10
SET SUPP%COUNT%PREREQUISITE=NONE
SET /a SUPP%COUNT%REFLECTABLE = 0
SET /a SUPP%COUNT%EFFECTSNUM = 1
SET SUPP%COUNT%EFFECT1ELEMENT=NONE
SET SUPP%COUNT%EFFECT1TYPE=STATUS
SET SUPP%COUNT%EFFECT1ATTRIBUTE=Shell
SET SUPP%COUNT%EFFECT1TARGET=ATTACKER
SET /a SUPP%COUNT%EFFECT1AMOUNT = 1
SET /a SUPP%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a SUPP%COUNT%EFFECT1MAXTURNCOUNT = 6
SET SUPP%COUNT%EFFECT1PLAYERTEXT=now has the !SUPP%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH


:REFLECTSPELLSUPPS
SET /a COUNT=%COUNT%+1
SET SUPP%COUNT%SPELL=Reflect
SET /a !SUPP%COUNT%SPELL!ID = %COUNT%
SET SUPP%COUNT%DESCRIPTION=Reflects offensive spell damage back at the caster
SET SUPP%COUNT%ANIMATION=SELFSPELL
SET /a SUPP%COUNT%ACCURACY = 9999
SET /a SUPP%COUNT%MPCOST = 25
SET /a SUPP%COUNT%UNLOCKLVL = 25
SET SUPP%COUNT%PREREQUISITE=NONE
SET /a SUPP%COUNT%REFLECTABLE = 0
SET /a SUPP%COUNT%EFFECTSNUM = 1
SET SUPP%COUNT%EFFECT1ELEMENT=NONE
SET SUPP%COUNT%EFFECT1TYPE=STATUS
SET SUPP%COUNT%EFFECT1ATTRIBUTE=Reflect
SET SUPP%COUNT%EFFECT1TARGET=ATTACKER
SET /a SUPP%COUNT%EFFECT1AMOUNT = 1
SET /a SUPP%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT1MINTURNCOUNT = 3
SET /a SUPP%COUNT%EFFECT1MAXTURNCOUNT = 6
SET SUPP%COUNT%EFFECT1PLAYERTEXT=now has the !SUPP%COUNT%EFFECT1ATTRIBUTE! status active^^!
CALL :SPELLNAMELENGTH

:DISPELSPELLSUPPS
SET /a COUNT=%COUNT%+1
SET SUPP%COUNT%SPELL=Dispel
SET /a !SUPP%COUNT%SPELL!ID = %COUNT%
SET SUPP%COUNT%DESCRIPTION=Removes enemy's positive status effects
SET SUPP%COUNT%ANIMATION=DRAINSPELL
SET /a SUPP%COUNT%ACCURACY = 80
SET /a SUPP%COUNT%MPCOST = 10
SET /a SUPP%COUNT%UNLOCKLVL = 15
SET SUPP%COUNT%PREREQUISITE=NONE
SET /a SUPP%COUNT%REFLECTABLE = 0
SET /a SUPP%COUNT%EFFECTSNUM = 4
SET SUPP%COUNT%EFFECT1ELEMENT=NONE
SET SUPP%COUNT%EFFECT1TYPE=STATUS
SET SUPP%COUNT%EFFECT1ATTRIBUTE=Haste
SET SUPP%COUNT%EFFECT1TARGET=DEFENDER
SET /a SUPP%COUNT%EFFECT1AMOUNT = 0
SET /a SUPP%COUNT%EFFECT1FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT1MINTURNCOUNT = 0
SET /a SUPP%COUNT%EFFECT1MAXTURNCOUNT = 0
SET SUPP%COUNT%EFFECT1PLAYERTEXT=no longer has the !SUPP%COUNT%EFFECT1ATTRIBUTE! status^^!
SET SUPP%COUNT%EFFECT2ELEMENT=NONE
SET SUPP%COUNT%EFFECT2TYPE=STATUS
SET SUPP%COUNT%EFFECT2ATTRIBUTE=Protect
SET SUPP%COUNT%EFFECT2TARGET=DEFENDER
SET /a SUPP%COUNT%EFFECT2AMOUNT = 0
SET /a SUPP%COUNT%EFFECT2FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT2MINTURNCOUNT = 0
SET /a SUPP%COUNT%EFFECT2MAXTURNCOUNT = 0
SET SUPP%COUNT%EFFECT2PLAYERTEXT=no longer has the !SUPP%COUNT%EFFECT2ATTRIBUTE! status^^!
SET SUPP%COUNT%EFFECT3ELEMENT=NONE
SET SUPP%COUNT%EFFECT3TYPE=STATUS
SET SUPP%COUNT%EFFECT3ATTRIBUTE=Shell
SET SUPP%COUNT%EFFECT3TARGET=DEFENDER
SET /a SUPP%COUNT%EFFECT3AMOUNT = 0
SET /a SUPP%COUNT%EFFECT3FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT3MINTURNCOUNT = 0
SET /a SUPP%COUNT%EFFECT3MAXTURNCOUNT = 0
SET SUPP%COUNT%EFFECT3PLAYERTEXT=no longer has the !SUPP%COUNT%EFFECT3ATTRIBUTE! status^^!
SET SUPP%COUNT%EFFECT4ELEMENT=NONE
SET SUPP%COUNT%EFFECT4TYPE=STATUS
SET SUPP%COUNT%EFFECT4ATTRIBUTE=Reflect
SET SUPP%COUNT%EFFECT4TARGET=DEFENDER
SET /a SUPP%COUNT%EFFECT4AMOUNT = 0
SET /a SUPP%COUNT%EFFECT4FIXEDAMOUNT = 1
SET /a SUPP%COUNT%EFFECT4MINTURNCOUNT = 0
SET /a SUPP%COUNT%EFFECT4MAXTURNCOUNT = 0
SET SUPP%COUNT%EFFECT4PLAYERTEXT=no longer has the !SUPP%COUNT%EFFECT4ATTRIBUTE! status^^!
CALL :SPELLNAMELENGTH


SET /a SUPPSPELLTOT = %COUNT%


GOTO :EOF

:SPELLNAMELENGTH
SET /a SUPP%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:SPELLNAMELOOPSTART
SET /a SUPP%COUNT%NAMELENGTH += 1
SET TEMP1=!SUPP%COUNT%NAMELENGTH!
SET SUBSTR=!SUPP%COUNT%SPELL:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPELLNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !SUPP%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!SUPP%COUNT%SPELL:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPELLNAMELOOPSTART
	)
)
GOTO :EOF
