SET /a COUNT = 0
:TOWN1
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 8
SET /a TOWN%COUNT%TELEPORTYCOORD = 3
:TOWN2
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 5
SET /a TOWN%COUNT%TELEPORTYCOORD = 7
:TOWN3
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 7
SET /a TOWN%COUNT%TELEPORTYCOORD = 5
:TOWN4
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 10
SET /a TOWN%COUNT%TELEPORTYCOORD = 4
:TOWN5
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 3
SET /a TOWN%COUNT%TELEPORTYCOORD = 4
:TOWN6
SET /a COUNT = %COUNT% + 1
SET /a TOWN%COUNT%TELEPORTXCOORD = 10
SET /a TOWN%COUNT%TELEPORTYCOORD = 3

SET /a TOWNTOT = %COUNT%