SET /a MINNAMELENGTH = 4
::SET /a MINNAMELENGTH = 1
SET /a COUNT = 0
SET /a WEAPONSTART = %COUNT%
:KTAPE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Knuckle Tape
SET WEAPON%COUNT%NICKNAME=KTAPE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 1
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !MEDID!
SET /a WEAPON%COUNT%COST = 100
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 0
SET /a WEAPON%COUNT%MAXSKL = 10
SET /a WEAPON%COUNT%QUANTDIV = 5
SET /a WEAPON%COUNT%EXP = 5
::CALL :WEAPONNAMELENGTH


:CBONE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Sharp Chicken Bone
SET WEAPON%COUNT%NICKNAME=CBONE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 2
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !FLEEID!
SET /a WEAPON%COUNT%COST = 200
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 0
SET /a WEAPON%COUNT%MAXSKL = 10
SET /a WEAPON%COUNT%QUANTDIV = 10
SET /a WEAPON%COUNT%EXP = 7
::CALL :WEAPONNAMELENGTH

:GGLOVES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Goth Gloves
SET WEAPON%COUNT%NICKNAME=GGLOVES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 1
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%SKILL2 = !SCANID!
SET /a WEAPON%COUNT%COST = 250
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 5
SET /a WEAPON%COUNT%MAXSKL = 15
SET /a WEAPON%COUNT%QUANTDIV = 8
SET /a WEAPON%COUNT%EXP = 8
::CALL :WEAPONNAMELENGTH

:DSTICK
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Drum Stick
SET WEAPON%COUNT%NICKNAME=DSTICK
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 3
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 400
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 2
SET /a WEAPON%COUNT%MAXSKL = 15
SET /a WEAPON%COUNT%QUANTDIV = 15
SET /a WEAPON%COUNT%EXP = 8
::CALL :WEAPONNAMELENGTH

:WLSTICK
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Wand-looking Stick
SET WEAPON%COUNT%NICKNAME=WLSTICK
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 3
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !HIDEID!
SET /a WEAPON%COUNT%COST = 400
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 10
SET /a WEAPON%COUNT%MAXSKL = 15
SET /a WEAPON%COUNT%QUANTDIV = 10
SET /a WEAPON%COUNT%EXP = 8
::CALL :WEAPONNAMELENGTH

:BKNIFE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Blunt Butter Knife
SET WEAPON%COUNT%NICKNAME=BKNIFE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 3
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 450
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 5
SET /a WEAPON%COUNT%MAXSKL = 15
SET /a WEAPON%COUNT%QUANTDIV = 15
SET /a WEAPON%COUNT%EXP = 10
::CALL :WEAPONNAMELENGTH

:LWLSTICK
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Long Wand-looking Stick
SET WEAPON%COUNT%NICKNAME=LWLSTICK
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 3
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !FIRESTRIKEID!
SET /a WEAPON%COUNT%COST = 500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 10
SET /a WEAPON%COUNT%MAXSKL = 25
SET /a WEAPON%COUNT%QUANTDIV = 10
SET /a WEAPON%COUNT%EXP = 10
::CALL :WEAPONNAMELENGTH

:HOMEMADEBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Homemade Bow
SET WEAPON%COUNT%NICKNAME=HOMEMADEBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 2
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 5
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 5
SET /a WEAPON%COUNT%MAXSKL = 25
SET /a WEAPON%COUNT%QUANTDIV = 15
SET /a WEAPON%COUNT%EXP = 20
::CALL :WEAPONNAMELENGTH

:SHIV
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Shiv
SET WEAPON%COUNT%NICKNAME=SHIV
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 4
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !MSTRIKEID!
SET /a WEAPON%COUNT%COST = 600
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 15
SET /a WEAPON%COUNT%MAXSKL = 30
SET /a WEAPON%COUNT%QUANTDIV = 25
SET /a WEAPON%COUNT%EXP = 30
::CALL :WEAPONNAMELENGTH


:SSWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Short Sword
SET WEAPON%COUNT%NICKNAME=SSWORD
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 600
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 10
SET /a WEAPON%COUNT%MAXSKL = 25
SET /a WEAPON%COUNT%QUANTDIV = 30
SET /a WEAPON%COUNT%EXP = 30
::CALL :WEAPONNAMELENGTH

:SSWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Plywood Staff
SET WEAPON%COUNT%NICKNAME=PSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 2
SET /a WEAPON%COUNT%MAG = 3
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !FOCID!
SET /a WEAPON%COUNT%COST = 700
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 25
SET /a WEAPON%COUNT%EXP = 40
::CALL :WEAPONNAMELENGTH

:SBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Short Bow
SET WEAPON%COUNT%NICKNAME=SBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 2
SET /a WEAPON%COUNT%MAG = 1
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 800
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 25
SET /a WEAPON%COUNT%EXP = 40
::CALL :WEAPONNAMELENGTH

:SWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Sword
SET WEAPON%COUNT%NICKNAME=SWORD
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 6
SET /a WEAPON%COUNT%MAG = 2
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !MEDID!
SET /a WEAPON%COUNT%COST = 1000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 35
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:IKEASTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Ikea Staff
SET WEAPON%COUNT%NICKNAME=IKEASTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 2
SET /a WEAPON%COUNT%MAG = 6
SET /a WEAPON%COUNT%ACC = 2
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !FOCID!
SET /a WEAPON%COUNT%COST = 1100
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 1
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 30
SET /a WEAPON%COUNT%MAXSKL = 45
SET /a WEAPON%COUNT%QUANTDIV = 25
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:LEADPIPE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Lead Pipe
SET WEAPON%COUNT%NICKNAME=LEADPIPE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 6
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEID!
SET /a WEAPON%COUNT%COST = 700
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 15
SET /a WEAPON%COUNT%MAXSKL = 30
SET /a WEAPON%COUNT%QUANTDIV = 30
SET /a WEAPON%COUNT%EXP = 45
::CALL :WEAPONNAMELENGTH

:GKNUCKLES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Glass Knuckles
SET WEAPON%COUNT%NICKNAME=GKNUCKLES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 4
SET /a WEAPON%COUNT%MAG = 1
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !SDATTID!
SET /a WEAPON%COUNT%COST = 750
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 35
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:HTRIM
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Hedge Trimmers
SET WEAPON%COUNT%NICKNAME=HTRIM
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 4
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%COST = 800
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 35
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:GOBSTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Goblin Staff
SET WEAPON%COUNT%NICKNAME=GOBSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 6
SET /a WEAPON%COUNT%ACC = 5
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !MPATTID!
SET /a WEAPON%COUNT%COST = 800
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 30
SET /a WEAPON%COUNT%MAXSKL = 45
SET /a WEAPON%COUNT%QUANTDIV = 25
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:ECARVE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Electric Carving Knife
SET WEAPON%COUNT%NICKNAME=ECARVE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 6
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !ELECTRICSTRIKEID!
SET /a WEAPON%COUNT%SKILL2 = !SDATTID!
SET /a WEAPON%COUNT%COST = 850
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 35
SET /a WEAPON%COUNT%QUANTDIV = 40
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:ECARVE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Knuckle Duster
SET WEAPON%COUNT%NICKNAME=KDUSTER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 1
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEID!
SET /a WEAPON%COUNT%COST = 900
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 20
SET /a WEAPON%COUNT%MAXSKL = 40
SET /a WEAPON%COUNT%QUANTDIV = 32
SET /a WEAPON%COUNT%EXP = 50
::CALL :WEAPONNAMELENGTH

:PSWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Pirate Sword
SET WEAPON%COUNT%NICKNAME=PSWORD
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 9
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 0
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEID!
SET /a WEAPON%COUNT%SKILL2 = !STLID!
SET /a WEAPON%COUNT%COST = 1300
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 25
SET /a WEAPON%COUNT%MAXSKL = 40
SET /a WEAPON%COUNT%QUANTDIV = 40
SET /a WEAPON%COUNT%EXP = 65
::CALL :WEAPONNAMELENGTH

:CROSSBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Crossbow
SET WEAPON%COUNT%NICKNAME=CROSSBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 4
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 15
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEID!
SET /a WEAPON%COUNT%COST = 1500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 25
SET /a WEAPON%COUNT%MAXSKL = 45
SET /a WEAPON%COUNT%QUANTDIV = 35
SET /a WEAPON%COUNT%EXP = 65
::CALL :WEAPONNAMELENGTH

:YEWWAND
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Yew Wand
SET WEAPON%COUNT%NICKNAME=YEWWAND
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 7
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL2 = !DETECTID!
SET /a WEAPON%COUNT%SKILL3 = !FOCID!
SET /a WEAPON%COUNT%COST = 1500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 1
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 30
SET /a WEAPON%COUNT%MAXSKL = 50
SET /a WEAPON%COUNT%QUANTDIV = 35
SET /a WEAPON%COUNT%EXP = 75
::CALL :WEAPONNAMELENGTH

:NINJASTAR
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Ninja Stars
SET WEAPON%COUNT%NICKNAME=NINJASTAR
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 5
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !STLID!
SET /a WEAPON%COUNT%SKILL2 = !PILGILID!
SET /a WEAPON%COUNT%COST = 1500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 40
SET /a WEAPON%COUNT%MAXSKL = 60
SET /a WEAPON%COUNT%QUANTDIV = 40
SET /a WEAPON%COUNT%EXP = 100
::CALL :WEAPONNAMELENGTH

:DAGGER
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Dagger
SET WEAPON%COUNT%NICKNAME=DAGGER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 8
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 12
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEID!
SET /a WEAPON%COUNT%COST = 1800
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 40
SET /a WEAPON%COUNT%MAXSKL = 60
SET /a WEAPON%COUNT%QUANTDIV = 40
SET /a WEAPON%COUNT%EXP = 100
::CALL :WEAPONNAMELENGTH

:LONGBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Longbow
SET WEAPON%COUNT%NICKNAME=LONGBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 5
SET /a WEAPON%COUNT%ACC = 20
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 2300
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 50
SET /a WEAPON%COUNT%MAXSKL = 70
SET /a WEAPON%COUNT%QUANTDIV = 45
SET /a WEAPON%COUNT%EXP = 120
::CALL :WEAPONNAMELENGTH

:CLEAVER
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Cleaver
SET WEAPON%COUNT%NICKNAME=CLEAVER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 13
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 8
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !MEDID!
SET /a WEAPON%COUNT%SKILL2 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 2300
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 45
SET /a WEAPON%COUNT%MAXSKL = 65
SET /a WEAPON%COUNT%QUANTDIV = 60
SET /a WEAPON%COUNT%EXP = 150
::CALL :WEAPONNAMELENGTH

:SKNUCKLES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Spiked Knucles
SET WEAPON%COUNT%NICKNAME=SKNUCKLES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 9
SET /a WEAPON%COUNT%MAG = 3
SET /a WEAPON%COUNT%ACC = 9
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !SCATTID!
SET /a WEAPON%COUNT%COST = 2500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 50
SET /a WEAPON%COUNT%MAXSKL = 70
SET /a WEAPON%COUNT%QUANTDIV = 50
SET /a WEAPON%COUNT%EXP = 130
::CALL :WEAPONNAMELENGTH

:FWAND
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Faerie Wand
SET WEAPON%COUNT%NICKNAME=FWAND
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 5
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !FOCID!
SET /a WEAPON%COUNT%SKILL2 = !WATERSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !HEALMPSKILLID!
SET /a WEAPON%COUNT%COST = 2200
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 55
SET /a WEAPON%COUNT%MAXSKL = 75
SET /a WEAPON%COUNT%QUANTDIV = 50
SET /a WEAPON%COUNT%EXP = 150
::CALL :WEAPONNAMELENGTH

:OAKSTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Oak Staff
SET WEAPON%COUNT%NICKNAME=OSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 3
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 4
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !FOCID!
SET /a WEAPON%COUNT%SKILL2 = !EARTHSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEID!
SET /a WEAPON%COUNT%COST = 2600
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 55
SET /a WEAPON%COUNT%MAXSKL = 75
SET /a WEAPON%COUNT%QUANTDIV = 60
SET /a WEAPON%COUNT%EXP = 200
::CALL :WEAPONNAMELENGTH

:SAMSWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Samurai Sword
SET WEAPON%COUNT%NICKNAME=SAMSWORD
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 15
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 3
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !SDATTID!
SET /a WEAPON%COUNT%SKILL2 = !SCATTID!
SET /a WEAPON%COUNT%COST = 2900
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 1
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 40
SET /a WEAPON%COUNT%MAXSKL = 65
SET /a WEAPON%COUNT%QUANTDIV = 70
SET /a WEAPON%COUNT%EXP = 250
::CALL :WEAPONNAMELENGTH

:WIZSTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Wizard Staff
SET WEAPON%COUNT%NICKNAME=WIZSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 3
SET /a WEAPON%COUNT%MAG = 15
SET /a WEAPON%COUNT%ACC = 5
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !SCANID!
SET /a WEAPON%COUNT%SKILL2 = !HEALHPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !HEALMPSKILLPLUSID!
SET /a WEAPON%COUNT%COST = 3500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 65
SET /a WEAPON%COUNT%MAXSKL = 95
SET /a WEAPON%COUNT%QUANTDIV = 65
SET /a WEAPON%COUNT%EXP = 300
::CALL :WEAPONNAMELENGTH

:HKNIFE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Hunting Knife
SET WEAPON%COUNT%NICKNAME=HKNIFE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 14
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !MSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 3200
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 60
SET /a WEAPON%COUNT%MAXSKL = 85
SET /a WEAPON%COUNT%QUANTDIV = 75
SET /a WEAPON%COUNT%EXP = 310
::CALL :WEAPONNAMELENGTH

:MKNUCKLES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Mythril Knuckles
SET WEAPON%COUNT%NICKNAME=MKNUCKLES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 10
SET /a WEAPON%COUNT%MAG = 6
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !STLID!
SET /a WEAPON%COUNT%SKILL2 = !GILTOSSID!
SET /a WEAPON%COUNT%COST = 3400
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 65
SET /a WEAPON%COUNT%MAXSKL = 95
SET /a WEAPON%COUNT%QUANTDIV = 65
SET /a WEAPON%COUNT%EXP = 320
::CALL :WEAPONNAMELENGTH

:FOULWORDS
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Book of Foul Words
SET WEAPON%COUNT%NICKNAME=FOULWORDS
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 20
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL2 = !HEALMPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !GILTOSSID!
SET /a WEAPON%COUNT%COST = 3500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 75
SET /a WEAPON%COUNT%MAXSKL = 110
SET /a WEAPON%COUNT%QUANTDIV = 65
SET /a WEAPON%COUNT%EXP = 350
::CALL :WEAPONNAMELENGTH

:DILDO
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Magical Wooden Dildo
SET WEAPON%COUNT%NICKNAME=DILDO
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 10
SET /a WEAPON%COUNT%MAG = 12
SET /a WEAPON%COUNT%ACC = 16
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 3500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 75
SET /a WEAPON%COUNT%MAXSKL = 110
SET /a WEAPON%COUNT%QUANTDIV = 65
SET /a WEAPON%COUNT%EXP = 350
::CALL :WEAPONNAMELENGTH

:BFLYKNIFE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Butterfly Knife
SET WEAPON%COUNT%NICKNAME=BFLYKNIFE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 14
SET /a WEAPON%COUNT%MAG = 6
SET /a WEAPON%COUNT%ACC = 12
SET /a WEAPON%COUNT%SKILLTOT = 1
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 4000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 60
SET /a WEAPON%COUNT%MAXSKL = 90
SET /a WEAPON%COUNT%QUANTDIV = 80
SET /a WEAPON%COUNT%EXP = 370
::CALL :WEAPONNAMELENGTH

:ELVENBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Elven Bow
SET WEAPON%COUNT%NICKNAME=ELVENBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 30
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !AIMID!
SET /a WEAPON%COUNT%COST = 4200
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 85
SET /a WEAPON%COUNT%MAXSKL = 120
SET /a WEAPON%COUNT%QUANTDIV = 65
SET /a WEAPON%COUNT%EXP = 400
::CALL :WEAPONNAMELENGTH

:GUNBLADE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Gunblade
SET WEAPON%COUNT%NICKNAME=GUNBLADE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 15
SET /a WEAPON%COUNT%MAG = 3
SET /a WEAPON%COUNT%ACC = 15
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !PILGILID!
SET /a WEAPON%COUNT%SKILL2 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 4200
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 80
SET /a WEAPON%COUNT%MAXSKL = 120
SET /a WEAPON%COUNT%QUANTDIV = 90
SET /a WEAPON%COUNT%EXP = 420
::CALL :WEAPONNAMELENGTH

:HIGHMAGESTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=High Wizard Staff
SET WEAPON%COUNT%NICKNAME=HIGHWIZSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 4
SET /a WEAPON%COUNT%MAG = 23
SET /a WEAPON%COUNT%ACC = 6
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL2 = !HEALHPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !HEALMPSKILLPLUSID!
SET /a WEAPON%COUNT%COST = 5000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 100
SET /a WEAPON%COUNT%MAXSKL = 140
SET /a WEAPON%COUNT%QUANTDIV = 85
SET /a WEAPON%COUNT%EXP = 480
::CALL :WEAPONNAMELENGTH

:BUSTERSWORD
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Buster Sword
SET WEAPON%COUNT%NICKNAME=BUSTERSWORD
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 20
SET /a WEAPON%COUNT%MAG = 8
SET /a WEAPON%COUNT%ACC = 15
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !MPHPATTID!
SET /a WEAPON%COUNT%COST = 5000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 1
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 80
SET /a WEAPON%COUNT%MAXSKL = 120
SET /a WEAPON%COUNT%QUANTDIV = 110
SET /a WEAPON%COUNT%EXP = 500
::CALL :WEAPONNAMELENGTH

:CREDARM
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Chris Redfield's Arm
SET WEAPON%COUNT%NICKNAME=CREDARM
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 25
SET /a WEAPON%COUNT%MAG = 0
SET /a WEAPON%COUNT%ACC = 10
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !MEDID!
SET /a WEAPON%COUNT%COST = 4500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 70
SET /a WEAPON%COUNT%MAXSKL = 110
SET /a WEAPON%COUNT%QUANTDIV = 120
SET /a WEAPON%COUNT%EXP = 500
::CALL :WEAPONNAMELENGTH

:ELDERWAND
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Elder Wand
SET WEAPON%COUNT%NICKNAME=ELDERWAND
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 25
SET /a WEAPON%COUNT%ACC = 15
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL2 = !GILTRANSID!
SET /a WEAPON%COUNT%COST = 6000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 90
SET /a WEAPON%COUNT%MAXSKL = 140
SET /a WEAPON%COUNT%QUANTDIV = 100
SET /a WEAPON%COUNT%EXP = 600
::CALL :WEAPONNAMELENGTH

:FIREELDERWAND
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Elder Wand
SET WEAPON%COUNT%NICKNAME=FIREELDERWAND
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 0
SET /a WEAPON%COUNT%MAG = 50
SET /a WEAPON%COUNT%ACC = 30
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL2 = !GILTRANSID!
SET /a WEAPON%COUNT%SKILL3 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 6000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 150
SET /a WEAPON%COUNT%MAXSKL = 200
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 1000
::CALL :WEAPONNAMELENGTH

:GKNUCKLES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Galva-Knuckles
SET WEAPON%COUNT%NICKNAME=GKNUCKLES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 20
SET /a WEAPON%COUNT%MAG = 5
SET /a WEAPON%COUNT%ACC = 20
SET /a WEAPON%COUNT%SKILLTOT = 4
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEID!
SET /a WEAPON%COUNT%SKILL2 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !ELECTRICSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !SCATTID!
SET /a WEAPON%COUNT%COST = 6000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 90
SET /a WEAPON%COUNT%MAXSKL = 140
SET /a WEAPON%COUNT%QUANTDIV = 100
SET /a WEAPON%COUNT%EXP = 600
::CALL :WEAPONNAMELENGTH

:FIREGKNUCKLES
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Galva-Knuckles
SET WEAPON%COUNT%NICKNAME=FIREGKNUCKLES
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 40
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 40
SET /a WEAPON%COUNT%SKILLTOT = 5
SET /a WEAPON%COUNT%SKILL1 = !POWSTRIKEID!
SET /a WEAPON%COUNT%SKILL2 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !ELECTRICSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !SCATTID!
SET /a WEAPON%COUNT%SKILL5 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 6000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 150
SET /a WEAPON%COUNT%MAXSKL = 200
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 1000
::CALL :WEAPONNAMELENGTH

:DRAGONBOW
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Dragon Bow
SET WEAPON%COUNT%NICKNAME=DRAGONBOW
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 8
SET /a WEAPON%COUNT%MAG = 8
SET /a WEAPON%COUNT%ACC = 50
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%SKILL2 = !AIMSTRIKEID!
SET /a WEAPON%COUNT%COST = 4500
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 90
SET /a WEAPON%COUNT%MAXSKL = 140
SET /a WEAPON%COUNT%QUANTDIV = 100
SET /a WEAPON%COUNT%EXP = 500
::CALL :WEAPONNAMELENGTH

:DRAGONBOWZ
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Dragon Bow Z
SET WEAPON%COUNT%NICKNAME=DRAGONBOWZ
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 10
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 60
SET /a WEAPON%COUNT%SKILLTOT = 5
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%SKILL2 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !MSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL5 = !SCATTID!
SET /a WEAPON%COUNT%COST = 8000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 90
SET /a WEAPON%COUNT%MAXSKL = 140
SET /a WEAPON%COUNT%QUANTDIV = 100
SET /a WEAPON%COUNT%EXP = 700
::CALL :WEAPONNAMELENGTH

:FIREDRAGONBOWZ
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Dragon Bow Z
SET WEAPON%COUNT%NICKNAME=FIREDRAGONBOWZ
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 20
SET /a WEAPON%COUNT%MAG = 20
SET /a WEAPON%COUNT%ACC = 120
SET /a WEAPON%COUNT%SKILLTOT = 6
SET /a WEAPON%COUNT%SKILL1 = !AIMID!
SET /a WEAPON%COUNT%SKILL2 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !MSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL5 = !SCATTID!
SET /a WEAPON%COUNT%SKILL6 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 8000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 150
SET /a WEAPON%COUNT%MAXSKL = 250
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 1100
::CALL :WEAPONNAMELENGTH

:NOONELIKESGT
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=No one likes GT
SET WEAPON%COUNT%NICKNAME=NOONELIKESGT
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 1
SET /a WEAPON%COUNT%MAG = 1
SET /a WEAPON%COUNT%ACC = 1
SET /a WEAPON%COUNT%SKILLTOT = 0
SET /a WEAPON%COUNT%COST = 1
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 1
SET /a WEAPON%COUNT%MAXSKL = 1
SET /a WEAPON%COUNT%QUANTDIV = 1
SET /a WEAPON%COUNT%EXP = 1
::CALL :WEAPONNAMELENGTH

:MACHETE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Machete
SET WEAPON%COUNT%NICKNAME=MACHETE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 25
SET /a WEAPON%COUNT%MAG = 8
SET /a WEAPON%COUNT%ACC = 18
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !PILGILID!
SET /a WEAPON%COUNT%COST = 8000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 80
SET /a WEAPON%COUNT%MAXSKL = 120
SET /a WEAPON%COUNT%QUANTDIV = 140
SET /a WEAPON%COUNT%EXP = 800
::CALL :WEAPONNAMELENGTH

:FIREMACHETE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Machete
SET WEAPON%COUNT%NICKNAME=FIREMACHETE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 50
SET /a WEAPON%COUNT%MAG = 16
SET /a WEAPON%COUNT%ACC = 36
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !PILGILID!
SET /a WEAPON%COUNT%SKILL3 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 8000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 130
SET /a WEAPON%COUNT%MAXSKL = 200
SET /a WEAPON%COUNT%QUANTDIV = 200
SET /a WEAPON%COUNT%EXP = 1200
::CALL :WEAPONNAMELENGTH

:GANDSTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Gandalf's Staff
SET WEAPON%COUNT%NICKNAME=GANDSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 10
SET /a WEAPON%COUNT%MAG = 30
SET /a WEAPON%COUNT%ACC = 8
SET /a WEAPON%COUNT%SKILLTOT = 5
SET /a WEAPON%COUNT%SKILL1 = !FORBIDDENSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !MPHPATTID!
SET /a WEAPON%COUNT%SKILL3 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL4 = !HEALHPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL5 = !HEALMPSKILLPLUSID!
SET /a WEAPON%COUNT%COST = 10000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 120
SET /a WEAPON%COUNT%MAXSKL = 250
SET /a WEAPON%COUNT%QUANTDIV = 120
SET /a WEAPON%COUNT%EXP = 900
::CALL :WEAPONNAMELENGTH

:FIREGANDSTAFF
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Gandalf's Staff
SET WEAPON%COUNT%NICKNAME=FIREGANDSTAFF
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 20
SET /a WEAPON%COUNT%MAG = 60
SET /a WEAPON%COUNT%ACC = 16
SET /a WEAPON%COUNT%SKILLTOT = 6
SET /a WEAPON%COUNT%SKILL1 = !FORBIDDENSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !MPHPATTID!
SET /a WEAPON%COUNT%SKILL3 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL4 = !HEALHPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL5 = !HEALMPSKILLPLUSID!
SET /a WEAPON%COUNT%SKILL6 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 10000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 180
SET /a WEAPON%COUNT%MAXSKL = 270
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 1300
::CALL :WEAPONNAMELENGTH

:MASAMUNE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Masamune
SET WEAPON%COUNT%NICKNAME=MASAMUNE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 30
SET /a WEAPON%COUNT%MAG = 10
SET /a WEAPON%COUNT%ACC = 15
SET /a WEAPON%COUNT%SKILLTOT = 3
SET /a WEAPON%COUNT%SKILL1 = !GILTRANSID!
SET /a WEAPON%COUNT%SKILL2 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL3 = !ITEMTRANSID!
SET /a WEAPON%COUNT%COST = 12000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 1
SET /a WEAPON%COUNT%MINSKL = 150
SET /a WEAPON%COUNT%MAXSKL = 250
SET /a WEAPON%COUNT%QUANTDIV = 180
SET /a WEAPON%COUNT%EXP = 1100
::CALL :WEAPONNAMELENGTH

:FIREMASAMUNE
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=On Fire Masamune
SET WEAPON%COUNT%NICKNAME=FIREMASAMUNE
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 60
SET /a WEAPON%COUNT%MAG = 20
SET /a WEAPON%COUNT%ACC = 30
SET /a WEAPON%COUNT%SKILLTOT = 4
SET /a WEAPON%COUNT%SKILL1 = !GILTRANSID!
SET /a WEAPON%COUNT%SKILL2 = !MPSTEALID!
SET /a WEAPON%COUNT%SKILL3 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL4 = !FIRESTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 12000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 170
SET /a WEAPON%COUNT%MAXSKL = 250
SET /a WEAPON%COUNT%QUANTDIV = 200
SET /a WEAPON%COUNT%EXP = 1500
::CALL :WEAPONNAMELENGTH

:ELESTICK
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Elemental Stick
SET WEAPON%COUNT%NICKNAME=ELESTICK
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 5
SET /a WEAPON%COUNT%MAG = 5
SET /a WEAPON%COUNT%ACC = 5
SET /a WEAPON%COUNT%SKILLTOT = 7
SET /a WEAPON%COUNT%SKILL1 = !FIRESTRIKEID!
SET /a WEAPON%COUNT%SKILL2 = !ICESTRIKEID!
SET /a WEAPON%COUNT%SKILL3 = !ELECTRICSTRIKEID!
SET /a WEAPON%COUNT%SKILL4 = !WATERSTRIKEID!
SET /a WEAPON%COUNT%SKILL5 = !EARTHSTRIKEID!
SET /a WEAPON%COUNT%SKILL6 = !FORBIDDENSTRIKEID!
SET /a WEAPON%COUNT%SKILL7 = %INDUCEWEAKNESSRANID%
SET /a WEAPON%COUNT%COST = 2000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 10
SET /a WEAPON%COUNT%MAXSKL = 20
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 5000
::CALL :WEAPONNAMELENGTH


::CURRENTLY NO WAY TO GET THIS OTHER THAT THE DWARF MINE
:TRUTHSTICK
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Truth Stick
SET WEAPON%COUNT%NICKNAME=TRUTHSTICK
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 10
SET /a WEAPON%COUNT%MAG = 15
SET /a WEAPON%COUNT%ACC = 20
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !SCANID!
SET /a WEAPON%COUNT%SKILL2 = !DETECTID!
SET /a WEAPON%COUNT%COST = 6000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 50
SET /a WEAPON%COUNT%MAXSKL = 150
SET /a WEAPON%COUNT%QUANTDIV = 85
SET /a WEAPON%COUNT%EXP = 600
::CALL :WEAPONNAMELENGTH

:LASER
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Magic, Melting Laser Gun
SET WEAPON%COUNT%NICKNAME=LASER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 25
SET /a WEAPON%COUNT%MAG = 60
SET /a WEAPON%COUNT%ACC = 20
SET /a WEAPON%COUNT%SKILLTOT = 2
SET /a WEAPON%COUNT%SKILL1 = !MPHPATTID!
SET /a WEAPON%COUNT%SKILL2 = !MPSTEALID!
SET /a WEAPON%COUNT%COST = 20000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 200
SET /a WEAPON%COUNT%MAXSKL = 600
SET /a WEAPON%COUNT%QUANTDIV = 100
SET /a WEAPON%COUNT%EXP = 2500
::CALL :WEAPONNAMELENGTH

:BAZOOKA
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Bazooka
SET WEAPON%COUNT%NICKNAME=BAZOOKA
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 60
SET /a WEAPON%COUNT%MAG = 15
SET /a WEAPON%COUNT%ACC = 30
SET /a WEAPON%COUNT%SKILLTOT = 4
SET /a WEAPON%COUNT%SKILL1 = !MSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !POWSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !AIMSTRIKEPLUSID!
SET /a WEAPON%COUNT%COST = 20000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 100
SET /a WEAPON%COUNT%MAXSKL = 600
SET /a WEAPON%COUNT%QUANTDIV = 200
SET /a WEAPON%COUNT%EXP = 2500
::CALL :WEAPONNAMELENGTH

:FUSRODAGGER
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Fus Ro Dagger
SET WEAPON%COUNT%NICKNAME=FUSRODAGGER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 40
SET /a WEAPON%COUNT%MAG = 25
SET /a WEAPON%COUNT%ACC = 80
SET /a WEAPON%COUNT%SKILLTOT = 6
SET /a WEAPON%COUNT%SKILL1 = !STLID!
SET /a WEAPON%COUNT%SKILL2 = !PILGILID!
SET /a WEAPON%COUNT%SKILL3 = !GILTRANSID!
SET /a WEAPON%COUNT%SKILL4 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL5 = !GILTOSSID!
SET /a WEAPON%COUNT%SKILL6 = !MUGID!
SET /a WEAPON%COUNT%COST = 20000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 150
SET /a WEAPON%COUNT%MAXSKL = 600
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 2500
::CALL :WEAPONNAMELENGTH

:HAMMER
SET /a COUNT=%COUNT%+1
SET WEAPON%COUNT%NAME=Thor's Hammer
SET WEAPON%COUNT%NICKNAME=HAMMER
SET /a !WEAPON%COUNT%NICKNAME!ID = %COUNT%
SET /a WEAPON%COUNT%STR = 50
SET /a WEAPON%COUNT%MAG = 50
SET /a WEAPON%COUNT%ACC = 90
SET /a WEAPON%COUNT%SKILLTOT = 9
SET /a WEAPON%COUNT%SKILL1 = !ELECTRICSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL2 = !POWSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL3 = !CRITICALSTRIKEPLUSID!
SET /a WEAPON%COUNT%SKILL4 = !SDATTID!
SET /a WEAPON%COUNT%SKILL5 = !STLID!
SET /a WEAPON%COUNT%SKILL6 = !PILGILID!
SET /a WEAPON%COUNT%SKILL7 = !GILTRANSID!
SET /a WEAPON%COUNT%SKILL8 = !ITEMTRANSID!
SET /a WEAPON%COUNT%SKILL9 = !MUGID!
SET /a WEAPON%COUNT%COST = 30000
SET /a WEAPON%COUNT%SELL = !WEAPON%COUNT%COST!/4
SET /a WEAPON%COUNT%SHOP1 = 0
SET /a WEAPON%COUNT%SHOP2 = 0
SET /a WEAPON%COUNT%SHOP3 = 0
SET /a WEAPON%COUNT%SHOP4 = 0
SET /a WEAPON%COUNT%SHOP5 = 0
SET /a WEAPON%COUNT%MINSKL = 200
SET /a WEAPON%COUNT%MAXSKL = 1000
SET /a WEAPON%COUNT%QUANTDIV = 150
SET /a WEAPON%COUNT%EXP = 3000
::CALL :WEAPONNAMELENGTH

SET /a WEAPONTOTAL = %COUNT%
SET /a WEAPONEND = %COUNT%

::CALL :RECORDNAMELENGTHS
CALL :SETNAMELENGTHS

GOTO :EOF

:WEAPONNAMELENGTH
SET /a WEAPON%COUNT%NAMELENGTH = %MINNAMELENGTH% - 1
:WEAPONNAMELOOPSTART
SET /a WEAPON%COUNT%NAMELENGTH += 1
SET TEMP1=!WEAPON%COUNT%NAMELENGTH!
SET SUBSTR=!WEAPON%COUNT%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :WEAPONNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !WEAPON%COUNT%NAMELENGTH! + 1
	SET SUBSTR=!WEAPON%COUNT%NAME:~%TEMPCOUNT%,1!s
	IF "%SUBSTR%" NEQ "" (
		GOTO :WEAPONNAMELOOPSTART
	)
)
::ECHO !WEAPON%COUNT%NAME! is !WEAPON%COUNT%NAMELENGTH! letters long
GOTO :EOF

:RECORDNAMELENGTHS
::To use this, remove all ::s from the "::CALL :WEAPONNAMELENGTH" lines so that the game can calculate the lengths. Then uncomment "CALL :RECORDWEAPONNAMELENGTHS"
SET /a COUNT = 0
:RECORDLENGTHSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a WEAPON%COUNT%NAMELENGTH = !WEAPON%COUNT%NAMELENGTH! >> C:\Game\weaponnamelengths.txt
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :RECORDLENGTHSLOOP
)
GOTO :EOF

:SETNAMELENGTHS
::This should be copied form the output of :RECORDNAMELENGTHS
SET /a WEAPON1NAMELENGTH = 12 
SET /a WEAPON2NAMELENGTH = 18 
SET /a WEAPON3NAMELENGTH = 11 
SET /a WEAPON4NAMELENGTH = 10 
SET /a WEAPON5NAMELENGTH = 18 
SET /a WEAPON6NAMELENGTH = 18 
SET /a WEAPON7NAMELENGTH = 23 
SET /a WEAPON8NAMELENGTH = 12 
SET /a WEAPON9NAMELENGTH = 4 
SET /a WEAPON10NAMELENGTH = 11 
SET /a WEAPON11NAMELENGTH = 13 
SET /a WEAPON12NAMELENGTH = 9 
SET /a WEAPON13NAMELENGTH = 5 
SET /a WEAPON14NAMELENGTH = 10 
SET /a WEAPON15NAMELENGTH = 9 
SET /a WEAPON16NAMELENGTH = 14 
SET /a WEAPON17NAMELENGTH = 14 
SET /a WEAPON18NAMELENGTH = 12 
SET /a WEAPON19NAMELENGTH = 22 
SET /a WEAPON20NAMELENGTH = 14 
SET /a WEAPON21NAMELENGTH = 12 
SET /a WEAPON22NAMELENGTH = 8 
SET /a WEAPON23NAMELENGTH = 8 
SET /a WEAPON24NAMELENGTH = 11 
SET /a WEAPON25NAMELENGTH = 6 
SET /a WEAPON26NAMELENGTH = 7 
SET /a WEAPON27NAMELENGTH = 7 
SET /a WEAPON28NAMELENGTH = 14 
SET /a WEAPON29NAMELENGTH = 11 
SET /a WEAPON30NAMELENGTH = 9 
SET /a WEAPON31NAMELENGTH = 13 
SET /a WEAPON32NAMELENGTH = 12 
SET /a WEAPON33NAMELENGTH = 13 
SET /a WEAPON34NAMELENGTH = 16 
SET /a WEAPON35NAMELENGTH = 18 
SET /a WEAPON36NAMELENGTH = 20 
SET /a WEAPON37NAMELENGTH = 15 
SET /a WEAPON38NAMELENGTH = 9 
SET /a WEAPON39NAMELENGTH = 8 
SET /a WEAPON40NAMELENGTH = 17 
SET /a WEAPON41NAMELENGTH = 12 
SET /a WEAPON42NAMELENGTH = 20 
SET /a WEAPON43NAMELENGTH = 10 
SET /a WEAPON44NAMELENGTH = 18 
SET /a WEAPON45NAMELENGTH = 14 
SET /a WEAPON46NAMELENGTH = 22 
SET /a WEAPON47NAMELENGTH = 10 
SET /a WEAPON48NAMELENGTH = 12 
SET /a WEAPON49NAMELENGTH = 20 
SET /a WEAPON50NAMELENGTH = 15 
SET /a WEAPON51NAMELENGTH = 7 
SET /a WEAPON52NAMELENGTH = 15 
SET /a WEAPON53NAMELENGTH = 15 
SET /a WEAPON54NAMELENGTH = 23 
SET /a WEAPON55NAMELENGTH = 8 
SET /a WEAPON56NAMELENGTH = 16 
SET /a WEAPON57NAMELENGTH = 15 
SET /a WEAPON58NAMELENGTH = 11 
SET /a WEAPON59NAMELENGTH = 24 
SET /a WEAPON60NAMELENGTH = 7 
SET /a WEAPON61NAMELENGTH = 13 
SET /a WEAPON62NAMELENGTH = 13 
GOTO :EOF