IF %BEATPACMAN% EQU 1 (
	GOTO :EOF
)
SET TEMPPATH=%MUSICPATH%\Maps\Cave\Pacman\Enter
SET /a STOP = 1
SET /a LOOP = 1
CALL "%MUSICPATH%\startmusic.bat"
SET /a STOP = 1
IF %CAVEMON1ALIVE% EQU 1 (
	SET MON1TOP=%CAVEMON1TOP%
	SET MON1MID=%CAVEMON1MID%
	SET MON1BOT=%CAVEMON1BOT%
) ELSE (
	SET MON1TOP=±±±±±
	SET MON1MID=±±±±±
	SET MON1BOT=±±±±±
)
IF %CAVEMON2ALIVE% EQU 1 (
	SET MON2TOP=%CAVEMON2TOP%
	SET MON2MID=%CAVEMON2MID%
	SET MON2BOT=%CAVEMON2BOT%
) ELSE (
	SET MON2TOP=±±±±±
	SET MON2MID=±±±±±
	SET MON2BOT=±±±±±
)
SET /a COUNT = 0
:CHESTLOOP
SET /a COUNT = %COUNT% + 1
IF !%MAP%CHEST%COUNT%OPEN! EQU 1 (
	SET CHEST%COUNT%TOP=%CHESTOTOP%
	SET CHEST%COUNT%MID=%CHESTOMID%
) ELSE IF !%MAP%CHEST%COUNT%OPEN! EQU 0 (
	SET CHEST%COUNT%TOP=%CHESTCTOP%
	SET CHEST%COUNT%MID=%CHESTCMID%
) 
IF %COUNT% LSS !%MAP%CHESTTOT! (
	GOTO :CHESTLOOP
)
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± ÚÄ¿ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± ^>þ³ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± ÀÄÙ ±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±± ÚÄ¿ ±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±± ^=þ³ ±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±± ÀÄÙ ±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±± ÚÄ¿ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±± ^>þ³ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±± ÀÄÙ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±± ÚÄ¿ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±± ^=þ³ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±± ÀÄÙ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º ÚV¿ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º ³þ³ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º ÀÄÙ ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º Úº¿ ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º ³þ³ ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º ÀÄÙ ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º ÚV¿ ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º ³þ³ ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º ÀÄÙ ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º Úº¿ ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º ³þ³ ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º ÀÄÙ ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º ÚV¿ ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º ³þ³ ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º ÀÄÙ ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º ÚÄ¿ ±±±±±±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º ³þ^= ±±±±±±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º ÀÄÙ ±±±±±±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±± ÚÄ¿ ±±±±±±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±± ³þ^< ±±±±±±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±± ÀÄÙ ±±±±±±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±± ÚÄ¿ ±±±±±    ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±± ³þ^= ±±±±± -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±± ÀÄÙ ±±±±± / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
CALL :WAITFORZERO
CLS
ECHO.
ECHO     ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO     º±±±±±±±±±±±±±±± ÚÄ¿     ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±± ³þ^<  -±- ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±± ÀÄÙ  / \ ±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4TOP%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHEST4MID%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1TOP%ªªªªª%CHEST3TOP%ªªªªª%MON2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1MID%ªªªªª%CHEST3MID%ªªªªª%MON2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%MON1BOT%ªªªªª%CHESTBOTT%ªªªªª%MON2BOT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1TOP%ªªªªª±±±±±ªªªªª%CHEST2TOP%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHEST1MID%ªªªªª±±±±±ªªªªª%CHEST2MID%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±ªªªªª%CHESTBOTT%ªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±ªªªªªªªªªªªªªªª±±±±±ªªªªªªªªªªªªªªª±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     º±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±º
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ºªªªªªªªªªªªªªªªªªªªª ÃÄ´ ªªªªªªªªªªªªªªªªªªªªº
ECHO     ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
SET TEMPPATH=%MUSICPATH%\Maps\Cave\Pacman\Fight
SET /a STOP = 1
SET /a LOOP = 0
CALL "%MUSICPATH%\startmusic.bat"
:PACMANBATTLE
SET /a ENEMYID = %PACMANID%
CALL "%BATTLESTARTRESOURCEPATH%\specialbattlestart.bat"
GOTO :EOF






:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF