SET /a SPACESMAX = 38
CALL "%DYNAMICRESOURCEPATH%\dynamicitemlistsell.bat"
CLS
:ITEMSHOPWELCOME
IF %DYNAMICITEMTOTAL% EQU 0 (
	GOTO :EOF
)
ECHO.
ECHO !SHOPKEEPER%SHOPNUM%NAME!: Very well sir, what Item would you like to sell?
GOTO :SELLSTART
:SELLSUCCESSFUL
CLS
ECHO.
ECHO !SHOPKEEPER%SHOPNUM%NAME!: Would you like to sell anything else sir?
:SELLSTART
ECHO.
ECHO You currently have %PLAYERGIL% Gil
ECHO.
SET /a COUNT = 0
:ITEMCHOICELOOP
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = %SPACESMAX% - !DYNAMICITEM%COUNT%NAMELENGTH!
ECHO. %COUNT% - !DYNAMICITEM%COUNT%NAME!!SPACES%SPACENUM%!(!DYNAMICITEM%COUNT%SELLPRICE! Gil) (!DYNAMICITEM%COUNT%NUM! Left)
IF %COUNT% LSS %DYNAMICITEMTOTAL% (
	GOTO :ITEMCHOICELOOP
)
ECHO. 0 - Done
ECHO.
:ITEMSELLCHOICE
SET /P ITEMSELLCHOICE=
ECHO.
IF "%ITEMSELLCHOICE%" EQU "" (
	GOTO :ITEMSELLCHOICE
) ELSE IF "%ITEMSELLCHOICE%" EQU "0" (
	GOTO :EOF
) 
IF %ITEMSELLCHOICE% GTR %DYNAMICITEMTOTAL% (
	GOTO :ITEMSELLCHOICE
) ELSE IF %ITEMSELLCHOICE% LSS 0 (
	GOTO :ITEMSELLCHOICE
)
:SELLSUCCESS
CLS
ECHO.
ECHO !SHOPKEEPER%SHOPNUM%NAME!: Thanks very much sir, have !DYNAMICITEM%ITEMSELLCHOICE%SELLPRICE! Gil
ECHO.
SET /a SELLSUCCESS = 1
SET /a PLAYERGIL = %PLAYERGIL% + !DYNAMICITEM%ITEMSELLCHOICE%SELLPRICE!
SET /a DYNAMICITEM%ITEMSELLCHOICE%NUM = !DYNAMICITEM%ITEMSELLCHOICE%NUM! - 1
CALL :SETSTATICIDS
CALL "%DYNAMICRESOURCEPATH%\dynamicitemlistsell.bat"
GOTO :SELLSUCCESSFUL


:SETSTATICIDS
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
IF "!ITEM%COUNT%NAME!" EQU "!DYNAMICITEM%ITEMSELLCHOICE%NAME!" (
	SET /a PLAYERITEM%COUNT%NUM = !DYNAMICITEM%ITEMSELLCHOICE%NUM!
	GOTO :EOF
)
IF %COUNT% LSS %ITEMTOTAL% (
	CALL :LOOPSTART
)
GOTO :EOF


:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
