CLS
ECHO.
ECHO %PRIESTNAME%: Certainly my child, the temple is always accepting donations.
ECHO.
ECHO           You have already donated %PLAYERTEMPLEDONATIONTOTAL% Gil and receive a %PLAYERTEMPLEDONATIONREDUCTION% Gil discount on all services.
ECHO           You currently have %PLAYERGIL% Gil. How much would you like to donate?
ECHO.
:TEMPLEDONATION
SET /P TEMPLEDONATIONAMOUNT=
ECHO.
IF "%TEMPLEDONATIONAMOUNT%" EQU "" (
	GOTO :TEMPLEDONATION
)
IF "%TEMPLEDONATIONAMOUNT%" EQU "0" (
	GOTO :EOF
)
IF %TEMPLEDONATIONAMOUNT% LSS 0 (
	ECHO %PRIESTNAME%: You can't donate a negative amount you idiot
	ECHO.
	pause
	GOTO :EOF
)
IF %TEMPLEDONATIONAMOUNT% GTR %PLAYERGIL% (
	ECHO %PRIESTNAME%: It appears you don't have that much money.
	CALL :WAITFORTWO
	GOTO :TEMPLEDONATION
) ELSE (
	CALL :TEMPLEDONATIONSUCCESSFUL
	CALL :DONATIONTEXT
)
pause
GOTO :EOF

:TEMPLEDONATIONSUCCESSFUL
SET /a PLAYERGIL = %PLAYERGIL% - %TEMPLEDONATIONAMOUNT%
SET /a PLAYERTEMPLEDONATIONTOTAL = %PLAYERTEMPLEDONATIONTOTAL% + %TEMPLEDONATIONAMOUNT%
SET /a PLAYERTEMPLEDONATIONREDUCTION = %PLAYERTEMPLEDONATIONTOTAL%/50
GOTO :EOF

:DONATIONTEXT
ECHO.
ECHO %PRIESTNAME%: Thank you for your donation, you will now receive %PLAYERTEMPLEDONATIONREDUCTION% gil discount on
ECHO           all temple services.
ECHO.
GOTO :EOF
	
















:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF