IF !SHOP%SHOPNUM%REMOTEACCESS! EQU 1 (
	GOTO :EOF
)
IF %SHOPNUM% EQU 1 (
	SET /a THRESHOLD = 1000
) ELSE IF %SHOPNUM% EQU 2 (
	SET /a THRESHOLD = 2000
) ELSE IF %SHOPNUM% EQU 3 (
	SET /a THRESHOLD = 3000
) ELSE IF %SHOPNUM% EQU 4 (
	SET /a THRESHOLD = 4000
) ELSE IF %SHOPNUM% EQU 5 (
	SET /a THRESHOLD = 5000
)
IF !SHOP%SHOPNUM%SPEND! GEQ %THRESHOLD% (
	CALL "%MENURESOURCEPATH%\menudisplay.bat"
	ECHO Your spendings have exceeded %THRESHOLD% gil in this shop. You can now access it remotely through the menu^^!
	ECHO.
	TIMEOUT /T 3 > nul
	SET /a REMOTEACCESSTRUE = 1
	SET /a SHOPREMOTEACCESS = 1
	SET /a SHOP%SHOPNUM%REMOTEACCESS = 1
)