:START
IF %PLAYERVAR% EQU 1 (
	SET /a ENEMYVAR = 2
) ELSE (
	SET /a ENEMYVAR = 1
)
CALL %INITIALRESOURCEPATH%\settabsvars.bat
CALL %INITIALRESOURCEPATH%\specials.bat
CALL :INITIALISEPLAYER
CALL :INITIALISEENEMY
SET CHARACTER=PLAYER1
CALL :INITIALISEGENERAL
SET CHARACTER=PLAYER2
CALL :INITIALISEGENERAL
SET /a BATTLEROUNDNUM = 0
CALL "%MULTIPLAYERRESOURCEPATH%\Battle\Battle.bat"
GOTO :START
GOTO :EOF


:INITIALISEPLAYER
SET /a COUNT = 0
:SPECIALLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!SPECIAL%COUNT%NICKNAME!
SET /a PLAYER%PLAYERVAR%%TEMP% = !PLAYER%TEMP%!
IF %COUNT% LSS %SPECIALTOT% (
	GOTO :SPECIALLOOP
)
SET PLAYER%PLAYERVAR%NAME=%PLAYERNAME%
SET /a PLAYER%PLAYERVAR%NAMELENGTH = %PLAYERNAMELENGTH%
SET /a PLAYER%PLAYERVAR%MAXHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a PLAYER%PLAYERVAR%MAXMP = %PLAYERBASEMAXMP% + %PLAYEREQUIPMAXMP%
SET /a PLAYER%PLAYERVAR%BASESTR = %PLAYERBASESTR% + %PLAYEREQUIPSTR%
SET /a PLAYER%PLAYERVAR%BASEEND = %PLAYERBASEEND% + %PLAYEREQUIPEND%
SET /a PLAYER%PLAYERVAR%BASEMAG = %PLAYERBASEMAG% + %PLAYEREQUIPMAG%
SET /a PLAYER%PLAYERVAR%BASESPR = %PLAYERBASESPR% + %PLAYEREQUIPSPR%
SET /a PLAYER%PLAYERVAR%BASEACC = %PLAYERBASEACC% + %PLAYEREQUIPACC%
SET /a PLAYER%PLAYERVAR%BASEEVA = %PLAYERBASEEVA% + %PLAYEREQUIPEVA%
SET /a PLAYER%PLAYERVAR%BASESPD = %PLAYERBASESPD% + %PLAYEREQUIPSPD%
SET /a PLAYER%PLAYERVAR%BASELCK = %PLAYERBASELCK% + %PLAYEREQUIPLCK%
SET /a PLAYER%PLAYERVAR%LVL = %PLAYERLVL%
::Sending specials to the database
curl -s %SERVERROOT%/battle/initiatespecials?battleid=%BATTLEID%^&player=%PLAYERVAR%^&ahaste=!PLAYER%PLAYERVAR%AHASTE! > nul
GOTO :EOF

:INITIALISEENEMY
SET /a LENGTH = 0
:ENEMYNAMELOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!PLAYER%ENEMYVAR%NAME:~%LENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ENEMYNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %LENGTH% + 1
	SET SUBSTR=!PLAYER%ENEMYVAR%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ENEMYNAMELOOPSTART
	)
)
SET /a PLAYER%ENEMYVAR%NAMELENGTH = %LENGTH%
::Retrieving Specials from the database
curl -s %SERVERROOT%/battle/getspecials?battleid=%BATTLEID%^&player=%ENEMYVAR% > output%PLAYERVAR%.bat
CALL output%PLAYERVAR%.bat
GOTO :EOF


:INITIALISEGENERAL
SET /a %CHARACTER%HP = !%CHARACTER%MAXHP!
SET /a %CHARACTER%MP = !%CHARACTER%MAXMP!
SET /a %CHARACTER%MAXAP = !%CHARACTER%LVL!*10
SET /a %CHARACTER%AP = 0
SET /a %CHARACTER%LIMITBREAK = 0
SET /a %CHARACTER%MAXLIMITBREAK = !%CHARACTER%MAXHP!/2
SET /a %CHARACTER%BLIND = 0
SET /a %CHARACTER%SILENCE = 0
SET /a %CHARACTER%POISON = 0
SET /a %CHARACTER%SLOW = 0
SET /a %CHARACTER%SLEEP = 0
SET /a %CHARACTER%CONFUSION = 0
SET /a %CHARACTER%STOP = 0
IF !%CHARACTER%AHASTE! EQU 0 (
	SET /a %CHARACTER%HASTE = 0
) ELSE (
	SET /a %CHARACTER%HASTE = 1
	SET /a %CHARACTER%HASTETURNCOUNT = 9999
)
SET /a %CHARACTER%PROTECT = 0
SET /a %CHARACTER%SHELL = 0
SET /a %CHARACTER%REFLECT = 0
SET /a %CHARACTER%MED = 0
SET /a %CHARACTER%FOC = 0
SET /a %CHARACTER%AIM = 0
SET /a %CHARACTER%HIDE = 0
::Will need to remove these once all specials are in the database because they will be set by output.bat during getSpecials
SET /a %CHARACTER%AUTOLIFE = 0
SET /a %CHARACTER%HALFMP = 0
SET /a %CHARACTER%HALFAP = 0
SET /a %CHARACTER%ZEROMP = 0
SET /a %CHARACTER%ZEROAP = 0
SET /a %CHARACTER%INCCRITCHANCE = 0
SET /a %CHARACTER%BREAKDAM = 0
SET /a %CHARACTER%FASTAP = 0
GOTO :EOF