IF %ENEMYID% EQU %TRAMPID% (
	IF %TRAMPCHOICE% EQU 4 (
		SET /a ENEMYSTR = 40
	) ELSE (
		SET /a ENEMYSTR = 20
	)
	IF %TRAMPCHOICE% EQU 4 (
		SET /a ENEMYACC = 10
	) ELSE (
		SET /a ENEMYACC = 20
	)
)
GOTO :EOF