@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET /a TEMP = 0
:LOOPTEMP
SET /a TEMP = %TEMP% + 1
CALL :INITIALISE
CALL :RANDOMISE
IF %TEMP% LSS 20 (
	GOTO :LOOPTEMP
)
GOTO :EOF

:INITIALISE
SET /a LENGTH = 111
SET /a HEIGHT = 44
SET /a NUMBER = 10
SET /a COUNT = 0
:LOOP1
SET /a COUNT = %COUNT% + 1
SET VAR%COUNT%=                                                                                                               
::SET VAR%COUNT%=!SPACES100!!SPACES11!
IF %COUNT% LSS %HEIGHT% (
	GOTO :LOOP1
)
GOTO :EOF

:RANDOMISE
SET /a COUNT = 0
:LOOP2
SET /a COUNT = %COUNT% + 1
SET /a LINEPOS1 = 0
:LOOP3
SET /a RANTEMP = %RANDOM% %% %NUMBER% + 1
SET /a LINEPOS = %LINEPOS1% + %RANTEMP%
IF %LINEPOS% GTR %LENGTH% (
	SET /a LINEPOS = %LENGTH%
)
SET /a LENGTHBEFORE = %LINEPOS% - 1
SET /a LENGTHAFTER = %LENGTH% - %LINEPOS%
SET VAR%COUNT%=!VAR%COUNT%:~0,%LENGTHBEFORE%!±!VAR%COUNT%:~%LINEPOS%,%LENGTHAFTER%!
SET /a LINEPOS1 = %LINEPOS1% + %NUMBER%
IF %LINEPOS1% LSS %LENGTH% (
	GOTO :LOOP3
)
IF %COUNT% LSS %HEIGHT% (
	GOTO :LOOP2
)
CALL :DISPLAY
SET /a NUMBER = %NUMBER% - 1
IF %NUMBER% GTR 1 (
	GOTO :RANDOMISE
)
GOTO :EOF


:DISPLAY
SET /a COUNT = 0
ECHO CLS>>"C:\Game\Resources\Battle\Start\Animations\animation%TEMP%.bat"
:DISPLAYLOOP
SET /a COUNT = %COUNT% + 1
ECHO ECHO !VAR%COUNT%!>>"C:\Game\Resources\Battle\Start\Animations\animation%TEMP%.bat"
IF %COUNT% LSS %HEIGHT% (
	GOTO :DISPLAYLOOP
)
ECHO TIMEOUT /T 0 ^> nul>>"C:\Game\Resources\Battle\Start\Animations\animation%TEMP%.bat"
GOTO :EOF
