SET /a COUNT = 0
SET /a ENEMY%COUNT%FIGHTCHANCECUM = 0
:LOOPSTART
SET /a OLDENEMYNO=%COUNT%
SET /a COUNT=%COUNT%+1
SET /a ENEMY%COUNT%ACTIVE = 0
IF %PLAYERLVL% GEQ !ENEMY%COUNT%MINLEVEL! (
	IF /I %MAP% EQU !ENEMY%COUNT%MAP! (
		SET /a ENEMY%COUNT%ACTIVE = 1
	)
)
IF !ENEMY%COUNT%ACTIVE! EQU 0 (
	SET /a ENEMY%COUNT%FIGHTCHANCETEMP = 0
) ELSE (
	SET /a ENEMY%COUNT%FIGHTCHANCETEMP = !ENEMY%COUNT%FIGHTCHANCE!
)
SET /a ENEMY%COUNT%FIGHTCHANCECUM = !ENEMY%OLDENEMYNO%FIGHTCHANCECUM!+!ENEMY%COUNT%FIGHTCHANCETEMP!
SET /a ENEMY%COUNT%FIGHTCHANCECUMDUMMY = !ENEMY%COUNT%FIGHTCHANCECUM!
IF !ENEMY%COUNT%ACTIVE! EQU 0 (
	SET /a ENEMY%COUNT%FIGHTCHANCECUMDUMMY = 0
)
IF %COUNT% LSS %ENEMYTOT% (
	GOTO :LOOPSTART
)
SET /a ENEMYFIGHTCHANCETOT=!ENEMY%COUNT%FIGHTCHANCECUM!
GOTO :EOF
