SET /a SPECIALFIGHT = 0
SET /a TRAINBATTLE = 0
SET /a GURUBATTLE = 0
SET TEMP=%GAMEPATH%
START "" "%BATTLESTARTRESOURCEPATH%\ranbattleinitiateddisplay.lnk"
CALL "%BATTLESTARTRESOURCEPATH%\enemyselect.bat"
CALL "%BATTLERESOURCEPATH%\battle.bat"