:INITIALISEPLAYER
CALL :AUTOBATTLE
CALL :STATUSNULL
CALL :INITIALSTATS
CALL :SPECIALSTATUS
CALL :INITIALFLAGS
CALL :SPECIALFLAGS
CALL :STEALFLAGS
CALL "%DYNAMICRESOURCEPATH%\dynamicskillchoose.bat"
CALL :LIMITBREAKCOUNT
GOTO :EOF

:AUTOBATTLE
IF %PERSISTENTAUTOBATTLE% EQU 0 (
	SET /a AUTOBATTLE = 0
)
GOTO :EOF

:STATUSNULL
SET /a PLAYERAUTOLIFE = 0
SET /a PLAYERSLEEP = 0
SET /a PLAYERCONFUSION = 0
SET /a PLAYERSTOP = 0
SET /a PLAYERREGEN = 0
SET /a PLAYERHASTE = 0
SET /a PLAYERPROTECT = 0
SET /a PLAYERSHELL = 0
SET /a PLAYERREFLECT = 0
SET /a PLAYERMED = 0
SET /a PLAYERFOC = 0
SET /a PLAYERAIM = 0
SET /a PLAYERHIDE = 0
IF %PLAYERBLIND% EQU 1 (
	SET /a PLAYERBLINDTURNCOUNT = 3
)
IF %PLAYERSILENCE% EQU 1 (
	SET /a PLAYERSILENCETURNCOUNT = 3
)
IF %PLAYERPOISON% EQU 1 (
	SET /a PLAYERPOISONTURNCOUNT = 3
)
IF %PLAYERSLOW% EQU 1 (
	SET /a PLAYERSLOWTURNCOUNT = 3
)
GOTO :EOF


:INITIALSTATS
SET /a PLAYERMAXHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a PLAYERMAXMP = %PLAYERBASEMAXMP% + %PLAYEREQUIPMAXMP%
SET /a PLAYERMAXAP = %PLAYERLVL%*5
SET /a PLAYERAP = 0
SET /a MAXAPGAIN = ((%PLAYERLVL%/10) + 1)*10
SET /a PLAYERSTR = %PLAYERBASESTR% + %PLAYEREQUIPSTR%
SET /a PLAYEREND = %PLAYERBASEEND% + %PLAYEREQUIPEND%
SET /a PLAYERMAG = %PLAYERBASEMAG% + %PLAYEREQUIPMAG%
SET /a PLAYERSPR = %PLAYERBASESPR% + %PLAYEREQUIPSPR%
SET /a PLAYERACC = %PLAYERBASEACC% + %PLAYEREQUIPACC%
SET /a PLAYEREVA = %PLAYERBASEEVA% + %PLAYEREQUIPEVA%
SET /a PLAYERSPD = %PLAYERBASESPD% + %PLAYEREQUIPSPD%
SET /a PLAYERLCK = %PLAYERBASELCK% + %PLAYEREQUIPLCK%
GOTO :EOF

:SPECIALSTATUS
IF %PLAYERAHASTE% EQU 1 (
	SET /a PLAYERHASTE = 1
	SET /a PLAYERHASTETURNCOUNT = 5
)
IF %PLAYERAPROTECT% EQU 1 (
	SET /a PLAYERPROTECT = 1
	SET /a PLAYERPROTECTTURNCOUNT = 5
)
IF %PLAYERASHELL% EQU 1 (
	SET /a PLAYERSHELL = 1
	SET /a PLAYERSHELLTURNCOUNT = 5
)
IF %PLAYERAREFLECT% EQU 1 (
	SET /a PLAYERREFLECT = 1
	SET /a PLAYERREFLECTTURNCOUNT = 5
)
IF %PLAYERAREGEN% EQU 1 (
	SET /a PLAYERREGEN = 1
	SET /a PLAYERREGENTURNCOUNT = 5
)
IF %PLAYERHEALHP% EQU 1 (
	SET /a PLAYERHP = %PLAYERMAXHP%
)
IF %PLAYERHEALMP% EQU 1 (
	SET /a PLAYERMP = %PLAYERMAXMP%
)
IF %PLAYERDOUBLEAP% EQU 1 (
	SET /a PLAYERMAXAP = %PLAYERMAXAP%*2
)
IF %PLAYERFULLAP% EQU 1 (
	SET /a PLAYERAP = %PLAYERMAXAP%
)
GOTO :EOF

:INITIALFLAGS
SET /a WINBATTLE = 0
SET /a LOSEBATTLE = 0
SET /a BATTLERUN = 0
SET /a BATTLECAUGHT = 0
SET /a ENEMYRUN = 0
SET /a ENDBATTLE = 0
SET /a PLAYERTRANSFORMAVAILABLE = 0
REM SET /a PLAYERSKILLBUFF = 0
SET /a PLAYERSUPERSAIYAN = 0
SET /a PLAYERENERGY = 0
SET /a PACMANAPPEAR = 0
SET /a LEEROYAPPEAR = 0
SET /a BATTLETOTAL = %BATTLETOTAL%+1
SET /a BATTLEROUNDNUM = 0
SET /a SCAN = 0
SET /a DETECT = 0
SET /a SCANACTIVE = 0
SET /a DETECTACTIVE = 0
SET /a PLAYERCUSTOMITEM = 0
GOTO :EOF

:SPECIALFLAGS
IF %PLAYERASCAN% EQU 1 (
	SET /a SCAN = 1
) ELSE IF !ENEMY%ENEMYID%CAUGHT! EQU 1 (
	SET /a SCAN = 1
	SET /a DETECT = 1
) ELSE IF %PLAYERADETECT% EQU 1 (
	SET /a DETECT = 1
)
GOTO :EOF

:STEALFLAGS
SET /a STEALITEM1SUCCESS = 0
SET /a STEALITEM2SUCCESS = 0
SET /a STEALITEM3SUCCESS = 0
SET /a STEALITEM4SUCCESS = 0
SET /a GILSTOLEN = 0
GOTO :EOF

:LIMITBREAKCOUNT
SET /a COUNT = 0
:LIMITBREAKLOOP
SET /a COUNT = %COUNT% + 1
SET /a LIMITBREAK%COUNT%BATTLECOUNT = 0
IF %COUNT% LSS %LIMITBREAKTOT% (
	GOTO :LIMITBREAKLOOP
)
GOTO :EOF