:INITIALISEENEMY
CALL :STATUSNULL
CALL "%BATTLESTARTRESOURCEPATH%\setenemystats.bat"
CALL "%BATTLESTARTRESOURCEPATH%\setenemyspells.bat"
CALL "%BATTLESTARTRESOURCEPATH%\setenemyskills.bat"
CALL "%BATTLESTARTRESOURCEPATH%\setenemyitems.bat"
REM IF %SPECIALFIGHT% EQU 1 (
REM 	CALL "%BATTLESTARTRESOURCEPATH%\bossstatadjustments.bat"
REM )
GOTO :EOF





:STATUSNULL
SET /a ENEMYBLIND = 0
SET /a ENEMYSILENCE = 0
SET /a ENEMYPOISON = 0
SET /a ENEMYSLOW = 0
SET /a ENEMYSLEEP = 0
SET /a ENEMYCONFUSION = 0
SET /a ENEMYSTOP = 0
SET /a ENEMYREGEN = 0
SET /a ENEMYHASTE = 0
SET /a ENEMYPROTECT = 0
SET /a ENEMYSHELL = 0
SET /a ENEMYREFLECT = 0
SET /a ENEMYFOC = 0
GOTO :EOF

