:START
SET TEMPPATH=%MUSICPATH%\Battle\Lj
SET /a STOP = 1
SET /a LOOP = 0
CALL "%MUSICPATH%\startmusic.bat"
CALL :WAITFORTHREE
SET /a SPACENUM = 3
:START2
CLS
ECHO !SPACES%SPACENUM%!            ³
ECHO !SPACES%SPACENUM%!  ÚÄÄÄ¿     ³
ECHO !SPACES%SPACENUM%!  ³  ø³     ³
ECHO !SPACES%SPACENUM%!  ³  ^<³     ³
ECHO !SPACES%SPACENUM%!  ÀÄÄÄÙ     ³
ECHO !SPACES%SPACENUM%!    ²       ³
ECHO !SPACES%SPACENUM%!  ²²²²²²   ÄÅÄ
ECHO !SPACES%SPACENUM%!  ²²²²²²ÄÄÄÄÛ
ECHO !SPACES%SPACENUM%!  ²²²²²²ÄÄÄÄÛ
ECHO !SPACES%SPACENUM%!  ²²²²²²
ECHO !SPACES%SPACENUM%!  ²²²²²²
ECHO !SPACES%SPACENUM%!    ³\
ECHO !SPACES%SPACENUM%!    ³ \
ECHO !SPACES%SPACENUM%!    ³  \
ECHO !SPACES%SPACENUM%!  ÄÄÙ   \
ECHO !SPACES%SPACENUM%!         \
ECHO.
ECHO %LJNAME1%
CALL :WAITFORZERO
SET /a SPACENUM = %SPACENUM% + 3
CLS
ECHO !SPACES%SPACENUM%!            ³
ECHO !SPACES%SPACENUM%!  ÚÄÄÄ¿     ³
ECHO !SPACES%SPACENUM%!  ³  ø³     ³
ECHO !SPACES%SPACENUM%!  ³  ^<³     ³
ECHO !SPACES%SPACENUM%!  ÀÄÄÄÙ     ³
ECHO !SPACES%SPACENUM%!    ²       ³
ECHO !SPACES%SPACENUM%!  ²²²²²²   ÄÅÄ
ECHO !SPACES%SPACENUM%!  ²²²²²²ÄÄÄÄÛ
ECHO !SPACES%SPACENUM%!  ²²²²²²ÄÄÄÄÛ
ECHO !SPACES%SPACENUM%!  ²²²²²²
ECHO !SPACES%SPACENUM%!  ²²²²²²
ECHO !SPACES%SPACENUM%!    /\
ECHO !SPACES%SPACENUM%!   /  \
ECHO !SPACES%SPACENUM%!  /    ) 
ECHO !SPACES%SPACENUM%! /    / 
ECHO !SPACES%SPACENUM%!/    /   
ECHO. 
ECHO %LJNAME1%
CALL :WAITFORZERO
SET /a SPACENUM = %SPACENUM% + 3
IF %SPACENUM% LSS 70 (
	GOTO :START2
)
SET EQUATION=LEEROYDAM
CALL "%BATTLERESOURCEPATH%\equations.bat"
ECHO.
ECHO %LJNAME2% did %DAM% damage to %ENEMYNAME%
SET /a ENEMYHP = %ENEMYHP% - %DAM%
CALL :WAITFORTHREE
GOTO :EOF




:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF

:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF