:ENEMYSTATS
IF %SPECIALFIGHT% EQU 0 (
	CALL :RANFACTEXTRA%DIFFICULTY%
) ELSE (
	IF /I %DIFFICULTY% EQU EASY (
		SET /a RANFACTEXTRA = 80
	) ELSE IF /I %DIFFICULTY% EQU HARD (
		SET /a RANFACTEXTRA = 130
	)
)
SET ENEMYNAME=!ENEMY%ENEMYID%NAME!
SET /a ENEMYNAMELENGTH = !ENEMY%ENEMYID%NAMELENGTH!
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYMAXHP = (!ENEMY%ENEMYID%MAXHP!*%RANFACT%)/100
SET /a ENEMYHP = %ENEMYMAXHP%
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYMAXMP = (!ENEMY%ENEMYID%MAXMP!*%RANFACT%)/100
SET /a ENEMYMP = %ENEMYMAXMP%
SET /a ENEMYLVL = !ENEMY%ENEMYID%LVL!
SET /a ENEMYEXP = !ENEMY%ENEMYID%EXP!
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASESTR = (!ENEMY%ENEMYID%STR!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASEEND = (!ENEMY%ENEMYID%END!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASEMAG = (!ENEMY%ENEMYID%MAG!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASESPR = (!ENEMY%ENEMYID%SPR!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASEACC = (!ENEMY%ENEMYID%ACC!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASEEVA = (!ENEMY%ENEMYID%EVA!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASESPD = (!ENEMY%ENEMYID%SPD!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASELCK = (!ENEMY%ENEMYID%LCK!*%RANFACT%)/100
SET /a RANFACT=(%RANDOM% %% 40)+%RANFACTEXTRA%
SET /a ENEMYBASEINT = (!ENEMY%ENEMYID%INT!*%RANFACT%)/100
SET /a ENEMYWEAKNESSNUM = !ENEMY%ENEMYID%WEAKNESSNUM!
SET /a ENEMYSTRENGTHNUM = !ENEMY%ENEMYID%STRENGTHNUM!
SET /a ENEMYELEMENTIMMUNENUM = !ENEMY%ENEMYID%ELEMENTIMMUNENUM!
SET /a ENEMYABSORBNUM = !ENEMY%ENEMYID%ABSORBNUM!
SET /a ENEMYSTATUSIMMUNENUM = !ENEMY%ENEMYID%STATUSIMMUNENUM!
CALL :SETRESISTANCES
IF %TUTORIALFIGHT% EQU 1 (
	SET /a ENEMYBASEACC = 1000
)
GOTO :EOF

:RANFACTEXTRAEASY
SET /a RANFACTEXTRA = 60+((%PLAYERLVL% - !ENEMY%ENEMYID%MINLEVEL!)*2)
GOTO :EOF

:RANFACTEXTRAHARD
SET /a RANFACTEXTRA = 100+((%PLAYERLVL% - !ENEMY%ENEMYID%MINLEVEL!)*5)
GOTO :EOF

:SETRESISTANCES
SET /a COUNT = 0
IF %ENEMYWEAKNESSNUM% EQU 0 (
	GOTO :STRENGTHS3
)
:WEAKNESSLOOP3
SET /a COUNT = %COUNT% + 1
SET ENEMYWEAKNESS%COUNT%=!ENEMY%ENEMYID%WEAKNESS%COUNT%!
IF %COUNT% LSS %ENEMYWEAKNESSNUM% (
	GOTO :WEAKNESSLOOP3
)
:STRENGTHS3
SET /a COUNT = 0
IF %ENEMYSTRENGTHNUM% EQU 0 (
	GOTO :IMMUNES3
)
:STRENGTHLOOP3
SET /a COUNT = %COUNT% + 1
SET ENEMYSTRENGTH%COUNT%=!ENEMY%ENEMYID%STRENGTH%COUNT%!
IF %COUNT% LSS %ENEMYSTRENGTHNUM% (
	GOTO :STRENGTHLOOP3
)
:IMMUNES3
SET /a COUNT = 0
IF %ENEMYELEMENTIMMUNENUM% EQU 0 (
	GOTO :ABSORBS3
)
:IMMUNELOOP3
SET /a COUNT = %COUNT% + 1
SET ENEMYELEMENTIMMUNE%COUNT%=!ENEMY%ENEMYID%ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS %ENEMYELEMENTIMMUNENUM% (
	GOTO :IMMUNELOOP3
)
:ABSORBS3
SET /a COUNT = 0
IF %ENEMYABSORBNUM% EQU 0 (
	GOTO :STATUSIMMUNES3
)
:ABSORBLOOP3
SET /a COUNT = %COUNT% + 1
SET ENEMYABSORB%COUNT%=!ENEMY%ENEMYID%ABSORB%COUNT%!
IF %COUNT% LSS %ENEMYABSORBNUM% (
	GOTO :ABSORBLOOP3
)
:STATUSIMMUNES3
SET /a COUNT = 0
IF %ENEMYSTATUSIMMUNENUM% EQU 0 (
	GOTO :EOF
)
:STATUSIMMUNELOOP3
SET /a COUNT = %COUNT% + 1
SET ENEMYSTATUSIMMUNE%COUNT%=!ENEMY%ENEMYID%STATUSIMMUNE%COUNT%!
IF %COUNT% LSS %ENEMYSTATUSIMMUNENUM% (
	GOTO :STATUSIMMUNELOOP3
)
GOTO :EOF
