CALL :INITIALISE
GOTO :EOF


:INITIALISE
SET /a ENEMYITEMNUM = !ENEMY%ENEMYID%ITEMNUM!
IF %ENEMYITEMNUM% EQU 0 (
	SET /a ENEMYITEMCHANCE = 0
	GOTO :EOF
)
SET /a ENEMYITEMCHANCE = !ENEMY%ENEMYID%ITEMCHANCE!
SET /a COUNT = 0
:INITIALISELOOP
SET /a COUNT = %COUNT% + 1
SET /a ENEMYITEM%COUNT% = !ENEMY%ENEMYID%ITEM%COUNT%!
SET /a ENEMYITEM!ENEMYITEM%COUNT%!NUM = !ENEMY%ENEMYID%ITEM%COUNT%NUM!
SET /a ENEMYITEM%COUNT%CHANCE = !ENEMY%ENEMYID%ITEM%COUNT%CHANCE!
IF %COUNT% LSS %ENEMYITEMNUM% (
	GOTO :INITIALISELOOP
)
GOTO :EOF





