CALL :INITIALISE
GOTO :EOF


:INITIALISE
SET /a ENEMYSKILLNUM = !ENEMY%ENEMYID%SKILLNUM!
IF %ENEMYSKILLNUM% EQU 0 (
	SET /a ENEMYSKILLCHANCE = 0
	GOTO :EOF
)
SET /a ENEMYSKILLCHANCE = !ENEMY%ENEMYID%SKILLCHANCE!
SET /a COUNT = 0
:INITIALISELOOP
SET /a COUNT = %COUNT% + 1
SET /a ENEMYSKILL%COUNT% = !ENEMY%ENEMYID%SKILL%COUNT%!
SET /a ENEMYSKILL%COUNT%CHANCE = !ENEMY%ENEMYID%SKILL%COUNT%CHANCE!
IF %COUNT% LSS %ENEMYSKILLNUM% (
	GOTO :INITIALISELOOP
)
GOTO :EOF





