CALL :SPELLCHANCE
CALL :SPELLS
CALL :CALCULATION1
GOTO :EOF

:SPELLCHANCE
IF DEFINED ENEMY%ENEMYID%SPELLCHANCE (
	SET /a ENEMYSPELLCHANCE = !ENEMY%ENEMYID%SPELLCHANCE!
) ELSE (
	SET /a ENEMYSPELLCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%OFFSPELLCHANCE (
	SET /a ENEMYOFFSPELLCHANCE = !ENEMY%ENEMYID%OFFSPELLCHANCE!
) ELSE (
	SET /a ENEMYOFFSPELLCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%STATSPELLCHANCE (
	SET /a ENEMYSTATSPELLCHANCE = !ENEMY%ENEMYID%STATSPELLCHANCE!
) ELSE (
	SET /a ENEMYSTATSPELLCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%RESTSPELLCHANCE (
	SET /a ENEMYRESTSPELLCHANCE = !ENEMY%ENEMYID%RESTSPELLCHANCE!
) ELSE (
	SET /a ENEMYRESTSPELLCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%SUPPSPELLCHANCE (
	SET /a ENEMYSUPPSPELLCHANCE = !ENEMY%ENEMYID%SUPPSPELLCHANCE!
) ELSE (
	SET /a ENEMYSUPPSPELLCHANCE = 0
)
GOTO :EOF


:SPELLS
REM ENEMY's Offensive Magic
SET /a COUNT = 0
:OFFSPELLLOOP
SET /a COUNT = %COUNT%+1
SET TEMP=!OFF%COUNT%SPELL!
IF DEFINED ENEMY%ENEMYID%%TEMP%ENABLED (
	SET /a ENEMY%TEMP%ENABLED = !ENEMY%ENEMYID%%TEMP%ENABLED!
) ELSE (	
	SET /a ENEMY%TEMP%ENABLED = 0
)
IF %COUNT% LSS %OFFSPELLTOT% (
	GOTO :OFFSPELLLOOP
)

REM ENEMY's Status Magic
SET /a COUNT = 0
:STATSPELLLOOP
SET /a COUNT = %COUNT%+1
SET TEMP=!STAT%COUNT%SPELL!
IF DEFINED ENEMY%ENEMYID%%TEMP%ENABLED (
	SET /a ENEMY%TEMP%ENABLED = !ENEMY%ENEMYID%%TEMP%ENABLED!
) ELSE (	
	SET /a ENEMY%TEMP%ENABLED = 0
)
IF %COUNT% LSS %STATSPELLTOT% (
	GOTO :STATSPELLLOOP
)

REM Enemy's Restoration Magic
SET /a COUNT = 0
:RESTSPELLLOOP
SET /a COUNT = %COUNT%+1
SET TEMP=!REST%COUNT%SPELL!
IF DEFINED ENEMY%ENEMYID%%TEMP%ENABLED (
	SET /a ENEMY%TEMP%ENABLED = !ENEMY%ENEMYID%%TEMP%ENABLED!
) ELSE (	
	SET /a ENEMY%TEMP%ENABLED = 0
)
IF %COUNT% LSS %RESTSPELLTOT% (
	GOTO :RESTSPELLLOOP
)

REM Enemy's Support Magic
SET /a COUNT = 0
:SUPPSPELLLOOP
SET /a COUNT = %COUNT%+1
SET TEMP=!SUPP%COUNT%SPELL!
IF DEFINED ENEMY%ENEMYID%%TEMP%ENABLED (
	SET /a ENEMY%TEMP%ENABLED = !ENEMY%ENEMYID%%TEMP%ENABLED!
) ELSE (	
	SET /a ENEMY%TEMP%ENABLED = 0
)
IF %COUNT% LSS %SUPPSPELLTOT% (
	GOTO :SUPPSPELLLOOP
)
GOTO :EOF




:CALCULATION1
IF %ENEMYSPELLCHANCE% GTR 0 (
	SET /a ENEMYSPELLCHANCETOT = %ENEMYOFFSPELLCHANCE%+%ENEMYSTATSPELLCHANCE%+%ENEMYDEBSPELLCHANCE%+%ENEMYRESTSPELLCHANCE%+%ENEMYSUPPSPELLCHANCE%
	SET /a ENEMYOFFSPELLCHANCECUM = %ENEMYOFFSPELLCHANCE%
	SET /a ENEMYSTATSPELLCHANCECUM = %ENEMYOFFSPELLCHANCE%+%ENEMYSTATSPELLCHANCE%
	SET /a ENEMYRESTSPELLCHANCECUM = %ENEMYOFFSPELLCHANCE%+%ENEMYSTATSPELLCHANCE%+%ENEMYRESTSPELLCHANCE%
	SET /a ENEMYSUPPSPELLCHANCECUM = %ENEMYOFFSPELLCHANCE%+%ENEMYSTATSPELLCHANCE%+%ENEMYRESTSPELLCHANCE%+%ENEMYSUPPSPELLCHANCE%
	IF %ENEMYOFFSPELLCHANCE% EQU 0 (
	SET /a ENEMYOFFSPELLCHANCECUM = 0
	)
	IF %ENEMYSTATSPELLCHANCE% EQU 0 (
	SET /a ENEMYSTATSPELLCHANCECUM = 0
	)
	IF %ENEMYRESTSPELLCHANCE% EQU 0 (
	SET /a ENEMYRESTSPELLCHANCECUM = 0
	)
	IF %ENEMYSUPPSPELLCHANCE% EQU 0 (
	SET /a ENEMYSUPPSPELLCHANCECUM = 0
	)
)
GOTO :EOF






