SET /a SPECIALFIGHT = 1
SET /a TRAINBATTLE = 0
SET /a GURUBATTLE = 0
IF NOT DEFINED ENEMY%ENEMYID%LOADED (
	SET /a ENEMY%ENEMYID%LOADED = 1
	CALL "%MISCRESOURCEPATH%\loadenemy.bat"
)
CALL "%BATTLERESOURCEPATH%\battle.bat"