CALL :INITIALISE
CALL :SKILLSMODIFY
CALL :SKILL2MODIFY
CALL :APPLYBONUSES

:INITIALISE
SET /a ITEM1SKILL1BONUS = 0
SET /a ITEM2SKILL1BONUS = 0
SET /a ITEM3SKILL1BONUS = 0
SET /a ITEM4SKILL1BONUS = 0
SET /a ITEM1SKILL2BONUS = 0
SET /a ITEM2SKILL2BONUS = 0
SET /a ITEM3SKILL2BONUS = 0
SET /a ITEM4SKILL2BONUS = 0
SET /a LUCKBONUS = %PLAYERLCK%
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL1CHANCE (
	SET /a ITEM1STEALCHANCE = !ENEMY%ENEMYID%SET%REWARDSET%STEAL1CHANCE!
) ELSE (
	SET /a ITEM1STEALCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL2CHANCE (
	SET /a ITEM2STEALCHANCE = !ENEMY%ENEMYID%SET%REWARDSET%STEAL2CHANCE!
) ELSE (
	SET /a ITEM2STEALCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL3CHANCE (
	SET /a ITEM3STEALCHANCE = !ENEMY%ENEMYID%SET%REWARDSET%STEAL3CHANCE!
) ELSE (
	SET /a ITEM3STEALCHANCE = 0
)
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL4CHANCE (
	SET /a ITEM4STEALCHANCE = !ENEMY%ENEMYID%SET%REWARDSET%STEAL4CHANCE!
) ELSE (
	SET /a ITEM4STEALCHANCE = 0
)
GOTO :EOF


:SKILLSMODIFY
IF %PLAYERINCSTLCHANCE% EQU 1 (
	CALL :SKILL1MODIFY
)
IF %PLAYERSTLBETTER% EQU 1 (
	CALL :SKILL2MODIFY
)
GOTO :EOF

:SKILL1MODIFY
SET /a COUNT = 0
:SKILL1LOOP
SET /a COUNT = %COUNT% + 1
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT% (
	SET /a ITEM%COUNT%SKILL1BONUS = !ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT%CHANCE!
)
IF %COUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :SKILL1LOOP
)
GOTO :EOF

:SKILL2MODIFY
SET /a COUNT = 0
:SKILL2LOOP
SET /a TEMPCOUNT = %COUNT%
SET /a COUNT = %COUNT% + 1
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT% (
	SET /a ITEM%COUNT%SKILL2BONUS = !ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT%CHANCE! * %TEMPCOUNT%
)
IF %COUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :SKILL2LOOP
)
GOTO :EOF

:APPLYBONUSES
SET /a COUNT = 0
:APPLYBONUSESLOOP
SET /a COUNT = %COUNT% + 1
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT% (
	SET /a ITEM%COUNT%STEALCHANCE = !ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT%CHANCE! + !ITEM%COUNT%SKILL1BONUS! + !ITEM%COUNT%SKILL2BONUS! + %LUCKBONUS%
)
IF %COUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :APPLYBONUSESLOOP
)
GOTO :EOF