CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: I'll be with you in two shakes of a lamb's tail
ECHO.
SET /a ENEMYID = 0
:LOADINGLOOP
SET /a ENEMYID = %ENEMYID% + 1
IF !ENEMY%ENEMYID%CAUGHT! EQU 1 (
	IF NOT DEFINED ENEMY%ENEMYID%LOADED (
		SET /a ENEMY%ENEMYID%LOADED = 1
		CALL "%MISCRESOURCEPATH%\loadenemy.bat"
	)
)
IF %ENEMYID% LSS %ENEMYTOT% (
	GOTO :LOADINGLOOP
)
CALL "%DYNAMICRESOURCEPATH%\dynamicenemylisttraining.bat"
:START
IF %DYNAMICENEMYTOT% EQU 0 (
	CLS
	ECHO.
	ECHO %MENUNAME%: You haven't caught anything yet^^!
	ECHO.
	pause
	GOTO :EOF
)
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Here's a list of innocent, cute animals that you've currently got locked in a cage you meanie mancy
ECHO.
SET /a COUNT = 0
:LOOPSTART1
SET /a COUNT = %COUNT% + 1
ECHO. %COUNT% - !DYNAMICENEMY%COUNT%NAME!
IF %COUNT% LSS %DYNAMICENEMYTOT% (
	GOTO :LOOPSTART1
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P DYNAMICCHOICE=
ECHO.
IF "%DYNAMICCHOICE%" EQU "" (
	GOTO :CHOICE
) ELSE IF "%DYNAMICCHOICE%" EQU "0" (
	GOTO :EOF
)
IF %DYNAMICCHOICE% GTR %DYNAMICENEMYTOT% (
	GOTO :CHOICE
) ELSE IF %DYNAMICCHOICE% LSS 0 (
	GOTO :CHOICE
)
CALL :SETSTATICID

CALL "%MENURESOURCEPATH%\caughtdisplay.bat"
GOTO :EOF

:SETSTATICID
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
IF "!ENEMY%COUNT%NAME!" EQU "!DYNAMICENEMY%DYNAMICCHOICE%NAME!" (
	SET /a CHOICE = %COUNT%
	GOTO :EOF
)
IF %COUNT% LSS %ENEMYTOT% (
	CALL :LOOPSTART
)
GOTO :EOF