SET /a COLUMN1WIDTH = 40
SET /a COLUMN2WIDTH = 23
SET /a COLUMN3WIDTH = 36
::CALL :TEMPSETUP
CALL :INITIALSETUP
CALL :INITIALISEVARS
CALL :COLUMN1CALCULATIONS
CALL :COLUMN2CALCULATIONS
CALL :COLUMN3CALCULATIONS
CALL :DISPLAY
pause
GOTO :EOF



:TEMPSETUP
SET /a COUNT = 0
SET SPACES0=
:LOOPY
SET /a OLDCOUNT = %COUNT%
SET /a COUNT = %COUNT% + 1
SET SPACES%COUNT%=!SPACES%OLDCOUNT%! 
IF %COUNT% LSS 100 (
	GOTO :LOOPY
)
SET /a REWARDSET = 1
SET /a CHOICE = 1
SET ENEMY1NAME=Nick
SET /a ENEMY1NAMELENGTH = 4
SET ENEMY1DESCRIPTION1=Nick
SET /a ENEMY1DESCRIPTION1LENGTH = 4
SET ENEMY1DESCRIPTION2=Sisson
SET /a ENEMY1DESCRIPTION2LENGTH = 6
SET ENEMY1DESCRIPTION3=Nick
SET /a ENEMY1DESCRIPTION3LENGTH = 4
SET ENEMY1DESCRIPTION4=Sisson
SET /a ENEMY1DESCRIPTION4LENGTH = 6
SET /a ENEMY1DESCRIPTIONNUM = 4
SET /a ENEMY1LVL = 1
SET /a ENEMY1MAXHP = 50
SET /a ENEMY1STR = 5
SET /a ENEMY1END = 5
SET /a ENEMY1MAG = 5
SET /a ENEMY1SPR = 5
SET /a ENEMY1ACC = 5
SET /a ENEMY1EVA = 5
SET /a ENEMY1SPD = 5
SET /a ENEMY1LCK = 5
SET /a ENEMY1INT = 5
SET /a ENEMY1GIL = 500
SET /a ENEMY1EXP = 1000
SET /a ENEMY1WEAKNESSNUM = 2
SET ENEMY1WEAKNESS1=Fire
SET ENEMY1WEAKNESS2=Ice
SET /a ENEMY1STRENGTHNUM = 0
SET /a ENEMY1ELEMENTIMMUNENUM = 1
SET ENEMY1ELEMENTIMMUNE1=Electricity
SET /a ENEMY1ABSORBNUM = 0
SET /a ENEMY1STATUSIMMUNENUM = 1
SET ENEMY1STATUSIMMUNE1=Confusion

SET /a COUNT = 1
SET /a ENEMY%COUNT%FIGHTCHANCE = 50
SET /a ENEMY%COUNT%MINLEVEL = 1
SET /a ENEMY%COUNT%MAXLEVEL = 5
SET ENEMY%COUNT%MAP=town2

SET /a ENEMY1OFFSPELLNUM = 1
SET OFF1SPELL=Fire
SET /a ENEMY1OFFSPELL1 = 1
SET /a ENEMY1STATSPELLNUM = 0
SET /a ENEMY1RESTSPELLNUM = 0
SET /a ENEMY1SUPPSPELLNUM = 0

SET /a ENEMY%COUNT%SKILLNUM = 1
SET /a ENEMY%COUNT%SKILLCHANCE = 35

SET ENEMYSKILL1NAME=Rabies Bite
SET ENEMYSKILL1NICKNAME=RAB
SET /a %ENEMYSKILL1NICKNAME%ID = 1

SET /a ENEMY%COUNT%SKILL1 = %RABID%
SET /a ENEMY%COUNT%SKILL1CHANCE = 100

SET /a POTID = 1
SET ITEM1NAME=Potion
SET /a ITEM1NAMELENGTH = 6
SET /a ETHID = 4
SET ITEM4NAME=Ether
SET /a ITEM4NAMELENGTH = 5
SET SPECIALITEM1NAME=Strength Stone
SET /a STRSTONEID = 1
SET /a SPECIALITEM1NAMELENGTH = 14

SET /a ENEMY%COUNT%ITEMNUM = 2
SET /a ENEMY%COUNT%ITEMCHANCE = 30
SET /a ENEMY%COUNT%ITEM1 = %ETHID%
SET /a ENEMY%COUNT%ITEM1NUM = 3
SET /a ENEMY%COUNT%ITEM1CHANCE = 50
SET /a ENEMY%COUNT%ITEM2 = %POTID%
SET /a ENEMY%COUNT%ITEM2NUM = 3
SET /a ENEMY%COUNT%ITEM2CHANCE = 50

SET /a ENEMY%COUNT%SET1ITEMNUM = 1
SET /a ENEMY%COUNT%SET1ITEM1 = %POTID%
SET /a ENEMY%COUNT%SET1ITEM1CHANCE = 30
SET /a ENEMY%COUNT%SET1ITEM1MAXNUM = 4
SET /a ENEMY%COUNT%SET1SPECIALITEMNUM = 1
SET /a ENEMY%COUNT%SET1SPECIALITEM1 = %STRSTONEID%
SET /a ENEMY%COUNT%SET1SPECIALITEM1CHANCE = 30
SET /a ENEMY%COUNT%SET1SPECIALITEM1MAXNUM = 4
SET /a ENEMY%COUNT%SET1WEAPONNUM = 0
SET /a ENEMY%COUNT%SET1ARMOURNUM = 0
SET /a ENEMY%COUNT%SET1ACCESSORYNUM = 0
SET /a ENEMY%COUNT%SET1STEALNUM = 1
SET ENEMY%COUNT%SET1STEAL1TYPE=ITEM
SET /a ENEMY%COUNT%SET1STEAL1 = %ETHID%
SET /a ENEMY%COUNT%SET1STEAL1CHANCE = 60
SET /a ENEMY%COUNT%SET1STEALGIL = 30
SET /a ENEMY%COUNT%SET1MORPHGIL = 200

SET ENEMY%COUNT%SET1MORPHTYPE=ITEM
SET /a ENEMY%COUNT%SET1MORPHID = %ETHID%
SET /a ENEMY%COUNT%SET1MORPHMINPERC = 20
SET /a ENEMY%COUNT%SET1MORPHMAXNUM = 3


::SET /a ENEMY%COUNT%SET1MORPHITEMNUM = 1
::SET ENEMY%COUNT%SET1MORPHITEM1TYPE=SPECIALITEM
::SET /a ENEMY%COUNT%SET1MORPHITEM1 = %STRSTONEID%
::SET /a ENEMY%COUNT%SET1MORPHITEM1CHANCE = 80
GOTO :EOF

:INITIALSETUP
IF %ENEMYID% NEQ %CHOICE% (
	CALL "%MENURESOURCEPATH%\menudisplay.bat"
	ECHO %MENUNAME%: Just let me grab that from ma books here darlin'
)
SET /a TOTALROWS = 30
SET /a NAMECOL = 1
SET /a NAMEROWSTART = 1
SET /a DESCRIPTIONCOL = 1
SET /a DESCRIPTIONROWSTART = 2
SET /a STATCOL = 1
SET /a STATROWSTART = 7
SET /a RESISTANCECOL = 1
SET /a RESISTANCEROWSTART = 13

SET /a SPELLSCOL = 2
SET /a SPELLSROWSTART = 2
SET /a REWARDSCOL = 3
SET /a REWARDSROWSTART = 2
GOTO :EOF

:INITIALISEVARS
SET /a COLNUM = 1
CALL :INITIALISECOLUMN
SET /a COLNUM = 2
CALL :INITIALISECOLUMN
SET /a COLNUM = 3
CALL :INITIALISECOLUMN
GOTO :EOF

:INITIALISECOLUMN
SET /a COUNT = 0
:INITIALISECOLUMNLOOP
SET /a COUNT = %COUNT% + 1
SET /a SPACENUM = !COLUMN%COLNUM%WIDTH!
SET COL%COLNUM%VAR%COUNT%=!SPACES%SPACENUM%!
IF %COUNT% LSS %TOTALROWS% (
	GOTO :INITIALISECOLUMNLOOP
)
GOTO :EOF

:COLUMN1CALCULATIONS
CALL :NAME
CALL :DESCRIPTION
CALL :STATS
CALL :RESISTANCES
GOTO :EOF

:COLUMN2CALCULATIONS
CALL :SPELLS
CALL :SKILLS
CALL :ITEMS
GOTO :EOF

:COLUMN3CALCULATIONS
CALL :REWARDS
CALL :STEAL
CALL :MORPHITEM
GOTO :EOF

:NAME
SET /a SPACENUM = !COLUMN%NAMECOL%WIDTH! - !ENEMY%CHOICE%NAMELENGTH!
SET COL%NAMECOL%VAR%NAMEROWSTART%=!ENEMY%CHOICE%NAME!!SPACES%SPACENUM%!
GOTO :EOF

:DESCRIPTION
SET /a COUNT = 0
SET /a TEMPCOUNT = %DESCRIPTIONROWSTART% - 1
:DESCRIPTIONLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF DEFINED ENEMY%CHOICE%DESCRIPTION%COUNT% (
	CALL :SETDESCRIPTION
) ELSE (
	GOTO :EOF
)
IF %COUNT% LSS 4 (
	GOTO :DESCRIPTIONLOOP
)
GOTO :EOF

:SETDESCRIPTION
SET /a SPACENUM = !COLUMN%DESCRIPTIONCOL%WIDTH! - !ENEMY%CHOICE%DESCRIPTION%COUNT%LENGTH!
SET COL%DESCRIPTIONCOL%VAR%TEMPCOUNT%=!ENEMY%CHOICE%DESCRIPTION%COUNT%!!SPACES%SPACENUM%!
GOTO :EOF

:STATS
SET /a SHORTSTATLENGTH = !COLUMN%STATCOL%WIDTH!/4
SET /a LONGSTATLENGTH = %SHORTSTATLENGTH%*2
CALL :STATCALCULATIONS
CALL :ROWCALCULATIONS
GOTO :EOF

:STATCALCULATIONS
SET STAT=LVL
SET STATDISPLAY=LVL
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=MAXHP
SET STATDISPLAY=HP 
SET STATLENGTH=LONG
CALL :STATVAR
SET STAT=STR
SET STATDISPLAY=STR
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=END
SET STATDISPLAY=END
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=MAG
SET STATDISPLAY=MAG
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=SPR
SET STATDISPLAY=SPR
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=ACC
SET STATDISPLAY=ACC
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=EVA
SET STATDISPLAY=EVA
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=SPD
SET STATDISPLAY=SPD
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=LCK
SET STATDISPLAY=LCK
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=INT
SET STATDISPLAY=INT
SET STATLENGTH=SHORT
CALL :STATVAR
SET STAT=GIL
SET STATDISPLAY=Gil
SET STATLENGTH=LONG
CALL :STATVAR
SET STAT=EXP
SET STATDISPLAY=EXP
SET STATLENGTH=LONG
CALL :STATVAR
GOTO :EOF

:ROWCALCULATIONS
SET /a SPACENUM = !COLUMN%STATCOL%WIDTH! - 6
SET COL%STATCOL%VAR%STATROWSTART%=Stats:!SPACES%SPACENUM%!
SET /a COUNT = %STATROWSTART%
SET /a COUNT = %COUNT% + 1
SET COL%STATCOL%VAR%COUNT%=%LVLVAR%%MAXHPVAR%%STRVAR%
SET /a COUNT = %COUNT% + 1
SET COL%STATCOL%VAR%COUNT%=%ENDVAR%%MAGVAR%%SPRVAR%%ACCVAR%
SET /a COUNT = %COUNT% + 1
SET COL%STATCOL%VAR%COUNT%=%EVAVAR%%SPDVAR%%LCKVAR%%INTVAR%
SET /a COUNT = %COUNT% + 1
SET COL%STATCOL%VAR%COUNT%=%GILVAR%%EXPVAR%
GOTO :EOF


:STATVAR
SET %STAT%VAR=%STATDISPLAY%: !ENEMY%CHOICE%%STAT%!
CALL :STATNAMELENGTH
SET /a SPACENUM = !%STATLENGTH%STATLENGTH! - %STATNAMELENGTH%
SET %STAT%VAR=!%STAT%VAR!!SPACES%SPACENUM%!
GOTO :EOF


:STATNAMELENGTH
SET /a STATNAMELENGTH = 0
:STATNAMELOOPSTART
SET /a STATNAMELENGTH += 1
SET /a TEMP1 = %STATNAMELENGTH%
SET SUBSTR=!%STAT%VAR:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :STATNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %STATNAMELENGTH% + 1
	SET SUBSTR=!%STAT%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :STATNAMELOOPSTART
	)
)
GOTO :EOF

:RESISTANCES
SET /a VARCOUNT = %RESISTANCEROWSTART%
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - 34
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Elemental and Status Abnormalities!SPACES%SPACENUM%!
IF !ENEMY%CHOICE%WEAKNESSNUM! EQU 0 (
	GOTO :STRENGTHS
)
SET /a COUNT = 0
:WEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Weakness: !ENEMY%CHOICE%WEAKNESS%COUNT%!
CALL :RESISTANCELENGTH
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - %RESISTANCENAMELENGTH%
SET COL%RESISTANCECOL%VAR%VARCOUNT%=!COL%RESISTANCECOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%WEAKNESSNUM! (
	GOTO :WEAKNESSLOOP
)
:STRENGTHS
IF !ENEMY%CHOICE%STRENGTHNUM! EQU 0 (
	GOTO :ELEMENTALIMMUNES
)
SET /a COUNT = 0
:STRENGTHLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Strength: !ENEMY%CHOICE%STRENGTH%COUNT%!
CALL :RESISTANCELENGTH
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - %RESISTANCENAMELENGTH%
SET COL%RESISTANCECOL%VAR%VARCOUNT%=!COL%RESISTANCECOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%STRENGTHNUM! (
	GOTO :STRENGTHLOOP
)
:ELEMENTALIMMUNES
IF !ENEMY%CHOICE%ELEMENTIMMUNENUM! EQU 0 (
	GOTO :ABSORBS
)
SET /a COUNT = 0
:ELEMENTALIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Elemental Immunity: !ENEMY%CHOICE%ELEMENTIMMUNE%COUNT%!
CALL :RESISTANCELENGTH
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - %RESISTANCENAMELENGTH%
SET COL%RESISTANCECOL%VAR%VARCOUNT%=!COL%RESISTANCECOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%ELEMENTALIMMUNENUM! (
	GOTO :ELEMENTALIMMUNELOOP
)
:ABSORBS
IF !ENEMY%CHOICE%ABSORBNUM! EQU 0 (
	GOTO :STATUSIMMUNES
)
SET /a COUNT = 0
:ABSORBLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Absorb: !ENEMY%CHOICE%ABSORB%COUNT%!
CALL :RESISTANCELENGTH
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - %RESISTANCENAMELENGTH%
SET COL%RESISTANCECOL%VAR%VARCOUNT%=!COL%RESISTANCECOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%ABSORBNUM! (
	GOTO :ABSORBLOOP
)
:STATUSIMMUNES
IF !ENEMY%CHOICE%STATUSIMMUNENUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:STATUSIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%RESISTANCECOL%VAR%VARCOUNT%=Status Immune: !ENEMY%CHOICE%STATUSIMMUNE%COUNT%!
CALL :RESISTANCELENGTH
SET /a SPACENUM = !COLUMN%RESISTANCECOL%WIDTH! - %RESISTANCENAMELENGTH%
SET COL%RESISTANCECOL%VAR%VARCOUNT%=!COL%RESISTANCECOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%STATUSIMMUNENUM! (
	GOTO :STATUSIMMUNELOOP
)
GOTO :EOF

GOTO :EOF

:RESISTANCELENGTH
SET /a RESISTANCENAMELENGTH = 0
:RESISTANCENAMELOOPSTART
SET /a RESISTANCENAMELENGTH += 1
SET SUBSTR=!COL%RESISTANCECOL%VAR%VARCOUNT%:~%RESISTANCENAMELENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :RESISTANCENAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %RESISTANCENAMELENGTH% + 1
	SET SUBSTR=!COL%RESISTANCECOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :RESISTANCENAMELOOPSTART
	)
)
GOTO :EOF

:SPELLS
SET /a VARCOUNT = %SPELLSROWSTART%
IF !ENEMY%CHOICE%OFFSPELLNUM! EQU 0 (
	IF !ENEMY%CHOICE%STATSPELLNUM! EQU 0 (
		IF !ENEMY%CHOICE%RESTSPELLNUM! EQU 0 (
			IF !ENEMY%CHOICE%SUPPSPELLNUM! EQU 0 (
				CALL :NOSPELLS
				GOTO :SPELLEND
			)
		)
	)
)
SET /a SPACENUM = !COLUMN%SPELLSCOL%WIDTH! - 7
SET COL%SPELLSCOL%VAR%VARCOUNT%=Spells:!SPACES%SPACENUM%!
SET TYPE=OFF
CALL :SETSPELLS
SET TYPE=STAT
CALL :SETSPELLS
SET TYPE=REST
CALL :SETSPELLS
SET TYPE=SUPP
CALL :SETSPELLS
:SPELLEND
::UPDATING THE VARCOUNT SO THAT SKILLS START 2 ROWS BELOW SPELLS
SET /a VARCOUNT = %VARCOUNT% + 2
SET /a SKILLSCOL = 2
SET /a SKILLSROWSTART = %VARCOUNT%
GOTO :EOF

:NOSPELLS
SET /a SPACENUM = !COLUMN%SPELLSCOL%WIDTH! - 9
SET COL%SPELLSCOL%VAR%VARCOUNT%=No Spells!SPACES%SPACENUM%!
GOTO :EOF

:SETSPELLS
IF !ENEMY%CHOICE%%TYPE%SPELLNUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:SPELLLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET /a TEMP = !ENEMY%CHOICE%%TYPE%SPELL%COUNT%!
SET COL%SPELLSCOL%VAR%VARCOUNT%=!%TYPE%%TEMP%SPELL!
CALL :SPELLLENGTH
SET /a SPACENUM = !COLUMN%SPELLSCOL%WIDTH! - %SPELLNAMELENGTH%
SET COL%SPELLSCOL%VAR%VARCOUNT%=!COL%SPELLSCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%%TYPE%SPELLNUM! (
	GOTO :SPELLLOOP
)
GOTO :EOF

:SPELLLENGTH
SET /a SPELLNAMELENGTH = 0
:SPELLNAMELOOPSTART
SET /a SPELLNAMELENGTH += 1
SET SUBSTR=!COL%SPELLSCOL%VAR%VARCOUNT%:~%SPELLNAMELENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SPELLNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %SPELLNAMELENGTH% + 1
	SET SUBSTR=!COL%SPELLSCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SPELLNAMELOOPSTART
	)
)
GOTO :EOF

:SKILLS
IF !ENEMY%CHOICE%SKILLNUM! EQU 0 (
	CALL :NOSKILLS
	GOTO :SKILLEND
)
SET /a SPACENUM = !COLUMN%SKILLSCOL%WIDTH! - 7
SET COL%SKILLSCOL%VAR%VARCOUNT%=Skills:!SPACES%SPACENUM%!
SET /a COUNT = 0
:SKILLLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET /a TEMP = !ENEMY%CHOICE%SKILL%COUNT%!
SET COL%SKILLSCOL%VAR%VARCOUNT%=!ENEMYSKILL%TEMP%NAME!
CALL :SKILLLENGTH
SET /a SPACENUM = !COLUMN%SKILLSCOL%WIDTH! - %SKILLNAMELENGTH%
SET COL%SKILLSCOL%VAR%VARCOUNT%=!COL%SKILLSCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%SKILLNUM! (
	GOTO :SKILLLOOP
)
:SKILLEND
SET /a VARCOUNT = %VARCOUNT% + 2
SET /a ITEMSCOL = 2
SET /a ITEMSROWSTART = %VARCOUNT%
GOTO :EOF

::This bit may be unnecessary if skill name lengths are calculated on startup
:SKILLLENGTH
SET /a SKILLNAMELENGTH = 0
:SKILLNAMELOOPSTART
SET /a SKILLNAMELENGTH += 1
SET SUBSTR=!COL%SKILLSCOL%VAR%VARCOUNT%:~%SKILLNAMELENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :SKILLNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %SKILLNAMELENGTH% + 1
	SET SUBSTR=!COL%SKILLSCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :SKILLNAMELOOPSTART
	)
)
GOTO :EOF

:NOSKILLS
SET /a SPACENUM = !COLUMN%SKILLSCOL%WIDTH! - 9
SET COL%SKILLSCOL%VAR%VARCOUNT%=No Skills!SPACES%SPACENUM%!
GOTO :EOF

:ITEMS
IF !ENEMY%CHOICE%ITEMNUM! EQU 0 (
	CALL :NOITEMS
	GOTO :EOF
)
SET /a SPACENUM = !COLUMN%ITEMSCOL%WIDTH! - 6
SET COL%ITEMSCOL%VAR%VARCOUNT%=Items:!SPACES%SPACENUM%!
SET /a COUNT = 0
:ITEMLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET /a TEMP = !ENEMY%CHOICE%ITEM%COUNT%!
SET COL%ITEMSCOL%VAR%VARCOUNT%=!ITEM%TEMP%NAME!
::CALL :ITEMLENGTH
SET /a SPACENUM = !COLUMN%ITEMSCOL%WIDTH! - !ITEM%TEMP%NAMELENGTH!
SET COL%ITEMSCOL%VAR%VARCOUNT%=!COL%ITEMSCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%ITEMNUM! (
	GOTO :ITEMLOOP
)
GOTO :EOF

::This bit may be unnecessary if ITEM name lengths are calculated on startup
:ITEMLENGTH
SET /a ITEMNAMELENGTH = 0
:ITEMNAMELOOPSTART
SET /a ITEMNAMELENGTH += 1
SET SUBSTR=!COL%ITEMSCOL%VAR%VARCOUNT%:~%ITEMNAMELENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ITEMNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %ITEMNAMELENGTH% + 1
	SET SUBSTR=!COL%ITEMSCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ITEMNAMELOOPSTART
	)
)
GOTO :EOF

:NOITEMS
SET /a SPACENUM = !COLUMN%ITEMSCOL%WIDTH! - 8
SET COL%ITEMSCOL%VAR%VARCOUNT%=No items!SPACES%SPACENUM%!
GOTO :EOF

:REWARDS
SET /a VARCOUNT = %REWARDSROWSTART%
IF !ENEMY%CHOICE%SET%REWARDSET%ITEMNUM! EQU 0 (
	IF !ENEMY%CHOICE%SET%REWARDSET%SPECIALITEMNUM! EQU 0 (
		IF !ENEMY%CHOICE%SET%REWARDSET%WEAPONNUM! EQU 0 (
			IF !ENEMY%CHOICE%SET%REWARDSET%ARMOURNUM! EQU 0 (
				IF !ENEMY%CHOICE%SET%REWARDSET%ACCESSORYNUM! EQU 0 (
					CALL :NOREWARDS
					GOTO :REWARDSEND
				)
			)
		)
	)
)
SET /a SPACENUM = !COLUMN%REWARDSCOL%WIDTH! - 8
SET COL%REWARDSCOL%VAR%VARCOUNT%=Rewards:!SPACES%SPACENUM%!
SET TYPE=ITEM
CALL :REWARDSET
SET TYPE=SPECIALITEM
CALL :REWARDSET
SET TYPE=WEAPON
CALL :REWARDSET
SET TYPE=ARMOUR
CALL :REWARDSET
SET TYPE=ACCESSORY
CALL :REWARDSET
:REWARDSEND
SET /a VARCOUNT = %VARCOUNT% + 2
SET /a STEALCOL = 3
SET /a STEALROWSTART = %VARCOUNT%
GOTO :EOF

:NOREWARDS
SET /a SPACENUM = !COLUMN%REWARDSCOL%WIDTH! - 10
SET COL%REWARDSCOL%VAR%VARCOUNT%=No rewards!SPACES%SPACENUM%!
GOTO :EOF

:REWARDSET
IF !ENEMY%CHOICE%SET%REWARDSET%%TYPE%NUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:REWARDLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET /a TEMP = !ENEMY%CHOICE%SET%REWARDSET%%TYPE%%COUNT%!
SET COL%REWARDSCOL%VAR%VARCOUNT%=!%TYPE%%TEMP%NAME!
CALL :REWARDLENGTH
SET /a SPACENUM = !COLUMN%REWARDSCOL%WIDTH! - %REWARDNAMELENGTH%
SET COL%REWARDSCOL%VAR%VARCOUNT%=!COL%REWARDSCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%SET%REWARDSET%%TYPE%NUM! (
	GOTO :REWARDLOOP
)
GOTO :EOF

:REWARDLENGTH
SET /a REWARDNAMELENGTH = 0
:REWARDNAMELOOPSTART
SET /a REWARDNAMELENGTH += 1
SET SUBSTR=!COL%REWARDSCOL%VAR%VARCOUNT%:~%REWARDNAMELENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :REWARDNAMELOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %REWARDNAMELENGTH% + 1
	SET SUBSTR=!COL%REWARDSCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :REWARDNAMELOOPSTART
	)
)
GOTO :EOF

:STEAL
IF !ENEMY%CHOICE%SET%REWARDSET%STEALNUM! EQU 0 (
	CALL :NOSTEAL
	GOTO :STEALEND
)
SET /a SPACENUM = !COLUMN%STEALCOL%WIDTH! - 7
SET COL%STEALCOL%VAR%VARCOUNT%=Steals:!SPACES%SPACENUM%!
SET /a COUNT = 0
:STEALLOOP
SET /a COUNT = %COUNT% + 1
SET /a VARCOUNT = %VARCOUNT% + 1
SET TYPE=!ENEMY%CHOICE%SET%REWARDSET%STEAL%COUNT%TYPE!
SET /a TEMP = !ENEMY%CHOICE%SET%REWARDSET%STEAL%COUNT%!
SET /a SPACENUM = !COLUMN%STEALCOL%WIDTH! - !%TYPE%%TEMP%NAMELENGTH!
SET COL%STEALCOL%VAR%VARCOUNT%=!%TYPE%%TEMP%NAME!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%CHOICE%SET%REWARDSET%STEALNUM! (
	GOTO :STEALLOOP
)
:STEALEND
CALL :STEALGIL
SET /a VARCOUNT = %VARCOUNT% + 2
SET /a MORPHITEMCOL = 3
SET /a MORPHITEMROWSTART = %VARCOUNT%
GOTO :EOF

:NOSTEAL
SET /a SPACENUM = !COLUMN%STEALCOL%WIDTH! - 9
SET COL%STEALCOL%VAR%VARCOUNT%=No steals!SPACES%SPACENUM%!
GOTO :EOF

:STEALGIL
SET /a VARCOUNT = %VARCOUNT% + 2
SET COL%STEALCOL%VAR%VARCOUNT%=Steal Gil - !ENEMY%CHOICE%SET%REWARDSET%STEALGIL!
CALL :STEALGILLENGTH
SET /a SPACENUM = !COLUMN%STEALCOL%WIDTH! - %STEALGILLENGTH%
SET COL%STEALCOL%VAR%VARCOUNT%=!COL%STEALCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
GOTO :EOF

:STEALGILLENGTH
SET /a STEALGILLENGTH = 0
:STEALGILLOOPSTART
SET /a STEALGILLENGTH += 1
SET SUBSTR=!COL%STEALCOL%VAR%VARCOUNT%:~%STEALGILLENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :STEALGILLOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %STEALGILLENGTH% + 1
	SET SUBSTR=!COL%STEALCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :STEALGILLOOPSTART
	)
)
GOTO :EOF

:MORPHITEM
SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - 6
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=Morph:!SPACES%SPACENUM%!
SET /a VARCOUNT = %VARCOUNT% + 1
SET TYPE=!ENEMY%CHOICE%SET%REWARDSET%MORPHTYPE!
SET /a TEMP = !ENEMY%CHOICE%SET%REWARDSET%MORPHID!
SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - !%TYPE%%TEMP%NAMELENGTH!
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=!%TYPE%%TEMP%NAME!!SPACES%SPACENUM%!
IF !ENEMY%CHOICE%SET1MORPHMINPERC! LSS 10 (
	SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - 32
) ELSE (
	SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - 33
)
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=Must have less than !ENEMY%CHOICE%SET1MORPHMINPERC! percent HP!SPACES%SPACENUM%!
IF !ENEMY%CHOICE%SET1MORPHMAXNUM! LSS 10 (
	SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - 26
) ELSE (
	SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - 25
)
SET /a VARCOUNT = %VARCOUNT% + 1
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=You can get a maximum of !ENEMY%CHOICE%SET%REWARDSET%MORPHMAXNUM!!SPACES%SPACENUM%!
:MORPHITEMEND
CALL :MORPHGIL
SET /a VARCOUNT = %VARCOUNT% + 2
::SET /a MORPHCOL = 3
::SET /a MORPHROWSTART = %VARCOUNT%
GOTO :EOF

:MORPHGIL
SET /a VARCOUNT = %VARCOUNT% + 2
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=Morph Gil - !ENEMY%CHOICE%SET%REWARDSET%MORPHGIL!
CALL :MORPHGILLENGTH
SET /a SPACENUM = !COLUMN%MORPHITEMCOL%WIDTH! - %MORPHGILLENGTH%
SET COL%MORPHITEMCOL%VAR%VARCOUNT%=!COL%MORPHITEMCOL%VAR%VARCOUNT%!!SPACES%SPACENUM%!
GOTO :EOF

:MORPHGILLENGTH
SET /a MORPHGILLENGTH = 0
:MORPHGILLOOPSTART
SET /a MORPHGILLENGTH += 1
SET SUBSTR=!COL%MORPHITEMCOL%VAR%VARCOUNT%:~%MORPHGILLENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :MORPHGILLOOPSTART
) ELSE (
	SET /a TEMPCOUNT = %MORPHGILLENGTH% + 1
	SET SUBSTR=!COL%MORPHITEMCOL%VAR%VARCOUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :MORPHGILLOOPSTART
	)
)
GOTO :EOF



:DISPLAY
CLS
ECHO.
ECHO. %MENUNAME%: Here we are...
ECHO.
ECHO. ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
ECHO. ³ %COL1VAR1% ³ %COL2VAR1% ³ %COL3VAR1% ³
ECHO. ³ %COL1VAR2% ³ %COL2VAR2% ³ %COL3VAR2% ³
ECHO. ³ %COL1VAR3% ³ %COL2VAR3% ³ %COL3VAR3% ³
ECHO. ³ %COL1VAR4% ³ %COL2VAR4% ³ %COL3VAR4% ³
ECHO. ³ %COL1VAR5% ³ %COL2VAR5% ³ %COL3VAR5% ³
ECHO. ³ %COL1VAR6% ³ %COL2VAR6% ³ %COL3VAR6% ³
ECHO. ³ %COL1VAR7% ³ %COL2VAR7% ³ %COL3VAR7% ³
ECHO. ³ %COL1VAR8% ³ %COL2VAR8% ³ %COL3VAR8% ³
ECHO. ³ %COL1VAR9% ³ %COL2VAR9% ³ %COL3VAR9% ³
ECHO. ³ %COL1VAR10% ³ %COL2VAR10% ³ %COL3VAR10% ³
ECHO. ³ %COL1VAR11% ³ %COL2VAR11% ³ %COL3VAR11% ³
ECHO. ³ %COL1VAR12% ³ %COL2VAR12% ³ %COL3VAR12% ³
ECHO. ³ %COL1VAR13% ³ %COL2VAR13% ³ %COL3VAR13% ³
ECHO. ³ %COL1VAR14% ³ %COL2VAR14% ³ %COL3VAR14% ³
ECHO. ³ %COL1VAR15% ³ %COL2VAR15% ³ %COL3VAR15% ³
ECHO. ³ %COL1VAR16% ³ %COL2VAR16% ³ %COL3VAR16% ³
ECHO. ³ %COL1VAR17% ³ %COL2VAR17% ³ %COL3VAR17% ³
ECHO. ³ %COL1VAR18% ³ %COL2VAR18% ³ %COL3VAR18% ³
ECHO. ³ %COL1VAR19% ³ %COL2VAR19% ³ %COL3VAR19% ³
ECHO. ³ %COL1VAR20% ³ %COL2VAR20% ³ %COL3VAR20% ³
ECHO. ³ %COL1VAR21% ³ %COL2VAR21% ³ %COL3VAR21% ³
ECHO. ³ %COL1VAR22% ³ %COL2VAR22% ³ %COL3VAR22% ³
ECHO. ³ %COL1VAR23% ³ %COL2VAR23% ³ %COL3VAR23% ³
ECHO. ³ %COL1VAR24% ³ %COL2VAR24% ³ %COL3VAR24% ³
ECHO. ³ %COL1VAR25% ³ %COL2VAR25% ³ %COL3VAR25% ³
ECHO. ³ %COL1VAR26% ³ %COL2VAR26% ³ %COL3VAR26% ³
ECHO. ³ %COL1VAR27% ³ %COL2VAR27% ³ %COL3VAR27% ³
ECHO. ³ %COL1VAR28% ³ %COL2VAR28% ³ %COL3VAR28% ³
ECHO. ³ %COL1VAR29% ³ %COL2VAR29% ³ %COL3VAR29% ³
ECHO. ³ %COL1VAR30% ³ %COL2VAR30% ³ %COL3VAR30% ³
ECHO. ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
ECHO.
GOTO :EOF