SET /a PLAYERDISPLAYMAXHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a PLAYERDISPLAYMAXMP = %PLAYERBASEMAXMP% + %PLAYEREQUIPMAXMP%
SET /a PLAYERDISPLAYSTR = %PLAYERBASESTR% + %PLAYEREQUIPSTR%
SET /a PLAYERDISPLAYEND = %PLAYERBASEEND% + %PLAYEREQUIPEND%
SET /a PLAYERDISPLAYMAG = %PLAYERBASEMAG% + %PLAYEREQUIPMAG%
SET /a PLAYERDISPLAYSPR = %PLAYERBASESPR% + %PLAYEREQUIPSPR%
SET /a PLAYERDISPLAYACC = %PLAYERBASEACC% + %PLAYEREQUIPACC%
SET /a PLAYERDISPLAYEVA = %PLAYERBASEEVA% + %PLAYEREQUIPEVA%
SET /a PLAYERDISPLAYSPD = %PLAYERBASESPD% + %PLAYEREQUIPSPD%
SET /a PLAYERDISPLAYLCK = %PLAYERBASELCK% + %PLAYEREQUIPLCK%
SET /a PLAYERDISPLAYMAXLIMITBREAK = %PLAYERMAXLIMITBREAK%
SET /a REQUIREDEXPDISPLAY = %REQEXP% - %EXP%
SET TEMP=DISPLAY
SET TEMP2=with
SET TEMP3=without
SET STAT=HP
CALL :BARVAR
SET STAT=MP
CALL :BARVAR
SET STAT=LIMITBREAK
CALL :BARVAR
:START
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Here are your stats %TEMP2% equipment.
ECHO.
ECHO Level          %PLAYERLVL%
ECHO Experience     %EXP%
ECHO Required Exp   %REQUIREDEXPDISPLAY%
ECHO Gil            %PLAYERGIL%
ECHO Limit Break    %PLAYERLIMITBREAKBAR%
ECHO.
ECHO HP             %PLAYERHP%/!PLAYER%TEMP%MAXHP!!SPACES%SPACENUMHP%!%PLAYERHPBAR%
ECHO MP             %PLAYERMP%/!PLAYER%TEMP%MAXMP!!SPACES%SPACENUMMP%!%PLAYERMPBAR%
ECHO Strength       !PLAYER%TEMP%STR!
ECHO Endurance      !PLAYER%TEMP%END!
ECHO Magic          !PLAYER%TEMP%MAG!
ECHO Spirit         !PLAYER%TEMP%SPR!
ECHO Accuracy       !PLAYER%TEMP%ACC!
ECHO Evasion        !PLAYER%TEMP%EVA!
ECHO Speed          !PLAYER%TEMP%SPD!
ECHO Luck           !PLAYER%TEMP%LCK!
ECHO.
IF %PLAYERBLIND% EQU 1 (
	ECHO You are currently Blind
)
IF %PLAYERSILENCE% EQU 1 (
	ECHO You are currently Silenced
)
IF %PLAYERPOISON% EQU 1 (
	ECHO You are currently Poisoned
)
IF %PLAYERSLOW% EQU 1 (
	ECHO You are currently Slowed
)
SET /a COUNT = 0
:SPECIALLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP4=!SPECIAL%COUNT%NICKNAME!
IF !PLAYER%TEMP%! EQU 1 (
	ECHO You have the !SPECIAL%COUNT%NAME! Special active
)
ECHO.
ECHO. 1 - Show stats %TEMP3% equipment
ECHO. 0 - Exit
ECHO.
CHOICE /C:01 /N
IF "%ERRORLEVEL%" EQU "1" (
	GOTO :EOF
) ELSE IF "%ERRORLEVEL%" EQU "2" (
	CALL :CHANGE
	GOTO :START
) ELSE (
	GOTO :START
)
GOTO :EOF

:CHANGE
IF %TEMP% EQU DISPLAY (
	SET TEMP=BASE
	SET TEMP2=without
	SET TEMP3=with
) ELSE IF %TEMP% EQU BASE (
	SET TEMP=DISPLAY
	SET TEMP2=with
	SET TEMP3=without
)
GOTO :EOF

:BARVAR
SET /a BARNUM = (((!PLAYER%STAT%!)*10)/!PLAYERDISPLAYMAX%STAT%!)
IF %BARNUM% GTR 10 (
	SET /a BARNUM = 10
)
IF %BARNUM% EQU 0 (
	IF !PLAYER%STAT%! NEQ 0 (
		SET /a BARNUM = 1
	)
)
CALL :BARVAR%BARNUM%
::SET TEMP=!PLAYER%STAT%!/!PLAYER%TEMP%MAX%STAT%!
CALL :SPACES
GOTO :EOF

:SPACES
IF !PLAYER%STAT%! GEQ 10000 (
	SET /a SPACENUM1 = 1
) ELSE IF !PLAYER%STAT%! GEQ 1000 (
	SET /a SPACENUM1 = 2
) ELSE IF !PLAYER%STAT%! GEQ 100 (
	SET /a SPACENUM1 = 3
) ELSE IF !PLAYER%STAT%! GEQ 10 (
	SET /a SPACENUM1 = 4
) ELSE (
	SET /a SPACENUM1 = 5
)
IF !PLAYER%TEMP%MAX%STAT%! GEQ 10000 (
	SET /a SPACENUM2 = 1
) ELSE IF !PLAYER%TEMP%MAX%STAT%! GEQ 1000 (
	SET /a SPACENUM2 = 2
) ELSE IF !PLAYER%TEMP%MAX%STAT%! GEQ 100 (
	SET /a SPACENUM2 = 3
) ELSE IF !PLAYER%TEMP%MAX%STAT%! GEQ 10 (
	SET /a SPACENUM2 = 4
) ELSE (
	SET /a SPACENUM2 = 5
)
SET /a SPACENUM%STAT% = %SPACENUM1% + %SPACENUM2%
GOTO :EOF

:BARVAR10
SET PLAYER%STAT%BAR=€€€€€€€€€€
GOTO :EOF

:BARVAR9
SET PLAYER%STAT%BAR=€€€€€€€€€∞
GOTO :EOF

:BARVAR8
SET PLAYER%STAT%BAR=€€€€€€€€∞∞
GOTO :EOF

:BARVAR7
SET PLAYER%STAT%BAR=€€€€€€€∞∞∞
GOTO :EOF

:BARVAR6
SET PLAYER%STAT%BAR=€€€€€€∞∞∞∞
GOTO :EOF

:BARVAR5
SET PLAYER%STAT%BAR=€€€€€∞∞∞∞∞
GOTO :EOF

:BARVAR4
SET PLAYER%STAT%BAR=€€€€∞∞∞∞∞∞
GOTO :EOF

:BARVAR3
SET PLAYER%STAT%BAR=€€€∞∞∞∞∞∞∞
GOTO :EOF

:BARVAR2
SET PLAYER%STAT%BAR=€€∞∞∞∞∞∞∞∞
GOTO :EOF

:BARVAR1
SET PLAYER%STAT%BAR=€∞∞∞∞∞∞∞∞∞
GOTO :EOF

:BARVAR0
SET PLAYER%STAT%BAR=∞∞∞∞∞∞∞∞∞∞
GOTO :EOF