:SKILLS
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The skills you currently have are...
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = 30 - !SKILL%COUNT%NAMELENGTH!
SET TEMP=!SKILL%COUNT%UNLOCKFIELD!
IF !PLAYERSKILL%COUNT%ENABLED! EQU 1 (
	IF !PLAYERSKILL%COUNT%EARNED! EQU 1 (
		ECHO !SKILL%COUNT%NAME!!SPACES%SPACENUM%!!SKILL%COUNT%APCOST! AP - Earned
	) ELSE (
		ECHO !SKILL%COUNT%NAME!!SPACES%SPACENUM%!!SKILL%COUNT%APCOST! AP - Earn by !SKILL%COUNT%EARNTEXT! - !%TEMP%! so far
	)
)
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOPSTART
) 
ECHO.
ECHO. 1 - Descriptions
ECHO. 2 - Limit Breaks
ECHO. 0 - Back
ECHO.
:CHOICE
CHOICE /C:012 /N
IF "%ERRORLEVEL%" EQU "1" (
	GOTO :EOF
) ELSE IF "%ERRORLEVEL%" EQU "2" (
	CALL :DESCRIPTIONS
) ELSE IF "%ERRORLEVEL%" EQU "3" (
	CALL :LIMITBREAKS
)
GOTO :EOF


:DESCRIPTIONS
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The skills you currently have are...
ECHO.
SET /a COUNT = 0
:LOOP2START
SET /a COUNT = %COUNT%+1
IF !PLAYERSKILL%COUNT%ENABLED! EQU 1 (
	ECHO !SKILL%COUNT%NAME! - !SKILL%COUNT%DESCRIPTION!
)
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOP2START
) 
ECHO.
ECHO. 1 - AP Cost and Earning Details
ECHO. 2 - Limit Breaks
ECHO. 0 - Back
ECHO.
:CHOICE
CHOICE /C:012 /N
IF "%ERRORLEVEL%" EQU "1" (
	GOTO :EOF
) ELSE IF "%ERRORLEVEL%" EQU "2" (
	CALL :SKILLS
) ELSE IF "%ERRORLEVEL%" EQU "3" (
	CALL :LIMITBREAKS
)
GOTO :EOF

:LIMITBREAKS
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The limit breaks that your skills contribute to are...
ECHO.
SET /a COUNT = 0
:LOOP3START
SET /a COUNT = %COUNT%+1
IF !PLAYERSKILL%COUNT%ENABLED! EQU 1 (
	CALL :LIMITS
)
IF %COUNT% LSS %SKILLTOT% (
	GOTO :LOOP3START
) 
ECHO.
ECHO. 1 - AP Cost and Earning Details
ECHO. 2 - Descriptions
ECHO. 0 - Back
ECHO.
:CHOICE
CHOICE /C:012 /N
IF "%ERRORLEVEL%" EQU "1" (
	GOTO :EOF
) ELSE IF "%ERRORLEVEL%" EQU "2" (
	CALL :SKILLS
) ELSE IF "%ERRORLEVEL%" EQU "3" (
	CALL :DESCRIPTIONS
)
GOTO :EOF

:LIMITS
SET /a TEMP = !SKILL%COUNT%LIMITBREAK!
ECHO !SKILL%COUNT%NAME! - !LIMITBREAK%TEMP%NAME!
GOTO :EOF




