CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The Items you currently hold are...
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = 25 - !ITEM%COUNT%NAMELENGTH!
IF !PLAYERITEM%COUNT%NUM! EQU 1 (
	ECHO. !PLAYERITEM%COUNT%NUM! !ITEM%COUNT%NAME!!SPACES%SPACENUM%!  - !ITEM%COUNT%DESCRIPTION!
) ELSE IF !PLAYERITEM%COUNT%NUM! GTR 9 (
	ECHO. !PLAYERITEM%COUNT%NUM! !ITEM%COUNT%NAME!s!SPACES%SPACENUM%!- !ITEM%COUNT%DESCRIPTION!
) ELSE IF !PLAYERITEM%COUNT%NUM! GTR 1 (
	ECHO. !PLAYERITEM%COUNT%NUM! !ITEM%COUNT%NAME!s!SPACES%SPACENUM%! - !ITEM%COUNT%DESCRIPTION!
)

IF %COUNT% LSS %ITEMTOTAL% (
	GOTO :LOOPSTART
)
ECHO.
pause
GOTO :EOF