:INVENTORYSTART
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: What Items would you like to look at?
ECHO.
ECHO. 1 - Usable Items
ECHO. 2 - Special Items
ECHO. 3 - Key Items
IF %CUSTOMITEMSUNLOCKED% EQU 1 (
	ECHO. 4 - Custom Items
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P INVENTORYCHOICE=
ECHO.
IF "%INVENTORYCHOICE%" EQU "1" (
	CALL "%MENURESOURCEPATH%\inventory.bat"
) ELSE IF "%INVENTORYCHOICE%" EQU "2" (
	CALL "%MENURESOURCEPATH%\specialinventory.bat"
) ELSE IF "%INVENTORYCHOICE%" EQU "3" (
	CALL "%MENURESOURCEPATH%\keyinventory.bat"
) ELSE IF "%INVENTORYCHOICE%" EQU "4" (
	IF %CUSTOMITEMSUNLOCKED% EQU 1 (
		CALL "%MENURESOURCEPATH%\custominventory.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%INVENTORYCHOICE%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :CHOICE
)
GOTO :INVENTORYSTART
















:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF