CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The Key Items you currently hold are...
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = 30 - !KEYITEM%COUNT%NAMELENGTH!
IF !PLAYERKEYITEM%COUNT%ACQUIRED! EQU 1 (
	ECHO. !KEYITEM%COUNT%NAME! !SPACES%SPACENUM%!- !KEYITEM%COUNT%DESCRIPTION!
)
IF %COUNT% LSS %KEYITEMTOTAL% (
	GOTO :LOOPSTART
)
ECHO.
pause
GOTO :EOF