CALL :INITIALISE
CALL :DISPLAYPAGE
GOTO :EOF

:INITIALISE
SET /a COUNT = %PAGETOT% + 1
:INITIALISELOOP
SET /a COUNT = %COUNT% - 1
SET /a TEMP = !PAGE%COUNT%START!
IF !STORY%TEMP%VERSIONNUM! NEQ 0 (
	SET /a MAXPAGENUM = %COUNT%
	SET /a PAGENUM = %COUNT%
	GOTO :EOF
)
IF %COUNT% GEQ 1 (
	GOTO :INITIALISELOOP
)
GOTO :EOF

:DISPLAYPAGE
CLS
ECHO.
SET /a COUNT = !PAGE%PAGENUM%START! - 1
:DISPLAYLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!STORY%COUNT%VERSIONNUM!
SET /a LINECOUNT = 0
:DISPLAYLOOP2
SET /a LINECOUNT = %LINECOUNT% + 1
IF !STORY%COUNT%VERSIONNUM! GTR 0 (
	ECHO. !STORY%COUNT%VERSION%TEMP%LINE%LINECOUNT%!
) ELSE (
	ECHO.
)
IF %LINECOUNT% LSS !STORY%COUNT%VERSION%TEMP%LINETOT! (
	GOTO :DISPLAYLOOP2
)
ECHO.
IF %COUNT% LSS !PAGE%PAGENUM%END! (
	GOTO :DISPLAYLOOP
)
ECHO. 1 - Previous Page
ECHO. 2 - Next Page
ECHO. 0 - Exit
ECHO.
CHOICE /C:120 /N
IF %ERRORLEVEL% EQU 1 (
	SET /a PAGENUM = %PAGENUM% - 1
) ELSE IF %ERRORLEVEL% EQU 2 (
	SET /a PAGENUM = %PAGENUM% + 1
) ELSE IF %ERRORLEVEL% EQU 3 (
	GOTO :EOF
)
CALL :VALIDPAGEQUERY
GOTO :DISPLAYPAGE

:VALIDPAGEQUERY
IF %PAGENUM% GTR %MAXPAGENUM% (
	SET /a PAGENUM = %MAXPAGENUM%
) ELSE IF %PAGENUM% LSS 1 (
	SET /a PAGENUM = 1
)
GOTO :EOF