SET /a MAXSPACENUM = 33
CALL :FAVOURITELIMITBREAK
CALL :CALCULATEPLAYTIME
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Ok two seconds, I just need to count everything up...
ECHO.
SET RECORD1-1=Number of Saves %TIMESSAVED%
SET RECORD1-2=Battles fought %BATTLETOTAL%
SET RECORD1-3=Battles won %BATTLEWINTOTAL%
SET RECORD1-4=Battles lost %BATTLELOSETOTAL%
SET RECORD1-5=Guitar Battles fought %GUITARBATTLETOTAL%
SET RECORD1-6=Guitar Battles won %GUITARBATTLEWINTOTAL%
SET RECORD1-7=Guitar Battles lost %GUITARBATTLELOSETOTAL%
SET RECORD1-8=Number of Attacks %PLAYERATTACKCOUNT%
SET RECORD1-9=Number of Misses %PLAYERMISSCOUNT%
SET RECORD1-10=Number of Dodges %DODGESUCCESSCOUNT%
SET RECORD1-11=Number of Catches %CATCHSUCCESSCOUNT%
SET RECORD1-12=Number of Runs %RUNSUCCESSCOUNT%
SET RECORD1-13=Items Used %PLAYERUSEITEMCOUNT%
SET RECORD1-14=Successful Steals %STEALSUCCESSCOUNT%
SET RECORD1-15=Critical Hits %CRITICALHITSUCCESSCOUNT%
SET RECORD1-16=Gil Stolen %GILSTOLENCOUNT%
SET RECORD1-17=Gil Thrown %GILTHROWNCOUNT%
SET RECORD1-18=Gil from Transforming %TRANSGILCOUNT%
SET RECORD1-19=MP Stolen %MPSTOLENCOUNT%
SET RECORD1-20=Limit Breaks Used %LIMITBREAKUSED%
SET RECORD1-21=Favourite Limit Break:
SET RECORD1-22=%FAVOURITELIMITBREAK%
SET RECORD1-23=Play Time: %HOURSPLAYTIMETEMP%:%MINSPLAYTIMETEMP%
SET /a RECORD1TOT = 23
SET RECORD2-1=Fire Spells Cast %FIRESPELLSCASTCOUNT%
SET RECORD2-2=Ice Spells Cast %ICESPELLSCASTCOUNT%
SET RECORD2-3=Electricity Spells Cast %ELECTRICITYSPELLSCASTCOUNT%
SET RECORD2-4=Water Spells Cast %WATERSPELLSCASTCOUNT%
SET RECORD2-5=Earth Spells Cast %EARTHSPELLSCASTCOUNT%
SET RECORD2-6=Forbidden Spells Cast %FORBIDDENSPELLSCASTCOUNT%
SET RECORD2-7=Custom Spells Cast %CUSTOMSPELLSCASTCOUNT%
SET RECORD2-8=Very Effective Spells Cast %WEAKNESSSPELLCOUNT%
SET RECORD2-9=Ineffective Spells Cast %STRENGTHSPELLCOUNT%
SET RECORD2-10=Element Immune Spells Cast %ELEMENTIMMUNESPELLCOUNT%
SET RECORD2-11=Absorbed Spells Cast %ABSORBSPELLCOUNT%
SET RECORD2-12=Status Immune Spells Cast %STATUSIMMUNESPELLCOUNT%
SET /a RECORD2TOT = 12
IF %BEATEMWEAPONCOUNT% GTR 0 (
	SET RECORD2-13=Emerald Weapon Death Count %BEATEMWEAPONCOUNT%
	SET /a RECORD2TOT = 13
)
SET RECORD3-1=Roulette Games Played %ROULETTEPLAYEDTOTAL%
SET RECORD3-2=Roulette Games Won %ROULETTEWINTOTAL%
SET RECORD3-3=Roulette Games Lost %ROULETTELOSETOTAL%
SET RECORD3-4=Total Roulette Profit %ROULETTEPROFIT%
SET RECORD3-5=Blackjack Games Played %BLACKJACKPLAYEDTOTAL%
SET RECORD3-6=Blackjack Games Won %BLACKJACKWINTOTAL%
SET RECORD3-7=Blackjack Games Lost %BLACKJACKLOSETOTAL%
SET RECORD3-8=Total Blackjack Profit %BLACKJACKPROFIT%
SET RECORD3-9=Slot Machine Games Played %SLOTMACHINEPLAYEDTOTAL%
SET RECORD3-10=Slot Machine Games Won %SLOTMACHINEWINTOTAL%
SET RECORD3-11=Slot Machine Games Lost %SLOTMACHINELOSETOTAL%
SET RECORD3-12=Total Slot Machine Profit %SLOTMACHINEPROFIT%
SET RECORD3-13=Total Casino Profit %TOTALCASINOPROFIT%
SET RECORD3-14=Total Temple Donation %PLAYERTEMPLEDONATIONTOTAL%
SET RECORD3-15=Temple Discount %PLAYERTEMPLEDONATIONREDUCTION%
SET RECORD3-16=Total Mine Hauls %PLAYERHAULTOTAL%
SET /a RECORD3TOT = 16
CALL :CALCULATELENGTHS
CALL :CALCULATEVARIABLES
CALL :DISPLAY
pause
GOTO :EOF

:CALCULATELENGTHS
SET /a SETCOUNT = 0
:LOOP1
SET /a COUNT = 0
SET /a SETCOUNT = %SETCOUNT% + 1
:LOOP2
SET /a COUNT = %COUNT% + 1
SET /a LENGTH = 9
:LOOP3
SET /a LENGTH += 1
SET SUBSTR=!RECORD%SETCOUNT%-%COUNT%:~%LENGTH%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :LOOP3
) ELSE (
	SET /a TEMPCOUNT = %LENGTH% + 1
	SET SUBSTR=!RECORD%SETCOUNT%-%COUNT%:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :LOOP3
	)
)
SET /a RECORD%SETCOUNT%a%COUNT%LENGTH=%LENGTH%
IF %COUNT% LSS !RECORD%SETCOUNT%TOT! (
	GOTO :LOOP2
) ELSE IF %SETCOUNT% LSS 3 (
	GOTO :LOOP1
)
GOTO :EOF

:CALCULATEVARIABLES
SET /a SETCOUNT = 0
:LOOP4
SET /a COUNT = 0
SET /a SETCOUNT = %SETCOUNT% + 1
:LOOP5
SET /a COUNT = %COUNT% + 1
IF DEFINED RECORD%SETCOUNT%-%COUNT% (
	CALL :YES
) ELSE (
	CALL :NO
)
IF %COUNT% LSS 30 (
	GOTO :LOOP5
) ELSE IF %SETCOUNT% LSS 3 (
	GOTO :LOOP4
)
GOTO :EOF

:YES
SET /a SPACENUM = %MAXSPACENUM% - !RECORD%SETCOUNT%a%COUNT%LENGTH!
SET COL%SETCOUNT%VAR%COUNT%=!RECORD%SETCOUNT%-%COUNT%!!SPACES%SPACENUM%!
GOTO :EOF

:NO
SET COL%SETCOUNT%VAR%COUNT%=!SPACES%MAXSPACENUM%!
GOTO :EOF

:DISPLAY
CLS
ECHO.
ECHO %MENUNAME%: Here are your records for this game.
ECHO.
ECHO. ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
ECHO. ³ %COL1VAR1% ³ %COL2VAR1% ³ %COL3VAR1% ³
ECHO. ³ %COL1VAR2% ³ %COL2VAR2% ³ %COL3VAR2% ³
ECHO. ³ %COL1VAR3% ³ %COL2VAR3% ³ %COL3VAR3% ³
ECHO. ³ %COL1VAR4% ³ %COL2VAR4% ³ %COL3VAR4% ³
ECHO. ³ %COL1VAR5% ³ %COL2VAR5% ³ %COL3VAR5% ³
ECHO. ³ %COL1VAR6% ³ %COL2VAR6% ³ %COL3VAR6% ³
ECHO. ³ %COL1VAR7% ³ %COL2VAR7% ³ %COL3VAR7% ³
ECHO. ³ %COL1VAR8% ³ %COL2VAR8% ³ %COL3VAR8% ³
ECHO. ³ %COL1VAR9% ³ %COL2VAR9% ³ %COL3VAR9% ³
ECHO. ³ %COL1VAR10% ³ %COL2VAR10% ³ %COL3VAR10% ³
ECHO. ³ %COL1VAR11% ³ %COL2VAR11% ³ %COL3VAR11% ³
ECHO. ³ %COL1VAR12% ³ %COL2VAR12% ³ %COL3VAR12% ³
ECHO. ³ %COL1VAR13% ³ %COL2VAR13% ³ %COL3VAR13% ³
ECHO. ³ %COL1VAR14% ³ %COL2VAR14% ³ %COL3VAR14% ³
ECHO. ³ %COL1VAR15% ³ %COL2VAR15% ³ %COL3VAR15% ³
ECHO. ³ %COL1VAR16% ³ %COL2VAR16% ³ %COL3VAR16% ³
ECHO. ³ %COL1VAR17% ³ %COL2VAR17% ³ %COL3VAR17% ³
ECHO. ³ %COL1VAR18% ³ %COL2VAR18% ³ %COL3VAR18% ³
ECHO. ³ %COL1VAR19% ³ %COL2VAR19% ³ %COL3VAR19% ³
ECHO. ³ %COL1VAR20% ³ %COL2VAR20% ³ %COL3VAR20% ³
ECHO. ³ %COL1VAR21% ³ %COL2VAR21% ³ %COL3VAR21% ³
ECHO. ³ %COL1VAR22% ³ %COL2VAR22% ³ %COL3VAR22% ³
ECHO. ³ %COL1VAR23% ³ %COL2VAR23% ³ %COL3VAR23% ³
ECHO. ³ %COL1VAR24% ³ %COL2VAR24% ³ %COL3VAR24% ³
ECHO. ³ %COL1VAR25% ³ %COL2VAR25% ³ %COL3VAR25% ³
ECHO. ³ %COL1VAR26% ³ %COL2VAR26% ³ %COL3VAR26% ³
ECHO. ³ %COL1VAR27% ³ %COL2VAR27% ³ %COL3VAR27% ³
ECHO. ³ %COL1VAR28% ³ %COL2VAR28% ³ %COL3VAR28% ³
ECHO. ³ %COL1VAR29% ³ %COL2VAR29% ³ %COL3VAR29% ³
ECHO. ³ %COL1VAR30% ³ %COL2VAR30% ³ %COL3VAR30% ³
ECHO. ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
GOTO :EOF

:FAVOURITELIMITBREAK
SET /a FAVENUM = 1
SET /a TOPCOUNT = 0
SET /a COUNT = 0
:LIMITBREAKLOOP
SET /a COUNT = %COUNT% + 1
IF !LIMITBREAK%COUNT%USED! GTR %TOPCOUNT% (
	SET /a FAVENUM = %COUNT%
	SET /a TOPCOUNT = !LIMITBREAK%COUNT%USED!
)
IF %COUNT% LSS %LIMITBREAKTOT% (
	GOTO :LIMITBREAKLOOP
)
SET FAVOURITELIMITBREAK=!LIMITBREAK%FAVENUM%NAME!
GOTO :EOF

:CALCULATEPLAYTIME
SET PREFIX=PLAYEND
CALL "%MISCRESOURCEPATH%\calculatedatetime.bat"
SET BEFORE=PLAYSTART
SET AFTER=PLAYEND
CALL "%MISCRESOURCEPATH%\calculatetimediff.bat"
SET /a MINSPLAYTIMETEMP = %MINSPLAYTIME% + %MINTIME%
SET /a EXTRAHOURS = %MINSPLAYTIMETEMP%/60
SET /a MINSPLAYTIMETEMP = %MINSPLAYTIMETEMP% - (60*%EXTRAHOURS%)
SET /a HOURSPLAYTIMETEMP = %HOURSPLAYTIME% + %HOURTIME% + %EXTRAHOURS%
GOTO :EOF