:START
SET /a REMOTEACCESS = 1
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Which facility would you like to access remotely?
ECHO.
IF %TEMPLEREMOTEACCESS% EQU 1 (
	ECHO. 1 - Temple
)
IF %TRAININGREMOTEACCESS% EQU 1 (
	ECHO. 2 - Training
)
IF %SHOPREMOTEACCESS% EQU 1 (
	ECHO. 3 - Shops
)
IF %CASINOREMOTEACCESS% EQU 1 (
	ECHO. 4 - Casino
)
IF %DWARFMINEREMOTEACCESS% EQU 1 (
	ECHO. 5 - Dwarf Mine
)
IF %BLACKSMITHREMOTEACCESS% EQU 1 (
	ECHO. 6 - Blacksmith
)
IF %ALCHEMISTREMOTEACCESS% EQU 1 (
	ECHO. 7 - Alchemist
)
IF %GURUREMOTEACCESS% EQU 1 (
	ECHO. 8 - Guru
)
IF %TUTORIALREMOTEACCESS% EQU 1 (
	ECHO. 9 - Tutorial
)
IF %TELEPORTREMOTEACCESS% EQU 1 (
	ECHO. 10 - Teleport
	SET /a EXITMAP = 1
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P CHOICE=
ECHO.
IF "%CHOICE%" EQU "1" (
	IF %TEMPLEREMOTEACCESS% EQU 1 (
		CALL "%TEMPLERESOURCEPATH%\entertemple.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "2" (
	IF %TRAININGREMOTEACCESS% EQU 1 (
		CALL "%TRAININGRESOURCEPATH%\initiatetraining.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "3" (
	IF %SHOPREMOTEACCESS% EQU 1 (
		CALL "%MENURESOURCEPATH%\shopremoteaccess.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "4" (
	IF %CASINOREMOTEACCESS% EQU 1 (
		CALL "%CASINORESOURCEPATH%\entercasino.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "5" (
	IF %DWARFMINEREMOTEACCESS% EQU 1 (
		CALL "%MINERESOURCEPATH%\entergoldmine.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "6" (
	IF %BLACKSMITHREMOTEACCESS% EQU 1 (
		CALL "%BLACKSMITHRESOURCEPATH%\enterblacksmith.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "7" (
	IF %ALCHEMISTREMOTEACCESS% EQU 1 (
		CALL "%ALCHEMISTRESOURCEPATH%\enteralchemist.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "8" (
	IF %GURUREMOTEACCESS% EQU 1 (
		CALL "%GURURESOURCEPATH%\enterguru.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "9" (
	IF %TUTORIALREMOTEACCESS% EQU 1 (
		CALL "%TUTORIALRESOURCEPATH%\entertutorial.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "10" (
	IF %TELEPORTREMOTEACCESS% EQU 1 (
		CALL "%TELEPORTRESOURCEPATH%\enterteleport.bat"
	) ELSE (
		GOTO :CHOICE
	)
) ELSE IF "%CHOICE%" EQU "0" (
	SET /a REMOTEACCESS = 0
	GOTO :EOF
) ELSE (
	GOTO :CHOICE
)
GOTO :START



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF