IF %QUICKSAVE% EQU 1 (
	SET SAVEFILE=quicksave
	GOTO :SAVESTART
)
CALL "%MENURESOURCEPATH%\menudisplay.bat"
:SELECTSLOT
CALL "%SAVERESOURCEPATH%\savelist.bat"
ECHO %MENUNAME%: Select a save slot
ECHO.
ECHO. 1 - %SAVESLOT1NAME%
ECHO. 2 - %SAVESLOT2NAME%
ECHO. 3 - %SAVESLOT3NAME%
ECHO. 4 - %SAVESLOT4NAME%
ECHO. 5 - %SAVESLOT5NAME%
ECHO. 6 - %SAVESLOT6NAME%
ECHO. 7 - %SAVESLOT7NAME%
ECHO. 8 - %SAVESLOT8NAME%
ECHO. 9 - %SAVESLOT9NAME%
ECHO. 0 - Back
ECHO.
SET /P SAVESLOTNUM=
IF "%SAVESLOTNUM%" EQU "" (
	GOTO :SELECTSLOT
	CLS
	ECHO.
)
IF %SAVESLOTNUM% GTR 9 (
	GOTO :SELECTSLOT
	CLS
	ECHO.
) ELSE IF %SAVESLOTNUM% LSS 0 (
	GOTO :SELECTSLOT
	CLS
	ECHO.
) ELSE IF %SAVESLOTNUM% EQU 0 (
	GOTO :EOF
)
ECHO.
ECHO Name your saved game (one word please)
ECHO.
ECHO Leave blank to keep the same name as before
ECHO.
SET /P SAVESLOT%SAVESLOTNUM%NAME=
ECHO.
SET SAVEFILE=Slot%SAVESLOTNUM%\!SAVESLOT%SAVESLOTNUM%NAME!
:SAVESTART
CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: Ok darlin' I'll just get your game saved there for ya^^!
ECHO.
ECHO SET SAVESLOT%SAVESLOTNUM%NAME=!SAVESLOT%SAVESLOTNUM%NAME!>>"%SAVERESOURCEPATH%\savelist.bat"

SET /a TIMESSAVED = %TIMESSAVED%+1
::Play Time
SET PREFIX=PLAYEND
CALL "%MISCRESOURCEPATH%\calculatedatetime.bat"
SET BEFORE=PLAYSTART
SET AFTER=PLAYEND
CALL "%MISCRESOURCEPATH%\calculatetimediff.bat"
SET /a MINSPLAYTIME = %MINSPLAYTIME% + %MINTIME%
SET /a EXTRAHOURS = %MINSPLAYTIME%/60
SET /a MINSPLAYTIME = %MINSPLAYTIME% - (60*%EXTRAHOURS%)
SET /a HOURSPLAYTIME = %HOURSPLAYTIME% + %HOURTIME% + %EXTRAHOURS%
SET PREFIX=PLAYSTART
CALL "%MISCRESOURCEPATH%\calculatedatetime.bat"
ECHO SET DIFFICULTY=%DIFFICULTY%>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a HOURSPLAYTIME = %HOURSPLAYTIME% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a MINSPLAYTIME = %MINSPLAYTIME% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a AUTOBATTLE = %AUTOBATTLE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM PLAYER LOCATION
ECHO SET /a PLAYERXCOORD=%PLAYERXCOORD% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERYCOORD=%PLAYERYCOORD% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET MAP=%MAP%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM PLAYER STATS
ECHO SET PLAYERNAME=%PLAYERNAME%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERNAMELENGTH = %PLAYERNAMELENGTH% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERLVL = %PLAYERLVL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a EXP = %EXP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERGIL = %PLAYERGIL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a NEWSPELLPOINT = %NEWSPELLPOINT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a NUMTRAINBATTLES = %NUMTRAINBATTLES% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEMAXHP = %PLAYERBASEMAXHP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERHP = %PLAYERHP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEMAXMP = %PLAYERBASEMAXMP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERMP = %PLAYERMP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASESTR = %PLAYERBASESTR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEEND = %PLAYERBASEEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEMAG = %PLAYERBASEMAG% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASESPR = %PLAYERBASESPR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEACC = %PLAYERBASEACC% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASEEVA = %PLAYERBASEEVA% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASESPD = %PLAYERBASESPD% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBASELCK = %PLAYERBASELCK% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a OLDREQEXP = %OLDREQEXP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a REQEXP = %REQEXP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM LIMIT BREAK
ECHO SET /a PLAYERLIMITBREAK = %PLAYERLIMITBREAK% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERMAXLIMITBREAK = %PLAYERMAXLIMITBREAK% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERLIMITBREAKACTIVE = %PLAYERLIMITBREAKACTIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM PLAYER MAGIC
REM Player's Offensive Magic
SET /a COUNT = 0
:OFFLOOPSTART
SET /a COUNT=%COUNT%+1
SET TEMPORARY=!OFF%COUNT%SPELL!
ECHO SET /a PLAYER%TEMPORARY%ENABLED = !PLAYER%TEMPORARY%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %OFFSPELLTOT% (
	GOTO :OFFLOOPSTART
)


REM Player's Status Magic
SET /a COUNT = 0
:STATLOOPSTART
SET /a COUNT=%COUNT%+1
SET TEMPORARY=!STAT%COUNT%SPELL!
ECHO SET /a PLAYER%TEMPORARY%ENABLED = !PLAYER%TEMPORARY%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %STATSPELLTOT% (
	GOTO :STATLOOPSTART
)

REM Player's Debuff Magic
REM SET /a COUNT = 0
REM :DEBLOOPSTART
REM SET /a COUNT=%COUNT%+1
REM SET TEMPORARY=!DEB%COUNT%STAT!
REM ECHO SET /a PLAYERDAMAGE%TEMPORARY%ENABLED = !PLAYERDAMAGE%TEMPORARY%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM IF %COUNT% LSS %DEBSPELLTOT% (
REM 	GOTO :DEBLOOPSTART
REM )

REM Player's Restoration Magic
SET /a COUNT = 0
:RESTLOOPSTART
SET /a COUNT=%COUNT%+1
SET TEMPORARY=!REST%COUNT%SPELL!
ECHO SET /a PLAYER%TEMPORARY%ENABLED = !PLAYER%TEMPORARY%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %RESTSPELLTOT% (
	GOTO :RESTLOOPSTART
)

REM Player's Support Magic
SET /a COUNT = 0
:SUPPLOOPSTART
SET /a COUNT=%COUNT%+1
SET TEMPORARY=!SUPP%COUNT%SPELL!
ECHO SET /a PLAYER%TEMPORARY%ENABLED = !PLAYER%TEMPORARY%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SUPPSPELLTOT% (
	GOTO :SUPPLOOPSTART
)

REM PLAYERSTATUS
ECHO SET /a PLAYERBLIND = %PLAYERBLIND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSILENCE = %PLAYERSILENCE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERPOISON = %PLAYERPOISON% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSLOW = %PLAYERSLOW% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERBLINDTURNCOUNT = %PLAYERBLINDTURNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSILENCETURNCOUNT = %PLAYERSILENCETURNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERPOISONTURNCOUNT = %PLAYERPOISONTURNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSLOWTURNCOUNT = %PLAYERSLOWTURNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERAUTOLIFE = %PLAYERAUTOLIFE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM PLAYER USABLE ITEMS
SET /a COUNT = 0
:ITEMLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERITEM%COUNT%NUM = !PLAYERITEM%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %ITEMTOTAL% (
	GOTO :ITEMLOOPSTART
)

REM PLAYER SPECIAL ITEMS
SET /a COUNT = 0
:SPECIALITEMLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERSPECIALITEM%COUNT%NUM = !PLAYERSPECIALITEM%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :SPECIALITEMLOOPSTART
)

REM PLAYER KEY ITEMS
SET /a COUNT = 0
:KEYITEMLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERKEYITEM%COUNT%ACQUIRED = !PLAYERKEYITEM%COUNT%ACQUIRED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %KEYITEMTOTAL% (
	GOTO :KEYITEMLOOPSTART
)

REM PLAYER WEAPONS ACQUIRED
SET /a COUNT = 0
:WEAPONLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERWEAPON%COUNT%NUM = !PLAYERWEAPON%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :WEAPONLOOPSTART
)

REM PLAYER ARMOUR ACQUIRED
SET /a COUNT = 0
:ARMOURLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERARMOUR%COUNT%NUM = !PLAYERARMOUR%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :ARMOURLOOPSTART
)

REM PLAYER ACCESSORY ACQUIRED
SET /a COUNT = 0
:ACCESSORYLOOPSTART
SET /a COUNT=%COUNT%+1
ECHO SET /a PLAYERACCESSORY%COUNT%NUM = !PLAYERACCESSORY%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :ACCESSORYLOOPSTART
)

REM PLAYER EQUIPMENT STATS
REM WEAPON STATS
ECHO SET PLAYERWEAPON=%PLAYERWEAPON%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERWEAPONID = %PLAYERWEAPONID% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPSTR = %PLAYEREQUIPSTR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPMAG = %PLAYEREQUIPMAG% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPACC = %PLAYEREQUIPACC% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM ARMOUR STATS
ECHO SET PLAYERARMOUR=%PLAYERARMOUR%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERARMOURID = %PLAYERARMOURID% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPEND = %PLAYEREQUIPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPSPR = %PLAYEREQUIPSPR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPEVA = %PLAYEREQUIPEVA% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPSPD = %PLAYEREQUIPSPD% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
REM ACCESSORY STATS
ECHO SET PLAYERACCESSORY=%PLAYERACCESSORY%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERACCESSORYID = %PLAYERACCESSORYID% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPMAXHP = %PLAYEREQUIPMAXHP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPMAXMP = %PLAYEREQUIPMAXMP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEREQUIPLCK = %PLAYEREQUIPLCK% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"



REM SKILLS ENABLED
SET /a COUNT = 0
:SKILLLOOPSTART
SET /a COUNT = %COUNT%+1
ECHO SET /a PLAYERSKILL%COUNT%ENABLED = !PLAYERSKILL%COUNT%ENABLED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILLLOOPSTART
)

REM SKILLS EARNED
SET /a COUNT = 0
:SKILL2LOOPSTART
SET /a COUNT = %COUNT%+1
ECHO SET /a PLAYERSKILL%COUNT%EARNED = !PLAYERSKILL%COUNT%EARNED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILL2LOOPSTART
)

ECHO SET /a PLAYERWEAKNESSNUM = %PLAYERWEAKNESSNUM% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSTRENGTHNUM = %PLAYERSTRENGTHNUM% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERELEMENTIMMUNENUM = %PLAYERELEMENTIMMUNENUM% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERABSORBNUM = %PLAYERABSORBNUM% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERSTATUSIMMUNENUM = %PLAYERSTATUSIMMUNENUM% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

:WEAKNESSES
SET /a COUNT = 0
IF %PLAYERWEAKNESSNUM% EQU 0 (
	GOTO :STRENGTHS
)
:WEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET PLAYERWEAKNESS%COUNT%=!PLAYERWEAKNESS%COUNT%!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PLAYERWEAKNESSNUM% (
	GOTO :WEAKNESSLOOP
)
:STRENGTHS
SET /a COUNT = 0
IF %PLAYERSTRENGTHNUM% EQU 0 (
	GOTO :IMMUNES
)
:STRENGTHLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET PLAYERSTRENGTH%COUNT%=!PLAYERSTRENGTH%COUNT%!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PLAYERSTRENGTHNUM% (
	GOTO :STRENGTHLOOP
)
:IMMUNES
SET /a COUNT = 0
IF %PLAYERELEMENTIMMUNENUM% EQU 0 (
	GOTO :ABSORBS
)
:IMMUNELOOP
SET /a COUNT = %COUNT% + 1
ECHO SET PLAYERELEMENTIMMUNE%COUNT%=!PLAYERELEMENTIMMUNE%COUNT%!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PLAYERELEMENTIMMUNENUM% (
	GOTO :IMMUNELOOP
)
:ABSORBS
SET /a COUNT = 0
IF %PLAYERABSORBNUM% EQU 0 (
	GOTO :STATUSIMMUNES
)
:ABSORBLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET PLAYERABSORB%COUNT%=!PLAYERABSORB%COUNT%!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PLAYERABSORBNUM% (
	GOTO :ABSORBLOOP
)
:STATUSIMMUNES
SET /a COUNT = 0
IF %PLAYERSTATUSIMMUNENUM% EQU 0 (
	GOTO :RESISTANCESEND
)
:STATUSIMMUNELOOP
SET /a COUNT = %COUNT% + 1
ECHO SET PLAYERSTATUSIMMUNE%COUNT%=!PLAYERSTATUSIMMUNE%COUNT%!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PLAYERSTATUSIMMUNENUM% (
	GOTO :STATUSIMMUNELOOP
)
:RESISTANCESEND

SET /a COUNT = 0
:SPECIALLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!SPECIAL%COUNT%NICKNAME!
ECHO SET /a PLAYER%TEMP% = !PLAYER%TEMP%! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SPECIALTOT% (
	GOTO :SPECIALLOOP
)

REM BATTLE REWARDS SET
ECHO SET /a REWARDSET = %REWARDSET% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM PLAYER ENEMIES CAUGHT
::SET /a COUNT = 0
:::ENEMYLOOPSTART
::SET /a COUNT = %COUNT% + 1
::ECHO SET ENEMY%COUNT%NAME=!ENEMY%COUNT%NAME!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
::IF %COUNT% LSS %ENEMYTOT% (
::	GOTO :ENEMYLOOPSTART
::)

SET /a COUNT = 0
:CAUGHTLOOPSTART
SET /a COUNT = %COUNT% + 1
ECHO SET /a ENEMY%COUNT%CAUGHT = !ENEMY%COUNT%CAUGHT! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %ENEMYTOT% (
	GOTO :CAUGHTLOOPSTART
)

REM CASINOSTATS
ECHO SET /a CASINOYEAR = %CASINOYEAR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOMONTH = %CASINOMONTH% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINODAY = %CASINODAY% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOHOUR = %CASINOHOUR% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOMIN = %CASINOMIN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOINCOMEPERCHUNK = %CASINOINCOMEPERCHUNK% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOVAULTCAPACITY = %CASINOVAULTCAPACITY% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ROULETTECOST = %ROULETTECOST% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKJACKCOST = %BLACKJACKCOST% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SLOTSCOST = %SLOTSCOST% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM GENERAL RECORDS
ECHO SET /a TIMESSAVED = %TIMESSAVED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GUITARBATTLETOTAL = %GUITARBATTLETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GUITARBATTLEWINTOTAL = %GUITARBATTLEWINTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GUITARBATTLELOSETOTAL = %GUITARBATTLELOSETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAINBATTLETOTAL = %TRAINBATTLETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALLELEMENTALSPELLSUNLOCKED = %ALLELEMENTALSPELLSUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALLSUPPORTSPELLSUNLOCKED = %ALLSUPPORTSPELLSUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERDROWNCOUNT = %PLAYERDROWNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP1SPEND = %SHOP1SPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP2SPEND = %SHOP2SPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP3SPEND = %SHOP3SPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP4SPEND = %SHOP4SPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP5SPEND = %SHOP5SPEND% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM BATTLE RECORDS
ECHO SET /a BATTLETOTAL = %BATTLETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BATTLEWINTOTAL = %BATTLEWINTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BATTLELOSETOTAL = %BATTLELOSETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERATTACKCOUNT = %PLAYERATTACKCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERMISSCOUNT = %PLAYERMISSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CATCHSUCCESSCOUNT = %CATCHSUCCESSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a RUNSUCCESSCOUNT = %RUNSUCCESSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERUSEITEMCOUNT = %PLAYERUSEITEMCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a STEALSUCCESSCOUNT = %STEALSUCCESSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DODGESUCCESSCOUNT = %DODGESUCCESSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CRITICALHITSUCCESSCOUNT = %CRITICALHITSUCCESSCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GILSTOLENCOUNT = %GILSTOLENCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GILTHROWNCOUNT = %GILTHROWNCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRANSGILCOUNT = %TRANSGILCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a MPSTOLENCOUNT = %MPSTOLENCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FIRESPELLSCASTCOUNT = %FIRESPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ICESPELLSCASTCOUNT = %ICESPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ELECTRICSPELLSCASTCOUNT = %ELECTRICSPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a WATERSPELLSCASTCOUNT = %WATERSPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a EARTHSPELLSCASTCOUNT = %EARTHSPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FORBIDDENSPELLSCASTCOUNT = %FORBIDDENSPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CUSTOMSPELLSCASTCOUNT = %CUSTOMSPELLSCASTCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a WEAKNESSSPELLCOUNT = %WEAKNESSSPELLCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a STRENGTHSPELLCOUNT = %STRENGTHSPELLCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ELEMENTIMMUNESPELLCOUNT = %ELEMENTIMMUNESPELLCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ABSORBSPELLCOUNT = %ABSORBSPELLCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a STATUSIMMUNESPELLCOUNT = %STATUSIMMUNESPELLCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
::LIMIT BREAKS

ECHO SET LIMITBREAKBONUSSTAT=%LIMITBREAKBONUSSTAT%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a LIMITBREAKUSED = %LIMITBREAKUSED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
SET /a COUNT = 0
:LIMITBREAKLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a LIMITBREAK%COUNT%USED = !LIMITBREAK%COUNT%USED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %LIMITBREAKTOT% (
	GOTO :LIMITBREAKLOOP
)

REM SKILL RECORDS
SET /a COUNT = 0
:SKILLRECORDLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!SKILL%COUNT%NICKNAME!
ECHO SET /a PLAYERUSE%TEMP% = !PLAYERUSE%TEMP%! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILLRECORDLOOP
)

REM BOSS RECORDS
::SET /a COUNT = %BOSSIDSTART%
:::BOSSLOOP
::SET /a COUNT = %COUNT% + 1
::SET TEMP=!ENEMY%COUNT%NICKNAME!
::ECHO SET /a %TEMP%ALIVE = !%TEMP%ALIVE! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
::ECHO SET /a BEAT%TEMP% = !BEAT%TEMP%! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
::IF %COUNT% LSS %BOSSIDEND% (
::	GOTO :BOSSLOOP
::)

ECHO SET /a NIGHTMAREBOSSALIVE = %NIGHTMAREBOSSALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATNIGHTMAREBOSS = %BEATNIGHTMAREBOSS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAMPALIVE = %TRAMPALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat" 
ECHO SET /a BEATTRAMP = %BEATTRAMP% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPKEEPER1ALIVE = %SHOPKEEPER1ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSHOPKEEPER1 = %BEATSHOPKEEPER1% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPKEEPER2ALIVE = %SHOPKEEPER2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSHOPKEEPER2 = %BEATSHOPKEEPER2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPKEEPER3ALIVE = %SHOPKEEPER3ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSHOPKEEPER3 = %BEATSHOPKEEPER3% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPKEEPER4ALIVE = %SHOPKEEPER4ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSHOPKEEPER4 = %BEATSHOPKEEPER4% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPKEEPER5ALIVE = %SHOPKEEPER5ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSHOPKEEPER5 = %BEATSHOPKEEPER5% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a LEPRECHAUNALIVE = %LEPRECHAUNALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATLEPRECHAUN = %BEATLEPRECHAUN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BOUNCERALIVE = %BOUNCERALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATBOUNCER = %BEATBOUNCER% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOBOSSALIVE = %CASINOBOSSALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATCASINOBOSS = %BEATCASINOBOSS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CAVEBOSSALIVE = %CAVEBOSSALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATCAVEBOSS = %BEATCAVEBOSS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CAVEMON1ALIVE = %CAVEMON1ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATCAVEMON1 = %BEATCAVEMON1% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CAVEMON2ALIVE = %CAVEMON2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATCAVEMON2 = %BEATCAVEMON2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PACMANALIVE = %PACMANALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPACMAN = %BEATPACMAN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT1ALIVE = %KNIGHT1ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT1 = %BEATKNIGHT1% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT2ALIVE = %KNIGHT2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT2 = %BEATKNIGHT2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT3ALIVE = %KNIGHT3ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT3 = %BEATKNIGHT3% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT4ALIVE = %KNIGHT4ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT4 = %BEATKNIGHT4% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT5ALIVE = %KNIGHT5ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT5 = %BEATKNIGHT5% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT6ALIVE = %KNIGHT6ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT6 = %BEATKNIGHT6% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT7ALIVE = %KNIGHT7ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT7 = %BEATKNIGHT7% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT8ALIVE = %KNIGHT8ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT8 = %BEATKNIGHT8% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT9ALIVE = %KNIGHT9ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT9 = %BEATKNIGHT9% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT10ALIVE = %KNIGHT10ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT10 = %BEATKNIGHT10% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT11ALIVE = %KNIGHT11ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT11 = %BEATKNIGHT11% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT12ALIVE = %KNIGHT12ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT12 = %BEATKNIGHT12% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT13ALIVE = %KNIGHT13ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT13 = %BEATKNIGHT13% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT14ALIVE = %KNIGHT14ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT14 = %BEATKNIGHT14% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT15ALIVE = %KNIGHT15ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT15 = %BEATKNIGHT15% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT16ALIVE = %KNIGHT16ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT16 = %BEATKNIGHT16% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT17ALIVE = %KNIGHT17ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT17 = %BEATKNIGHT17% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT18ALIVE = %KNIGHT18ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT18 = %BEATKNIGHT18% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT19ALIVE = %KNIGHT19ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT19 = %BEATKNIGHT19% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT20ALIVE = %KNIGHT20ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT20 = %BEATKNIGHT20% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT21ALIVE = %KNIGHT21ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT21 = %BEATKNIGHT21% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT22ALIVE = %KNIGHT22ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT22 = %BEATKNIGHT22% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT23ALIVE = %KNIGHT23ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT23 = %BEATKNIGHT23% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT24ALIVE = %KNIGHT24ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT24 = %BEATKNIGHT24% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT25ALIVE = %KNIGHT25ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT25 = %BEATKNIGHT25% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT26ALIVE = %KNIGHT26ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT26 = %BEATKNIGHT26% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a KNIGHT27ALIVE = %KNIGHT27ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATKNIGHT27 = %BEATKNIGHT27% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a LEEROYALIVE = %LEEROYALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATLEEROY = %BEATLEEROY% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a MINEBOSSALIVE = %MINEBOSSALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATMINEBOSS = %BEATMINEBOSS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a MINEBOSS2ALIVE = %MINEBOSS2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATMINEBOSS2 = %BEATMINEBOSS2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GIMPLYALIVE = %GIMPLYALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATGIMPLY = %BEATGIMPLY% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD1ALIVE = %PALACEGUARD1ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD1 = %BEATPALACEGUARD1% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD2ALIVE = %PALACEGUARD2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD2 = %BEATPALACEGUARD2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD3ALIVE = %PALACEGUARD3ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD3 = %BEATPALACEGUARD3% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD4ALIVE = %PALACEGUARD4ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD4 = %BEATPALACEGUARD4% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD5ALIVE = %PALACEGUARD5ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD5 = %BEATPALACEGUARD5% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PALACEGUARD6ALIVE = %PALACEGUARD6ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATPALACEGUARD6 = %BEATPALACEGUARD6% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SEAKINGALIVE = %SEAKINGALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATSEAKING = %BEATSEAKING% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON1ALIVE = %ALCHEMISTMON1ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON1 = %BEATALCHEMISTMON1% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON2ALIVE = %ALCHEMISTMON2ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON2 = %BEATALCHEMISTMON2% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON3ALIVE = %ALCHEMISTMON3ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON3 = %BEATALCHEMISTMON3% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON4ALIVE = %ALCHEMISTMON4ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON4 = %BEATALCHEMISTMON4% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON5ALIVE = %ALCHEMISTMON5ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON5 = %BEATALCHEMISTMON5% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTMON6ALIVE = %ALCHEMISTMON6ALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATALCHEMISTMON6 = %BEATALCHEMISTMON6% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FORESTBOSSALIVE = %FORESTBOSSALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATFORESTBOSS = %BEATFORESTBOSS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BANDITALIVE = %BANDITALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATBANDIT = %BEATBANDIT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a RAGATAALIVE = %RAGATAALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATRAGATA = %BEATRAGATA% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a EMWEAPONALIVE = %EMWEAPONALIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATEMWEAPON = %BEATEMWEAPON% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BEATEMWEAPONCOUNT = %BEATEMWEAPONCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM CASINO RECORDS
ECHO SET /a ROULETTEPLAYEDTOTAL = %ROULETTEPLAYEDTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ROULETTEWINTOTAL = %ROULETTEWINTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ROULETTELOSETOTAL = %ROULETTELOSETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ROULETTEPROFIT = %ROULETTEPROFIT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKJACKPLAYEDTOTAL = %BLACKJACKPLAYEDTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKJACKWINTOTAL = %BLACKJACKWINTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKJACKLOSETOTAL = %BLACKJACKLOSETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKJACKPROFIT = %BLACKJACKPROFIT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SLOTMACHINEPLAYEDTOTAL = %SLOTMACHINEPLAYEDTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SLOTMACHINEWINTOTAL = %SLOTMACHINEWINTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SLOTMACHINELOSETOTAL = %SLOTMACHINELOSETOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SLOTMACHINEPROFIT = %SLOTMACHINEPROFIT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TOTALCASINOPROFIT = %TOTALCASINOPROFIT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM TEMPLE RECORDS
ECHO SET /a PLAYERTEMPLEDONATIONTOTAL = %PLAYERTEMPLEDONATIONTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERTEMPLEDONATIONREDUCTION = %PLAYERTEMPLEDONATIONREDUCTION% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERCUSTOMSPELLCREATIONCOUNT = %PLAYERCUSTOMSPELLCREATIONCOUNT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM QUEST RECORD
ECHO SET /a HOMETOWNQUESTPHASE = %HOMETOWNQUESTPHASE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAMPQUESTACTIVE = %TRAMPQUESTACTIVE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAMPDAY = %TRAMPDAY% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAMPSAVED = %TRAMPSAVED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOBOUGHT = %CASINOBOUGHT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BANDITQUESTCOMPLETE = %BANDITQUESTCOMPLETE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BANDITGILSTEAL = %BANDITGILSTEAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a NIGHTMAREMONEYACQUIRED = %NIGHTMAREMONEYACQUIRED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PORTALOPENED = %PORTALOPENED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM CAVESTATS
ECHO SET /a CAVEEXAMINED = %CAVEEXAMINED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CAVEENTER = %CAVEENTER% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CAVEITEMSACQUIRED = %CAVEITEMSACQUIRED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM MINESTATS
ECHO SET /a DWARFTOT = %DWARFTOT% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARFSLOTS = %DWARFSLOTS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYERHAULTOTAL = %PLAYERHAULTOTAL% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a STRTRAININGFACILITYUNLOCKED = %STRTRAININGFACILITYUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SKLTRAININGFACILITYUNLOCKED = %SKLTRAININGFACILITYUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PERTRAININGFACILITYUNLOCKED = %PERTRAININGFACILITYUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
SET /a COUNT = 0
:MINELOOP1
SET /a COUNT = %COUNT% + 1
ECHO SET /a MINEITEMTYPE%COUNT%UNLOCKED = !MINEITEMTYPE%COUNT%UNLOCKED! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS 9 (
	GOTO :MINELOOP1
)

SET /a COUNT = 0
:MINELOOP2
SET /a COUNT = %COUNT%+1
ECHO SET /a PLAYERPICKAXE%COUNT%NUM = !PLAYERPICKAXE%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %PICKAXETOT% (
	GOTO :MINELOOP2
)

SET /a COUNT = 0
:MINELOOP3
SET /a COUNT = %COUNT%+1
ECHO SET /a PLAYERSACK%COUNT%NUM = !PLAYERSACK%COUNT%NUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %SACKTOT% (
	GOTO :MINELOOP3
)

REM DWARFSTATS
SET /a COUNT = 0
IF %DWARFTOT% EQU 0 (
	GOTO :DWARFLOOP1END
)
:DWARFLOOP1
SET /a COUNT = %COUNT% + 1
ECHO SET DWARF%COUNT%NAME=!DWARF%COUNT%NAME!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%NAMELENGTH = !DWARF%COUNT%NAMELENGTH! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%LVL = !DWARF%COUNT%LVL! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%EXP = !DWARF%COUNT%EXP! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%BASESTR = !DWARF%COUNT%BASESTR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%BASESKL = !DWARF%COUNT%BASESKL! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%BASEPER = !DWARF%COUNT%BASEPER! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SAT = !DWARF%COUNT%SAT! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SALARY = !DWARF%COUNT%SALARY! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%PICKAXEID = !DWARF%COUNT%PICKAXEID! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SACKID = !DWARF%COUNT%SACKID! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%PICKAXESTR = !DWARF%COUNT%PICKAXESTR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%PICKAXESKL = !DWARF%COUNT%PICKAXESKL! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%PICKAXEPER = !DWARF%COUNT%PICKAXEPER! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SACKSTR = !DWARF%COUNT%SACKSTR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SACKSKL = !DWARF%COUNT%SACKSKL! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%SACKPER = !DWARF%COUNT%SACKPER! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%SPECIAL=!DWARF%COUNT%SPECIAL!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%SPECIALDISPLAY=!DWARF%COUNT%SPECIALDISPLAY!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%TYPE=!DWARF%COUNT%TYPE!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%TYPE2=!DWARF%COUNT%TYPE2!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%TYPEDISPLAY=!DWARF%COUNT%TYPEDISPLAY!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%MINID = !DWARF%COUNT%MINID! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%MAXID = !DWARF%COUNT%MAXID! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAINING = !DWARF%COUNT%TRAINING! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET DWARF%COUNT%TRAININGSTAT=!DWARF%COUNT%TRAININGSTAT!>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%YEAR = !DWARF%COUNT%YEAR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%MONTH = !DWARF%COUNT%MONTH! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%DAY = !DWARF%COUNT%DAY! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%HOUR = !DWARF%COUNT%HOUR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%MIN = !DWARF%COUNT%MIN! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAININGYEAR = !DWARF%COUNT%TRAININGYEAR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAININGMONTH = !DWARF%COUNT%TRAININGMONTH! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAININGDAY = !DWARF%COUNT%TRAININGDAY! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAININGHOUR = !DWARF%COUNT%TRAININGHOUR! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARF%COUNT%TRAININGMIN = !DWARF%COUNT%TRAININGMIN! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %DWARFTOT% (
	GOTO :DWARFLOOP1
)
:DWARFLOOP1END

REM LAKESTATS
ECHO SET /a LAKECAVEDISCOVERED = %LAKECAVEDISCOVERED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a PLAYEROXYGEN = %PLAYEROXYGEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM ALCHEMISTSTATS
ECHO SET /a ALCHEMYBATTLESEXPLAINED = %ALCHEMYBATTLESEXPLAINED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CUSTOMITEMSUNLOCKED = %CUSTOMITEMSUNLOCKED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM TELEPORTSTATS
SET /a COUNT = 0
:TELEPORTLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a TOWN%COUNT%TELEPORTACTIVE = !TOWN%COUNT%TELEPORTACTIVE! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %TOWNTOT% (
	GOTO :TELEPORTLOOP
)

REM CHESTS
::SET /a TEMPCOUNT = 0
:::CHESTLOOP1START
::SET /a TEMPCOUNT = %TEMPCOUNT% + 1
::SET TEMPMAP=!MAP%TEMPCOUNT%!
::IF !%TEMPMAP%CHESTTOT! EQU 0 (
::	GOTO :CHESTLOOPEND
::)
::SET /a COUNT = 0
:::CHESTLOOP2START
::SET /a COUNT = %COUNT% + 1
::ECHO SET /a %TEMPMAP%CHEST%COUNT%OPEN = !%TEMPMAP%CHEST%COUNT%OPEN! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
::IF %COUNT% LSS !%TEMPMAP%CHESTTOT! (
::	GOTO :CHESTLOOP2START
::)
:::CHESTLOOPEND
::IF %TEMPCOUNT% LSS %MAPTOT% (
::	GOTO :CHESTLOOP1START
::)

ECHO SET /a castle2CHEST1OPEN = %castle2CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST2OPEN = %castle2CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST3OPEN = %castle2CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST4OPEN = %castle2CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST5OPEN = %castle2CHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST6OPEN = %castle2CHEST6OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST7OPEN = %castle2CHEST7OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST8OPEN = %castle2CHEST8OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST9OPEN = %castle2CHEST9OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST10OPEN = %castle2CHEST10OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST11OPEN = %castle2CHEST11OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST12OPEN = %castle2CHEST12OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST13OPEN = %castle2CHEST13OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST14OPEN = %castle2CHEST14OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST15OPEN = %castle2CHEST15OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST16OPEN = %castle2CHEST16OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST17OPEN = %castle2CHEST17OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST18OPEN = %castle2CHEST18OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST19OPEN = %castle2CHEST19OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST20OPEN = %castle2CHEST20OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST21OPEN = %castle2CHEST21OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST22OPEN = %castle2CHEST22OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST23OPEN = %castle2CHEST23OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST24OPEN = %castle2CHEST24OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST25OPEN = %castle2CHEST25OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST26OPEN = %castle2CHEST26OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST27OPEN = %castle2CHEST27OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST28OPEN = %castle2CHEST28OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST29OPEN = %castle2CHEST29OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST30OPEN = %castle2CHEST30OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle2CHEST31OPEN = %castle2CHEST31OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle3CHEST1OPEN = %castle3CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle3CHEST2OPEN = %castle3CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle3CHEST3OPEN = %castle3CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle3CHEST4OPEN = %castle3CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castle3CHEST5OPEN = %castle3CHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST1OPEN = %castleCHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST2OPEN = %castleCHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST3OPEN = %castleCHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST4OPEN = %castleCHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST5OPEN = %castleCHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a castleCHEST6OPEN = %castleCHEST6OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1lvl2CHEST1OPEN = %cave1lvl2CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1lvl2CHEST2OPEN = %cave1lvl2CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1lvl2CHEST3OPEN = %cave1lvl2CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1lvl2CHEST4OPEN = %cave1lvl2CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1CHEST1OPEN = %cave1CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1CHEST2OPEN = %cave1CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a cave1CHEST3OPEN = %cave1CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake1CHEST1OPEN = %lake1CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake1CHEST2OPEN = %lake1CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake1CHEST3OPEN = %lake1CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake2CHEST1OPEN = %lake2CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake2CHEST2OPEN = %lake2CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake2CHEST3OPEN = %lake2CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake2CHEST4OPEN = %lake2CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake2CHEST5OPEN = %lake2CHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake3CHEST1OPEN = %lake3CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake3CHEST2OPEN = %lake3CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake3CHEST3OPEN = %lake3CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake3CHEST4OPEN = %lake3CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lake3CHEST5OPEN = %lake3CHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST1OPEN = %lakepalaceCHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST2OPEN = %lakepalaceCHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST3OPEN = %lakepalaceCHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST4OPEN = %lakepalaceCHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST5OPEN = %lakepalaceCHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a lakepalaceCHEST6OPEN = %lakepalaceCHEST6OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine1CHEST1OPEN = %mine1CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine1CHEST2OPEN = %mine1CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine1CHEST3OPEN = %mine1CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine1CHEST4OPEN = %mine1CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine2CHEST1OPEN = %mine2CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine2CHEST2OPEN = %mine2CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine2CHEST3OPEN = %mine2CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine2CHEST4OPEN = %mine2CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine3CHEST1OPEN = %mine3CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine3CHEST2OPEN = %mine3CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine3CHEST3OPEN = %mine3CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a mine3CHEST4OPEN = %mine3CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a town1CHEST1OPEN = %town1CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a town2CHEST1OPEN = %town2CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a town2CHEST2OPEN = %town2CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a town3CHEST1OPEN = %town3CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a town3CHEST2OPEN = %town3CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST1OPEN = %FOREST1MIST0CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST2OPEN = %FOREST1MIST0CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST3OPEN = %FOREST1MIST0CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST4OPEN = %FOREST1MIST0CHEST4OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST5OPEN = %FOREST1MIST0CHEST5OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST6OPEN = %FOREST1MIST0CHEST6OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FOREST1MIST0CHEST7OPEN = %FOREST1MIST0CHEST7OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a HELL1CHEST1OPEN = %HELL1CHEST1OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a HELL1CHEST2OPEN = %HELL1CHEST2OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a HELL1CHEST3OPEN = %HELL1CHEST3OPEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"


REM Remote access
ECHO SET /a REMOTEACCESSTRUE = %REMOTEACCESSTRUE% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAININGREMOTEACCESS = %TRAININGREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TUTORIALREMOTEACCESS = %TUTORIALREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TELEPORTREMOTEACCESS = %TELEPORTREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKSMITHREMOTEACCESS = %BLACKSMITHREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TEMPLEREMOTEACCESS = %TEMPLEREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TEMPLE2REMOTEACCESS = %TEMPLE2REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTREMOTEACCESS = %ALCHEMISTREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GURUREMOTEACCESS = %GURUREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a DWARFMINEREMOTEACCESS = %DWARFMINEREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOREMOTEACCESS = %CASINOREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOPREMOTEACCESS = %SHOPREMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP1REMOTEACCESS = %SHOP1REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP2REMOTEACCESS = %SHOP2REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP3REMOTEACCESS = %SHOP3REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP4REMOTEACCESS = %SHOP4REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a SHOP5REMOTEACCESS = %SHOP5REMOTEACCESS% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

::BLACKSMITH STATS
ECHO SET /a WEAPONSCRAFTED = %WEAPONSCRAFTED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ARMOURCRAFTED = %ARMOURCRAFTED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ACCESSORIESCRAFTED = %ACCESSORIESCRAFTED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a EQUIPMENTCRAFTED = %EQUIPMENTCRAFTED% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

::CHARACTER NAMES
ECHO SET GIRLNAME=%GIRLNAME%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET GIRLNAMECAP=%GIRLNAMECAP%>> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GIRLNAMELENGTH = %GIRLNAMELENGTH% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET GIRLHOUSEVAR1=%GIRLHOUSEVAR1%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET GIRLHOUSEVAR2=%GIRLHOUSEVAR2%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET GIRLHOUSEVAR3=%GIRLHOUSEVAR3%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET FRIENDNAME=%FRIENDNAME%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET FRIENDNAMECAP=%FRIENDNAMECAP%>> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a FRIENDNAMELENGTH = %FRIENDNAMELENGTH% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET FRIENDHOUSEVAR1=%FRIENDHOUSEVAR1%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET FRIENDHOUSEVAR2=%FRIENDHOUSEVAR2%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET FRIENDHOUSEVAR3=%FRIENDHOUSEVAR3%>>"%SAVERESOURCEPATH%\%SAVEFILE%.bat"

::STORY
SET /a COUNT = 0
:STORYLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET /a STORY%COUNT%VERSIONNUM = !STORY%COUNT%VERSIONNUM! >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
IF %COUNT% LSS %STORYTOT% (
	GOTO :STORYLOOP
)

::Tutorials Seen
ECHO SET /a MENUTUTORIALSEEN = %MENUTUTORIALSEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a MINETUTORIALSEEN = %MINETUTORIALSEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASTLECUTSCENESEEN = %CASTLECUTSCENESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

::Welcomes Seen
ECHO SET /a SHOPWELCOMESEEN = %SHOPWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TEMPLEWELCOMESEEN = %TEMPLEWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TUTORIALWELCOMESEEN = %TUTORIALWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a CASINOWELCOMESEEN = %CASINOWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a BLACKSMITHWELCOMESEEN = %BLACKSMITHWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a ALCHEMISTWELCOMESEEN = %ALCHEMISTWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a GURUWELCOMESEEN = %GURUWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"
ECHO SET /a TRAININGWELCOMESEEN = %TRAININGWELCOMESEEN% >> "%SAVERESOURCEPATH%\%SAVEFILE%.bat"

REM CUSTOM SPELLS
IF %QUICKSAVE% EQU 0 (
	RMDIR "%CUSTOMSPELLRESOURCEPATH%\Slot%SAVESLOTNUM%" /S /Q
	XCOPY "%CUSTOMSPELLRESOURCEPATH%\Temp" "%CUSTOMSPELLRESOURCEPATH%\Slot%SAVESLOTNUM%" /E /I
) ELSE (
	RMDIR "%CUSTOMSPELLRESOURCEPATH%\QS" /S /Q
	XCOPY "%CUSTOMSPELLRESOURCEPATH%\Temp" "%CUSTOMSPELLRESOURCEPATH%\QS" /E /I
)

REM CUSTOM ITEMS
IF %QUICKSAVE% EQU 0 (
	RMDIR "%CUSTOMITEMRESOURCEPATH%\Slot%SAVESLOTNUM%" /S /Q
	XCOPY "%CUSTOMITEMRESOURCEPATH%\Temp" "%CUSTOMITEMRESOURCEPATH%\Slot%SAVESLOTNUM%" /E /I
) ELSE (
	RMDIR "%CUSTOMITEMRESOURCEPATH%\QS" /S /Q
	XCOPY "%CUSTOMITEMRESOURCEPATH%\Temp" "%CUSTOMITEMRESOURCEPATH%\QS" /E /I
)

REM CUSTOM WEAPONS
IF %QUICKSAVE% EQU 0 (
	RMDIR "%CUSTOMWEAPONRESOURCEPATH%\Slot%SAVESLOTNUM%" /S /Q
	XCOPY "%CUSTOMWEAPONRESOURCEPATH%\Temp" "%CUSTOMWEAPONRESOURCEPATH%\Slot%SAVESLOTNUM%" /E /I
) ELSE (
	RMDIR "%CUSTOMWEAPONRESOURCEPATH%\QS" /S /Q
	XCOPY "%CUSTOMWEAPONRESOURCEPATH%\Temp" "%CUSTOMWEAPONRESOURCEPATH%\QS" /E /I
)

REM CUSTOM ARMOUR
IF %QUICKSAVE% EQU 0 (
	RMDIR "%CUSTOMARMOURRESOURCEPATH%\Slot%SAVESLOTNUM%" /S /Q
	XCOPY "%CUSTOMARMOURRESOURCEPATH%\Temp" "%CUSTOMARMOURRESOURCEPATH%\Slot%SAVESLOTNUM%" /E /I
) ELSE (
	RMDIR "%CUSTOMARMOURRESOURCEPATH%\QS" /S /Q
	XCOPY "%CUSTOMARMOURRESOURCEPATH%\Temp" "%CUSTOMARMOURRESOURCEPATH%\QS" /E /I
)

REM CUSTOM ACCESSORIES
IF %QUICKSAVE% EQU 0 (
	RMDIR "%CUSTOMACCESSORYRESOURCEPATH%\Slot%SAVESLOTNUM%" /S /Q
	XCOPY "%CUSTOMACCESSORYRESOURCEPATH%\Temp" "%CUSTOMACCESSORYRESOURCEPATH%\Slot%SAVESLOTNUM%" /E /I
) ELSE (
	RMDIR "%CUSTOMACCESSORYRESOURCEPATH%\QS" /S /Q
	XCOPY "%CUSTOMACCESSORYRESOURCEPATH%\Temp" "%CUSTOMACCESSORYRESOURCEPATH%\QS" /E /I
)
::pause
CLS
ECHO.
ECHO Game Saved Successfully^^!
ECHO.
GOTO :EOF
