:START
SET /a TEMP = %TOWNTOT% - 1
CLS
ECHO.
ECHO %MENUNAME%: Which town's shop would you like to access?
ECHO.
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
SET /a NICKNAMECOUNT = %COUNT% + 1
IF !SHOP%COUNT%REMOTEACCESS! EQU 1 (
	ECHO. %COUNT% - !TOWN%NICKNAMECOUNT%NICKNAME!
)
IF %NICKNAMECOUNT% LSS %TOWNTOT% (
	GOTO :LOOP
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P SHOPNUM=
ECHO.
IF "%SHOPNUM%" EQU "" (
	GOTO :CHOICE
) ELSE IF "%SHOPNUM%" EQU "0" (
	GOTO :EOF
)
IF %SHOPNUM% GTR %TEMP% (
	GOTO :CHOICE
) ELSE IF %SHOPNUM% LSS 0 (
	GOTO :CHOICE
) ELSE (
	IF !SHOP%SHOPNUM%REMOTEACCESS! EQU 1 (
		CALL "%SHOPRESOURCEPATH%\entershop.bat"
		GOTO :EOF
	) ELSE (
		GOTO :CHOICE
	)
)
GOTO :START
