CALL "%MENURESOURCEPATH%\menudisplay.bat"
ECHO %MENUNAME%: The Special Items you currently hold are...
ECHO.
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = 37 - !SPECIALITEM%COUNT%NAMELENGTH!
IF !PLAYERSPECIALITEM%COUNT%NUM! EQU 1 (
	ECHO. !PLAYERSPECIALITEM%COUNT%NUM! !SPECIALITEM%COUNT%NAME!!SPACES%SPACENUM%!  - !SPECIALITEM%COUNT%DESCRIPTION!
) ELSE IF !PLAYERSPECIALITEM%COUNT%NUM! GTR 9 (
	ECHO. !PLAYERSPECIALITEM%COUNT%NUM! !SPECIALITEM%COUNT%NAME!s!SPACES%SPACENUM%!- !SPECIALITEM%COUNT%DESCRIPTION!
) ELSE IF !PLAYERSPECIALITEM%COUNT%NUM! GTR 1 (
	ECHO. !PLAYERSPECIALITEM%COUNT%NUM! !SPECIALITEM%COUNT%NAME!s!SPACES%SPACENUM%! - !SPECIALITEM%COUNT%DESCRIPTION!
)
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :LOOPSTART
)
ECHO.
pause
GOTO :EOF