SET /a COUNT=0
SET /a STATICCOUNTITEM=%SKILLSTONESTART%
SET /a STATICCOUNTSKILL = 0
:LOOPSTART
SET /a STATICCOUNTITEM=%STATICCOUNTITEM%+1
SET /a STATICCOUNTSKILL=%STATICCOUNTSKILL%+1
IF !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM! GTR 0 (
	SET /a COUNT=%COUNT%+1
)
IF !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM! GTR 0 (
	SET DYNAMICSKILL%COUNT%NAME=!SKILL%STATICCOUNTSKILL%NAME!
	SET DYNAMICSKILL%COUNT%NICKNAME=!SKILL%STATICCOUNTSKILL%NICKNAME!
	SET DYNAMICSKILL%COUNT%DESCRIPTION=!SKILL%STATICCOUNTSKILL%DESCRIPTION!
	SET /a DYNAMICSKILL%COUNT%APCOST = !SKILL%STATICCOUNTSKILL%APCOST!
	SET /a DYNAMICSKILL%COUNT%GILCOST = !SKILL%STATICCOUNTSKILL%GILCOST!
	SET /a DYNAMICSKILL%COUNT%NAMELENGTH = !SKILL%STATICCOUNTSKILL%NAMELENGTH!
	SET DYNAMICSPECIALITEM%COUNT%NAME=!SPECIALITEM%STATICCOUNTITEM%NAME!
REM	SET /a DYNAMICSPECIALITEM%COUNT%NUM = !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM!
	SET DYNAMICSPECIALITEM%COUNT%NICKNAME=!SPECIALITEM%STATICCOUNTITEM%NICKNAME!
)
IF %STATICCOUNTITEM% LSS %SKILLSTONEEND% (
	GOTO :LOOPSTART
)
SET /a DYNAMICSPECIALITEMTOT = %COUNT%

GOTO :EOF
