SET /a COUNT=0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERSKILL%STATICCOUNT%ENABLED! EQU 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS %SKILLTOT% (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF


:SETVARS
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!SKILL%STATICCOUNT%NAME!
SET /a TEXT%COUNT%NAMELENGTH = !SKILL%STATICCOUNT%NAMELENGTH!
SET /a SPACENUM = 34-!TEXT%COUNT%NAMELENGTH!
SET TEXT%COUNT%NAME2=!SKILL%STATICCOUNT%APCOST!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 1
SET TEXT%COUNT%DESCRIPTION1=!SKILL%STATICCOUNT%DESCRIPTION!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!!SPACES%SPACENUM%!!TEXT%COUNT%NAME2! AP
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
GOTO :EOF