SET /a COUNT = 0
SET /a STATICCOUNT = 0
:LOOPSTART
SET /a STATICCOUNT = %STATICCOUNT% + 1
SET TEMP=!%TYPE%%STATICCOUNT%SPELL!
SET TEMP2=!%TYPE%%STATICCOUNT%PREREQUISITE!
IF !PLAYER%TEMP%ENABLED! EQU 0 (
	IF %PLAYERLVL% GEQ !%TYPE%%STATICCOUNT%UNLOCKLVL! (
		IF /I %TEMP2% EQU NONE (
			CALL :SETVARS
		) ELSE (
			IF !PLAYER%TEMP2%ENABLED! EQU 1 (
				CALL :SETVARS
			)
		)
	)
)
IF %STATICCOUNT% LSS !%TYPE%SPELLTOT! (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF




:SETVARS
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!%TYPE%%STATICCOUNT%SPELL!
SET /a TEXT%COUNT%NAMELENGTH = !%TYPE%%STATICCOUNT%NAMELENGTH!
SET /a SPACENUM = 34-!TEXT%COUNT%NAMELENGTH!
SET TEXT%COUNT%NAME2=!%TYPE%%STATICCOUNT%MPCOST!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 1
SET TEXT%COUNT%DESCRIPTION1=!%TYPE%%STATICCOUNT%DESCRIPTION!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!!SPACES%SPACENUM%!!TEXT%COUNT%NAME2! MP
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
GOTO :EOF