SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERITEM%STATICCOUNT%NUM! GEQ 1 (
	SET /a COUNT=%COUNT%+1
)
IF !PLAYERITEM%STATICCOUNT%NUM! GEQ 1 (
	SET /a DYNAMICITEM%COUNT%ID = %COUNT%
	SET DYNAMICITEM%COUNT%NAME=!ITEM%STATICCOUNT%NAME!
	SET /a DYNAMICITEM%COUNT%COST = !ITEM%STATICCOUNT%COST!
	SET /a DYNAMICITEM%COUNT%SELLPRICE = !ITEM%STATICCOUNT%COST!/4
	SET /a DYNAMICITEM%COUNT%NUM = !PLAYERITEM%STATICCOUNT%NUM!
	SET /a DYNAMICITEM%COUNT%NAMELENGTH = !ITEM%STATICCOUNT%NAMELENGTH!
)
IF %STATICCOUNT% LSS %ITEMTOTAL% (
	GOTO :LOOPSTART
)
SET /a DYNAMICITEMTOTAL = %COUNT%
GOTO :EOF