SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERACCESSORY%STATICCOUNT%NUM! GTR 0 (
	SET /a COUNT=%COUNT%+1
)
IF !PLAYERACCESSORY%STATICCOUNT%NUM! GTR 0 (
	SET /a DYNAMICACCESSORY%COUNT%ID = %STATICCOUNT%
	SET DYNAMICACCESSORY%COUNT%NAME=!ACCESSORY%STATICCOUNT%NAME!
	SET /a DYNAMICACCESSORY%COUNT%NUM = !PLAYERACCESSORY%STATICCOUNT%NUM!
	SET /a DYNAMICACCESSORY%COUNT%NAMELENGTH = !ACCESSORY%STATICCOUNT%NAMELENGTH!
	SET /a DYNAMICACCESSORY%DYNAMICCOUNT%CUSTOM = 0
)
IF %STATICCOUNT% LSS %ACCESSORYTOTAL% (
	GOTO :LOOPSTART
)
SET /a DYNAMICACCESSORYTOTAL = %COUNT%
GOTO :EOF
