SET /a COUNT = 0
SET /a STATICCOUNT = 0
:LOOP
SET /a STATICCOUNT = %STATICCOUNT% + 1
IF !PLAYERSPECIALITEM%STATICCOUNT%NUM! GEQ 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS %STATSTONEEND% (
	GOTO :LOOP
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF

:SETVARS
SET /a COUNT = %COUNT% + 1
SET DYNAMICSPECIALITEM%COUNT%NAME=!SPECIALITEM%STATICCOUNT%NAME!
SET /a DYNAMICSPECIALITEM%COUNT%NAMELENGTH = !SPECIALITEM%STATICCOUNT%NAMELENGTH!
SET /a DYNAMICSPECIALITEM%COUNT%NUM = !PLAYERSPECIALITEM%STATICCOUNT%NUM!
GOTO :EOF