SET /a COUNT = 0
SET /a STATICCOUNT = 0
:LOOPSTART
SET /a STATICCOUNT = %STATICCOUNT% + 1
CALL :SETVARS
IF %STATICCOUNT% LSS %OPTIONSMENUTOT% (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF

:SETVARS
SET /a COUNT=%COUNT%+1
SET TEMPVAR5=!OPTION%COUNT%VAR!
IF !%TEMPVAR5%! EQU 1 (
	SET TEXT%COUNT%NAME1=² !OPTION%STATICCOUNT%NAME!
) ELSE (
	SET TEXT%COUNT%NAME1=° !OPTION%STATICCOUNT%NAME!
)
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 2
SET TEXT%COUNT%DESCRIPTION1=%MENUNAME%: !OPTION%STATICCOUNT%DESCRIPTION1!
SET TEXT%COUNT%DESCRIPTION2=!SPACES%MENUNAMELENGTH%!  !OPTION%STATICCOUNT%DESCRIPTION2!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
::Add the description to this DISPLAYSUFF if required.
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
GOTO :EOF
