SET /a COUNT = 0
SET /a STATICCOUNT = 0
:LOOPSTART
SET /a STATICCOUNT = %STATICCOUNT%+1
SET /a ENEMYID = %STATICCOUNT%
IF !ENEMY%STATICCOUNT%CAUGHT! EQU 1 (
	SET /a COUNT=%COUNT%+1
	IF NOT DEFINED ENEMY%ENEMYID%LOADED (
		SET /a ENEMY%ENEMYID%LOADED = 1
		CALL "%MISCRESOURCEPATH%\loadenemy.bat"
	)
)
IF !ENEMY%STATICCOUNT%CAUGHT! EQU 1 (
	SET /a DYNAMICENEMY%COUNT%ID=%STATICCOUNT%
	SET DYNAMICENEMY%COUNT%NAME=!ENEMY%STATICCOUNT%NAME!
)
IF %STATICCOUNT% LSS %ENEMYTOT% (
	GOTO :LOOPSTART
)
SET /a DYNAMICENEMYTOT=%COUNT%
GOTO :EOF


