SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERITEM%STATICCOUNT%NUM! GEQ 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS %ITEMTOTAL% (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF

:SETVARS
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!ITEM%STATICCOUNT%NAME!
SET /a TEXT%COUNT%NAMELENGTH = !ITEM%STATICCOUNT%NAMELENGTH!
SET /a SPACENUM = 34-!TEXT%COUNT%NAMELENGTH!
SET TEXT%COUNT%NAME2=!PLAYERITEM%STATICCOUNT%NUM!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 1
SET TEXT%COUNT%DESCRIPTION1=!ITEM%STATICCOUNT%DESCRIPTION!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!!SPACES%SPACENUM%!!TEXT%COUNT%NAME2! Left
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
GOTO :EOF