SET /a COUNT=0
SET /a STATICCOUNTITEM=%SPECIALSTONESTART%
SET /a STATICCOUNTSPECIAL = 0
:LOOPSTART
SET /a STATICCOUNTITEM=%STATICCOUNTITEM%+1
SET /a STATICCOUNTSPECIAL=%STATICCOUNTSPECIAL%+1
IF !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM! GTR 0 (
	SET /a COUNT=%COUNT%+1
)
IF !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM! GTR 0 (
	SET DYNAMICSPECIAL%COUNT%NAME=!SPECIAL%STATICCOUNTSPECIAL%NAME!
	SET DYNAMICSPECIAL%COUNT%NICKNAME=!SPECIAL%STATICCOUNTSPECIAL%NICKNAME!
	SET DYNAMICSPECIAL%COUNT%DESCRIPTION=!SPECIAL%STATICCOUNTSPECIAL%DESCRIPTION!
	SET /a DYNAMICSPECIAL%COUNT%NAMELENGTH = !SPECIAL%STATICCOUNTSPECIAL%NAMELENGTH!
	SET /a DYNAMICSPECIAL%COUNT%GILCOST = !SPECIAL%STATICCOUNTSPECIAL%GILCOST!
	SET DYNAMICSPECIALITEM%COUNT%NAME=!SPECIALITEM%STATICCOUNTITEM%NAME!
	SET /a DYNAMICSPECIALITEM%COUNT%NUM = !PLAYERSPECIALITEM%STATICCOUNTITEM%NUM!
	SET DYNAMICSPECIALITEM%COUNT%NICKNAME=!SPECIALITEM%STATICCOUNTITEM%NICKNAME!
)
IF %STATICCOUNTITEM% LSS %SPECIALSTONEEND% (
	GOTO :LOOPSTART
)
SET /a DYNAMICSPECIALITEMTOT = %COUNT%

GOTO :EOF