SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!NEWDWARF%COUNT%NAME!
SET /a TEXT%COUNT%NAMELENGTH = !NEWDWARF%COUNT%NAMELENGTH!
SET /a SPACENUM = 34-!TEXT%COUNT%NAMELENGTH!
SET TEXT%COUNT%NAME2=Level !NEWDWARF%COUNT%LVL!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 5
SET TEXT%COUNT%DESCRIPTION1=Strength     !NEWDWARF%COUNT%BASESTR!
SET TEXT%COUNT%DESCRIPTION2=Skill        !NEWDWARF%COUNT%BASESKL!
SET TEXT%COUNT%DESCRIPTION3=Persistence  !NEWDWARF%COUNT%BASEPER!
SET TEXT%COUNT%DESCRIPTION4=Satisfaction !NEWDWARF%COUNT%SAT!
SET TEXT%COUNT%DESCRIPTION5=Speciality   !NEWDWARF%COUNT%SPECIALDISPLAY!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!!SPACES%SPACENUM%!!TEXT%COUNT%NAME2!
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
IF %COUNT% LSS 9 (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF