SET /a COUNT=0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERSKILL%STATICCOUNT%ENABLED! EQU 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS %SKILLTOT% (
	GOTO :LOOPSTART
)
SET /a DYNAMICSKILLTOT = %COUNT%
GOTO :EOF



:SETVARS
SET /a COUNT=%COUNT%+1
SET DYNAMICSKILL%COUNT%NAME=!SKILL%STATICCOUNT%NAME!
SET /a DYNAMICSKILL%COUNT%APCOST = !SKILL%STATICCOUNT%APCOST!
SET /a DYNAMICSKILL%COUNT%NAMELENGTH = !SKILL%STATICCOUNT%NAMELENGTH!
SET DYNAMICSKILL%COUNT%DESCRIPTION=!SKILL%STATICCOUNT%DESCRIPTION!
GOTO :EOF