SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERARMOUR%STATICCOUNT%NUM! GEQ 1 (
	SET /a COUNT=%COUNT%+1
)
IF !PLAYERARMOUR%STATICCOUNT%NUM! GEQ 1 (
	SET /a DYNAMICARMOUR%COUNT%ID = %COUNT%
	SET DYNAMICARMOUR%COUNT%NAME=!ARMOUR%STATICCOUNT%NAME!
REM	SET /a DYNAMICARMOUR%COUNT%END = !ARMOUR%STATICCOUNT%END!
REM	SET /a DYNAMICARMOUR%COUNT%SPR = !ARMOUR%STATICCOUNT%SPR!
REM	SET /a DYNAMICARMOUR%COUNT%EVA = !ARMOUR%STATICCOUNT%EVA!
REM	SET /a DYNAMICARMOUR%COUNT%SPD = !ARMOUR%STATICCOUNT%SPD!
REM	SET DYNAMICARMOUR%COUNT%WEAKNESS=!ARMOUR%STATICCOUNT%WEAKNESS!
REM	SET DYNAMICARMOUR%COUNT%STRENGTH=!ARMOUR%STATICCOUNT%STRENGTH!
REM	SET DYNAMICARMOUR%COUNT%ELEMENTIMMUNE=!ARMOUR%STATICCOUNT%ELEMENTIMMUNE!
REM	SET DYNAMICARMOUR%COUNT%ABSORB=!ARMOUR%STATICCOUNT%ABSORB!
REM	SET DYNAMICARMOUR%COUNT%STATUSIMMUNE1=!ARMOUR%STATICCOUNT%STATUSIMMUNE1!
REM	SET DYNAMICARMOUR%COUNT%STATUSIMMUNE2=!ARMOUR%STATICCOUNT%STATUSIMMUNE2!
REM	SET DYNAMICARMOUR%COUNT%STATUSIMMUNE3=!ARMOUR%STATICCOUNT%STATUSIMMUNE3!
REM	SET /a DYNAMICARMOUR%COUNT%COST = !ARMOUR%STATICCOUNT%COST!
	SET /a DYNAMICARMOUR%COUNT%NUM = !PLAYERARMOUR%STATICCOUNT%NUM!
	SET /a DYNAMICARMOUR%COUNT%NAMELENGTH = !ARMOUR%STATICCOUNT%NAMELENGTH!
)
IF %STATICCOUNT% LSS %ARMOURTOTAL% (
	GOTO :LOOPSTART
)
SET /a DYNAMICARMOURTOTAL = %COUNT%
GOTO :EOF