SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!%TYPE%%COUNT%NAME!
SET /a TEXT%COUNT%NAMELENGTH = !%TYPE%%COUNT%NAMELENGTH!
SET /a SPACENUM = 34-!TEXT%COUNT%NAMELENGTH!
SET TEXT%COUNT%NAME2=!%TYPE%%COUNT%COST!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 3
SET TEXT%COUNT%DESCRIPTION1=Strength     !%TYPE%%COUNT%STR!
SET TEXT%COUNT%DESCRIPTION2=Skill        !%TYPE%%COUNT%SKL!
SET TEXT%COUNT%DESCRIPTION3=Persistence  !%TYPE%%COUNT%PER!
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!!SPACES%SPACENUM%!!TEXT%COUNT%NAME2! Gil
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
IF %COUNT% LSS !%TYPE%TOT! (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF