SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !AVAILABLE%TYPE%%STATICCOUNT%! GTR 0 (
	SET /a COUNT=%COUNT%+1
) ELSE IF !DWARF%DWARFCHOICE%%TYPE%ID! EQU %STATICCOUNT% (
	SET /a COUNT = %COUNT% + 1
)
IF !AVAILABLE%TYPE%%STATICCOUNT%! GTR 0 (
	SET DYNAMIC%TYPE%%COUNT%NAME=!%TYPE%%STATICCOUNT%NAME!
	SET /a DYNAMIC%TYPE%%COUNT%NUM = !AVAILABLE%TYPE%%STATICCOUNT%!
	SET /a DYNAMIC%TYPE%%COUNT%NAMELENGTH = !%TYPE%%STATICCOUNT%NAMELENGTH!
) ELSE IF !DWARF%DWARFCHOICE%%TYPE%ID! EQU %STATICCOUNT% (
	SET DYNAMIC%TYPE%%COUNT%NAME=!%TYPE%%STATICCOUNT%NAME!
	SET /a DYNAMIC%TYPE%%COUNT%NUM = !AVAILABLE%TYPE%%STATICCOUNT%!
	SET /a DYNAMIC%TYPE%%COUNT%NAMELENGTH = !%TYPE%%STATICCOUNT%NAMELENGTH!
)
IF %STATICCOUNT% LSS !%TYPE%TOT! (
	GOTO :LOOPSTART
)
SET /a DYNAMIC%TYPE%TOT = %COUNT%
GOTO :EOF