SET /a COUNT = 0
SET /a STATICCOUNT=0
:LOOPSTART
SET /a STATICCOUNT=%STATICCOUNT%+1
IF !PLAYERITEM%STATICCOUNT%NUM! GEQ 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS %ITEMTOTAL% (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF

:SETVARS
SET /a COUNT=%COUNT%+1
SET DYNAMICITEM%COUNT%NAME=!ITEM%STATICCOUNT%NAME!
SET /a DYNAMICITEM%COUNT%NAMELENGTH = !ITEM%STATICCOUNT%NAMELENGTH!
SET DYNAMICITEM%COUNT%DESCRIPTION=!ITEM%STATICCOUNT%DESCRIPTION!
SET /a DYNAMICITEM%COUNT%NUM = !PLAYERITEM%STATICCOUNT%NUM!
GOTO :EOF