SET /a COUNT = 0
SET /a STATICCOUNT = 0
:LOOPSTART
SET /a STATICCOUNT = %STATICCOUNT% + 1
IF !LIMITBREAK%STATICCOUNT%USED! GTR 0 (
	CALL :SETVARS
) ELSE IF %STATICCOUNT% EQU 1 (
	CALL :SETVARS
)
IF %STATICCOUNT% LSS !LIMITBREAKTOT! (
	GOTO :LOOPSTART
)
SET /a OPTIONTOT = %COUNT%
GOTO :EOF

:SETVARS
SET /a COUNT=%COUNT%+1
SET TEXT%COUNT%NAME1=!LIMITBREAK%STATICCOUNT%NAME!
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = 1
SET TEXT%COUNT%DESCRIPTION1=!LIMITBREAK%STATICCOUNT%DESCRIPTION!
SET /a SKILLCOUNT = 0
:LOOP1
SET /a SKILLCOUNT = %SKILLCOUNT% + 1
SET /a TEMP = !LIMITBREAK%STATICCOUNT%SKILL%SKILLCOUNT%!
SET TEMP2=!SKILL%TEMP%NICKNAME!
IF !PLAYERSKILL%TEMP%ENABLED! GTR 0 (
	CALL :SETVAR
) ELSE IF !PLAYERUSE%TEMP2%! GTR 0 (
	CALL :SETVAR
)
IF %SKILLCOUNT% LSS !LIMITBREAK%STATICCOUNT%SKILLTOT! (
	GOTO :LOOP1
)
SET OPTION%COUNT%DISPLAYSELECTEDPRE=¯ 
SET OPTION%COUNT%DISPLAYINITIALPRE=  
::Add the description to this DISPLAYSUFF if required.
SET OPTION%COUNT%DISPLAYSUFF=!TEXT%COUNT%NAME1!
SET OPTION%COUNT%DISPLAY=!OPTION%COUNT%DISPLAYINITIALPRE!!OPTION%COUNT%DISPLAYSUFF!
GOTO :EOF

:SETVAR
SET /a TEXT%COUNT%DESCRIPTIONLINETOT = !TEXT%COUNT%DESCRIPTIONLINETOT! + 1
SET TEXT%COUNT%DESCRIPTION!TEXT%COUNT%DESCRIPTIONLINETOT!=!SKILL%TEMP%NAME!
GOTO :EOF
