IF %ANIMATIONENABLED% EQU 0 (
	GOTO :EOF
) ELSE IF %SCAN% EQU 1 (
	GOTO :EOF
) ELSE IF %DETECT% EQU 1 (
	GOTO :EOF
)
SET %ATTACKER%ANIMATION=%ANIMATION%
SET %DEFENDER%ANIMATION=STATIC
CALL :EXCEPTIONS
SET /a ANIMATIONCOUNT = 0
:LOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 0
:LOOP2
SET /a COUNT = %COUNT% + 1
IF /I %PLAYERANIMATION% EQU STATIC (
	IF /I %ENEMYANIMATION% EQU STATIC (
		SET ANIMATION%COUNT%=!%PLAYERANIMATION%PLAYER1-%COUNT%!!%ANIMATION%MID1-%COUNT%!!%ENEMYANIMATION%ENEMY1-%COUNT%!
	) ELSE (
		SET ANIMATION%COUNT%=!%PLAYERANIMATION%PLAYER1-%COUNT%!!%ANIMATION%MID%ANIMATIONCOUNT%-%COUNT%!!%ENEMYANIMATION%ENEMY%ANIMATIONCOUNT%-%COUNT%!
	)
) ELSE IF /I %ENEMYANIMATION% EQU STATIC (
	SET ANIMATION%COUNT%=!%PLAYERANIMATION%PLAYER%ANIMATIONCOUNT%-%COUNT%!!%ANIMATION%MID%ANIMATIONCOUNT%-%COUNT%!!%ENEMYANIMATION%ENEMY1-%COUNT%!
) ELSE (
	SET ANIMATION%COUNT%=!%PLAYERANIMATION%PLAYER%ANIMATIONCOUNT%-%COUNT%!!%ANIMATION%MID%ANIMATIONCOUNT%-%COUNT%!!%ENEMYANIMATION%ENEMY%ANIMATIONCOUNT%-%COUNT%!
)
IF %COUNT% LSS 21 (
	GOTO :LOOP2
)
CALL :EXCEPTIONS2
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
IF %ANIMATIONCOUNT% LSS 3 (
	TIMEOUT /T 0 > nul
	GOTO :LOOP1
)
TIMEOUT /T 0 > nul
CALL :RESET
GOTO :EOF

:RESET
SET PLAYERANIMATION=STATIC
SET ENEMYANIMATION=STATIC
SET /a COUNT = 0
:RESETLOOP
SET /a COUNT = %COUNT% + 1
SET ANIMATION%COUNT%=!STATICPLAYER1-%COUNT%!!STATICMID1-%COUNT%!!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :RESETLOOP
)
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
COLOR 0F
GOTO :EOF

:EXCEPTIONS
IF /I %ATTACKER% EQU ENEMY (
	IF /I %ANIMATION% EQU ENEMYEARTHSPELL (
		SET PLAYERANIMATION=ENEMYEARTHSPELL
	)
)
GOTO :EOF

:EXCEPTIONS2
IF %ANIMATION% EQU ENEMYFORBIDDEN1SPELL (
	CALL :COLOURCHANGE
) ELSE IF %ANIMATION% EQU ENEMYFORBIDDEN2SPELL (
	CALL :COLOURCHANGE
) ELSE IF %ANIMATION% EQU PLAYERFORBIDDEN1SPELL (
	CALL :COLOURCHANGE
) ELSE IF %ANIMATION% EQU PLAYERFORBIDDEN2SPELL (
	CALL :COLOURCHANGE
)
GOTO :EOF

:COLOURCHANGE
IF /I !%ATTACKER%SPELLNAME! EQU COMET (
	COLOR 6E
) ELSE IF /I !%ATTACKER%SPELLNAME! EQU METEOR (
	COLOR 4C
) ELSE IF /I !%ATTACKER%SPELLNAME! EQU SHADOWFLARE (
	COLOR 5D
) ELSE IF /I !%ATTACKER%SPELLNAME! EQU ULTIMA (
	COLOR 2A
)
GOTO :EOF

:COLOURCHANGE2
IF %ANIMATIONCOUNT% EQU 1 (
	COLOR %COLOUR%
) ELSE IF %ANIMATIONCOUNT% EQU 2 (
	COLOR 0F
) ELSE IF %ANIMATIONCOUNT% EQU 3 (
	COLOR %COLOUR%
)
GOTO :EOF