IF %ANIMATIONENABLED% EQU 0 (
	GOTO :EOF
)
SET ENEMYSPRITE=!ENEMY%ENEMYID%SPRITE!
CALL :SETANIMATIONSTATIC
CALL :SETANIMATIONATTACK
SET ELEMENT=FIRE
CALL :SETANIMATIONSPELL
SET ELEMENT=ELECTRICITY
CALL :SETANIMATIONSPELL
SET ELEMENT=WATER
CALL :SETANIMATIONSPELL
SET ELEMENT=ICE
CALL :SETANIMATIONSPELL
SET ELEMENT=EARTH
CALL :SETANIMATIONSPELL
SET ELEMENT=DRAIN
CALL :SETANIMATIONSPELL
SET ELEMENT=DEMI
CALL :SETANIMATIONSPELL
SET ELEMENT=FORBIDDEN1
CALL :SETANIMATIONSPELL
SET ELEMENT=FORBIDDEN2
CALL :SETANIMATIONSPELL
SET ELEMENT=STATUS
CALL :SETANIMATIONSPELL
::This shouldn't be necessary but it needs testing. When the player does a move, the enemy sprite is set to "STATIC". We shouldn't need a PLAYERSTEALENEMY animation.
::CALL :SETANIMATIONSTEAL
CALL :SETANIMATIONOFFITEM
CALL :SETANIMATIONSELFSPELL
CALL :SETANIMATIONSELFITEM
CALL :FORBIDDEN1EXCEPTION
CALL :INITIALSETUP
GOTO :EOF


:SETANIMATIONSTATIC
SET /a COUNT = 0
:SETANIMATIONSTATICLOOP2
SET /a COUNT = %COUNT% + 1
SET STATICENEMY1-%COUNT%=!STATIC%ENEMYSPRITE%ENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONSTATICLOOP2
)
GOTO :EOF

:SETANIMATIONSTEAL
SET /a COUNT = 0
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONSTEALLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
:SETANIMATIONSTEALLOOP2
SET /a COUNT = %COUNT% + 1
SET PLAYERSTEALENEMY%ANIMATIONCOUNT%-%COUNT%=!STATIC%ENEMYSPRITE%ENEMY%ANIMATIONCOUNT%-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONATTACKLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONATTACKLOOP1
)
GOTO :EOF

:SETANIMATIONATTACK
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONATTACKLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 0
:SETANIMATIONATTACKLOOP2
SET /a COUNT = %COUNT% + 1
SET ENEMYATTACKENEMY%ANIMATIONCOUNT%-%COUNT%=!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONATTACKLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONATTACKLOOP1
)
GOTO :EOF

:SETANIMATIONSPELL
IF !ENEMY%ENEMYID%%ELEMENT%SPELLANIMATION! EQU 0 (
	GOTO :EOF
)
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONOFFSPELLLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 0
:SETANIMATIONOFFSPELLLOOP2
SET /a COUNT = %COUNT% + 1
SET ENEMY%ELEMENT%SPELLENEMY%ANIMATIONCOUNT%-%COUNT%=!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONOFFSPELLLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONOFFSPELLLOOP1
)
GOTO :EOF

:SETANIMATIONOFFITEM
IF !ENEMY%ENEMYID%OFFITEMANIMATION! EQU 0 (
	GOTO :EOF
)
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONOFFITEMLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 0
:SETANIMATIONOFFITEMLOOP2
SET /a COUNT = %COUNT% + 1
SET ENEMYOFFITEMENEMY%ANIMATIONCOUNT%-%COUNT%=!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONOFFITEMLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONOFFITEMLOOP1
)
GOTO :EOF



:SETANIMATIONSELFSPELL
IF !ENEMY%ENEMYID%SELFSPELLANIMATION! EQU 0 (
	GOTO :EOF
)
SET ENEMYSELFSPELLENEMY1-1=               
SET ENEMYSELFSPELLENEMY1-2=               
SET ENEMYSELFSPELLENEMY1-3=               
SET ENEMYSELFSPELLENEMY1-4=               
SET ENEMYSELFSPELLENEMY1-5=               
SET ENEMYSELFSPELLENEMY2-1=               
SET ENEMYSELFSPELLENEMY2-2=   \³/         
SET ENEMYSELFSPELLENEMY2-3=  -   -        
SET ENEMYSELFSPELLENEMY2-4=   /³\         
SET ENEMYSELFSPELLENEMY2-5=               
SET ENEMYSELFSPELLENEMY3-1= \  ³  /       
SET ENEMYSELFSPELLENEMY3-2=               
SET ENEMYSELFSPELLENEMY3-3= -     -       
SET ENEMYSELFSPELLENEMY3-4=               
SET ENEMYSELFSPELLENEMY3-5= /  ³  \       
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONSELFSPELLLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 5
:SETANIMATIONSELFSPELLLOOP2
SET /a COUNT = %COUNT% + 1
SET ENEMYSELFSPELLENEMY%ANIMATIONCOUNT%-%COUNT%=!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONSELFSPELLLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONSELFSPELLLOOP1
)
GOTO :EOF

:SETANIMATIONSELFITEM
IF !ENEMY%ENEMYID%SELFITEMANIMATION! EQU 0 (
	GOTO :EOF
)
SET ENEMYSELFITEMENEMY1-1=               
SET ENEMYSELFITEMENEMY1-2=   ÚÄ¿         
SET ENEMYSELFITEMENEMY1-3=   ³³         
SET ENEMYSELFITEMENEMY1-4=   ÀÄÙ         
SET ENEMYSELFITEMENEMY1-5=               
SET ENEMYSELFITEMENEMY2-1=               
SET ENEMYSELFITEMENEMY2-2=   \³/         
SET ENEMYSELFITEMENEMY2-3=  -  -        
SET ENEMYSELFITEMENEMY2-4=   /³\         
SET ENEMYSELFITEMENEMY2-5=               
SET ENEMYSELFITEMENEMY3-1= \  ³  /       
SET ENEMYSELFITEMENEMY3-2=               
SET ENEMYSELFITEMENEMY3-3= -    -       
SET ENEMYSELFITEMENEMY3-4=               
SET ENEMYSELFITEMENEMY3-5= /  ³  \       
SET /a ANIMATIONCOUNT = 0
:SETANIMATIONSELFITEMLOOP1
SET /a ANIMATIONCOUNT = %ANIMATIONCOUNT% + 1
SET /a COUNT = 5
:SETANIMATIONSELFITEMLOOP2
SET /a COUNT = %COUNT% + 1
SET ENEMYSELFITEMENEMY%ANIMATIONCOUNT%-%COUNT%=!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :SETANIMATIONSELFITEMLOOP2
) ELSE IF %ANIMATIONCOUNT% LSS 3 (
	GOTO :SETANIMATIONSELFITEMLOOP1
)
GOTO :EOF

:FORBIDDEN1EXCEPTION
SET ENEMYFORBIDDEN1SPELLENEMY1-1=     __        
SET ENEMYFORBIDDEN1SPELLENEMY1-2=    / .\       
SET ENEMYFORBIDDEN1SPELLENEMY1-3=    \__/       
GOTO :EOF


:INITIALSETUP
SET PLAYERANIMATION=STATIC
SET ENEMYANIMATION=STATIC
SET /a COUNT = 0
:RESETLOOP
SET /a COUNT = %COUNT% + 1
SET ANIMATION%COUNT%=!STATICPLAYER1-%COUNT%!!STATICMID1-%COUNT%!!STATICENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :RESETLOOP
)
GOTO :EOF