IF %SCANACTIVE% EQU 1 (
	CALL :SCANDISPLAY
) ELSE IF %DETECTACTIVE% EQU 1 (
	CALL :DETECTDISPLAY
) ELSE IF %ANIMATIONENABLED% EQU 1 (
	CALL :STANDARDDISPLAYANIMATIONS
) ELSE (
	CALL :STANDARDDISPLAY
)
GOTO :EOF


:DETECTDISPLAY
CLS
ECHO.
ECHO. Round %BATTLEROUNDNUM%
ECHO. зддддддддддддддддддддддддддддддддддбдддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO. Ё %PLAYERNAMEVAR% Ё %ENEMYNAMEVAR% Ё                                                   Ё
ECHO. Ё                                  Ё                   Ё Item Rewards                                      Ё
ECHO. Ё %PLAYERHPVAR% %PLAYERCOL1VAR1% %PLAYERCOL2VAR1% Ё %ENEMYHPVAR% Ё %ITEMREWARD1% Ё
ECHO. Ё %PLAYERHPBAR% %PLAYERCOL1VAR2% %PLAYERCOL2VAR2% Ё %ENEMYHPBAR% Ё %ITEMREWARD2% Ё
ECHO. Ё              %PLAYERCOL1VAR3% %PLAYERCOL2VAR3% Ё                   Ё %ITEMREWARD3% Ё
ECHO. Ё %PLAYERMPVAR% %PLAYERCOL1VAR4% %PLAYERCOL2VAR4% Ё %ENEMYCOL1VAR1% Ё %ITEMREWARD4% Ё
ECHO. Ё %PLAYERMPBAR% %PLAYERCOL1VAR5% %PLAYERCOL2VAR5% Ё %ENEMYCOL1VAR2% Ё                                                   Ё
ECHO. Ё              %PLAYERCOL1VAR6% %PLAYERCOL2VAR6% Ё %ENEMYCOL1VAR3% Ё Equipment Rewards                                 Ё
ECHO. Ё %PLAYERAPVAR% %PLAYERCOL1VAR7% %PLAYERCOL2VAR7% Ё %ENEMYCOL1VAR4% Ё %EQUIPMENTREWARD1% Ё
ECHO. Ё %PLAYERAPBAR% %PLAYERCOL1VAR8% %PLAYERCOL2VAR8% Ё %ENEMYCOL1VAR5% Ё %EQUIPMENTREWARD2% Ё
ECHO. Ё              %PLAYERCOL1VAR9% %PLAYERCOL2VAR9% Ё %ENEMYCOL1VAR6% Ё %EQUIPMENTREWARD3% Ё
ECHO. Ё Limit Break  %PLAYERCOL1VAR10% %PLAYERCOL2VAR10% Ё %ENEMYCOL1VAR7% Ё %EQUIPMENTREWARD4% Ё
ECHO. Ё %PLAYERLIMITBREAKBAR% %PLAYERCOL1VAR11% %PLAYERCOL2VAR11% Ё %ENEMYCOL1VAR8% Ё                                                   Ё
ECHO. Ё              %PLAYERCOL1VAR12% %PLAYERCOL2VAR12% Ё %ENEMYCOL1VAR9% Ё Steal Rewards                                     Ё
ECHO. Ё              %PLAYERCOL1VAR13% %PLAYERCOL2VAR13% Ё %ENEMYCOL1VAR10% Ё %STEALREWARD1% Ё
ECHO. Ё              %PLAYERCOL1VAR14% %PLAYERCOL2VAR14% Ё %ENEMYCOL1VAR11% Ё %STEALREWARD2% Ё
ECHO. Ё              %PLAYERCOL1VAR15% %PLAYERCOL2VAR15% Ё %ENEMYCOL1VAR12% Ё %STEALREWARD3% Ё
ECHO. Ё              %PLAYERCOL1VAR16% %PLAYERCOL2VAR16% Ё %ENEMYCOL1VAR13% Ё %STEALREWARD4% Ё
ECHO. Ё                                  Ё                   Ё                                                   Ё
ECHO. юддддддддддддддддддддддддддддддддддадддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO. 
GOTO :EOF

:SCANDISPLAY
CLS
ECHO.
ECHO. Round %BATTLEROUNDNUM%
ECHO. зддддддддддддддддддддддддддддддддддбдддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO. Ё %PLAYERNAMEVAR% Ё %ENEMYNAMEVAR% Ё                                                   Ё
ECHO. Ё                                  Ё                   Ё                                                   Ё
ECHO. Ё %PLAYERHPVAR% %PLAYERCOL1VAR1% %PLAYERCOL2VAR1% Ё %ENEMYHPVAR% Ё Weakness  Resist    E.Immune  Absorb    S.Immune  Ё
ECHO. Ё %PLAYERHPBAR% %PLAYERCOL1VAR2% %PLAYERCOL2VAR2% Ё %ENEMYHPBAR% Ё                                                   Ё
ECHO. Ё              %PLAYERCOL1VAR3% %PLAYERCOL2VAR3% Ё                   Ё %WEAKNESS1VAR% %STRENGTH1VAR% %ELEMENTIMMUNE1VAR% %ABSORB1VAR% %STATUSIMMUNE1VAR% Ё
ECHO. Ё %PLAYERMPVAR% %PLAYERCOL1VAR4% %PLAYERCOL2VAR4% Ё %ENEMYCOL1VAR1% Ё %WEAKNESS2VAR% %STRENGTH2VAR% %ELEMENTIMMUNE2VAR% %ABSORB2VAR% %STATUSIMMUNE2VAR% Ё
ECHO. Ё %PLAYERMPBAR% %PLAYERCOL1VAR5% %PLAYERCOL2VAR5% Ё %ENEMYCOL1VAR2% Ё %WEAKNESS3VAR% %STRENGTH3VAR% %ELEMENTIMMUNE3VAR% %ABSORB3VAR% %STATUSIMMUNE3VAR% Ё
ECHO. Ё              %PLAYERCOL1VAR6% %PLAYERCOL2VAR6% Ё %ENEMYCOL1VAR3% Ё %WEAKNESS4VAR% %STRENGTH4VAR% %ELEMENTIMMUNE4VAR% %ABSORB4VAR% %STATUSIMMUNE4VAR% Ё
ECHO. Ё %PLAYERAPVAR% %PLAYERCOL1VAR7% %PLAYERCOL2VAR7% Ё %ENEMYCOL1VAR4% Ё %WEAKNESS5VAR% %STRENGTH5VAR% %ELEMENTIMMUNE5VAR% %ABSORB5VAR% %STATUSIMMUNE5VAR% Ё
ECHO. Ё %PLAYERAPBAR% %PLAYERCOL1VAR8% %PLAYERCOL2VAR8% Ё %ENEMYCOL1VAR5% Ё %WEAKNESS6VAR% %STRENGTH6VAR% %ELEMENTIMMUNE6VAR% %ABSORB6VAR% %STATUSIMMUNE6VAR% Ё
ECHO. Ё              %PLAYERCOL1VAR9% %PLAYERCOL2VAR9% Ё %ENEMYCOL1VAR6% Ё %WEAKNESS7VAR% %STRENGTH7VAR% %ELEMENTIMMUNE7VAR% %ABSORB7VAR% %STATUSIMMUNE7VAR% Ё
ECHO. Ё Limit Break  %PLAYERCOL1VAR10% %PLAYERCOL2VAR10% Ё %ENEMYCOL1VAR7% Ё                                                   Ё
ECHO. Ё %PLAYERLIMITBREAKBAR% %PLAYERCOL1VAR11% %PLAYERCOL2VAR11% Ё %ENEMYCOL1VAR8% Ё %EXPVARDISPLAY% %GILVARDISPLAY% Ё
ECHO. Ё              %PLAYERCOL1VAR12% %PLAYERCOL2VAR12% Ё %ENEMYCOL1VAR9% Ё                                                   Ё
ECHO. Ё              %PLAYERCOL1VAR13% %PLAYERCOL2VAR13% Ё %ENEMYCOL1VAR10% Ё %DESCRIPTION1VAR% Ё
ECHO. Ё              %PLAYERCOL1VAR14% %PLAYERCOL2VAR14% Ё %ENEMYCOL1VAR11% Ё %DESCRIPTION2VAR% Ё
ECHO. Ё              %PLAYERCOL1VAR15% %PLAYERCOL2VAR15% Ё %ENEMYCOL1VAR12% Ё %DESCRIPTION3VAR% Ё
ECHO. Ё              %PLAYERCOL1VAR16% %PLAYERCOL2VAR16% Ё %ENEMYCOL1VAR13% Ё %DESCRIPTION4VAR% Ё
ECHO. Ё                                  Ё                   Ё                                                   Ё
ECHO. юддддддддддддддддддддддддддддддддддадддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO. 
GOTO :EOF



:STANDARDDISPLAY
CLS
ECHO.
ECHO. Round %BATTLEROUNDNUM%
ECHO. зддддддддддддддддддддддддддддддддддбддддддддддддддддддд©
ECHO. Ё %PLAYERNAMEVAR% Ё %ENEMYNAMEVAR% Ё   
ECHO. Ё                                  Ё                   Ё
ECHO. Ё %PLAYERHPVAR% %PLAYERCOL1VAR1% %PLAYERCOL2VAR1% Ё %ENEMYHPVAR% Ё
ECHO. Ё %PLAYERHPBAR% %PLAYERCOL1VAR2% %PLAYERCOL2VAR2% Ё %ENEMYHPBAR% Ё
ECHO. Ё              %PLAYERCOL1VAR3% %PLAYERCOL2VAR3% Ё                   Ё
ECHO. Ё %PLAYERMPVAR% %PLAYERCOL1VAR4% %PLAYERCOL2VAR4% Ё %ENEMYCOL1VAR1% Ё
ECHO. Ё %PLAYERMPBAR% %PLAYERCOL1VAR5% %PLAYERCOL2VAR5% Ё %ENEMYCOL1VAR2% Ё
ECHO. Ё              %PLAYERCOL1VAR6% %PLAYERCOL2VAR6% Ё %ENEMYCOL1VAR3% Ё
ECHO. Ё %PLAYERAPVAR% %PLAYERCOL1VAR7% %PLAYERCOL2VAR7% Ё %ENEMYCOL1VAR4% Ё
ECHO. Ё %PLAYERAPBAR% %PLAYERCOL1VAR8% %PLAYERCOL2VAR8% Ё %ENEMYCOL1VAR5% Ё
ECHO. Ё              %PLAYERCOL1VAR9% %PLAYERCOL2VAR9% Ё %ENEMYCOL1VAR6% Ё
ECHO. Ё Limit Break  %PLAYERCOL1VAR10% %PLAYERCOL2VAR10% Ё %ENEMYCOL1VAR7% Ё
ECHO. Ё %PLAYERLIMITBREAKBAR% %PLAYERCOL1VAR11% %PLAYERCOL2VAR11% Ё %ENEMYCOL1VAR8% Ё
ECHO. Ё              %PLAYERCOL1VAR12% %PLAYERCOL2VAR12% Ё %ENEMYCOL1VAR9% Ё
ECHO. Ё              %PLAYERCOL1VAR13% %PLAYERCOL2VAR13% Ё %ENEMYCOL1VAR10% Ё
ECHO. Ё              %PLAYERCOL1VAR14% %PLAYERCOL2VAR14% Ё %ENEMYCOL1VAR11% Ё
ECHO. Ё              %PLAYERCOL1VAR15% %PLAYERCOL2VAR15% Ё %ENEMYCOL1VAR12% Ё
ECHO. Ё              %PLAYERCOL1VAR16% %PLAYERCOL2VAR16% Ё %ENEMYCOL1VAR13% Ё
ECHO. Ё                                  Ё                   Ё
ECHO. юддддддддддддддддддддддддддддддддддаддддддддддддддддддды
ECHO. 
GOTO :EOF

:STANDARDDISPLAYANIMATIONS
CLS
ECHO.
ECHO. Round %BATTLEROUNDNUM%
ECHO. зддддддддддддддддддддддддддддддддддбддддддддддддддддддд©%ANIMATION1%
ECHO. Ё %PLAYERNAMEVAR% Ё %ENEMYNAMEVAR% Ё%ANIMATION2%
ECHO. Ё                                  Ё                   Ё%ANIMATION3%
ECHO. Ё %PLAYERHPVAR% %PLAYERCOL1VAR1% %PLAYERCOL2VAR1% Ё %ENEMYHPVAR% Ё%ANIMATION4%
ECHO. Ё %PLAYERHPBAR% %PLAYERCOL1VAR2% %PLAYERCOL2VAR2% Ё %ENEMYHPBAR% Ё%ANIMATION5%
ECHO. Ё              %PLAYERCOL1VAR3% %PLAYERCOL2VAR3% Ё                   Ё%ANIMATION6%
ECHO. Ё %PLAYERMPVAR% %PLAYERCOL1VAR4% %PLAYERCOL2VAR4% Ё %ENEMYCOL1VAR1% Ё%ANIMATION7%
ECHO. Ё %PLAYERMPBAR% %PLAYERCOL1VAR5% %PLAYERCOL2VAR5% Ё %ENEMYCOL1VAR2% Ё%ANIMATION8%
ECHO. Ё              %PLAYERCOL1VAR6% %PLAYERCOL2VAR6% Ё %ENEMYCOL1VAR3% Ё%ANIMATION9%
ECHO. Ё %PLAYERAPVAR% %PLAYERCOL1VAR7% %PLAYERCOL2VAR7% Ё %ENEMYCOL1VAR4% Ё%ANIMATION10%
ECHO. Ё %PLAYERAPBAR% %PLAYERCOL1VAR8% %PLAYERCOL2VAR8% Ё %ENEMYCOL1VAR5% Ё%ANIMATION11%
ECHO. Ё              %PLAYERCOL1VAR9% %PLAYERCOL2VAR9% Ё %ENEMYCOL1VAR6% Ё%ANIMATION12%
ECHO. Ё Limit Break  %PLAYERCOL1VAR10% %PLAYERCOL2VAR10% Ё %ENEMYCOL1VAR7% Ё%ANIMATION13%
ECHO. Ё %PLAYERLIMITBREAKBAR% %PLAYERCOL1VAR11% %PLAYERCOL2VAR11% Ё %ENEMYCOL1VAR8% Ё%ANIMATION14%
ECHO. Ё              %PLAYERCOL1VAR12% %PLAYERCOL2VAR12% Ё %ENEMYCOL1VAR9% Ё%ANIMATION15%
ECHO. Ё              %PLAYERCOL1VAR13% %PLAYERCOL2VAR13% Ё %ENEMYCOL1VAR10% Ё%ANIMATION16%
ECHO. Ё              %PLAYERCOL1VAR14% %PLAYERCOL2VAR14% Ё %ENEMYCOL1VAR11% Ё%ANIMATION17%
ECHO. Ё              %PLAYERCOL1VAR15% %PLAYERCOL2VAR15% Ё %ENEMYCOL1VAR12% Ё%ANIMATION18%
ECHO. Ё              %PLAYERCOL1VAR16% %PLAYERCOL2VAR16% Ё %ENEMYCOL1VAR13% Ё%ANIMATION19%
ECHO. Ё                                  Ё                   Ё%ANIMATION20%
ECHO. юддддддддддддддддддддддддддддддддддаддддддддддддддддддды%ANIMATION21%
ECHO. 
GOTO :EOF
