IF %BATTLEROUNDNUM% EQU 0 (
	CALL :PLAYERNAMECALCULATIONS
	CALL :ENEMYNAMECALCULATIONS
REM 	CALL :PLAYEREXPCALCULATIONS
)
SET TARGET=PLAYER
SET STAT=HP
CALL :TARGETSTATCALCULATIONS
SET STAT=MP
CALL :TARGETSTATCALCULATIONS
SET STAT=AP
CALL :TARGETSTATCALCULATIONS
SET STAT=LIMITBREAK
CALL :TARGETSTATCALCULATIONS
SET TARGET=ENEMY
SET STAT=HP
CALL :TARGETSTATCALCULATIONS
SET TARGET=PLAYER
SET /a COLNUM = 1
CALL :COL%COLNUM%CALCULATIONS
SET /a COLNUM = 2
CALL :COL%COLNUM%CALCULATIONS
SET /a COLNUM = 1
SET TARGET=ENEMY
CALL :COL%COLNUM%CALCULATIONS
GOTO :EOF

:PLAYERNAMECALCULATIONS
SET /a SPACENUM = 32 - %PLAYERNAMELENGTH%
SET PLAYERNAMEVAR=%PLAYERNAME%!SPACES%SPACENUM%!
GOTO :EOF

:ENEMYNAMECALCULATIONS
SET /a SPACENUM = 17-%ENEMYNAMELENGTH%
SET ENEMYNAMEVAR=%ENEMYNAME%!SPACES%SPACENUM%!
GOTO :EOF

:PLAYEREXPCALCULATIONS
SET /a PLAYERMAXEXP = %REQEXP% - %OLDREQEXP%
SET /a PLAYEREXP = %EXP% - %OLDREQEXP%
SET TARGET=PLAYER
SET STAT=Exp
CALL :TARGETSTATCALCULATIONS
GOTO :EOF

:TARGETSTATCALCULATIONS
SET %TARGET%%STAT%DISPLAY=%STAT%:!%TARGET%%STAT%!/!%TARGET%MAX%STAT%!
SET /a LENGTH = 0
:TARGETSTATLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!%TARGET%%STAT%DISPLAY:~%LENGTH%!
IF DEFINED SUBSTR (
	GOTO :TARGETSTATLOOPSTART
)
IF %TARGET% EQU PLAYER (
	SET /a SPACENUM = 12 - %LENGTH%
) ELSE (
	SET /a SPACENUM = 17 - %LENGTH%
)
SET %TARGET%%STAT%VAR=!%TARGET%%STAT%DISPLAY!!SPACES%SPACENUM%!
SET /a BARNUM = (((!%TARGET%%STAT%!)*10)/!%TARGET%MAX%STAT%!)
IF %BARNUM% GTR 10 (
	SET /a BARNUM = 10
)
IF %BARNUM% EQU 0 (
	IF !%TARGET%%STAT%! NEQ 0 (
		SET /a BARNUM = 1
	)
)
IF %TARGET% EQU PLAYER (
	SET /a SPACENUM = 2
) ELSE (
	SET /a SPACENUM = 7
)
CALL :BARVAR%BARNUM%
GOTO :EOF

:BARVAR10
SET %TARGET%%STAT%BAR=€€€€€€€€€€!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR9
SET %TARGET%%STAT%BAR=€€€€€€€€€∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR8
SET %TARGET%%STAT%BAR=€€€€€€€€∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR7
SET %TARGET%%STAT%BAR=€€€€€€€∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR6
SET %TARGET%%STAT%BAR=€€€€€€∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR5
SET %TARGET%%STAT%BAR=€€€€€∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR4
SET %TARGET%%STAT%BAR=€€€€∞∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR3
SET %TARGET%%STAT%BAR=€€€∞∞∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR2
SET %TARGET%%STAT%BAR=€€∞∞∞∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR1
SET %TARGET%%STAT%BAR=€∞∞∞∞∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:BARVAR0
SET %TARGET%%STAT%BAR=∞∞∞∞∞∞∞∞∞∞!SPACES%SPACENUM%!
GOTO :EOF

:COL1CALCULATIONS
CALL :INITIALISECOLUMN
SET /a COUNT = 0
SET COL%COLNUM%=Blind
SET COL%COLNUM%DISPLAY=Blind
CALL :COLASSIGN
SET COL%COLNUM%=Silence
SET COL%COLNUM%DISPLAY=Silence
CALL :COLASSIGN
SET COL%COLNUM%=Poison
SET COL%COLNUM%DISPLAY=Poison
CALL :COLASSIGN
SET COL%COLNUM%=Slow
SET COL%COLNUM%DISPLAY=Slow
CALL :COLASSIGN
SET COL%COLNUM%=Sleep
SET COL%COLNUM%DISPLAY=Sleep
CALL :COLASSIGN
SET COL%COLNUM%=Confusion
SET COL%COLNUM%DISPLAY=Confusion
CALL :COLASSIGN
SET COL%COLNUM%=Stop
SET COL%COLNUM%DISPLAY=Stop
CALL :COLASSIGN
SET COL%COLNUM%=Haste
SET COL%COLNUM%DISPLAY=Haste
CALL :COLASSIGN
SET COL%COLNUM%=Protect
SET COL%COLNUM%DISPLAY=Protect
CALL :COLASSIGN
SET COL%COLNUM%=Shell
SET COL%COLNUM%DISPLAY=Shell
CALL :COLASSIGN
SET COL%COLNUM%=Reflect
SET COL%COLNUM%DISPLAY=Reflect
CALL :COLASSIGN
SET COL%COLNUM%=Regen
SET COL%COLNUM%DISPLAY=Regen
CALL :COLASSIGN
SET COL%COLNUM%=MED
SET COL%COLNUM%DISPLAY=Meditate
CALL :COLASSIGN
SET COL%COLNUM%=FOC
SET COL%COLNUM%DISPLAY=Focus
CALL :COLASSIGN
SET COL%COLNUM%=AIM
SET COL%COLNUM%DISPLAY=Aim
CALL :COLASSIGN
SET COL%COLNUM%=HIDE
SET COL%COLNUM%DISPLAY=Hide
CALL :COLASSIGN
GOTO :EOF

:COL2CALCULATIONS
CALL :INITIALISECOLUMN
SET /a COUNT = 0
SET COL%COLNUM%=AUTOLIFE
SET COL%COLNUM%DISPLAY=Auto-Life
CALL :COLASSIGN
SET COL%COLNUM%=HALFMP
SET COL%COLNUM%DISPLAY=Half MP
CALL :COLASSIGN
SET COL%COLNUM%=ZEROMP
SET COL%COLNUM%DISPLAY=Zero MP
CALL :COLASSIGN
SET COL%COLNUM%=HALFAP
SET COL%COLNUM%DISPLAY=Half AP
CALL :COLASSIGN
SET COL%COLNUM%=ZEROAP
SET COL%COLNUM%DISPLAY=Zero AP
CALL :COLASSIGN
SET COL%COLNUM%=INCCRITCHANCE
SET COL%COLNUM%DISPLAY=Inc Crit
CALL :COLASSIGN
SET COL%COLNUM%=BREAKDAM
SET COL%COLNUM%DISPLAY=Break Lim
CALL :COLASSIGN
SET COL%COLNUM%=FASTAP
SET COL%COLNUM%DISPLAY=AP Gain
CALL :COLASSIGN
GOTO :EOF



:INITIALISECOLUMN
IF %TARGET% EQU PLAYER (
	SET /a SPACENUM = 9
	IF %COLNUM% EQU 1 (
		SET /a COL%COLNUM%TOTAL = 16
	) 
	IF %COLNUM% EQU 2 (
		SET /a COL%COLNUM%TOTAL = 16
	) 
) ELSE (
	SET /a SPACENUM = 17
	SET /a COL%COLNUM%TOTAL = 13
)
SET /a COUNT = 0
:INITIALISECOLLOOP
SET /a COUNT = %COUNT% + 1
SET %TARGET%COL%COLNUM%VAR%COUNT%=!SPACES%SPACENUM%!
IF %COUNT% LSS !COL%COLNUM%TOTAL! (
	GOTO :INITIALISECOLLOOP
)
GOTO :EOF

:COLASSIGN
SET TEMP=!COL%COLNUM%!
SET TEMP2=!COL%COLNUM%DISPLAY!
IF !%TARGET%%TEMP%! EQU 1 (
	SET /a COUNT = %COUNT%+1
) ELSE (
	GOTO :EOF
)
SET /a LENGTH = 0
:COLLENGTHLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!TEMP2:~%LENGTH%!
IF DEFINED SUBSTR (
	GOTO :COLLENGTHLOOPSTART
)
IF %TARGET% EQU PLAYER (
	SET /a SPACENUM = 9 - %LENGTH%
) ELSE (
	SET /a SPACENUM = 17 - %LENGTH%
)
IF %SPACENUM% EQU 0 (
	SET %TARGET%COL%COLNUM%VAR%COUNT%=!COL%COLNUM%DISPLAY!
) ELSE (
	SET %TARGET%COL%COLNUM%VAR%COUNT%=!COL%COLNUM%DISPLAY!!SPACES%SPACENUM%!
)
GOTO :EOF

