SET /a MAXSPACENUM = 9
SET TYPE=WEAKNESS
CALL :SETRESISTANCES
SET TYPE=STRENGTH
CALL :SETRESISTANCES
SET TYPE=ELEMENTIMMUNE
CALL :SETRESISTANCES
SET TYPE=ABSORB
CALL :SETRESISTANCES
SET TYPE=STATUSIMMUNE
CALL :SETRESISTANCES
CALL :CALCULATEEXP
CALL :CALCULATEGIL
SET /a MAXSPACENUM = 49
CALL :CALCULATEDESCRIPTIONS
GOTO :EOF





:SETRESISTANCES
CALL :INITIALISERESISTANCES
IF !ENEMY%TYPE%NUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESISTANCESLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP=!ENEMY%TYPE%%COUNT%!
IF /I %TEMP% EQU ELECTRICITY (
	SET TEMP=Electric
)
SET /a LENGTH = 0
:LENGTHLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!TEMP:~%LENGTH%!
IF DEFINED SUBSTR (
	GOTO :LENGTHLOOPSTART
)
SET /a SPACENUM = 9 - %LENGTH%
IF %SPACENUM% EQU 0 (
	SET %TYPE%%COUNT%VAR=%TEMP%
) ELSE (
	SET %TYPE%%COUNT%VAR=%TEMP%!SPACES%SPACENUM%!
)
IF %COUNT% LSS !ENEMY%TYPE%NUM! (
	GOTO :RESISTANCESLOOP
)
GOTO :EOF



:INITIALISERESISTANCES
SET /a COUNT = 0
:INITIALISERESISTANCESLOOP
SET /a COUNT = %COUNT% + 1
SET %TYPE%%COUNT%VAR=!SPACES%MAXSPACENUM%!
IF %COUNT% LSS 7 (
	GOTO :INITIALISERESISTANCESLOOP
)
GOTO :EOF


:CALCULATEEXP
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a GAINEDEXPTEMP = (%ENEMYEXP%/%PLAYERLVL%) + %PLAYERLCK%
SET /a GAINEDEXP = (%GAINEDEXPTEMP%*%RANFACT%)/100
SET EXPVAR=Exp:%GAINEDEXP%
SET /a LENGTH = 0
:EXPLENGTHLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!EXPVAR:~%LENGTH%!
IF DEFINED SUBSTR (
	GOTO :EXPLENGTHLOOPSTART
)
SET /a SPACENUM = 24 - %LENGTH%
SET EXPVARDISPLAY=%EXPVAR%!SPACES%SPACENUM%!
GOTO :EOF

:CALCULATEGIL
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
IF %GURUBATTLE% EQU 0 (
	SET /a ENEMYGIL = !ENEMY%ENEMYID%GIL! + %PLAYERLCK%
) ELSE (
	SET /a ENEMYGIL = !ENEMY%ENEMYID%GIL!
)
SET /a GAINEDGIL = (%ENEMYGIL%*%RANFACT%)/100
IF %TRAINBATTLE% EQU 1 (
	SET /a GAINEDGIL = 0
)
SET GILVAR=Gil:%GAINEDGIL%
SET /a LENGTH = 0
:GILLENGTHLOOPSTART
SET /a LENGTH += 1
SET SUBSTR=!GILVAR:~%LENGTH%!
IF DEFINED SUBSTR (
	GOTO :GILLENGTHLOOPSTART
)
SET /a SPACENUM = 24 - %LENGTH%
SET GILVARDISPLAY=%GILVAR%!SPACES%SPACENUM%!
GOTO :EOF

:CALCULATEDESCRIPTIONS
SET /a COUNT = 0
:DESCRIPTIONLOOP
SET /a COUNT = %COUNT% + 1
IF DEFINED ENEMY%ENEMYID%DESCRIPTION%COUNT% (
	CALL :SETDESCRIPTION
) ELSE (
	SET DESCRIPTION%COUNT%VAR=!SPACES%MAXSPACENUM%!
)
IF %COUNT% LSS 4 (
	GOTO :DESCRIPTIONLOOP
)
GOTO :EOF

:SETDESCRIPTION
SET /a SPACENUM = %MAXSPACENUM% - !ENEMY%ENEMYID%DESCRIPTION%COUNT%LENGTH!
IF %SPACENUM% EQU 0 (
	SET DESCRIPTION%COUNT%VAR=!ENEMY%ENEMYID%DESCRIPTION%COUNT%!
) ELSE (
	SET DESCRIPTION%COUNT%VAR=!ENEMY%ENEMYID%DESCRIPTION%COUNT%!!SPACES%SPACENUM%!
)
GOTO :EOF


