SET /a MAXSPACENUM = 49
CALL :INITIALISE
SET TYPE1=REWARD
SET TYPE2=ITEM
SET TYPE3=ITEM
CALL :SETREWARDSLENGTH
SET TYPE1=REWARD
SET TYPE2=ITEM
SET TYPE3=SPECIALITEM
CALL :SETREWARDSLENGTH
SET TYPE1=EQUIPMENT
SET TYPE2=EQUIPMENT
SET TYPE3=WEAPON
CALL :SETREWARDSLENGTH
SET TYPE1=EQUIPMENT
SET TYPE2=EQUIPMENT
SET TYPE3=ARMOUR
CALL :SETREWARDSLENGTH
SET TYPE1=EQUIPMENT
SET TYPE2=EQUIPMENT
SET TYPE3=ACCESSORY
CALL :SETREWARDSLENGTH
CALL :SETSTEALS
GOTO :EOF


:INITIALISE
SET ITEMREWARD1=!SPACES%MAXSPACENUM%!
SET ITEMREWARD2=!SPACES%MAXSPACENUM%!
SET ITEMREWARD3=!SPACES%MAXSPACENUM%!
SET ITEMREWARD4=!SPACES%MAXSPACENUM%!
SET EQUIPMENTREWARD1=!SPACES%MAXSPACENUM%!
SET EQUIPMENTREWARD2=!SPACES%MAXSPACENUM%!
SET EQUIPMENTREWARD3=!SPACES%MAXSPACENUM%!
::SET EQUIPMENTREWARD4=!SPACES%MAXSPACENUM%!
CALL :MORPH
SET STEALREWARD1=!SPACES%MAXSPACENUM%!
SET STEALREWARD2=!SPACES%MAXSPACENUM%!
SET STEALREWARD3=!SPACES%MAXSPACENUM%!
SET STEALREWARD4=!SPACES%MAXSPACENUM%!
GOTO :EOF

:MORPH
SET TYPE3=!ENEMY%ENEMYID%SET%REWARDSET%MORPHTYPE!
SET /a TEMP = !ENEMY%ENEMYID%SET%REWARDSET%MORPHID!
SET /a SPACENUM = %MAXSPACENUM% - !%TYPE3%%TEMP%NAMELENGTH%! - 7
SET EQUIPMENTREWARD4=Morph: !%TYPE3%%TEMP%NAME!!SPACES%SPACENUM%!
GOTO :EOF

:SETREWARDSLENGTH
IF !ENEMY%ENEMYID%SET%REWARDSET%%TYPE3%NUM! EQU 0 (
	GOTO :EOF
)
SET /a %TYPE2%REWARDCOUNT = 0
SET /a %TYPE3%COUNT = 0
:REWARDLOOP
SET /a %TYPE3%COUNT = !%TYPE3%COUNT! + 1
SET /a TEMP1 = !%TYPE3%COUNT!
IF DEFINED ENEMY%ENEMYID%SET%REWARDSET%%TYPE3%%TEMP1% (
	CALL :REWARDSET
)
IF !%TYPE3%COUNT! LSS !ENEMY%ENEMYID%SET%REWARDSET%%TYPE3%NUM! (
	GOTO :REWARDLOOP
)
GOTO :EOF




:REWARDSET
SET /a %TYPE2%REWARDCOUNT = !%TYPE2%REWARDCOUNT! + 1!
SET /a TEMP = !ENEMY%ENEMYID%SET%REWARDSET%%TYPE3%%TEMP1%!
SET /a SPACENUM = %MAXSPACENUM% - !%TYPE3%%TEMP%NAMELENGTH%!
SET %TYPE2%REWARD!%TYPE2%REWARDCOUNT!=!%TYPE3%%TEMP%NAME!!SPACES%SPACENUM%!
GOTO :EOF

:SETSTEALS
IF !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:STEALLOOP
SET /a COUNT = %COUNT% + 1
SET TYPE=!ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT%TYPE!
SET /a TEMP = !ENEMY%ENEMYID%SET%REWARDSET%STEAL%COUNT%!
SET /a SPACENUM = %MAXSPACENUM% - !%TYPE%%TEMP%NAMELENGTH!
SET STEALREWARD%COUNT%=!%TYPE%%TEMP%NAME!!SPACES%SPACENUM%!
IF %COUNT% LSS !ENEMY%ENEMYID%SET%REWARDSET%STEALNUM! (
	GOTO :STEALLOOP
)
GOTO :EOF




	
	
	
	
	
	
	
	
	
	