SET /a STORY30VERSIONNUM = 1
CALL "%HELLRESOURCEPATH%\prebattlecutscene.bat"
:BATTLE
SET /a ENEMYID = %RAGATAID%
CALL "%BATTLESTARTRESOURCEPATH%\specialbattlestart.bat"
IF %BEATRAGATA% EQU 1 (
	SET /a STORY30VERSIONNUM = 2
	SET /a EXITMAP = 1
	CALL "%HELLRESOURCEPATH%\postbattlecutscene.bat"
	CALL "%MISCRESOURCEPATH%\credits.bat"
) ELSE (
	SET /a PLAYERXCOORD = %PLAYEROLDXCOORD%
	SET /a PLAYERYCOORD = %PLAYEROLDYCOORD%
)
GOTO :EOF