IF %AUTOBATTLE% EQU 1 (
	SET WAITTIME=ZERO
) ELSE (
	SET WAITTIME=ONE
)
:ATTEMPTRUN
CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a RUNCHANCE = (%PLAYERSPD%*50)/(%ENEMYSPD%)
IF %RANPERC% LEQ %RUNCHANCE% (	
CALL :RUNSUCCESS
) ELSE (
CALL :RUNFAIL
)
GOTO :EOF

:RUNSUCCESS
ECHO Attempting to escape...
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO....
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO....
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO Got Away Safely...
ECHO.
IF %SPECIALFIGHT% EQU 1 (
	CALL "%BATTLEENDRESOURCEPATH%\specialfightrun.bat"
)
IF %TRAINBATTLE% EQU 1 (
	ECHO.
	ECHO The %ENEMYNAME% escaped as you ran away
	ECHO.
	SET /a ENEMY%ENEMYID%CAUGHT=0
)
SET /a SPECIALFIGHT = 0
pause
SET /a BATTLERUN = 1
SET /a RUNSUCCESSCOUNT = %RUNSUCCESSCOUNT% + 1
GOTO :EOF

:RUNFAIL
ECHO Attempting to escape...
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO....
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO....
ECHO.
CALL :WAITFOR%WAITTIME%
ECHO The %ENEMYNAME% tripped you up!
GOTO :EOF








:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF