:ENEMYTURN
REM CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
SET ATTACKER=ENEMY
SET DEFENDER=PLAYER
IF %ENEMYSTOP% EQU 1 (
	ECHO %ENEMYNAME% is stopped and cannot act
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %ENEMYSLEEP% EQU 1 (
	ECHO %ENEMYNAME% is asleep and cannot act
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %ENEMYSILENCE% EQU 1 (
	IF %ENEMYACTION% EQU 2 (
		SET /a ENEMYACTION = 1
	)
)
IF %ENEMYACTION% EQU 1 (
	CALL "%BATTLEACTIONRESOURCEPATH%\attack.bat"
) ELSE IF %ENEMYACTION% EQU 2 (
	CALL "%BATTLEACTIONRESOURCEPATH%\castspell.bat"
) ELSE IF %ENEMYACTION% EQU 3 (
	CALL "%BATTLEACTIONRESOURCEPATH%\enemyuseskill.bat"
) ELSE IF %ENEMYACTION% EQU 4 (
	CALL "%BATTLEACTIONRESOURCEPATH%\useitem.bat"
)
GOTO :EOF



:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF



