CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
ECHO %ENEMYNAME% used %ENEMYSKILLNAME%
ECHO.
TIMEOUT /T 1 > nul
SET ANIMATION=%ATTACKER%!ENEMYSKILL%ENEMYSKILLCHOICE%ANIMATION!
CALL "%BATTLEDISPLAYRESOURCEPATH%\animation.bat"
CALL "%ENEMYSKILLRESOURCEPATH%\!ENEMYSKILL%ENEMYSKILLCHOICE%NICKNAME!.bat"