:PLAYERTURN
REM CALL "%BATTLEDISPLAYRESOURCEPATH%\battledisplay.bat"
SET ATTACKER=PLAYER
SET DEFENDER=ENEMY
IF %PLAYERSTOP% EQU 1 (
	ECHO You are stopped and cannot act
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %PLAYERSLEEP% EQU 1 (
	ECHO You are asleep and cannot act
	ECHO.
	CALL :WAITFORTWO
	GOTO :EOF
)
IF %PLAYERACTION% EQU 1 (
	IF %BANDITQUESTCOMPLETE% EQU 0 (
		CALL "%BATTLEACTIONRESOURCEPATH%\attack.bat"
	) ELSE (
		CALL "%BATTLEACTIONRESOURCEPATH%\mug.bat"
	)
) ELSE IF %PLAYERACTION% EQU 2 (
	IF %PLAYERSILENCE% EQU 0 (
		CALL "%BATTLEACTIONRESOURCEPATH%\castspell.bat"
	) ELSE (
		ECHO You can't use magic when you're silenced
		ECHO.
		CALL :WAITFORTWO
	)
) ELSE IF %PLAYERACTION% EQU 3 (
	CALL "%BATTLEACTIONRESOURCEPATH%\useskill.bat"
) ELSE IF %PLAYERACTION% EQU 4 (
	CALL "%BATTLEACTIONRESOURCEPATH%\useitem.bat"
) ELSE IF %PLAYERACTION% EQU 5 (
	CALL "%BATTLEACTIONRESOURCEPATH%\attemptcatch.bat"
) ELSE IF %PLAYERACTION% EQU 6 (
	CALL "%BATTLEACTIONRESOURCEPATH%\attemptrun.bat"
) ELSE IF %PLAYERACTION% EQU 9 (
	CALL "%BATTLEACTIONRESOURCEPATH%\limitbreak.bat"
) ELSE (
	GOTO :PLAYERTURN
)
GOTO :EOF






:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF



