@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET /a REMOTEACCESS = 1
SET MUSICPATH=C:\Game\Music
SET /a SFXENABLED = 1
SET RESOURCEPATH=C:\Game\Resources
SET GURURESOURCEPATH=%RESOURCEPATH%\Guru
SET INITIALRESOURCEPATH=%RESOURCEPATH%\Setup\Initial
SET NEWRESOURCEPATH=%RESOURCEPATH%\Setup\New
SET DYNAMICRESOURCEPATH=%RESOURCEPATH%\Dynamic
SET MISCRESOURCEPATH=%RESOURCEPATH%\Misc
SET LASTBOSSNAME=Ragata


SET /a PLAYERLVL = 40
SET /a PLAYERGIL = 10000

CALL "%INITIALRESOURCEPATH%\mapnicknames.bat"
CALL "%INITIALRESOURCEPATH%\settabsvars.bat"
CALL "%INITIALRESOURCEPATH%\displayletters.bat"
CALL "%INITIALRESOURCEPATH%\enemytotals.bat"
CALL "%INITIALRESOURCEPATH%\gurufightlist.bat"
CALL "%INITIALRESOURCEPATH%\spellstats.bat"
CALL "%INITIALRESOURCEPATH%\specials.bat"
CALL "%INITIALRESOURCEPATH%\limitbreaksetup.bat"
CALL "%INITIALRESOURCEPATH%\skilllist.bat"
CALL "%INITIALRESOURCEPATH%\itemlist.bat"
CALL "%INITIALRESOURCEPATH%\specialitemlist.bat"
CALL "%INITIALRESOURCEPATH%\weaponstats.bat"
CALL "%INITIALRESOURCEPATH%\armourstats.bat"
CALL "%INITIALRESOURCEPATH%\accessorystats.bat"
CALL "%INITIALRESOURCEPATH%\enemyskilllist.bat"
CALL "%NEWRESOURCEPATH%\playerinitialskills.bat"
SET /a COUNT = 0
:WEAPONLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERWEAPON%COUNT%NUM = 1
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :WEAPONLOOPSTART
)
SET /a COUNT = 0
:ARMOURLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERARMOUR%COUNT%NUM = 1
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :ARMOURLOOPSTART
)
SET /a COUNT = 0
:ACCESSORYLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERACCESSORY%COUNT%NUM = 1
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :ACCESSORYLOOPSTART
)
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERSPECIALITEM%COUNT%NUM = 10
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :LOOPSTART
)
:LOOPEND
CALL "%GURURESOURCEPATH%\enterguru.bat"
GOTO :EOF
