@ECHO OFF
FOR /f "delims=" %%A in ('wmic os get localdatetime ^| find "."') do set "DUMMYDATE=%%A"
SET YEARDUMMY=%DUMMYDATE:~0,4%
SET /a %PREFIX%YEAR = %YEARDUMMY%
IF %DUMMYDATE:~4,1% EQU 0 (
	SET MONTHDUMMY=%DUMMYDATE:~5,1%
) ELSE (
	SET MONTHDUMMY=%DUMMYDATE:~4,2%
)
SET /a %PREFIX%MONTH = %MONTHDUMMY%
IF %DUMMYDATE:~6,1% EQU 0 (
	SET DAYDUMMY=%DUMMYDATE:~7,1%
) ELSE (
	SET DAYDUMMY=%DUMMYDATE:~6,2%
)
SET /a %PREFIX%DAY = %DAYDUMMY%
IF "%DUMMYDATE:~8,1%" EQU "" (
	SET HOURDUMMY=%DUMMYDATE:~9,1%
) ELSE (
	SET HOURDUMMY=%DUMMYDATE:~8,2%
)
SET /a %PREFIX%HOUR = %HOURDUMMY%
IF %DUMMYDATE:~10,1% EQU 0 (
	SET MINDUMMY=%DUMMYDATE:~11,1%
) ELSE (
	SET MINDUMMY=%DUMMYDATE:~10,2%
)
SET /a %PREFIX%MIN = %MINDUMMY%