SET /a YEARDIFF = !%AFTER%YEAR! - !%BEFORE%YEAR!
SET /a MONTHDIFF = !%AFTER%MONTH! - !%BEFORE%MONTH!
SET /a DAYDIFF = !%AFTER%DAY! - !%BEFORE%DAY!
SET /a HOURDIFF = !%AFTER%HOUR! - !%BEFORE%HOUR!
SET /a MINDIFF = !%AFTER%MIN! - !%BEFORE%MIN!
SET /a MINTIME = 0
IF %DAYDIFF% NEQ 0 (
	SET /a MINTIME = %MINTIME% + 1440
)
SET /a MINTIME = %MINTIME% + (%HOURDIFF%*60)
SET /a MINTIME = %MINTIME% + %MINDIFF%
SET /a HOURTIME = %MINTIME%/60
SET /a MINTIME = %MINTIME% - (%HOURTIME%*60)