@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
COLOR 0F
TITLE Loading
CALL :STORY
SET /a HINTNUM = (%RANDOM% %% %HINTTOT%) + 1
:START
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
CALL :DISPLAY
IF %COUNT% LSS 8 (
	GOTO :LOOP
) ELSE (
	GOTO :START
)

:STORY
SET /a STORYNUM = %STORYTOT% + 1
:LOOP1
SET /a STORYNUM = %STORYNUM% - 1
SET /a STORYVERSION = !STORY%STORYNUM%VERSIONNUM!
IF %STORYVERSION% NEQ 0 (
	SET /a STORYLINES = !STORY%STORYNUM%VERSION%STORYVERSION%LINETOT!
	GOTO :EOF
)
GOTO :LOOP1

:DISPLAY
CLS
ECHO.
CALL :DISPLAYHINT!HINT%HINTNUM%LINENUM!
ECHO.
CALL :DISPLAYSTORY%STORYLINES%
ECHO.
ECHO %LOADINGTEXT%
ECHO.
CALL :DISPLAY%COUNT%
ECHO.
TIMEOUT /T 0 > nul
GOTO :EOF

:DISPLAYHINT1
ECHO !HINT%HINTNUM%LINE1!
GOTO :EOF

:DISPLAYHINT2
ECHO !HINT%HINTNUM%LINE1!
ECHO !HINT%HINTNUM%LINE2!
GOTO :EOF

:DISPLAYHINT3
ECHO !HINT%HINTNUM%LINE1!
ECHO !HINT%HINTNUM%LINE2!
ECHO !HINT%HINTNUM%LINE3!
GOTO :EOF

:DISPLAYSTORY1
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
GOTO :EOF

:DISPLAYSTORY2
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE2!
GOTO :EOF

:DISPLAYSTORY3
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE2!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE3!
GOTO :EOF

:DISPLAYSTORY4
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE2!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE3!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE4!
GOTO :EOF

:DISPLAYSTORY5
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE2!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE3!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE4!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE5!
GOTO :EOF

:DISPLAYSTORY6
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE1!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE2!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE3!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE4!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE5!
ECHO !STORY%STORYNUM%VERSION%STORYVERSION%LINE6!
GOTO :EOF

:DISPLAY1
ECHO.  ²±°
ECHO.  Û
ECHO.  
GOTO :EOF

:DISPLAY2
ECHO.  ±°
ECHO.  ²
ECHO.  Û
GOTO :EOF

:DISPLAY3
ECHO.  °
ECHO.  ±
ECHO.  ²Û
GOTO :EOF

:DISPLAY4
ECHO.  
ECHO.  °
ECHO.  ±²Û
GOTO :EOF

:DISPLAY5
ECHO.  
ECHO.    Û
ECHO.  °±²
GOTO :EOF

:DISPLAY6
ECHO.    Û
ECHO.    ²
ECHO.   °±
GOTO :EOF

:DISPLAY7
ECHO.   Û²
ECHO.    ±
ECHO.    °
GOTO :EOF

:DISPLAY8
ECHO.  Û²±
ECHO.    °
ECHO.    
GOTO :EOF