@ECHO OFF
SET /a LOADINGBARMAX = 60
SET /a LOADINGTIME = 3
SET LOADINGTEXT=Loading
:START
SET /a UNIT = %LOADINGBARMAX%/%LOADINGTIME%
SET /a COUNT = 1
SET BARFULL=Û
SET BAREMPTY=°
:LOOP1
SET /a COUNT = %COUNT% + 1
SET BARFULL=%BARFULL%Û
SET BAREMPTY=%BAREMPTY%°
IF %COUNT% LSS %UNIT% (
	GOTO :LOOP1
)
SET /a COUNT = 0
:LOOP2
SET /a COUNT = %COUNT% + 1
SET BARVAR=
SET /a VARCOUNT = 0
:LOOP3
SET /a VARCOUNT = %VARCOUNT% + 1
SET BARVAR=%BARVAR%%BARFULL%
IF %VARCOUNT% LSS %COUNT% (
	GOTO :LOOP3
)
IF %COUNT% EQU %LOADINGTIME% (
	GOTO :LOOP4END
)
:LOOP4
SET /a VARCOUNT = %VARCOUNT% + 1
SET BARVAR=%BARVAR%%BAREMPTY%
IF %VARCOUNT% LSS %LOADINGTIME% (
	GOTO :LOOP4
)
:LOOP4END
CALL :DISPLAY
IF %COUNT% LSS %LOADINGTIME% (
	GOTO :LOOP2
) ELSE (
	GOTO :EOF
)

:DISPLAY
CLS
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO %LOADINGTEXT%...
ECHO.
ECHO %BARVAR%
ping -n 1 -w 1000 1.1.1.1 >nul
GOTO :EOF