@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
CALL "C:\Game\Resources\Setup\Initial\settabsvars.bat"
CALL "C:\Game\Resources\Setup\Initial\initialanimationsetup.bat"
SET SPRITE=SMALLDOG2
SET SPRITE=SMALLCREATURE
SET SPRITE=SMALLDOG
CLS
ECHO.
ECHO зд©
ECHO ЁЁ
ECHO юды
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
ECHO. !STATIC%SPRITE%ENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :LOOP
)
pause


SET SPRITE=SMALLDOG2
SET SPRITE=SMALLDOG
SET SPRITE=SMALLCREATURE
ECHO.
SET /a COUNT = 0
:LOOP
SET /a COUNT = %COUNT% + 1
ECHO. !STATIC%SPRITE%ENEMY1-%COUNT%!
IF %COUNT% LSS 21 (
	GOTO :LOOP
)
pause