SET /a ENEMYSTR = %ENEMYBASESTR%
SET /a ENEMYEND = %ENEMYBASEEND%
SET /a ENEMYMAG = %ENEMYBASEMAG%
SET /a ENEMYSPR = %ENEMYBASESPR%
SET /a ENEMYACC = %ENEMYBASEACC%
SET /a ENEMYEVA = %ENEMYBASEEVA%
SET /a ENEMYSPD = %ENEMYBASESPD%
SET /a ENEMYLCK = %ENEMYBASELCK%
SET /a ENEMYINT = %ENEMYBASEINT%
SET TARGET=ENEMY
SET TARGETER=PLAYER
CALL "%BATTLESTATUSRESOURCEPATH%\statusquery.bat"
CALL "%BATTLESTATUSRESOURCEPATH%\buffquery.bat"
IF %ENEMYITEMNUM% GTR 0 (
	CALL :ITEMQUERY
)
GOTO :EOF

:ITEMQUERY
SET /a ENEMYHASITEMS = 0
SET /a COUNT = 0
:ITEMLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP = !ENEMYITEM%COUNT%!
IF !ENEMYITEM%TEMP%NUM! GTR 0 (
	SET /a ENEMYHASITEMS = 1
	GOTO :END
) ELSE IF %COUNT% LSS %ENEMYITEMNUM% (
	GOTO :ITEMLOOP
)
:END
IF %ENEMYHASITEMS% EQU 0 (
	SET /a ENEMYITEMCHANCE = 0
)
GOTO :EOF