:FIRSTACTION
IF %PLAYERSPD% GEQ %ENEMYSPD% (
	CALL :SPDGTRESPD
) ELSE IF %ENEMYSPD% GTR %PLAYERSPD% (
	CALL :ESPDGTRSPD
)
GOTO :EOF

:SPDGTRESPD
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a DIFFSPD = %PLAYERSPD% - %ENEMYSPD%
SET /a FIRSTGO = ((%DIFFSPD%*50)/(%ENEMYSPD%))+50
IF %RANPERC% LEQ %FIRSTGO% (
SET /a ACTFIRST=1
) ELSE (
SET /a ACTFIRST=0
)
GOTO :EOF


:ESPDGTRSPD
CALL "%BATTLERESOURCEPATH%\ranresources.bat"
SET /a DIFFSPD = %ENEMYSPD% - %PLAYERSPD%
SET /a FIRSTGO = ((%DIFFSPD%*50)/(%PLAYERSPD%))+50
IF %RANPERC% LEQ %FIRSTGO% (
SET /a ACTFIRST=0
) ELSE (
SET /a ACTFIRST=1
)
GOTO :EOF







:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
