SET /a PLAYERMAXHP = %PLAYERBASEMAXHP% + %PLAYEREQUIPMAXHP%
SET /a PLAYERMAXMP = %PLAYERBASEMAXMP% + %PLAYEREQUIPMAXMP%
SET /a PLAYERSTR = %PLAYERBASESTR% + %PLAYEREQUIPSTR%
SET /a PLAYEREND = %PLAYERBASEEND% + %PLAYEREQUIPEND%
SET /a PLAYERMAG = %PLAYERBASEMAG% + %PLAYEREQUIPMAG%
SET /a PLAYERSPR = %PLAYERBASESPR% + %PLAYEREQUIPSPR%
SET /a PLAYERACC = %PLAYERBASEACC% + %PLAYEREQUIPACC%
SET /a PLAYEREVA = %PLAYERBASEEVA% + %PLAYEREQUIPEVA%
SET /a PLAYERSPD = %PLAYERBASESPD% + %PLAYEREQUIPSPD%
SET /a PLAYERLCK = %PLAYERBASELCK% + %PLAYEREQUIPLCK%
SET TARGET=PLAYER
SET TARGETER=ENEMY
CALL "%BATTLESTATUSRESOURCEPATH%\statusquery.bat"
CALL "%BATTLESTATUSRESOURCEPATH%\buffquery.bat"
CALL :LIMITBREAKBONUS
GOTO :EOF

:LIMITBREAKBONUS
SET /a TEMP = %PLAYERLIMITBREAK%*100/%PLAYERMAXLIMITBREAK%
SET /a BONUS = !PLAYERBASE%LIMITBREAKBONUSSTAT%!*%TEMP%/200
SET /a PLAYER%LIMITBREAKBONUSSTAT% = !PLAYER%LIMITBREAKBONUSSTAT%! + %BONUS%
GOTO :EOF