SET MAP=lake1
SET /a PLAYERXCOORD = 1
SET /a PLAYERYCOORD = 7
IF %LAKECAVEDISCOVERED% EQU 0 (
	SET %MAP%LOCATION!%MAP%EXIT2YCOORD!-!%MAP%EXIT2XCOORD!=
) ELSE IF %LAKECAVEDISCOVERED% EQU 1 (
	SET /a STORY21VERSIONNUM = 1
	SET %MAP%LOCATION!%MAP%EXIT2YCOORD!-!%MAP%EXIT2XCOORD!=EXIT
)
SET /a EXITMAP = 1