CLS
ECHO.
ECHO You have found a secret^^!
ECHO.
pause
SET /a ENEMYID = %EMWEAPONID%
SET /a VAR = 5*%BEATEMWEAPONCOUNT%
SET /a VAR2 = 500*%BEATEMWEAPONCOUNT%
SET /a ENEMY%ENEMYID%MAXHP = 9999 + %VAR2%
SET /a ENEMY%ENEMYID%HP = 9999 + %VAR2%
SET /a ENEMY%ENEMYID%MAXMP = 50000
SET /a ENEMY%ENEMYID%MP = 50000
SET /a ENEMY%ENEMYID%LVL = 90 + %VAR%
SET /a ENEMY%ENEMYID%STR = 90 + %VAR%
SET /a ENEMY%ENEMYID%END = 90 + %VAR%
SET /a ENEMY%ENEMYID%MAG = 90 + %VAR%
SET /a ENEMY%ENEMYID%SPR = 90 + %VAR%
SET /a ENEMY%ENEMYID%ACC = 90 + %VAR%
SET /a ENEMY%ENEMYID%EVA = 90 + %VAR%
SET /a ENEMY%ENEMYID%SPD = 90 + %VAR%
SET /a ENEMY%ENEMYID%LCK = 90 + %VAR%
CALL "%BATTLESTARTRESOURCEPATH%\specialbattlestart.bat"