CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a DAM = (%DAM%*3)/2
SET TARGET=PLAYER
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %MISS% EQU 1 (
	GOTO :EOF
)
SET TARGET=ENEMY
SET /a RANFACT = %RANDOM% %% 100
IF %RANFACT% LSS 25 (
	CALL :REDUCESPD
) ELSE IF %RANFACT% LSS 50 (
	CALL :REDUCEEVA
)
TIMEOUT /T 2 > nul
GOTO :EOF

:REDUCESPD
SET /a %TARGET%BASESPD = (!%TARGET%BASESPD!*4)/5
ECHO !%TARGET%NAME!'s Speed has been reduced by 20 percent
ECHO.
GOTO :EOF

:REDUCEEVA
SET /a %TARGET%BASEEVA = (!%TARGET%BASEEVA!*4)/5
ECHO !%TARGET%NAME!'s Evasion has been reduced by 20 percent
ECHO.
GOTO :EOF