::Damage
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET TARGET=PLAYER
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %MISS% EQU 1 (
	GOTO :EOF
)
::Status
SET /a HITCHANCE = !%ATTACKER%ACC!*30/!%DEFENDER%EVA!
SET STATUS=Slow
SET /a TURNCOUNT = ((!%ATTACKER%LVL!/3)*!%ATTACKER%MAG!)/((!%DEFENDER%LVL!/3)*(!%DEFENDER%SPR!*2))
CALL "%ENEMYSKILLRESOURCEPATH%\status.bat"