SET /a ENEMYHASTE = 1
SET /a ENEMYHASTETURNCOUNT = 3
SET /a ENEMYPROTECT = 1
SET /a ENEMYPROTECTTURNCOUNT = 3
SET /a ENEMYSHELL = 1
SET /a ENEMYSHELLTURNCOUNT = 3
ECHO %ENEMYNAME% now has Haste, Protect and Shell active for 3 turns
ECHO.
TIMEOUT /T 3 > nul