SET TARGET=PLAYER
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a TEMP2 = (((!%ATTACKER%SPD!*3)/2)+!%ATTACKER%STR!)/2
SET /a DAM = (((%TEMP2%*5)+!%ATTACKER%LVL!)/((!%DEFENDER%END!*3)+!%DEFENDER%LVL!)*(%TEMP2%+5)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"