SET /a RANFACT = (%RANDOM% %% 9) + 106
SET /a ENEMYBASEACC = (%ENEMYBASEACC%*%RANFACT%)/100
SET /a ENEMYBASEEVA = (%ENEMYBASEEVA%*%RANFACT%)/100
SET /a ENEMYBASESPD = (%ENEMYBASESPD%*%RANFACT%)/100
ECHO %ENEMYNAME%'s Accuracy, Evasion and Speed have increased
ECHO.
TIMEOUT /T 2 > nul