::Status1
SET /a TEMP1 = 0
SET /a TEMP2 = 0
SET /a TEMP3 = 0
SET TARGET=PLAYER
SET /a TEMP1 = (%RANDOM% %% %STATSPELLTOT%) + 1
SET /a HITCHANCE = !%ATTACKER%ACC!*50/!%DEFENDER%EVA!
IF DEFINED STAT%TEMP1%SPELL (
	SET STATUS=!STAT%TEMP1%SPELL!
)
SET /a TURNCOUNT = 2
CALL "%ENEMYSKILLRESOURCEPATH%\status.bat"
::STATUS2
SET /a TEMP2 = (%RANDOM% %% %STATSPELLTOT%) + 1
SET /a HITCHANCE = !%ATTACKER%ACC!*50/!%DEFENDER%EVA!
IF %TEMP2% EQU %TEMP1% (
	GOTO :STATUS3
) ELSE IF DEFINED STAT%TEMP2%SPELL (
	SET STATUS=!STAT%TEMP2%SPELL!
)
SET /a TURNCOUNT = 2
CALL "%ENEMYSKILLRESOURCEPATH%\status.bat"
:STATUS3
SET /a TEMP3 = (%RANDOM% %% %STATSPELLTOT%) + 1
SET /a HITCHANCE = !%ATTACKER%ACC!*50/!%DEFENDER%EVA!
IF %TEMP3% EQU %TEMP1% (
	GOTO :EOF
) ELSE IF %TEMP3% EQU %TEMP2% (
	GOTO :EOF
) ELSE IF DEFINED STAT%TEMP3%SPELL (
	SET STATUS=!STAT%TEMP3%SPELL!
)
SET /a TURNCOUNT = 2
CALL "%ENEMYSKILLRESOURCEPATH%\status.bat"