CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a DAM = (%DAM%*3)/2
SET TARGET=PLAYER
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %MISS% EQU 1 (
	GOTO :EOF
)
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a CRITICALCHANCE = 0
SET /a HITCHANCE = 100
SET /a DAM = %DAM%/2
SET TARGET=ENEMY
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"