SET TARGET=PLAYER
SET /a HITS = (%RANDOM% %% 4) + 1
SET /a HITCOUNT = 0
:LOOP
SET /a HITCOUNT = %HITCOUNT% + 1
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a DAM = %DAM%/3
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %HITCOUNT% LSS %HITS% (
	GOTO :LOOP
)