SET /a DAM = (((!%ATTACKER%STR!*5)+!%ATTACKER%LVL!)/((!%DEFENDER%END!*3)+!%DEFENDER%LVL!))*((!%ATTACKER%STR!+5)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)
SET /a HITCHANCE = !%ATTACKER%ACC!*80/!%DEFENDER%EVA!
SET /a CRITICALCHANCE = !%ATTACKER%LCK!*10/!%DEFENDER%LCK!