::Needs %TARGET%,%STATUS%,%TURNCOUNT%,%MISSCHANCE%

SET /a MISS = 0
SET /a IMMUNE = 0
CALL :RANDOMISE
CALL :IMMUNEQUERY
IF %IMMUNE% EQU 1 (
	GOTO :EOF
)
CALL :MISSQUERY
IF %MISS% EQU 1 (
	GOTO :EOF
)	
CALL :SKILLTEXT
GOTO :EOF

:RANDOMISE
SET /a RANFACT = (%RANDOM% %% 40) + 80
SET /a HITCHANCE = (%HITCHANCE%*100)/%RANFACT%
GOTO :EOF

:IMMUNEQUERY
IF !%TARGET%STATUSIMMUNENUM! EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:IMMUNELOOP
SET /a COUNT = %COUNT% + 1
IF /I !%TARGET%STATUSIMMUNE%COUNT%! EQU %STATUS% (
	SET /a IMMUNE = 1
	GOTO :EOF
)
IF %COUNT% LSS !%TARGET%STATUSIMMUNENUM! (
	GOTO :IMMUNELOOP
)
GOTO :EOF

:MISSQUERY
SET /a RANMISSCHANCE = %RANDOM% %% 100
IF %HITCHANCE% LSS %RANMISSCHANCE% (
	SET /a MISS = 1
)
GOTO :EOF

:SKILLTEXT
SET /a %TARGET%%STATUS% = 1
IF %TURNCOUNT% LSS 2 (
	SET /a TURNCOUNT = 2
) ELSE IF %TURNCOUNT% GTR 6 (
	SET /a TURNCOUNT = 6
)
SET /a %TARGET%%STATUS%TURNCOUNT = %TURNCOUNT%
ECHO !%TARGET%NAME! has been afflicted with %STATUS%
ECHO.
TIMEOUT /T 2 > nul
ECHO It will last for %TURNCOUNT% turns
ECHO.
TIMEOUT /T 2 > nul
GOTO :EOF