IF !%MAP%UNDERWATER! EQU 0 (
	CALL :DAMAGE
) ELSE (
	CALL :STEALOXYGEN
)
GOTO :EOF

:DAMAGE
SET /a PLAYERCONFUSION = 1
SET /a PLAYERCONFUSIONTURNCOUNT = ((!%ATTACKER%LVL!/3)*!%ATTACKER%MAG!)/((!%DEFENDER%LVL!/3)*(!%DEFENDER%SPR!*2))
IF %PLAYERCONFUSIONTURNCOUNT% LSS 3 (
	SET /a PLAYERCONFUSIONTURNCOUNT = 3
) ELSE IF %PLAYERCONFUSIONTURNCOUNT% GTR 6 (
	SET /a PLAYERCONFUSIONTURNCOUNT = 6
)
ECHO %ENEMYNAME% tried to steal oxygen from you but you're not underwater. How confusing^^!
ECHO.
TIMEOUT /T 3 > nul
ECHO %PLAYERNAME% is now confused. It will last for %PLAYERCONFUSIONTURNCOUNT% turns.
ECHO.
TIMEOUT /T 2 > nul
GOTO :EOF

:STEALOXYGEN
ECHO You have lost some oxygen^^!
ECHO.
TIMEOUT /T 2 > nul
SET /a PLAYEROXYGEN = (%PLAYEROXYGEN%*2)/3
IF %PLAYEROXYGEN% LSS 0 (
	SET /a PLAYEROXYGEN = 0
)
GOTO :EOF