CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET TARGET=PLAYER
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %MISS% EQU 1 (
	GOTO :EOF
)
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a HEAL = %DAM%
SET TARGET=ENEMY
CALL "%ENEMYSKILLRESOURCEPATH%\heal.bat"