CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET TARGET=PLAYER
SET /a DAM = %DAM%*3
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"
IF %MISS% EQU 1 (
	GOTO :EOF
)
CALL "%ENEMYSKILLRESOURCEPATH%\standarddam.bat"
SET /a CRITICALCHANCE = 0
SET /a HITCHANCE = 100
SET /a DAM = %ENEMYHP% - 1
SET TARGET=ENEMY
CALL "%ENEMYSKILLRESOURCEPATH%\dam.bat"