SET /a SPACESMAX = 38
SET /a STATINCREASEGIL = 200
SET /a WEAKNESSREMOVECOST = 1000
SET /a STRENGTHCOST = 3000
SET /a ELEMENTIMMUNECOST = 4000
SET /a ABSORBCOST = 5000
SET /a STATUSIMMUNECOST = 2500
SET /a GILCOST = 0
SET /a ENDSTONECOST = 0
SET /a SPRSTONECOST = 0
SET /a EVASTONECOST = 0
SET /a SPDSTONECOST = 0
SET /a BASECHOICE = 1000
CLS
:SLOTSET
CALL :SLOT
IF %SLOTNUM% EQU 0 (
	GOTO :EOF
)
:ARMOUREXISTQUERYSET
CALL :ARMOUREXISTQUERY
IF %ARMOUREXIST% EQU 1 (
	GOTO :ARMOUREXIST
) ELSE (
	GOTO :ARMOURNOTEXIST
)
:ARMOURNOTEXIST
:NAMESET
CALL :NAME
IF %NAMEBACK% EQU 1 (
	GOTO :SLOTSET
)
:BASESET
CALL :BASE
IF %BASEBACK% EQU 1 (
	GOTO :NAMESET
)
:BASESTATSET
CALL :CALCULATEBASESTATS
GOTO :STATINCREASESET


:ARMOUREXIST
:CUSTOMSTATSET
CALL :CALCULATECUSTOMSTATS
:STATINCREASESET
CALL :STATINCREASE
IF %STATINCREASEBACK% EQU 1 (
	IF %ARMOUREXIST% EQU 0 (
		GOTO :BASESET
	) ELSE (
		GOTO :SLOTSET
	)
)
:RESISTANCESSET
CALL :RESISTANCES
IF %RESISTANCESBACK% EQU 1 (
	IF %ARMOUREXIST% EQU 0 (
		GOTO :BASESTATSET
	) ELSE (
		GOTO :CUSTOMSTATSET
	)
)
:CONFIRMATIONSET
CALL :CONFIRMATION
IF %CONFIRMATIONBACK% EQU 1 (
	GOTO :RESISTANCESSET
)
IF %CONFIRMATIONCHOICE% EQU 1 (
	CALL :CREATEARMOUR
) ELSE IF %CONFIRMATIONCHOICE% EQU 2 (
	GOTO :EOF
)
:EQUIPSET
CALL :EQUIP
GOTO :EOF


:SLOT
CALL :INITIALISEBACKS
REM SET /a AVAILABLESLOTS = %PLAYERLVL%/10
SET /a AVAILABLESLOTS = 5
IF %AVAILABLESLOTS% GTR 9 (
	SET /a AVAILABLESLOTS = 9
)
IF EXIST "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat" (
	CALL "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat"
)
CLS
ECHO.
IF %AVAILABLESLOTS% EQU 0 (
	ECHO %BLACKSMITHNAME%: Sorry you're not a high enough level to customise armour yet...
	ECHO.
	SET /a SLOTNUM = 0
	pause
	GOTO :EOF
) ELSE IF %AVAILABLESLOTS% EQU 1 (
	ECHO %BLACKSMITHNAME%: You can hold %AVAILABLESLOTS% piece of custom armour
) ELSE IF %AVAILABLESLOTS% GEQ 2 (	
	ECHO %BLACKSMITHNAME%: You can hold %AVAILABLESLOTS% pieces of custom armour
)
ECHO.
ECHO            Select a custom armour slot
ECHO.
SET /a COUNT = 0
:SLOTSLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP = %ARMOURTOTAL% + %COUNT%
IF %AVAILABLESLOTS% GEQ %COUNT% (
ECHO. %COUNT% - !ARMOUR%TEMP%NAME!
)
IF %COUNT% LSS %AVAILABLESLOTS% (
	GOTO :SLOTSLOOP
)
ECHO. 0 - Back
ECHO.
:SLOTCHOICE
SET /P SLOTNUM=
ECHO.
IF "%SLOTNUM%" EQU "" (
	GOTO :SLOTCHOICE
)
IF %SLOTNUM% GTR %AVAILABLESLOTS% (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% LSS 0 (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% EQU 0 (
	GOTO :EOF
)
GOTO :EOF


:ARMOUREXISTQUERY
SET /a TEMP = %ARMOURTOTAL% + %SLOTNUM%
IF DEFINED ARMOUR%TEMP%NAME (
	CALL :EXISTTRUE
) ELSE (
	SET /a ARMOUREXIST = 0
)
GOTO :EOF

:EXISTTRUE
SET /a ARMOUREXIST = 1
CALL "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
SET ARMOURNAME=!ARMOUR%TEMP%NAME!
SET /a ARMOURID = %TEMP%
GOTO :EOF


:NAME
CLS
CALL :INITIALISEBACKS
ECHO.
ECHO %BLACKSMITHNAME%: What would you like to call your armour? (1 word)
ECHO.
ECHO             0 to exit
ECHO.
:NAMECHOICE
SET /P ARMOURNAME=
ECHO.
IF "%ARMOURNAME%" EQU "" (
	GOTO :NAMECHOICE
) ELSE IF "%ARMOURNAME%" EQU "0" (
	SET /a NAMEBACK = 1
)
GOTO :EOF

:BASE
CLS
CALL "%DYNAMICRESOURCEPATH%\dynamicarmourstatscustomise.bat"
CALL :INITIALISEBACKS
ECHO.
ECHO %BLACKSMITHNAME%: Choose a base piece of armour to customise
ECHO.
ECHO             0 to exit
ECHO.
SET /a COUNT = 0
SET /a PLAYERARMOURTOTAL = 0
:ARMOURCHECKLOOP
SET /a COUNT = %COUNT%+1
SET /a PLAYERARMOURTOTAL = %PLAYERARMOURTOTAL% + !PLAYERARMOUR%COUNT%NUM!
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :ARMOURCHECKLOOP
)
IF %PLAYERARMOURTOTAL% EQU 0 (
	GOTO :NOARMOURS
)
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT = %COUNT%+1
SET /a SPACENUM = %SPACESMAX% - !DYNAMICARMOUR%COUNT%NAMELENGTH!
ECHO. %COUNT% - !DYNAMICARMOUR%COUNT%NAME!!SPACES%SPACENUM%!(!DYNAMICARMOUR%COUNT%NUM!)
IF %COUNT% LSS %DYNAMICARMOURTOTAL% (
	GOTO :LOOPSTART
) 
:NOARMOURS
ECHO. 0 - Back
ECHO.
:BASECHOICE
SET /P DYNAMICBASECHOICE=
IF "%DYNAMICBASECHOICE%" EQU "" (
	GOTO :BASECHOICE
)
IF %DYNAMICBASECHOICE% LSS 0 (
	GOTO :BASECHOICE
) ELSE IF %DYNAMICBASECHOICE% GTR %DYNAMICARMOURTOTAL% (
	GOTO :BASECHOICE
) ELSE IF %DYNAMICBASECHOICE% EQU 0 (
	SET /a BASEBACK = 1
	GOTO :EOF
)
REM This is like SETSTATICID
SET /a COUNT = 0
:LOOP2START
SET /a COUNT = %COUNT%+1
IF "!ARMOUR%COUNT%NAME!" EQU "!DYNAMICARMOUR%DYNAMICBASECHOICE%NAME!" (
	SET /a BASECHOICE = %COUNT%
) ELSE IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :LOOP2START
) ELSE IF %COUNT% EQU %ARMOURTOTAL% (
	GOTO :BASECHOICE
)
GOTO :EOF

:CALCULATEBASESTATS
SET /a TEMPEND = !ARMOUR%BASECHOICE%END!
SET /a TEMPSPR = !ARMOUR%BASECHOICE%SPR!
SET /a TEMPEVA = !ARMOUR%BASECHOICE%EVA!
SET /a TEMPSPD = !ARMOUR%BASECHOICE%SPD!
GOTO :EOF

:CALCULATECUSTOMSTATS
SET /a TEMP = %ARMOURTOTAL% + %SLOTNUM%
SET /a TEMPEND = !ARMOUR%TEMP%END!
SET /a TEMPSPR = !ARMOUR%TEMP%SPR!
SET /a TEMPEVA = !ARMOUR%TEMP%EVA!
SET /a TEMPSPD = !ARMOUR%TEMP%SPD!
GOTO :EOF

:STATINCREASE
CALL :INITIALISEBACKS
SET /a GILCOST = 0
SET /a ENDSTONECOST = 0
SET /a SPRSTONECOST = 0
SET /a EVASTONECOST = 0
SET /a SPDSTONECOST = 0
:STATINCREASE2
CALL :SETTEMPSTATVARS
CLS
ECHO.
ECHO %BLACKSMITHNAME%: This armour currently give you the following stat bonuses:
ECHO.
ECHO. Endurance +%TEMPEND%
ECHO. Spirit    +%TEMPSPR%
ECHO. Evasion   +%TEMPEVA%
ECHO. Speed     +%TEMPSPD%
ECHO.
ECHO %BLACKSMITHNAME%: Select the stat you'd like to increase.
ECHO             Each stat costs 1 stone and %STATINCREASEGIL% Gil
ECHO             You have %TEMPGIL% Gil remaining
ECHO.
IF %TEMPENDSTONE% EQU 1 (
	ECHO. 1 - Endurance                 %TEMPENDSTONE% !SPECIALITEM%ENDSTONEID%NAME!
) ELSE (
	ECHO. 1 - Endurance                 %TEMPENDSTONE% !SPECIALITEM%ENDSTONEID%NAME!s
)
IF %TEMPSPRSTONE% EQU 1 (
	ECHO. 2 - Spirit                    %TEMPSPRSTONE% !SPECIALITEM%SPRSTONEID%NAME!
) ELSE (
	ECHO. 2 - Spirit                    %TEMPSPRSTONE% !SPECIALITEM%SPRSTONEID%NAME!s
)
IF %TEMPEVASTONE% EQU 1 (
	ECHO. 3 - Evasion                   %TEMPEVASTONE% !SPECIALITEM%EVASTONEID%NAME!
) ELSE (
	ECHO. 3 - Evasion                   %TEMPEVASTONE% !SPECIALITEM%EVASTONEID%NAME!s
)
IF %TEMPSPDSTONE% EQU 1 (
	ECHO. 4 - Speed                     %TEMPSPDSTONE% !SPECIALITEM%SPDSTONEID%NAME!
) ELSE (
	ECHO. 4 - Speed                     %TEMPSPDSTONE% !SPECIALITEM%SPDSTONEID%NAME!s
)
ECHO. 0 - Done
ECHO. B - Back
ECHO.
:STATINCREASECHOICE
SET /P STATINCREASECHOICE=
ECHO.
IF "%STATINCREASECHOICE%" EQU "1" (
	IF %TEMPENDSTONE% GTR 0 (
		IF %PLAYERGIL% GEQ %TEMPGILCOST% (
			SET /a GILCOST = %GILCOST% + %STATINCREASEGIL%
			SET /a ENDSTONECOST = %ENDSTONECOST% + 1
			SET /a TEMPEND = %TEMPEND% + 1
		) ELSE (
			ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
			ECHO.
			CALL :WAITFORTWO
		)
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%ENDSTONEID%NAME!s for this
		ECHO.
		CALL :WAITFORTWO
	)
) ELSE IF "%STATINCREASECHOICE%" EQU "2" (
	IF %TEMPSPRSTONE% GTR 0 (
		IF %PLAYERGIL% GEQ %TEMPGILCOST% (
			SET /a GILCOST = %GILCOST% + %STATINCREASEGIL%
			SET /a SPRSTONECOST = %SPRSTONECOST% + 1
			SET /a TEMPSPR = %TEMPSPR% + 1
		) ELSE (
			ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
			ECHO.
			CALL :WAITFORTWO
		)
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%SPRSTONEID%NAME!s for this
		ECHO.
		CALL :WAITFORTWO
	)
) ELSE IF "%STATINCREASECHOICE%" EQU "3" (
	IF %TEMPEVASTONE% GTR 0 (
		IF %PLAYERGIL% GEQ %TEMPGILCOST% (
			SET /a GILCOST = %GILCOST% + %STATINCREASEGIL%
			SET /a EVASTONECOST = %EVASTONECOST% + 1
			SET /a TEMPEVA = %TEMPEVA% + 1
		) ELSE (
			ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
			ECHO.
			CALL :WAITFORTWO
		)
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%EVASTONEID%NAME!s for this
		ECHO.
		CALL :WAITFORTWO
	)
) ELSE IF "%STATINCREASECHOICE%" EQU "4" (
	IF %TEMPSPDSTONE% GTR 0 (
		IF %PLAYERGIL% GEQ %TEMPGILCOST% (
			SET /a GILCOST = %GILCOST% + %STATINCREASEGIL%
			SET /a SPDSTONECOST = %SPDSTONECOST% + 1
			SET /a TEMPSPD = %TEMPSPD% + 1
		) ELSE (
			ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
			ECHO.
			CALL :WAITFORTWO
		)
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%SPDSTONEID%NAME!s for this
		ECHO.
		CALL :WAITFORTWO
	)
) ELSE IF "%STATINCREASECHOICE%" EQU "0" (
	SET /a STATGILCOST = %GILCOST%
	GOTO :EOF
) ELSE IF /I "%STATINCREASECHOICE%" EQU "B" (
	SET /a STATINCREASEBACK = 1
	GOTO :EOF
) ELSE (
	GOTO :STATINCREASECHOICE
)
GOTO :STATINCREASE2

:SETTEMPSTATVARS
SET /a TEMPGILCOST = %GILCOST% + %STATINCREASEGIL%
SET /a TEMPGIL = %PLAYERGIL% - %GILCOST%
SET /a TEMPENDSTONE = !PLAYERSPECIALITEM%ENDSTONEID%NUM! - %ENDSTONECOST%
SET /a TEMPSPRSTONE = !PLAYERSPECIALITEM%SPRSTONEID%NUM! - %SPRSTONECOST%
SET /a TEMPEVASTONE = !PLAYERSPECIALITEM%EVASTONEID%NUM! - %EVASTONECOST%
SET /a TEMPSPDSTONE = !PLAYERSPECIALITEM%SPDSTONEID%NUM! - %SPDSTONECOST%
GOTO :EOF



:RESISTANCES
IF %ARMOUREXIST% EQU 0 (
	CALL :INITIALBASERESISTANCESET
) ELSE (
	CALL :INITIALCUSTOMRESISTANCESET
)
CALL :TEMPRESISTANCERESET
CALL :RESISTANCESET
GOTO :EOF

:RESISTANCESET
SET /a WEAKNESSGILCOST = 0
SET /a WEAKNESSITEMCOST = 0
SET /a STRENGTHGILCOST = 0
SET /a STRENGTHITEMCOST = 0
SET /a ELEMENTIMMUNEGILCOST = 0
SET /a ELEMENTIMMUNEITEMCOST = 0
SET /a ABSORBGILCOST = 0
SET /a ABSORBITEMCOST = 0
SET /a STATUSIMMUNEGILCOST = 0
SET /a STATUSIMMUNEITEMCOST = 0
:RESISTANCESET2
CALL :INITIALISEBACKS
CALL :SETTEMPRESISTANCEVARS
CLS
ECHO.
IF %TEMP2WEAKNESSTOT% EQU 0 (
	IF %TEMP2STRENGTHTOT% EQU 0 (
		IF %TEMP2ELEMENTIMMUNETOT% EQU 0 (
			IF %TEMP2ABSORBTOT% EQU 0 (
				IF %TEMP2STATUSIMMUNETOT% EQU 0 (
					ECHO %BLACKSMITHNAME%: This armour currently doesn't give you any resistances or weaknesses
					ECHO.
					GOTO :ENDRESISTANCELOOP5
				)
			)
		)
	)
)
ECHO %BLACKSMITHNAME%: This armour currently has the following properties:
ECHO.
IF %TEMP2WEAKNESSTOT% EQU 0 (
	GOTO :ENDRESISTANCELOOP1
)
SET /a COUNT = 0
:RESISTANCELOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Weakness to !TEMP2WEAKNESS%COUNT%! elemental magic
IF %COUNT% LSS %TEMP2WEAKNESSTOT% (
	GOTO :RESISTANCELOOP1
)
ECHO.
:ENDRESISTANCELOOP1
IF %TEMP2STRENGTHTOT% EQU 0 (
	GOTO :ENDRESISTANCELOOP2
)
SET /a COUNT = 0
:RESISTANCELOOP2
SET /a COUNT = %COUNT% + 1
ECHO. Resistance to !TEMP2STRENGTH%COUNT%! elemental magic
IF %COUNT% LSS %TEMP2STRENGTHTOT% (
	GOTO :RESISTANCELOOP2
)
ECHO.
:ENDRESISTANCELOOP2
IF %TEMP2ELEMENTIMMUNETOT% EQU 0 (
	GOTO :ENDRESISTANCELOOP3
)
SET /a COUNT = 0
:RESISTANCELOOP3
SET /a COUNT = %COUNT% + 1
ECHO. Immunity to !TEMP2ELEMENTIMMUNE%COUNT%! elemental magic
IF %COUNT% LSS %TEMP2ELEMENTIMMUNETOT% (
	GOTO :RESISTANCELOOP3
)
ECHO.
:ENDRESISTANCELOOP3
IF %TEMP2ABSORBTOT% EQU 0 (
	GOTO :ENDRESISTANCELOOP4
)
SET /a COUNT = 0
:RESISTANCELOOP4
SET /a COUNT = %COUNT% + 1
ECHO. Absorption of !TEMP2ABSORB%COUNT%! elemental magic
IF %COUNT% LSS %TEMP2ABSORBTOT% (
	GOTO :RESISTANCELOOP4
)
ECHO.
:ENDRESISTANCELOOP4
IF %TEMP2STATUSIMMUNETOT% EQU 0 (
	GOTO :ENDRESISTANCELOOP5
)
SET /a COUNT = 0
:RESISTANCELOOP5
SET /a COUNT = %COUNT% + 1
ECHO. Immunity to the !TEMP2STATUSIMMUNE%COUNT%! ailment
IF %COUNT% LSS %TEMP2STATUSIMMUNETOT% (
	GOTO :RESISTANCELOOP5
)
ECHO.
:ENDRESISTANCELOOP5
ECHO %BLACKSMITHNAME%: Which properties would you like to tinker with?
ECHO.
ECHO. 1 - Remove elemental weaknesses           (%TEMPWEAKNESSITEMNUM% !SPECIALITEM%WEAKPOWID%NAME!s)
ECHO. 2 - Add elemental resistances             (%TEMPSTRENGTHITEMNUM% !SPECIALITEM%RESPOWID%NAME!s)
ECHO. 3 - Add elemental immunities              (%TEMPELEMENTIMMUNEITEMNUM% !SPECIALITEM%ELEIMMPOWID%NAME!s)
ECHO. 4 - Add elemental absorption              (%TEMPABSORBITEMNUM% !SPECIALITEM%ABSPOWID%NAME!s)
ECHO. 5 - Add status immunities                 (%TEMPSTATUSIMMUNEITEMNUM% !SPECIALITEM%STATIMMPOWID%NAME!s)
ECHO. 0 - Done
ECHO. B - Back
ECHO.
:RESISTANCECHOICE
SET /P RESISTANCECHOICE=
ECHO.
IF "%RESISTANCECHOICE%" EQU "1" (
	CALL :REMOVEWEAKNESSES
) ELSE IF "%RESISTANCECHOICE%" EQU "2" (
	CALL :ADDSTRENGTHS
) ELSE IF "%RESISTANCECHOICE%" EQU "3" (
	CALL :ADDELEMENTIMMUNES
) ELSE IF "%RESISTANCECHOICE%" EQU "4" (
	CALL :ADDABSORBS
) ELSE IF "%RESISTANCECHOICE%" EQU "5" (
	CALL :ADDSTATUSIMMUNES
) ELSE IF /I "%RESISTANCECHOICE%" EQU "B" (
	SET /a RESISTANCESBACK = 1
	GOTO :EOF
) ELSE IF "%RESISTANCECHOICE%" EQU "0" (
	GOTO :EOF
)
GOTO :RESISTANCESET2

:SETTEMPRESISTANCEVARS
SET /a TEMPWEAKNESSITEMNUM = !PLAYERSPECIALITEM%WEAKPOWID%NUM! - %WEAKNESSITEMCOST%
SET /a TEMPSTRENGTHITEMNUM = !PLAYERSPECIALITEM%RESPOWID%NUM! - %STRENGTHITEMCOST%
SET /a TEMPELEMENTIMMUNEITEMNUM = !PLAYERSPECIALITEM%ELEIMMPOWID%NUM! - %ELEMENTIMMUNEITEMCOST%
SET /a TEMPABSORBITEMNUM = !PLAYERSPECIALITEM%ABSPOWID%NUM! - %ABSORBITEMCOST%
SET /a TEMPSTATUSIMMUNEITEMNUM = !PLAYERSPECIALITEM%STATIMMPOWID%NUM! - %STATUSIMMUNEITEMCOST%
SET /a RESISTANCEGILCOST = %WEAKNESSGILCOST% + %STRENGTHGILCOST% + %ELEMENTIMMUNEGILCOST% + %ABSORBGILCOST% + %STATUSIMMUNEGILCOST%
SET /a GILCOST = %STATGILCOST% + %RESISTANCEGILCOST%
SET /a TEMPGIL = %PLAYERGIL% - %GILCOST%
GOTO :EOF



:REMOVEWEAKNESSES
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have %TEMPWEAKNESSITEMNUM% !SPECIALITEM%WEAKPOWID%NAME!s and %TEMPGIL% Gil
ECHO             It'll cost you 1 !SPECIALITEM%WEAKPOWID%NAME! and %WEAKNESSREMOVECOST% gil per element
ECHO             Choose which elemental weakness you'd like to remove
ECHO.
IF %TEMP2WEAKNESSTOT% EQU 0 (
	GOTO :NOWEAKNESSES
)
SET /a COUNT = 0

:REMOVEWEAKNESSESLOOP
SET /a COUNT = %COUNT% + 1
ECHO. %COUNT% - !TEMP2WEAKNESS%COUNT%!
IF %COUNT% LSS %TEMP2WEAKNESSTOT% (
	GOTO :REMOVEWEAKNESSESLOOP
)
:NOWEAKNESSES
ECHO. 0 - Done
ECHO. R - Reset
ECHO.
:REMOVEWEAKNESSESCHOICE
SET /P REMOVEWEAKNESSESCHOICE=
ECHO.
IF "%REMOVEWEAKNESSESCHOICE%" EQU "" (
	GOTO :REMOVEWEAKNESSESCHOICE
) ELSE IF /I "%REMOVEWEAKNESSESCHOICE%" EQU "R" (
	CALL :RESETTEMPWEAKNESSES
	CALL :SETTEMPRESISTANCEVARS
	GOTO :REMOVEWEAKNESSES
)
IF %REMOVEWEAKNESSESCHOICE% GTR %TEMP2WEAKNESSTOT% (
	GOTO :REMOVEWEAKNESSESCHOICE
) ELSE IF %REMOVEWEAKNESSESCHOICE% LSS 0 (
	GOTO :REMOVEWEAKNESSESCHOICE
) ELSE IF %REMOVEWEAKNESSESCHOICE% EQU 0 (
	GOTO :EOF
)
IF %TEMPGIL% GEQ %WEAKNESSREMOVECOST% (
	IF %TEMPWEAKNESSITEMNUM% GTR 1 (
		CALL :REMOVEWEAKNESSSUCCESS
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%WEAKPOWID%NAME!s for this
		ECHO.
		CALL :WAITFORTHREE
	)
) ELSE (
	ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
	ECHO.
	CALL :WAITFORTHREE
)
GOTO :REMOVEWEAKNESSES

:REMOVEWEAKNESSSUCCESS
SET /a WEAKNESSITEMCOST = %WEAKNESSITEMCOST% + 1
SET /a WEAKNESSGILCOST = %WEAKNESSGILCOST% + %WEAKNESSREMOVECOST%
CALL :SETTEMPRESISTANCEVARS
CALL :REMOVEWEAKNESS
GOTO :EOF

:REMOVEWEAKNESS
IF %TEMP2WEAKNESSTOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
SET /a TEMPCOUNT = 0
:REMOVEWEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
IF %COUNT% NEQ %REMOVEWEAKNESSESCHOICE% (
	SET /a TEMPCOUNT = %TEMPCOUNT% + 1
)
IF %COUNT% NEQ %REMOVEWEAKNESSESCHOICE% (
	SET TEMP2WEAKNESS%TEMPCOUNT%=!TEMPWEAKNESS%COUNT%!
)
IF %COUNT% LSS %TEMP2WEAKNESSTOT% (
	GOTO :REMOVEWEAKNESSLOOP
)
SET /a TEMP2WEAKNESSTOT = %TEMP2WEAKNESSTOT% - 1
GOTO :EOF


:ADDSTRENGTHS
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have %TEMPSTRENGTHITEMNUM% !SPECIALITEM%RESPOWID%NAME!s and %TEMPGIL% Gil
ECHO             It'll cost you 1 !SPECIALITEM%RESPOWID%NAME! and %STRENGTHCOST% gil per element
ECHO             Choose which elemental resistance you'd like to add
ECHO.
SET /a COUNT = 0
:ADDSTRENGTHSLOOP
SET SPELL=FIRE
SET ELEMENT=Fire
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=BLIZZARD
SET ELEMENT=Ice
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=THUNDER
SET ELEMENT=Electricity
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=WATER
SET ELEMENT=Water
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=QUAKE
SET ELEMENT=Earth
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=DEMI
SET ELEMENT=Demi
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=DRAIN
SET ELEMENT=Drain
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET SPELL=COMET
SET ELEMENT=Forbidden
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTRENGTHCHECK
)
SET /a TEMPADDSTRENGTHTOTAL = %COUNT%
ECHO. 0 - Done
ECHO. R - Reset
ECHO.
:ADDSTRENGTHCHOICE
SET /P ADDSTRENGTHCHOICE=
ECHO.
IF "%ADDSTRENGTHCHOICE%" EQU "" (
	GOTO :ADDSTRENGTHCHOICE
) ELSE IF /I "%ADDSTRENGTHCHOICE%" EQU "R" (
	CALL :RESETTEMPSTRENGTHS
	CALL :SETTEMPRESISTANCEVARS
	GOTO :ADDSTRENGTHS
)
IF %ADDSTRENGTHCHOICE% GTR %TEMPADDSTRENGTHTOTAL% (
	GOTO :ADDSTRENGTHCHOICE
) ELSE IF %ADDSTRENGTHCHOICE% LSS 0 (
	GOTO :ADDSTRENGTHCHOICE
) ELSE IF %ADDSTRENGTHCHOICE% EQU 0 (
	GOTO :EOF
)
IF %TEMPGIL% GEQ %STRENGTHCOST% (
	IF %TEMPSTRENGTHITEMNUM% GTR 1 (
		CALL :ADDSTRENGTHSUCCESS
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%RESPOWID%NAME!s for this
		ECHO.
		CALL :WAITFORTHREE
	)
) ELSE (
	ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
	ECHO.
	CALL :WAITFORTHREE
)
GOTO :ADDSTRENGTHS

:ADDSTRENGTHSUCCESS
SET /a STRENGTHITEMCOST = %STRENGTHITEMCOST% + 1
SET /a STRENGTHGILCOST = %STRENGTHGILCOST% + %STRENGTHCOST%
CALL :SETTEMPRESISTANCEVARS
SET /a TEMP2STRENGTHTOT = %TEMP2STRENGTHTOT% + 1
SET TEMP2STRENGTH%TEMP2STRENGTHTOT%=!TEMPSTATUS%ADDSTRENGTHCHOICE%!
GOTO :EOF


:ADDSTRENGTHCHECK
SET /a TEMPFLAG = 1
SET /a TEMPCOUNT = 0
:ADDSTRENGTHCHECKLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF %TEMP2STRENGTHTOT% EQU 0 (
	CALL :ADDSTRENGTHCHECKTRUE
	GOTO :EOF
)
IF /I %ELEMENT% EQU !TEMP2STRENGTH%TEMPCOUNT%! (
	SET /a TEMPFLAG = 0
)
IF %TEMPCOUNT% LSS %TEMP2STRENGTHTOT% (
	GOTO :ADDSTRENGTHCHECKLOOP
)
IF %TEMPFLAG% EQU 1 (
	CALL :ADDSTRENGTHCHECKTRUE
)
GOTO :EOF

:ADDSTRENGTHCHECKTRUE
SET /a COUNT = %COUNT% + 1
SET TEMPELEMENT%COUNT%=%ELEMENT%
ECHO. %COUNT% - %ELEMENT%
GOTO :EOF



:ADDELEMENTIMMUNES
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have %TEMPELEMENTIMMUNEITEMNUM% !SPECIALITEM%ELEIMMPOWID%NAME!s and %TEMPGIL% Gil
ECHO             It'll cost you 1 !SPECIALITEM%ELEIMMPOWID%NAME! and %ELEMENTIMMUNECOST% gil per element
ECHO             Choose which elemental resistance you'd like to add
ECHO.
SET /a COUNT = 0
:ADDELEMENTIMMUNESLOOP
SET SPELL=FIRA
SET ELEMENT=Fire
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=BLIZZARA
SET ELEMENT=Ice
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=THUNDARA
SET ELEMENT=Electricity
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=WATERA
SET ELEMENT=Water
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=QUAKE
SET ELEMENT=Earth
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=DEMI
SET ELEMENT=Demi
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=DRAIN
SET ELEMENT=Drain
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET SPELL=METEOR
SET ELEMENT=Forbidden
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDELEMENTIMMUNECHECK
)
SET /a TEMPADDELEMENTIMMUNETOTAL = %COUNT%
ECHO. 0 - Done
ECHO. R - Reset
ECHO.
:ADDELEMENTIMMUNECHOICE
SET /P ADDELEMENTIMMUNECHOICE=
ECHO.
IF "%ADDELEMENTIMMUNECHOICE%" EQU "" (
	GOTO :ADDELEMENTIMMUNECHOICE
) ELSE IF /I "%ADDELEMENTIMMUNECHOICE%" EQU "R" (
	CALL :RESETTEMPELEMENTIMMUNES
	CALL :SETTEMPRESISTANCEVARS
	GOTO :ADDELEMENTIMMUNES
)
IF %ADDELEMENTIMMUNECHOICE% GTR %TEMPADDELEMENTIMMUNETOTAL% (
	GOTO :ADDELEMENTIMMUNECHOICE
) ELSE IF %ADDELEMENTIMMUNECHOICE% LSS 0 (
	GOTO :ADDELEMENTIMMUNECHOICE
) ELSE IF %ADDELEMENTIMMUNECHOICE% EQU 0 (
	GOTO :EOF
)
IF %TEMPGIL% GEQ %ELEMENTIMMUNECOST% (
	IF %TEMPELEMENTIMMUNEITEMNUM% GTR 1 (
		CALL :ADDELEMENTIMMUNESUCCESS
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%ELEIMMPOWID%NAME!s for this
		ECHO.
		CALL :WAITFORTHREE
	)
) ELSE (
	ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
	ECHO.
	CALL :WAITFORTHREE
)
GOTO :ADDELEMENTIMMUNES

:ADDELEMENTIMMUNESUCCESS
SET /a ELEMENTIMMUNEITEMCOST = %ELEMENTIMMUNEITEMCOST% + 1
SET /a ELEMENTIMMUNEGILCOST = %ELEMENTIMMUNEGILCOST% + %ELEMENTIMMUNECOST%
CALL :SETTEMPRESISTANCEVARS
SET /a TEMP2ELEMENTIMMUNETOT = %TEMP2ELEMENTIMMUNETOT% + 1
SET TEMP2ELEMENTIMMUNE%TEMP2ELEMENTIMMUNETOT%=!TEMPELEMENT%ADDELEMENTIMMUNECHOICE%!
GOTO :EOF


:ADDELEMENTIMMUNECHECK
SET /a TEMPFLAG = 1
SET /a TEMPCOUNT = 0
:ADDELEMENTIMMUNECHECKLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF %TEMP2ELEMENTIMMUNETOT% EQU 0 (
	CALL :ADDELEMENTIMMUNECHECKTRUE
	GOTO :EOF
)
IF /I %ELEMENT% EQU !TEMP2ELEMENTIMMUNE%TEMPCOUNT%! (
	SET /a TEMPFLAG = 0
)
IF %TEMPCOUNT% LSS %TEMP2ELEMENTIMMUNETOT% (
	GOTO :ADDELEMENTIMMUNECHECKLOOP
)
IF %TEMPFLAG% EQU 1 (
	CALL :ADDELEMENTIMMUNECHECKTRUE
)
GOTO :EOF

:ADDELEMENTIMMUNECHECKTRUE
SET /a COUNT = %COUNT% + 1
SET TEMPELEMENT%COUNT%=%ELEMENT%
ECHO. %COUNT% - %ELEMENT%
GOTO :EOF



:ADDABSORBS
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have %TEMPABSORBITEMNUM% !SPECIALITEM%ABSPOWID%NAME!s and %TEMPGIL% Gil
ECHO             It'll cost you 1 !SPECIALITEM%ABSPOWID%NAME! and %ABSORBCOST% gil per element
ECHO             Choose which elemental resistance you'd like to add
ECHO.
SET /a COUNT = 0
:ADDABSORBSLOOP
SET SPELL=FIRAGA
SET ELEMENT=Fire
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=BLIZZAGA
SET ELEMENT=Ice
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=THUNDAGA
SET ELEMENT=Electricity
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=WATERAGA
SET ELEMENT=Water
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=QUAKE
SET ELEMENT=Earth
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=DEMI
SET ELEMENT=Demi
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=DRAIN
SET ELEMENT=Drain
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
)
SET SPELL=SHADOWFLARE
SET ELEMENT=Forbidden
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
) ELSE IF !PLAYER%SPELL2%ENABLED! EQU 1 (
	CALL :ADDABSORBCHECK
) 
SET /a TEMPADDABSORBTOTAL = %COUNT%
ECHO. 0 - Done
ECHO. R - Reset
ECHO.
:ADDABSORBCHOICE
SET /P ADDABSORBCHOICE=
ECHO.
IF "%ADDABSORBCHOICE%" EQU "" (
	GOTO :ADDABSORBCHOICE
) ELSE IF /I "%ADDABSORBCHOICE%" EQU "R" (
	CALL :RESETTEMPABSORBS
	CALL :SETTEMPRESISTANCEVARS
	GOTO :ADDABSORBS
)
IF %ADDABSORBCHOICE% GTR %TEMPADDABSORBTOTAL% (
	GOTO :ADDABSORBCHOICE
) ELSE IF %ADDABSORBCHOICE% LSS 0 (
	GOTO :ADDABSORBCHOICE
) ELSE IF %ADDABSORBCHOICE% EQU 0 (
	GOTO :EOF
)
IF %TEMPGIL% GEQ %ABSORBCOST% (
	IF %TEMPABSORBITEMNUM% GTR 1 (
		CALL :ADDABSORBSUCCESS
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%ABSPOWID%NAME!s for this
		ECHO.
		CALL :WAITFORTHREE
	)
) ELSE (
	ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
	ECHO.
	CALL :WAITFORTHREE
)
GOTO :ADDABSORBS

:ADDABSORBSUCCESS
SET /a ABSORBITEMCOST = %ABSORBITEMCOST% + 1
SET /a ABSORBGILCOST = %ABSORBGILCOST% + %ABSORBCOST%
CALL :SETTEMPRESISTANCEVARS
SET /a TEMP2ABSORBTOT = %TEMP2ABSORBTOT% + 1
SET TEMP2ABSORB%TEMP2ABSORBTOT%=!TEMPSTATUS%ADDABSORBCHOICE%!
GOTO :EOF


:ADDABSORBCHECK
SET /a TEMPFLAG = 1
SET /a TEMPCOUNT = 0
:ADDABSORBCHECKLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF %TEMP2ABSORBTOT% EQU 0 (
	CALL :ADDABSORBCHECKTRUE
	GOTO :EOF
)
IF /I %ELEMENT% EQU !TEMP2ABSORB%TEMPCOUNT%! (
	SET /a TEMPFLAG = 0
)
IF %TEMPCOUNT% LSS %TEMP2ABSORBTOT% (
	GOTO :ADDABSORBCHECKLOOP
)
IF %TEMPFLAG% EQU 1 (
	CALL :ADDABSORBCHECKTRUE
)
GOTO :EOF

:ADDABSORBCHECKTRUE
SET /a COUNT = %COUNT% + 1
SET TEMPELEMENT%COUNT%=%ELEMENT%
ECHO. %COUNT% - %ELEMENT%
GOTO :EOF


:ADDSTATUSIMMUNES
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have %TEMPSTATUSIMMUNEITEMNUM% !SPECIALITEM%STATIMMPOWID%NAME!s and %TEMPGIL% Gil
ECHO             It'll cost you 1 !SPECIALITEM%STATIMMPOWID%NAME! and %STATUSIMMUNECOST% gil per element
ECHO             Choose which elemental resistance you'd like to add
ECHO.
SET /a COUNT = 0
:ADDSTATUSIMMUNESLOOP
SET SPELL=BLIND
SET STATUS=Blind
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=SILENCE
SET STATUS=Silence
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=POISON
SET STATUS=Poison
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=SLOW
SET STATUS=Slow
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=SLEEP
SET STATUS=Sleep
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=CONFUSION
SET STATUS=Confusion
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET SPELL=STOP
SET STATUS=Stop
IF !PLAYER%SPELL%ENABLED! EQU 1 (
	CALL :ADDSTATUSIMMUNECHECK
)
SET /a TEMPADDSTATUSIMMUNETOTAL = %COUNT%
ECHO. 0 - Done
ECHO. R - Reset
ECHO.
:ADDSTATUSIMMUNECHOICE
SET /P ADDSTATUSIMMUNECHOICE=
ECHO.
IF "%ADDSTATUSIMMUNECHOICE%" EQU "" (
	GOTO :ADDSTATUSIMMUNECHOICE
) ELSE IF /I "%ADDSTATUSIMMUNECHOICE%" EQU "R" (
	CALL :RESETTEMPSTATUSIMMUNES
	CALL :SETTEMPRESISTANCEVARS
	GOTO :ADDSTATUSIMMUNES
)
IF %ADDSTATUSIMMUNECHOICE% GTR %TEMPADDSTATUSIMMUNETOTAL% (
	GOTO :ADDSTATUSIMMUNECHOICE
) ELSE IF %ADDSTATUSIMMUNECHOICE% LSS 0 (
	GOTO :ADDSTATUSIMMUNECHOICE
) ELSE IF %ADDSTATUSIMMUNECHOICE% EQU 0 (
	GOTO :EOF
)
IF %TEMPGIL% GEQ %STATUSIMMUNECOST% (
	IF %TEMPSTATUSIMMUNEITEMNUM% GTR 1 (
		CALL :ADDSTATUSIMMUNESUCCESS
	) ELSE (
		ECHO %BLACKSMITHNAME%: You don't have enough !SPECIALITEM%STATIMMPOWID%NAME!s for this
		ECHO.
		CALL :WAITFORTHREE
	)
) ELSE (
	ECHO %BLACKSMITHNAME%: You don't have enough Gil for this
	ECHO.
	CALL :WAITFORTHREE
)
GOTO :ADDSTATUSIMMUNES

:ADDSTATUSIMMUNESUCCESS
SET /a STATUSIMMUNEITEMCOST = %STATUSIMMUNEITEMCOST% + 1
SET /a STATUSIMMUNEGILCOST = %STATUSIMMUNEGILCOST% + %STATUSIMMUNECOST%
CALL :SETTEMPRESISTANCEVARS
SET /a TEMP2STATUSIMMUNETOT = %TEMP2STATUSIMMUNETOT% + 1
SET TEMP2STATUSIMMUNE%TEMP2STATUSIMMUNETOT%=!TEMPSTATUS%ADDSTATUSIMMUNECHOICE%!
GOTO :EOF

:ADDSTATUSIMMUNECHECK
SET /a TEMPFLAG = 1
SET /a TEMPCOUNT = 0
:ADDSTATUSIMMUNECHECKLOOP
SET /a TEMPCOUNT = %TEMPCOUNT% + 1
IF %TEMP2STATUSIMMUNETOT% EQU 0 (
	CALL :ADDSTATUSIMMUNECHECKTRUE
	GOTO :EOF
)
IF /I %STATUS% EQU !TEMP2STATUSIMMUNE%TEMPCOUNT%! (
	SET /a TEMPFLAG = 0
)
IF %TEMPCOUNT% LSS %TEMP2STATUSIMMUNETOT% (
	GOTO :ADDSTATUSIMMUNECHECKLOOP
)
IF %TEMPFLAG% EQU 1 (
	CALL :ADDSTATUSIMMUNECHECKTRUE
)
GOTO :EOF

:ADDSTATUSIMMUNECHECKTRUE
SET /a COUNT = %COUNT% + 1
SET TEMPSTATUS%COUNT%=%STATUS%
ECHO. %COUNT% - %STATUS%
GOTO :EOF



:TEMPRESISTANCERESET
CALL :RESETTEMPWEAKNESSES
CALL :RESETTEMPSTRENGTHS
CALL :RESETTEMPELEMENTIMMUNES
CALL :RESETTEMPABSORBS
CALL :RESETTEMPSTATUSIMMUNES
GOTO :EOF


:RESETTEMPWEAKNESSES
SET /a WEAKNESSGILCOST = 0
SET /a WEAKNESSITEMCOST = 0
SET /a TEMP2WEAKNESSTOT = %TEMPWEAKNESSTOT%
IF %TEMPWEAKNESSTOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESETTEMPWEAKNESSESLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP2WEAKNESS%COUNT%=!TEMPWEAKNESS%COUNT%!
IF %COUNT% LSS %TEMPWEAKNESSTOT% (
	GOTO :RESETTEMPWEAKNESSESLOOP
)
GOTO :EOF


:RESETTEMPSTRENGTHS
SET /a STRENGTHGILCOST = 0
SET /a STRENGTHITEMCOST = 0
SET /a TEMP2STRENGTHTOT = %TEMPSTRENGTHTOT%
IF %TEMPSTRENGTHTOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESETTEMPSTRENGTHSLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP2STRENGTH%COUNT%=!TEMPSTRENGTH%COUNT%!
IF %COUNT% LSS %TEMPSTRENGTHTOT% (
	GOTO :RESETTEMPSTRENGTHSLOOP
)
GOTO :EOF

:RESETTEMPELEMENTIMMUNES
SET /a ELEMENTIMMUNEGILCOST = 0
SET /a ELEMENTIMMUNEITEMCOST = 0
SET /a TEMP2ELEMENTIMMUNETOT = %TEMPELEMENTIMMUNETOT%
IF %TEMPELEMENTIMMUNETOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESETTEMPELEMENTIMMUNESLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP2ELEMENTIMMUNE%COUNT%=!TEMPELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPELEMENTIMMUNETOT% (
	GOTO :RESETTEMPELEMENTIMMUNESLOOP
)
GOTO :EOF

:RESETTEMPABSORBS
SET /a ABSORBGILCOST = 0
SET /a ABSORBITEMCOST = 0
SET /a TEMP2ABSORBTOT = %TEMPABSORBTOT%
IF %TEMPABSORBTOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESETTEMPABSORBSLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP2ABSORB%COUNT%=!TEMPABSORB%COUNT%!
IF %COUNT% LSS %TEMPABSORBTOT% (
	GOTO :RESETTEMPABSORBSLOOP
)
GOTO :EOF

:RESETTEMPSTATUSIMMUNES
SET /a STATUSIMMUNEGILCOST = 0
SET /a STATUSIMMUNEITEMCOST = 0
SET /a TEMP2STATUSIMMUNETOT = %TEMPSTATUSIMMUNETOT%
IF %TEMPSTATUSIMMUNETOT% EQU 0 (
	GOTO :EOF
)
SET /a COUNT = 0
:RESETTEMPSTATUSIMMUNESLOOP
SET /a COUNT = %COUNT% + 1
SET TEMP2STATUSIMMUNE%COUNT%=!TEMPSTATUSIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPSTATUSIMMUNETOT% (
	GOTO :RESETTEMPSTATUSIMMUNESLOOP
)
GOTO :EOF


:INITIALBASERESISTANCESET
SET /a NEWWEAKNESSTOT = 0
SET /a TEMPWEAKNESSTOT = !ARMOUR%BASECHOICE%WEAKNESSNUM!
SET /a TEMPSTRENGTHTOT = !ARMOUR%BASECHOICE%STRENGTHNUM!
SET /a TEMPELEMENTIMMUNETOT = !ARMOUR%BASECHOICE%ELEMENTIMMUNENUM!
SET /a TEMPABSORBTOT = !ARMOUR%BASECHOICE%ABSORBNUM!
SET /a TEMPSTATUSIMMUNETOT = !ARMOUR%BASECHOICE%STATUSIMMUNENUM!
SET /a COUNT = 0
IF %TEMPWEAKNESSTOT% EQU 0 (
	GOTO :INITIALBASERESISTANCESET2
)
:INITIALBASERESISTANCESETLOOP1
SET /a COUNT = %COUNT% + 1
SET TEMPWEAKNESS%COUNT%=!ARMOUR%BASECHOICE%WEAKNESS%COUNT%!
IF %COUNT% LSS %TEMPWEAKNESSTOT% (
	GOTO :INITIALBASERESISTANCESETLOOP1
)
:INITIALBASERESISTANCESET2
SET /a COUNT = 0
IF %TEMPSTRENGTHTOT% EQU 0 (
	GOTO :INITIALBASERESISTANCESET3
)
:INITIALBASERESISTANCESETLOOP2
SET /a COUNT = %COUNT% + 1
SET TEMPSTRENGTH%COUNT%=!ARMOUR%BASECHOICE%STRENGTH%COUNT%!
IF %COUNT% LSS %TEMPSTRENGTHTOT% (
	GOTO :INITIALBASERESISTANCESETLOOP2
)
:INITIALBASERESISTANCESET3
SET /a COUNT = 0
IF %TEMPELEMENTIMMUNETOT% EQU 0 (
	GOTO :INITIALBASERESISTANCESET4
)
:INITIALBASERESISTANCESETLOOP3
SET /a COUNT = %COUNT% + 1
SET TEMPELEMENTIMMUNE%COUNT%=!ARMOUR%BASECHOICE%ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPELEMENTIMMUNETOT% (
	GOTO :INITIALBASERESISTANCESETLOOP3
)
:INITIALBASERESISTANCESET4
SET /a COUNT = 0
IF %TEMPABSORBTOT% EQU 0 (
	GOTO :INITIALBASERESISTANCESET5
)
:INITIALBASERESISTANCESETLOOP4
SET /a COUNT = %COUNT% + 1
SET TEMPABSORB%COUNT%=!ARMOUR%BASECHOICE%ABSORB%COUNT%!
IF %COUNT% LSS %TEMPABSORBTOT% (
	GOTO :INITIALBASERESISTANCESETLOOP4
)
:INITIALBASERESISTANCESET5
SET /a COUNT = 0
IF %TEMPSTATUSIMMUNETOT% EQU 0 (
	GOTO :EOF
)
:INITIALBASERESISTANCESETLOOP5
SET /a COUNT = %COUNT% + 1
SET TEMPSTATUSIMMUNE%COUNT%=!ARMOUR%BASECHOICE%STATUSIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPSTATUSIMMUNETOT% (
	GOTO :INITIALBASERESISTANCESETLOOP5
)
GOTO :EOF


:INITIALCUSTOMRESISTANCESET
SET /a TEMP = %ARMOURTOTAL% + %SLOTNUM%
SET /a NEWWEAKNESSTOT = 0
SET /a TEMPWEAKNESSTOT = !ARMOUR%TEMP%WEAKNESSNUM!
SET /a TEMPSTRENGTHTOT = !ARMOUR%TEMP%STRENGTHNUM!
SET /a TEMPELEMENTIMMUNETOT = !ARMOUR%TEMP%ELEMENTIMMUNENUM!
SET /a TEMPABSORBTOT = !ARMOUR%TEMP%ABSORBNUM!
SET /a TEMPSTATUSIMMUNETOT = !ARMOUR%TEMP%STATUSIMMUNENUM!
SET /a COUNT = 0
IF %TEMPWEAKNESSTOT% EQU 0 (
	GOTO :INITIALCUSTOMRESISTANCESET2
)
:INITIALCUSTOMRESISTANCESETLOOP1
SET /a COUNT = %COUNT% + 1
SET TEMPWEAKNESS%COUNT%=!ARMOUR%TEMP%WEAKNESS%COUNT%!
IF %COUNT% LSS %TEMPWEAKNESSTOT% (
	GOTO :INITIALCUSTOMRESISTANCESETLOOP1
)
:INITIALCUSTOMRESISTANCESET2
SET /a COUNT = 0
IF %TEMPSTRENGTHTOT% EQU 0 (
	GOTO :INITIALCUSTOMRESISTANCESET3
)
:INITIALCUSTOMRESISTANCESETLOOP2
SET /a COUNT = %COUNT% + 1
SET TEMPSTRENGTH%COUNT%=!ARMOUR%TEMP%STRENGTH%COUNT%!
IF %COUNT% LSS %TEMPSTRENGTHTOT% (
	GOTO :INITIALCUSTOMRESISTANCESETLOOP2
)
:INITIALCUSTOMRESISTANCESET3
SET /a COUNT = 0
IF %TEMPELEMENTIMMUNETOT% EQU 0 (
	GOTO :INITIALCUSTOMRESISTANCESET4
)
:INITIALCUSTOMRESISTANCESETLOOP3
SET /a COUNT = %COUNT% + 1
SET TEMPELEMENTIMMUNE%COUNT%=!ARMOUR%TEMP%ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPELEMENTIMMUNETOT% (
	GOTO :INITIALCUSTOMRESISTANCESETLOOP3
)
:INITIALCUSTOMRESISTANCESET4
SET /a COUNT = 0
IF %TEMPABSORBTOT% EQU 0 (
	GOTO :INITIALCUSTOMRESISTANCESET5
)
:INITIALCUSTOMRESISTANCESETLOOP4
SET /a COUNT = %COUNT% + 1
SET TEMPABSORB%COUNT%=!ARMOUR%TEMP%ABSORB%COUNT%!
IF %COUNT% LSS %TEMPABSORBTOT% (
	GOTO :INITIALCUSTOMRESISTANCESETLOOP4
)
:INITIALCUSTOMRESISTANCESET5
SET /a COUNT = 0
IF %TEMPSTATUSIMMUNETOT% EQU 0 (
	GOTO :EOF
)
:INITIALCUSTOMRESISTANCESETLOOP5
SET /a COUNT = %COUNT% + 1
SET TEMPSTATUSIMMUNE%COUNT%=!ARMOUR%TEMP%STATUSIMMUNE%COUNT%!
IF %COUNT% LSS %TEMPSTATUSIMMUNETOT% (
	GOTO :INITIALCUSTOMRESISTANCESETLOOP5
)
GOTO :EOF

:CONFIRMATION
CLS
CALL :INITIALISEBACKS
ECHO.
ECHO %BLACKSMITHNAME%: Ok, here's a summary^^!
ECHO.
ECHO. Armour Name:    %ARMOURNAME%
ECHO. Endurane Bonus: %TEMPEND%
ECHO. Spirit Bonus:   %TEMPSPR%
ECHO. Evasion Bonus:  %TEMPEVA%
ECHO. Speed Bonus:    %TEMPSPD%
ECHO.
IF %TEMP2WEAKNESSTOT% EQU 0 (
	GOTO :CONFIRMATIONWEAKNESSLOOP1END
)
SET /a COUNT = 0
:CONFIRMATIONWEAKNESSLOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Weakness to     !TEMP2WEAKNESS%COUNT%!
IF %COUNT% LSS %TEMP2WEAKNESSTOT% (
	GOTO :CONFIRMATIONWEAKNESSLOOP1
)
ECHO.
:CONFIRMATIONWEAKNESSLOOP1END
IF %TEMP2STRENGTHTOT% EQU 0 (
	GOTO :CONFIRMATIONSTRENGTHLOOP1END
)
SET /a COUNT = 0
:CONFIRMATIONSTRENGTHLOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Resistance to   !TEMP2STRENGTH%COUNT%!
IF %COUNT% LSS %TEMP2STRENGTHTOT% (
	GOTO :CONFIRMATIONSTRENGTHLOOP1
)
ECHO.
:CONFIRMATIONSTRENGTHLOOP1END
IF %TEMP2ELEMENTIMMUNETOT% EQU 0 (
	GOTO :CONFIRMATIONELEMENTIMMUNELOOP1END
)
SET /a COUNT = 0
:CONFIRMATIONELEMENTIMMUNELOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Immunity to     !TEMP2ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS %TEMP2ELEMENTIMMUNETOT% (
	GOTO :CONFIRMATIONELEMENTIMMUNELOOP1
)
ECHO.
:CONFIRMATIONELEMENTIMMUNELOOP1END
IF %TEMP2ABSORBTOT% EQU 0 (
	GOTO :CONFIRMATIONABSORBLOOP1END
)
SET /a COUNT = 0
:CONFIRMATIONABSORBLOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Absorption of   !TEMP2ABSORB%COUNT%!
IF %COUNT% LSS %TEMP2ABSORBTOT% (
	GOTO :CONFIRMATIONABSORBLOOP1
)
ECHO.
:CONFIRMATIONABSORBLOOP1END
IF %TEMP2STATUSIMMUNETOT% EQU 0 (
	GOTO :CONFIRMATIONSTATUSIMMUNELOOP1END
)
SET /a COUNT = 0
:CONFIRMATIONSTATUSIMMUNELOOP1
SET /a COUNT = %COUNT% + 1
ECHO. Immunity to     !TEMP2STATUSIMMUNE%COUNT%!
IF %COUNT% LSS %TEMP2STATUSIMMUNETOT% (
	GOTO :CONFIRMATIONSTATUSIMMUNELOOP1
)
ECHO.
:CONFIRMATIONSTATUSIMMUNELOOP1END
ECHO %BLACKSMITHNAME%: It'll cost you %GILCOST% Gil
IF %ENDSTONECOST% EQU 1 (
	ECHO             %ENDSTONECOST% !SPECIALITEM%ENDSTONEID%NAME!
) ELSE IF %ENDSTONECOST% GTR 1 (
	ECHO             %ENDSTONECOST% !SPECIALITEM%ENDSTONEID%NAME!s
)
IF %SPRSTONECOST% EQU 1 (
	ECHO             %SPRSTONECOST% !SPECIALITEM%SPRSTONEID%NAME!
) ELSE IF %SPRSTONECOST% GTR 1  (
	ECHO             %SPRSTONECOST% !SPECIALITEM%SPRSTONEID%NAME!s
)
IF %EVASTONECOST% EQU 1 (
	ECHO             %EVASTONECOST% !SPECIALITEM%EVASTONEID%NAME!
) ELSE IF %EVASTONECOST% GTR 1  (
	ECHO             %EVASTONECOST% !SPECIALITEM%EVASTONEID%NAME!s
)
IF %SPDSTONECOST% EQU 1 (
	ECHO             %SPDSTONECOST% !SPECIALITEM%SPDSTONEID%NAME!
) ELSE IF %SPDSTONECOST% GTR 1  (
	ECHO             %SPDSTONECOST% !SPECIALITEM%SPDSTONEID%NAME!s
)
IF %WEAKNESSITEMCOST% EQU 1 (
	ECHO             %WEAKNESSITEMCOST% !SPECIALITEM%WEAKPOWID%NAME!
) ELSE IF %WEAKNESSITEMCOST% GTR 1  (
	ECHO             %WEAKNESSITEMCOST% !SPECIALITEM%WEAKPOWID%NAME!s
)
IF %STRENGTHITEMCOST% EQU 1 (
	ECHO             %STRENGTHITEMCOST% !SPECIALITEM%RESPOWID%NAME!
) ELSE IF %STRENGTHITEMCOST% GTR 1  (
	ECHO             %STRENGTHITEMCOST% !SPECIALITEM%RESPOWID%NAME!s
)
IF %ELEMENTIMMUNEITEMCOST% EQU 1 (
	ECHO             %ELEMENTIMMUNEITEMCOST% !SPECIALITEM%ELEIMMPOWID%NAME!
) ELSE IF %ELEMENTIMMUNEITEMCOST% GTR 1  (
	ECHO             %ELEMENTIMMUNEITEMCOST% !SPECIALITEM%ELEIMMPOWID%NAME!s
)
IF %ABSORBITEMCOST% EQU 1 (
	ECHO             %ABSORBITEMCOST% !SPECIALITEM%ABSPOWID%NAME!
) ELSE IF %ABSORBITEMCOST% GTR 1  (
	ECHO             %ABSORBITEMCOST% !SPECIALITEM%ABSPOWID%NAME!s
)
IF %STATUSIMMUNEITEMCOST% EQU 1 (
	ECHO             %STATUSIMMUNEITEMCOST% !SPECIALITEM%STATIMMPOWID%NAME!
) ELSE IF %STATUSIMMUNEITEMCOST% GTR 1  (
	ECHO             %STATUSIMMUNEITEMCOST% !SPECIALITEM%STATIMMPOWID%NAME!s
)
ECHO.
ECHO %BLACKSMITHNAME%: Would you like to create this armour?
ECHO.
ECHO. 1 - Yes
ECHO. 2 - No
ECHO. 0 - Back
ECHO.
:CONFIRMATIONCHOICE
SET /P CONFIRMATIONCHOICE=
ECHO.
IF "%CONFIRMATIONCHOICE%" EQU "1" (
	GOTO :EOF
) ELSE IF "%CONFIRMATIONCHOICE%" EQU "2" (
	GOTO :EOF
) ELSE IF "%CONFIRMATIONCHOICE%" EQU "0" (
	SET /a CONFIRMATIONBACK = 1
) ELSE (
	GOTO :CONFIRMATIONCHOICE
)
GOTO :EOF



:CREATEARMOUR
SET /a ARMOURCRAFTED = %ARMOURCRAFTED% + 1
SET /a EQUIPMENTCRAFTED = %EQUIPMENTCRAFTED% + 1
CALL :REDUCERESOURCES
SET /a ARMOURID = %ARMOURTOTAL% + %SLOTNUM%
SET ARMOUR%ARMOURID%NAME=%ARMOURNAME%
CALL :ARMOURNAMELENGTH
SET /a ARMOUR%ARMOURID%END = %TEMPEND%
SET /a ARMOUR%ARMOURID%SPR = %TEMPSPR%
SET /a ARMOUR%ARMOURID%EVA = %TEMPEVA%
SET /a ARMOUR%ARMOURID%SPD = %TEMPSPD%
SET /a ARMOUR%ARMOURID%WEAKNESSNUM = %TEMP2WEAKNESSTOT%
SET /a ARMOUR%ARMOURID%STRENGTHNUM = %TEMP2STRENGTHTOT%
SET /a ARMOUR%ARMOURID%ELEMENTIMMUNENUM = %TEMP2ELEMENTIMMUNETOT%
SET /a ARMOUR%ARMOURID%ABSORBNUM = %TEMP2ABSORBTOT%
SET /a ARMOUR%ARMOURID%STATUSIMMUNENUM = %TEMP2STATUSIMMUNETOT%
SET /a COUNT = 0
:SETARMOURVARSWEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
SET ARMOUR%ARMOURID%WEAKNESS%COUNT%=!TEMP2WEAKNESS%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%WEAKNESSNUM! (
	GOTO :SETARMOURVARSWEAKNESSLOOP
)
SET /a COUNT = 0
:SETARMOURVARSSTRENGTHLOOP
SET /a COUNT = %COUNT% + 1
SET ARMOUR%ARMOURID%STRENGTH%COUNT%=!TEMP2STRENGTH%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%STRENGTHNUM! (
	GOTO :SETARMOURVARSSTRENGTHLOOP
)
SET /a COUNT = 0
:SETARMOURVARSELEMENTIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET ARMOUR%ARMOURID%ELEMENTIMMUNE%COUNT%=!TEMP2ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! (
	GOTO :SETARMOURVARSELEMENTIMMUNELOOP
)
SET /a COUNT = 0
:SETARMOURVARSABSORBLOOP
SET /a COUNT = %COUNT% + 1
SET ARMOUR%ARMOURID%ABSORB%COUNT%=!TEMP2ABSORB%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%ABSORBNUM! (
	GOTO :SETARMOURVARSABSORBLOOP
)
SET /a COUNT = 0
:SETARMOURVARSSTATUSIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET ARMOUR%ARMOURID%STATUSIMMUNE%COUNT%=!TEMP2STATUSIMMUNE%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%STATUSIMMUNENUM! (
	GOTO :SETARMOURVARSSTATUSIMMUNELOOP
)
ECHO SET ARMOUR%ARMOURID%NAME=!ARMOUR%ARMOURID%NAME!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat"
ECHO SET /a ARMOUR%ARMOURID%NAMELENGTH = !ARMOUR%ARMOURID%NAMELENGTH! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat"
ECHO SET ARMOUR%ARMOURID%NAME=!ARMOUR%ARMOURID%NAME!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%END = !ARMOUR%ARMOURID%END! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%SPR = !ARMOUR%ARMOURID%SPR! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%EVA = !ARMOUR%ARMOURID%EVA! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%SPD = !ARMOUR%ARMOURID%SPD! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%WEAKNESSNUM = !ARMOUR%ARMOURID%WEAKNESSNUM! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%STRENGTHNUM = !ARMOUR%ARMOURID%STRENGTHNUM! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%ELEMENTIMMUNENUM = !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%ABSORBNUM = !ARMOUR%ARMOURID%ABSORBNUM! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET /a ARMOUR%ARMOURID%STATUSIMMUNENUM = !ARMOUR%ARMOURID%STATUSIMMUNENUM! >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF !ARMOUR%ARMOURID%WEAKNESSNUM! EQU 0 (
	GOTO :CREATEARMOURWEAKNESSLOOPEND
)
SET /a COUNT = 0
:CREATEARMOURWEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET ARMOUR%ARMOURID%WEAKNESS%COUNT%=!ARMOUR%ARMOURID%WEAKNESS%COUNT%!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %COUNT% LSS !ARMOUR%ARMOURID%WEAKNESSNUM! (
	GOTO :CREATEARMOURWEAKNESSLOOP
)
:CREATEARMOURWEAKNESSLOOPEND
IF !ARMOUR%ARMOURID%STRENGTHNUM! EQU 0 (
	GOTO :CREATEARMOURSTRENGTHLOOPEND
)
SET /a COUNT = 0
:CREATEARMOURSTRENGTHLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET ARMOUR%ARMOURID%STRENGTH%COUNT%=!ARMOUR%ARMOURID%STRENGTH%COUNT%!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %COUNT% LSS !ARMOUR%ARMOURID%STRENGTHNUM! (
	GOTO :CREATEARMOURSTRENGTHLOOP
)
:CREATEARMOURSTRENGTHLOOPEND
IF !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! EQU 0 (
	GOTO :CREATEARMOURELEMENTIMMUNELOOPEND
)
SET /a COUNT = 0
:CREATEARMOURELEMENTIMMUNELOOP
SET /a COUNT = %COUNT% + 1
ECHO SET ARMOUR%ARMOURID%ELEMENTIMMUNE%COUNT%=!ARMOUR%ARMOURID%ELEMENTIMMUNE%COUNT%!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %COUNT% LSS !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! (
	GOTO :CREATEARMOURELEMENTIMMUNELOOP
)
:CREATEARMOURELEMENTIMMUNELOOPEND
IF !ARMOUR%ARMOURID%ABSORBNUM! EQU 0 (
	GOTO :CREATEARMOURABSORBLOOPEND
)
SET /a COUNT = 0
:CREATEARMOURABSORBLOOP
SET /a COUNT = %COUNT% + 1
ECHO SET ARMOUR%ARMOURID%ABSORB%COUNT%=!ARMOUR%ARMOURID%ABSORB%COUNT%!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %COUNT% LSS !ARMOUR%ARMOURID%ABSORBNUM! (
	GOTO :CREATEARMOURABSORBLOOP
)
:CREATEARMOURABSORBLOOPEND
IF !ARMOUR%ARMOURID%STATUSIMMUNENUM! EQU 0 (
	GOTO :CREATEARMOURSTATUSIMMUNELOOPEND
)
SET /a COUNT = 0
:CREATEARMOURSTATUSIMMUNELOOP
SET /a COUNT = %COUNT% + 1
ECHO SET ARMOUR%ARMOURID%STATUSIMMUNE%COUNT%=!ARMOUR%ARMOURID%STATUSIMMUNE%COUNT%!>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %COUNT% LSS !ARMOUR%ARMOURID%STATUSIMMUNENUM! (
	GOTO :CREATEARMOURSTATUSIMMUNELOOP
)
:CREATEARMOURSTATUSIMMUNELOOPEND
GOTO :EOF


:ARMOURNAMELENGTH
SET /a ARMOUR%ARMOURID%NAMELENGTH = 0
:ARMOURNAMELENGTHLOOPSTART
SET /a ARMOUR%ARMOURID%NAMELENGTH += 1
SET TEMP1=!ARMOUR%ARMOURID%NAMELENGTH!
SET SUBSTR=!ARMOUR%ARMOURID%NAME:~%TEMP1%,1!
IF "%SUBSTR%" NEQ "" (
	GOTO :ARMOURNAMELENGTHLOOPSTART
) ELSE (
	SET /a TEMPCOUNT = !ARMOUR%ARMOURID%NAMELENGTH! + 1
	SET SUBSTR=!ARMOUR%ARMOURID%NAME:~%TEMPCOUNT%,1!
	IF "%SUBSTR%" NEQ "" (
		GOTO :ARMOURNAMELENGTHLOOPSTART
	)
)
GOTO :EOF

:REDUCERESOURCES
SET /a PLAYERGIL = %PLAYERGIL% - %GILCOST%
IF %ARMOUREXIST% EQU 0 (
	SET /a PLAYERARMOUR%BASECHOICE%NUM = !PLAYERARMOUR%BASECHOICE%NUM! - 1
)
SET /a PLAYERSPECIALITEM%ENDSTONEID%NUM = !PLAYERSPECIALITEM%ENDSTONEID%NUM! - %ENDSTONECOST%
SET /a PLAYERSPECIALITEM%SPRSTONEID%NUM = !PLAYERSPECIALITEM%SPRSTONEID%NUM! - %SPRSTONECOST%
SET /a PLAYERSPECIALITEM%EVASTONEID%NUM = !PLAYERSPECIALITEM%EVASTONEID%NUM! - %EVASTONECOST%
SET /a PLAYERSPECIALITEM%SPDSTONEID%NUM = !PLAYERSPECIALITEM%SPDSTONEID%NUM! - %SPDSTONECOST%
SET /a PLAYERSPECIALITEM%WEAKPOWID%NUM = !PLAYERSPECIALITEM%WEAKPOWID%NUM! - %WEAKNESSITEMCOST%
SET /a PLAYERSPECIALITEM%RESPOWID%NUM = !PLAYERSPECIALITEM%RESPOWID%NUM! - %STRENGTHITEMCOST%
SET /a PLAYERSPECIALITEM%ELEIMMPOWID%NUM = !PLAYERSPECIALITEM%ELEIMMPOWID%NUM! - %ELEMENTIMMUNEITEMCOST%
SET /a PLAYERSPECIALITEM%ABSPOWID%NUM = !PLAYERSPECIALITEM%ABSPOWID%NUM! - %ABSORBITEMCOST%
SET /a PLAYERSPECIALITEM%STATIMMPOWID%NUM = !PLAYERSPECIALITEM%STATIMMPOWID%NUM! - %STATUSIMMUNEITEMCOST%
GOTO :EOF


:EQUIP
CLS
ECHO.
ECHO %BLACKSMITHNAME%: You have successfully customised the !ARMOUR%ARMOURID%NAME!^^!
ECHO.
ECHO             Would like like to equip it now?
ECHO.
ECHO. 1 - Yes
ECHO. 0 - No
ECHO.
:EQUIPCHOICE
SET /P EQUIPCHOICE=
ECHO.
IF "%EQUIPCHOICE%" EQU "1" (
	GOTO :EQUIPTRUE
) ELSE IF "%EQUIPCHOICE%" EQU "0" (
	GOTO :EQUIPFALSE
) ELSE (
	GOTO :EQUIPCHOICE
)
GOTO :EOF

:EQUIPTRUE
SET PLAYERARMOUR=!ARMOUR%ARMOURID%NAME!
SET /a PLAYERARMOURID = %ARMOURID%
SET /a PLAYEREQUIPEND = !ARMOUR%ARMOURID%END!
SET /a PLAYEREQUIPSPR = !ARMOUR%ARMOURID%SPR!
SET /a PLAYEREQUIPEVA = !ARMOUR%ARMOURID%EVA!
SET /a PLAYEREQUIPSPD = !ARMOUR%ARMOURID%SPD!
IF !ARMOUR%ARMOURID%WEAKNESSNUM! EQU 0 (
	GOTO :ENDEQUIPWEAKNESSLOOP
)
SET /a COUNT = 0
:EQUIPWEAKNESSLOOP
SET /a COUNT = %COUNT% + 1
SET PLAYERWEAKNESS%COUNT%=!ARMOUR%ARMOURID%WEAKNESS%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%WEAKNESSNUM! (
	GOTO :EQUIPWEAKNESSLOOP
)
:ENDEQUIPWEAKNESSLOOP
IF !ARMOUR%ARMOURID%STRENGTHNUM! EQU 0 (
	GOTO :ENDEQUIPSTRENGTHLOOP
)
SET /a COUNT = 0
:EQUIPSTRENGTHLOOP
SET /a COUNT = %COUNT% + 1
SET PLAYERSTRENGTH%COUNT%=!ARMOUR%ARMOURID%STRENGTH%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%STRENGTHNUM! (
	GOTO :EQUIPSTRENGTHLOOP
)
:ENDEQUIPSTRENGTHLOOP
IF !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! EQU 0 (
	GOTO :ENDEQUIPELEMENTIMMUNELOOP
)
SET /a COUNT = 0
:EQUIPELEMENTIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET PLAYERELEMENTIMMUNE%COUNT%=!ARMOUR%ARMOURID%ELEMENTIMMUNE%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%ELEMENTIMMUNENUM! (
	GOTO :EQUIPELEMENTIMMUNELOOP
)
:ENDEQUIPELEMENTIMMUNELOOP
IF !ARMOUR%ARMOURID%ABSORBNUM! EQU 0 (
	GOTO :ENDEQUIPABSORBLOOP
)
SET /a COUNT = 0
:EQUIPABSORBLOOP
SET /a COUNT = %COUNT% + 1
SET PLAYERABSORB%COUNT%=!ARMOUR%ARMOURID%ABSORB%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%ABSORBNUM! (
	GOTO :EQUIPABSORBLOOP
)
:ENDEQUIPABSORBLOOP
IF !ARMOUR%ARMOURID%STATUSIMMUNENUM! EQU 0 (
	GOTO :ENDEQUIPSTATUSIMMUNELOOP
)
SET /a COUNT = 0
:EQUIPSTATUSIMMUNELOOP
SET /a COUNT = %COUNT% + 1
SET PLAYERSTATUSIMMUNE%COUNT%=!ARMOUR%ARMOURID%STATUSIMMUNE%COUNT%!
IF %COUNT% LSS !ARMOUR%ARMOURID%STATUSIMMUNENUM! (
	GOTO :EQUIPSTATUSIMMUNELOOP
)
:ENDEQUIPSTATUSIMMUNELOOP
ECHO.
ECHO You have equipped the %PLAYERARMOUR%
ECHO.
pause
GOTO :EOF

:EQUIPFALSE
pause
IF %ARMOUREXIST% EQU 1 (
	IF %PLAYERARMOURID% EQU %ARMOURID% (
		CALL :UNEQUIPARMOUR
	)
) ELSE (
	IF %PLAYERARMOURID% EQU %BASECHOICE% (
		IF !PLAYERARMOUR%PLAYERARMOURID%NUM! EQU 0 (
			CALL :UNEQUIPARMOUR
		)
	)
)
GOTO :EOF
		


:UNEQUIPARMOUR
SET PLAYERARMOUR=NONE
SET /a PLAYERARMOURID = 0
SET /a PLAYEREQUIPSTR = 0
SET /a PLAYEREQUIPMAG = 0
SET /a PLAYEREQUIPACC = 0
SET /a PLAYERWEAKNESSNUM = 0
SET /a PLAYERSTRENGTHNUM = 0
SET /a PLAYERELEMENTIMMUNENUM = 0
SET /a PLAYERABSORBNUM = 0
SET /a PLAYERSTATUSIMMUNENUM = 0
GOTO :EOF




:INITIALISEBACKS
SET /a NAMEBACK = 0
SET /a BASEBACK = 0
SET /a STATINCREASEBACK = 0
SET /a RESISTANCESBACK = 0
SET /a CONFIRMATIONBACK = 0
GOTO :EOF





:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF