:SLOT
SET /a AVAILABLESLOTS = %PLAYERLVL%/10
IF %AVAILABLESLOTS% GTR 9 (
	SET /a AVAILABLESLOTS = 9
)
IF EXIST "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat" (
	CALL "%CUSTOMARMOURRESOURCEPATH%\Temp\customarourlist.bat"
)
CLS
ECHO.
IF %AVAILABLESLOTS% EQU 0 (
	ECHO %BLACKSMITHNAME%: Sorry you don't have any armour slots yet
	ECHO.
	SET /a SLOTNUM = 0
	pause
	GOTO :EOF
) ELSE (
	ECHO %BLACKSMITHNAME%: Here's a list of the custom armour that you have
)
ECHO.
ECHO            Select a piece of custom armour to destroy
ECHO.
SET /a COUNT = 0
:SLOTSLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP = %ARMOURTOTAL% + %COUNT%
IF %AVAILABLESLOTS% GEQ %COUNT% (
ECHO. %COUNT% - !ARMOUR%TEMP%NAME!
)
IF %COUNT% LSS %AVAILABLESLOTS% (
	GOTO :SLOTSLOOP
)
ECHO. 0 - Back
ECHO.
:SLOTCHOICE
SET /P SLOTNUM=
ECHO.
IF "%SLOTNUM%" EQU "" (
	GOTO :SLOTCHOICE
)
IF %SLOTNUM% GTR %AVAILABLESLOTS% (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% LSS 0 (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% EQU 0 (
	GOTO :EOF
)
SET /a TEMP = %ARMOURTOTAL% + %SLOTNUM%
IF DEFINED ARMOUR%TEMP%NAME (
	CALL :CONFIRMATION
) ELSE (
	GOTO :SLOTCHOICE
)
GOTO :SLOT

:CONFIRMATION
CLS
ECHO.
CALL "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
IF %PLAYERARMOURID% EQU %TEMP% (
	ECHO %BLACKSMITHNAME%: You have this armour equipped at the moment so be careful^^!
	ECHO.
)
ECHO %BLACKSMITHNAME%: You won't get anything back for destroying this armour:
ECHO.
ECHO             Are you sure you want to destroy it?
ECHO.
:CONFIRMATIONQUESTION
ECHO. 1 - Yes
ECHO. 0 - No
ECHO.
:CONFIRMATIONCHOICE
SET /P CONFIRMATIONCHOICE=
ECHO.
IF "%CONFIRMATIONCHOICE%" EQU "1" (
	CALL :SALVAGETRUE
) ELSE IF "%CONFIRMATIONCHOICE%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :CONFIRMATIONCHOICE
)
GOTO :EOF

:SALVAGETRUE
IF %PLAYERARMOURID% EQU %TEMP% (
	CALL :UNEQUIPARMOUR
)
DEL "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmour%SLOTNUM%.bat"
ECHO SET ARMOUR%TEMP%NAME=>>"%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat"
ECHO SET ARMOUR%TEMP%NAMELENGTH= >> "%CUSTOMARMOURRESOURCEPATH%\Temp\customarmourlist.bat"
CLS.
ECHO.
ECHO %BLACKSMITHNAME%: Successfully destroyed^^!
ECHO.
pause
GOTO :EOF


:UNEQUIPARMOUR
SET PLAYERARMOUR=NONE
SET /a PLAYERARMOURID = 0
SET /a PLAYEREQUIPEND = 0
SET /a PLAYEREQUIPSPR = 0
SET /a PLAYEREQUIPEVA = 0
SET /a PLAYEREQUIPSPD = 0
SET /a PLAYERWEAKNESSNUM = 0
SET /a PLAYERSTRENGTHNUM = 0
SET /a PLAYERELEMENTIMMUNENUM = 0
SET /a PLAYERABSORBNUM = 0
SET /a PLAYERSTATUSIMMUNENUM = 0
GOTO :EOF



