:SLOT
REM SET /a AVAILABLESLOTS = %PLAYERLVL%/10
SET /a AVAILABLESLOTS = 5
IF %AVAILABLESLOTS% GTR 9 (
	SET /a AVAILABLESLOTS = 9
)
IF EXIST "%CUSTOMWEAPONRESOURCEPATH%\Temp\customweaponlist.bat" (
	CALL "%CUSTOMWEAPONRESOURCEPATH%\Temp\customweaponlist.bat"
)
CLS
ECHO.
IF %AVAILABLESLOTS% EQU 0 (
	ECHO %BLACKSMITHNAME%: Sorry you don't have any weapon slots yet
	ECHO.
	SET /a SLOTNUM = 0
	pause
	GOTO :EOF
) ELSE (
	ECHO %BLACKSMITHNAME%: Here are the custom weapons that you currently have
)
ECHO.
ECHO            Select a custom weapon slot
ECHO.
SET /a COUNT = 0
:SLOTSLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP = %WEAPONTOTAL% + %COUNT%
IF %AVAILABLESLOTS% GEQ %COUNT% (
ECHO. %COUNT% - !WEAPON%TEMP%NAME!
)
IF %COUNT% LSS %AVAILABLESLOTS% (
	GOTO :SLOTSLOOP
)
ECHO. 0 - Back
ECHO.
:SLOTCHOICE
SET /P SLOTNUM=
ECHO.
IF "%SLOTNUM%" EQU "" (
	GOTO :SLOTCHOICE
)
IF %SLOTNUM% GTR %AVAILABLESLOTS% (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% LSS 0 (
	GOTO :SLOTCHOICE
) ELSE IF %SLOTNUM% EQU 0 (
	GOTO :EOF
)
SET /a TEMP = %WEAPONTOTAL% + %SLOTNUM%
IF DEFINED WEAPON%TEMP%NAME (
	CALL :CONFIRMATION
) ELSE (
	GOTO :SLOTCHOICE
)
GOTO :SLOT

:CONFIRMATION
CLS
ECHO.
CALL "%CUSTOMWEAPONRESOURCEPATH%\Temp\customweapon%SLOTNUM%.bat"
IF %PLAYERWEAPONID% EQU %TEMP% (
	ECHO %BLACKSMITHNAME%: You have this weapon equipped at the moment so be careful^^!
	ECHO.
)
IF !WEAPON%TEMP%SKILLTOT! EQU 0 (
	ECHO %BLACKSMITHNAME%: This weapon doesn't have any skills so you'll get nothing for salvaging it
	ECHO.
	ECHO             Are you sure you want to?
	ECHO.
	GOTO :CONFIRMATIONQUESTION
)
ECHO %BLACKSMITHNAME%: You can salvage the following items from this weapon:
ECHO.
SET /a COUNT = 0
:CONFIRMATIONLOOPSTART
SET /a COUNT = %COUNT% + 1
SET /a TEMP2 = !WEAPON%TEMP%SKILL%COUNT%!
SET /a TEMP3 = %SKILLSTONESTART% + %TEMP2%
ECHO. 1 !SPECIALITEM%TEMP3%NAME!
IF %COUNT% LSS !WEAPON%TEMP%SKILLTOT! (
	GOTO :CONFIRMATIONLOOPSTART
)
ECHO.
ECHO %BLACKSMITHNAME%: Are you sure you want to salvage this weapon?
ECHO.
:CONFIRMATIONQUESTION
ECHO. 1 - Yes
ECHO. 0 - No
ECHO.
:CONFIRMATIONCHOICE
SET /P CONFIRMATIONCHOICE=
ECHO.
IF "%CONFIRMATIONCHOICE%" EQU "1" (
	CALL :SALVAGETRUE
) ELSE IF "%CONFIRMATIONCHOICE%" EQU "0" (
	GOTO :EOF
) ELSE (
	GOTO :CONFIRMATIONCHOICE
)
GOTO :EOF

:SALVAGETRUE
IF %PLAYERWEAPONID% EQU %TEMP% (
	CALL :UNEQUIPWEAPON
)
SET /a COUNT = 0
:SALVAGELOOPSTART
SET /a COUNT = %COUNT% + 1
SET /a TEMP2 = !WEAPON%TEMP%SKILL%COUNT%!
SET /a TEMP3 = %SKILLSTONESTART% + %TEMP2%
SET /a PLAYERSPECIALITEM%TEMP3%NUM = !PLAYERSPECIALITEM%TEMP3%NUM! + 1
IF %COUNT% LSS !WEAPON%TEMP%SKILLTOT! (
	GOTO :SALVAGELOOPSTART
)
DEL "%CUSTOMWEAPONRESOURCEPATH%\Temp\customweapon%SLOTNUM%.bat"
ECHO SET WEAPON%TEMP%NAME=>>"%CUSTOMWEAPONRESOURCEPATH%\Temp\customweaponlist.bat"
ECHO SET WEAPON%TEMP%NAMELENGTH= >> "%CUSTOMWEAPONRESOURCEPATH%\Temp\customweaponlist.bat"
CLS.
ECHO.
ECHO %BLACKSMITHNAME%: Successfully salvaged^^!
ECHO.
pause
GOTO :EOF


:UNEQUIPWEAPON
IF !WEAPON%PLAYERWEAPONID%SKILLTOT! EQU 0 (
	GOTO :UNEQUIPLOOPEND
)
SET /a COUNT = 0
:UNEQUIPLOOP
SET /a COUNT = %COUNT% + 1
SET /a TEMP2 = !WEAPON%PLAYERWEAPONID%SKILL%COUNT%!
IF !PLAYERSKILL%TEMP2%EARNED! EQU 0 (
	SET /a PLAYERSKILL%TEMP2%ENABLED = 0
)
IF %COUNT% LSS !WEAPON%PLAYERWEAPONID%SKILLTOT! (
	GOTO :UNEQUIPLOOP
)
:UNEQUIPLOOPEND
SET PLAYERWEAPON=NONE
SET /a PLAYERWEAPONID = 0
SET /a PLAYEREQUIPSTR = 0
SET /a PLAYEREQUIPMAG = 0
SET /a PLAYEREQUIPACC = 0
GOTO :EOF


