@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET /a REMOTEACCESS = 1
SET BLACKSMITHNAME=Blacksmith
SET RESOURCEPATH=D:\Users\NDSisson\Desktop\Desktop\Recent\Game\Resources
SET BLACKSMITHRESOURCEPATH=%RESOURCEPATH%\Blacksmith
SET CUSTOMWEAPONRESOURCEPATH=%RESOURCEPATH%\CustomWeapons
SET INITIALRESOURCEPATH=%RESOURCEPATH%\Setup\Initial
SET NEWRESOURCEPATH=%RESOURCEPATH%\Setup\New
SET DYNAMICRESOURCEPATH=%RESOURCEPATH%\Dynamic
SET /a PLAYERLVL = 40
SET /a PLAYERGIL = 10000
CALL "%INITIALRESOURCEPATH%\spellstats.bat"
CALL "%INITIALRESOURCEPATH%\skilllist.bat"
CALL "%INITIALRESOURCEPATH%\specials.bat"
CALL "%INITIALRESOURCEPATH%\specialitemlist.bat"
CALL "%INITIALRESOURCEPATH%\weaponstats.bat"
CALL "%INITIALRESOURCEPATH%\armourstats.bat"
CALL "%INITIALRESOURCEPATH%\accessorystats.bat"
CALL "%NEWRESOURCEPATH%\initialblacksmithstats.bat"
CALL "%NEWRESOURCEPATH%\playerequipstats.bat"
SET /a COUNT = 0
:WEAPONLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERWEAPON%COUNT%NUM = 1
IF %COUNT% LSS %WEAPONTOTAL% (
	GOTO :WEAPONLOOPSTART
)
SET /a COUNT = 0
:ARMOURLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERARMOUR%COUNT%NUM = 1
IF %COUNT% LSS %ARMOURTOTAL% (
	GOTO :ARMOURLOOPSTART
)
SET /a COUNT = 0
:ACCESSORYLOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERACCESSORY%COUNT%NUM = 1
IF %COUNT% LSS %ACCESSORYTOTAL% (
	GOTO :ACCESSORYLOOPSTART
)
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
SET /a PLAYERSPECIALITEM%COUNT%NUM = 10
IF %COUNT% LSS %SPECIALITEMTOTAL% (
	GOTO :LOOPSTART
)
SET TABS1=	
SET TABS2=		
SET TABS3=			
SET TABS4=				
SET TABS5=					
SET /a COUNT = 0
:LOOP
SET /a OLDCOUNT = %COUNT%
SET /a COUNT = %COUNT% + 1
SET SPACES%COUNT%=!SPACES%OLDCOUNT%! 
IF %COUNT% LSS 100 (
	GOTO :LOOP
)
CALL "%BLACKSMITHRESOURCEPATH%\enterblacksmith.bat"