IF %REMOTEACCESS% EQU 0 (
	CALL :SETLOCATION
) ELSE (
	SET /a REMOTEACCESS = 0
)
IF %TRAININGWELCOMESEEN% EQU 0 (
	CALL "%TRAININGRESOURCEPATH%\trainingwelcome.bat"
)
:SELECTENEMYID
CALL "%DYNAMICRESOURCEPATH%\dynamicenemylisttraining.bat"
IF %DYNAMICENEMYTOT% LSS 20 (
	CALL "%TRAININGRESOURCEPATH%\trainingdisplay.bat"
) ELSE (
	CLS
)
IF %DYNAMICENEMYTOT% EQU 0 (
	CALL :NOENEMIES
	GOTO :EOF
)
ECHO.
ECHO %TRAINERNAME%: Choose the enemy that you'd like to fight
ECHO.
SET /a COUNT=0
:LOOPSTART1
SET /a COUNT=%COUNT%+1
ECHO. %COUNT% - !DYNAMICENEMY%COUNT%NAME!
IF %COUNT% LSS %DYNAMICENEMYTOT% (
	GOTO :LOOPSTART1
)
ECHO. 0 - Back
ECHO.
:CHOICE
SET /P DYNAMICENEMYID=
ECHO.
IF "%DYNAMICENEMYID%" EQU "" (
	GOTO :CHOICE
)
IF %DYNAMICENEMYID% EQU 0 (
	CALL "%REMOTERESOURCEPATH%\training.bat"
	GOTO :EOF
) ELSE IF %DYNAMICENEMYID% GTR %DYNAMICENEMYTOT% (
	GOTO :CHOICE
) ELSE IF %DYNAMICENEMYID% LSS 0 (
	GOTO :CHOICE
)
CALL :SETSTATICIDS
SET /a NUMTRAINBATTLES=%NUMTRAINBATTLES%+1
SET /a TRAINBATTLE = 1
SET /a SPECIALFIGHT = 0
SET /a GURUBATTLE = 0
CALL "%BATTLERESOURCEPATH%\battle.bat"
GOTO :SELECTENEMYID

:NOENEMIES
ECHO %TRAINERNAME%: You haven't caught any enemies yet. You need to catch some before you can train
ECHO.
GOTO :EOF

:SETSTATICIDS
SET /a COUNT = 0
:LOOPSTART
SET /a COUNT=%COUNT%+1
IF "!ENEMY%COUNT%NAME!" EQU "!DYNAMICENEMY%DYNAMICENEMYID%NAME!" (
	SET /a ENEMYID = %COUNT%
	GOTO :EOF
)
IF %COUNT% LSS %ENEMYTOT% (
	CALL :LOOPSTART
)
GOTO :EOF


:SETLOCATION
IF /I %MAP% EQU town2 (
	SET /a PLAYERXCOORD = 9
	SET /a PLAYERYCOORD = 7
)
GOTO :EOF


:WAITFORZERO
TIMEOUT /T 0 > nul
GOTO :EOF

:WAITFORONE
TIMEOUT /T 1 > nul
GOTO :EOF

:WAITFORTWO
TIMEOUT /T 2 > nul
GOTO :EOF

:WAITFORTHREE
TIMEOUT /T 3 > nul
GOTO :EOF
