:STATUSTURNCOUNTS
SET STATUS=BLIND
CALL :STATUSQUERY
SET STATUS=SILENCE
CALL :STATUSQUERY
SET STATUS=POISON
CALL :STATUSQUERY
SET STATUS=SLOW
CALL :STATUSQUERY
SET STATUS=SLEEP
CALL :STATUSQUERY
SET STATUS=CONFUSION
CALL :STATUSQUERY
SET STATUS=STOP
CALL :STATUSQUERY
SET STATUS=HASTE
CALL :STATUSQUERY
SET STATUS=PROTECT
CALL :STATUSQUERY
SET STATUS=SHELL
CALL :STATUSQUERY
SET STATUS=REFLECT
CALL :STATUSQUERY
SET STATUS=REGEN
CALL :STATUSQUERY
GOTO :EOF


:STATUSQUERY
SET TARGET=PLAYER1
CALL :STATUSCALCULATIONS
SET TARGET=PLAYER2
CALL :STATUSCALCULATIONS
GOTO :EOF

:STATUSCALCULATIONS
IF !%TARGET%%STATUS%! EQU 1 (
	CALL :REDUCETURNCOUNT
) ELSE (
	GOTO :EOF
)
CALL :STATUSACTIVEQUERY
GOTO :EOF

:REDUCETURNCOUNT
IF !%TARGET%%STATUS%TURNCOUNT! GTR 0 (	
	SET /a %TARGET%%STATUS%TURNCOUNT = !%TARGET%%STATUS%TURNCOUNT!-1
)
GOTO :EOF

:STATUSACTIVEQUERY
IF !%TARGET%%STATUS%TURNCOUNT! EQU 0 ( 
	SET /a %TARGET%%STATUS% = 0
)
GOTO :EOF