@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
CALL :INITIALSETUP
CALL :NEWSETUP
CALL :PLAYERSETUP
CALL :ENEMYSETUP
CALL :EXTRAS
CALL :BATTLE
GOTO :EOF

:INITIALSETUP
SET GAMEPATH=C:\Game
SET RESOURCEPATH=%GAMEPATH%\Resources
SET OPTIONSRESOURCEPATH=%RESOURCEPATH%\Options
SET SETUPRESOURCEPATH=%RESOURCEPATH%\Setup
SET INITIALRESOURCEPATH=%SETUPRESOURCEPATH%\Initial
SET NEWRESOURCEPATH=%SETUPRESOURCEPATH%\New
SET DYNAMICRESOURCEPATH=%RESOURCEPATH%\Dynamic
SET BATTLERESOURCEPATH=%RESOURCEPATH%\Battle
SET BATTLEACTIONRESOURCEPATH=%BATTLERESOURCEPATH%\Action
SET BATTLECHOICERESOURCEPATH=%BATTLERESOURCEPATH%\Choice
SET BATTLEDISPLAYRESOURCEPATH=%BATTLERESOURCEPATH%\Display
SET BATTLESTARTRESOURCEPATH=%BATTLERESOURCEPATH%\Start
SET BATTLETURNSTARTRESOURCEPATH=%BATTLERESOURCEPATH%\Turnstart
SET BATTLESTATUSRESOURCEPATH=%BATTLERESOURCEPATH%\Turnstart\Status
SET BATTLEENDRESOURCEPATH=%BATTLERESOURCEPATH%\End
SET CUSTOMSPELLRESOURCEPATH=%RESOURCEPATH%\CustomSpells
SET SKILLRESOURCEPATH=%RESOURCEPATH%\Skills
SET ENEMYSKILLRESOURCEPATH=%RESOURCEPATH%\EnemySkills
SET MISCRESOURCEPATH=%RESOURCEPATH%\Misc

SET MUSICPATH=%GAMEPATH%\Music
SET BATTLEMUSICPATH=%MUSICPATH%\Battle

CALL "%OPTIONSRESOURCEPATH%\options.bat"
CALL "%INITIALRESOURCEPATH%\settabsvars.bat"
ECHO.
ECHO Loading Animations...
CALL "%INITIALRESOURCEPATH%\initialanimationsetup.bat"
::CALL "%INITIALRESOURCEPATH%\characternames.bat"
ECHO.
ECHO Loading Spells...
CALL "%INITIALRESOURCEPATH%\spellstats.bat"
CALL "%INITIALRESOURCEPATH%\limitbreaksetup.bat"
ECHO.
ECHO Loading Skills...
CALL "%INITIALRESOURCEPATH%\skilllist.bat"
CALL "%INITIALRESOURCEPATH%\enemyskilllist.bat"
ECHO.
ECHO Loading Specials...
CALL "%INITIALRESOURCEPATH%\specials.bat"
CALL "%INITIALRESOURCEPATH%\itemlist.bat"
CALL "%INITIALRESOURCEPATH%\specialitemlist.bat"
::CALL "%INITIALRESOURCEPATH%\keyitemlist.bat"
CALL "%INITIALRESOURCEPATH%\weaponstats.bat"
CALL "%INITIALRESOURCEPATH%\armourstats.bat"
CALL "%INITIALRESOURCEPATH%\accessorystats.bat"
CALL "%INITIALRESOURCEPATH%\luckfactors.bat"
CALL "%INITIALRESOURCEPATH%\enemytotals.bat"
ECHO.
ECHO Loading Misc...
CALL "%INITIALRESOURCEPATH%\teleportlocations.bat"
CALL "%INITIALRESOURCEPATH%\misc.bat"
CALL "%INITIALRESOURCEPATH%\enemyanimations.bat"
GOTO :EOF

:NEWSETUP
ECHO.
ECHO Loading New...
SET DIFFICULTY=EASY
CALL "%NEWRESOURCEPATH%\playerinitialstatus.bat"
CALL "%NEWRESOURCEPATH%\playerequipstats.bat"
CALL "%NEWRESOURCEPATH%\playerinitialspecials.bat"
CALL "%NEWRESOURCEPATH%\playerinitialstats.bat"
CALL "%NEWRESOURCEPATH%\playerinitialresistances.bat"
CALL "%NEWRESOURCEPATH%\playerinitialmagic.bat"
CALL "%NEWRESOURCEPATH%\playerinitialskills.bat"
CALL "%NEWRESOURCEPATH%\playerinitialitems.bat"
CALL "%NEWRESOURCEPATH%\playerinitialspecialitems.bat"
::CALL "%NEWRESOURCEPATH%\playerinitialkeyitems.bat"
CALL "%NEWRESOURCEPATH%\playerinitialcaught.bat"
CALL "%NEWRESOURCEPATH%\playerinitialrecords.bat"
CALL "%NEWRESOURCEPATH%\initialqueststats.bat"
::CALL "%NEWRESOURCEPATH%\initialbossstate.bat"
::CALL "%NEWRESOURCEPATH%\playerequiplist.bat"
SET LIMITBREAKBONUSSTAT=STR
GOTO :EOF

:PLAYERSETUP
SET PLAYERNAME=Nick
SET /a PLAYERNAMELENGTH = 4
SET /a PLAYERLVL = 50
SET /a EXP = ((%PLAYERLVL%-1)*200)+50
SET /a PLAYERBASEMAXHP = 4000
SET /a PLAYERHP = 4000
SET /a PLAYERMAXLIMITBREAK = %PLAYERBASEMAXHP%
SET /a PLAYERBASEMAXMP = 200
SET /a PLAYERMP = 200
SET /a PLAYERBASESTR = 25 + %PLAYERLVL%/2
SET /a PLAYERBASEEND = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEMAG = 5 + %PLAYERLVL%/2
SET /a PLAYERBASESPR = 5 + %PLAYERLVL%/2
SET /a PLAYERBASEACC = 10 + %PLAYERLVL%/2
SET /a PLAYERBASEEVA = 5 + %PLAYERLVL%/2
SET /a PLAYERBASESPD = 5 + %PLAYERLVL%/2
SET /a PLAYERBASELCK = 50 + %PLAYERLVL%/2
SET /a BANDITQUESTCOMPLETE = 1
GOTO :EOF

:ENEMYSETUP
::49 is shopkeeper 3. Not actually in the game so I'm using him for testing
SET /a SPECIALFIGHT = 1
SET /a ENEMYID = 49
SET /a ENEMY%ENEMYID%LOADED = 1
CALL "%MISCRESOURCEPATH%\loadenemy.bat"
GOTO :EOF

:EXTRAS
SET /a PLAYERLIMITBREAKACTIVE = 1
SET /a PLAYERLIMITBREAK = %PLAYERMAXLIMITBREAK%
SET /a PLAYERCURAGAENABLED = 1
SET /a PLAYERTHUNDAGAENABLED = 1
SET /a PLAYERFASTAP = 1
SET /a PLAYERDOUBLEAP = 1
SET /a PLAYERFULLAP = 1
SET /a PLAYERDOUBLELIM = 1
SET /a COUNT = 0
:SKILLLOOP
SET /a COUNT = %COUNT% + 1
SET /a PLAYERSKILL%COUNT%ENABLED = 1
IF %COUNT% LSS %SKILLTOT% (
	GOTO :SKILLLOOP
)
GOTO :EOF


:BATTLE
SET /a TRAINBATTLE = 0
SET /a GURUBATTLE = 0
CALL "%BATTLERESOURCEPATH%\battle.bat"
GOTO :EOF