CALL "%BATTLERESOURCEPATH%\ranresources.bat"
CALL :%EQUATION%
GOTO :EOF


:ATTACKMISS
SET /a MISSVAR = !%ATTACKER%ACC!*80/!%DEFENDER%EVA!
GOTO :EOF

:ATTACKDAM
SET /a DAM=(((((!%ATTACKER%STR!*5)+!%ATTACKER%LVL!)/((!%DEFENDER%END!*3)+!%DEFENDER%LVL!)*(!%ATTACKER%STR!+5)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)*100)*%RANFACT%)/10000
GOTO :EOF

:SPELLMISS
IF !%ATTACKER%SPELLEFFECT%EFFECT1%TARGET! EQU DEFENDER (
	SET /a MISSCHANCE = !%ATTACKER%ACC!*80*!%ATTACKER%SPELLACCURACY!/100/!%DEFENDER%EVA!
) ELSE (
	SET /a MISSCHANCE = !%ATTACKER%ACC!*80*!%ATTACKER%SPELLACCURACY!/100/!%ATTACKER%LVL!
)
GOTO :EOF

:SPELLDAM
IF !%ATTACKER%SPELLEFFECT%EFFECTNUM%TARGET! EQU DEFENDER (
	CALL :SETAMOUNT1
) ELSE (
	CALL :SETAMOUNT2
)
:SETAMOUNT1
SET /a TEMPAMOUNT = (((((!%ATTACKER%MAG!*%TEMPAMOUNT2%)+!%ATTACKER%LVL!)/((!%DEFENDER%SPR!*3)+!%DEFENDER%LVL!)*(!%ATTACKER%MAG!+%TEMPAMOUNT2%)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)*100)*%RANFACT%)/10000
GOTO :EOF
:SETAMOUNT2
SET /a TEMPAMOUNT = !%ATTACKER%MAG!*!TEMPAMOUNT2!*%RANFACT%/300
GOTO :EOF

:ITEMS
SET /a ITEMEFFECT%EFFECTNUM%TEMPAMOUNT = -(((((!%ATTACKER%MAG!*%TEMPAMOUNT%)+!%ATTACKER%LVL!)/((!%DEFENDER%SPR!*3)+!%DEFENDER%LVL!)*(!%ATTACKER%MAG!+%TEMPAMOUNT%)*!%ATTACKER%LVL!/!%DEFENDER%LVL!)*100)*%RANFACT%)/10000
GOTO :EOF

:LEEROYDAM
IF /I %DIFFICULTY% EQU EASY (
	SET /a TEMP = 5
) ELSE IF /I %DIFFICULTY% EQU HARD (
	SET /a TEMP = 10
)
SET /a DAM = (%ENEMYHP%*%RANFACT%)/(%TEMP%*100)
GOTO :EOF